### PR TITLE
feat(dropdown): introduce narrow version

### PR DESCRIPTION
**Pull request by asudoh**
Fixes IBM/carbon-components-react#1209.

Requires review by: @IBM/carbon-designers

Anybody - Feel free to suggest the naming!

#### Changelog

**New**

- `bx--dropdown--narrow` CSS class for `width:auto` (Update: Changed it to `bx--dropdown--auto-width`)

#### Testing / Reviewing

Testing should make sure dropdown is not broken.

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
LGTM! Would be good to update the `README.md` file for Dropdown to add this new class name.

**Comment by aagonzales** [comment]
@asudoh can you spin up a code pen or something with a preview to review. (I'm still not great at pulling things down locally)

**Comment by alisonjoseph** [comment]
Hi @aagonzales here is a codepen. https://codepen.io/alisonjoseph/pen/QVmdKx

this doesn't actually change the styling at all, just allow the width of the dropdown to be equal to the width of the content inside it instead of being 100% width of the container. Does that make sense?

**Comment by alisonjoseph** [comment]
On second thought @asudoh I'm not sure the class name `dropdown--narrow` is the best word for this. 

what about `dropdown--auto` `dropdown--auto-width` 🤔 hmm

**Comment by asudoh** [comment]
Thank you for your help creating the CodePen! I like the idea of `auto-width` and made a change as such with an update to `README.md`.

**Review by joshblack — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
