### PR TITLE
refactor(popover): update <div> to <span>

### PR DESCRIPTION
**Pull request by joshblack**
This PR refactors our popover to use `<span>` instead of `<div>` so that popovers may be used in inline tags like `<p>` for components like `DefinitionTooltip`. It also adds in an e2e test for VRT.

#### Changelog

**New**

- Add e2e test for Popover

**Changed**

- Change all tags to `<span>` for Popover

**Removed**

#### Testing / Reviewing

- Verify Percy has picked up the new VRT for Popover
- Verify Popover still renders as expected across browsers

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]
LGTM. Popover is working as expected. 👍🏽

**Comment by jnm2377** [comment]
oh, just noticed Percy shows a change in the snapshot, but I can't actually tell what has changed... 🤔 It looks right to me..

**Review by aledavila — APPROVED** [review]
lgtm. Percy just says new snapshot not even a changed one

**Review by dakahn — APPROVED** [review]
Nice! Good ol reliable spans to the rescue 👍🏾

**Pull request merged**
