### PR TITLE
feat(data-table): add data-table paths and aliases

### LINKED ISSUE #2295: DataTable: Still using v2 file names
We need to create new files without the v2 name to use as the default location of the datatable styles. We can maintain the v2 files with a reference to the correct files and a warning for backwards compatibility throughout this release.

### PR DESCRIPTION
**Pull request by joshblack**
Closes #2295

Add `data-table` folder and appropriate aliases for JS and SCSS files. This diff does *not* include the deprecation warning for `data-table-v2`, we should discuss that strategy and implement in another PR most likely 👍 

#### Changelog

**New**

- content in `data-table-v2` now lives under `data-table`

**Changed**

- `data-table-v2` now points to `data-table`
- Update style entrypoint to reference `data-table`
- Update JS entrypoint to reference `DataTable`
- Update data table spec

**Removed**

### CODE REVIEW

**Comment by elizabethsjudd** [comment]
@joshblack isn't this a breaking change for any one referencing your component on a per-component basis?

**Review by asudoh — COMMENTED** [review]
Thanks @joshblack for doing this! LGTM basically, one thing I found in the Netlify link is that some Fractal configurations need some updates, likely:

* For old directory - Add Fractal configuration just with `hidden: true`, like [one for floating menu](https://github.com/IBM/carbon-components/blob/v10.0.0/src/components/floating-menu/floating-menu.config.js)
* For new directory - Update the component name (removing `v2`)

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack for your quick update!

**Comment by joshblack** [comment]
v6 published using the v6 branch at: http://v6-react.carbondesignsystem.com

**Review by vpicone — APPROVED** [review]

**Pull request merged**
