### PR TITLE
feat(icons): updated and new model icons

### PR DESCRIPTION
**Pull request by conradennis**
Submitting new and updated `model` UI icons as requested by @mjabbink [here](https://github.ibm.com/brand/ui-icons/issues/345). All updates and additions approved by BXD

2 net new icons
4 updated icons
1 deprecated icon

updated categories.yml with additions
updated icons.yml with additions
updated deprecated.yml with additions

#### Changelog

**New**

- 32/ml-model--reference.svg
- 32/model--foundation.svg

**Changed**

- 32/model.svg
- 32/model--reference.svg
- 32/model--tuned.svg
- 32/machine-learning-model.svg

**Deprecated**

- 32/machine-learning.svg

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
Looks good to me  ⭐️

**Review by ariellalgilmore — APPROVED** [review]

**Review by kennylam — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Comment by mjabbink** [comment]
@conradennis @laurenmrice @tay1orjones It looks like `foundation-model` icon is not appearing in the Carbon UI icon library but I see it in the preview. Also, the icon library is not in synch wit the Carbon one. 

Screenshot 2024-09-12 at 4 28 58 PM

**Comment by mjabbink** [comment]
Several M2W3 product teams are using these right now and missing now. Can you all look into this and resolve as soon as you can. Much thanks

**Comment by mjabbink** [comment]
and `model` is missing

image

**Comment by mjabbink** [comment]
oh, I see it in the site library, but it’s missing in the deploy preview. Seems to be in there so scratch the above entry on missing `model` icon

**Pull request merged**
