### PR TITLE
feat(Tokens): add expressive tokens

### LINKED ISSUE #8299: Add type tokens for expressive reading experience
### Summary

"Carbon expressive theme" was originally conceived based on the assumption that majority of the experience on IBM.com is for long form reading and/or based on a marketing intent. This has proven to be not true over the last 2 years. We need productive experiences in the global masthead mega menu, IBM.com search, commerce, product configuration, search/filter on catalogs, and many more places. The common occurrence of productive experience (14px type size, and compact components such as tabs and checkboxes) too often for the approach of "expressive theme" to make sense. 

The proposal is **add a handful of tokens and expressive components to Carbon 10, and deprecate "expressive theme"**. Moving forward, Carbon for IBM.com would like to depend on Carbon core, and focus on delivering unique components that's needed by IBM.com on top of leveraging the full offering of Carbon Design System. 

### Add expressive type tokens
- Letter spacing unchanged: `Letter-spacing: .16px`

| Token name | Value |
| --- | --- | 
| `caption-02` | 14px type size, 18px line height | 
| `label-02` | 14px type size, 18px line height | 
| `helper-text-02` | 14px type size, 18px line height | 

### Additional notes
- Someone did complain about the 12px label a long time ago, and Mike was interested in a variant that allowed for 14 label, 14 form. Not sure if it ever went anywhere. 
- This ask is not to update existing components with the new tokens. Just to add the new tokens.

### PR DESCRIPTION
**Pull request by dakahn**
Closes #8299 

adds expressive type tokens; 
- `caption-02`
- `label-02`
- `helper-text-02`

#### Changelog

**Changed**

- add expressive tokens to packages/type/scss/_styles.scss
- add expressive tokens to packages/type/src/styles.js
- add expressive tokens to packages/type/src/tokens.js

### CODE REVIEW

**Comment by dakahn** [comment]
Hmmm -- CI failing with `unkown primitive...` exception. 😕

**Comment by joshblack** [comment]
@dakahn just pushed up a quick update, the values were missing from the theme so when the "builder" was generating the files it couldn't find the value of the token in the theme.

**Review by joshblack — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
looks like snapshots need to be updated to pass CI

**Review by shixiedesign — APPROVED** [review]
Looks good in the preview! Thank you!!

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
