### PR TITLE
feat(modal): support alertdialog aria role

### LINKED ISSUE #5960: The React implementation of the Modal component should support role="alertdialog"
## Detailed description

[WAI-ARIA 1.1 describes an alertdialog](https://www.w3.org/TR/wai-aria-1.1/#alertdialog) role. To quote: 

> Dialogs are most often used to prompt the user to enter or respond to information. **A dialog that is designed to interrupt workflow is usually modal. See related alertdialog.**

Carbon already supports the `danger={true}` prop which, in my opinion, should go hand in hand with an `alert` prop that changes the `role` of the modal from `dialog` to `alertdialog`. 

When an `alertdialog` role is set, assistive technology can announce the contents of the dialog upon being displayed, much like the contents of a `role="alert"` element are announced. This is desirable for dialogs that should interrupt workflow (see the ARIA description above).

It is also important that the WAI-ARIA guidelines state that a role="alertdialog" element should be supplied with an `aria-label` or `aria-labelledby` attribute as well as an `aria-describedby` attribute. The former is already taken care of by the Modal component, but an `aria-describedby` attribute should be added for alertdialogs that should point to the body text of the modal (i.e. the element that contains the props.children).

### PR DESCRIPTION
**Pull request by FrivalszkyP**
Closes #5960 

There is an [alertdialog](https://www.w3.org/TR/wai-aria-1.1/#alertdialog) role in ARIA which is described as this: 

> Dialogs are most often used to prompt the user to enter or respond to information. A dialog that is designed to interrupt workflow is usually modal. 

Much like role="alert", it will be read out by screen reader software immediately when displayed. 

#### Changelog

**New**

- Added the `alert` prop to the react implementation of Modal.js
- Added a unit test covering it

#### Testing / Reviewing

See Carbon React Storybook where I added a knob for controlling the alert prop.

### CODE REVIEW

**Comment by FrivalszkyP** [comment]
My decision behind adding a new prop to control this behavior was that, although `role="alertdialog"` is closely related to `danger`, I assume there could be cases where a dialog has the `alert=true` prop but not the `danger=true` prop. Also, I did not want to introduce a breaking change for developers who already implemented a workaround for the lack of control of the role attribute.

**Review by emyarod — COMMENTED** [review]
this looks good to me, but is there a ticket associated with this PR? just trying to get some additional context for this change

**Comment by FrivalszkyP** [comment]
> this looks good to me, but is there a ticket associated with this PR? just trying to get some additional context for this change

Sorry, I completely glanced over the note in the guidelines that I should have created an issue. I can create one to provide some example codes.

**Comment by FrivalszkyP** [comment]
@emyarod Added the issue and referenced it in my PR description! See here #5960 

Hope I was able to provide enough context!

**Review by asudoh — COMMENTED** [review]
Hi @FrivalszkyP thank you for jumping in! After comparing the purpose of `alertdialog` role and [our modal usage guide](https://www.carbondesignsystem.com/components/modal/usage), I'm inclined to believe that the `alertdialog` should be applied to all `passiveModal` variants. What do you think?

**Comment by dakahn** [comment]
@asudoh the attritbute `role="alertdialog"` should only be applied to dialogs [that require the user to respond somehow](https://w3c.github.io/aria-practices/#alertdialog) (like with a confirmation or some other interaction). Our "passive" modals should just be `role="alert"`

**Review by dakahn — CHANGES_REQUESTED** [review]
We may need to distinguish passive or active modals here. With passive modals not needing a users response simply being `role="alert"` and active modals requiring a response being `role="alertdialog"` since there is this distinction in our design guidance.

https://www.digitala11y.com/alertdialog-role/

**Comment by FrivalszkyP** [comment]
@dakahn Good call, do you suggest changing the role to `alert` in case `passiveModal` and `alert` are both `true`?

**Comment by FrivalszkyP** [comment]
Thanks! I updated the PR with the role="alert" functionality.

**Review by dakahn — APPROVED** [review]
Looks good! Thanks a lot for taking this on. :surfer:

**Review by tw15egan — APPROVED** [review]
LGTM as well, thanks for adding! 👍 ✅

**Pull request merged**
