### PR TITLE
fix(list-box): remove order property for flex layout

### LINKED ISSUE #1891: List-box `order` attribute breaks layout
## List-box `order` attribute breaks layout:
The bx--list-box styling contains 'order: 1', which breaks the intended order defined in the HTML.

List-box components will always be at the end of flex-box layouts (if no order is defined on other parts)
Code:
image
Result:
image

> Is this issue related to a specific component?
Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?
That the order is not predefined and positions as the HTML structures
Based on the sample before, this:
image

> What browser are you working in?
Chrome 72.0.3626.109, FireFox 60.5.2esr

> What version of the Carbon Design System are you using?
9.76.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
None

## Steps to reproduce the issue
1. Create a flex-box row layout
2. Place a dropdown and a button in there
3. Dropdown will be displayed 

https://codesandbox.io/s/ol6v556qo5

### PR DESCRIPTION
**Pull request by joshblack**
Closes #1891

#### Changelog

**New**

**Changed**

**Removed**

- `order` property for `list-box`

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Would you recall what the `order` property here was for? Thanks @joshblack!

**Comment by joshblack** [comment]
Looking at blame, seems like it was added in our light input fields pass. cc @alisonjoseph have any ideas? Might have just been for demo purposes?

**Review by dakahn — APPROVED** [review]
Looks cool!

**Review by tw15egan — APPROVED** [review]
Pretty sure it was when we did highlighting on the labels when the inputs were focused. Seems like a leftover legacy style that can be safely removed

**Pull request merged**
