### PR TITLE
feat(DataTable): Update DataTable to phase 2 spec

### LINKED ISSUE #15708: Update React `DataTable` to phase 2 AI spec

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15708

Updates the `DataTable` with `Slug` to the new phase 2 styles. It also adds support for the full-column gradient.

#### Changelog

**New**

- `$ai-aura-start-table` token,  slightly more opaque than `$ai-aura-start`
- `getCellProps` prop getter added to `TableCell` to check if a cell is in a column that has a `Slug` in the header
- `ai-table-gradient` mixin to specify the `DataTable` specific gradients

**Changed**

- Converted `TableCell` to a component, rather than using `wrapComponent` function
- `slug` can now be provided the `DataTableHeader`, e.g. you would define your headers (with a slug) like so:
```jsx
const columnSlugHeaders = [
  {
    key: 'name',
    header: 'Name',
  },
...
  {
    key: 'attached_groups',
    header: 'Attached groups',
    slug: MySlugComponent
  },
];
```

#### Testing / Reviewing

Go to `Experiemental --> unstable__slug --> DataTable` and ensure all variants match the spec. Ensure there are no regressions to the main `DataTable`

### CODE REVIEW

**Review by guidari — APPROVED** [review]
LGTM! 🚀

**Review by tay1orjones — APPROVED** [review]

**Comment by tay1orjones** [comment]
@aagonzales just need a visual pass on this one, looks good to go on the dev side

**Review by aagonzales — COMMENTED** [review]
It looks good! But can we move this slug over to the right in the header in the story "column slug with expansion and selection"

Also the hover colors in all the themes seems a little too intense/bright compared to the design. Would adding that extra stop in the gradient help with this? 

image

**Review by aagonzales — APPROVED** [review]
Reviewed it with TJ, looks good to go now! 🎉 ✅

**Pull request merged**
