### PR TITLE
fix(radiobutton): shows helper text

### PR DESCRIPTION
**Pull request by aledavila**
Helper text wasn't showing up in Radio Group

### CODE REVIEW

**Comment by aledavila** [comment]
Hey @francinelucca here's the fix for the helper text. You can lose out your PR if need be I added the helper id that you added in your PR if this is blocking you and we can work off of this. If you are getting an error it may also be cause the helper text is outside of the fieldset. I have a fix for that as well locally that I can push up instead.

**Review by francinelucca — APPROVED** [review]
LGTM!

**Review by andreancardona — APPROVED** [review]
looks good!

**Comment by tay1orjones** [comment]
@aledavila there's a conflict on this one

**Comment by aledavila** [comment]
updated @tay1orjones

**Pull request merged**
