### PR TITLE
feat(tabs): take out fade from scroll button

### PR DESCRIPTION
**Pull request by divya-281**
Closes #

It fixes these two issues from the issue #15961 

Screenshot 2024-05-20 at 7 04 19 PM

Screenshot 2024-05-20 at 7 04 44 PM

#### Changelog

**Changed**
Left scroll button:
Screenshot 2024-05-20 at 7 05 26 PM

Right scroll button:
Screenshot 2024-05-20 at 7 05 09 PM

The disabled token is already apprearing here:
Screenshot 2024-05-20 at 6 18 23 PM

#### Testing / Reviewing

Start story book with `yarn storybook`
Narrow your screen so that the scrollable button is visible

### CODE REVIEW

**Review by tay1orjones — CHANGES_REQUESTED** [review]
There is a small gap on the left scroll button that allows you to see the text when you shouldn't be able to.

https://github.com/carbon-design-system/carbon/assets/3360588/de468a71-328a-4b1e-a7bb-3023d93334bc

This might be able to be resolved by updating with the latest from `main`, but there are conflicts that need to be resolved.

**Review by kingtraceyj — CHANGES_REQUESTED** [review]
I'm seeing a non-transparent background on the default tabs, but I know that there are [open issues](https://github.com/carbon-design-system/carbon/issues/15924) about this:
image

We should keep the fade on the default tabs and only take the fade out on contained tabs only.

Since the disabled border token is higher contrast, let's update the `$border-disabled` to `$border-subtle` in the default tabs.

**Comment by divya-281** [comment]
> There is a small gap on the left scroll button that allows you to see the text when you shouldn't be able to.
> 
>  CleanShot.2024-06-17.at.11.41.24.mp4 
> This might be able to be resolved by updating with the latest from `main`, but there are conflicts that need to be resolved.

Hi @tay1orjones I have rebased and resolved all conflicts

**Comment by divya-281** [comment]
> I'm seeing a non-transparent background on the default tabs, but I know that there are [open issues](https://github.com/carbon-design-system/carbon/issues/15924) about this: image
> 
> We should keep the fade on the default tabs and only take the fade out on contained tabs only.
> 
> Since the disabled border token is higher contrast, let's update the `$border-disabled` to `$border-subtle` in the default tabs.

Hey @kingtraceyj 
In the issue It is mentioned that the 
>"Disabled border token in default line tabs should be $border-disabled
Current looks like a higher contrast than $border-subtle"

So could you confirm if I need to change the colour to $border-subtle?

**Comment by tay1orjones** [comment]
@divya-281 could you try out this idea for a fix and see if we could fix the transparent left button issue in this PR? https://github.com/carbon-design-system/carbon/issues/15924#issuecomment-2052231667

**Comment by divya-281** [comment]
> @divya-281 could you try out this idea for a fix and see if we could fix the transparent left button issue in this PR? [#15924 (comment)](https://github.com/carbon-design-system/carbon/issues/15924#issuecomment-2052231667)

Hi @tay1orjones  I added this suggestion also

**Comment by tay1orjones** [comment]
@divya-281 looks good, but the border token still needs updated

**Comment by divya-281** [comment]
> @divya-281 looks good, but the border token still needs updated

Hi @tay1orjones This is how the disabled tabs look like with $border-subtle
Screenshot 2024-08-06 at 8 21 31 PM

**Comment by tay1orjones** [comment]
@laurenmrice could you do a visual review on this?

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Hi @divya-281 Thank you for working on this. It is looking really good and almost there. ⭐️

The only bug I saw is that when the Line tabs show the disabled state on the last tab (called "Settings"). That tab should have a 2px stroke underline to match the other tab underline strokes. Right now it is at 1 px and its too small.

Screenshot 2024-08-07 at 8 44 39 AM

**Review by kingtraceyj — CHANGES_REQUESTED** [review]
it's looking good except one tiny change. the disabled border should be 2px. it looks like it's a 1px right now.

**Review by kingtraceyj — CHANGES_REQUESTED** [review]
is there a way to keep the overflow gradient on the default/line tabs? the contained tabs should not have the gradient but the default/line tabs should. thank you!

**Review by kingtraceyj — CHANGES_REQUESTED** [review]
@divya-281 it looks like the dafault tabs are right but the contained tabs now have the gradient: 
image

**Comment by divya-281** [comment]
@kingtraceyj @tay1orjones I have made the changes, Could you please review.

**Review by aagonzales — COMMENTED** [review]
Ok the problems previously mentioned look resolved but I noticed some things. The 1px gap between the default line tabs disappears as the container shrinks down. (Kind of hard to see the gif) 

Sep-26-2024 14-59-09

image

The arrow button seems to be a bit delayed in disappearing when dragging the browser back out. Not sure if others are seeing this too. 

Sep-26-2024 15-05-23

**Comment by divya-281** [comment]
Hi @tay1orjones these issues already exist in product I can work on it on another PR if that's okay

**Review by tay1orjones — APPROVED** [review]
Yeah those are existing issues not related to this PR. @divya-281 could you open up a new issue outlining those issues?

**Comment by divya-281** [comment]
Hi @tay1orjones  @aagonzales  I have created an [issue](https://github.com/carbon-design-system/carbon/issues/17648) for this

**Review by aagonzales — APPROVED** [review]
Ok, ignoring those other issues this PR looks good. The fade looks properly removed.

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
