### PR TITLE
fix(select): remove transition on background-color to avoid jumping in Firefox

### LINKED ISSUE #4464: [Pagination]: Incorrect hover trigger causes jank
### Hovering issue
screen

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4464 

Firefox appears to jump when you add transition on background-color, and then change the background-color on hover: https://codepen.io/jendowns/pen/VwwzmBd

#### Changelog

**New**

- remove transition on background-color to avoid jumping seen in #4464 

#### Testing

In Firefox, compare the `Pagination` or the inline `Select` component in the `carbon-components-react` PR deployment with what's currently on http://react.carbondesignsystem.com/?path=/story/pagination--pagination

### CODE REVIEW

**Comment by jendowns** [comment]
@vpicone Can you verify that this works on your end? With the `background-color`, I can no longer see the jumping & honestly I'm... shocked 😆 

UPDATE: I now have a general notion what's going on now... replicated it here: https://codepen.io/jendowns/pen/VwwzmBd

**Review by emyarod — COMMENTED** [review]
this looks related to Firefox `<select>` resizing/overflow, but I haven't been able to look into it yet. have you been able to identify the cause of the issue? the size of the `<select>` element and options is smaller with the `background-color` rule. it may be worth checking if this bug occurs on other OSes as well

**Comment by jendowns** [comment]
@emyarod Here's what I know:

* in Firefox when you see the "jumping", you can see the top/bottom space that keeps getting added/removed are a different color -- it's easier to notice on the bottom space (that's why I tried changing the background color in the first place)
* Yes the options here appear "smaller" in Firefox now with the `background-color` rule, but that's because that top/bottom space that was getting added/removed & the jumping is no longer there. It's the same look as the regular `Select`: http://react.carbondesignsystem.com/?path=/story/select--default
* this doesn't appear to happen to Safari or Chrome, without or without the `background-color` rule applied (I can't check IE 11 or Edge currently because I'm using a loaner macbook without Parallels setup)

So I'm not 100% clear on the cause, but I would caution against thinking of a resizing/reflow problem as not related to certain CSS rules... (for example, there's a bug we had to workaround recently related to WebKit (Safari) crashing when you add `text-rendering: optimizeLegibility` & tried to open a select element.

**Comment by emyarod** [comment]
yeah the issue exists in the standalone inline select so it's worth investigating the cause of the issue rather than just applying a bandaid fix to pagination. I am leaning towards this being Firefox specific given that this does not appear in webkit browsers and since we have some styles that target the FF user agent, but I haven't been able to look closely at the issue yet. I'm not ruling user agent styles (or our styles) out as the cause of the issue

**Comment by jendowns** [comment]
Okay thanks @emyarod I'll move the `background-color` "bandaid" up to the select styles for now.

**Comment by emyarod** [comment]
I'm not sure if it'll be the same given the transparent background color on inline select but let me know what you find

**Comment by jendowns** [comment]
@emyarod Found it -- check out this CodePen:

https://codepen.io/jendowns/pen/VwwzmBd

It's the combo of the following:

* ~`background-color: transparent`~ actually this part doesn't seem necessary to replicate the issue
* transition to `background-color` applied
* on hover, `background-color: something-else`

It looks like it *can* be avoided by setting a background color (not `transparent`) on the select input but let me know if you want another approach (like *also* removing the transition for the background color) 🤔 

I can't find anything bug-related for Firefox about this yet but I have seen several StackOverflow answers referencing the fact that Firefox, unlike other browsers, sets a background color on it's `select` element. So maybe when you set ~`background-color: transparent`~ a non-transparent `background-color` when using a `background-color` transition with a color change on hover, it's messing something up in Firefox...

**Comment by jendowns** [comment]
🤷 I opened an issue here btw: https://bugzilla.mozilla.org/show_bug.cgi?id=1591978

**Comment by jendowns** [comment]
I went ahead and updated this PR to just straight up remove the transition on the background color but keep the transparent background color on inline `Select`s. 🤔

**Review by jnm2377 — APPROVED** [review]
LGTM. Seems like the best fix. 👍

**Review by jillianhowarth — APPROVED** [review]

**Comment by asudoh** [comment]
@emyarod Does @jendowns' latest code look good here...? Thanks!

**Review by emyarod — APPROVED** [review]
looks good to me, interested in seeing how Mozilla handles the issue

**Pull request merged**
