### PR TITLE
chore: update codeowners

### PR DESCRIPTION
**Pull request by alisonjoseph**
Updates codeowners to reference `developers-system` team

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Comment by joshblack** [comment]
@alisonjoseph would we want to structure it like:

Teams:
- System
  - Developers
  - Designers
- Website
  - Developers
  - Designers

**Comment by alisonjoseph** [comment]
We would have to name it `system-developers` I think, I tried making a sub-team called developers and it just moved the main one underneath system. Lets wait and sync with design on how they plan on working within the squads first. (meeting w/ Anna/Jeanne tomorrow morning)

**Comment by joshblack** [comment]
Ah, got it. Would it instead be this structure that would be valid?

- System
  - System - Designers
  - System - Developers

**Comment by alisonjoseph** [comment]
Yep 👍

**Review by joshblack — APPROVED** [review]

**Pull request merged**
