### PR TITLE
fix: bottom padding and overflow scroll for multi line snippet

### PR DESCRIPTION
**Pull request by jnm2377**
Fixes overflow bugs when text is too long and can't be seen behind button.
 
cc: @designertyler @shixiedesign

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
LGTM from dev side 👍

**Review by designertyler — APPROVED** [review]
lgtm

**Comment by designertyler** [comment]
@alisonjoseph sorry, I accidentally re-requested your review instead of mine and not sure how to get it back!

I just found that we were getting a 1px white inner border on focus

Screen Shot 2019-03-15 at 3 55 00 PM

**Review by asudoh — CHANGES_REQUESTED** [review]
@designertyler Do we want to go through this PR or do you want to wait for the white border issue getting fixed? Let me add a read mark meanwhile so nobody accidentally hit "merge" button. Thanks! (And @jnm2377 for the fix!)

**Review by shixiedesign — APPROVED** [review]
- [ ] White inside focus border should be fixed. 
This one is a little hard to inspect because there's no default max-height to cause any scrolling. But I think I've seen it on your computer and it looked good!

**Review by asudoh — APPROVED** [review]
:+1: according to the design review - Thanks @jnm2377!

**Pull request merged**
