### PR TITLE
fix(Modal): edit close icon alt text to match content guidelines

### LINKED ISSUE #5639: Modal close button text says "close the modal" instead of "Close"
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The default hover text for the Close button in a modal says "close the modal". 

https://github.com/carbon-design-system/carbon/blob/12c17f126e620db5a6cb2342d8fcb87159037137/packages/react/src/components/Modal/Modal.js#L172

image

> Is this issue related to a specific component?

Modal. Might affect other components with the same close button.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The default hover text should just be "Close" according to the Carbon action labels: https://www.carbondesignsystem.com/guidelines/content/action-labels/#C

> What browser are you working in?

All

> What version of the Carbon Design System are you using?

9, 10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud platform (public)

@cdmauney Just an FYI since we've discussed in the past

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5639

This PR changes the modal close icon alt text to match the content guidelines on our website

### CODE REVIEW

**Review by connor-leech — APPROVED** [review]
Fantastic, thank you!

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Review by joshblack — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by asudoh** [comment]
@emyarod thanks this is ready to merge - Thanks @emyarod!

**Pull request merged**
