### PR TITLE
feat: icons-new-january-february

### PR DESCRIPTION
**Pull request by conradennis**
Submitting new and updated UI icons from January + February
all updates and additions approved by BXD

36 net new icons
1 removed icon (approved by Brand + Legal team, see Carbon issue: https://github.com/carbon-design-system/carbon/issues/5153)

updated categories.yml with additions and updates
updated ui-icon-master.ai with additions and updates

#### Changelog

**New**

- 32/watson-health/download-study.svg
- 32/watson-health/hole-filling.svg
- 32/watson-health/hole-filling--cursor.svg
- 32/watson-health/smoothing.svg
- 32/watson-health/smoothing--cursor.svg
- 32/center--circle.svg
- 32/center--square.svg
- 32/circle--filled.svg
- 32/covariate.svg
- 32/data-refinery.svg
- 32/data-table.svg
- 32/document--download.svg
- 32/document--pdf.svg
- 32/document--view.svg
- 32/double-integer.svg
- 32/email--new.svg
- 32/factor.svg
- 32/fetch-upload.svg
- 32/fetch-upload--cloud.svg
- 32/generate-pdf.svg
- 32/graphical-data-flow.svg
- 32/hashtag.svg
- 32/in-progress.svg
- 32/logo--jupyter.svg
- 32/logo--python.svg
- 32/logo--r-script.svg
- 32/model-builder.svg
- 32/operations--field.svg
- 32/operations--record.svg
- 32/save--model.svg
- 32/script.svg
- 32/string-integer.svg
- 32/string-text.svg
- 32/sys-provision.svg
- 32/task--view.svg
- 32/user--speaker.svg

**Removed**

- 32/logo--google.svg

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Seems good to me, will make sure to help scaffold out metadata either tomorrow or early next week!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
For `32/circle--filled.svg`, this needs to be a completely filled in circle to be able to be used in the progress indicator component for the `current state`. We need to omit the space between the border and the fill.

Ex:
Screen Shot 2020-02-14 at 9 11 44 AM

Everything else looks good to me 👍🏻

**Comment by conradennis** [comment]
> For `32/circle--filled.svg`, this needs to be a completely filled in circle to be able to be used in the progress indicator component for the `current state`. We need to omit the space between the border and the fill.
> 
> Ex:
> Screen Shot 2020-02-14 at 9 11 44 AM
> 
> Everything else looks good to me 👍🏻

Hey @laurenmrice I originally made it as you specified above but then @jeanservaas slacked me a few days later and mentioned her and Mike decided there should be a space between fill and outer stroke.

**Comment by laurenmrice** [comment]
Thanks for clarifying Conrad! Just spoke with jeannie, are you using a 3px gap between the border and the fill? They want a 2px gap, so just wanted to confirm that.

**Comment by conradennis** [comment]
> Thanks for clarifying Conrad! Just spoke with jeannie, are you using a 3px gap between the border and the fill? They want a 2px gap, so just wanted to confirm that.

ya we originally agreed on 3px, seems like that's too close to radio button so 2px it is. Will update the icon and the PR in a mo

**Review by laurenmrice — APPROVED** [review]
looks great ! thanks for making that fix ! 🚀

**Review by dakahn — APPROVED** [review]

**Comment by joshblack** [comment]
~Quick update, waiting on metadata updates over in: https://github.com/carbon-design-system/carbon/pull/5372~ Done!

**Pull request merged**
