### PR TITLE
fix(multi-select): match experimental spec

### LINKED ISSUE #2187: Match multi select to experimental spec
Depends on listbox and required for `carbon-components-react`

#2167 

https://github.com/IBM/carbon-components/pull/2181

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2187

This PR updates the experimental multi-select component to align with the v10 spec

related: #2206 

#### Changelog

**New**

- v10 multiselect (based on v10 listbox)

**Changed**

- extend docs example to test text overflow
- correct aria attributes in docs

**Removed**

- legacy multi-select styles

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Changes:**
- [ ] There is a light gray rule that is flush against the darker gray rule of the label. it needs to be removed.
Screen Shot 2019-03-26 at 1 40 00 PM

- [x] When an option is selected in the dropdown, the text color needs to change to be persistently at `text-01`.

- [x] The tag needs to be calling `inverse-02` color token and the hover oval for the close icon should be color #4C4C4C.

- [ ] During focus for both multi-select and inline: there is a rule under the focus border of the label that needs to be omitted.
Screen Shot 2019-03-26 at 2 02 48 PM


Inline dropdown:

- [ ] The drawer is currently not getting a background. Also make sure the divider rules in the dropdown have 16px padding on both sides.
Screen Shot 2019-03-26 at 2 08 48 PM

- [x] There needs to be only 8px from the left from the focus border.
Screen Shot 2019-03-26 at 2 03 45 PM

**Comment by emyarod** [comment]
>There is a light gray rule that is flush against the darker gray rule of the label. it needs to be removed

>During focus for both multi-select and inline: there is a rule under the focus border of the label that needs to be omitted.

this should be resolved in https://github.com/IBM/carbon-components/pull/2212, which https://github.com/IBM/carbon-components-react/pull/2093 is also depending on

> The drawer is currently not getting a background. Also make sure the divider rules in the dropdown have 16px padding on both sides.

as we discussed, we will no longer be making that change for now

**Comment by asudoh** [comment]
@shinytoyrobots @alisonjoseph Fix seems well contained - Are you good with putting this into `v10`? Thanks!

**Comment by alisonjoseph** [comment]
Issues all seem to be addressed except the two issues unrelated to this PR, is this ok to merge @laurenmrice

**Review by laurenmrice — APPROVED** [review]
Yes looks good 👍

**Pull request merged**
