### PR TITLE
fix(accordion-button-outline): remove ::before from hover and focus

### LINKED ISSUE #8645: Accordion - iPad VoiceOver won't read full content
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description
When using iPad voiceOver to read accordion content, sometimes the voiceOver will not read the full content.
It is unstable, sometimes it reads full content, and sometimes it doesn't.

**Here is my finding:**
The cause of this issue is we have pseudo element for `bx--accordion-heading` button which confuses the screen reader.

```
bx--accordion__heading {
&:focus::before {
    content: '';
  }
}
```

**Here is my fix:**
```
bx--accordion__heading {
&:focus::before {
    content: none;
  }
}
```

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by linzhaoken**
Closes #8645 

{{short description}}

#### Changelog

**Changed**

- Use outline for accordion button focus

**Removed**

- Remove `::before` from accordion button style

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Review by tay1orjones — COMMENTED** [review]
Thanks for the PR! This introduces a small visual difference in the focus that we'll need to fix and/or review with @carbon-design-system/design. The top/bottom gray borders are visible on a focused item:

Screen Shot 2021-05-11 at 11 34 07 AM

Production:
Screen Shot 2021-05-11 at 11 34 18 AM

**Comment by tw15egan** [comment]
The linked issue seems to propose a different solution, does changing `content: '';` to `content: none` not fix the issue?

**Comment by linzhaoken** [comment]
@tw15egan yes the proposed solution will fix the voiceover issue but I realize that it also removes the `focus` style as well. So instead of just change to `content: none` which ignores `::before` styles, we could remove `::before` and use `outline` instead.

@tay1orjones The gray line above the outline is the separation line between each accordion item, maybe that is the reason why the current css use `::before`. Hopefully carbon design team approve it or if there is another solution. Personally, I think it should be ok.

**Comment by linzhaoken** [comment]
I just realize that I commit changes with my enterprise user (LinZhao1). Not sure what to do to comment DCO statement. Any suggestions?

**Comment by aagonzales** [comment]
Can't do visual review as preview is not working.

**Comment by tw15egan** [comment]
@aagonzales preview should be fixed

**Review by aagonzales — CHANGES_REQUESTED** [review]
Same comment as @tay1orjones. Focus is not aligning correctly to the item container. The focus should be on top of the border top and bottoms. Zoom in close to see. 

There should at least be no visible white gap between the border and focus. 

As-is: 
image

To-be: 
image

**Comment by linzhaoken** [comment]
@aagonzales Thanks for reviewing it, I will try to fix it once I have free time.

**Comment by dakahn** [comment]
@linzhaoken did you have time to circle back on this? We can always close this up and reopen it later if that works better 👍🏽

**Comment by linzhaoken** [comment]
@dakahn I have been very busy recently, have not got a chance to work on this. I will close this pr for now.

**Pull request closed without merging**
