### PR TITLE
fix(icon-build-helpers): update parser to replace \t sequences

### LINKED ISSUE #8811: Figure out issue with React icons generation in next package
There were some issues that came up when we updated our icons to the ones in the next builder in #8648 

This issue is to investigate what's going on with the icon generation and address it. We will know if it's been addressed if we no longer address the issues found in that PR.

### PR DESCRIPTION
**Pull request by joshblack**
Closes #8811

This PR updates our builder to replace tab characters `\t` with a space character. This issue seemed to always be at play in our builder since the AI SVG files that are parsed contain a `\t` character in them. In previous iterations of the builder, it would embed this character in the final React component. In our latest builder, it was directly embedding the `\t` character causing errors to occur in #8648 

With this update, all SVG paths should be correct. To verify, follow the testing/reviewing steps below. If this change is successful, a follow-up PR will be made for adding the next icons into the codebase.

#### Changelog

**New**

**Changed**

- Update our SVG parser in `icon-build-helpers` to replace `\t` characters with space
- Refactor the parser to control the emitted format to make migration simpler in the future if we need to switch parsing libraries

**Removed**

#### Testing / Reviewing

- Run `yarn lerna run build --scope='@carbon/icons-react' --include-dependencies` after pulling down the PR
- Run `cd codemods` to change into the codemods directory
- Run `yarn jscodeshift --parser babylon -t transforms/icons-react-size-prop.js '../packages/react/src/components'` to apply the codemod for icons-react to all of our icons
- Go through the list of components Andrew cited in #8648 and verify the icons render as expected, they are roughly:
  - [ ] Button
  - [ ] TreeView
  - [ ] Password Input
  - [ ] DatePicker Input

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
looks good to me, should this also get a design review to check icon rendering?

**Comment by joshblack** [comment]
@emyarod I think we'll need it on the PR that updates the icons but for this one it's a technical review since there are no visual changes to review 👍

**Comment by joshblack** [comment]
cc @emyarod @sstrubberg let me know if you have any questions!

**Review by emyarod — DISMISSED** [review]
meant to approve in my original review

**Review by sstrubberg — CHANGES_REQUESTED** [review]
Button seems fine, but the others don't look like what's in production.


image

image

image

**Comment by joshblack** [comment]
@sstrubberg which story are you looking at? For password I'm seeing this:

image

**Review by emyarod — COMMENTED** [review]
some of the original issues I mentioned in #8648 remain (warning states)

image

**Comment by joshblack** [comment]
@emyarod @sstrubberg I think you all might need to run:

```
yarn lerna run build --scope='@carbon/icons-react' --include-dependencies
```

(Sorry I forgot to include this in my description!)

**Comment by emyarod** [comment]
updated my comment, I've been building and rebuilding icons for sketch so much lately I'm pretty sure I ran the build command in my initial review and just didn't check warning states. I assumed I looked at the netlify preview after seeing @sstrubberg's review earlier and then rechecked without rebuilding icons again

**Comment by joshblack** [comment]
Thanks for the catch @emyarod! Seems like the `data-icon-path` and `opacity` attributes aren't being passed through. I'll make an update and push it up and give you a heads up once that's done

**Comment by joshblack** [comment]
@emyarod @sstrubberg should be good to go now!

**Comment by joshblack** [comment]
@emyarod @sstrubberg let me know if you have any questions!

**Review by emyarod — APPROVED** [review]
FYI re-requesting a review through the GitHub UI will notify reviewers on all channels

image

**Comment by joshblack** [comment]
Sure thing @emyarod, is that your preference instead of commenting?

**Comment by emyarod** [comment]
yep it'll work with any GitHub integrations like the Slack integration since it is a review request and not just a mention

**Comment by sstrubberg** [comment]
Yikes, sorry about that. I think i'm like Andrew and wait for the re-request to come through my Slack notifications.

**Review by sstrubberg — APPROVED** [review]
🔥

**Pull request merged**
