### PR TITLE
fix(button): prevent icon and tooltip jumping for tertiary button

### LINKED ISSUE #5617: Button: icon in tertiary button jumps on focus
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The icon in an tertiary button seems to sit further to the right than on other button types (primary, secondary, danger or ghost). When focusing a tertiary button, the icon jumps.
Screen Recording 2020-03-13 at 11 36 29

> What browser are you working in?
Chrome v80

> What version of the Carbon Design System are you using?
`carbon-components@10.10.1`
`carbon-components-react@7.10.1`

## Steps to reproduce the issue

1. Open react storybook -> Buttons
2. Select an icon from the knobs and switch button type to "tertiary"
3. Focus the button by either clicking on tabbing
4. Observe icon

### PR DESCRIPTION
**Pull request by janhassel**
Closes #5617

Simplifies the button styling and fixes the following problems:
1. Icon in tertiary button jumps when focused (#5617)
2. Tooltip jumps when focusing icon-only tertiary button
3. Border color of danger button changes color on hover when focused

(see screen recordings posted below)

#### Changelog

**Changed**
- All buttons use the same border / box-shadow setup to render focused styles now, eliminating a lot of special declarations for the tertiary button
- Deprecated unused `$button-outline-offset` and `$button-outline` tokens

**Removed**
- `$border-width` parameter of `button-theme` mixin

#### Testing / Reviewing

1. Open react storybook -> Buttons
2. Re-create the scenario in the screen recordings posted below
5. Compare to behaviour in current react storybook

#### Additional resources
1. Icon in tertiary button jumps when focused (#5617)
  - Screen Recording 2020-03-13 at 14 13 49
2. Tooltip jumps when focusing icon-only tertiary button
 - Screen Recording 2020-03-13 at 14 10 06
3. Border color of danger button changes color on hover when focused
  - Screen Recording 2020-03-13 at 14 11 34

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
on a side note, if users are using the tokens I think we may need to deprecate them rather than removing them outright before a major release

**Comment by janhassel** [comment]
@emyarod True, didn't think about that. Reverted removal and added `/// @deprecated` note to the tokens.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Everything you noted is working correctly now 👍🏻

One other thing I am noticing is that on active the danger button is getting some kind of lighter red border around it. That should not be showing up.
Mar-13-2020 13-16-36

**Comment by tw15egan** [comment]
Looks like this will also close out https://github.com/carbon-design-system/carbon/issues/5263

**Review by tw15egan — COMMENTED** [review]
Seeing an issue with icon only buttons + svg fill color

icon-primary

**Comment by janhassel** [comment]
@laurenmrice Thanks for catching that. Should be fixed now.

@tw15egan Weird. That didn't show up in my local setup. I think I know where the issue lies though and tried to fix it. We'll see once the deploy preview is done building.
Regarding the issue about the 2px border you mentioned: I cannot really see a difference between this implementation and the current 10.10.1 one. Should I adjust anything?

**Comment by tw15egan** [comment]
@janhassel I just noticed that you modified the border token width, which is all that the issue was talking about 👍 

https://github.com/carbon-design-system/carbon/pull/5618/files#diff-cfdf7d6a6baff15d13476bc700c119b9R134


Other issues look resolved now!

**Review by tw15egan — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
looks great, thank you ! 🙌🏻

**Comment by asudoh** [comment]
@emyarod Any further comments...? Thanks!

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
