### PR TITLE
fix(dropdown): use itemToElement for selected label if not null

### LINKED ISSUE #4913: Dropdown component doesn't support component label.
## Title line template: [Title]: Brief description
**I want to show the component label after selecting a component option for dropdown.** 

## What package(s) are you using?
**carbon-components-react**

## Detailed description

Describe in detail the issue you're having. Is this a feature request (new
component, new icon), a bug, or a general issue?

> Is this issue related to a specific component?
**Yes, carbon/packages/react/src/components/Dropdown/Dropdown.js**

> What did you expect to happen? What happened instead? What would you like to
> see changed?
For dropdown component, if I use itemsToElement to make option an component, after select it, it will show itemToString function's result.  I think it should show the component as well.

After I checked the source code of **Dropdown.js**, I found below code. It use itemToString function to render the label. In my circumstance, I want to use itemToElement to render the label. Shall we support it for this dropdown component?

 `  {selectedItem ? itemToString(selectedItem) : label}`              
Source: carbon/packages/react/src/components/Dropdown/Dropdown.js

> What browser are you working in?
**chrome v79**
> What version of the Carbon Design System are you using?
**carbon-components-react": "^7.7.3"**

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4913 

As described in #4913, if a someone utilizes `itemToElement` to render a custom component inside dropdown items, that custom component isn't used when you select a dropdown item. Instead, a selected dropdown item is made into a string regardless of implementation.

You can demonstrate this here: http://react.carbondesignsystem.com/?path=/story/dropdown--items-as-components
(Select one of the custom options with blue text, and you will see that the blue option number isn't shown as "selected" -- the option text is all black, meaning the custom component for the option was dropped)

So this PR changes the "selected item" label rendering logic to include `itemToElement` if it is used.

#### Changelog

**Changed**

- use `itemToElement` for "selected" dropdown item label, if `itemToElement` is not null... otherwise, do what was done before with rendering as a string.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Review by abbeyhrt — APPROVED** [review]
🎉 Thanks @jendowns!

**Comment by joshblack** [comment]
I'm a little confused, I had interpreted that `itemToElement` was meant for rendering an option in the list of options, is that not the case?

**Comment by jendowns** [comment]
@joshblack -- when you say "rendering an option" do you mean using a custom component as an option, rather than just text? That's what my interpretation of it is. So if you put blue text or something in the list of options and then select that option, now that "selected" option will be blue like it was in the list. (Previously the selected option was just rendered as a string regardless of if you did something custom)

**Comment by joshblack** [comment]
@jendowns yeah, I think it should be meant only for rendering an option in a list. If we support custom rendering for the value on top of the field, we won't be able to control things like contrast or could end up with violations if people decide to put things other than text in that location. Could easily be misreading though, let me know.

**Comment by jendowns** [comment]
Oh yeah that's a good point @joshblack -- do you think that same concern should apply to the list of options as well, which could for example have a custom option that doesn't meet contrast requirements, etc.?

Also would you prefer I revert / undo this?

**Pull request merged**
