### PR TITLE
fix(tooltip): ensure tooltip is not hidden in storybook

### LINKED ISSUE #5286: [tooltip] interactive tooltip when open goes off page in react
The interactive tooltip when open goes off the page and obstructs its view in react.

Ex:
Screen Shot 2020-02-06 at 9 58 23 AM

This happens with every example except for the `right` placement.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5286

Centers `Tooltip` so that the pop up is not hidden under the side nav

Also adjusts Tooltip positioning logic for `left` and `right` directions

#### Changelog

**New**

- Storybook specific position styles

**Changed**

- Modified positioning for `left` and `right` variations

#### Testing / Reviewing

Ensure the tooltip no longer renders under the side nav

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Can we have the icon be the info icon again with icon-02 color token? Right  now its showing a red dot

The tooltip open looks good when set to `bottom` and `right` now.  It still gets covered up for `left and `top`. I don't know if its that big of a deal for people if some positioning options look visually cut off, but it looks weird to me.

**Comment by tw15egan** [comment]
@laurenmrice updated

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Awesome thank you! 

One last thing, the tooltip shark fins just needs to point to the center of the icon in the `left` and `right` positions. The others look good.
Screen Shot 2020-02-07 at 3 39 50 PM

**Review by dakahn — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Comment by tw15egan** [comment]
@laurenmrice updated again!

**Review by abbeyhrt — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
looks great thank you !! 🙌🏻

**Pull request merged**
