### PR TITLE
fix(pagination): hide pagination text if `totalItems` prop is not provided

### LINKED ISSUE #3165: Pagination: if non-required prop `totalItems` not set, displays "0-0 of null items"
## Detailed description

In the `Pagination` component, `totalItems` is a non-required prop.

If you don't include `totalItems`, then the component displays "0-0 of null items":
Screen Shot 2019-06-24 at 2 49 40 PM

Test with knobs here:
http://react.carbondesignsystem.com/?path=/story/pagination--pagination

It seems like the best thing to do in this case, when no `totalItems` prop is provided, is to not show that pagination text at all. It's not the same situation as when `pagesUnknown` is set to `true`. 🤔

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3165 

If no `totalItems` prop is provided, I propose just making the pagination text blank. To me it seems different than the situation where `pagesUnknown` is true 🤔 

However if you disagree let me know and I could also just do this instead:
```javascript
      {pagesUnknown || !totalItems
      // etc
```

(The goal here is just to avoid showing "0-0 of null items" if no `totalItems` is provided 😅 

#### Changelog

**Changed**

- update pagination text ternary to show no text if `totalItems` isn't provided

### CODE REVIEW

**Comment by jendowns** [comment]
Hey I noticed the tests are failing -- let me know if you approve of this approach or if you prefer just adding `|| !totalItems` to line 300, and I'll update the tests if its still necessary 👍

**Comment by asudoh** [comment]
Hi @jendowns thank you for jumping in! Though not sure why we have `pagesUnknown` as a separate prop, but seems that not having `totalItems` is equivalent to `pagesUnknown`?

**Comment by jendowns** [comment]
Thanks @asudoh! To me, when you don't have `totalItems` provided, it doesn't make sense to say "1-10 items" (which is currently the case when `pagesUnknown=true`), because seems possible to have fewer than 10 items if you don't know the total? 🤔  But I can go ahead and make `totalItems` is equivalent to `pagesUnknown` (either way, it's better than having "null items" in the text)

**Comment by jendowns** [comment]
Hey @asudoh I just realized that after the latest version updates, I can longer replicate this in Carbon's storybook or in my own environment 😆 The text now reads `0-0 of 0 items` if you don't provide a `totalItems` prop value, which makes sense. So I'm going to close this PR -- thanks again for your help!

**Pull request closed without merging**
