### PR TITLE
Fix toast notification long text

### PR DESCRIPTION
**Pull request by imandyhq**
Before
Screenshot 2019-04-21 at 10 48 09 PM

After
Screen Shot 2019-05-15 at 22 52 39

### CODE REVIEW

**Comment by elizabethsjudd** [comment]
@imandyie Is this fix applied to inline notifications and would also fix [this issue](https://github.com/carbon-design-system/carbon/issues/2294#issuecomment-482717958) I brought up?

**Review by asudoh — APPROVED** [review]
LGTM 👍 once @elizabethsjudd's question is addressed - Thanks @imandyie!

**Comment by imandyhq** [comment]
@elizabethsjudd this fix is for toast notifications. I could not replicate the issue for inline notifications.
Screen Shot 2019-05-16 at 08 51 35

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by tw15egan** [comment]
@elizabethsjudd is correct, this issue still happens with inline notifications

https://codepen.io/tjegan/pen/NVgRVg

Screen Shot 2019-05-17 at 9 23 48 AM

**Pull request merged**
