### PR TITLE
feat(ui-shell): design updates to ui shell global header

### LINKED ISSUE #2401: Development of standalone Shell Header
Design issue: https://github.com/carbon-design-system/carbon-components/issues/2334

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/2401
Refs #2334 

Design updates to UI Shell Global Header component

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]

**Review by aagonzales — COMMENTED** [review]
Can we change the content to be more general. ie "Link" "Sub-menu"
image

Also the icons need to be the 20x20 size. But other than that looks good!

**Comment by tw15egan** [comment]
@aagonzales done!

**Comment by aagonzales** [comment]
Awesome! 

And one more thing I just noticed. The little pipe divider should only show up if there are links other wise its hidden. So it shouldn't* be in the `Header Base`, `Header Base w/ Menu` or `Header Base w/ Action`. Maybe just make it a part of the `bx--header__menu-bar` ?

image

**Comment by tw15egan** [comment]
Assuming you mean shouldn't be in those that you listed?

Updated

**Review by aagonzales — APPROVED** [review]
Thanks for the updates! It's good to go!

**Pull request merged**
