### PR TITLE
fix(modal): set half width single buttons

### LINKED ISSUE #5344: ModalFooter with one button should have 50% width but has 100%
[Title]: When using ComposedModal with a ModalFooter without a secondary button, the primary button should be 50% width on the right but instead is full width.

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Incorrect styling per latest design system updates

> Is this issue related to a specific component?

Yes, ModalFooter

> What version of the Carbon Design System are you using?

+-- carbon-components@10.9.3 
`-- carbon-components-react@7.9.3

### LINKED ISSUE #5345: Enable single visible button on Modal component
Use this template if you want to request a new feature, or a change to an
existing feature.

If you are reporting a bug or problem, please use the bug template instead.

### Summary

Add capability to the Modal component where a single clickable button is shown.  

Asking for design and development.

### Justification

There are many use cases where a modal needs to be shown and there is only one action:  acknowledge the modal.   This should be done with a single clickable button.   Using the X to terminate the modal is not preferred.  It's use is not obvious, may be overlooked by the user, does not clearly communicate the action to be taken,  infers cancelation rather than acknowledgement, and in some cases is not a familiar path to the user.  

For example:

----
Job completed

Your job has completed.

[OK]

-----
Example: 
Single Modal Button

In such a case, a button such as OK is superior for the user and preferred by UX designers.

Consider the uploaded video of a modal displaying a progress component.  When the progress is complete, the interaction needs a button of some sort to acknowledge completion.

[Progress.mov.zip](https://github.com/carbon-design-system/carbon/files/3253661/Progress.mov.zip)
### Desired UX and success metrics

The full user experience is a modal is displayed and has one major button in the button area which has text and click action.  

### "Must have" functionality

Must haves:
Property which somehow shows only one button.  The button has text and a callback.
It might be done by totally hiding (not just graying) the secondary button.

### Specific timeline issues / requests

This is an issue we are currently working around by adding our own button in the body and changing CSS.  We will utilize at any availability.

### Available extra resources

Skills are nascent on our team.  For this work we would need more help than it's worth.

### LINKED ISSUE #5346: Single buttons on modals should be half width
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

A single primary button inside a modal takes up the entire width of the modal. We've confirmed that the screenshot attached shows the correct styling of the button and the documentation on full-length buttons is incorrect.

> Is this issue related to a specific component?

Modals and Buttons 

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.7.4",
    "carbon-components-react": "^7.7.4",
## Additional information
carbon-modal-bug

Our overriding styling: 
```
.bx--modal-footer {
  justify-content: flex-end;
  button.bx--btn--primary {
    max-width: 50%;
  }
}
```

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5344
Closes #5345 
Closes #5346
Refs #4607, more research needed for expected 3 button modal layout

This PR sets a single button within modal footers to span half of the modal width while maintaining default 2 button modal layout

#### Testing / Reviewing

Ensure single button modals appear correct

### CODE REVIEW

**Comment by aagonzales** [comment]
@emyarod is there a knob to see it?

**Comment by emyarod** [comment]
@aagonzales the ComposedModal story contains some single button modal examples

**Comment by aagonzales** [comment]
Got it, was only looking under "modal". 
Side question: what's the difference between "compose modal" "modal" and "modal wrapper"

**Review by aagonzales — CHANGES_REQUESTED** [review]
Empty space beside the single primary button should be the same color as the modal content area, not darker.

image

**Comment by emyarod** [comment]
The Modal component is just the modal by itself. Composed modal allows users to create their own modals with only the pieces they need. The ModalWrapper story just shows the modal launching UX. All three share the same styles (modal component styles)

it looks like the modal footer color was carried over from v9 so I will deprecate that token

**Review by aagonzales — APPROVED** [review]
Look good!

**Review by abbeyhrt — APPROVED** [review]
LGTM! 🎉

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
