### PR TITLE
fix(icons): Rename 16/filter

### PR DESCRIPTION
**Pull request by chrisconnors-ibm**
/16/filter.svg renamed to  /16/settings--adjust.svg;
/32/filter.svg does not need a bespoke 16/16/filter.svg

#### Changelog

**Changed**

- `/16/filter.svg` renamed to  `/16/settings--adjust.svg`;

**Removed**

- `16/16/filter.svg`

#### Testing / Reviewing

Confirm `/16/settings--adjust.svg` = `/32/settings--adjust.svg`
confirm 'Filter' does not return 'settings--adjust.svg` on website and vice versa

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by jnm2377** [comment]
Can we update the title to proper commit syntax? I'm unsure if this is a feat or fix given the name change, but you can find all our commit types here: https://github.com/carbon-design-system/carbon/blob/master/docs/developer-handbook.md#commit-conventions

**Comment by joshblack** [comment]
I think we'd have two technically, but can group into one.

The `feat` would be adding in the new icon, then `refactor` for removing an unnecessary icon size.

**Review by abbeyhrt — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Comment by chrisconnors-ibm** [comment]
it's a fix bc this is how the icons manifest today:
image
 the break occurred here:
image

**Comment by joshblack** [comment]
@chrisconnors-ibm I think the `feat` is from the addition of the new icon asset `settings--adjust`, the `fix` is for removing `filter` (through the rename)

**Pull request merged**
