### PR TITLE
fix(date-picker): disable mobile UI

### LINKED ISSUE #4420: Bug - DatePicker with Calendar - Carbon for React
Datepicker open and set methods are not available in mobile devices. Due to as issue with rerendering of the input after the maxDate and minDate prop values are changed, I was advised to use _set_ method using the datepicker ref `(ref.current.cal.set({ maxDate: new Date() }))` which wont work on android. 

## What package(s) are you using?

- [ ] `carbon-components` - ver: 10.5.1
- [x] `carbon-components-react` - ver: 7.5.1

## Detailed description

Throwing errors on console when opened in mobile view

## Steps to reproduce the issue

1. Open a new tab with dev tools in Chrome
2. Go to [React Storybook link for Datepicker](http://react.carbondesignsystem.com/?path=/story/datepicker--single-with-calendar)
3. Switch to mobile view
4. Click on the date input or calendar icon in the date input
5. Check console
6. You should see an error 

> `vendors~main.ea56bc5986fd20de4d78.bundle.js:93 Uncaught TypeError: _this.cal.open is not a function`

I think the calendar implementation is done differently for different devices. I opened the link on my android phone and it opened the android calendar. However, since I am using internal methods of datepicker for my use case and although it works fine on desktop, it wont on mobile.

### PR DESCRIPTION
**Pull request by asudoh**
This change disables `flatpickr`'s mobile mode, given we have been not
supporting the mobile UI and the mobile UI has caused several
JavaScript errors.

Fixes #4420.

#### Changelog

**New**

- Code to disable `flatpick`'s mobile mode.

#### Testing / Reviewing

Testing should make sure our date picker is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
issue is resolved for both libraries but would we want to support the native mobile date pickers in the future?

**Review by jeanservaas — COMMENTED** [review]
Just want to clarify... does this affect anything visual... this is what I see following the steps in the issue, so I'm not sure what I should be reviewing in this PR

image

**Comment by abbeyhrt** [comment]
@jeanservaas talking with @joshblack, it seems like we just wanted to verify on the UX design side if we want to disable the MobileUI for the DatePicker.

**Comment by joshblack** [comment]
@jeanservaas I think what you are seeing may be what is intended. It seems like in the past flatpickr had a mobile view that this PR gets rid of to create that screenshot you posted

**Comment by asudoh** [comment]
Sorry for not being clear enough @jeanservaas - @abbeyhrt and @joshblack are right, Flatpickr has different look for mobile. We haven't supported that mode, but in the status quo, whenever user goes to mobile such mobile mode is activated, causing several bugs, notably you'll see something below in some conditions (this is browser's native date picker):

image

So we want to ensure mobile mode is never activated.

**Comment by asudoh** [comment]
@emyarod You have good question, native date picker may be in (future) consideration if we can style it in the way we want. Same thing applies to sliders, etc, too (in my personal opinion).

**Review by abbeyhrt — APPROVED** [review]
Thank you for the explanation @asudoh! This looks good to me!

**Review by jeanservaas — APPROVED** [review]

**Pull request merged**
