### PR TITLE
fix(FileUploader): respect multiple prop in default file uploader

### LINKED ISSUE #2537: Fileuploader component: Multiple prop set to false but all selected files are accepted.
## Detailed description

Hello Team,
We are using Fileuploader component, even though *multiple* prop is set to false one can select files one by one and all selected files are accepted.

## Steps to reproduce the issue

[http://react.carbondesignsystem.com/?selectedKind=FileUploader&selectedStory=FileUploader&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs](url)

## Additional information

image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2537

This PR will restrict the file list to 1 file if the `multiple` prop is false in the default file uploader

#### Changelog

**Changed**

- internal file list is replaced instead of concatenated when `multiple` is false

#### Testing / Reviewing

Ensure only one file is listed when `multiple` is false in default file uploader

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
🎉 - Thanks @emyarod!

**Comment by abbeyhrt** [comment]
Should this address the drag and drop variant as well? It seems to have the `multiple` prop but I can still select multiple if it is set false.

**Comment by emyarod** [comment]
the drag and drop file uploader does not control the file list* so it doesn't have this issue out of the box. but I can update the example application to match this behavior

**Review by abbeyhrt — APPROVED** [review]
LGTM! 🎉

**Review by dakahn — APPROVED** [review]

**Pull request merged**
