### PR TITLE
fix(icon-build-helpers): disable svgo plugins that cause rendering issues

### LINKED ISSUE #5565: Icon rendering is broken in newer versions of Sketch
In our Sketch plugin, we make use of the following code snippet to generate our icons from a source SVG descriptor (a descriptor describes the parts of an SVG as an object):

```js
/**
 * Create a layer from an SVG descriptor
 *
 * Reference:
 * https://github.com/airbnb/react-sketchapp/blob/aa3070556c47883974edbc7f78978c421a8199f7/src/jsonUtils/sketchImpl/makeSvgLayer.js#L12
 *
 * @param {object} svg
 * @returns {Layer}
 */
function createSVGLayer(svg) {
  const svgString = NSString.stringWithString(toString(svg));
  const svgData = svgString.dataUsingEncoding(NSUTF8StringEncoding);
  const svgImporter = MSSVGImporter.svgImporter();
  svgImporter.prepareToImportFromData(svgData);
  const svgLayer = svgImporter.importAsLayer();

  return svgLayer;
}
```

Unfortunately, in later versions of Sketch this behavior seems to be busted for certain types of icons that have been transformed by SVGO. To reproduce, we can use the following template:

```js
const selectedDocument = Document.getSelectedDocument();
const page = findOrCreatePage(selectedDocument, 'test');
const svgString = NSString.stringWithString(source);
const svgData = svgString.dataUsingEncoding(NSUTF8StringEncoding);
const svgImporter = MSSVGImporter.svgImporter();
svgImporter.prepareToImportFromData(svgData);
const svgLayer = svgImporter.importAsLayer();

page.layers = [svgLayer];
```

To render a broken icon, replace `source` with the following SVG code:

```svg
<svg focusable="false" preserveAspectRatio="xMidYMid meet"
  xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32"
aria-hidden="true"><path d="M8 9H4a2 2 0 00-2 2V23H4V18H8v5h2V11A2 2 0 008 9zM4
  16V11H8v5zM22 11L25 11 25 21 22 21 22 23 30 23 30 21 27 21 27 11 30 11 30 9 22
9 22 11zM14 23H12V9h6a2 2 0 012 2v5a2 2 0 01-2 2H14zm0-7h4V11H14z"></path><rect
width="32" height="32" fill="none"></rect></svg>
```

This will render the following icon:

image

If instead, we use the original source, we get:

```svg
<svg id="icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><defs><style>.cls-1{fill:none;}</style></defs><title>API</title><path d="M8,9H4a2,2,0,0,0-2,2V23H4V18H8v5h2V11A2,2,0,0,0,8,9ZM4,16V11H8v5Z" transform="translate(0 0)"/><polygon points="22 11 25 11 25 21 22 21 22 23 30 23 30 21 27 21 27 11 30 11 30 9 22 9 22 11"/><path d="M14,23H12V9h6a2,2,0,0,1,2,2v5a2,2,0,0,1-2,2H14Zm0-7h4V11H14Z" transform="translate(0 0)"/><rect id="_Transparent_Rectangle_" data-name="&lt;Transparent Rectangle&gt;" class="cls-1" width="32" height="32"/></svg>
```

image

### PR DESCRIPTION
**Pull request by joshblack**
Closes #5565

After investigating the causes of our icon rendering issues, it seems related to these two optimization plugins from SVGO. Disabling them causes our icons to render correctly in Sketch.

#### Changelog

**New**

**Changed**

- Disable two SVGO plugins used for optimization

**Removed**

**Testing / Reviewing**

- Setup the sketch plugin per the instructions in the README
- Run the sync command from the carbon elements plugin
- Verify that icons render as intended in the symbols page

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
a few strange icon changes I noticed. should we add design review to these PRs?

image

image

**Comment by joshblack** [comment]
@emyarod I believe the numbers are known issues flagged in: https://github.com/carbon-design-system/carbon-design-kit/issues/260

**Review by emyarod — APPROVED** [review]
ok since those icons are tracked elsewhere this looks good to me, just need to pass CI

**Comment by joshblack** [comment]
@asudoh @tw15egan let me know if I can help out at all with reviewing!

**Review by asudoh — APPROVED** [review]
Seems fine by looking at the change in snapshot

**Pull request merged**
