### PR TITLE
feat(AI): update `ai-gradient` to phase 2 spec

### LINKED ISSUE #15527: Update linear gradient styles to new spec
Spec:

Image

[Figma link](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1368%3A115940&mode=design&t=XzcxFSEVGYuwDJHU-1)

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15527
Refs https://github.com/carbon-design-system/carbon/pull/15522

Updates the `ai-gradient` mixin to match the new spec

#### Changelog

**New**

- The `ai-gradient` mixin has been updated to use the new styles and now applies a bottom border.
- The following tokens have been added:
```scss
$ai-inner-shadow
$ai-aura-start
$ai-aura-end
$ai-border-strong
$ai-border-start
$ai-border-end
$ai-drop-shadow
```

This consolidates some of the tokens that were used in #15522 

**Changed**

- Some component-specific overrides to get the bottom AI border to show properly
- Changed some of the tokens added in #15522 to use the new consolidated tokens
- Adjusted the `ai-gradient` styles so that they are not applied if the slug is in the revert state

**Removed**

- Removed extra tokens that were added in #15522 that weren't needed after consolidating tokens:
```scss
$slug-callout-shadow-inner
$slug-callout-border-01
$slug-callout-border-02
```

#### Testing / Reviewing

Ensure that the new linear gradient looks correct on form components. Some components (`Modal,` `Tile,` and `DataTable`) will have additional PRs to address additional styles.

### CODE REVIEW

**Comment by aagonzales** [comment]
@tw15egan, the fade-out of the gradient seems a little harsh. Is there anything we can do to help with the blending? The color seems correct; the transition out of the gradient just feels a little too strong.

image

**Comment by tw15egan** [comment]
@aagonzales could it be the extra `.1` of opacity? If I switch it to `blue50` at `.1` here is what I get
Screenshot 2024-01-11 at 5 38 22 PM

`blue50` at `.2`
Screenshot 2024-01-11 at 5 38 39 PM

they are both blending `blue50` at opacity with `white` at `0` opacity (so to transparent) between 0% and 50%, and then all transparent from 50% to 100%. Let me know if we need to tweak these stops

**Comment by aagonzales** [comment]
OoOoOoOo yes exactly! That looks awesome now! 🎉

**Review by aagonzales — COMMENTED** [review]
The visuals look good but I noticed the revert examples wasn't removing the AI styles when the values were changed and the slug goes away. Is that part of this PR or something that's done separately?

**Comment by tw15egan** [comment]
@aagonzales ooo good catch, I don't think I'd ever built that in. Let me take a look

**Comment by tw15egan** [comment]
@aagonzales fixed!

**Review by aagonzales — APPROVED** [review]
🎉 Looks good!!

**Review by alisonjoseph — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Review by guidari — APPROVED** [review]
LGTM!

**Pull request merged**
