### PR TITLE
fix(a11y): Move label to be before all select and text input fields 

### LINKED ISSUE #1009: <label> should be before text input, select etc
form elements are failing DAP tests

Ref: https://github.com/IBM/carbon-components-react/issues/1131#issue-345021899
Ref: https://github.com/IBM/carbon-components-react/pull/1134
Ref: 

This is documented in the w3 test techniques for H44: https://www.w3.org/TR/WCAG-TECHS/H44.html

For all input elements of type text, file or password, for all textareas and for all select elements in the Web page:
* Check that there is a label element that identifies the purpose of the control *before* the input, textarea, or select element
* Check that the for attribute of the label element matches the id of the input, textarea, or select element
* Check that the label element is visible.

Elements to update/test

- [x] Number Input
- [x] Search 
- [x] Select
- [x] Text Input
- [x] ~Text Area~ (label is already before textarea)
**Date Picker**
- [x] Single
- [x] Default (no calendar)
- [x] Range

### PR DESCRIPTION
**Pull request by alisonjoseph**
## Overview

Resolves #1009 

Label for text input and select should be BEFORE the input/select to pass a11y requirements

### Changed

Updated 

- Number Input
-  Search
-  Select
-  Text Input
-  Date Picker  ~single with calendar is broken, need to see if there is a non-breaking way to fix~ _fixed_

## Testing / Reviewing

Test that this doesn't break any of the above components.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Thanks for doing this! Only noticed what you mentioned before with DatePicker. Definitely down to go with whatever you end up deciding is best moving forward 👍

**Comment by alisonjoseph** [comment]
pushed a css update that should fix date picker, and also not break anything for users with the current html

**Review by asudoh — APPROVED** [review]
Thanks alot @alisonjoseph for taking a look! Given this seems a minor breaking change (requiring markup change in app), do we want to advertise this before (or right after) merging?

**Comment by alisonjoseph** [comment]
While it is a change in markup, it doensn't break anything for anyone using the old markup.

**Comment by asudoh** [comment]
I see - Thanks alot @alisonjoseph for clarifying and my apologies for the false alarm!

**Pull request merged**
