### PR TITLE
fix(loading): update theme token

### PR DESCRIPTION
**Pull request by SimonFinney**
#### Changelog

**Changed**

- Update loading theme token for accessibility in darker themes

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by shixiedesign — APPROVED** [review]
Good catch. Thank you!

**Comment by asudoh** [comment]
@shinytoyrobots @alisonjoseph Straightforward two-line changes - OK to put it in `v10`? Thanks!

**Review by mattrosno — COMMENTED** [review]
Not really in scope for v10 release, but is this token change good for g10, g90 and g100 themes? If not, may need to create a new issue that we address later.

**Comment by asudoh** [comment]
@SimonFinney Any thoughts on ^? Thanks!

**Review by shixiedesign — COMMENTED** [review]
@mattrosno Yeah the new token used here `$interactive-04` have the correct values in all 4 color themes.

**Pull request merged**
