### PR TITLE
style(modal): adds the danger style to modals

### PR DESCRIPTION
**Pull request by davidmenendez**
## Overview

Adds the danger style to modals
screen shot 2018-02-13 at 10 22 27 am

screen shot 2018-02-13 at 10 22 45 am

Based on other current implementations I think we would like to see new styles of button to be paired with the danger modal. This is a currently implemented danger modal in Bluemix-
screen shot 2018-02-12 at 2 28 03 pm

Notice the primary button is a solid red and the secondary is the grey outline. It's somewhat unrelated to this PR, but I think we would like to open this up to discussion.

### CODE REVIEW

**Comment by tw15egan** [comment]
Hmm, wonder if the danger modal should default to a gray secondary button, since the red / blue button combo is pretty conflicting visually. cc @carbon-design-system/design

**Comment by davidmenendez** [comment]
Totally agree. I think this should be an opportunity to add some additional button styles. I've asked the Armada designers to provide feedback here.

**Comment by SpencerReynolds18** [comment]
Things I'll call out:
-The spacing between buttons on David's example is too tight. David was telling me that the spacing is only restricted to 1 rem between a primary and secondary button. Because the Danger button isn't a primary button in carbons implementation it doesn't come with the spacing out of the box so he didn't include it. 
- There is no primary danger button style with red fill. We propose adding a primary danger button and its disabled(grayed out/opaque) counterpart as we have implemented on our microservice.
-I'll second the previous conversation in this thread about the blue secondary button being a little weird next to the red primary... can we add a grey secondary button to carbon?

**Comment by davidmenendez** [comment]
yeah it looks like the spacing is only for primary buttons next to secondary https://github.com/carbon-design-system/carbon-components/blob/master/src/components/button/_button.scss#L144
```
.bx--btn--secondary + .bx--btn--primary {
    margin-left: 1rem;
}
```
Perhaps this could be reworked to just be for any combination of buttons and not just primary + secondary? Unless we want different flavors of primary (blue/red).

**Comment by tay-aitken** [comment]
Hey guys 👋We actually just had a discussion about this the other day. The reason behind making it a secondary button was becuase we felt the primary button was too intrusive. On full pages where the danger button is used, its the first thing the user notices since its the only red on the page in a sea of blue/gray. 

Ill bring up your issue up with the other designers and see if we can come to a new consensus now that this use case was brought up. Thanks!

**Comment by SpencerReynolds18** [comment]
Yeah, we weren't using the primary danger in a full page context, and we understand it would be overwhelming in a full page context. If y'all end up adding a primary danger you could add guidance against using it in larger contexts. 

Also, I understand this may expand into a couple of different issues:
-New buttons
-Additional Friction Modal
-others?

**Comment by SpencerReynolds18** [comment]
One other thing to call out on this modal is the red color stripe instead of the blue color stripe at the top of the modal. The red matches that this is a danger modal.

**Comment by tw15egan** [comment]
Once https://github.com/carbon-design-system/carbon-components/pull/565 and https://github.com/carbon-design-system/carbon-components/pull/573 are merged in, can you update this PR to use those elements? After that should be good to go 👍

**Comment by davidmenendez** [comment]
Updated with the new danger button pairing-

screen shot 2018-02-16 at 11 53 38 am

**Review by tw15egan — APPROVED** [review]

**Review by marijohannessen — APPROVED** [review]

**Pull request merged**
