### PR TITLE
fix(modal): remove leftover mixin

### LINKED ISSUE #3768: Modal: deprecated mixin and class
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Summary

There is a mixin and associated class that may be deprecated.

### `modal--color` mixin
We’re doing some work with the Modal and I’m curious if the `modal--color` mixin is still relevant.
https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/modal/_mixins.scss#L14

The mixin adds a border color to the bx--modal-container class, but the border on that element is set to 0px, I believe via the `reset` css. Because there is no border width, no color is visible in the component. It seems like that top border may have been a v9 style that didn’t get retained in the latest IDL styles of v10.

Am i correct that that top-bar color is no longer part of Carbon's modal?

### bx--danger--modal

This would also seem to mean that the class `bx--danger--modal` may not have any affect when applied to the modal. It's [listed in as a modifier for bx--modal](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/modal/README.md#modifiers) but [in the Sass file](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/modal/_modal.scss#L68), it only calls `modal--color`

I can't find any instance where the className is used, other than it being applied in the React modal, but it doesn't seem to have any JS functionality or add styling.

Is it correct that this className may not be needed?

thanks!

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/3768

`Modal` used to use a mixin to achieve different border colors based on regular / danger. Since `Modal` no longer has a border, this mixin is no longer needed.

#### Changelog

**Removed**
- Reference to `modal--color` mixin 
- `mixin.scss` inside `modal`

#### Testing / Reviewing

Make sure Danger Modal still looks correct

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by emyarod — DISMISSED** [review]
looks good to me

**Review by emyarod — COMMENTED** [review]
I guess we can't remove that file since the grid tests are making references to it?

**Review by emyarod — APPROVED** [review]
seems to be passing CI now

**Review by aagonzales — APPROVED** [review]
LGTM 👍

**Review by abbeyhrt — APPROVED** [review]

**Pull request merged**
