### PR TITLE
fix(code-snippet): use the focus theme token for inline variation focus outline

### LINKED ISSUE #4509: [CodeSnippet] Inline variation focus outline is not properly themed
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The inline variation of the `CodeSnippet` uses the theme token `$interactive-01` for the focus outline, which is already blu60 for every theme --

https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/code-snippet/_code-snippet.scss#L53-L56

It looks like this in the `gray100` theme:
Screen Shot 2019-10-31 at 11 34 40 AM

Ideally it would be the `$focus` theme token instead.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4509

#### Changelog

**Changed**

- use `$focus` theme token for the focus outline of the inline `CodeSnippet`, instead of `$interactive-01` (which is always blue60)

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me, pending design review

**Comment by laurenmrice** [comment]
Looks good in Vanilla. Can't review React in dark themes because the switcher is gone?

**Comment by joshblack** [comment]
Hey @laurenmrice! 👋 Sorry about the deploy preview issue, mind checking again?

**Review by laurenmrice — APPROVED** [review]
Looks good ! 🎉

**Review by aledavila — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Pull request merged**
