### PR TITLE
fix(data-table): right align datatable sort icon

### LINKED ISSUE #6577: [data table] sort icon is in the wrong place
The sort icons need to be positioned to the right of the header cell.

What is happening now:
Screen Shot 2020-07-29 at 17 07 30

-----------------------------------------------------------------------------------------------------------------------------

Spec:

Artboard

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6577

Right aligns the `DataTable` sort icon 

#### Changelog

**Changed**

- Align sort icon `8px` from right edge of `DataTable` header

#### Testing / Reviewing

Ensure sort icon renders properly in all browsers

### CODE REVIEW

**Comment by wkeese** [comment]
Please test in IE11 as IE11 was broken even before things broke in chrome.

**Comment by tw15egan** [comment]
@wkeese that should be resolved with https://github.com/carbon-design-system/carbon/pull/6550

**Comment by wkeese** [comment]
OK, that's good.

The bad news though is that this fix isn't working for the compact, short, and tall rowsizes.  (It does work for the standard rowsize.)   Here's how tall looks:

Screen Shot 2020-07-30 at 15 11 57

Same problem on both IE11 and Chrome.

**Comment by laurenmrice** [comment]
Once the icons are right aligned in the other size data table options we will be good to go!

**Comment by tw15egan** [comment]
@laurenmrice updated 👍 

IE11 Screenshot included:

Screen Shot 2020-07-30 at 9 47 45 AM

**Review by laurenmrice — APPROVED** [review]
looks good to me!

**Review by joshblack — APPROVED** [review]

**Pull request merged**
