### PR TITLE
chore(test): switch to Jasmine/WebPack for tests

### PR DESCRIPTION
**Pull request by asudoh**
### Changed

* Chai to Jasmine: So the assertion syntax matches ones used in `carbon-components-react`
* Rollup to Webpack (only for testing): For boosting the speed of running tests
* `minimist` to `commander`: Given the former seems no longer maintained

## Testing / Reviewing

Testing should make sure no test/build is broken.

### CODE REVIEW

**Comment by joshblack** [comment]
Slightly related, do you think there is any way we could use Jest for testing? Maybe with a custom runner?

**Review by joshblack — APPROVED** [review]

**Comment by asudoh** [comment]
Thank you for reviewing and good question @joshblack! Adding Karma (non-JSDOM) support to Jest hasn’t happened yet, and we’d need to have that to use Jest here.

**Comment by joshblack** [comment]
@asudoh totally get that the environment by default is JSDOM, however we could create our own environment for it like in https://github.com/alexeyraspopov/jest-webdriver

**Comment by asudoh** [comment]
IIRC the Jest maintainer said that currently Jest depends on node.js env. WebDriver works fine from that perspective, but not Karma as far as I see.

**Review by marijohannessen — APPROVED** [review]

**Pull request merged**
