### PR TITLE
chore(pictograms): correct berlin brandenburg name typo

### PR DESCRIPTION
**Pull request by janhassel**
As noted in #4610, the gate in Berlin is called "Brandenburg Gate", not "Brandenberg Gate". This PR just fixes this typo.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
on a side note, are the SVG ID's auto generated? if so we should make sure to update the source files as well

**Comment by janhassel** [comment]
Good point, @emyarod. Do you know who maintains the source files?

**Review by aledavila — APPROVED** [review]
thanks

**Comment by emyarod** [comment]
@janhassel, I'm not sure but most likely the design group will know cc @carbon-design-system/design

**Comment by joshblack** [comment]
I think they come from the icon AI file 👍 will bump @conradennis just so he's aware

**Pull request merged**
