### PR TITLE
feat(React): updates to size prop

### PR DESCRIPTION
**Pull request by tw15egan**
Refs https://github.com/carbon-design-system/carbon/issues/8151

This PR will update the `size` prop across components to use `sm`, `md`, and `lg`. 

For now, I am adding in comments anywhere `xl` is used to mark for deletion when we create our alpha branch. Until then, `lg` and `xl` should function interchangeably. I've also added `md` to the allowed values for `size` for consistency throughout.  

#### Changelog

**New**

- `lg` is now the preferred `size` value to get the "bigger" version of a component. 
- `md` is added to the `size` propType definition. Will be set as a default where needed.

**Changed**

- Changed the `size` prop knob to reflect new values

List of components that use the size prop and that will be updated:

- [x] Accordion
- [ ] Button 
- [x] Listbox
   - [x] Combobox
   - [x] Dropdown
   - [x] Multiselect
   - [x] Filterable Multiselect
- [x] Content Switcher
- [x] DatePicker
- [ ] FileUploader
   - [ ] FileUploaderButton
   - [ ] FileUploaderDropContainer
   - [ ] FileUploaderItem
- [x] Link
- [x] Modal
   - [x] ComposedModal
- [x] Number Input
- [x] Overflow Menu
- [ ] Search
- [x] Select
- [x] Tag
- [x] Text Input
- [x] Time Picker
- [x] Toggle

Questions:
- Do we want to keep the `field` button size? This also cascades into `FileUploader`, which has `small` field` and `default` size buttons
- `Data Table` has a few sizes (`compact`, `short`, `normal`, `tall`). Do we want to change any of these? 
- Treeview has a size prop with `default` and `compact`. Do we want to change these? 

Blockers:
- Search cannot be updated yet as it has `sm` `lg` and `xl` styles

#### Testing / Reviewing

Ensure the components listed above that are checked correctly render at the correct sizes
Ensure no prop warnings are emitted when toggling sizes

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Verified components render as expected in different size variants. No prop warnings, all are 👍  except for the ones you have unchecked in your list 

> * [ ]  Button
> * [ ]  FileUploader
>   * [ ]  FileUploaderButton
>   * [ ]  FileUploaderDropContainer
>   * [ ]  FileUploaderItem
> * [ ]  Search

**Review by jnm2377 — APPROVED** [review]
Sorry I'm just now getting to this. Tested the size variations and all are working correctly. WRT some of your questions:

> Do we want to keep the field button size? This also cascades into FileUploader, which has small fieldanddefault` size buttons

For the sake of consistency,  I vote for updating these to be `sm, md, lg` as well. The FileUploader sizing (field, small, default) confuses me as is.


> Data Table has a few sizes (compact, short, normal, tall). Do we want to change any of these?

I would be fine with updating these. I think it would still make sense with `xs, s, m, lg` with `md` being default. Tbh I think this would be more intuitive. I always have a hard time remembering whether `compact` or `short` is the smallest. Modal has `xs` size, so it wouldn't be the first component to have 4 sizes. And would be consistent with our other sizing.

> Treeview has a size prop with default and compact. Do we want to change these?

Same as above.

I can work on those sizing updates in another PR, if ya want. :)

**Comment by tw15egan** [comment]
@jnm2377 great points! Yeah, maybe we should move these outstanding questions to a new issue, and address them in a separate PR as you said. These ones were the easy ones and mapped directly to the new values 🎉

**Comment by aagonzales** [comment]
- Ok below is basically what you have with name to size collation. So all `sm` things are always 32px, it shouldn't vary based on component. 
-  Default shouldn't ever be the size name. Default is going to vary based on the component, it won't always be at the `md` level. Default will just be in guidance now and not as part of the name. 
- I'm fine with changing data table rows and file uploader size to be consistent with this naming. Row sizes just came before we had any other size variant which is why its the outlier now. 

| Name | Size |
|-----|-------|
| `xs` | 24 |
| `sm` | 32 |
| `md` | 40 |
| `lg` | 48 |
| `xl` | 64 |
| `2xl` | 80 |

**Comment by tw15egan** [comment]
@aagonzales that is super helpful! I'm going to create a new issue with that table to track those outstanding components that map a little differently than these basic form ones.

**Comment by aagonzales** [comment]
@tw15egan the one thing I'm just noticing though like data table doesn't have a `md`/40px row size so would we just skip that size then? I don't really like the idea of mixing values across a single size name. ie sometimes `md` is 40 somethings its 48. 

| Name | Size |
|-----|-------|
| `xs` | 24 |
| `sm` | 32 |
| `md` | n/a |
| `lg` | 48 |
| `xl` | 64 |

**Comment by tw15egan** [comment]
I think if we apply it to DataTable, I would skip the values we don't have (or is there a use-case for adding in that missing value?). I agree, we shouldn't mix what the value of `md` is across components. A user should know `md === 40px`

**Comment by aagonzales** [comment]
I think most components we would probably just add in the skipped value. I'm not so sure about data table though, just skip the `md` value for now I guess.

**Comment by tw15egan** [comment]
@aagonzales I created https://github.com/carbon-design-system/carbon/issues/8370 to properly track the work, and to keep a running list of the components that have / have not been updated

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
