### PR TITLE
fix(tooltip): change default styles

### LINKED ISSUE #6450: [tooltip] definition tooltip enabled state bug
The enabled state for definition tooltip should have a gray underline.

Spec:
Tooltip - White theme Copy

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6450

Updates default styles for `DefinitionTooltip` so that it is `text-02` by default and  `interactive-04` on focus / hover

#### Changelog

**Changed**

- `text-02` by default and  `interactive-04` on focus / hover

#### Testing / Reviewing

`DefinitionTooltip` renders properly

### CODE REVIEW

**Comment by laurenmrice** [comment]
@tw15egan  woo!!! thanks for getting that fixed so fast. We need to actually use `interactive-04` so the blue is lighter in the dark themes. I need to fix that in our design specs.

**Comment by tw15egan** [comment]
@laurenmrice updated 🤘

**Review by laurenmrice — APPROVED** [review]
looks great ! thank you 🚀

**Review by joshblack — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me, just rerunning test suite

**Pull request merged**
