### PR TITLE
feat(Tabs): allow dismissable tabs to have descriptive icons

### LINKED ISSUE #12845: Tabs: provide dismissable tabs with descriptive icon tab layout helper/component
This issue is for ensuring that the presentational/descriptive icon (delivered in https://github.com/carbon-design-system/carbon/issues/12844) and dismissible feature (delivered in https://github.com/carbon-design-system/carbon/issues/12813) for tabs work together as shown in [the spec](https://github.com/carbon-design-system/carbon/issues/8487#issuecomment-1020664248)

This probably needs to be completed after dismissable and presentational icons are both delivered.

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #12845 

#### Changelog

**New**

-Dismissable tabs with icons story + VRT
- Test cases for dismissable tabs with icons
- CSS for new `$prefix}--tabs__nav-item--icon-left` class

**Changed**

- Render tab icon to the left when tab is dismissable

#### Testing / Reviewing

Check that [deployment story](https://deploy-preview-13830--carbon-components-react.netlify.app/?path=/story/components-tabs--dismissable-with-icons) matches [spec](https://github.com/carbon-design-system/carbon/issues/8487#issuecomment-1020664248)
*Added a temporary "contained" toggle to switch between line/contained tabs for review purposes

TODO:

- [x] remove contained control in dismissable with icons story

### CODE REVIEW

**Review by kingtraceyj — APPROVED** [review]
Looks good to go! 💥

**Review by laurenmrice — APPROVED** [review]
Looks good to me. Unrelated, but I noticed that on the disabled state for dismissable tabs, the close icon still gets a pointer mouse cursor. It should be the disabled mouse cursor. I can open a separate issue for this if you want.

**Review by guidari — APPROVED** [review]
I tested locally and LGTM!

**Review by guidari — APPROVED** [review]
I tested locally and LGTM!

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by laurenmrice** [comment]
@francinelucca Yes, it is the intended behavior that if a dismissable tab is disabled, you can not actively close that tab by using the close icon, so the mouse indicator should be the disabled one.

**Comment by francinelucca** [comment]
> @francinelucca Yes, it is the intended behavior that if a dismissable tab is disabled, you can not actively close that tab by using the close icon, so the mouse indicator should be the disabled one. I would say if someone has a different use case for this they could change it on their end.

https://github.com/carbon-design-system/carbon/issues/13897

**Pull request merged**
