### PR TITLE
chore(content-switcher): update styles

### LINKED ISSUE #2092: v10: Content switcher updates
From @lovemecomputer at #2085:

- [ ]  currently there is a disparity btw chrome & other browers: chrome always displays the focus outline after clicking, but other browsers on mac only display the outline when using keyboard navigation. we want to make this consistent across all browsers
    - for the time being, we will make sure the border display on safari & firefox after clicking. it's probably the easiest thing to implement, and is more consistent with other components.

From @laurenmrice at #2085:

- [x] The small rule is showing between hover states. it needs to be hidden or overlapped by the hover.
Screen Shot 2019-03-13 at 4 30 48 PM

- [x] When focusing on a section that is not currently selected. The text color should not change to text-01 it should remain text-02.
Screen Shot 2019-03-13 at 4 33 03 PM

- [ ] If the ellipses occurs, we should include the interaction of having the tooltip to show the full text. This will be the same tooltip used for progress indicator.

### PR DESCRIPTION
**Pull request by aledavila**
Closes #2092 

partially closes ^ 

#### Changelog

**Changed**

- hover state ruler hidden
- focus text no change

Post v10 

- [ ]  If the ellipses occurs, we should include the interaction of having the tooltip to show the full text. This will be the same tooltip used for progress indicator.

- [ ] Focus outline only present on click in Chrome (browser functionality is different)

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
Looks good to me for stop ship items, since we will be addressing JS and ellipses post v10. 👍

**Review by alisonjoseph — APPROVED** [review]
LGTM for what this PR is addressing. 

Did notice the icons are out of alignment here though. 
Screen Shot 2019-03-14 at 1 15 14 PM

**Review by lovemecomputer — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Changes:**

- [x] We do not need the text with icons option for content switcher section for v10.
- [x] There should be no hover state on the options for the disabled content switcher.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @aledavila!

**Review by laurenmrice — APPROVED** [review]
Looks good !! 👍

**Pull request merged**
