### PR TITLE
fix(tabs): match experimental spec

### LINKED ISSUE #1838: Component Design Audit v1.1 - Tabs
## Tabs

- Update width of bottom portion of tab (border-bottom) to 3px

image

- 2px space between tabs (versus 1px)

- See if we can keep type alignment between tabs and content

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1838

This PR incorporates the feedback from the v1.1 audit

some more clarification is needed on the 3rd point though:

> * See if we can keep type alignment between tabs and content

### CODE REVIEW

**Comment by tw15egan** [comment]
It seems like it is just matching up where the content begins relative to the First tab. Could we just add 16px left padding to the tab-content, and possibly create a `bx--tab-content` class? 

screen shot 2019-02-15 at 1 59 49 pm

**Comment by emyarod** [comment]
that's what I initially thought too but apparently [we felt the need to remove that with an `!important` style override](https://github.com/IBM/carbon-components/blob/master/demo/js/components/ComponentExample/component-overrides.scss#L180) since the default example markup includes padding to align the content with the tab label

**Comment by tw15egan** [comment]
I'm guessing that override was for the old tabs, not the experimental tabs. If we need to remove the padding to display the V9 version on the website, we should do it there

**Review by joshblack — APPROVED** [review]

**Comment by jnm2377** [comment]
Did the hover spec change for tabs? I didn't see it in the audit comments so not sure if this happened before audit or there's a bug somewhere, but the hover styles now are different than the original ones (seen on the next site). Screenshots below, hovering on tab 2:

**current**
screen shot 2019-02-19 at 12 38 02 pm

**next site**
screen shot 2019-02-19 at 12 38 17 pm

**Comment by emyarod** [comment]
the hover styles should be fixed now. they were lost when invalid `disabled` attributes were pulled from several components (#1612) and replaced with nested `:not` pseudoclasses

would be nice to confirm the tab content alignment issue, since it's not clear if we want it aligned with the tab title or with the component edge. I would assume component edge to avoid strange whitespace around the tab content but I may be mistaken. this is also an opportunity to examine documentation-only component overrides, since it means the component example we are testing with does not necessarily reflect how the component looks out of the box (with the `!important` rule I referenced earlier being an example)

**Review by aagonzales — APPROVED** [review]
LGTM! 🎉

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
