### PR TITLE
fix(data-table): style audit fixes for data-table

### LINKED ISSUE #7219: [component audit] data table bugs
**Code bugs:**
- [x] `tr` row hover should be using token `hover-ui` and not `hover-field`
- [x] ~In Safari, focus is not appearing on the column headers~ See TJs [comment](https://github.com/carbon-design-system/carbon/issues/7219#issuecomment-721407184) below
- [x] Disabled row styling is missing.
- [x] Zebra stripes: in the G90 and G100 themes the first row and the table headers are blending together. The first row should use the default color and the second row should use the zebra color. (we may need to re-evaluate this from a design perspective but this will resolve the main issue for now).
   image

**Visual bugs:**
- [x] Overflow menu: in G100 theme the menu blends into the table background.
   image

Questions:
- Is the row of a data table supposed to be focusable? I cannot get it to focus in the storybook.
- Is disabling a row or the whole table possible?

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/7219

Style fixes for Data Table

#### Changelog

**New**

- `DataTable w/ Overflow Menu` now uses the `light` prop on the `OverflowMenu`, so it does not display incorrect colors on dark themes. 

**Changed**

- `$hover-field` replaced with `$hover-ui`
- Swapped `even` and `odd` zebra styles to fix the first table row from blending in with the header on dark themes.

#### Testing / Reviewing

Check out the playground story and enable zebra styles. Ensure it looks correct on all themes. Also, take a look at the sorting story and ensure active states look correct in all themes. Lastly, check out the overflow menu story and ensure the overflow menu looks correct in all themes.

### CODE REVIEW

**Review by aagonzales — COMMENTED** [review]
Looks good! Just one thing the hover of the zebra stripes is now off.

**Comment by tw15egan** [comment]
@aagonzales it looks like they all just get `$hover-ui`, is this incorrect?

**Comment by aagonzales** [comment]
Hmm yeah I guess it's just in the dark themes where it looks weird. Or rather hard to tell. It should be fine then.

**Review by aagonzales — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
@tw15egan looks good!

**Pull request merged**
