### PR TITLE
docs(accordion): add displayname for select component proptable

### PR DESCRIPTION
**Pull request by jendowns**
If you look at the `Accordion` story, there is an "Unknown" component (it's the `Select`): http://react.carbondesignsystem.com/?path=/story/accordion--default

You can see `<Unknown>` in the story source and for the `Select`'s proptable.

By adding a display name, the `Select` component is properly shown in the story source and the proptable is properly labeled.

#### Changelog

**Changed**

- add display name for `Select` used inside of `Accordion` story

#### Testing / Reviewing

Check out the React storybook deploy and compare to this live version: http://react.carbondesignsystem.com/?path=/story/accordion--default

### CODE REVIEW

**Comment by abbeyhrt** [comment]
hey @jendowns could you screenshot where it says `<Unknown>` for me? I'm still pretty new to Storybook so I think i'm looking in the wrong places.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Comment by jendowns** [comment]
No worries @abbeyhrt!

When you click on the "show info" button for the default `Accordion` story, you'll see this first `<Unknown>` in the story source (inside the 3rd `AccordionItem`):

Screen Shot 2019-10-02 at 4 08 06 PM

And then scroll almost to the bottom, past a couple prop tables, and you will a prop table for an "unknown component"
Screen Shot 2019-10-02 at 4 08 22 PM

**Comment by abbeyhrt** [comment]
@jendowns Thank you!!

**Review by abbeyhrt — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Pull request merged**
