### PR TITLE
feat(carbon-react): update Downshift to v6

### PR DESCRIPTION
**Pull request by dakahn**
Upgrades us to latest Downshift. Prep work for swapping our `useSelect` in Multiselect to `useMultipleselection` hook and maybe Combobox to `useCombobox`

#### Testing / Reviewing

Check the Downshift components are working as intended:

- [ ] MultiSelect
- [ ] Combobox
- [ ] Dropdown

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Seems like there aren't really any breaking changes with this update outside of TS types, right?

**Comment by joshblack** [comment]
bump @aledavila when you have a sec to review today

**Comment by joshblack** [comment]
One quick note, commit type should be `feat` for the merge commit so this will end up triggering a `minor` release 👍

**Review by aledavila — APPROVED** [review]
everything looks good

**Comment by aledavila** [comment]
waiting on @dakahn to update commit

**Comment by dakahn** [comment]
We've got some broken tests i'm clearing up now @aledavila @joshblack

**Comment by dakahn** [comment]
I'm going to close this up and get the upgrade in with the work i'm doing on #6102 👍

**Pull request closed without merging**
