### PR TITLE
Document TextInput.PasswordInput deprecation and PasswordInput in storybook

### LINKED ISSUE #16213: Document `TextInput.PasswordInput` deprecation and `PasswordInput` in storybook
`TextInput.PasswordInput` is deprecated in v11, to be removed in v12. It's actually the same singular component source behind both exports.

We need to improve documentation in the storybook around this deprecation. It's really confusing wrt the experimental "fluid" inputs too, which is basically a new visual variant of the same component.

```[tasklist]
### To clean things up we could:
- [x] Pop PasswordInput out from under TextInput into it's own section in storybook with overview/default/playground stories
- [x] Pop FluidPasswordInput out from under FluidTextInput into it's own section in storybook with overview/default/playground stories
- [x] Make a note in the `TextInput.mdx` that `TextInput.PasswordInput` is deprecated.
- [x] Add a new label to the monorepo - `component: passwordinput`
```

### PR DESCRIPTION
**Pull request by guidari**
Closes #16213

Added more description to the TextInput.mdx

#### Changelog

**New**

- Create new `FluidPasswordInput.js` file.
- Two new stories called `PasswordInput` and `FluidPasswordInput`
- Added new label `component: password-input` to github repo

#### Testing / Reviewing

- Check if the stories are working as expected;
- Check if the description in TextInput.mdx make sense.

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
This looks great, I am noticing some issues with warn/invalid states for fluid password input.

Screenshot 2024-05-01 at 12 00 40 PM
Screenshot 2024-05-01 at 12 01 34 PM

**Comment by guidari** [comment]
> This looks great, I am noticing some issues with warn/invalid states for fluid password input.

@alisonjoseph  Looks like that was introduced in another PR, the issue is happening in the current version. I'll take a look to see if I can find the bug.

https://react.carbondesignsystem.com/?path=/story/experimental-fluid-components-unstable-fluidtextinput--playground&args=invalid:!true;isPassword:!true

**Review by tay1orjones — APPROVED** [review]
Thanks for updating the avt and vrt tests! I'd be fine rolling what Alison found into a new issue if it's not a quick fix.

**Comment by guidari** [comment]
> Thanks for updating the avt and vrt tests! I'd be fine rolling what Alison found into a new issue if it's not a quick fix.

Yeah, looks trick that one. I created a new issue and assigned myself

https://github.com/carbon-design-system/carbon/issues/16314

**Review by alisonjoseph — APPROVED** [review]
👍LGTM!

**Pull request merged**
