### PR TITLE
style(NumberInput): allow NumberInput to fill its parent container

### LINKED ISSUE #8122: Number input does not fill its parent container
Screen Shot 2021-03-18 at 12 37 49 PM

Noticed on slack, `NumberInput` should behave like all other input elements

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/8122

Matches `NumberInput` to other form elements by allowing the input to fill its parent container. The `NumberInput` itself had `width: 100%` but the wrapper did not have this set as well. 

#### Changelog

**New**

- `width: 100%` added to the `bx--number` wrapper element

#### Testing / Reviewing

Ensure the `NumberInput` fills its parent container

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me pending visual review

**Review by dakahn — APPROVED** [review]

**Comment by joshblack** [comment]
bump @thyhmdo if you have a sec to review!

**Comment by thyhmdo** [comment]
looking at this

**Comment by thyhmdo** [comment]
Looks good to me!

**Review by thyhmdo — APPROVED** [review]

**Pull request merged**
