### PR TITLE
fix(notification): use close20 icon, not close16

### PR DESCRIPTION
**Pull request by jendowns**
Based on conversation here: https://github.com/carbon-design-system/carbon/pull/3283#issuecomment-509766196
This close icon is meant to be `Close20`, not `Close16`

#### Changelog

**Changed**

- changed `Close16` icon to `Close20`

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
cc @jeanservaas if you have a chance!

**Review by alisonjoseph — APPROVED** [review]
👍

**Review by laurenmrice — DISMISSED** [review]
The close icon looks like it is not centered within the notification and a couple pixels closer to the top. It should be visually centered.
Screen Shot 2019-07-10 at 11 02 41 AM

**Comment by jendowns** [comment]
Thanks @laurenmrice!

I have centered the icon inside the close button & that should be visible in the preview shortly 👍 

One thing I did notice though, that I wanted to bring to your attention --

The lockup with the title + subtitle, per my latest update, looks great and appears to align exactly:
Screen Shot 2019-07-10 at 11 16 53 AM

But if there is a significantly long subtitle in the `Notification` then the lockup with the title is off like this:

Screen Shot 2019-07-10 at 11 17 41 AM

Is this acceptable to you, or should I fix the title-to-icon lockup as well? I'm not 100% sure what the cause is, as I haven't examined it too closely... the title and subtitle appear to have the same vertical padding (i.e., none) and same line height 🤔 Could be weight related?

**Comment by laurenmrice** [comment]
Yes, the single one looks great now. 👍 For the multi-line it would be good to get that close icon visually center with the title, because now it looks bottom heavy.

**Comment by jendowns** [comment]
Thanks again @laurenmrice! I increased the `line-height` for the `InlineNotification` title, and now it looks lined-up when the subtitle is super long. Could you take another look when you get a chance & let me know what you think?

**Review by tw15egan — APPROVED** [review]
Looks good once @laurenmrice signs off 👍

**Comment by laurenmrice** [comment]
Those look good now! Quick question: Should I approve this pr since `inline notification` is good to go? I noticed we still need to make close icon changes/alignments for `toast notification` and `modal`, but we could do those in separate prs

**Comment by jeanservaas** [comment]
Agree with @laurenmrice -- this PR looks good! 

Just wondering if we should merge the 20px close icon in without updating it in toast and modal too.

**Pull request merged**
