### PR TITLE
fix(icons-vue): update import for vue 2/3 interop

### LINKED ISSUE #7833: vue - @carbon/icon-builder-helpers cause compiler warning on vue 2.x due to vue 3.x adaptation
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

The line I'm talking about here can be found [in commit `aebf79e` line 9](https://github.com/carbon-design-system/carbon/commit/aebf79e433239061d76ab78dc1e8b8911de81d1f#diff-be769708c4f1685c1044e00822eb6509939573db0bc3ac5271780eeea47a1641R9) which causes an import warning when using vue 2.x. It will work fine for vue 3.x as this function has the intended use in vue 3.x but vue 2.x is still the goto version. Replacing this with:
```diff
- import { h } from 'vue';
+ const {h} = require('vue');
```
would fix the issue due to the non-evaluated export tree. `h` will stay `undefined` due to the `require` function definition as it is supposed to do.If I'm using the package in a wrong way, I'm looking forward to be corrected. Code example can be found below.

Caused error message:
```bash
# [...]
 warning  in ./node_modules/@carbon/icons-vue/es/utils-7a44a5de.js

export 'h' was not found in 'vue'
# [...]
```

## Steps to reproduce the issue

1. Create a new vue project.
2. Add `@carbon/vue` and `@carbon/icons-vue`.
3. Use the below `main.js`.

## Additional information
```js
import Vue from 'vue'
import 'carbon-components/css/carbon-components.css'
import CarbonComponentsVue from '@carbon/vue/src/index'

Vue.config.productionTip = false

Vue.use(CarbonComponentsVue)

import { CarbonIconsVue } from '@carbon/icons-vue'
import AppSwitcher20 from '@carbon/icons-vue/es/app-switcher/20'

Vue.use(CarbonIconsVue, {
  components: {
    AppSwitcher20
  }
})

import App from './App.vue'

new Vue({
  render: h => h(App),
}).$mount('#app')
```

### PR DESCRIPTION
**Pull request by joshblack**
Closes #7833

Update the import pattern to address Vue 2/3 interop issues.

cc @lee-chase 

#### Changelog

**New**

**Changed**

- Update import pattern for ESM exports for Vue 2/3 interop

**Removed**

#### Testing / Reviewing

- Verify that the issue from #7833 no longer exists

### CODE REVIEW

**Comment by lee-chase** [comment]
Not sure if it is me @joshblack but when I build this I still get the following in my es folder.

```
import { getAttributes } from '@carbon/icon-helpers';
import { h } from 'vue';
```

**Comment by joshblack** [comment]
@lee-chase ahh, same. I think `rollup` may be re-writing it. I might have to close this one out then if I can't figure out how to make rollup respect the syntax 🤔

**Comment by joshblack** [comment]
@lee-chase I _think_ I found a fix with dynamic lookup on the export 👀  Just pushed up the changes

**Comment by lee-chase** [comment]
Works for me in both Vue 2 and Vue 3, I have tested here https://github.com/lee-chase/vue-2-carbon-icon-test and here https://github.com/lee-chase/vue-3-carbon-icon-test in previous load pattern and that shown in the issue #7833 .

**Comment by joshblack** [comment]
Nice! So seems like it should be good @lee-chase, or am I misunderstanding?

bump @dakahn @jnm2377 let me know if you have any questions!

**Review by lee-chase — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]
🔥 Thanks for adding the comment too, it was very helpful!

**Pull request merged**
