### PR TITLE
 feat(cli): add contribute commands

### PR DESCRIPTION
**Pull request by joshblack**
Add in a `contribute` command dir for `@carbon/cli`

#### Changelog

**New**

- Add in support for `contribute setup` command for `@carbon/cli`

**Changed**

- Update `@carbon/cli` to use `commandDir` pattern

**Removed**

#### Testing / Reviewing

- You can pull down this PR and reference the CLI with the path `./packages/cli/bin/carbon-cli.js`
- You can run the specific command being added by doing: `./packages/cli/bin/carbon-cli.js contribute setup`

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
tested with gh token, looks good to me! (except on win10 related #2434)

**Review by jnm2377 — APPROVED** [review]
Works great! 🎉 did run into one small issue, opened an issue for it here: https://github.com/carbon-design-system/carbon/issues/3164

**Review by tw15egan — APPROVED** [review]
Very nice! 👍

**Review by lovemecomputer — APPROVED** [review]
rad!

**Review by cal-smith — APPROVED** [review]
This looks really neat!

**Pull request merged**
