### PR TITLE
fix(dropdown): match experimental spec

### LINKED ISSUE #1955: [Audit] Dropdown
## Dropdown

- [ ] Should dropdown be using listbox styles? Should we pull out listbox into a set of tools to apply styles instead of shared styles for each?

- [x] Should use `body-short-01` for placeholder text and value

- [x] What should focus be for error state? cc @laurenmrice Currently it's a red border

- [ ] All dropdown versions should be pulling the 16 icon. I think this is the old icon.

## Inline Dropdown

- [x] Should use `body-short-01` for text

- [x] Bounding box should have only `8px` of padding on left hand side

Expected:

image

Actual:

image

- [ ] Width of control seems off from spec

Expected:

image

Actual:

screen shot 2019-02-28 at 10 46 59 am

## Filterable Dropdown (Combobox), MultiSelects, etc.

These all use `list-box` and will most likely share updates

- [x] Should use `body-short-01` for text
- [x] Disabled -> hover seems to still have hover color
- [ ] Need to verify in React repo for functionality

### LINKED ISSUE #2041: [Audit] Dropdown error state icon
This should be pulling the 16 icon. I think this is the old icon.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1955 

Closes #2041

Depends on #1987 #2020 https://github.com/IBM/carbon-components/pull/2064

This PR incorporates feedback from the February 2019 dropdown component audit

### CODE REVIEW

**Comment by asudoh** [comment]
Removing blocked label as both of the dependencies @emyarod marked have been merged.

**Comment by asudoh** [comment]
Also removing question label as @emyarod question seems to have been addressed. @emyarod please don't hesitate to add question and re-add question label if you have any remaining questions - Thanks!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**For all dropdown variations:**

- [x] The top label is still getting a selected-ui color when open. It should always remain field-01 with a ui-03 1px full width rule underneath when open. Dropdown does still get the hover color when closed.  Ref #1955 

Screen Shot 2019-03-11 at 12 50 21 PM

- [x] When selecting a new option in the dropdown, the background color should go to color token selected-ui (#dcdcdc) on-click. Right now it looks too dark. Ref #1955


- [x] The Option text in the drawer by default should be text-02 color (#565656). The Option text turns text-01 (#171717) when it gets a hover or selection background. Right now they are all still #171717. Ref #1955

Focus:
- [x] The focus outline of the first option in the dropdown when it is open needs to be flush against the sides of the menu. Right now it is hanging. Ref #1955
Screen Shot 2019-03-11 at 1 10 12 PM

Error:
~The current error icon is not pulling in the correct icon. Ref #2041. Should be the 16/warning—filled  https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fwarning--filled~ It is pulling in the right icon. Disregard this comment.

Disabled:
- [x] For disabled versions, the text and icon need to be disabled-02 color (#bebebe)


**Dropdown**
- [x] For normal dropdowns: Update padding to 16px on right of the chevron icon. Right now it still looks like its 8px. Ref #1955 
Screen Shot 2019-03-11 at 12 56 07 PM

**Inline Dropdowns**
- [ ] Inline dropdowns do not need helper text. (A user could potentially use a tooltip icon instead for this instance, but we are leaving this out until we get a usecase for needing this. This should be updated in documentation as well.)
- [x] The error version of the inline dropdown isn’t resizing properly. The icons are too far away from the text.

**Comment by asudoh** [comment]
@emyarod Is this ready for another visual review...? Thanks!

**Comment by emyarod** [comment]
yes @asudoh we will be reviewing the remaining points tomorrow

**Review by laurenmrice — CHANGES_REQUESTED** [review]
A couple more changes:

**All dropdowns:**
- [ ]  When the focus is on an option in the drawer, now the rule at the bottom is showing next to the focus box. The focus needs to overlap/hide the rule.
Screen Shot 2019-03-12 at 4 36 31 PM

**Inline dropdown:** 
- [x] The disabled state variation gets a focus box. Needs to be omitted.
Screen Shot 2019-03-12 at 4 34 28 PM

- [x] The error state variation, after selecting an option it only gets a focus border around the text. It needs to include the icons as well. Also when selecting an option with a smaller text length the icons are not adapting in space to the type.
Screen Shot 2019-03-12 at 4 34 42 PM

- [x] The hover, focus border and error border need to be the same width and height. They all need to be 32px tall like the error border.
Screen Shot 2019-03-12 at 4 57 01 PM

- [x] I don't know if this can be fixed, but sometimes this top rule appears in the inline select dropdown when its open. Just seems like a glitch.
Screen Shot 2019-03-12 at 5 02 14 PM

**Comment by asudoh** [comment]
Hi @emyarod what's blocking this PR? Thanks!

**Comment by emyarod** [comment]
@asudoh this PR is also affected by #2064

**Comment by emyarod** [comment]
@laurenmrice I'm not able to replicate the issues with the rules in the menu list, but let's double check it's not a cached stylesheet or something

**Comment by asudoh** [comment]
Removing "blocked" label as the dependency is resolved. @emyarod Is this ready for another visual review? Thanks!

**Comment by emyarod** [comment]
yes @asudoh this is ready for another visual review

**Comment by emyarod** [comment]
all points have been addressed @laurenmrice with the exception of the bottom rule remaining after a focused menu item. 

Originally the rule was covered by the focus outline, but this caused another visual bug where an adjacent hovered item would overlap with the focus outline, like so:

image

and fixing that bug reveals the rule. Because of how our markup is structured and the limitations of CSS3 selectors, we most likely need JavaScript to fully implement this cc @asudoh

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Alright one last change, everything else looks good.

- [x] For inline dropdown, the drawers option text doesn't line up vertically with the label text above it. This is only happening for inline dropdown, the other dropdowns look correct.
Screen Shot 2019-03-13 at 1 07 33 PM

**Comment by emyarod** [comment]
should be resolved now @laurenmrice !

**Review by laurenmrice — APPROVED** [review]
Ok this looks good to me so going to approve. 👍 

*Note:
For the focus showing bottom rule problem, this can only be resolved with JS because of the limitation of CSS3 selectors which needs further development discussion (Andrew and Akira).

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
