### PR TITLE
fix(CodeSnippet): adjust calculation when show more button is clicked

### LINKED ISSUE #15774: [Bug]: Nothing happen when I clicked on "Show more"  in <CodeSnippet> component.
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.49.0

### React version

v17.0.2

### Description

The `Show more` button does not cause the windows to enlarge when the string is sufficiently short. The `Show more` button functions when the string is longer. It appears that there is a calculation error with the `Show more` button.

### Reproduction/example

https://stackblitz.com/edit/github-kjuqye?file=src%2FApp.jsx

### Steps to reproduce

Create a multiline code snippet with sufficiently short string and try to click on `Show more` button. We noticed this in Windows Chrome environment. 

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15774

Based on this [comment](https://github.com/carbon-design-system/carbon/issues/15774#issuecomment-1968943215), I've adjusted the default `minExpandedNumberOfRows` to `0`.

#### Changelog

**Changed**

- adjusted the default `minExpandedNumberOfRows` to `0`

#### Testing / Reviewing

View the test story in `CodeSnippet` on a Windows machine and ensure there are no visual bugs.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Maybe I'm missing what this is trying to fix, but I think the show more button shouldn't be showing at all in the test story since the code block fits entirely in the window. I'm seeing the same issue in windows and mac.

**Comment by tw15egan** [comment]
@alisonjoseph I tweaked some things so it should now appropriately show / hide the button as well

**Review by alisonjoseph — APPROVED** [review]
Nice, LGTM!

**Review by guidari — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
