### PR TITLE
test: adding unit tests for ProgressIndicatorSkeleton

### LINKED ISSUE #17472: Increase `ProgressIndicator.Skeleton` unit test coverage

### PR DESCRIPTION
**Pull request by mariat189**
Closes #17472

This PR adds unit tests for the ProgressIndicatorSkeleton component to ensure its proper rendering and functionality. The The tests ensure that the skeleton renders with the appropriate class names, accommodates custom class names etc.

#### Changelog

**Changed**

- Added Unit test file for ProgressIndicatorSkeleton

#### Testing / Reviewing

- Run the test suite to ensure that all new tests pass.
- Review the tests for clarity and coverage.
#### Additional Notes
- Please let me know if any further modifications are needed or if you have any questions regarding the changes.

### CODE REVIEW

**Review by guidari — APPROVED** [review]
LGTM! 🚀
Thanks for doing that!

**Review by kennylam — APPROVED** [review]
LGTM! Just need to resolve the conflicts.

**Comment by mariat189** [comment]
Hi @kennylam , I have resolved the conflicts. Can you please recheck?

**Comment by mariat189** [comment]
@kennylam , @guidari
Can you please recheck this pr?

**Pull request merged**
