### PR TITLE
ci(release-v10): remove deprecated action, call github API directly

### PR DESCRIPTION
**Pull request by tay1orjones**
Ref https://github.com/carbon-design-system/carbon/issues/12500

Same as https://github.com/carbon-design-system/carbon/pull/13017, just for the v10 branch

### CODE REVIEW

**Comment by andreancardona** [comment]
@tay1orjones not sure why the v10 tests are failing but looks like they are

**Review by andreancardona — CHANGES_REQUESTED** [review]
@tay1orjones not sure why the v10 tests are failing but looks like they are

**Comment by tay1orjones** [comment]
@andreancardona Looks like it was just a fluke - the checkout action didn't get a response from GitHub. Re-ran it and it's now passing 👍

**Review by tw15egan — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
💯 lgtm!

**Pull request merged**
