### PR TITLE
feat(DataTable): allow additional contents to expand cells

### LINKED ISSUE #5028: Data Table Expand Row needs the ability to add text (hidden or visual) to table header
Windows

> Browser\
Chrome/FireFox/IE

> Automated testing tool and ruleset

> Assistive technology used to verify
WAVE/Jaws

## Detailed description
When using <TableExpandedRow><TableExpandedHeader> there should be a way to add either a visual or hidden text for screen readers "Expanded" to allow that row to have a non-empty header.

Violates WCAG 2.0/2.1 1.3.1 Info and Relationships (Level A)

> What version of the Carbon Design System are you using?
10.3.0 / React 7.3.0

> What did you expect to happen?
That the <TableExpandHeader would give me the ability to add props for "setHeaderText("string") and showHeaderText(true/false). If setHeaderText is not empty, it would either visually show the text on the column header or if false, arrange that it is positioned off-left and readable by screen readers.

> What happened instead?

> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Set up a Data Table with a TableExpandedRow 
2. Verify page in WAVE
3. Note that WAVE fails for Empty table header
4. etc.

> Please create a reduced test case in CodeSandbox
https://2bvnv.csb.app/

## Additional information

- Screenshots or code
image

- Notes

### PR DESCRIPTION
**Pull request by asudoh**
This change adds `children` prop support to `<TableExpandHeader>`. This provides applications with more control so application can better describe the expand cell.

Fixes #5028.

#### Changelog

**New**

- `children` prop support to `<TableExpandHeader>`.

#### Testing / Reviewing

Testing should make sure our data table is not broken.

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM

**Review by joshblack — COMMENTED** [review]
Do we need to add a prop type for `children`? If so, should it be `PropTypes.string` or `PropTypes.node`? 🤔

**Review by emyarod — APPROVED** [review]
looks good to me, I'm leaning towards setting the `children` prop type to `string` based on current usage examples

**Comment by tw15egan** [comment]
If they are going to need to hide whatever text they place there for a11y purposes, they're going to have to pass in a node with a `visually-hidden` class, so I'm leaning towards `node`

**Comment by joshblack** [comment]
If we're adding this for a11y should we wrap `children` in `bx--assistive-text` (or visually hidden) and set the prop type as string?

**Comment by tw15egan** [comment]
@joshblack depends on if this is the _only_ use case we have for adding this text. If yes, then yeah we might as well hook it all up for them. Not sure if users will ever need this content to be visible

**Comment by joshblack** [comment]
Totally fair!

Real quick, when looking at the original issue are they looking for the `aria-label` prop to label the button in the `th`?

**Comment by asudoh** [comment]
> Real quick, when looking at the original issue are they looking for the `aria-label` prop to label the button in the `th`?

Quick look at the original issue I couldn't find any mention of `aria-label`, but let us know if there was what led to such thoughts.

**Comment by joshblack** [comment]
I think it's just me misunderstanding things, thanks for checking in! It does seem like we'd want to go down the route of giving the option to supply text to be announced by a screen reader but not necessarily have it visually rendered, would that make sense with how everyone is interpreting this with respect to the data table design?

**Comment by asudoh** [comment]
> It does seem like we'd want to go down the route of giving the option to supply text to be announced by a screen reader but not necessarily have it visually rendered, would that make sense with how everyone is interpreting this with respect to the data table design?

Looking at #5028, the hard requirement seems the ability for application to add text to table expand cells. It makes sense for the sake of flexibility. The specifics above may have some room for discussion, so what #5028 requests for sounds a good stop-gap.

**Review by joshblack — APPROVED** [review]

**Pull request merged**
