### PR TITLE
fix(StructuredList): add role attribute to StructuredListRow

### PR DESCRIPTION
**Pull request by atikenny**
Relates to #4828

Fix the accessibility problem in the StrcuturedListRow.

#### Changelog

**Changed**

- added the row role to the `StructuredListRow`

#### Testing / Reviewing

Check the accessibility of the component in Storybook using the IBM Able Chrome plugin.

#### Note

Tried to fix the related issue about the missing role for the label but that invalidates another rule that labels cannot have roles specified.

### CODE REVIEW

**Comment by atikenny** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by tay1orjones** [comment]
> Fix the accessibility problem in the StrcuturedListRow.

@atikenny could you clarify what the specific problem is that this change solves?

StructuredList was updated recently with some accessibility improvements https://github.com/carbon-design-system/carbon/pull/8172, though I believe they're all behind the v11 flag for now.  @dakahn was this addressed as part of it - moving away from the `table` role to the `grid` role?

**Comment by atikenny** [comment]
> > Fix the accessibility problem in the StrcuturedListRow.
> 
> @atikenny could you clarify what the specific problem is that this change solves?
> 
> StructuredList was updated recently with some accessibility improvements #8172, though I believe they're all behind the v11 flag for now. @dakahn was this addressed as part of it - moving away from the `table` role to the `grid` role?

This PR fixes the original problem with the `table` role missing a `row` role in it.

**Review by andreancardona — APPROVED** [review]

**Review by dakahn — CHANGES_REQUESTED** [review]
@tay1orjones we have a total accessibility overhaul behind our feature flags right now yeah. But as for fixing existing problems with v10 StructuredList I'm all for that. I still see 16 errors for `role="row"` in my Accessibility Checker though 👀

**Comment by atikenny** [comment]
> @tay1orjones we have a total accessibility overhaul behind our feature flags right now yeah. But as for fixing existing problems with v10 StructuredList I'm all for that. I still see 16 errors for `role="row"` in my Accessibility Checker though 👀

I tried fixing those as well, but unfortunately, I wasn't able to (it used to be 20 problems now it's 16).
The problem is that instead of a table we use a collection of divs and labels. But we would also like to use a label as a row in that table. This is impossible with the table design, but we cannot ditch the label as then we would lose the selection use-case of this component.

**Review by dakahn — APPROVED** [review]
i mean i'm cool with this. It fixes four errors 🏄🏽

**Review by tay1orjones — APPROVED** [review]
Thanks for the input @dakahn!

**Pull request merged**
