### PR TITLE
fix(skeleton): update color tokens

### LINKED ISSUE #3220: [Skeleton] v9 color spotted in v10 skeleton state
## V9 color spotted in V10 skeleton state 😱 

I'm guessing skeleton token is not used here. Dark theme skeletons are showing v9 colors (blue). Should be using `$skeleton-01` and `$skeleton-02`.

image

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3220.

#### Changelog

**Changed**

- Updated skeleton to use `$skeleton-01`/`$skeleton-02` tokens.

#### Testing / Reviewing

Testing should make sure skeleton is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me pending design review

**Review by joshblack — APPROVED** [review]

**Comment by jeanservaas** [comment]
Hi @asudoh !

Sorry for the delay on approval here -- I read @shixiedesign's issue and it does seem like the token change is to spec. However, I'm noticing some discrepancies in the values for the skeleton tokens.

- I searched Git and I can't find Shixie's design/animation spec for the skeleton state. I wanted to double check it because I noticed that incorporating the @skeleton-02 token in the light themes seems very dark. I wanted to make sure this was intentional.

- This may not be a token issue... it may just be a value issue, in which case we could merge this PR and open another issue... but I want to make sure. I will ask @laurenmrice when she's in too, because she probably has more insight.

**$skeleton-02 value is very dark in light themes**
image


**skeleton token values (at least for G90) are incorrect on the Carbon site**
image


**Netlify elements preview is showing different values for G90 skeleton tokens then the website, which one is right?**
image

**Comment by joshblack** [comment]
@jeanservaas per your elements question, whatever is rendering in the preview is the latest value in code. If we need to change that, definitely not a problem! Although I'm sorry this doesn't help you figure out which value is actually correct 😓 lol

**Comment by asudoh** [comment]
Thanks @jeanservaas for the feedback! What I know wrt the spec is only that we should use `$skeleton-01`/`$skeleton-02` color tokens, so sounds that we need to have color spec for different themes.

**Review by aagonzales — APPROVED** [review]
Tokens are correct, we'll open a separate issue later for the values if we need to change them.

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
