### PR TITLE
[Don't Merge] UIShell(feat): Update shell to use context

### PR DESCRIPTION
**Pull request by vpicone**
This is just an initial demo to show how context could work for us. I think it makes the UIShell much easier to use, more adaptable to custom components, and allows us to scale to more complex state far easier than the renderprop/prop getter pattern.

TODO:
- [ ] Update other stories
- [ ] Ensure presentational/controlled mode compatability
- [ ] default values
- [ ] general cleanup/api uniformity

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thanks @vpicone for sharing your prototype. As I mentioned in the discussion, please don't bake in context integration to our UI components. Putting it to `<HeaderContainer>` is good, though.

**Comment by vpicone** [comment]
@asudoh If we duplicate the context in the SideNav as well it would make the wrapper only necessary with a header/right panel present. Otherwise the SideNav is dependant on the wrapper to share state with the menu items.

**Comment by vpicone** [comment]
I don't know what you mean by 'bake context integration into ui components'. Do you mean the `useContext` values? That's the whole point behind context, is to share the state with children?

If we don't use context, they wrapper state (context) needs to be 'baked in' by mandatory render props. 

As you can see in this demo, any props passed in to the SideNav override the context values.

**Comment by asudoh** [comment]
Non-ui components can have context and should pass along context values to UI components like side nav via props.

**Comment by vpicone** [comment]
@asudoh What is your reasoning behind that? If a component can accept props those props take precedence over context I don't see the point of adding _another_ wrapper. Dan Abramov has recently walked back his presentational/data component ideas in favor of hooks based solutions like this one:

>    Update from 2019: I wrote this article a long time ago and my views have since evolved. In particular, I don’t suggest splitting your components like this anymore. If you find it natural in your codebase, this pattern can be handy. But I’ve seen it enforced without any necessity and with almost dogmatic fervor far too many times. The main reason I found it useful was because it let me separate complex stateful logic from other aspects of the component. Hooks let me do the same thing without an arbitrary division. This text is left intact for historical reasons but don’t take it too seriously.

[source](https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0/#99d5)

**Comment by asudoh** [comment]
Our component library has been written in a way of writing components that do one thing and do it well and easy to work together, instead of keeping adding features to components. I'd like to see us keep that principle.

**Comment by vpicone** [comment]
@asudoh a wrapper container like the one you describe is no different than render props. It requires the developer to apply the correct props to every subscribing component in order for the component to render properly. I would argue this has not been very effective for the data table component. 

I don't necessarily think past precedent should be used to prevent better solutions when they come along.

**Comment by asudoh** [comment]
Sounds that there is a temptation to overly avoid props drill-down. Props drill-down is the proper way for components work together, and I'd like to see us not being attracted to short-circuit that.

**Comment by vpicone** [comment]
@asudoh It has nothing to do with prop drilling, all of these components live relatively closely nested and in the same component. We need to share wrapper state with all of the nested children. We've done this with render-props in the past. However, passing is sideNavExpanded setSideNavExpanded sideNavPinned setSideNavPinned to both the SideNav and the menu items is laborious. 
Using context is to prevent forcing developers to pass down the correct carbon-provided props just for our own carbon components to render properly.

You can compare the rail story to the other previous UI shell stories to see how much easier it is to use the shell with this approach. Keep in my the other stories don't account for a pinned nav state or supply the relevant state to sub menus (which my approach here does).

**Comment by asudoh** [comment]
Probably the detail of the wording aside, I'd like to see us not being tempted too much on short-circuiting that area.

**Comment by joshblack** [comment]
@asudoh what's your primary concern when it comes to using context in components? Is it that they are now coupled to the context provider and folks can't implement their own state management if they wanted to? Or something else? Code snippets to help demonstrate would also be super helpful 🙏

**Comment by asudoh** [comment]
> Is it that they are now coupled to the context provider and folks can't implement their own state management if they wanted to?

It's the former half. Even if the component still works without context, having context in an application changes the behavior of components, instead of components having clear API contract with props.

**Comment by joshblack** [comment]
@asudoh wouldn't the API contract be the context shape provided by the explicit usage of `useContext(ContextProvider)`? What do you mean by it changes the behavior? Would love code snippets or examples to help ground this and help me better understand 👍

**Comment by asudoh** [comment]
Context works in a similar way as global variables. Baking context feature into UI components adds [the complexity of global variables](http://misko.hevery.com/code-reviewers-guide/flaw-brittle-global-state-singletons/).

**Comment by vpicone** [comment]
@asudoh The context is contained within the HeaderContainer or a developer's own context provider, not global.

Re: 'clear API contract with props'. The menu's already maintain their own state (no clear api contract with props). There's also nothing stopping devs from passing props and controlling the component themselves (in which case context is ignored)

**Comment by joshblack** [comment]
@asudoh I'm not sure I understand the analogy to global variables, singletons, or global state. It very much so is not global state as it is, by definition, not globally accessible. Components choose to opt-in and use these patterns.

**Comment by asudoh** [comment]
Not exactly global, but works in a very similar way as globals. Having context dependency to a component removes the consistency how the component works in isolation vs. how the component works in an integrated manner.

**Comment by joshblack** [comment]
> Having context dependency to a component removes the consistency how the component works in isolation vs. how the component works in an integrated manner.

Do you have an example to help illustrate this? Does this idea make sense in the context of UI Shell where we would most likely not want to use these components in isolation?

**Comment by vpicone** [comment]
The behavior is the same in isolation between render props and context. The only difference is it vastly decreases the complexity of implementing these components together (like @joshblack said, likely the default state).

**Comment by vpicone** [comment]
>Props drill-down is the proper way for components work together

That is definitely true in applications where you control the total flow of state through props. However if the choice is between prop getters and context, I'm going to pick context every time. Keep in mind prop getters are necessary for us to share new pieces of state without breaking changes. They also abstract away the API in a way that is not clear for the developer. `getTableProps()` vs `useContext(DataTableContext)` offer the same abstraction, except the prop getter is extra work/clutter for the developer for no reason.

**Comment by asudoh** [comment]
If props seen in `<Component foo="Foo" ...>` are not the only factor that affects component's behavior, people have to figure out what other places in the app affect the components behavior.

**Comment by joshblack** [comment]
@asudoh code here will help a ton to better understand the exact case you're thinking about. I think we need to remember that not everything in a component needs to be exposed, we only need to expose the public API, e.g. things we want to be configurable. If there is no need for a consumer to use or configure this info, we wouldn't need to expose it as props.

**Comment by vpicone** [comment]
Also, for `<Component foo="Foo" ...>` the foo prop would take precedence over context so there wouldn't be other places in the app affecting the behavior simultaneously.

**Comment by tw15egan** [comment]
For me, personally, this would make handling all the different states between Side Nav, Hamburger Menu and (eventually) Right Panel much more manageable. I'd like to see what @jnm2377 and @aledavila think about this as well

**Comment by jnm2377** [comment]
I had initially planned on using context for this functionality but based on these comments it seemed like more people thought it would be more manageable _not_ using context. https://github.com/carbon-design-system/carbon/pull/2846#discussion_r287962017

**Comment by vpicone** [comment]
@jnm2377 that render prop example looks okay in examples like that when there’s only one prop but when there’s multiple (isExpanded, setExpanded, isPinned, setPinned) and you also have to supply some of those props to the menu items, header and right panel it gets really gnarley.

**Comment by vpicone** [comment]
I’d definitely encourage you guys to try writing the render prop version of what I have here (supplying state to menus and allowing for sidebar to be pinned). It’s...unsettling.

**Comment by aledavila** [comment]
I do agree that doing the render prop example wouldn't be great. Not only what Vince mentioned but there more things to handle and consider than we think. Not only those 3 but also all the other "header actions" that people can add to the header. We just have too many working parts to it. The way vince explained context to me in the beginning made it seem like a clean solution.

**Comment by joshblack** [comment]
Are we tackling this in this project cycle? If not, should we close and re-open when this gets picked up?

**Comment by jnm2377** [comment]
@joshblack I think it's fine to close this now. It's not something we've prioritized this iteration since we're not working on UI shell or component enhancements (I see this more as an enhancement rather than a bug). Plus there seems to be a lot of discussion still going on around this. Perhaps this is something we can talk about in one of our dev meetings and come to a consensus about (Idk what the rule of thumb is for RFC decisions, majority rules or unanimous agreement?).

**Comment by vpicone** [comment]
@jnm2377 The side nav with rail aspect of the shell is non-functional as-is. Are we gonna put that off as well?

**Comment by joshblack** [comment]
@vpicone I think this boils down to project planning yeah? I'm not sure if this fits into a project at the moment, if this is a concern we should 100% bring it up in our core channel to figure out how to proceed!

**Comment by dakahn** [comment]
UIShell is the first big project the Accessibility team are tackling next cycle and I want to reopen this PR in particular. 

These changes are meaningful and would greatly simplify debugging and enhancement work in the future. 

Let's get this in 👍

**Comment by vpicone** [comment]
Closing for the systems squad to explore if prioritized https://github.com/carbon-design-system/carbon/issues/4735

**Pull request closed without merging**
