### PR TITLE
feat(tile): add ignoreLinkClicks and ignoreTextSelection props

### LINKED ISSUE #3642: [Tile] Not collapsing the expandable tile on link click or text select
### Summary

If the expandable tile's below the fold content contains links or text, then if the user clicks a link / selects some text, then the tile should not collapse. 

### Justification

Users are annoyed when they try to copy/paste from below the fold content and the tile collapses. Similarly for clicking links. In those cases, they probably didn't want the tile to collapse. 

### Desired UX and success metrics

Clicking a link or selecting text does not collapse the expandable tile. 

### "Must have" functionality

Clicking a link or selecting text does not collapse the expandable tile. 

We'd be happy with this being either default behavior or something that is toggled by a property. 

### Specific timeline issues / requests

No specific timeline. in particular we would like to use this enhancement on the IBM Cloud deploy toolchain page: https://cloud.ibm.com/devops/setup/deploy?repository=https%3A%2F%2Fgithub.com%2Fopen-toolchain%2Fsecure-kube-toolchain&env_id=ibm:yp:us-east

### Available extra resources

If we agree to add this enhancement, I can make the PR.

### PR DESCRIPTION
**Pull request by keithkade**
Closes #3642 

Add optional prop to disable tile toggle on based on the event details. For example, we might disable toggle on link click or on text select

#### Changelog

**New**

- `onBeforeClick` prop for `ExpandableTile`

#### Testing / Reviewing

Default behavior is unchanged. To validate the new prop, you can pass in a function with whatever criteria you want to use to possibly reject a click event. I added a unit test that does so based on the event target being a link

### CODE REVIEW

**Comment by keithkade** [comment]
Open to any and all suggestions for how this should work. My hope with splitting it like this was to give developers the most flexibility in how the component functions

**Review by asudoh — COMMENTED** [review]
Hi 👋 thank you for jumping in! For this kind of use case, I'd suggest we introduce `onBeforeClick()` callback with the raw event object passed along, and let application return `false` to prevent the tile being collapsed. In this way we don't have to add another prop/check to cope with another possible condition that should prevent tile from being closed.

**Comment by keithkade** [comment]
@asudoh I like that solution much better. will adjust the PR accordingly

**Review by jnm2377 — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @keithkade!

**Pull request merged**
