### PR TITLE
fix(list-box): match experimental spec

### LINKED ISSUE #2167: Match listbox to experimental spec
Several of our React components inherit listbox markup and styles, which have not yet been updated to match the new spec

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2167 

Related: https://github.com/IBM/carbon-components-react/issues/2022

This PR modifies the base listbox to match the experimental spec and lay the foundation for MultiSelect, ComboBox, and DropdownV2 changes in React

#### Changelog

**New**

- invalid state support
- docs examples

**Changed**

- listbox hover color
- spacing for inline and block level listbox elements
- listbox menu list max-height

**Removed**

- redundant styles

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Great work - Thanks @emyarod! Two things:

* Given usage of CSS grid, test needs to be done with IE11 (though we are drifting away from IE11, we cannot deliberately break IE11 until we get broader consensus from product teams)
* Though this PR seems to attempt to completely separate `v9`/`v10` markups, I couldn't be sure if `v9` markup is kept intact. If it's intact, great to have an info on what line went where, etc. Otherwise `v9` needs test as well.

**Comment by emyarod** [comment]
yeah @asudoh from my testing on IE11 the inconsistencies seemed to be on par with most of our other flex or grid components when viewed in IE11. I used grid here because I initially wanted to reduce markup changes as much as possible especially since multiple components are based on listbox. That being said, I am willing to refactor using the wrapper div approach like I used for some other form components if we would ultimately prefer that

the v9 markup is completely preserved after this line. I just removed the if/else blocks for the new icon SVGs and left the legacy icons

**Review by asudoh — APPROVED** [review]
Great thanks @emyarod for explaining! - Unless IE11 is completely unusable we'll be fine.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Changes:**

All list boxes:
- [x] There is a weird glitch of color overlays on open drawers in Safari.
Screen Shot 2019-03-22 at 8 12 20 AM

Light and Inline:
- [x] When hovering inside the drawer, the top label is getting a field color change. It should not have color behind it.
Screen Shot 2019-03-22 at 8 13 10 AM

Inline:
- [x] The default state should not have an underline and neither should the open state.
Screen Shot 2019-03-22 at 8 14 37 AM

- [x] All of the versions for this (except for the first validation state, that looks fine) need to have the chevron 8px from the text. Right now it is too far away.
Screen Shot 2019-03-22 at 8 21 27 AM

**Comment by emyarod** [comment]
thanks for the feedback! this is ready for another review @laurenmrice

**Comment by shixiedesign** [comment]
Hey I'm jumping in only because we are near code freeze, @laurenmrice @emyarod. I still see one error:

**Only in light variant for both regular and inline:** 

- [x] The opened drawer options should have White background too, should be `$field-02` token, same as the dropdown's closed state background.
image

Other than that, it's all good to me!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
I think only one more thing:
- [x] After clicking on the inline dropdown and hovering off of it, the rule underneath shows up. There shouldn't be a rule there.
Screen Shot 2019-03-22 at 12 55 10 PM

**Review by dakahn — APPROVED** [review]
LGT 👋🏽

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] For some reason now the underline is coming up on the disabled states for list 
box and light. We need to take those off.
Screen Shot 2019-03-22 at 3 52 36 PM

- [x] There is a double/glitch rule line in the dropdown between option 3 and option 4.
Screen Shot 2019-03-22 at 3 52 29 PM


- [x] If we are going to display the dropdown open with the first option with a hover, the text in it should be `text-01` color.
Screen Shot 2019-03-22 at 3 55 20 PM

**Review by laurenmrice — APPROVED** [review]
Looks good to me ! 👍

**Pull request merged**
