### PR TITLE
chore(devenv): re-introduce theme switcher

### PR DESCRIPTION
**Pull request by asudoh**
This change (re-)introduces a theme switcher at the top right in dev env. It's done by creating a dev env Sass build option (`--use-custom-properties`) that emits style ruleset like:

```scss
.bx--foo {
  color: #171717; // $text-01, escape hatch for IE11
  color: var(--text-01);
}
```

This Sass build option is:

* Turned **off** by default for regular dev env, because it doubles Sass build time
* Turned **on** by default for deployed dev env so our designers can fiddle with different themes there

Refs #3046.

#### Changelog

**New**

- `--use-custom-properties` dev env Sass build option (see above).

**Changed**

- ~~Upgrades `carbon-components-react` used in dev env to `v10`.~~

#### Testing / Reviewing

Testing should make sure our dev env is not broken.

### CODE REVIEW

**Comment by asudoh** [comment]
@shixiedesign The demo can be seen at https://deploy-preview-3073--the-carbon-components.netlify.com/?nav=accordion. Ability to change individual theme tokens haven't been implemented yet, will address in a separate PR. Please let me know if you'd like kitchen-sink style UI seen in http://themes.carbondesignsystem.com - I'll add one if so. Thanks!

**Comment by joshblack** [comment]
Should we wait for #3033 to resolve to make sure the strategies are aligned?

**Comment by asudoh** [comment]
How to emit CSS custom properties is not the core of the change; Can change that any approach as long as it's flexible enough that fits in the purpose of the theme switcher introduced in this PR.

**Review by emyarod — COMMENTED** [review]
it looks like the legacy dropdown is being imported for the theme switcher

image

vs

image

**Comment by joshblack** [comment]
@asudoh not sure I understand, just felt like a lot of stuff was being added that felt coupled to that strategy. Let me know how you're thinking this will felt together if you get the chance 👍

**Comment by asudoh** [comment]
@joshblack The theme switcher is implemented by existing Sass maps in `@carbon/themes` - No substantial thing is added to implement that - Not a lot of stuffs like you said. All of changes are dev-env only thing. When we determine the future theming strategy, we can simply change the theme switcher code.

**Comment by asudoh** [comment]
@emyarod You are right, due to build problem I needed to put V9 dropdown there - But it's dev env-only thing.

**Review by shixiedesign — CHANGES_REQUESTED** [review]
I am sooooo happy to see the themes being rendered with a simple dropdown. Can't wait to start verifying each component's styling in each theme. Only 1 error I noticed, hopefully easy fixes: 

Looks like the background in component live example is pulling the incorrect token. Should not be using `$ui-02`, please use `$ui-background` instead.
image

**Comment by shixiedesign** [comment]
@joshblack right this is only for internal use. Design desperately needed this functionality to verify the correctness of our token values and token assignment to components. I have no idea what "emit custom properties" is haha – this PR does not define / restrict the way Carbon is going to ship themeing function to our users.

**Review by shixiedesign — APPROVED** [review]
Perfect! This will help me so much. Thanks! 🙌

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by emyarod — COMMENTED** [review]
actually just one thing I noticed, after navigating to a new page, the selection in the theme switcher dropdown resets but the theme itself does not change

**Comment by asudoh** [comment]
Good catch @emyarod! Fixed.

**Comment by joshblack** [comment]
@asudoh why are we merging things when there are open questions on the PRs? This is adding more stuff to our dev environment for this use-case that may or may not make sense depending on our theming strategy (for example, adding a feature flag for custom properties and toggling our dev build pipeline as a result). We really should not be merging things in if there are open questions or if someone is asking for clarification.

**Comment by joshblack** [comment]
@shixiedesign yes, I totally get that. This is a comment towards implementation and how that relates to the dev env and our strategy towards that 👍

**Comment by asudoh** [comment]
@joshblack This PR is independent from our theming strategy.

**Comment by joshblack** [comment]
@asudoh that makes sense, just was hoping we could chat about things before items get merged in. One thing I wanted to raise is that we should look to add this into our React environment first instead of our vanilla environment.

**Pull request merged**
