### PR TITLE
fix(structured-list): flatten sass

### PR DESCRIPTION
**Pull request by alisonjoseph**
@aledavila I noticed some weirdness with a structured list when trying to pull it into the website. 

This PR flattens all the sass to make it more readable. Apologize for not noticing this in your original PR.  Double checking w/ other @IBM/carbon-developers that we had agreed upon not nesting sass selectors to make it easier to edit. Do we have that in docs somewhere? We should 

### Added
Updated docs to mention flat sass selectors

### Testing
Check experimental structured list and make sure I didn't break anything with these updates 🙏

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
Looks good to me! 👍

**Comment by tw15egan** [comment]
For me, I think we should still continue to nest direct pseudo state, e.g.


DO 

```scss
.bx--button {

   &:hover {
      color: red;
   }

   &:active {
      color: black;
   } 
}
```

DON'T 
```scss
.bx--button {
   
   &:hover {
      color: red;

      svg {
         fill: blue
      }
   }
}
```

**Comment by alisonjoseph** [comment]
👍 I'm ok with that @tw15egan

**Comment by aledavila** [comment]
Oh my bad. Should've checked the previous sass. I didn't want to change too much for the original structure. But I agree unnesting is better.

**Review by aledavila — APPROVED** [review]

**Comment by alisonjoseph** [comment]
No worries @aledavila I ran into issues with the website because we add another level of nesting to the sass when it pulls in experimental components, which breaks the way `&` works. I think.

**Pull request merged**
