### PR TITLE
refactor(Slug): refactor Slug callout into composable components

### LINKED ISSUE #15051: C4AI Slug: Implement action bar styles and React components
As a continuation of #14947, implement the action bar spec'ed here:

https://github.com/carbon-design-system/carbon/issues/14948#issuecomment-1773389378

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15051

Refs https://github.com/carbon-design-system/carbon/issues/14947

This is a continuation of the initial `Slug` PR that adds in the action bar to the `Slug` callout.

#### Changelog

**New**

- Styles added for the `Slug` action bar
- `Slug` is now composed similarly to `Toggletip`, with a `SlugContent` component mapping to `ToggletipContent` and `SlugActions` mapping to `ToggletipActions`.

```jsx
<Slug>
  <SlugContent>
    Main callout content goes here
    <SlugActions>
      <IconButton kind="ghost" label="View">
        <View />
      </IconButton>
      <IconButton kind="ghost" label="Open Folder">
        <FolderOpen />
       </IconButton>
       <IconButton kind="ghost" label="Folders">
         <Folders />
       </IconButton>
       <Button>View literature</Button>
     </SlugActions>
  </SlugContent>
</Slug>
```

#### Testing / Reviewing

Ensure that all `hollow` `Slug`'s only render the default callout, and all others render the new callout styles. Ensure there are no visual regressions.

### CODE REVIEW

**Comment by aagonzales** [comment]
@tw15egan Can we had a control in the storybook playground to turn on and off the action bar?

**Comment by tw15egan** [comment]
@aagonzales Yeah definitely, I can add something to turn it off. For now, the first two normal slugs (mini and 2xs) in the default story don't have the toolbar.

**Comment by tw15egan** [comment]
@aagonzales updated 👍🏻

**Review by aagonzales — APPROVED** [review]
The action group looks good!

This is just a side note for me, in the dark themes the gradient and toolbar kind of blend together. So I may tweak that later for visuals but everything looks to spec here. The gradient also isn't blending out as nicely at top so I'm going to look into that too. 

image

**Comment by mattrosno** [comment]
@tw15egan so we can track this on the project board and give visibility, here's an issue for this PR:

https://github.com/carbon-design-system/carbon/issues/15051

**Review by alisonjoseph — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
