### PR TITLE
fix(button): apply color to all possible svg elements

### LINKED ISSUE #5962: Gray 10 theme SVGs inside icon-only ghost buttons are not properly colored
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Steps to reproduce:

1. NPM install the latest `@carbon/icons-react`, `@carbon/components` and `@carbon/react`
1. Create a carbon css with the gray 10 theme. This will make the `.bx--btn--ghost` color #0f62fe.
2. [Implement an icon-only ghost-button described here](https://deploy-preview-5955--carbon-components-react.netlify.app/?path=/story/buttons--icon-only-buttons).
3. As the icon, set any of the following: Delete16, Help16, ArrowRight16 or Maximize16 from `@carbon/icons-react`. 

Expected result: 

All of the button should be colored #161616 like this:

image

Actual result: 

The button is only partially colored, and parts of it inherit the ghost button's blue color:

image

Related component: **Button**

## Additional information

Sorry, I wasn't able to get CodeSandbox to work with SASS and create a Gray 10 themed carbon css. If you have any solution for that, I'd be glad to provide a working example.

### PR DESCRIPTION
**Pull request by FrivalszkyP**
Closes #5962 

I noticed that icon-only ghost buttons did not apply the fill color to SVGs thoroughly. The fill color was applied to the `path` element of the icon SVGs, but carbon icons use not only `paths` but `rect` and other elements as well. The same color rule has to be applied to all of these.

#### Changelog

**New**

- Added `rect`, `circle`, `polygon` and `polyline` next to `path` to apply the fill color for ghost buttons.

#### Testing / Reviewing

I should note that for visibility's sake, more buttons should be added to the storybook knobs for icon-only buttons. 

To see how this PR affects the icon-only ghost buttons, test with these icons: 

- Delete16 (has `rect`), Edit16 (has `rect`)
- Help16 (has `circle`)
- ArrowRight16 (has `rect`, `polygon`)
- Maximize16 (has `polyline`)

Before:
image

After:
image

### CODE REVIEW

**Comment by FrivalszkyP** [comment]
Could the root cause of the issue be that SVGO is not executed on the icons properly? 

It seems to me that [on the demo site](https://carbon-elements.netlify.app/icons/examples/preview/), there are only `path`s and `circle`s in the source because, I assume, SVGO transforms everything into `path`s. But in the carbon packages I checked (e.g. icons-react), I don't see these transformations.

**Review by tw15egan — APPROVED** [review]
Changes look good to me ✅ 👍 

Screen Shot 2020-04-28 at 11 57 35 AM
Screen Shot 2020-04-28 at 11 57 40 AM

**Comment by joshblack** [comment]
@FrivalszkyP @tw15egan would we be able to use as the selector `svg` and have the `fill` style cascade down? Or is this something where there is hard-coded fill or stroke attributes on the SVG? 🤔

**Comment by joshblack** [comment]
@FrivalszkyP, unfortunately, the optimized assets are only available in the JS source, but this should be changed in our upcoming release where that SVG folder gets optimized too!

**Comment by FrivalszkyP** [comment]
@joshblack Cool! Then, in fact, all we need to keep is `path` and `circle`, I think because with the exception of `circle`, everything else is converted to a `path` element.

**Comment by joshblack** [comment]
@FrivalszkyP sounds good! Would you happen to know why the fill style from the `<svg>` isn't being cascaded down? Trying to figure out if there are inline fill attributes that shouldn't be there or not 😅 haha

**Comment by FrivalszkyP** [comment]
@joshblack That's a good question and I should have looked into that. :) I'll get back to you.

**Comment by joshblack** [comment]
Hey @FrivalszkyP! 👋 Just wanted to check-in to see if you had any thoughts after looking into it 👀

**Comment by FrivalszkyP** [comment]
@joshblack I haven't had the time yet but I didn't forget!

**Comment by FrivalszkyP** [comment]
@joshblack I looked into it and there are two things to note here:

First of all, I guess your pull request #5937 solved this problem as well, just like you mentioned before, so we do not need to merge this PR anymore.

Secondly, I still took some time to look into the `path` selector and why the `fill` rule didn't cascade down from the `svg` selector. I can safely say that the `path` selectors can safely be removed from everywhere because the `fill` rules properly cascade down from the `svg` selectors. I assume there were cases where you needed that `svg path` specificity in some edge cases, but these edge cases are gone now. 

I checked the button.scss and the file-uploader.scss. I removed the `path` selectors and they all worked fine with every carbon theme. Unless there's a browser-specific behavior that necessitates using the `svg path` selector, I suggest to remove it. But that should be the scope of a different PR and a different related GitHub issue altogether to make it more clear.

**Comment by joshblack** [comment]
Sounds good @FrivalszkyP! 🎉 

Thank you so, so much for looking into this. Really appreciate it, and I'm glad that a lot of the shortcomings were addressed by that PR!

**Comment by FrivalszkyP** [comment]
Glad I could help! :) Closing this PR and the related issue now.

**Pull request closed without merging**
