### PR TITLE
feat(toggle): Add small toggle

### PR DESCRIPTION
**Pull request by alisonjoseph**
### Added

New small toggle variant
https://github.ibm.com/Bluemix/carbon-issues/issues/453

## Testing / Reviewing

Spec
image
image

### CODE REVIEW

**Comment by bsonefeld** [comment]
❗️ 👍 

This looks awesome!! Looks good to me other than this one comment 👇 

Are we required for a11y to have the labels on either side of the toggle (on/off)? I think for this variation we wanted no labels with the _option_ to include them. Right @tay-aitken ?

Can the developers go in and manually do this on their own, or do we need to be providing guidance on that?

**Comment by alisonjoseph** [comment]
I believe for a11y purposes a label is recommended, I can do a little more digging unless someone else knows for sure. That being said anyone using this could easily omit them.

**Review by asudoh — APPROVED** [review]
Looks great - Thanks @alisonjoseph! 👍 ✅

**Comment by tay-aitken** [comment]
@bsonefeld we might want to check with Bo on that. The only reason I did not include side labels in the toggle was because they were not included in your initial designs you passed off to me.

**Comment by alisonjoseph** [comment]
I think as long as we add an `aria-label` we should be covered, looks like that's what we are doing for the checkboxes inside the data table that don't have visible labels.

**Review by marijohannessen — APPROVED** [review]
Looks awesome! 👍 ✅

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
