### PR TITLE
fix(number-input): update value of errorId for aria-labelledby on input

### LINKED ISSUE #4198: AVT 1 - NumberInput DAP violation for ID references
## Enviroment
macOS 10.14.6
Chrome Version 77.0.3865.90
VoiceOver
DAP 1.8.0.0

## Description
Run DAP on the NumberInput Component and the following violation displays:
DAP violation screen shot

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4198 

In the originating issue, `aria-labelledby` (which was referring the `id` of the error message) was always present even when there wasn't an error, causing a DAP violation.

So this PR proposes tying the `errorId` to the `error` message, since their values are connected. So if the `error` exists, so does the `errorId` -- otherwise both are `null`.

**NOTE:** in the process of looking into this, I noticed that the `aria-invalid` and `data-invalid` attributes are tied to the `invalid` prop & won't be updated if an invalid entry is added. I opened an issue here: https://github.com/carbon-design-system/carbon/issues/4294

#### Changelog

**Changed**

- move `errorId` into `error` message conditional logic & make it `null` by default

#### Testing / Reviewing

1. Open the `NumberInput` story here: https://deploy-preview-4295--carbon-components-react.netlify.com/
2. Inspect the `input` and confirm that there is *no* `aria-labelledby` attribute
3. Enter an invalid entry and then check the `input` again to confirm that this *is* now an `aria-labelledby` attribute & it correctly matches the `id` of the error message container.

### CODE REVIEW

**Review by dakahn — CHANGES_REQUESTED** [review]
Looks like this has a DAP error -- `aria-describedby` still referencing an invalid error ID. But if you cause an error the violation goes away. 

> The id tj-input-error-id specified for WAI-ARIA property aria-describedby on element input is not valid

I'm also not seeing `aria-labelledby` being set on the input element when there is an error if that was the intention.

**Comment by jendowns** [comment]
@dakahn do you mind taking another look using this deployment URL? https://deploy-preview-4295--carbon-components-react.netlify.com/

In my testing instructions, I put the link to the published storybook, not the one for my PR deployment 😅  I fixed that link now

**Review by dakahn — APPROVED** [review]
Tested on Chrome latest using current DAP ruleset and looks 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Comment by snidersd** [comment]
@dakahn After running DAP on the deployment URL (https://deploy-preview-4295--carbon-components-react.netlify.com/), I'm seeing a new DAP error. "the accessible name must match or contain the visible label text.". Can you check?  (see screenshot)
Screen Shot 2019-10-11 at 2 10 59 PM

**Comment by dakahn** [comment]
Just checked again @snidersd using the September 2019 ruleset on Chrome
https://deploy-preview-4295--carbon-components-react.netlify.com/

Using that deploy preview link I don't have that error 😕

**Comment by snidersd** [comment]
@dakahn Are you using the IBM Accessibility WCAG 2.1 September 2019 ruleset or IBM Accessibility September 2019? I'm seeing the issue using WCAG 2.1.
Screen Shot 2019-10-11 at 2 23 36 PM

**Comment by emyarod** [comment]
I have the same error ("Accessible name must match or contain the visible label text") when testing with the same ruleset

**Pull request merged**
