### PR TITLE
fix(modal): Remove flex from footer to avoid shrinking

### LINKED ISSUE #1000: [Modal]: Too much content or a very short window causes the buttons to be pushed off the footer
## Detailed description

When using a transactional modal it is possible to push the buttons off of the footer. This happens when you either have too much content in the modal or if you have a short window.

> Is this issue related to a specific component? 

Modal component

> What did you expect to happen? What happened instead? What would you like to see changed?

If adding more content it shouldn't affect the placement of the buttons since the content has scroll.

> What browser are you working in? 

Chrome, tested in Firefox and the same does not happen

> What version of the Carbon Design System are you using? 

Last tested in 9.5.0

## Steps to reproduce the issue

1. Open up the [react storybook modal component](http://react.carbondesignsystem.com/?selectedKind=ModalWrapper&selectedStory=transactional%20modal&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) in Chrome
2. Open the transactional modal
3. Shrink the window vertically until it is very small and watch the buttons be pushed off the footer
4. Make the window a normal size, inspect the modal content and copy and paste the text of one of the content paragraphs over and over inside dev tools and watch as the button moves off the footer.

## Additional information

image

image

### PR DESCRIPTION
**Pull request by krbrewer**
## Overview

Resolves #1000 
The modal footer was shrinking when the modal had a lot of content or if the height of the window was decreased.

screen shot 2018-07-26 at 11 04 10 am

### Changed

Previous versions of the footer styles used `display: block`, which retains the height of the parent based on the button children. I added this change to the display type and `text-align: right` to align the buttons to the right of the footer. I also removed the justification since it is dependent on the footer being a flex-box.

## Testing / Reviewing

Verified on Storybook.

Before:
screen shot 2018-07-26 at 11 26 21 am

After:
screen shot 2018-07-26 at 11 25 57 am

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Hi @krbrewer thank you for jumping in and trying to fix the issue! What I have got in mind is custom modal footers - The change drifting away from `display:flex` would impact that. Given this, we may consider the change in a future major release, is it possible for your project to apply your proposed style in per-application basis? If you figure out a less drastic style change please feel free to propose it - Thanks!

**Comment by krbrewer** [comment]
@asudoh Sounds good. I think the only way to keep the footer from collapsing if the display is `flex` is to set its `min-height`. This would allow the footer to grow if more children are added to it, however, since it will remain a flex, this will end up also collapsing to at least the min-height set.

**Comment by krbrewer** [comment]
At the very least the footer should be given `align-items:center` to keep the buttons from bleeding out of the modal.

**Comment by asudoh** [comment]
@krbrewer Thank you for proposing a couple and giving them your thoughts on! While `align-items:center` sounds very reasonable, I think we can start with `min-height` that looks the safest.

**Review by joshblack — APPROVED** [review]

**Review by joshblack — COMMENTED** [review]
Whoops, meant to leave a general comment. Just wanted to echo what @asudoh brought up with the removal of `display: flex` and making sure to verify the styles work in our browser targets 👍

**Comment by alisonjoseph** [comment]
Closing this for now since there has been no activity in a couple weeks. Feel free to re-open or open another PR with the `min-height` fix if needed.

**Comment by asudoh** [comment]
Refs: #790

**Pull request closed without merging**
