### PR TITLE
new cloud pictograms 31-60

### PR DESCRIPTION
**Pull request by dudley-ibm**
Closes #

{{includes 31-60 of 225 new Cloud pictograms}}

#### Changelog

**New**

- {{Issue #81 – pictograms 31-60
access-management	(Cloud)
audio-data	(Cloud)
automated	(Cloud)
business--continuity--02	(Cloud)
code	(Cloud)
connectivity	(Cloud)
continuous	(Cloud)
data--privacy--02	(Cloud)
data--transfer	(Cloud)
encryption	(Cloud)
event-driven	(Cloud)
extend-the-data-center	(Cloud)
fault-tolerant	(Cloud)
filter-and-group-data	(Cloud)
high--performance	(Cloud)
high-volume-data	(Cloud)
highly-available	(Cloud)
operate-offline	(Cloud)
predictability	(Cloud)
react-to-data	(Cloud)
real-time	(Cloud)
reliability--02	(Cloud)
resource-health	(Cloud)
security--02	(Cloud)
sharing-data	(Cloud)
streaming-data	(Cloud)
text--data	(Cloud)
transform-data	(Cloud)
unstructured-data	(Cloud)
visual--data	(Cloud)}}

#### Testing / Reviewing

{{ These pictograms should show up on both the carbon and IBM Design Language sites }}

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
Looks good!

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by dakahn — APPROVED** [review]

**Comment by laurenmrice** [comment]
Oh it looks like this PR has some merge conflicts which need to be resolved before we merge. Could someone help Michael?

**Comment by tw15egan** [comment]
@laurenmrice on it 👍🏻

**Comment by dudley-ibm** [comment]
@tw15egan @laurenmrice it appears to be an issue with the pictograms.yml and the categories.yml files, but I'm not sure what needs to be fixed.

**Comment by tw15egan** [comment]
@dudley-ibm I've resolved the conflicts, we'll probably get some more on the other pictogram PRs but I'll take care of them once each one is merged

**Pull request merged**
