### PR TITLE
fix(button): fix ghost button padding

### LINKED ISSUE #7091: [button] incorrect ghost button left and right padding
- The ghost button left and right padding increments are off (12px padding and 1px border)

- The left and right padding should be 16px/1rem.

----------------------------------------------------------------------------------------------------------------------------

#### Spec:

Artboard

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/7091

Adjusts padding on Ghost Button variant

#### Changelog

**Changed**

- Bumps horizontal padding from `12px` to `16px`

#### Testing / Reviewing

Ensure padding looks correct

### CODE REVIEW

**Comment by laurenmrice** [comment]
The ghost button has the correct padding now for the `default` size. But it needs to still be updated for the `field` and `small` sizes

**Comment by tw15egan** [comment]
@laurenmrice updated 👍

**Review by emyarod — COMMENTED** [review]
looks good to me pending design review

**Review by laurenmrice — APPROVED** [review]
Looks good to me ! Thank you 🙌🏻

**Review by joshblack — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
@tw15egan looks good! 🎉

**Pull request merged**
