### PR TITLE
fix(dropdown): update color tokens

### LINKED ISSUE #3217: [Dropdown] Dark theme inline dropdown styling bug
Couple of styling error on inline dropdown only: 

- Default background should be using `$ui-background` 
- Disabled background should still be `$ui-background`
- Disabled text & icon should use `$disabled-03` token

**Current**
From top to bottom: default, disabled, error states

image

**Should be** 

image

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3217.

#### Changelog

**Changed**

- Update several color tokens in inline variant of dropdown.

#### Testing / Reviewing

Testing should make sure our dropdown is not broken. The React variant can be verified by:

1. Set `true` to `CARBON_REACT_STORYBOOK_USE_EXTERNAL_CSS` as well as `CARBON_REACT_STORYBOOK_USE_STYLE_SOURCEMAP` environment variables
2. `cd /path/to/carbon/packages/react`
3. `yarn storybook`
4. Go to Dropdown - Default and set `inline` to `type` and check off `disabled` in the Knobs tab at the bottom
5. Go to DOM inspector in Chrome DevTools and select `<div>` with `.bx--dropdown--inline` class
6. Click on the line number link of the style ruleset and see the color token applied
7. Do above two steps for `<span>` with `.bx--list-box__label` class and the icon `<svg>`

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
tested locally according to the steps provided, looks good to me!

**Review by alisonjoseph — APPROVED** [review]
LGTM! just waiting on @carbon-design-system/design approval

**Comment by jeanservaas** [comment]
hey @emyarod 

Tokens changes look right according to @shixiedesign's issue specs, but could I review this on your screen sometime this week. Not really sure how to test and review.

**Review by joshblack — APPROVED** [review]

**Review by jeanservaas — APPROVED** [review]
LGTM

**Pull request merged**
