### PR TITLE
fix(ui-shell): sidenav menu height transition bug for Safari

### LINKED ISSUE #2928: [ui-shell] Sidenav icons don't move with parent container on mobile
You can see here, when a sidenavmenu is opened, the icons of sibling sidenavmenus stay put on ios safari

shell-sidenav

Steps:
1. go to [the sidenav storybook](http://react.carbondesignsystem.com/?selectedKind=%5BExperimental%5D%20UI%20Shell&selectedStory=SideNav%20w%2F%20Header&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) on mobile.
2. Expand a Sidenav Menu Item
3. Notice how the icons don't move with their parent containers

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #2928 

Temporary fix until we have time to implement dynamic height transitions.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
Interested to see if this fix works as well: https://github.com/carbon-design-system/carbon/issues/2928#issuecomment-504940535

**Comment by joshblack** [comment]
Mind checking in the changes to `componenots/docs/sass.md`? I think the command to generate is `cd packages/components && yarn docs`

**Review by tw15egan — APPROVED** [review]
Looks good to me! 👍

**Comment by jnm2377** [comment]
Tried out this solution: https://github.com/carbon-design-system/carbon/issues/2928#issuecomment-504940535 which also worked, but had to override the style using `!important` since it's an inline style in our svg. If we're fine with that override, I can add the height transitions back in, but at some point we will still need to figure out how to set those dynamically. @tw15egan

**Comment by tw15egan** [comment]
I'm fine with leaving them out until we can figure out how to do it better 👍

**Review by lovemecomputer — APPROVED** [review]
cool! i know svgs combined with transitions can be troublesome and take time to work through on safari

**Pull request merged**
