### PR TITLE
fix(checkbox): add padding to accommodate focus state box-shadow

### LINKED ISSUE #6480: Checkbox focus state is cut off when inside a container with an overflow
## Detailed description

Whenever the `Checkbox` component sits inside a container with a non-default/initial overflow value (like `overflow: auto` or `overflow: hidden`, its focus outline is cut off at the edge of the container.

This is likely because the focus outline uses `box-shadow` & is not currently accommodating for the extra space needed.

Screenshots:

**With `overflow`**|**Without `overflow`**
--- | --- 
Screen Shot 2020-07-16 at 8 52 11 AM|Screen Shot 2020-07-16 at 8 52 22 AM

## Steps to reproduce the issue

1. Go to the storybook: https://carbon-components-react.netlify.app/?path=/story/checkbox--checked
2. Inspect `Checkbox` and find the wrapping `<fieldset>` element
3. In the browser inspector, change the `<fieldset>` to `overflow: auto` or `overflow: hidden`
4. Focus on a `Checkbox` to see the focus "outline" (i.e., box-shadow) is cut off.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #6480 

Adds 2px top and left padding to the checkbox's wrapper element. This will make space for the focus state's box-shadow, so that the shadow isn't cut off when the checkbox is inside a container that has an overflow. (See screenshots in #6480 for details)

Let me know if you want a diff approach! 👍 

#### Changelog

**New**

- add 2px top and left padding to the checkbox wrapper

### CODE REVIEW

**Comment by jendowns** [comment]
I just wanted to note here that depending on the solution for https://github.com/carbon-design-system/carbon/issues/6471, this PR may need to shift direction.

**Review by rjhenriquez — APPROVED** [review]

**Comment by andreancardona** [comment]
@jendowns Hey Jen! Going to bring this up to the team since it seems to be part of a larger discussion. Will keep you posted!

**Comment by jendowns** [comment]
@andreancardona totally understandable! To be honest I'm not sure there's a path forward with this particular solution, since box-shadow isn't going to work for Windows high-contrast mode anyway. And other solutions (outline, border) won't require this work around.

So taking all of that into account, do you mind if I close this PR and defer to whatever solution you want to go with for #6471?

**Comment by andreancardona** [comment]
> @andreancardona totally understandable! To be honest I'm not sure there's a path forward with this particular solution, since box-shadow isn't going to work for Windows high-contrast mode anyway. And other solutions (outline, border) won't require this work around.
> 
> So taking all of that into account, do you mind if I close this PR and defer to whatever solution you want to go with for #6471?

@jendowns Yep that works for me! :)

**Pull request closed without merging**
