### PR TITLE
fix(react): add prop adapter for downshift changes

### LINKED ISSUE #6420: Pre-selecting items in ComboBox does not work in v7.15
## What package(s) are you using?
carbon-components-react

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
I am using `initialSelectedItem` prop to pass the initial selection to the ComboBox component. It was working in v7.12. But since I moved up to v7.15, it no longer works. The input field is set to the label of the pre-selected item, but if I open the dropdown, I don't see the pre-selected item is highlighted. Then when the component lost the focus, the text in the combo input field will be clear.

> Is this issue related to a specific component?
Yes, ComboBox component.

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expect the pre-selected item will be persisted and opening the dropdown will see the item highlighted.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
carbon-components v10.15
carbon-components-react v7.15

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud Console. This is a regression and it should be fixed as soon as possible.

## Steps to reproduce the issue

1. Step one
Render the component like the code snippet attached below.
2. Step two
Open the dropdown menu. You will see no item is highlighted.
3. Step three
Click elsewhere to make the component lose focus.
4. Results
The text in the input field is clear and nothing is highlighted in the dropdown.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
Code snippet:
```
          <ComboBox
            id="my-id"
            items={['aaa', 'bbb', 'ccc']}
            initialSelectedItem={'bbb'}
            light
          />
```

combobox-bug

- Notes

### PR DESCRIPTION
**Pull request by joshblack**
Closes #6420 

Adds in the prop adapter for Downshift to map from `initial` to `default` without a breaking change

#### Changelog

**New**

**Changed**

- Add prop adapter to MultiSelect, Dropdown, Combobox, and Filterable MultiSelect

**Removed**

#### Testing / Reviewing

- Checkout the PR locally 
- Run storybook
- Update the combobox story with the example from: https://github.com/carbon-design-system/carbon/pull/6425 and verify that it works as intended

### CODE REVIEW

**Comment by flannanl** [comment]
@joshblack I pull the code from your PR and try but it does not work for me.

**Comment by joshblack** [comment]
@flannanl was it using your storybook example from the other PR? Or is this application code?

**Comment by flannanl** [comment]
@joshblack I was testing with the storybook example I gave in my PR.

**Comment by joshblack** [comment]
Hmm, not sure what's going on. Before the change we got this (incorrect) behavior:

image


When updating it, I get this behavior:

image

With this code:

image

**Comment by flannanl** [comment]
@joshblack did you try to open the dropdown and then lose focus?

**Comment by flannanl** [comment]
@joshblack  Here is a clip showing the fix does not work.

combobox-bugfix

**Comment by joshblack** [comment]
Thanks @flannanl! Totally get what you mean now, for ComboBox I totally missed that it was setting `default` directly instead of being in the mapping layer, will make sure to update along with the other changes. Thanks!

**Comment by joshblack** [comment]
@flannanl just updated with that change!

**Comment by flannanl** [comment]
@joshblack Thanks! Your latest fixes work!

**Review by tw15egan — APPROVED** [review]
Working as expected 👍 ✅

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
