### PR TITLE
feat(utilities): add typescript declarations to dist

### PR DESCRIPTION
**Pull request by janhassel**
Adds typescript declarations to build output for `@carbon/utilities` and `@carbon/utilities-react`.

### CODE REVIEW

**Review by guidari — APPROVED** [review]
LGTM!

**Review by riddhybansal — APPROVED** [review]
LGTM !!

**Review by alisonjoseph — APPROVED** [review]

**Comment by nchevsky** [comment]
@janhassel Are you aware that the generated type declaration files aren't actually being shipped with the package? It seems this PR neglected to add the `types` directory (where the `.d.ts` files are being emitted) to the `files` field in `package.json`.

CC: @alisonjoseph, @guidari, @riddhybansal (approvers)

**Comment by janhassel** [comment]
@nchevsky Yeah, that should be fixed with #18545 and therefore be included in the next release.

**Pull request merged**
