### PR TITLE
fix(treeview): update text and color tokens to match spec

### LINKED ISSUE #8000: [tree view] code bugs
Following up on the experimental tree view component. I have a couple different bug items to address:

----

- [x] **Width:** Lets set the width by default to be 256 px/16 rem. Teams can adjust as needed.

width
 
- [x] **Enabled state:** icons need to be `icon-02`

enabled

- [x] **Hover state:** the text needs to be `text-01`. The icons need to be `icon-01`

hover

- [x] **Selected state:** Blue side bar should be `interactive-04`

selected

### PR DESCRIPTION
**Pull request by emyarod**
Closes #8000

This PR updates the text and color tokens for the treeview hover and enabled state

#### Changelog

**New**

- story specific tree width rule

**Changed**

- hover and enabled state text and color tokens

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Hover and Selected states:** Icons need to be `icon-01` to match the text color.
hover

**Review by laurenmrice — CHANGES_REQUESTED** [review]
When a top level parent is selected and open, the nested items that have a caret icon are currently getting an `icon-01` color. The unselected items with caret icons should be `icon-02` unless they are selected or hovered on.
Screen Shot 2021-03-15 at 9 48 59 AM

**Review by tay1orjones — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Ok last thing, the disabled nodes just need to get a disabled cursor applied on hover. Everything else looks great !

**Comment by emyarod** [comment]
I believe the cursor style for disabled items was [intentional](https://github.com/carbon-design-system/carbon/pull/6008/commits/75b57b30dadc942fb98dd18ff79a085e773780af) to match behavior in native context menus, but since we now have a context menu component and use the disabled cursor there I can make that change here as well

**Review by jnm2377 — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
Looks good to me 🎉

**Pull request merged**
