### PR TITLE
fix(list): update padding rules around items and nested items

### LINKED ISSUE #4433: [list] need to add 4px spacing between each item
Unordered
- [ ] Add 4px spacing between each item

Ordered
- [ ] Add 4px spacing between each item
- [ ] Change text in items to say "Ordered List level 1". It is confusing it says Unordered.

---------------------------------------------------------------------------------------------------
List - Specs - White theme

---------------------------------------------------------------------------------------------------

Ref: #4330

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4433 

#### Changelog

**Changed**

- updated padding rules for items and then items in nested lists
- updated demo text in handlebars template to match context

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]
LGTM! 🎉

**Review by emyarod — COMMENTED** [review]
this is part of the theming project for this month so it may be superseded by current work in progress cc @laurenmrice

**Comment by jendowns** [comment]
OH I didn't notice anyone had assigned that issue? Is this conflicting with an open PR right now?

**Comment by laurenmrice** [comment]
@jendowns yes I am sorry, Andrew has been currently working on this same list issue but has also been addressing /fixing other items within it as well. We could close this and use his pr.

**Comment by jendowns** [comment]
Okay sure... I don't see any list-related PR right now but I can close this one either way. 🤔

**Comment by emyarod** [comment]
yeah I forgot to assign it once I picked it up but it's under the November theming project in GitHub so all of those tickets are on our project group's radar. for this particular issue the spec is being revised as we go over additional use cases/variants

thanks for jumping in though! as a general note in the future it would be great if you left a note on any issue you decide to pick up to let others know that it's being worked on

**Comment by jendowns** [comment]
Sure thing @emyarod, I can leave a note. I thought it was sufficient to tag the issue (similar to how the originating issue appears to have been included in the theming project you mentioned) when creating the PR.

**Comment by emyarod** [comment]
oh I meant writing a note in the issue before starting work so that we know something is in progress

**Pull request closed without merging**
