### PR TITLE
Key and virtual column icon

### PR DESCRIPTION
**Pull request by rebeccaurry15**
Closes #

IA is using this icon for when a column is both a key AND virtual column.

[key and virtual column.zip](https://github.com/carbon-design-system/carbon/files/3709235/key.and.virtual.column.zip)

### CODE REVIEW

**Comment by asudoh** [comment]
Hi 👋 thank you for jumping in! Seems that this PR contains many irrelevant changes. Would you try rebasing and make sure only your change is in this PR?

**Review by emyarod — COMMENTED** [review]
is this PR supposed to be targeting the `v9` branch?

**Comment by rebeccaurry15** [comment]
Sorry for the confusion. The carbon site has incorrect guidelines for submitting icons. The site syas to upload icons as a pull request. I synced with the Carbon designers and was told to submit icons as issues NOT pull requests.

**Comment by abbeyhrt** [comment]
Hi @rebeccaurry15 Sorry for the confusion around our icon submission guidance! We will definitely update that soon. I am going to close this PR since this won't be getting merged in. For everyone's future reference,  here is the issue to address the suggested icon #4284.

**Pull request closed without merging**
