### PR TITLE
fix(button): update icon only ghost button colors

### LINKED ISSUE #5312: [icon button] add ghost icon button functionality to react
We need to add a ghost icon button. This type of button is being used a lot within UIs when it's not the primary call to action on the page (provisioning experiences, options within a data table row @marceltrautmann ). The icon needs to have a default `icon-01` color with the option to switch to `icon-02` as well. 

---------------------------------------------------------------------------------------------------

Spec:
md-672px-8 column

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5312

Sets icon fill to `icon-01` when using icon only ghost button

#### Changelog

**New**

- Adds icon only ghost button back into react storybook
- Fill is now `icon-01`

#### Testing / Reviewing

Ensure icon only ghost button renders with `icon-01`

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
For the disabled state, the icon needs to be `disabled-02`. I also think they should not get a tooltip when disabled and should get the disabled cursor change? (@dakahn may be able to confirm that though)

Can we have a way where we can switch between viewing it as `icon-01` (being the default) and `icon-02`. Or is this something developers can change easily on their own end? I say this because the icon-02 is a frequent usecase when there are multiple of these icons in a row or near eachother.

**Comment by tw15egan** [comment]
Right now none of our button variations have specific props that can change color, but I guess we can add one. Is this similar to the `light` variations of inputs? Just unsure of the use case / why we need to have multiple icon colors for this variation, but none of our others have this feature.

**Review by dakahn — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by laurenmrice** [comment]
It wouldn't be similar to the light prop.  Is this something devs can easily change if they wanted to on their own? If so we can just keep the icon-01 and note in our doc guidance when to use icon-01 versus icon-02. People use this type of button differently within their UIs than other types of buttons (ex: as action icons on the page next to certain components, adding or deleting things, etc) and there are usecases for both.

**Comment by tw15egan** [comment]
Yeah they can always just set the icon to `$icon-02` via their own css if needed

**Comment by laurenmrice** [comment]
Ok cool, then how you have it is good. 👍🏻 Just need to update the disabled state icon to be `disabled-02`. It should not get a tooltip and should get the disabled cursor change instead.

**Review by abbeyhrt — APPROVED** [review]

**Comment by tw15egan** [comment]
@laurenmrice is this good to go?

**Review by laurenmrice — CHANGES_REQUESTED** [review]
There shouldn't be a background on the disabled state. only the icon needs to be `disabled-02`

**Comment by tw15egan** [comment]
Does the spec here (https://github.com/carbon-design-system/carbon/issues/5312) need to be updated then?

**Comment by laurenmrice** [comment]
oh sorry! yes, i just updated it to reflect that change.

**Comment by tw15egan** [comment]
@laurenmrice updated 👍

**Review by laurenmrice — APPROVED** [review]
awesome ! looks good to me 🙌🏻

**Pull request merged**
