### PR TITLE
fix(typography) - Line-height for type to be relative not absolute - #5975

### LINKED ISSUE #5975: Line-height not using ems
# Summary

I noticed line-height for reset and type is set to rems. This makes it not scalable.
This causes users to have to declare extra line-heights for no justifiable reason.
When text scales the line-height needs to with it and this can be achieved by using ems for font-size instead of rems

We can achieve scalability and same visual

# Resources:

https://codepen.io/dusanmilko/pen/JjYyjYw

### PR DESCRIPTION
**Pull request by DusanMilko**
Type should use ems to it scales relative to the local font-size.
The reset file sets base p tag font-size and line-height to the values from body-long-02.
If in a project a dev changes his font-size for a p tag the line-height does not scale since its in rem. The dev is also required to set line-height.
This fixes that issue so if font-size changes the line-height will scale relatively. This makes the code scale and easier to use.

#### Changelog

**Changed**

- Changed line height calculation to ems instead of rems

#### Testing / Reviewing

Example:

https://codepen.io/dusanmilko/pen/JjYyjYw

Fixes #5975

### CODE REVIEW

**Comment by asudoh** [comment]
Hi @DusanMilko 👋 thank you for jumping in - I thought the font size scales with <kbd>Command</kbd><kbd>+</kbd> even without the change. Wondering I'm missing something. That said, great to have an issue associated with the PR. We ask doing so for every PR except for small chores.

**Comment by joshblack** [comment]
Hi there @DusanMilko! 👋 To add more context to the type styles, the line heights are chosen specifically to pair with the font size of the token. The two need to update in lock-step if I understand correctly.

Definitely seems like our reset may be too aggressive here, I can totally get wanting to update the `p` styles. I believe you can turn off the default text styles with `$css--default-type: false;` and then can add in the token styles for the specific text that you would like.

**Comment by DusanMilko** [comment]
@joshblack Yes, currently a dev needs to update both font-size and line-height at the same time. This is excessive and is the point of using ems, Ems allows us to scale relative to local font-size. By switching line-height to ems the line-height can scale if font-size changes. Ems should be the default for line-height.

@asudoh I supplied a codepen displaying how line-height can scale with just changing font-size. This is not in regards to zooming.

**Comment by asudoh** [comment]
Thanks @DusanMilko for clarifying, let's see @joshblack and other devs thinks about your requirement. Could you enter an issue with your CodePen? Again we ask PRs to be associated with issues except for minor chores. Thanks!

**Comment by joshblack** [comment]
@DusanMilko definitely agreed, `em`s are great for the relative font-size use-case. I think that might be what is causing the mismatch in expectations here, earlier I was trying to say that the font-size and line-height values for these tokens are inherently coupled. We would expect if folks changed one of these values that the other would need to be changed, as well.

You can see this in the type tokens themselves as the font-sizes scale up/down where the line-height adjusts depending on font size and use-case (short or long-form text). There isn't necessarily a set line-height ratio that applies to all font-size values so the relative use-case might not be most appropriate here.

**Comment by DusanMilko** [comment]
@joshblack Having different tokens for different calculations is fine. I'm not saying use a single line-height for all type. We can have different ratios using ems. Ems allows there to be a default/base line-height scaling for the type. This is especially useful for the base/reset values. Using ems maintains current visuals but allows for scaling line-height more easily for dev. There isn't really a benefit to use rem in line-height

**Comment by joshblack** [comment]
@DusanMilko definitely didn't mean to suggest that there would only be one ratio, sorry if it came across that way! I think you're totally right that line heights can be super valuable as `em` values, but scaling one of these type tokens up in the way that's being proposed would most likely result in an incorrect line-height value.

I think `body-long-01` and `body-long-02` might be a good example of this. Paragraphs might have `body-long-01` by default, with a 14px font-size and 20px line-height (1.25 ratio).

When we try to scale it up to 16px, we would end up getting `16 * 1.25` 20px line-height. If we look at `body-long-02`, the more appropriate pairing would be `22px` as the ratio changes from `1.25` to `1.375`.

As a result, if we wanted to update the base font-size for the paragraph tag we would also need to update the line-height in order to achieve the correct font-size/line-height pairing.

Let me know if I'm talking about something different here, I could definitely be misunderstanding something! I just wanted to say that while this may be helpful in scaling I believe that folks would still need to update font-size and line-height in order to get the correct value from the IDL.

**Comment by DusanMilko** [comment]
@joshblack Sorry, Yeah I must have misunderstood that part. My point is using ems for line-height still maintains current visuals but allows the text to scale.

I think the calculations you mentioned are off.

body-long-01 has 14px font-size and line height 20px; 
thats a 1.428... ratio, not 1.25.
scaling that up to 16px font-size gives us 22.8, which is closer to appropriate.

#### Example 
The reset sets the p tag font-size to body-long-02, which is
font-size: 16px
line-height 1.5rem (aka 24px)

If for any reason a dev using carbon does a p tag and decides to use a custom font-size or etc, 
lets say they use 30px; 
so
p.some-class { font-size: 30px; }  <-- currently inherits body-long-02

So font-size is 30px but the line-height will still be 24px because line-height is in rems and isn't scaling to the modified font-size. This means the line-height is smaller than the font. This would force the dev to always specify a line-height.

Same example with ems

The font size is 30px and line-height being 1.5em instead of 1.5rem would mean line-height scales and is 45px; This keeps visual clarity and doesn't force the user to always specify line-height, they still can but aren't required. 

I understand the tokens having specific values, but using ems wont break the tokens.
These tokens are used as part of base/reset styles which is causing the issue.
I understand why rems are used, but highly recommend to using ems for line-height specifically. Using ems for line-height does not break any of the current visuals and allows for scalability shown above

**Comment by joshblack** [comment]
@DusanMilko haha you're totally right, thanks for correcting me on the math 🙏 I was referring to our website which clearly does not have the right values 🤦‍♂️ 

> I understand the tokens having specific values, but using ems won't break the tokens.

Definitely agreed! It shouldn't break them at all. It seemed like the issue was being presented as developers needing to change two things from the default styles when customizing the default styles for a `p` tag: font-size and line-height.

I was noting that it seems like this requirement would not change if the proposed changes were merged in as a developer would still need to update both font-size and line-height to match the value needed from the IDL.

**Comment by DusanMilko** [comment]
@joshblack Not sure I fully understand.

With ems the dev is not required to change line-height, its optional. To match a certain design language, yes they might need to.

Ems allows us to make it optional to change line-height instead of required.
In a general sense, it also makes sense to scale line-height relative to font-size, aka ems, so the container can always contain the content properly. So the height of for example the p tag is proportional to font-size. Making the line-height responsive/scalable relative to font-size of the element.

**Comment by joshblack** [comment]
@DusanMilko We might be talking about different things here. For type, the requirement to change wouldn’t come from the developer and CSS but from the IBM Design Language. As the font size grows, I believe the language/brand team would want the line height to change. 

I could definitely be misunderstanding the requirements though from their end, let me go and double-check while we’re talking about this 👀 If the flexibility is there then the proposed changes 100% make sense. I was only speaking about the constraints/requirements as they may come to dev from design/brand. 

Thanks btw for talking through this! It’s been really helpful and I appreciate you taking the time to explain 🙏

**Comment by joshblack** [comment]
Following up on this, it seems like we may still have the requirements for the line-height potentially changing but I think you're dead-on @DusanMilko about changing from the absolute size to a relative one.

How would you feel about going down a unitless line-height route for these changes too @DusanMilko 👀 and would this need to be updated for all the type tokens potentially?

**Comment by DusanMilko** [comment]
@joshblack Yeah both ems and unit less value in line-height is based on font-size so its the same thing. Also yes, line-height pretty much just always makes sense to base off of font-size.

Making the jump from rems to ems for line-height specifically should not introduce any issues.

**Review by joshblack — APPROVED** [review]

**Review by designertyler — APPROVED** [review]

**Pull request merged**
