### PR TITLE
feat(icons): new icons september 2024

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
Submitting new and updated UI icons, September 2024 all updates and additions approved by BXD

47 net new icons
2 icons moved to new category
1 icon's friendly name changed
1 icon deprecated
1 icon updated

updated categories.yml with additions and updates

we will update the ui-icon-master.ai shortly after

Changelog

**New**
**Category: AI**
32/ibm--granite.svg

**Category: App catalogue**
32/ibm--knowledge-catalog.svg
32/ibm--knowledge-catalog-standard.svg
32/ibm--knowledge-catalog-premium.svg
32/ibm-cloud--vpc-block-storage-snapshots.svg
32/ibm-cloud--vpc-file-storage.svg
32/ibm-cloud--vpc-client-vpn.svg
32/ibm-cloud--vpc-images.svg
32/ibm--streamsets.svg
32/ibm--planning-analytics.svg
32/ibm--global-storage-architecture.svg
32/ibm-watsonx--code-assistant-for-z-validation-assistant.svg 
32/ibm-z--open-editor.svg
32/ibm-cloud--code-engine.svg
32/ibm-cloud--backup-and-recovery.svg
32/ibm--aspera.svg
32/ibm--deployable-architecture.svg
32/ibm--machine-learning-for-zos.svg
32/ibm-cloud--gate-keeper.svg
32/ibm-cloud--security-groups.svg
32/ibm-cloud--security.svg
32/ibm-cloud--backup-service-vpc.svg
32/ibm-quantum--safe-advisor.svg
32/ibm-quantum--safe-explorer.svg
32/ibm-quantum--safe-remediator.svg
32/ibm-cloud--databases.svg
32/ibm-cloud--observability.svg
32/ibm--api-connect.svg
32/ibm--app-connect-enterprise.svg
32/ibm--data-power.svg
32/ibm-devops--control.svg

**Category: Systems**
32/network-time-protocol.svg
32/job--daemon.svg
32/job--run.svg

**Category: Toggle**
32/thumbs-up-double.svg
32/thumbs-up-double--filled.svg

**Category: Formatting**
32/punctuation-check.svg

**Category: Technology**
32/array--booleans.svg
32/array--dates.svg
32/array--strings.svg
32/array--objects.svg
32/array--numbers.svg
32/object.svg
32/build--image.svg
32/build--run.svg
32/function--2.svg

**Category: Data**
32/bland-altman-plot.svg

**Moved categories**
32/cloud-foundry--2.svg from “File” to “App catalogue” 32.cics--explorer.svg  from “Systems” to “App catalogue”

**Updated friendly name**
32/gateway--api.svg update to Gateway API

**Deprecated**
32/ibm-watson--knowledge-catalog.svg

**Updated**
32/transform--code.svg

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]

**Comment by laurenmrice** [comment]
@DianaStanciulescu Hey Diana, Just saw that this name was in here twice, and was not sure if that was intentional or a mistake. Everything else looks good to me!

Screenshot 2024-10-11 at 12 16 41 PM

**Review by tay1orjones — APPROVED** [review]

**Comment by tay1orjones** [comment]
This is ready to merge pending the comment above @DianaStanciulescu

**Review by laurenmrice — APPROVED** [review]

**Comment by DianaStanciulescu** [comment]
@laurenmrice this is a mistake, but I don't see this if I go into the changelog here. This is what I see. 
Screenshot 2024-10-15 at 14 40 51

Can you fix it on your end? Not sure how I can since I see a different thing.

**Comment by laurenmrice** [comment]
@DianaStanciulescu It looks like Kenny removed it! Looks good now to me.

**Comment by DianaStanciulescu** [comment]
Great, thank you!!

**Comment by DianaStanciulescu** [comment]
Thank you all! Please make sure to push the updates to IDL as well.

**Pull request merged**
