### PR TITLE
docs(Type): add v11 migration guide for type tokens

### LINKED ISSUE #10755: Type token migration changelog
- [ ] Document new vs. old in https://github.com/carbon-design-system/carbon/blob/main/docs/migration/v11.md#carbontype
-  [ ] Add reference for changes on the website
    - One has been deprecated
    - Names have been changed for a lot of them

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/10755

Adds in a type-token migration table for v11 type tokens

#### Changelog

**New**

- `11.x-type.md` file added to help users migrate type tokens

#### Testing / Reviewing

Ensure the document is correct

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
🎉 Looks great to me.

Only note would be if you think it'd be helpful to add this to the v11.md file. It seemed like people wanted to try more of an "all-in-one" approach versus several files but wanted to check-in with you first to see what you thought

**Comment by tw15egan** [comment]
@joshblack Good thinking, I've added it over there as well.

**Review by dakahn — APPROVED** [review]

**Comment by jnm2377** [comment]
@tay1orjones any idea why Percy would show a lot of changes if this was just a doc update? I don't wanna approve the build bc the changes look off but it's weird that it's showing up here... 👀

**Comment by tw15egan** [comment]
@jnm2377 I'm getting the same Percy errors in another PR I just pushed up 🤔 

https://github.com/carbon-design-system/carbon/pull/10817

**Pull request merged**
