### PR TITLE
Resize DataTable columns (standard & sticky header tables)

### LINKED ISSUE #3911: DataTable with sticky header has reduced width
## Brief description: 
Tables that use the sticky header option have reduced width. I did not investigate what is responsible for this, though.

## What package(s) are you using?
latest

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
When using the appropriate styles in Vanilla JS or the new stickyHeader flag in the react component (https://github.com/carbon-design-system/carbon/issues/3875) the width of the table is reduced.

> Is this issue related to a specific component?
DataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?
table width should stay the same with or without sticky header

> What browser are you working in?
chrome / firefox

> What version of the Carbon Design System are you using?
latest 

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud SQL Query

## Steps to reproduce the issue

1. Select DataTable in storyboard
2. In Knows turn on the sticky header option
3. The table has a scroll bar, but also a reduced width

### LINKED ISSUE #4751: Resize table columns
### Summary

We are requesting the ability for a user to resize column width within a table. This functionality is related to the ability to edit and reorder columns.

**Proposed design:**

image

**Related issues:**
- https://github.com/carbon-design-system/carbon/issues/4750
- https://github.com/carbon-design-system/carbon/issues/4687
- https://github.com/carbon-design-system/carbon/issues/4687
- https://github.com/carbon-design-system/carbon/issues/4749

### Justification

This functionality will support the ability to edit and reorder columns, functionality that is currently offered by the Softlayer table used by a third of IBM Cloud pages - functionality which we do not want users to lose. Many of our customers use small desktops or multiple windows side by side, so this will allow them to optimize their view.

**Proposed design:** 

image

image

### Desired UX and success metrics

The column divider would show up if a user hovers within the hover target. If the user then hovers over the divider they would get an "adjust width" browser icon. The user could then click to drag the divider right or left.

Letting go of the mouse or trackpad would release the divider.

Since drag and drop is not accessible, we would also offer a keyboard and screen reader accessible option that would allow users to adjust column width using their keyboard.

[Design provide link to accessibility flow]

### "Must have" functionality

- Resize column width must meet accessibility requirements

### Specific timeline issues / requests

This work is related to the CloudPAL-sponsored project to contribute back a more robust data table to Carbon by mid-December, as part of Carbon X / CloudPAL adoption. As such, we have a very tight timeline. We would like teams to be able to start consuming these tables in January.

Our team is working closely with Carbon design and development and trying to anticipate accessibility concerns.

### Available extra resources

What resources do you have to assist this effort?

Holman from ICED development squad in Toronto, possibly CloudPAL developers. Holman is currently working on developing this feature.

### PR DESCRIPTION
**Pull request by gmoehler**
Closes https://github.com/carbon-design-system/carbon/issues/4751
Closes https://github.com/carbon-design-system/carbon/issues/3911

This PR implements a column width resizer which works both for standard DataTable as well as for a DataTable with sticky-header.

It builds on an earlier PR (https://github.com/carbon-design-system/carbon/pull/5214), but minimizes the impact to the existing code dramatiacally, because it either uses additional components (like `TableColumnResizer`) or tools (like `DataTable/tools/columnResize.js`) or introduces copies of existing components (`TableHeader` -> `TableHeaderResizable`, `TableCell`-> `TableCellResizable`). The resize story `with-resizable-columns.js` uses the duplicated components and covers a few little additions for the resizing to work (see below).

The resizing algorithm is enhanced as compared to the earlier PR  https://github.com/carbon-design-system/carbon/pull/5214:
- the algorithm is based on table with use 100% of the available with and works best if a `min-width`is defined for `th/td`(as it is the case for _sticky header_ tables)
- if we move a resizer to the right the column is increased and all columns to the right are squeezed accordingly
- when we reduce the width of a column, the width of the column to the right is enlarged and the column of the left is reduced accordingly. When the column to the left hits its minimal width  (currently set to 40px) all other columns to the left are squeezed as well
- when all columns (either to the right or left) are at their minimum, no further modification is possible anymore
- going back and forth will alyway produce the same results

The algorithm needs access to the width of all columns, also it potentially changes the column width of all columns. For sticky header tables it is required to update the widh in the header `th` _and_ the cell `td`. Therefore, a central place is required to keep the width data. This solution uses an React Context `ResizeContext` along with a store to keep that data. This keeps the impact to other code low to a maximum, while using state-of-the-art react mechanism. A reducer `ResizeReducer` triggers store changes. Everything is encapsulated into a custom react hook `useColumnResizing()`. The hook  is used in the resizer component `TableColumnResizer` to trigger the resizing. In TableHeaderResizable` and `TableCellResizable` the same hook is used to retreive the new width and set it via `style={{ width: colWidth + 'px' }}`.

#### Changelog

**New**
- new components (as copies of existing components with resizing capabilities): `TableHeader` -> `TableHeaderResizable`, `TableCell`-> `TableCellResizable`
- additional component `TableColumnResizer`
- custom react hooks and react context in `DataTable/tools/columnResize.js`
- some style additions in `_data-table-column-resize.scss`
- tests for all components and tools

**Changed**

- included styles from `_data-table-column-resize.scss`
- modified 3 styles for sticky header table
- more data for data table story to see scrolling in sticky header table

**Removed**

_nothing_

#### Testing / Reviewing

Open the story DataTable > with resizabable columns, grab the resizer in the header of the table and resize the columns. Also switch on Sticky header (experimental) in the Knobs to verify things work for sticky header tables, too.
Screenshot 2020-02-06 at 17 35 34

### CODE REVIEW

**Comment by gmoehler** [comment]
^ @aagonzales, @asudoh, @emyarod

**Comment by gmoehler** [comment]
accessibility is not yet addressed. according to @joshblack we should possibly use Salesforce technique #4 from: https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09

**Comment by joshblack** [comment]
Hi @gmoehler! 👋 If I remember correctly, were you going down the route of adding this into Cloud PAL?

**Comment by gmoehler** [comment]
Correct that was the suggestion from the Carbon team. Will work on it in near future

**Comment by joshblack** [comment]
Perfect! Sounds great 😄 

We're going through older PRs just to clean-up ones that may be inactive. I am going to close this one out but feel free to re-open!

**Comment by akmalmzamri** [comment]
Is this available in the latest version of Carbon React? Couldn't find any documentation on this

**Comment by nagiah** [comment]
Can someone please answer: **what version of Carbon React** is this available in?

**Comment by tw15egan** [comment]
@nagiah @akmalhakimi1991 this feature was not added to Carbon core

**Comment by nagiah** [comment]
Thanks for your quick response @tw15egan 
Is there a plan to added it any time soon?

**Comment by nagiah** [comment]
An answer please:
Is there a plan to add Resize DataTable columns any time soon?

**Comment by tw15egan** [comment]
@nagiah there are no plans to implement this feature

**Pull request closed without merging**
