### PR TITLE
fix(link): color adjustments

### PR DESCRIPTION
**Pull request by asudoh**
Refs IBM/carbon-components-react#2061.

> Tooltip's link's hover underline color should be $link-01, same as link. Also wrong is link's `active` state
image

@shixiedesign My finding is this; I saw `box-shadow: 0 1px #0062ff` on the link in question which seems to match `$link-01` color in white theme. The code was using `$interactive-01`, though, so I replaced `$interactive-01` with `$link-01`. Tried to get an idea on what your feedback means further by digging the history of issues/PRs for link and found [this](https://github.com/IBM/carbon-components/pull/1960#issuecomment-469357884) saying that the underlines should be `currentColor`, which made me start guessing your feedback came from this and went ahead with ensuring text/underline colors are in sync. Hoping the changes matches your intent, but please don't hesitate to speak up anything - Thanks!

#### Changelog

**Changed**

- Replaced `$interactive-01` with `$link-01`.
- Ensured underline color matches text color regardless of the link state

#### Testing / Reviewing

Testing should make sure our link component (experimental) is not broken, especially its colors.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
just want design to confirm the color change for the underline, since I originally worked off of the [spec update from a couple weeks ago](https://github.com/IBM/carbon-components/pull/1802#issuecomment-469351568). other than that, changes look good to me

**Review by shixiedesign — APPROVED** [review]
Looks good! FYI @emyarod spec from before (Blue60) is still correct for white & G10 themes. We just recently added $link-01 token to account for other color themes.

**Comment by shixiedesign** [comment]
Thank you @asudoh  for doing to investigation to uncover what my issue really meant. I should definitely work on writing the issues better. But yes this is exactly what I meant. Underline & link text color should be the same, both calling `$link-01 ` 👍

**Comment by emyarod** [comment]
got it @shixiedesign , just wanted to confirm if the focus+active link underline should be different from the text color

image

**Review by tw15egan — APPROVED** [review]
👍

**Comment by asudoh** [comment]
No problem @shixiedesign and thank you for double-checking that my change matches your intent. And great point @emyarod - Created #2164 to see if the change matches the design intent.

**Pull request merged**
