### PR TITLE
fix(Toggle): fix JavaScript error in keyboard handler

### LINKED ISSUE #3453: onToggle is not invoked when pressing enter key on Toggle
## Environment

> Operating system
Mac and others

> Browser
Chrome and others

> Automated testing tool and ruleset
n/a

> Assistive technology used to verify
just normal keyboard

## Detailed description
When the user toggles the Toggle component the view updates and the onToggle handler is called if the user clicks the toggle or uses the space bar for toggling.  However, using the enter key to toggle, results in the view being update but no call to the onToggle handler.  I noticed that there is an exception in the Chrome DevTools console:
Uncaught TypeError: _onChange is not a function
    at onKeyUp (Toggle.js:108)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
    at invokeGuardedCallback (react-dom.development.js:256)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:270)
    at executeDispatch (react-dom.development.js:561)
    at executeDispatchesInOrder (react-dom.development.js:583)
    at executeDispatchesAndRelease (react-dom.development.js:680)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:688)
    at forEachAccumulated (react-dom.development.js:662)
    at runEventsInBatch (react-dom.development.js:816)
    at runExtractedEventsInBatch (react-dom.development.js:824)
    at handleTopLevel (react-dom.development.js:4826)
    at batchedUpdates$1 (react-dom.development.js:20439)
    at batchedUpdates (react-dom.development.js:2151)
    at dispatchEvent (react-dom.development.js:4905)
    at eval (react-dom.development.js:20490)
    at Object.unstable_runWithPriority (scheduler.development.js:255)
    at interactiveUpdates$1 (react-dom.development.js:20489)
    at interactiveUpdates (react-dom.development.js:2170)
    at dispatchInteractiveEvent (react-dom.development.js:4882)

> What version of the Carbon Design System are you using?
"carbon-components": "^10.3.1",
"carbon-components-react": "^7.3.2",

> What did you expect to happen?
onToggle should be called when pressing enter key, same as clicking and pressing space bar

> What happened instead?
onToggle was not called when pressing enter key

> What WCAG 2.1 checkpoint does the issue violate?
keyboard accessibility

## Steps to reproduce the issue
1. Press enter on the toggle
2. Notice that the onToggle was not invoked and an exception is logged in the console.

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/s/codesandbox-2vk1e

## Additional information
If you bring up the Chrome devTools console, there is an exception logged when clicking enter that doesn't happen when clicking or pressing space bar.
image

### PR DESCRIPTION
**Pull request by asudoh**
This change fixes a JavaScript error that happens when `<Toggle>` is used without `onChange` prop and user interacts it with keyboard.

Fixes #3453.

#### Changelog

**Changed**

- `<Toggle>` code checking `onChange()` existence before running it from the keyboard event handler.

#### Testing / Reviewing

Testing should make sure `<Toggle>` is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, toggling with `Enter` no longer logs an error

**Comment by lovemecomputer** [comment]
in the vanilla preview build, the return key does not trigger the Toggle to toggle (spacebar _does_ work). 

the return key _does_ trigger the toggle in react, however. 

not sure why there is a discrepancy, but i can test more locally later on, if you need me to!

**Comment by emyarod** [comment]
@lovemecomputer just FYI `Enter` doesn't toggle checkboxes by default and we don't have any custom logic for the vanilla toggle. the React toggle handles `Enter` keypresses, but that was added in https://github.com/carbon-design-system/carbon-components-react/pull/2219 so the discrepancy is unrelated to this PR

**Comment by lovemecomputer** [comment]
@emyarod i see, thank you for the context! i wanted to verify that i was testing properly before approving.

**Review by lovemecomputer — APPROVED** [review]
🎉

**Review by joshblack — APPROVED** [review]

**Pull request merged**
