### PR TITLE
fix(pagination): adjust md breakpoint chevron position

### LINKED ISSUE #3328: [Pagination] Fix spacing of number of pages dropdown
The current spacing of the dropdown for number of pages has too much spacing compared the the dropdown on the left for items per page. It may be inheriting something from select?

Current:

Redlines:

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3328

This PR adjusts the spacing between the select and chevron down icon in pagination components

#### Changelog

**Changed**

- incorrect style rules for selects in pagination component
- Replace chevron glyph icon in React `<Select>`

#### Testing / Reviewing

Ensure the pagination component is visually correct

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] Missing a rule line between '1-10 of 40 items' and '1'
Screen Shot 2019-07-12 at 2 16 36 PM

- [x] There should be a space before and after the en dash 
- [x] The chevrons are sitting low in the container. They should be centered.
Screen Shot 2019-07-12 at 1 58 13 PM
- [x] Can we make the '1-10 of 40 items' text to `text-02`
- [ ] There is more padding for the second dropdown in react than in vanilla.The spacing in vanilla is correct.
Vanilla:
Screen Shot 2019-07-12 at 2 22 00 PM

React:
Screen Shot 2019-07-12 at 2 24 46 PM

**Comment by emyarod** [comment]
>  There is more padding for the second dropdown in react than in vanilla.The spacing in vanilla is correct.

@laurenmrice this difference is because the React select goes from pages 1 to 11 so the select is wider to accommodate 2 digits (ref https://github.com/carbon-design-system/carbon/issues/3328#issuecomment-510968857). The vanilla example only goes from 1 to 5

image

image

will address the other points in your review

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Ok only one more thing, check the padding on either side of the dropdowns within the pagination component. It should be 16px each. I attached a spec to show how it should look for enabled, hover, focus, and padding 
specpag
specs.

**Review by alisonjoseph — APPROVED** [review]
LGTM from a dev perspective once design signs off 👍

**Comment by emyarod** [comment]
sure @laurenmrice I made that change. I guess the spec was updated since https://github.com/carbon-design-system/carbon/issues/1638?

**Review by jnm2377 — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
looks great andrew!

**Pull request merged**
