### PR TITLE
fix(data-table): fix action bar animation

### LINKED ISSUE #3058: [Data table] action bar animation broken
The action bar animation is broken since the last time I checked. 

Current: 

Jun-13-2019 10-26-51

Should be: 
 
temp

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3058.

@jnm2377 Seems that this change may affect your change at https://github.com/jnm2377/carbon-components/commit/75d5eccacc83b6ce865330003740a942cddb5208#diff-219e33146a644a16ef77f4f184a4ce3f - Please let me know if you think it'll be the case and what thing may be broken by putting `background-color` back. Thanks!

#### Changelog

**Changed**

- Bring back `background-color` of table header cell.

#### Testing / Reviewing

Testing should make sure data table is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by shixiedesign — COMMENTED** [review]
- blue of the action bar shows through the shorter rows (variants: **Short Select, Small Select**)
Jun-18-2019 09-26-15
Jun-18-2019 09-27-31

- [ ] animation is still broken on **any data tables with Search** (variants: Expandable, Expand all, Pagination) it seems
Jun-18-2019 09-29-43

- [ ] animation here too, and **data table with pagination** has pagination is sticking out. Not a big deal, but is it possible to align? 
Jun-18-2019 09-31-41

**Comment by jnm2377** [comment]
Ah, @asudoh that may have been a regression in my PR. I had opened that PR before we had the monorepo and then we switched to monorepo before it got merged in, so I had a lot of conflicts with that PR. I think removing the background-color was not intentional, so it should be fine adding it back in.

**Comment by jnm2377** [comment]
It looks like it also had some animation that was removed. That wasn't intentional either. I think we could add those back.

```css
background-color: $ui-03;	
transition: background-color $duration--fast-01 motion(entrance, productive), outline $duration--fast-01 motion(entrance, productive);
```

**Comment by asudoh** [comment]
@shixiedesign Thank you for finding those out - Fixed animations. The pagination alignment issue is fixed as part of #2965 ([ref](https://github.com/carbon-design-system/carbon/pull/2965#issuecomment-501041563)).

@jnm2377 No worries, just wanted to see your intent - And thank you for bringing up another line that were missed!

**Review by shixiedesign — DISMISSED** [review]
Thank you Akira! Only 1 last thing I noticed: 
- [ ] Did **Small select data table** 's action bar ghost buttons got bumped down? they are not middle-aligned any more. 
image

**Review by shixiedesign — COMMENTED** [review]
Thank you Akira! Only 1 last thing I noticed: 
- [ ] Did **Small select data table** 's action bar ghost buttons got bumped down? they are not middle-aligned any more. 
image

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Comment by asudoh** [comment]
@shixiedesign Thank you for pointing it out. Seems that it was pre-existing issue (wrong button height). Fixed.

**Review by shixiedesign — APPROVED** [review]
🎉 Beautiful! Thanks so much. Really nice work!

**Pull request merged**
