### PR TITLE
feat: sliding selector

### PR DESCRIPTION
**Pull request by lee-chase**
An experiment in making the content switcher slide

### CODE REVIEW

**Comment by lee-chase** [comment]
Not sure why this does not generate a a storybook preview.

**Comment by lee-chase** [comment]
@mikeolasov @glapadre can you add your thoughts/updates to this?

**Comment by mikeolasov** [comment]
> @mikeolasov @glapadre can you add your thoughts/updates to this?

Two primary notes:
- The focus state activating on the selected icon and not on the icon that's sliding over
- The sliding icon has a crossfade of multiple layered elements that's producing some muddy visual results

**Comment by tay1orjones** [comment]
Hey, thanks again for all your work here! It's been a couple months since there was movement here. In the interest of keeping the PR queue focused on actionable in progress items I'm going to close this PR for now.

If/when you're ready to pick this back up feel free to reopen this PR or open a new one.

**Pull request closed without merging**
