### PR TITLE
feat(themes): add ability to emit custom properties

### PR DESCRIPTION
**Pull request by joshblack**
Add ability to optionally output CSS Custom Properties as part of `carbon--theme`.

#### Changelog

**New**

**Changed**

- **themes**
  - Build task now updates `carbon--theme` to conditionally emit CSS Custom properties
  - Preview now contains example of how to toggle between themes
- **scss-generator**
  - Now supports AST nodes in various positions

**Removed**

### CODE REVIEW

**Comment by asudoh** [comment]
Good start on CSS custom properties support. Any thoughts on emitting Sass variables and CSS custom properties separately - Given the latter tends to be as part of a CSS ruleset.

**Comment by joshblack** [comment]
We definitely could, although it seems like doing so under the theme mixin might help future-proof it? It is nice to be able to do:

```
:root {
  @include carbon--theme($theme--white);
}

.dark-mode {
  @include carbon--theme($theme--g100);
}
```

Basically, I figured usage of the mixin would occur in similar places so that's why it ended up there. With the optional flag, the user can also conditionally include or omit these properties, as well.

**Comment by asudoh** [comment]
Any thoughts on having a way for `.dark-mode { @include carbon--theme($theme--g100); }` to avoid overriding Sass global theme variables? e.g. `$emit-sass-variables`.

**Update**: Another approach may be introducing a separate mix-in, like:

```scss
/// Emits CSS custom properties from a Carbon theme map.
/// @param {Map} $theme-map [$carbon--theme] The theme map to emit CSS custom properties from.
/// @example @include theme--custom-properties($carbon--theme--white);
@mixin theme--custom-properties($theme-map: $carbon--theme) {
  @each $key, $value in $theme-map {
    --#{$key}: #{$value};
  }
}
```

**Comment by joshblack** [comment]
@asudoh 

> to avoid overriding Sass global theme variables? e.g. $emit-sass-variables.

I believe the current implementation ends up resetting any overrides at the end of the mixin. As I understand it, it's essentially a noop for things outside of the stack frame. In this case, talking about this block: https://github.com/carbon-design-system/carbon/blob/master/packages/themes/scss/_mixins.scss#L92-L95

>  Another approach may be introducing a separate mix-in, like:

Tried to address this above with:

> We definitely could, although it seems like doing so under the theme mixin might help future-proof it?

**Comment by asudoh** [comment]
Thanks for clarifying - I tend to choose scoping provided by language features over changing-global-then-reset approach, but I now understand your intent.

**Review by tw15egan — APPROVED** [review]
Very nice! 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Pull request merged**
