### PR TITLE
fix(time-picker): reset select margins

### LINKED ISSUE #5745: Time picker select inputs have additional left and right margins in Safari
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

image

image

The time picker select inputs have an extra left and right margin

> Is this issue related to a specific component?

Time picker

> What browser are you working in?

Safari

## Steps to reproduce the issue

View time picker storybook examples in Safari

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5745 

found during https://github.com/carbon-design-system/carbon/pull/5686 review. not sure if we want to add this to our CSS reset instead but I scoped this to the time picker select inputs for now. we may also want to look into importing the select component directly in our time picker in the future

#### Changelog

**New**

- `margin` reset rule for time picker select inputs

#### Testing / Reviewing

Confirm the time picker appears correct

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by aledavila — APPROVED** [review]
lgtm

**Comment by laurenmrice** [comment]
need links :D so I can review. I'm not sure why they are not appearing.

**Comment by emyarod** [comment]
is the one above not working correctly for you? otherwise I can take screenshots

**Comment by laurenmrice** [comment]
Links have appeared! I can review now, thanks!

**Review by laurenmrice — APPROVED** [review]
spacing between fields looks correct now 👍🏻 thanks !

**Review by tw15egan — APPROVED** [review]

**Comment by asudoh** [comment]
@emyarod thinks this is ready to merge - Thanks @emyarod!

**Pull request merged**
