### PR TITLE
fix(icons-angular): use DOMParser to support ie11

### LINKED ISSUE #2826: SVG icons don't show up in IE 11
Hello,

I've been using this for my project: https://github.com/carbon-design-system/carbon-elements/tree/master/packages/icons-angular.

But in IE 11, none of the icon is getting displayed. When inspected, the `<path>` is not getting rendered.

Thanks.

### PR DESCRIPTION
**Pull request by cal-smith**
Closes #2826 

IE11 doesn't allow `innerHTML` calls on SVG elements, to work around this we can use DOMParser and manually append the nodes into our SVG host element.

#### Changelog

**New**

- angular 8 support

**Changed**

- switched to DOMParser in the icon directive to support IE11

### CODE REVIEW

**Comment by cal-smith** [comment]
There seems to be some weirdness in how the SVG is sized ... it doesn't seem to be respecting the `width`/`height` attrs ... so, blocked until I sort that out

**Comment by cal-smith** [comment]
🤔 seems to be something to do with `setAttributeNS` ... investigating ...

**Comment by cal-smith** [comment]
Yeah it seems like `setAttributeNS` was unnecessary and, more importantly, it broke the usual `width`/`height` attrs ... fixing!

**Comment by cal-smith** [comment]
Ready for review!

**Review by joshblack — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @cal-smith!

**Pull request merged**
