### PR TITLE
fix(react): added onClick type to SwitcherItem

### LINKED ISSUE #15440: [Bug]: SwitcherItem types. "onClick" prop does not exist
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox

### Package version

v1.45.0

### React version

v18

### Description

Since I updated my carbon/react package from ver. 1.40.0 to ver. 1.45.0, typescript started complaining about the "onClick" prop in the SwitcherItem component. 

### Reproduction/example

https://codesandbox.io/p/github/Yaren-IT/carbon-nextjs-sidenav/csb-5mffqr/draft/inspiring-poincare?file=%2Fapp%2Fpage.tsx%3A24%2C26

### Steps to reproduce

Screenshot 2023-12-22 at 11 41 19

1. open Codesandbox
2. open page.tsx
3. you can find typescript complaining on lines 37 and 44

The error message is 

> Type '{ children: string; key: number; "aria-label": string; onClick: () => void; }' is not assignable to type 'IntrinsicAttributes & (SwitcherItemProps & RefAttributes<ElementType<any, keyof IntrinsicElements>>)'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & SwitcherItemWithAriaLabel & RefAttributes<ElementType<any, keyof IntrinsicElements>>'.typescript(2322)

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by amercury**
Closes #15440

added a type for `onClick` handler in SwitcherItem component

#### Changelog

**New**

-  `onClick` prop in SwitcherItem component

**Changed**

- SwitcherItem.tsx, SwitcherItem-test.js

**Removed**

### CODE REVIEW

**Review by andreancardona — APPROVED** [review]
Thank you for the contribution! @amercury looks good. You just need to add the following comment "I have read the DCO document and I hereby sign the DCO."

**Comment by amercury** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by amercury** [comment]
recheck

**Review by guidari — APPROVED** [review]

**Comment by amercury** [comment]
recheck

**Comment by amercury** [comment]
@andreancardona @guidari sorry to bother you, but what can I do to run a pipeline with checks like `avt`, `format`, `lint` etc. to merge my branch with master?

**Comment by guidari** [comment]
> @andreancardona @guidari sorry to bother you, but what can I do to run a pipeline with checks like `avt`, `format`, `lint` etc. to merge my branch with master?

Hey @amercury
The branch is on merge queue and it will merge soon!
Thank you for the contribution! 🚀

**Pull request merged**
