### PR TITLE
fix(Modal): clean up Modal, ComposedModal stories

### LINKED ISSUE #7671: [audit] modal storybook bugs
- Storybook needs to be update to new structure with playground
- Playgrounds and example for `modal` and `composedModal` should include the same content. Right now its featuring different content and examples.
- Need a knob for different footer options: 1, 2 and 3 button options

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/7671

Syncs the `Modal` and `ComposedModal` storybooks so that they show similar examples. This also adds in single-button functionality to `Modal` instead of users needing to use `ComposedModal` for that variant.

@aagonzales let me know if there are any other stories we want to display. I don't see anything for 3 buttons, so I'm wondering if we should split that into a separate issue and I can add that in separately.

#### Changelog

**New**

- A new knob called `Number of buttons` allows you to dynamically choose how many buttons should display. Can be found in the `Playground`

**Changed**

- There are now 4 stories, `Default`, `Passive`, a state manager example to handle `open`/`close`, and a `Playground` that has all knobs enabled
- The presence of the `secondaryButtonText` prop will now handle displaying the secondary button in `Modal`

**Removed**

- Old examples

#### Testing / Reviewing

Ensure all knobs work, there are no prop warnings in the console

Are there any additional stories we would like to see here?

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
it looks like there are a few failing CI tests currently, otherwise looks good to me after design review. on a side note I have some leftover local modal enhancements from #4607 if we want to reprioritize it

**Comment by tw15egan** [comment]
@emyarod awesome! Yeah I think we should definitely prioritize getting that into the next sprint 👍

**Comment by aagonzales** [comment]
Looks good!

@tw15egan For additional stories, does the modal component have built in [validation](https://carbondesignsystem.com/components/modal/usage/#validation) or [loading](https://carbondesignsystem.com/components/modal/usage/#loading)? Or are those applied later?

**Comment by tw15egan** [comment]
@aagonzales Nothing built-in, but a user could use those individual components (Form elements, Inline Loading) to create those experiences

**Review by aagonzales — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
I guess I left my previous review on "comment", was waiting for this to continue #4607

**Review by aledavila — APPROVED** [review]
lgtm 🎉

**Pull request merged**
