### PR TITLE
fix(list-box): add focus outline for highlighted items

### LINKED ISSUE #3121: AVT- Dropdown list- Focused item is not visible when color is removed
## Title 
When colour is removed, the focused item in dropdown list is not visible.

FF 67.03

- A distinguishable visual focus indicator helps keyboard-only users locate the point of focus.

> What happened instead? 
- The focus is not visible when you try to select any option on the menu.

## Steps to reproduce the issue

1. Step one: To remove color follow  next steps:
For Firefox®:
• Select Tools >Options.
• On the Language and Appearance section select Colors... button.
• On the Colors window go to Override the colors specified by the page with your selections above: and open the menu and select Always, then press OK.
• On the Advance button deselect the Allow pages to choose their own fonts, instead of your selections above checkbox.
• Select OK to save changes.

2. Step two: 
In url: http://react.carbondesignsystem.com/?path=/story/dropdown--default

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/carbon-components-getting-started-t3ec6
> - React:
> https://codesandbox.io/s/codesandbox-bxf8v

## Additional information
It seems only the Vanilla JS has visible focus indicator:
Screenshot-2019-06-20-14:55:58

- Notes

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3121

This PR adds a focus outline to highlighted items in listbox components. It looks like the active and highlighted behavior were combined in this PR carbon-design-system/carbon-components-react#1502

for now I have gone back to differentiating between active and highlighted items (active items will receive bold font weight and highlighted items will receive an outline), but going to defer to design on the final decision on combobox visuals

#### Changelog

**New**

- focus outline for highlighted items
- bold font weight for active items
- disabled styles for highlighted items to remove outline and text color

**Changed**

- separate highlighted and active items (align with default downshift behavior)

#### Testing / Reviewing

Ensure focus, highlight, and active indicators are viewable in listbox components (check original ticket for high contrast Firefox)

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by joshblack — COMMENTED** [review]
Quick question was around if the nodes themselves received focus, and if not are we making sure that the nodes themselves that get focused don't have an outline?

**Review by tw15egan — APPROVED** [review]
👍

**Comment by lovemecomputer** [comment]
cool!

curious if we want to distinguish hover outline color from focus color?

when first clicking to open comobox, the comboxbox is in focus, as well as the first item:
Screen Shot 2019-06-20 at 4 36 51 PM


when hovering an additional item (option 3 in this screenshot), 
Screen Shot 2019-06-20 at 4 35 38 PM


this is responding to user input, so it should still be understandable! just pointing this out in case we want to vary it up or anything

**Comment by emyarod** [comment]
@joshblack focus does not change from the input, this is the default behavior in downshift

@lovemecomputer it's also default downshift behavior to highlight the selected item in the dropdown, so we end up in this situation where we have focus on the input field, and outline around the currently active item in the input, and an outline for the item highlighted by the user. changing the colors will not resolve the original issue here, since high contrast modes will override colors

it looks like the active and highlighted behavior were combined in this PR https://github.com/carbon-design-system/carbon-components-react/pull/1502

for now I have gone back to differentiating between active and highlighted items (active items will receive bold font weight and highlighted items will receive an outline), but going to defer to design on the final decision on combobox visuals

**Review by chrisconnors-ibm — CHANGES_REQUESTED** [review]
cannot verify without a spec. no spec here or in linked issue? Or was this just making react & vanilla match? 

DO NOT MERGE

**Comment by chrisconnors-ibm** [comment]
> cool!
> 
> curious if we want to distinguish hover outline color from focus color?
> 
> when first clicking to open comobox, the comboxbox is in focus, as well as the first item:
> Screen Shot 2019-06-20 at 4 36 51 PM
> 
> when hovering an additional item (option 3 in this screenshot),
> Screen Shot 2019-06-20 at 4 35 38 PM
> 
> this is responding to user input, so it should still be understandable! just pointing this out in case we want to vary it up or anything

does this make `focus` `hover` and `selected` all the same blue outline?

`focus` has a very specific meaning - takes a the keyboard event. if there are three identical adornments meaning 3 very different things (for everyone), that's worse than not showing focus for the audience that doesn't perceive color

**Comment by chrisconnors-ibm** [comment]
what gets the event when I hit the return key here:
image

**Comment by chrisconnors-ibm** [comment]
here are the unresolved design issues for which a spec is needed:
1. showing `selected` item with a style that that is distinct from `hover` or `focus` (if we decide we need more than displaying the value in the menu control itself) 
2. `hover` and `focus` can be the same style/indication, but keyboard set `focus` must be immediately released if a new `hover` is detected.


focus-hover

**Comment by emyarod** [comment]
it looks like the images are showing outdated behavior, can you describe how to reproduce what you are seeing?

focus does not change in the combobox, it is always on the input field. this is marked by a blue outline

the active item refers to the item that currently populates the input field. this is marked with bold font in this PR

the highlighted item refers to the item that is currently highlighted by the user either by hover or by keyboard navigation. this now gets a blue outline

**Comment by emyarod** [comment]
> > cool!
> > curious if we want to distinguish hover outline color from focus color?
> > when first clicking to open comobox, the comboxbox is in focus, as well as the first item:
> > Screen Shot 2019-06-20 at 4 36 51 PM
> > when hovering an additional item (option 3 in this screenshot),
> > Screen Shot 2019-06-20 at 4 35 38 PM
> > this is responding to user input, so it should still be understandable! just pointing this out in case we want to vary it up or anything
> 
> does this make `focus` `hover` and `selected` all the same blue outline?
> 
> `focus` has a very specific meaning - takes a the keyboard event. if there are three identical adornments meaning 3 very different things (for everyone), that's worse than not showing focus for the audience that doesn't perceive color



it looks like you were reviewing Dropdown rather than ComboBox. I've changed Dropdown active/highlighted item behavior to match ComboBox now

**Comment by emyarod** [comment]
@dakahn do you mind giving this a look over? @laurenmrice and I need a bit of guidance on acceptable a11y practices for high contrast listbox components

**Comment by dakahn** [comment]
As far as keyboard users are concerned there should be[ two distinct visual state](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_focus_discernable_predictable )s: **active** and **focused**. Think of your focus state like a pointer tracking the path of navigation. Visually there should only be one point of focus at any time.

[WAI-Aria authoring practices give two "most important considerations" here:](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_focus_vs_selection)

**- The visual focus indicator must always be visible**
**- The selected state must be visually distinct from the focus indicator**

If we're looking at our component in question:
2019-07-02 17_00_31-Window

Our ListBox component's active and focused states do not seem to meet the criteria of being "visually distinct" in any reasonable way.

The situation gets pretty grim in Windows 10 High Contrast Mode 💀:
2019-07-02 17_28_05-Window

The High Contrast Mode detecting CSS in our reset only applies to SVG icons (right now), you'll need to implement it in the CSS here as well -- here's some refs:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast
http://www.gwhitworth.com/blog/2017/04/how-to-use-ms-high-contrast/

**Review by dakahn — CHANGES_REQUESTED** [review]
Thanks for the ping! @emyarod @laurenmrice 🏄 
 
As far as keyboard users are concerned there should be two distinct visual states: **active** and **focused**. Think of your focus state like a pointer tracking the path of navigation. Visually there should only be one point of focus at any time.

[WAI-Aria authoring practices give two "most important considerations" here:](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_focus_vs_selection)

**- The visual focus indicator must always be visible** 
**- The selected state must be visually distinct from the focus indicator** 

If we're looking at our component in question:
2019-07-02 18_07_07-Window

[Reviewing the Authoring Practices on the perception of dual focus](https://www.w3.org/TR/wai-aria-practices-1.1/#kbd_focus_vs_selection) our list box component doesn't seem to meet the second criteria for having the active element (top most node that opens menu) and focused element (current navigation point) being visually distinct from one another. @snidersd Any thoughts here? 

The situation gets pretty grim in Windows 10 High Contrast Mode 💀:
2019-07-02 18_02_57-Window

The High Contrast Mode detecting CSS in our reset only applies to SVG icons (right now), you'll need to implement it in the CSS here as well -- here's some refs:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/-ms-high-contrast
http://www.gwhitworth.com/blog/2017/04/how-to-use-ms-high-contrast/

Also, it's not a regression, but I'm not sure why the chevron SVG is not picking up the HCM code in our reset? 😕 @joshblack

**Comment by emyarod** [comment]
it looks like you're viewing the vanilla dev env listbox which only exposes the base styles. the changes are only visible in the React library because they're built on downshift, we don't expose the vanilla listbox anywhere outside of the dev environment

**Comment by dakahn** [comment]
Oh! Mega confusing since there's a vanilla ListBox component, but ListBox is _used_ in React's Dropdown. Sorry I'll update my review 👍

**Comment by emyarod** [comment]
yeah listbox is the base for our React dropdown, combobox, multiselect, and filterable multiselect. listbox is an internal component only viewable in our vanilla dev environment. for that reason, we don't document it on our website

for clarification, using combobox as an example: there is a focused element, a highlighted element, and an active element. `focus` (DOM/CSS/JS focus) is always kept on the trigger button, which shows the selected item if a selection has been made. the terms "highlight" and "active" come from [downshift](https://github.com/downshift-js/downshift). "highlight" marks the user's current position in the menu, and "active" refers to the currently selected item (assuming a selection was previously made)

image

the original issue uses the term "focus" but it is referring to highlighted items. currently we don't differentiate between highlighted and active items, and we also lack high contrast mode support for those 3 states (this was introduced in https://github.com/carbon-design-system/carbon-components-react/pull/1502 as mentioned in topmost comment). right now this PR differentiates highlight and active states according to downshift defaults and makes them distinct in high contrast mode. so I hope this PR is a catalyst for that discussion involving the a11y team and our designers. it seems like we need to visit the drawing board for a bit before there is anything actionable on the dev side, since it sounds like returning to downshift default behavior is not sufficient for our needs

I believe we should address this by at least reverting to downshift defaults while we iterate on the design spec. it's a severe issue caused by a major regression

**Comment by joshblack** [comment]
@dakahn any other outstanding concerns?

@laurenmrice do you have a chance to review?

**Review by dakahn — APPROVED** [review]
It's chill if this is a "lets do what we can" PR. I'll make a note to open an issue where we can hash out the busted HCM support, and confusing active vs focus vs highlighted styling. :hurtrealbad:

**Comment by joshblack** [comment]
Removing from v10.4 milestone due to some uncertainty here on the design side. Let me know if this was done in error and we can definitely change back!

**Comment by jeanservaas** [comment]
Don't think we want to close this @emyarod ? @laurenmrice

**Comment by emyarod** [comment]
unless there are any updates this is still blocked on the design side @jeanservaas

**Comment by lnajjar** [comment]
Could you please add this very helpful component to the Carbon Design System Sketch library so I can use it in my user interfaces?

**Comment by lnajjar** [comment]
Could you please add this component to the Carbon Design System Sketch library so I can use it in my user interface designs?

**Comment by laurenmrice** [comment]
@lnajjar We do have the Combobox in the library already, its under Dropdown.

**Comment by lnajjar** [comment]
@laurenmrice, I think we have a terminology problem. I was not looking for a combo box. I was looking for a _list_ box. Also, the title of this discussion includes "list-box" but appears to describe dropdowns. Miscommunication ensues.

Anyway, to meet the needs of enterprise users, I need a classic, vertically scrollable, selectable item, multiple column list box: https://en.wikipedia.org/wiki/List_box

image


https://doc.4d.com/4Dv17/4D/17.2/Managing-List-Box-Objects.300-4386875.en.html

image

**Comment by emyarod** [comment]
@lnajjar for clarification, we do have a listbox component (https://the-carbon-components.netlify.com/?nav=list-box) but it is an internal and React only component (https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ListBox/ListBox.js). Our React dropdown, multiselect, and combobox components are built on top of it. From your description it seems our existing multiselect or combobox components would meet all of your requirements except for multiple columns. if this is not the case feel free to make a separate issue for further discussion

**Comment by laurenmrice** [comment]
@lnajjar I think that our Combobox and/or multi-select dropdown would meed your needs, except we do not currently have functionality for multiple columns. For the future, if you have feature requests please open a new issue so we can easily track this discussion :).

**Comment by lnajjar** [comment]
Yeah, beside being an unavailable, internal, and React only component, the
"list box" component at
https://the-carbon-components.netlify.com/?nav=list-box is not the classic
list box. It is some kind of scrollable dropdown menu. Your multi select
dropdown and combo boxes are not list boxes.

My enterprise users need the classic list box user interface component:
https://doc.4d.com/4Dv17/4D/17.2/Managing-List-Box-Objects.300-4386875.en.html

[image: image.png]

and: https://en.wikipedia.org/wiki/List_box

[image: image.png]

So, yes, I will submit a request for this new feature.


Lawrence Najjar
lnajjar100@gmail.com
http://www.lawrence-najjar.com/new-index.html
(512) 740-6852

**Comment by lnajjar** [comment]
Yeah, beside being unavailable, internal, and React only, the "list box" component at [https://the-carbon-components.netlify.com/?nav=list-box](url) is not the classic list box. It is a scrollable dropdown menu. Also, the multi select dropdown and combo boxes you mention are not list boxes.

My enterprise users need the classic list box user interface component: https://doc.4d.com/4Dv17/4D/17.2/Managing-List-Box-Objects.300-4386875.en.html

image.png
image

and: [](https://en.wikipedia.org/wiki/List_box)

image

So, I will take your advice and open a new issue for this feature request

**Comment by chrisconnors-ibm** [comment]
@carbon-design-system/design : we need an effort to resolve this, and ideally, broader issues with `focus` and `indicate selected` states for this and other controls.

**Comment by jnm2377** [comment]
Following up: can we get clear action items from @carbon-design-system/design so that we can get this merged. What exactly does this PR need to get approved?

**Review by chrisconnors-ibm — CHANGES_REQUESTED** [review]
We cannot approve this as is. @carbon-design-system/design needs to address this holistically. Recommended fix impacts a BUNCH of other controls. DO NOT MERGE.

**Comment by jnm2377** [comment]
closing per discussions here: https://ibm-studios.slack.com/archives/GCPF37GEB/p1568225875130800

**Comment by chrisconnors-ibm** [comment]
Design issue to address the problem is here: https://github.com/carbon-design-system/carbon/issues/3988

**Review by laurenmrice — COMMENTED** [review]
@emyarod 

**Hover state:**
Add a 2px border on top of the hover that is the same color (`hover-ui`).

**Selected state:**
Add a checkmark icon inline with the selected row. The checkmark icon should be color `icon-01`. Make sure the selected row is color `selected-ui`. Ref open issue: #3531 

Here is a visual spec below:
Artboard

**Comment by joshblack** [comment]
@laurenmrice I don't believe this is active work right now for a project, should we keep it closed until it can be picked up?

**Comment by laurenmrice** [comment]
@joshblack  Oh okay, its up to dev, I guess Andrew that would be continuing it.

**Comment by joshblack** [comment]
@laurenmrice I believe it'd fall under devs in the components project 👍 @emyarod is on theming right now.

**Pull request closed without merging**
