### PR TITLE
fix(button): set minimum height instead of fixed height

### LINKED ISSUE #1893: Button: wrapping content overflows button container
## Detailed description
When a button's content wraps to multiple lines the content can overflow the bounding container

> Describe in detail the issue you're having.

image

> Is this issue related to a specific component?

Button

> What did you expect to happen? What happened instead? What would you like to see changed?

The height of the button would expand as needed

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Assets Library (PAL)

## Steps to reproduce the issue

1. Add enough content to the button/or reduce the parent container size that the text within the button wraps to multiple lines

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1893

This PR will replace the fixed height of our buttons with a minimum height so that it can grow based on its content

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
Looks good to me!

**Comment by photodow** [comment]
I was just coming here to create an issue around this. It probably doesn't carry much weight here, but this looks good to me! 👍 😉

**Review by jeanservaas — APPROVED** [review]
LGTM too

**Comment by elizabethsjudd** [comment]
Thank you for getting this in there so quickly!

**Pull request merged**
