### PR TITLE
fix(react): update side nav aria-hidden check

### LINKED ISSUE #11122: [a11y]: Collapsed SideNav Rail aria-hidden is accessibility violation
### Package

carbon-components-react

### Browser

_No response_

### Operating System

_No response_

### Package version

v7.56.0

### React version

_No response_

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker

### Assistive technology

_No response_

### Description

When a SideNav Rail is collapsed, `aria-hidden` is set to true, but there are still active buttons within the `nav` element. This is an accessibility violation. (`A focusable element should not be within the subtree of an element with 'aria-hidden' set to "true"`)

This can be seen when running the Accessibility Checker on the Storybook page: https://react.carbondesignsystem.com/?path=/story/components-ui-shell--side-nav-rail

This line should probably take isRail into account: https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/UIShell/SideNav.js#L125

### WCAG 2.1 Violation

1.3.1 Info and Relationships

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-ui-shell--side-nav-rail

### Steps to reproduce

Run Accessibility Checker on SideNav Rail story.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by joshblack**
Closes #11122 

This PR includes `isRail` in the check to see if the SideNav should be `aria-hidden`, or not.

#### Changelog

**New**

**Changed**

- Update `aria-hidden` to include an `isRail` check

**Removed**

#### Testing / Reviewing

- Run accessibility checker on the story in #11122 and verify no AC violations occur

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]

**Review by jnm2377 — COMMENTED** [review]
Did you mean to include the breadcrumb changes in this PR?
Also, I checked the rail story for this PR and our live storybook, and I'm not seeing the a11y violation in the current rail story (I was trying to see what to compare it to).
Screen Shot 2022-05-09 at 11 44 51 AM

**Comment by jnm2377** [comment]
@joshblack just wanted to follow up on this. I wasn't sure if I was testing correctly bc I'm not seeing the a11y violation in the current component. Also wasn't sure if you meant to include the breadcrumb changes in this PR or if it should just be the sidenav stuff.

**Comment by tay1orjones** [comment]
Looks like this might've been branched off https://github.com/carbon-design-system/carbon/pull/11358, which would explain the breadcrumb stuff. I'll update with latest from `main` which should pull it out of this PR.

**Review by tay1orjones — APPROVED** [review]
@jnm2377 I can get the error with current storybook

image

This PR fixes it for me 👍  Admittedly odd that yours passes, it looks to be the same url we're both using 🤔

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
