### PR TITLE
Clarify unary for Sass

### LINKED ISSUE #17593: [Bug]: Strict unary deprecation in Sass
### Package

@carbon/styles

### Browser

_No response_

### Package version

1.66.0

### React version

18.2.0

### Description

I get this warning when building:

```text
DEPRECATION WARNING on line 128, column 20 of ../../node_modules/@carbon/styles/scss/components/modal/_modal.scss: 
This operation is parsed as:

    -$spacing-05 - $spacing-05

but you may have intended it to mean:

    -$spacing-05 (-$spacing-05)

Add a space after - to clarify that it's meant to be a binary operation, or wrap
it in parentheses to make it a unary operation. This will be an error in future
versions of Sass.

More info and automated migrator: https://sass-lang.com/d/strict-unary
    ╷
128 │     margin-inline: -$spacing-05 -$spacing-05;
    │                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
```

I'm using Sass 1.69.7

### Reproduction/example

https://codesandbox.io/p/devbox/practical-bush-ywp9pq

### Steps to reproduce

Open the CodeSandbox link and run the following in a terminal.

```
npm install && sass --load-path=./node_modules style.scss output.css
```

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by frankharkins**
Closes #17593

https://sass-lang.com/documentation/breaking-changes/strict-unary/

This line causes a deprecation warning in newer versions of Sass. This PR makes a small edit to solve the warning. This shouldn't change the behaviour of the style as Sass interprets the syntax as a subtraction (EDIT: This did not have no effect as I thought, see [my comment](https://github.com/carbon-design-system/carbon/pull/17595#issuecomment-2382777756)). This is also most likely what the original author intended, otherwise they could have omitted the second `-$spacing-05`.

#### Changelog

**Changed**

- Changed style to make compatible with https://sass-lang.com/d/strict-unary.

#### Testing / Reviewing

Probably easiest way to verify this is to go to the [CodeSandbox repro](https://codesandbox.io/p/devbox/practical-bush-ywp9pq) and add the space to `node_modules/@carbon/styles/scss/components/modal/_modal.scss (L128)`.

### CODE REVIEW

**Comment by frankharkins** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by Gururajj77 — APPROVED** [review]

**Comment by frankharkins** [comment]
Looking at the failed snapshot, it seems the change _did_ break the styling. I've switched to the other interpretation of the syntax.

**Review by tay1orjones — APPROVED** [review]

**Comment by tay1orjones** [comment]
Sorry for the flaky percy report, it definitely wasn't related to your changes. All should be good here to merge once status checks pass

**Comment by frankharkins** [comment]
@tay1orjones no worries, thanks for reviewing!

**Pull request merged**
