### PR TITLE
fix(data-table-skeleton): remove unnecessary border bottom

### LINKED ISSUE #2957: blue border-bottom in data-table th
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

There is a `border-bottom: 1px solid #0062ff;` applied to ` .bx--data-table.bx--skeleton th` that should not be there. (@jnm2377 has approved this)

> Is this issue related to a specific component?

data-table

> What did you expect to happen? What happened instead? What would you like to
> see changed?

no border-bottom. There is a border-bottom. To have no border-bottom.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.2.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

`carbon-components-angular`

Screen Shot 2019-06-06 at 3 36 59 PM

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #2957 

This PR removes the `border-bottom` on the table header of the DataTable Skeleton, removing the blue line visible here: 
Screen Shot 2020-01-14 at 4 32 38 PM

What it looks like from this PR: 
Screen Shot 2020-01-14 at 4 33 50 PM

#### Changelog

**Removed**

- border-bottom

#### Testing / Reviewing

For designers reviewing: Check the DataTable Skeleton and make sure that the blue border isn't supposed to be there according to spec.

### CODE REVIEW

**Comment by abbeyhrt** [comment]
@aagonzales  for context, the only change here is that the blue border bottom that is on the DataTableSkeleton has been removed. I think we just need you to confirm that is what we want! Let me know if you have any questions

**Review by aagonzales — APPROVED** [review]
Yup! Removing that border is the correct move. Thanks!

**Comment by jendowns** [comment]
Thank you @abbeyhrt this border has always mystified me 😆

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @abbeyhrt!

**Pull request merged**
