### PR TITLE
feat(radio-button): add validation props

### LINKED ISSUE #12643: Field validation errors: RadioGroup implementation
This issue is to track the dev implementation of field validation errors on a RadioGroup.

States needed:
- Invalid (error)
- Warn
- Helper text

## Spec
Radio button - White theme

### PR DESCRIPTION
**Pull request by aledavila**
Closes #12643

Adds `invalid` `warning` and `helperText` to `RadioGroup`

#### Changelog

**New**

- adds new validation props to the RadioGroup

#### Testing / Reviewing

Make sure new props work as expected
Make sure `readOnly` always takes precedence over other validation props.

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
LGTM! Unrelated to this issue, I did notice that the knobs for the regular story still work and not just the playground, not sure if we want to clean that up here or make a new issue?

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Oops, just took a look at Percy and it seems that there is an extra space now below the radio button group. (yay VRT!)
Screenshot 2023-03-10 at 8 11 30 AM

**Comment by aledavila** [comment]
@alisonjoseph thanks. Yea I can clean that up in this PR. I'll check about the space.

**Comment by aledavila** [comment]
@alisonjoseph updated. ready for review

**Review by alisonjoseph — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
🔥 looks good!

**Review by aagonzales — CHANGES_REQUESTED** [review]
The error icon should be using `$support-error`

image

The error message and icon are also misaligned
image

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
