### PR TITLE
fix(notification): update focus styles for low contrast

### LINKED ISSUE #5977: [Notification]: 'X' close button always has focused outline shown
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.

The 'x' close button is always showing the blue focused outline. When the notification is in low contrast mode, regardless of if the element is actually focused.

> Is this issue related to a specific component?

Vue: `CvToastNotificaiton` & `CvInlineNotification`
React: `ToastNotification` & `InlineNotification`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected the outline to only show when the element is focused

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Lastest `v10.11.2` (sandbox)

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. set notification to low-contrast

> Please create a reduced test case in CodeSandbox
>

Issue present:

> - React:
>   https://codesandbox.io/s/unruffled-breeze-8shf4?file=/index.js

> - Vue:
>   https://codesandbox.io/s/carbonvue-notification-btn-qzv6s

Issue not present:

> - Angular (not present)
>  sandbox - https://angular.carbondesignsystem.com/?path=/story/components-notification--toast

> - Vanilla (not present)
> https://the-carbon-components.netlify.app/component/notification--inline-low-contrast.html

## Additional information

Screenshot 2020-04-29 at 16 54 48

- related, but resolved by #4282

### LINKED ISSUE #6053: [Notification] Focus outline now permanent on low contrast notifications
## Environment

Any

## Detailed description

Issue #5737 was raised to changed the focus outline from white to blue, however the 'fix' was incorrect and is now permanently visible rather than only on `:focus` events.

This makes the low contrast button quite distracting and it now has visually different behaviour from high contrast. 

Much like the original defect, it continues to break accessibility as the button still has no focus indicator.

> What WCAG 2.1 checkpoint does the issue violate?
https://www.ibm.com/able/guidelines/ci162/focus_visible.html

## Steps to reproduce the issue

1. Navigate to https://react.carbondesignsystem.com/?path=/story/notifications--inline
2. Check the low contrast knob
3. focus on the close button, there is no visual change

### PR DESCRIPTION
**Pull request by joshblack**
Closes #5977

Updates focus styles for low-contrast to be applied on `:focus`

#### Changelog

**New**

**Changed**

- Update toast and inline low contrast styles to include focus

**Removed**

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
Thanks for fixing that 👍 ✅

**Review by emyarod — APPROVED** [review]
looks good to me, should this get a visual review as well?

**Review by laurenmrice — CHANGES_REQUESTED** [review]
There is a slight haze/overlay when focusing on the`action` button in the notification. There should also be a 2px border around the action button, it looks like its at 1px.

Apr-30-2020 15-04-14

**Comment by joshblack** [comment]
@laurenmrice I believe the haze is coming from the styles for the ghost button if I understand correctly. Would we want to remove them?

For the outline, it should be using the 2px focus styles 👀 

image

**Comment by laurenmrice** [comment]
When I view the ghost button story and apply focus, it is not applying that visual overlay/haze look. I think this has something to do with how we are treating it in the notification component. 

When I was referring to 2px focus outline, the close icon outline is correct, it is the Action button that needs the 2px outline, it is currently at 1px. This is also different from how the ghost button story is, so I think it is only happening here.

**Comment by joshblack** [comment]
@laurenmrice Sounds good! Thanks so much for clarifying. Let me take a look 😄

**Review by laurenmrice — APPROVED** [review]
Thank you Josh ! Everything looks great 🙌🏻

**Pull request merged**
