### PR TITLE
chore(tabs): use fragment for customlabel wrapper in story

### LINKED ISSUE #3359: AVT 1 - React Tab, has a DAP violation on the custom label
## Environment
macOS Mojave version 10.14.5
Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React

## Detailed Description
1. Navigate to the Custom Label Tab
2. Run DAP and the following issue is present:
Screen Shot 2019-07-10 at 4 22 10 PM
Note: This is only a violation on the custom label tab.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3359 

#### Changelog

**Changed**

- wrap custom label text in a fragment instead of a `<span>` to avoid DAP violation (NOTE: theoretically putting a `<span>` inside an `<a>` should be fine? But this is a quick fix either way)

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@jendowns could you specify the commit as `chore` or `docs` since it's for a story? Doesn't need to apply to this one, but just for future ones 👍

**Comment by jendowns** [comment]
Oh sure thing @joshblack! 👍

**Review by abbeyhrt — APPROVED** [review]
Looks good!

**Review by alisonjoseph — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Pull request merged**
