### PR TITLE
fix(breadcrumb): terminating slash based on current page existence

### LINKED ISSUE #3625: Current Page breadcrumb fails Use of Color
## Current Page breadcrumb fails Use of Color

Windows 7

> Browser
Chrome and Firefox

## Detailed description

> What version of the Carbon Design System are you using?

React Storybook, v10, themes

> What did you expect to happen?

In the "current page" of the breadcrumbs, the only means of understanding that the current page is being displayed is to be able to distinguish between the blue and black text. Normally, my expectation would be that the links in the breadcrumbs (which would be the blue text here) would all have underlines, making them clearly identifiable as actionable links. Since the current page would not be expected to have a link, I would understand that this item without a link in the breadcrumb must represent the current page.

If an underline is not going to be employed on the breadcrumb links, then the black text of the current page must have at least a 3:1 relative luminance with the blue links of the actionable breadcrumbs.

> What WCAG 2.1 checkpoint does the issue violate?
https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html

## Additional information
Note that this model is disrupted, since the current page IS a link. That is a separate issue I will capture later, but I mention it here since it makes the current issue a bit messier.

Another option to overcome this challenge is to put a closing slash on the normal breadcrumb view (e.g., Breadcrumb 1 / Breadcrumb 2 / Breadcrumb 3 /). That way, when the current page is included, it would be distinguished by the fact there is no terminating slash e.g., Breadcrumb 1 / Breadcrumb 2 / Breadcrumb 3 / current page).

### PR DESCRIPTION
**Pull request by asudoh**
This change is to example/story code, where they use "with trailing slash" mode for ones without current page, and "without trailing slash" mode for ones with current page, so the current page existence can be commnunicated by the existence of the trailing slash.

Fixes #3625.

#### Changelog

**Changed**

- Breadcrumbs example/story code, as described above.

#### Testing / Reviewing

Testing should make sure breadcrumbs demo/story are not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by joshblack — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
Looks good! Just want to confirm we have to keep the current page as link (its still clickable) for accessibility reasons?

**Comment by aagonzales** [comment]
Follow up: could we remove the underline on hover for the current page and still be compliant?

**Comment by asudoh** [comment]
> Follow up: could we remove the underline on hover for the current page and still be compliant?

@aagonzales Done!

Also addressed a comment from @shixiedesign in #3625, by changing the mouse cursor for "current page" link.

**Review by aagonzales — APPROVED** [review]
Thanks for updating! Re-approving

**Review by shixiedesign — APPROVED** [review]
Nice work! Thank you!

**Pull request merged**
