### PR TITLE
feat(DataTable): update size prop, add md size

### LINKED ISSUE #8395: [data table] add 40px (md) row height
- Add a 40px (`md`) row height option to data table, since we have this size in most of our other components that offer size variants. 

Artboard

### PR DESCRIPTION
**Pull request by tw15egan**
Closes #8395 
Refs #8369 

This PR updates the `DataTable` and all variants to use the same prop values for the `size` prop as other components throughout the system.

Values determined by the following table:

| Name | Size |
|-----|-------|
| `xs` | 24 |
| `sm` | 32 |
| `md` | 40 |
| `lg` | 48 |
| `xl` | 64 |
| `2xl` | 80 | 

For now, `compact` will map to `xs`, `short` will map to `sm`, and `tall` will map to `xl. When we create an alpha branch, we can remove these extraneous code blocks. But for now, it will retain all current functionality.

#### Changelog

**New**

- Adds 5 new size props: `xs`, `sm`, `md`, `lg` (default), and `xl`
- Adds in styles for the new `md` size variant

**Changed**

- Anywhere we referenced `--compact`, I've added a `--xs` selector with a note to deprecate the `compact` selector in the next release
- Anywhere we referenced `--short`, I've added a `--sm` selector with a note to deprecate the `compact` selector in the next release
- Anywhere we referenced `--tall`, I've added a `--xl` selector with a note to deprecate the `compact` selector in the next release
- Renamed the expansion stories based on their size

#### Testing / Reviewing

I've kept the old size props, as well as adding in the new ones, to the `knobs` for the DataTable variants that are not inside of folders. I will remove these extra props before merging, but it will allow you to test all sizes in a few different Table scenarios

### CODE REVIEW

**Comment by tw15egan** [comment]
@laurenmrice wasn't sure what we wanted to do with the `With Overflow Menu` variant in the `md` size. Should we remove the padding and have it align with the `xs` and `sm` variants? 

As is:
Screen Shot 2021-04-19 at 3 19 45 PM

**Review by dakahn — APPROVED** [review]
seems cool to me pending design 👍🏽 🏄🏽

**Review by joshblack — APPROVED** [review]

**Comment by laurenmrice** [comment]
@tw15egan is the overflow menu getting a 24px height for both the `xs` and `sm` row sizes? (Asking because I can't view it with different sizes right now in the data table stories). We originally speced the `sm` to have a 32px height for the overflow, but I am not sure if there was a reason why we made it smaller since then? 

For the `md` row sizes we can use the 32px  height for the overflow since it would still fit in the row size.

This is how we had speced it out originally. 
Artboard

**Comment by tw15egan** [comment]
@laurenmrice just pushed some updates for OverflowMenu 👍🏻

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- Overflow looks good in all sizes ! 🎉

- For the size dropdown we will need to change the Large option to read as `Large (lg) - default` like we are doing for our other components so far. The "(lg)" just needs to come after the word "Large".

Screen Shot 2021-04-22 at 12 54 59 PM

**Comment by tw15egan** [comment]
@laurenmrice fixed 👍🏻

**Review by laurenmrice — APPROVED** [review]
Looks good to me ! 🎉

**Pull request merged**
