### PR TITLE
feat(UI Icon): add Russian Ruble icon

### LINKED ISSUE #7848: Create Russian Ruble icon
### Summary

I wanted to use Carbon icons, but found out, there is no Russian Ruble icon, which I need.

I would like to have that icon, therefore I have created one and would like to contribute.

### Justification

Improve the internationalization.

---

It would be nice if someone could assign me to this.

### PR DESCRIPTION
**Pull request by AndrisJefimovs**
Closes #7848 

Submitting a new UI icon for the Russian currency, the Russian Ruble.

#### Changelog

**New**

+ 32/currency--ruble.svg

**Changed**

+ README.md
+ .all-constributorsrc

#### Testing / Reviewing

Requirements (from [carbondesignsystem.com](https://www.carbondesignsystem.com/contributing/contribute-icons#production-ready)):

- [x] Icon should be at whole pixels
- [x] Aligned to the pixel grid 
- [x] All strokes must be expanded and at full pixel values
- [x] All possible shapes and paths should be combined

---

It is my first contribution. Please mention anything I missed, or did wrong!

### CODE REVIEW

**Comment by conradennis** [comment]
just looked over the svg. Proportions look a little off compared to the other currency icons. Here's the redraw I did (Mike approved). 

I can include this in my next icon batch PR which I should be able to get to before end of February. @AndrisJefimovs If you need it sooner I can share the SVG with you in the meantime. 

Screen Shot 2021-02-19 at 2 33 10 PM

Screen Shot 2021-02-19 at 2 34 08 PM

**Comment by AndrisJefimovs** [comment]
There is no need to rush, I have enough time. :)

Should I close this now?

**Comment by conradennis** [comment]
@AndrisJefimovs yup you can close. I made an issue in UI icon repo here in case you want the SVG: https://github.ibm.com/brand/ui-icons/issues/76

**Comment by conradennis** [comment]
@AndrisJefimovs I just submitted the PR including the ruble icon: https://github.com/carbon-design-system/carbon/pull/7985

**Pull request closed without merging**
