### PR TITLE
fix(OverflowMenu): call closeMenu method only when menu is open

### LINKED ISSUE #5079: Create over 300 Tooltip or OverflowMenu, page is not responsive
After I created a DataTable with some cell using Tooltip(in canbon9) and OverflowMenu, after the total widget count is over 300(e.g. 30 rows with 10 cols ), the page is not very responsive, each time I click, I need to wait about 2-3 seconds.

The root cause is that Tooltip and OverflowMenu are using `ClickListener` which registers the click event for each widget.

I suggest that only use ClickListener after the menu or tooltip is opened or use react's own event handling to avoid this issue.

Related code => 

OverflowMenu
https://github.com/carbon-design-system/carbon/blob/5513126a1f63a4acd757c3a82a0a6dd98ea386a3/packages/react/src/components/OverflowMenu/OverflowMenu.js#L548

Tooltip
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Tooltip/Tooltip.js#L433

ClickListener
https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/internal/ClickListener.js#L31

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5079

This PR adds an open state check to the `handleClickOutside` method so that the click listener correctly fires only when the menu is open.

Prior to this change, the click handler would fire with every click outside of the component regardless of the component state, meaning that for every overflow menu on a page, each click would trigger a `handleClickOutside` function call even if the menus were closed. As shown in the demo provided in the original ticket, this led to the action of opening a single overflow menu taking over 4 seconds on a page containing 500 menu instances.

image

With this check for menu state, the time taken for a single menu to open on the same demo is reduced to 19 milliseconds.

Screen Shot 2020-02-12 at 6 03 05 PM

#### Changelog

**Changed**

- overflow menu `handleClickOutside` method

#### Testing / Reviewing

To test this locally, you can recreate the demo by adding this as a story in storybook and comparing it to the demo in the original ticket:

```js
const Container = () => (
  <div>
    <OverflowMenu>
      <OverflowMenuItem itemText="item 1" />
      <OverflowMenuItem itemText="item 2" />
    </OverflowMenu>
  </div>
);

const containers = [];
for (let i = 0; i < 500; i++) {
  containers.push(<Container />);
}

return <div>{containers}</div>;
```

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
Simple fix that greatly improves the performance 🎉 - Thanks @emyarod!

**Review by aledavila — APPROVED** [review]

**Comment by joshblack** [comment]
cc @vpicone

**Review by vpicone — APPROVED** [review]
Awesome work @emyarod thanks for tackling this. A big improvement!

**Comment by asudoh** [comment]
Got a green light from @emyarod to make this "ready to merge" state - Thanks @emyarod!

**Comment by tw15egan** [comment]
🎉

**Pull request merged**
