### PR TITLE
fix(button): fix icon-only ghost button svg fill

### LINKED ISSUE #5720: [button] ghost icon button color is wrong
Ref this original pr: https://github.com/carbon-design-system/carbon/pull/5313

I noticed that our current react for the ghost icon only button is blue. We specifically want this to be `icon-01`. I think there may have been some kind of regression 

Screen Shot 2020-03-26 at 1 33 48 PM

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5720

Fixes icon-only Ghost button SVG fill color

#### Changelog

**Changed**

- Ensures icon-only ghost button has an icon fill of `icon-01`

#### Testing / Reviewing

Check out icon-only ghost button and make sure the icon is not blue

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
When the button receives focus, the icon should not turn blue. Otherwise it looks great in all themes !
Screen Shot 2020-03-26 at 3 38 16 PM

**Review by dakahn — APPROVED** [review]

**Comment by tw15egan** [comment]
@laurenmrice updated 👍

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Focus looks good now.

Disabled was correct before but now when hovering over it, the icon turns back to `icon-01`
Mar-27-2020 12-14-08

**Comment by tw15egan** [comment]
Whoops! Should be fixed now

**Review by laurenmrice — APPROVED** [review]
thank you ! looks good 👍🏻

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by joshblack — APPROVED** [review]

**Pull request merged**
