### PR TITLE
feat(type): add Plex Sans Condensed

### LINKED ISSUE #5615: [Carbon Type Package]: Add IBM Plex Condensed
Carbon Charts uses the condensed in X and Y-axis and axis labels
https://carbon-design-system.github.io/carbon-charts/

Teams like IoT are using Carbon Charts and getting Helvetica in place of Plex Condensed in all their Bar Chart versions
https://carbon-addons-iot-react.com/?path=/story/watson-iot-experimental-barchartcard--simple-bar

sample:
Screen Shot 2020-03-12 at 6 03 31 PM

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5615

Adds in Plex Sans Condensed font-face declarations. 

#### Changelog

**New**

- Plex Sans Condensed styles will now render instead of Helvetica

**Changed**

- Updated type examples to reflect this addition

#### Testing / Reviewing

Go to `type/examples` folder, build, then run the example. Ensure that Condensed styles are being shown in all browsers.

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
The changes seem great 🎉 Do we need to add this to the type font family map too or is that not needed?

**Comment by tw15egan** [comment]
@joshblack seems like it's been in there, we just weren't declaring the `font-face`

https://github.com/carbon-design-system/carbon/blob/d31eadd33d25ada72adf7cc0d247c4e8d7f1def9/packages/type/scss/_font-family.scss#L19

Or did you mean somewhere else? Not too familiar with the `type` package

**Comment by joshblack** [comment]
Oh perfect! Sounds great

**Review by joshblack — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
image

looks good to me

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! 🎉

**Pull request merged**
