### PR TITLE
feat(definition-tooltip): WCAG 2.1 compliance

### LINKED ISSUE #3099: Definition Tooltip: AVT 1 violation
## Environment

> Operating system

Mac OS X

> Browser

Safari

> Automated testing tool and ruleset

AAT 2.4.1: https://aat.w3ibm.mybluemix.net/token/c1e59337-69c6-45fb-9ff0-6379259a1405/67022795-93d7-4142-b7e3-712ea042711b/archives/2019FebDeploy//doc/w3/help/en-US/idhi_accessibility_check_g1202.html

> Assistive technology used to verify

VoiceOver

## Detailed description

Button's can't use `aria-label` as it overwrites the contents of the button so screen reader user is not getting the text that displays in the trigger

> What version of the Carbon Design System are you using?

10.3.1

> What did you expect to happen?

Screen reader users would be able to access all content.

> What happened instead?

Screen reader users only got the tooltip content

> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Use a screen reader on Carbon's demo of the definition tooltip

## Additional information
You need to use the `aria-describedby` attribute and point to a different element that contains the content of the tooltip separately from the trigger
Screen Shot 2019-06-18 at 12 45 25 PM

### PR DESCRIPTION
**Pull request by elizabethsjudd**
Closes #3099 

Update Definition tooltip to be compliant with WCAG 2.1; Content should be within a tooltip element instead of an `aria-label`. The use of the aria-label caused the screen readers to not announce the content within the button itself.  Also verified the `top` placement works and that the trigger is not required to be a button.

#### Changelog

**Changed**

- Contents of the tooltip are in a separate `role="tooltip"` element
- Followed same styling patterns/updates as #3115 

#### Testing / Reviewing

Test Carbon supported browsers and that legacy demos still work as expected.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
looks good so far! just one thing: the changed markup is now affecting the caret positioning when the tooltip is placed above the trigger element

image

**Comment by elizabethsjudd** [comment]
@emyarod  Good catch! I noticed it when it was below and added a patch but didn't see when it opens above. I'll double check why I didn't see that locally and make a fix.

**Comment by jnm2377** [comment]
Thanks for this contribution! Looks good once that caret bug is fixed. 👍

**Comment by elizabethsjudd** [comment]
@emyarod is it a known thing that the full render and the dev site preview are different?  There are side-effect styles bleeding in to one of them (i couldn't find where it is) but if you look at the two screen shots I've attached there are 2 obvious differences between them:
1. the caret location on the "top" demos
2. the line-height/spacing between each variant

Screen Shot 2019-06-24 at 11 39 43 AM
Screen Shot 2019-06-24 at 11 39 48 AM

I found a solution that corrected the caret position (as well as a bug I found with the `end` alignment) in both views but it did make them look even more different because of whatever is bleeding in to them.

---

As of today when I run `yarn ci-check` I'm getting the following error.

```
➜  carbon git:(feature/definition-tooltip) yarn ci-check
yarn run v1.16.0
$ carbon-cli ci-check
/Users/liz/Projects/ibm/elizabethsjudd/carbon/packages/cli/node_modules/jsonfile/index.js:67
      throw err
      ^

Error: /Users/liz/Projects/ibm/elizabethsjudd/carbon/packages/.DS_Store/package.json: ENOTDIR: not a directory, open '/Users/liz/Projects/ibm/elizabethsjudd/carbon/packages/.DS_Store/package.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.readFileSync (/Users/liz/Projects/ibm/elizabethsjudd/carbon/packages/cli/node_modules/jsonfile/index.js:61:22)
    at fs.readdirSync.map.pkg (/Users/liz/Projects/ibm/elizabethsjudd/carbon/packages/cli/src/workspace.js:20:21)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/Users/liz/Projects/ibm/elizabethsjudd/carbon/packages/cli/src/workspace.js:15:51)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by asudoh** [comment]
@elizabethsjudd Not sure how you created a clone of Carbon repo, but would you want to try deleting `.DS_store` stuffs?

**Comment by emyarod** [comment]
@elizabethsjudd I have seen discrepancies between the dev preview and full renders in the past and just addressed them as I encountered them. I can look more into the caret positioning issue you're facing

**Comment by elizabethsjudd** [comment]
@emyarod Thanks, I wasn't sure what the policy was with that. I did notice that the difference seemed to come down to line-height and the way the `bx--tooltip--definition` divs were displayed.  

* For line-height, calculated value was 14px (full preview) and 16px (site demo).  
* For the div display, width only expanded to the width of the trigger (full preview) vs width was 100% of the containing div (site demo)

Personally, I feel like these two things are valid deviations we could expect to find in applications and they shouldn't affect the caret and tooltip position.  That is why I ended up with my solution of setting a specific display on the root element of the component to be `inline-flex`. This approach kind of just reset the container for the tooltip and the caret and tooltip positioned seemed to be consistent to the trigger. The `inline-flex` also allows us to use a definition tooltip within a paragraph (which is in the usage documentation).

**Review by joshblack — COMMENTED** [review]
> Update Definition tooltip to be compliant with WCAG 2.1; Content should be within a tooltip element instead of an aria-label.

Could you clarify which rule you're referring to?

**Comment by elizabethsjudd** [comment]
@joshblack This is an AVT 3 rule that is failing. When a VO user hits a button with an `aria-label` it does not read the actual content of the button but only reads the content of the tooltip.  You need to test it with a screen reader (not just run DAP)

**Comment by joshblack** [comment]
Cool! Just want to make sure we're tracking specific rule IDs so that they don't get missed in future work 😄

**Review by dakahn — CHANGES_REQUESTED** [review]
This is awesome! Thanks so much for contributing. Tested with Voice Over we get this:

"Definition tooltip (start aligned), button. Brief description of the dotted, underlined word above., you are currently on a button inside web content..."

So essentially, _"(button content), (control type). (tooltip text)"_ Great stuff 👍🏽

It seems like the last six examples in our demonstration of Definition Tooltip still _only_ read their tooltip text though (like before your fix). 
Screen Shot 2019-06-25 at 1 04 31 PM

**Comment by elizabethsjudd** [comment]
@dakahn you are correct that the last six only read  the tooltip text.  I left those in there for the designers to verify that I didn't "break" the old HTML with my updated styles but those will be removed from the demo before merging so only the new, a11y compliant HTML will be in the demo.

Once I get the okay, (not sure from who) I'll remove them. (FYI, my other PRs are also set up this way so that way we are thoroughly testing the original code as well and I plan on doing a clean up before the merge).

**Review by emyarod — COMMENTED** [review]
it looks like the caret spacing issue was resolved in Chrome and Firefox but it still remains on Safari:

image

**Comment by elizabethsjudd** [comment]
@emyarod thanks for catching that. It was actually just when applied to buttons in Safari because of some of the default browser styles.  I've added a fix!

**Review by emyarod — COMMENTED** [review]
awesome, issue looks resolved on Safari now. just a heads up: you'll need to update the sassdoc (run `yarn build` in the repository root) to pass CI

**Review by dakahn — APPROVED** [review]

**Review by emyarod — DISMISSED** [review]
@elizabethsjudd would you mind resolving the merge conflict with the icon tooltip rules?

**Comment by elizabethsjudd** [comment]
Who else needs to review this to get approval for merging?  I'd like to have this as part of v10.4

**Comment by joshblack** [comment]
@elizabethsjudd it follows our normal review process with 2 devs signing off 👍 I totally get wanting it in for 10.4 but as we approach our endgame next week, alongside folks being out this week, we do have commitments from active projects that will take priority. Will definitely try our best here!

**Comment by dakahn** [comment]
@elizabethsjudd Already gave this the greenlight, but had a question

What part of this is specifically getting us in line with the new WCAG 2.1 requirements? 
Seems like a solid improvement for screen reader usability but I can't figure out what 2.1 rule these changes are in reference to.

**Comment by elizabethsjudd** [comment]
@dakahn I was focused on the AVT 1 violation of not having a visible label (i know the label previously implemented had it visible through the content CSS property but it wasn't detected that way).  Once I started digging in though I found that this was failing on a much bigger level of AVT 3 (screen reader testing) because the user wasn't getting the content of the trigger at all so it was better to just tackle the whole thing since the solution for both was the same.

**Comment by joshblack** [comment]
Could we update the PR to address existing violations and defer the WCAG 2.1-specific updates around `aria-label` -> `assistive-text` in a separate PR? Or are these updates related to the issue you're describing?

**Comment by elizabethsjudd** [comment]
@josh the fix in this PR addresses both AVT 1 and AVT 3 violations (it's 1 fix for 2 violations)

**Comment by joshblack** [comment]
@elizabethsjudd cool! So all changes are because we have to change that aspect of the tooltip as it relates to a violation? It feels like we're also including some other stuff with respect to flexibility in the markup, right?

**Comment by elizabethsjudd** [comment]
@joshblack I didn't actually change the code to add in the flexibility but instead added demos to show the flexibility of the the trigger based off the usage docs on Carbon's website.

**Comment by joshblack** [comment]
Cool! Sorry I misunderstood 😄 Having a hard time understanding the changes in between stuff going on today and I apologize for any misconceptions here 👍

**Comment by asudoh** [comment]
@emyarod Would you be able to re-review this...? Thanks!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by joshblack — APPROVED** [review]

**Pull request merged**
