### PR TITLE
Create storybook theme addon standalone

### PR DESCRIPTION
**Pull request by lee-chase**
Breaks carbon theme addon out to a stand-alone package that supports both React and Vue. It could also support other frameworks.

#### Changelog

A       .yarn/offline-mirror/@babel-core-7.11.6.tgz
A       .yarn/offline-mirror/@babel-generator-7.11.6.tgz
A       .yarn/offline-mirror/@babel-helper-builder-react-jsx-experimental-7.11.5.tgz
A       .yarn/offline-mirror/@babel-helper-module-transforms-7.11.0.tgz
A       .yarn/offline-mirror/@babel-helper-split-export-declaration-7.11.0.tgz
A       .yarn/offline-mirror/@babel-parser-7.11.5.tgz
A       .yarn/offline-mirror/@babel-plugin-transform-react-display-name-7.10.4.tgz
A       .yarn/offline-mirror/@babel-plugin-transform-react-jsx-development-7.11.5.tgz
A       .yarn/offline-mirror/@babel-plugin-transform-react-jsx-self-7.10.4.tgz
A       .yarn/offline-mirror/@babel-plugin-transform-react-jsx-source-7.10.5.tgz
A       .yarn/offline-mirror/@babel-plugin-transform-react-pure-annotations-7.10.4.tgz
A       .yarn/offline-mirror/@babel-preset-react-7.10.4.tgz
A       .yarn/offline-mirror/@babel-traverse-7.11.5.tgz
A       .yarn/offline-mirror/@babel-types-7.11.5.tgz
M       packages/components/docs/sass.md
M       packages/react/.storybook/addon-carbon-theme/components/Panel.js
M       packages/react/.storybook/addon-carbon-theme/register.js
M       packages/react/.storybook/addon-carbon-theme/shared.js
M       packages/react/.storybook/main.js
M       packages/react/.storybook/preview.js
M       packages/react/.storybook/webpack.config.js
M       packages/react/package.json
A       packages/storybook-addon-carbon-theme/.babelrc
A       packages/storybook-addon-carbon-theme/README.md
A       packages/storybook-addon-carbon-theme/package.json
A       packages/storybook-addon-carbon-theme/react.js
A       packages/storybook-addon-carbon-theme/register.js
A       packages/storybook-addon-carbon-theme/src/components/Panel.js
A       packages/storybook-addon-carbon-theme/src/react.js
A       packages/storybook-addon-carbon-theme/src/register.js
A       packages/storybook-addon-carbon-theme/src/shared.js
A       packages/storybook-addon-carbon-theme/src/vue.js
A       packages/storybook-addon-carbon-theme/vue.js
M       yarn.lock

#### Testing / Reviewing

- Tested in local React component libraries
- Tested in Vue Branch https://github.com/lee-chase/carbon-components-vue/tree/attemptToUseThemeAddon

### CODE REVIEW

**Comment by tw15egan** [comment]
@lee-chase sorry for the delay, just getting around to taking a look at this. This is a great idea and we definitely appreciate the PR to do this. I see you've already got the package on NPM so just let me know what else is needed on our end

cc @joshblack

**Review by tw15egan — APPROVED** [review]
Everything looks good on my end 👍 ✅

**Comment by joshblack** [comment]
@tw15egan curious what you think about this, would be cool if we had `storybook-addon-carbon` and it included any of the panels we thought would be useful externally.

Couple notes for this PR to get in:

- Our `README.md` files are auto-generated and follow a specific template, just wanted to raise that so it wouldn't get replaced from `carbon-bot` when files are synced
  - Basically the tl;dr of this template is that only what is under `## Usage` sections can be custom for a package, the rest is auto-generated
- The `package.json` file itself seems to be using `npm` commands instead of `yarn`
- We try to use `rollup` for bundling instead of babel where we can, and use the `es` and `lib` convention for ESM and CommonJS modules
- There are some comments that we'd want to clean-up, either eslint rules or just imports from copying over code

Couple of questions:

- Do we have to use a decorator for setting the attribute on the document, or could we just have that logic live in the panel itself? (I just wasn't sure)

**Comment by tw15egan** [comment]
@joshblack I agree, it would be nice to get a package that included all of our addons, but I think this is a great start. Not sure we use many of the other panels besides knobs and action? Perhaps when we get the RTL functionality added in it may make sense to bundle all these together. 

I'm also curious, should we enable this when developing locally? Seems like we only have the theme switcher active on deploy previews

**Comment by lee-chase** [comment]
@tw15egan @joshblack happy to re-publish as @carbon/storybook-addon although adding more panels to the package does put a bigger hurdle in the way of anyone wishing to contribute angular, svelte etc. The current package supports React and Vue

**Comment by andreancardona** [comment]
@lee-chase do you mind taking a quick look at the merge conflicts and resolving them please - thank you :)

**Comment by lee-chase** [comment]
@andreancardona resolving conflicts every time someone else merges a build is going to get dull very quickly. I do not have permission to click on the 'Resolve conflicts' button.

**Review by andreancardona — APPROVED** [review]

**Pull request merged**
