### PR TITLE
chore(devenv): introduce theme editor

### PR DESCRIPTION
**Pull request by asudoh**
**NOTE**: This PR has _no_ intention of making theming dev env vanilla-only. Integrating theme switcher to Storybook is underway.

If you click on the icon at the top right, a side bar comes up where you can change the theme (the capability the earlier PR introduced) as well as edit the theme. If you go to the bottom in the side bar, you’ll see a button where the theme content is copied to clipboard.

#### Changelog

**New**

- Theme editor sidebar, ported from themes.carbondesignsystem.com.

**Changed**

- Moved the theme switcher to the theme editor sidebar (above).

#### Testing / Reviewing

Testing should make sure our dev env is not broken.

### CODE REVIEW

**Comment by joshblack** [comment]
These PRs into the vanilla dev environment really worry me, we shouldn't be adding more code into an area that we are moving away from. Can we instead invest time into an environment that is future-proof and preferably shareable between storybook variants? (like for Angular/Vue)

**Comment by asudoh** [comment]
As I noted in the issue description, this PR is _not_ for picking a dev env for theming effort.

**Comment by asudoh** [comment]
Withdrawing as we determined that this feature is more for designer than for dev.

**Comment by joshblack** [comment]
@asudoh all the changes are in the component demo folder which is what prompted that comment. The testing comments also states to check that the dev env isn’t broken. As stated earlier, it seems like it’d be preferred if a solution for this problem was crafted such that it could support our various storybook environments.

**Pull request closed without merging**
