### PR TITLE
docs(Combobox): add docs for shouldFilterItem prop

### PR DESCRIPTION
**Pull request by tw15egan**
Based on the discussion we had in design crit last week, this adds an example for the `shouldFilterItem` prop to help discoverability. I've also cleaned up some of the code syntax highlighting. 

#### Changelog

**New**

- Under `Combobox / Docs` in the storybook, a new `shouldFilterItem` block shows how a user can implement their own filtering logic. 

**Changed**

- Fixed syntax highlighting

#### Testing / Reviewing

Go to `Combobox / Docs` and ensure the instructions are clear and make sense, and that the code block renders correctly and filters the items properly.

### CODE REVIEW

**Comment by guidari** [comment]
The information looks good to me! @tw15egan 

But I think there is a bug. When I open the ComboBox and click outside of it, the pages goes blank.

I tested in Chorme, FireFox and Safari

Other than that looks good!

Screenshot 2023-06-01 at 14 53 58

**Comment by tw15egan** [comment]
@guidari good catch, added some null checks that should prevent that!

**Review by guidari — APPROVED** [review]
LGTM!

**Review by alisonjoseph — APPROVED** [review]

**Comment by thyhmdo** [comment]
I have a few questions. When there are two options start with the same letter (see the example below), does it: 
- Filter out the options with letter B?
- Highlight the first option with letter B? 

image

**Comment by tw15egan** [comment]
Yeah exactly

**Review by thyhmdo — APPROVED** [review]
Looks great!

**Pull request merged**
