### PR TITLE
feat(data-table): add mobile-optimized variant

### LINKED ISSUE #2938: [Table] Mobile version
### Summary

What might a table look like on mobile (small breakpoint) screens? Currently, it's as-is but with the expectation the user will scroll. But that requires a lot of work for the user to complete tasks involving comparing columns. Instead, my proposal transposes columns per row to be more scannable (and scrolling vertically only):

image

I've implemented it using angular, but I understand we'd have to splice the css and some layout from there into a separate PR to the components package. This is just a preview for now:
https://github.com/werdnanoslen/carbon-components-angular/tree/feat(table)-add-mobile-variant

### Justification

Improved usability and accessibility for mobile users.

### Desired UX and success metrics

- A user can complete tasks involving multiple columns more quickly.
- A user can access information from columns past the first few more quickly.

### Specific timeline issues / requests

No rush, just wanted to discuss this.

### Available extra resources

I made it in Angular, and I maybe could learn enough React to do that too.

### PR DESCRIPTION
**Pull request by werdnanoslen**
Closes #2938, #2992, #3006

What might a table look like on mobile (small breakpoint) screens? Currently, it's as-is but with the expectation the user will scroll. But that requires a lot of work for the user to complete tasks involving comparing columns. Instead, my proposal transposes columns per row to be more scannable (and scrolling vertically only).

image

FYI this is a different implementation of my [previous PR](https://github.com/carbon-design-system/carbon/pull/2992) for this feature.

#### Changelog

**New**

- Vanilla files for narrow table variant
- Handlebars helper

#### Testing / Reviewing

Go to the last example on the Data Table component page, titled "Narrow"

### CODE REVIEW

**Comment by joshblack** [comment]
Wanted to bring in @aagonzales to weigh in on the design aspect of things!

**Comment by aagonzales** [comment]
We've said its an ok pattern as long as its not the default behavior. The table that Virginia and Tracey have been working included a better horizontal responsive behavior.

**Comment by joshblack** [comment]
@aagonzales would that proposed mobile style be the preference moving forward then?

**Comment by joshblack** [comment]
bump @aagonzales if you have a sec!

**Comment by aagonzales** [comment]
The default data table responsive behavior will be the one Virginia's team is contributing. This one will be a secondary option. At some point we'll need to write some guidelines about when it would be beneficial to use this one instead.

**Comment by joshblack** [comment]
Hi there! 👋 We're going through PRs that have been waiting around for a bit and closing out the ones that might be lingering.

Just wanted to say thanks so much for your time in making this contribution, we really, really appreciate it 🙏 If you feel like closing this out is in error, feel free to re-open!

**Pull request closed without merging**
