### PR TITLE
fix(data-table): sortable, boolean column, and overflow menu row fixes

### LINKED ISSUE #6261: fix vertical alignment of table column headers when table size is tall
## Table: header text vertical alignment issues when size changed.

In a table, especially in `tall` mode, the column header text isn't vertically centered. 

## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

In a table, especially in `tall` mode, the column header text isn't vertically centered. 
And the alignment is different for columns that are sorted vs. ones that aren't.

row-height

This is on 10.13.0.

The problem can be seen on https://react.carbondesignsystem.com/?path=/story/datatable--default and https://react.carbondesignsystem.com/?path=/story/datatable--with-sorting, after using the knobs to set row-height to `tall`.

### LINKED ISSUE #6262: [data table] column header and row size heights are inconsistent
Related:
https://github.com/carbon-design-system/carbon/pull/6197
#6261 

-------------------------------------------------------------------------------------------------

Data table column headers and row size heights are inconsistent. This has to also do with the overflow menu component affecting the size of the rows.

-------------------------------------------------------------------------------------------------

Spec for all data table height sizes with padding specified:

datable

-------------------------------------------------------------------------------------------------

Spec for how to treat overflow menu inside smaller row sizes:

compact

short

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6261
Closes #6262

This PR addresses data table issues specific to the boolean column, overflow menu, and sortable variants.

#### Testing / Reviewing

The row heights for all variants should be consistent with the headers, and the alignment and positioning of table elements should be consistent with the spec

### CODE REVIEW

**Comment by tw15egan** [comment]
Small issue with some sortable / some not Data Table (Tall variant) in Safari.

All other variants look good 👍 

Screen Shot 2020-06-15 at 1 59 20 PM

**Review by laurenmrice — APPROVED** [review]
Everything looks great to me ! thank you 🙌🏻

**Review by joshblack — APPROVED** [review]
Looks great after TJ's feedback 👀

**Comment by emyarod** [comment]
just a heads up, the Safari issue is an unresolved flexbox issue at the browser level

compare this demo in different browsers: https://codesandbox.io/s/funny-golick-u5zfe

a workaround is to add a wrapper element around the table header content, but then we will need to adjust table styles across the board accordingly. if that's fine I can proceed with that plan

related links

https://codepen.io/scheinercc/pen/ZEGwpKb
https://bugs.webkit.org/show_bug.cgi?id=169700
https://bugs.webkit.org/show_bug.cgi?id=177503

**Review by tw15egan — APPROVED** [review]
@emyarod I'm fine with it as is if it's a browser level issue, and it's only appearing on a very specific scenario (tall table with a mix of sortable headers, only on safari).


Thanks for the links!

**Comment by emyarod** [comment]
I have the fix prepared if you want to take a look, but if we don't want to go forward with it I can just revert the latest commits

**Comment by tw15egan** [comment]
@emyarod ah gotcha, let me check it out

**Comment by tw15egan** [comment]
Nice! Looks like its rendering properly across all browsers. Didn't realize adding a span inside the button would get around the flex inconsistencies in buttons.

**Review by aledavila — APPROVED** [review]

**Pull request merged**
