### PR TITLE
fix(number-input): remove default value for label

### LINKED ISSUE #5341: [Number Input]: label default prop causes label to always render then ariaLabel isn't applied
## What package(s) are you using?

- [ ] `carbon-components`
- [X] `carbon-components-react`

## Detailed description

Since the `label` has a default prop of an empty string, the `label` element is always rendered causing DAP violations if the user only specifies `ariaLabel` (which should replace a label if they don't want that) and the `ariaLabel` doesn't get applied. 

If you specify an `ariaLabel` and not a label, these are the violations that causes: 
Screen Shot 2020-02-13 at 12 12 23 PM

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #5341 

This removes the default prop for `label` so the label element isn't always rendered, for example if a user wants to label the Number Input with `ariaLabel` instead. 

#### Changelog

**Removed**

- `label` default prop

#### Testing / Reviewing

Check that if `label` is empty, no label element is rendered

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Looks fine from the diff, what are the implications for removing it? Does any part of the rendered UI change for folks who might be using the default prop?

**Comment by asudoh** [comment]
@abbeyhrt Would you be able to do some quick testing if setting empty label has the same visual effect as `hideLabel`? Thanks!

**Comment by abbeyhrt** [comment]
@joshblack @asudoh in the storybook, it seems to move a 7 pixels down if there is no label present vs `hideLabel` (this is true before this PR though). There's code that seems to want the label element to not be rendered if there is no label defined but the default prop makes that never happen unless someone deliberately sets `label` to null. We maybe always wanted this to happen but it's been broken?
```
    const labelText = label ? (
      <label htmlFor={id} className={labelClasses}>
        {label}
      </label>
    ) : null;
```
```
     'aria-label': label ? null : ariaLabel,
```

**Review by designertyler — APPROVED** [review]

**Comment by asudoh** [comment]
@abbeyhrt To do that, I think we need to ensure the styling of `hideLabel` is applied to `<NumberInput>` with empty value. Signing off given @designertyler created an issue to track that.

**Review by asudoh — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
