### PR TITLE
fix(checkbox-x): make background transparent

### PR DESCRIPTION
**Pull request by SimonFinney**
Experimental checkboxes currently use `$ui-02` as a background color - The implications of this are that they look visually off on different container background colors.

This PR proposes to make the background color transparent to align with that of the parent container.

#### Changelog

**Changed**

- Make experimental checkbox background color transparent

### CODE REVIEW

**Comment by joshblack** [comment]
cc @IBM/carbon-designers to review when you get the chance 👍

**Review by joshblack — APPROVED** [review]
This change seems fine to me 👍 Could we leave a comment explaining how `transparent` works in the component? Would help a lot when re-visiting this file

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @SimonFinney!

**Review by aagonzales — APPROVED** [review]
Sounds good to me!

**Pull request merged**
