### PR TITLE
fix(checkbox): use box-shadow for appearance of mult rounded borders to improve a11y for dark themes

### LINKED ISSUE #5984: Checkbox focus outline color is inaccessible for g90 and g100 themes
## Detailed description

The `Checkbox` uses the `$focus` color token to apply an "outline" color (technically, a border color) on `:focus`: https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/checkbox/_checkbox.scss#L157

However, for `g90` and `g100` themes, the `$focus` token's color is **white**: https://carbon-elements.netlify.app/themes/examples/preview/

So you get the following the result when trying to focus on a `Checkbox` (**white** outline color against a **white** checkbox background color):

Screen Shot 2020-04-29 at 5 14 21 PM

> What version of the Carbon Design System are you using?

`carbon-components-react@7.10.0` (this is observable in the `7.11.3` deploy as well, however)

## Steps to reproduce the issue

1. Go here: https://carbon-components-react.netlify.app/?path=/story/checkbox--checked
2. Apply g90 or g100 theme in the "Carbon Theme" knobs tab.
3. Focus on a checkbox & observe the white focus outline color next to the white checkbox.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #5984 

The `$focus` color token used for the `Checkbox` focus outline is white for g90 and g100 themes, which is not accessible (see #5984)

~This PR proposes using the `$interactive-04` color token instead, which will be blue40 for g90 and g100 themes: https://carbon-elements.netlify.app/themes/examples/preview/~ See https://github.com/carbon-design-system/carbon/pull/5985#pullrequestreview-406157405

#### Changelog

**Changed**

- ~use `$interactive-04` instead of `$focus` for the Checkbox's `:focus` outline/border color~ use `box-shadow` to create appearance of multiple borders with rounded corners, per https://github.com/carbon-design-system/carbon/pull/5985#pullrequestreview-406157405

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me pending visual review

**Comment by aagonzales** [comment]
My concern is `interactive-04` isn't really used for that purpose. I'm wondering if we should introduce a new focus-alt token (we already have `$inverse-focus-ui` but that wont work here). I'm curious if this is a problem on any other controls as well. 

I also wonder if we could just style the focus more like what the buttons has with the 1px internal border to help distinguish the focus from the box. 

image

**Comment by jendowns** [comment]
Thank you @aagonzales I'm happy to go with either option, though I was wondering about the accessibility of the second one? 

@carbon-design-system/ibma would that second option in https://github.com/carbon-design-system/carbon/pull/5985#issuecomment-621998357, with an offset white border, work?

**Comment by aagonzales** [comment]
It is similar to what we do with button so that's my only real point for it being accessible. I'm not really sure what the visual requirements for focus are. I will look into it.
image

From the looks of it this will probably be an issue with Radio button as well if thickening the border isn't enough for focus.

**Comment by aagonzales** [comment]
This is what I found in the guidelines. I kind of sounds like as long as its thick enough to be noticeable it is ok. I'm wondering if the as-is is fine then? 

https://www.w3.org/WAI/WCAG21/Techniques/general/G195

image

The options:
image

**Comment by jeanservaas** [comment]
guys I'm punting this one back to @aagonzales because she and Lauren know what's going on with it.

**Comment by aagonzales** [comment]
Let's go with the below option. That way the token gets to stay `$focus` and it should meet the accessibility requirements. Its 1px of padding then 2px for the border

image

**Review by aagonzales — CHANGES_REQUESTED** [review]
Let's go with the below option. That way the token gets to stay `$focus` and it should meet the accessibility requirements. Its 1px of padding then 2px for the border

image

**Comment by jendowns** [comment]
Thank you @aagonzales -- I updated the PR with changes you suggested above 👍 

Also @emyarod & @joshblack -- I've changed the direction here to match feedback from https://github.com/carbon-design-system/carbon/pull/5985#pullrequestreview-406157405. Could you take another look when you get a chance & let me know if you are OK with these changes? Thank you!

**Review by aagonzales — APPROVED** [review]
Yay! Thanks for updating that is looks good! Just one thing though I wasn't able to click on the checkbox anymore, I'm not sure if that's related to this PR. You used to be able to check and uncheck the demo.

**Comment by jendowns** [comment]
Thanks @aagonzales! Yeah that's strange... I noticed it on the main deployment too: https://carbon-components-react.netlify.app/?path=/story/checkbox--unchecked

I'm only able to check/uncheck these checkboxes using my keyboard in this deployment + the main deployment. 🤔

**Comment by jendowns** [comment]
@aagonzales quick update -- I did a little digging to try to see why that `Checkbox` doesn't work in the React deploy. 

I believe this is related to a change merged in the last day or so, so I opened an issue here: https://github.com/carbon-design-system/carbon/issues/6048
And I believe I have a resolution here: https://github.com/carbon-design-system/carbon/pull/6049

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by dakahn — APPROVED** [review]

**Pull request merged**
