### PR TITLE
fix(sketch): resolve sketch plugin color layer style duplication

### LINKED ISSUE #7734: [icons] color layer style duplication
## Color layer styles

Color layer styles are being duplicated. There are 2 separate sets of the ibm color palette. We only need one copy of the ibm color palette in the color layer styles.

 - [ ] We need to remove the word `fill` from the naming convention and also add spaces inbetween the slashes so it looks as follows: `color / blue / 60`
 - [ ] Remove any duplicate colors that show up

------

 **Example of what currently is happening with the plugin:**
- One set has a naming convention of `color / fill / blue / 60` with spaces inbetween the slashes.
Screen Shot 2021-02-03 at 1 55 05 PM

- The other set has a naming convention of `color/blue/60` without spaces inbetween the slashes.
Screen Shot 2021-02-03 at 1 54 49 PM

### PR DESCRIPTION
**Pull request by emyarod**
Closes #7734

related #5664 #5692 #5744

This PR resolves the color layer style duplication issue. Since we have changed direction in how we expect shared styles to be named, we can undo some changes initially introduced in #5744 to address #5692. We also add some logic to check for the breaking change in #5664 and rename the style layers in place

#### Changelog

**Changed**

- remove style type from style name
- use param objects instead of lists of params
- rename `formatSharedStyleName` to be more descriptive

**Removed**

- Color style "type" references

#### Testing / Reviewing

color style names should no longer contain style type, and any references to color style type should no longer be in the plugin codebase

image

image

[carbon-elements.sketchplugin.zip](https://github.com/carbon-design-system/carbon/files/5946503/carbon-elements.sketchplugin.zip)

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
🎉

**Review by laurenmrice — CHANGES_REQUESTED** [review]
After syncing the plugin with the icon sketch file, the new color palette structure is coming through and is being used by the icons, but the old color structure also remains which causes a duplication of the same colors.

Example:
Screen Shot 2021-02-09 at 3 54 02 PM
Screen Shot 2021-02-09 at 4 04 21 PM

**Comment by emyarod** [comment]
here is the updated plugin which should rename layers in place. the layers should now have the correct name format and no duplicate layers will be generated

[carbon-elements.sketchplugin.zip](https://github.com/carbon-design-system/carbon/files/5968422/carbon-elements.sketchplugin.zip)

**Review by laurenmrice — APPROVED** [review]
I see the correct color styles and they are maintaining overrides when I tested it 🎉

**Pull request merged**
