### PR TITLE
fix(DataTable): address spacing and alignment issues

### LINKED ISSUE #6184: data table height bugs
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

the alignment of the labels in `tall` data table headers are misaligned when sorting is enabled

> Is this issue related to a specific component?

data table

> What did you expect to happen? What happened instead? What would you like to
> see changed?

the table header labels should have the same alignment

## Steps to reproduce the issue

set the value of the DataTable `size` prop to `tall`

## Additional information

originally reported in #6132

> Things get worse when you change the row height (i.e. the `size` property). Here's a screenshot from our app where only the first column is sortable.
> 
> Screen Shot 2020-06-02 at 9 39 53

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6184

This PR addresses several spacing and alignment issues in the data table:

* Expansion column style rules should be consistent in all table variants
* selection (checkbox) cells are now correctly aligned and spaced
* Changing the `size` no longer breaks cell height for expansion cells and selection (checkbox) cells
* radio button selection cells are now aligned and sized according to spec
* some documentation-only changes to correct the appearance of expanded row content

#### Testing / Reviewing

Confirm all table sizes and variants appear correct

### CODE REVIEW

**Review by dakahn — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
`with boolean column` and `with overlfow menu` stories:
The column header needs to be the same size as the rows per size prop change.
Tall: 64px/4rem
Default: 48px/3rem
Short: 32px/2rem
Compact: 24px/1.5rem

Example of what is happening:
Screen Shot 2020-06-08 at 2 35 54 PM


**Expandable row stories:**
-Can you bring the chevron icons down a pixel for stories that have expansion? They seem too high.
-When expanded, there is a line that is flashing next to the expansion rule divider. This is only happening in Firefox but I don’t know if it is possible to get it to stop doing that.


**Radio button story:**
The radio buttons in each row need to come down a pixel. They look too high.

**Comment by laurenmrice** [comment]
Here is a data table spec for all sizes with padding specified:

datable

**Comment by emyarod** [comment]
the row height issues for those 2 examples in particular are because of the sizes of the checkbox and overflow menu trigger button. unless it's alright to scale those down in size, the rows need to expand a bit to allow those elements to fit

**Comment by laurenmrice** [comment]
@emyarod Why do the icons require extra space which would make the rows larger? Is it the states applied to those icons that is causing the issue? 

This is an example of our original spec of the compact and short data table when states are applied. The icons are smaller than the rows.

Compact:
compact
--------------------------------------------------------------------------------------------------
Short:
short

**Comment by emyarod** [comment]
for the overflow menu, it looks like it's taken directly from the OverflowMenu component which has a 32x32 trigger button, but if it's fine to reduce the height then I'll add rules for that

for the checkbox, the component is 24px tall but the padding on every table cell  expands the row height. I do have a solution in mind but it might be a little hacky

but since neither of these are regressions I can tackle them separately (my original ticket was for text alignment) but if you think it should be rolled together I can do that too

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] “with batch actions”, “with overflow menu” and “with selection” stories:
-The first checkbox in the column header is too low for the default size.
checkbox

------------------------------------------------------------------------------------------------------

- [x] “with batch expansion”, “with dynamic content” and “with expansion” stories:
-The chevrons are too high for all sizes. Need to come down 1px.
chevrons

------------------------------------------------------------------------------------------------------

- [x] “with radio button selection” story:
-The radio button is too high in each row for the tall size.
radiobutton

**Review by joshblack — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
Approving because the last changes about icon control alignments have been fixed. We will tackle row and header heights for the overflow icon and checkbox in another pr. 👍🏻

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
