### PR TITLE
fix(code-snippet): allow horizontal scroll, add right padding to multi-line snippet

### PR DESCRIPTION
**Pull request by tw15egan**
Ref https://github.com/carbon-design-system/carbon/issues/5689

QoL changes to the multi-line code snippet 

#### Changelog

**Changed**

- Adds in horizontal scrolling for the multi-line code snippet
- Adds in right-padding for the scrollable code container so that when the code is scrolled all the way, it will not be hidden under the copy button. 

#### Testing / Reviewing

Take a look at the Multi-Line code snippet. Currently set to the same width/text that is being shown in the issue (more lines added to get the show more button to appear)

### CODE REVIEW

**Comment by tw15egan** [comment]
cc @aagonzales , made this to iterate on some possible changes to multi line snippet.

**Review by aagonzales — COMMENTED** [review]
Nice! I think this works really well. Can we just add the linear gradient back to the end. 
`linear-gradient(to right, rgba(244,244,244,0), #f4f4f4)` 
image

**Review by aagonzales — APPROVED** [review]
Ok talked to TJ about the missing gradient that's not actually missing but just a preview deploy problem. This is good to go then from design!

**Review by joshblack — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Review by abbeyhrt — APPROVED** [review]

**Pull request merged**
