### PR TITLE
style(Checkbox): align styles with vertical radio buttons, figma kit

### LINKED ISSUE #14628: [Carbon components]: Radio-button and Checkbox implementations differs from figma
### Package

@carbon/react

### Browser

_No response_

### Package version

1.37

### React version

_No response_

### Description

Reference issue for web-components: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/10911#issuecomment-1714142260

I was trying to implement a form using radio buttons and checkboxes and I saw that they are so different between them and looking at the [Figma file](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=11555-314421&mode=design&t=3iPwUr1InFX1Tcbq-4), I saw some differences between the implementation and the Figma library.

| Element  | Figma | Implementation |
| ------------- | ------------- | ------------- |
| radio margins  | vector image  | top 0.0625rem, right: 0.5rem, bottom: 0.125rem, left: 0.125rem |
| Spacing between label-text and radio  |  8px (0.5rem) | none (uses radio button right margin but it is 8px and it should be 8+2px because of the extra margin  |
| total height | 20px | 21px |
| screen capture |  Captura de pantalla 2023-09-05 a las 19 36 10 | Captura de pantalla 2023-09-05 a las 19 38 02 |

I was trying to implement a form using radio buttons and checkboxes and I saw that they are so different between them and looking at the [Figma file](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=11555-314711&mode=design&t=3iPwUr1InFX1Tcbq-4), I saw some differences between the implementation and the Figma library.

| Element  | Figma | Implementation |
| ------------- | ------------- | ------------- |
| Padding between label-text and checkbox  |  8px (0.5rem) | 6px (0.375rem)  |
| Checkbox margins  | all: 0.125rem  | left: 0.1875rem  the rest: 0.125rem |
| <label> tag  | none (the min-height can be inferred if the checkbox is not `absolute`) | `min-height: 1.5rem; padding-top: 0.1875rem; padding-left: 1.25rem;`  |
| host margin-bottom | none | 0.25rem |
| screen capture | Captura de pantalla 2023-09-05 a las 18 54 52 | Captura de pantalla 2023-09-05 a las 19 02 54 |

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-radiobutton--overview

### Steps to reproduce

Use it

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

IBM Quantum Learning

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/14628

Aligns vertical `RadioButton` and `Checkbox` styles so that they fit the same dimensions. Also brings styles more in line with the Figma kit. The experiment can be found [here](https://stackblitz.com/edit/github-81xkqc-bkl4li?file=src%2FApp.jsx,src%2Findex.scss).

#### Changelog

**Changed**

- Adjusted styles so that `Checkbox` and `RadioButton` have similar bounding boxes / padding

#### Testing / Reviewing

Go to `Checkbox --> Test` and ensure there is no alignment changes when the component switches from `RadioButton` to `Checkbox` and vice versa

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Looks great to me, though the text dances by what seems to be 1px difference vertically


https://github.com/carbon-design-system/carbon/assets/3360588/64322827-29e2-4a17-bc84-f13410c32912

**Comment by tay1orjones** [comment]
Percy also is catching ~28 minor changes to alignment on things like the DataTable. It makes the checkboxes slightly misaligned from the text in the DataTable rows, for instance. Maybe we have some overrides in the component styles (datatable, etc) that we could modify or remove?

**Comment by tw15egan** [comment]
@tay1orjones Hmm, what browser? Not seeing the same with the latest version of Chrome

**Comment by tw15egan** [comment]
@laurenmrice and I compared the storybook to the deploy preview, but if you are seeing another px shift due to the same issue with the test story, I wonder if that is throwing the DataTable off even more? Should only be a 1px shift

**Comment by tw15egan** [comment]
@korgan00 made the adjustments so that they are both 20px on the wrapper, and adjusted the label padding. Not going to adjust the built-in overflow margins with this change, I just want to align their structure.

**Comment by alisonjoseph** [comment]
Chrome and Edge look perfect on mac, I'm seeing the same 1px or so shift in FF and Safari.

**Comment by tw15egan** [comment]
@alisonjoseph @tay1orjones should be the same across all 4 browsers now

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by tay1orjones — APPROVED** [review]
No more shift! 👍 

Percy reported 19 snapshot changes though. I just updated with latest from main to see if they'll self-resolve against updated baseline snapshots. 🤞

**Review by laurenmrice — APPROVED** [review]

**Comment by tw15egan** [comment]
The bounding margins of the Checkbox have been reduced, so the changes are expected 👍🏻

**Pull request merged**
