### PR TITLE
feat(color-tokens): add skeleton tokens

### LINKED ISSUE #1824: Add skeleton-ui token
Ref: https://github.com/IBM/carbon-components/pull/1797

Current skeleton color calls for token that has a value of `#e5e5e5` (i.e. `$hover-ui`), and `#bebebe` (i.e. `$ibm-colors__gray-30`, or `$active-ui`). Neither of those tokens seem semantically correct. It seems like we need a `$skeleton-ui` and `$skeleton-text` token.

### PR DESCRIPTION
**Pull request by shixiedesign**
Closes https://github.com/carbon-design-system/carbon/issues/1824

Added skeleton tokens to themes package and then ran `yarn build` in `carbon/packages/`. 

**New** 
Tokens `skeleton01` and `skeleton02`

### CODE REVIEW

**Review by dakahn — APPROVED** [review]

**Review by asudoh — COMMENTED** [review]
🎉 @shixiedesign Is the removal of several files intentional? I have an impression that we need to run the build and check them in.

**Comment by asudoh** [comment]
Given CI seemed to have been broken I just ran the build and pushed the result. Just for a record the command was `npx lerna run build --scope @carbon/themes`.

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@asudoh does `npx` pull from local `node_modules/.bin` or from remote? If from remote, can also do `yarn lerna ...` as well!

**Comment by shixiedesign** [comment]
Thanks for the help @asudoh 
I ran `yarn build` in `carbon/packages/` thinking that's what you did last time to the `$support` tokens PR, but I guess that wasn't it. I don't intend to remove any files. Only intent of this PR is adding `$skeleton-01` and `$skeleton-01`.

**Comment by asudoh** [comment]
@joshblack Not much into this space, but I have an impression that it's from local as long as local one is available. Anyway, you are right that `yarn lerna` is an alternate.

**Pull request merged**
