### PR TITLE
chore(examples): build examples based on whitelist

### LINKED ISSUE #2895: Setup auto-deploy of Elements package preview links
Elements preview links are not auto-updated any more. Would be great to have an up-to-date preview link to confirm any changes made it in correctly. 

Eg.

https://carbon-elements.netlify.com/themes/examples/preview/#theming

### PR DESCRIPTION
**Pull request by joshblack**
Closes #2895 

Update `tasks/examples.js` to work with new monorepo setup. Also updated netlify config to point this to repo to allow deploy previews for elements.

#### Changelog

**New**

**Changed**

- `tasks/examples.js` has been updated to include a package whitelist.

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @shixiedesign

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by dakahn — APPROVED** [review]

**Comment by shixiedesign** [comment]
Thanks for this Josh!!! Looks updated to me all correctly. 🙌

**Review by shixiedesign — APPROVED** [review]
Looks good!

**Pull request merged**
