### PR TITLE
fix(dependencies): update to move dependencies to devDep and peerDep

### PR DESCRIPTION
**Pull request by chrisdhanaraj**
## Overview

Prior to this, anyone installing carbon-components would get a whole lot of dependencies they don't actually need. The library is standalone, it's just that pushing our development server to a cloud environment has some dependencies. When we move our testing environment to a new sandbox, that'll make some of this stuff more clear but for now just tidying this up.

### CODE REVIEW

**Comment by hellobrian** [comment]
image

**Comment by chrisdhanaraj** [comment]
@hellobrian just going to move `server.js` into the `eslintignore` file for now

**Comment by marijohannessen** [comment]
We should probably add `yarn.lock` to `.gitignore`

**Comment by marijohannessen** [comment]
👍 ✅

**Comment by hellobrian** [comment]
👍 ✅

**Pull request merged**
