### PR TITLE
fix(time-picker): adjust experimental markup alignment and colors

### LINKED ISSUE #1790: Component Design Audit v1.1 - Time picker
References #1749

## Time Picker

- text-03 for placeholder text

image

- Space should be 2px

image

- Should be 16px on both sides of chevron

image

### Light

- should be using field-02 color

image

### PR DESCRIPTION
**Pull request by emyarod**
References: #1749

Closes #1790 

This PR addresses markup alignment for icons and input elements for the experimental time picker, as well as incorrect colors

### CODE REVIEW

**Comment by emyarod** [comment]
for the reviewers:

I am confused about the audit turning up a required change for the placeholder text color, [since it is `$text-03` in the experimental styles](https://github.com/IBM/carbon-components/blob/c408f6866bc1280ea25d58064530a1f7a97e1ff9/src/components/time-picker/_time-picker.scss#L159)

is this just an issue with us having outdated carbon color package dependencies?

**Review by jnm2377 — APPROVED** [review]
Looks good to me!

**Comment by jnm2377** [comment]
> I am confused about the audit turning up a required change for the placeholder text color, [since it is `$text-03` in the experimental styles](https://github.com/IBM/carbon-components/blob/c408f6866bc1280ea25d58064530a1f7a97e1ff9/src/components/time-picker/_time-picker.scss#L159)

Yeah, that's weird. @IBM/carbon-designers

**Comment by aagonzales** [comment]
🤷‍♀️ If its calling `$text-03` for placeholder text then its right. Could have been from an old audit.

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
