### PR TITLE
V9 changes to master

### PR DESCRIPTION
**Pull request by asudoh**
## Overview

This PR is a version of `v9` branch rebased to `master`. There are some pending changes to `v9` and I’ll make sure bringing those to here (`v9-rc`).

### Added

All `v9` changes.

## Testing / Reviewing

Another close eyes on every component will be nice. Especially code snippet - The skeleton change and the change of new set of variants seem to conflict a bit hardly, so having close eyes there will be great.

### CODE REVIEW

**Comment by tw15egan** [comment]
Thanks for getting this ready, @asudoh! 🎉

**Comment by tw15egan** [comment]
Not seeing `bx--text-input--light` styles 

screen shot 2018-05-31 at 4 13 25 pm

**Comment by tw15egan** [comment]
Number Input arrow styles seems a bit off

screen shot 2018-05-31 at 4 14 30 pm

**Comment by tw15egan** [comment]
@aledavila search close icon isn't in the correct position

screen shot 2018-05-31 at 4 15 55 pm

**Comment by tw15egan** [comment]
Small fixes have been made here: https://github.com/carbon-design-system/carbon-components/pull/838

**Comment by asudoh** [comment]
Thank you for making the fixes @tw15egan! Merged it to `v9` and cherry-picked it to here.

**Review by joshblack — APPROVED** [review]

**Review by marijohannessen — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
