### PR TITLE
fix(ContentSwitcher): set onChange event data correctly

### LINKED ISSUE #6162: ContentSwitcher selection with arrow keys
## Environment

> Operating system
MacOS

> Browser
Chrome, FireFox

> Automated testing tool and ruleset

> Assistive technology used to verify

## Detailed description

> What version of the Carbon Design System are you using?
10

> What did you expect to happen?
When using the left/right arrow keys to navigate a ContentSwitcher I expected the correct button to be selected with focus on the desired button. 

> What happened instead?
For example:
I tabbed to the first ContentSwitcher item and pressed the right arrow key. The index passed to the onChange event was the index of the currently selected button so the content did not change as the button to the right was not selected. However, focus still moved to that button.
The issue is the same when using the left arrow key. Every subsequent arrow press means focus is on the wrong button and does not align with the content displayed.

> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Tab to ContentSwitcher
2. Press either the left or right arrow key

## Additional information

This is what's captured in the onChange function (see _ref) when clicking on the desired button (Sample Code button)
image

This is what's captured in the onChange function (see _ref) when trying to move off the Sample Code button to another on it's left. (pressing the left arrow key on that button)
image

I would expect the last scenario to say `index: 0` 

Related issue: https://github.ibm.com/mhub/qp-planning/issues/5510

### PR DESCRIPTION
**Pull request by motou**
Closes #6162 

The `onChange` event data by pressing arrow keys should be the same as clicking on the previous/next switch.

#### Changelog

**Changed**

- set the `onChange` event data correctly by pressing arrow keys 

#### Testing / Reviewing

In the https://codesandbox.io/s/sad-moon-ji8u0 the event data should be the same with pressing arrow keys or clicking.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
thanks for jumping in! it looks like you need to run `prettier` to format the changed file in order to pass CI

but to address one of the points in the original issue, since this would technically be a breaking change for users, would we be fine with this change in between major releases? cc @carbon-design-system/developers-system

**Comment by tw15egan** [comment]
This will also close https://github.com/carbon-design-system/carbon/issues/6143

**Comment by tw15egan** [comment]
I think this is a similar fix to https://github.com/carbon-design-system/carbon/pull/6257

cc @joshblack

**Comment by motou** [comment]
Yes almost the same 😅 but the other fix uses `...data`, which introduces unwanted attribute `key`. That is not what the user expects. See https://github.com/carbon-design-system/carbon/pull/6257/files#r500786562

I agree that it belongs to breaking changes. Moreover, I am thinking if the `onKeyDown` event of the original / destination tab should be triggered as well, just like the mouse event: firstly child component Switch `onClick` event, then ContentSwitcher `onChange` event.

**Comment by joshblack** [comment]
For context, the spread on `data` was to try and match the existing implementation and try and ship the correct one at the same time (e.g. currently it does `this.props.onChange(data)` and so the PR was attempting to maintain that functionality)

Unfortunately, removing that `data` would be a breaking change (as noted above) and we wouldn't be able to ship this until v11 😞

**Comment by dakahn** [comment]
@motou bump

**Pull request closed without merging**
