### PR TITLE
fix(list-box): update CarbonX selection icon svg's height

### LINKED ISSUE #2111: [Carbon X] List box "clear selected item" svg is not placed correctly
## Detailed description

Head over to the experimental component environment and select an item in the `ComboBox`: http://react-experimental.carbondesignsystem.com/?selectedKind=ComboBox&selectedStory=Default

You will see this:
Screen Shot 2019-03-15 at 2 21 32 PM

Looks like a `list-box` style is missing in this library. I believe adding `height: 100%;` to the svg itself will fix this. PR incoming 👍

### PR DESCRIPTION
**Pull request by jendowns**
Closes #2111 

#### Changelog

**Changed**

- adds `height: 100%` to the `bx--list-box__selection` svg so it is placed better. This is similar to what is done for the `bx--list-box__menu-icon` svg already 👍   (for comparison: https://github.com/IBM/carbon-components/blob/master/src/components/list-box/_list-box.scss#L456)

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Comment by joshblack** [comment]
cc @IBM/carbon-designers @laurenmrice do we use the chevron glyphs for dropdown variants, or should we use a 16x16 version?

**Review by emyarod — APPROVED** [review]
Thanks for the fix!

**Comment by laurenmrice** [comment]
@joshblack we are currently using the 16x16 version

**Comment by joshblack** [comment]
@IBM/carbon-developers should this be merged in as-is or should we be updating the assets to use the 16x16 variant? (or both?) I believe the hbs is using the glyph variant of these icons right now.

**Comment by emyarod** [comment]
this should be fine as-is right? I believe there are some other components using the chevron glyphs instead of 16x16 so we can cut a new issue for that

**Comment by joshblack** [comment]
@emyarod if the spec has it at 16x16 icon we should be using that instead of the glyph so that it aligns with type and so custom CSS may not be needed to size/position it 👍

**Comment by asudoh** [comment]
@jendowns Do you want to go ahead with the change that @joshblack suggests? Or would you feel better if we take care of choosing the sized icon? Thanks!

**Comment by tw15egan** [comment]
Just chiming in, I agree with @joshblack's suggestion. Would be nice if all assets are using the intended sizing to reduce possible style bugs

**Comment by jendowns** [comment]
Thanks everyone! 🎉  (oops sorry, started to tag all and realized it would have been a quite a list 😆)  I'll update the icon shortly

**Review by joshblack — APPROVED** [review]

**Review by shixiedesign — APPROVED** [review]
LGTM! 👍 Thanks Jen!

**Pull request merged**
