### PR TITLE
fix(_var): easing & duration values update

### PR DESCRIPTION
**Pull request by shixiedesign**
Updated static values (easing curves, default duration) in global var scss to get closer to the look & feel of the new IDL.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Is this for v9 or v10?

**Comment by shixiedesign** [comment]
V10! Just added feature flag.

**Comment by shixiedesign** [comment]
Reverted the change once because I should have left `flatpickr` alone. It uses `-webkit-animation` and probably have issues using the tokens.

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
unified header and left nav are deprecated components (they live in cloud addons now), so I think you can remove those updates. 

If you're looking for our left nav on the website the css for that is coming from UI-Shell first and then  the website-addons repo

**Review by asudoh — APPROVED** [review]
LGTM 👍 - While we may want to do if-else block rather than define-then-override, such (and other) structural changes can be done after. Thanks alot @shixiedesign for jumping in!

**Comment by asudoh** [comment]
And good point @alisonjoseph wrt deprecated components!

**Review by joshblack — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Comment by shixiedesign** [comment]
Closes https://github.com/carbon-design-system/carbon-website/issues/841

**Pull request merged**
