### PR TITLE
chore(components): update icons to use exp icons behind feature flag

### LINKED ISSUE #1441: Update icons in experimental components
After going through an audit of our existing icon usage, we noticed some of the following components that might need their icons updated with our handlebars helpers:

- Button
  - AddSolid
- Dropdown
  - Caret should be chevron
- Notification
  - Pulling in 16s
  - Close 10x10
  - InformationSolid
  - ErrorFilled - SOlid?
  - CHeckmarkFilled - Solid?
  - WarningAlt 16
- Number Input
- Overflow Menu
  - Put glyph (3x15) on 16x16 for Overflow Menu
- Select
  - Chevron, not caret
- Structured LIst check
- Text Input
  - Error icon
- Selectable Tile
  - Check
  - Chevron
- Tooltip
  - information
- Code Snippet
  - Copy
- Modal
  - Close
- File Uploader
  - Close
- Search
  - Search
- Pagination
  - Chevron
- Time Picker
  - Chevron
- In general, we should make sure these icons are updated:
  - Close

### PR DESCRIPTION
**Pull request by joshblack**
Closes #1441 

This is a WIP PR, will most likely require bouncing between design and development review. Below are some questions for design and development reviewers, will make sure to push commits with any changes requested!

Design Questions:

- For Code Snippet, I went ahead and added in https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcopy, wanted to confirm that's 🆗 
- Notifications
  - `WarningFilled16` does not include the filled ! in the center
  - Should close be replaced with `Close16`?
- Number Input
  - Looks like glyphs turned into a 16x16, should we keep using glyphs or refactor styles to work with 16x16?
- Overflow Menu
  - Was unable to find a horizontal example, does one exist in our environment?
- Text Input
  - Do we have icons for visibility status?
  - Not allowed for disabled?

Developer questions:

- Date Picker seems tricky to update SVG markup, any tips?
- Select needs to have its styles fixed
- For text input, it seems like we're inlining in the CSS?

#### Changelog

**New**

**Changed**

- Components described in #1440, namely `*.config.js` and `.hbs` templates

**Removed**

#### Testing / Reviewing

[Preview URL](http://carbon-dev-environment-shy-lion.mybluemix.net/)

- Verify that icons work in experimental mode and stable do not break

### CODE REVIEW

**Comment by joshblack** [comment]
cc @chrisconnors-ibm @aagonzales @designertyler @laurenmrice @jeanservaas @shixiedesign

**Comment by alisonjoseph** [comment]
The inline css for text input was temporary, so something to revisit now that we have a way to update html only for experimental.

**Comment by asudoh** [comment]
Good going though component @joshblack - For date picker, you can do:

```handlebars
<div data-date-picker data-date-picker-type="single" class="bx--date-picker bx--date-picker--single">
  <div hidden data-date-picker-right-arrow-html>
      {{ carbon-icon ... }}
  </div>
  <div hidden data-date-picker-left-arrow-html>
      {{ carbon-icon ... }}
  </div>
  <div class="bx--date-picker-container">
    ...
  </div>
</div>
```

```javascript
class DatePicker extends mixin(createComponent, initComponentBySearch, handles) {
  ...

  _rightArrowHTML() {
    const elem = this.element.querySelector(this.options.selectorRightArrowHTML);
    return !elem ? '' : elem.innerHTML;
  }

  _leftArrowHTML() {
    const elem = this.element.querySelector(this.options.selectorLeftArrowHTML);
    return !elem ? '' : elem.innerHTML;
  }

  ...

  static get options() {
    ...
    return {
      ...
      selectorRightArrowHTML: '[data-date-picker-right-arrow-html]',
      selectorLeftArrowHTML: '[data-date-picker-left-arrow-html]',
    };
  }
}
```

**Comment by chrisconnors-ibm** [comment]
> For Code Snippet, I went ahead and added in https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fcopy, wanted to confirm that's 🆗

Yep!

>Notifications
>WarningFilled16 does not include the filled ! in the center

They were black before for contrast - can we use https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fwarning--alt--filled so we have the shape, the [!], the color and the label for distinction?

>Should close be replaced with Close16?

Yep great!

>Number Input
>Looks like glyphs turned into a 16x16, should we keep using glyphs or refactor styles to work with 16x16?

per our convo will update the glyphs for :
https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fcaret--down
https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fcaret--left
https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fcaret--right
https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fcaret--up

https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fchevron--down
https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fchevron--left
https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fchevron--right
https://ibm.github.io/carbon-elements/icons/examples/esm/#%2Fchevron--up

moving towards _only_ having glyphs for caret--h, caret--v, chevron--h, chevron--v

>Overflow Menu
>Was unable to find a horizontal example, does one exist in our environment?

Me neither - what was I looking at? disregard.

>Text Input
>Do we have icons for (password) visibility status?

https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fview--off
https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fview

>Not allowed for disabled?

propose https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Ferror--outline

**Comment by joshblack** [comment]
@chrisconnors-ibm 

> can we use https://ibm.github.io/carbon-elements/icons/examples/esm/#16%2Fwarning--alt--filled so we have the shape, the [!], the color and the label for distinction?

Added in that icon, but it looks like the path gets consolidated into one so the ! is not styled. Is that what is expected? (staging link reflects this)

**Comment by joshblack** [comment]
Final pass:

- [x] Accordion
  - Update style to enforce 16x16 icon, including setting flex-basis and flex-shrink to prevent size collapse
- [x] ~Breadcrumb~
- [x] Button
- [x] ~Checkbox~
- [x] Code Snippet
  - 16x16
  - Copy16
- [x] Combobox
  - 10x6
  - ChevronDownGlyph
- [x] Content Switcher
  - 16x16
  - AddFilled16
- [x] CopyButton
  - 16x16
  - AddFilled16
- [ ] Data Table, will need to be in separate PR
- [ ] Date Picker, will need to be in separate PR
- [x] Dropdown
  - 10x6
  - ChevronDownGlyph
- [ ] FileUploader, needs close icon, add in separate PR
- [x] Form
  - 10x6
  - ChevronDownGLyph
- [x] ~Inline loading~
- [x] ~Link~
- [x] ~List~
- [x] ListBox
  - 10x6
  - ChevronDownGlyph
- [x] ~Loading~
- [x] Modal
  - 16x16
  - Close16
- [x] MultiSelect
  - 10x6
  - ChevronDownGlyph
- [x] Notification
    - Close16
    - ErrorFilled16
    - CheckmarkFilled16
    - WarningAltFilled16
- [x] NumberInput
  - 8x4
  - CaretDownGlyph
- [x] OverflowMenu
  - OverflowMenuVertical16
- [ ] Pagination, will need to be in separate PR
- [x] ProgressIndicator
  - CheckmarkOutline16
  - Warning16
- [x] ~RadioButton~
- [x] Search
  - Search16
- [x] Select
  - ChevronDownGlyph
- [x] ~Skeleton~
- [x] Structured List
  - AddFilled16
- [x] ~Tabs~
- [x] ~Tag~
- [x] ~Text Area~
- [ ] Text Input, will need to be in separate PR
- [x] Tile
  - ChevronDown16
  - AddFilled16
- [x] Time Picker
  - ChevronDownGlyph
- [x] ~Toggle~
- [x] Toolbar
  - Icons updated but needs style updates (maybe?)
- [x] Tooltip
  - Information16
  - Filter16

**Review by aagonzales — COMMENTED** [review]
Still spotted a few problem children:
- It still looks like the chevrons in `dropdown` and `select` are getting shrunk down a little for some reason.
- `Text inputs: disabled` is calling the wrong icon. The slash should be going in the other direction.
- `Time picker` needs chevrons not carets

**Comment by joshblack** [comment]
@aagonzales just to confirm are you checking on: https://deploy-preview-1490--the-carbon-components.netlify.com or the previous URL comment?

RE: text inputs, those will be in a separate PR 👍 

RE: time picker, on it!

**Comment by aagonzales** [comment]
yes was using the link here for review: https://github.com/IBM/carbon-components/pull/1490#issuecomment-444230729

**Review by aagonzales — APPROVED** [review]

**Comment by laurenmrice** [comment]
Two things I noticed:
- Button components pulling in old icon still (you might already know that)
- Code snippet copy icon appears blurrier in firefox than chrome/safari for some reason?

**Comment by joshblack** [comment]
@laurenmrice updated the button icon! The blurriness should also be resolved 👍

**Review by laurenmrice — APPROVED** [review]
Looks good to me, the only things I saw to be off were the ones you addressed in other issues 👍

**Review by alisonjoseph — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
