### PR TITLE
fix(DatePicker): add override behavior for start date deletion bug

### LINKED ISSUE #12980: [Bug]: Date picker of type range never call onChange when second input value change
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.11.0

### React version

v17.0.2

### Description

This bug is for the possibility to type a date by hand and not using the calendar widget.
For a range date picker, the onChange props is never called after typing in the second input (and not choosing a date in the calendar) and close the calendar.
It works for the first input. And of course it works normally by using the calendar widget for both input.

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

https://stackblitz.com/edit/github-pzlus6-jt29yb?file=src/App.jsx

### Steps to reproduce

- Type a date in the first input, quit & focus again the first input, the date in the calendar change
- Type a date in the second input, quit & focus again the second input, the date don't change on the calendar
- try console.log the onChange prop, for the first input the function is called, for the second nothing happen.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #12980 

#### Changelog

**Changed**

- Added conditional to `fixEventsPlugin` to programatically re-set the start date that is getting deleted on the `endDate` blur due to the flatpickr bug

#### Testing / Reviewing

Follow reproduction steps in #12980 and confirm calendar gets updated in PR deployment. Also test DatePicker keyboard and mouse behavior to ensure no regressions

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Oooh I was gonna bug you to look at this next week, but you're too fast! 🔥 This works if I type in the date and click off, but if I click a date on the calendar and click off it disappears, or click back in/out if disappears too. wondering if that is also something we could/should fix?

**Comment by francinelucca** [comment]
> https://deploy-preview-13443--carbon-components-react.netlify.app

Ah I see what you mean... I/we can take a look next week!

**Comment by francinelucca** [comment]
Ready for re-rev! @alisonjoseph @andreancardona

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by andreancardona — APPROVED** [review]
🔥

**Pull request merged**
