### PR TITLE
fix(icons-angular): update node parse logic

### LINKED ISSUE #2826: SVG icons don't show up in IE 11
Hello,

I've been using this for my project: https://github.com/carbon-design-system/carbon-elements/tree/master/packages/icons-angular.

But in IE 11, none of the icon is getting displayed. When inspected, the `<path>` is not getting rendered.

Thanks.

### PR DESCRIPTION
**Pull request by cal-smith**
- use importNode to keep ownerDocument references in sync

Closes #2826 (again)

Turns out the original node looping logic only completed one loop - because `appendChild` pulled the node into the document, and broke the `nextSibling` chain ... oops!

### CODE REVIEW

**Comment by cal-smith** [comment]
I tested this with a few icons in chrome, firefox, and IE, and they all worked correctly.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @cal-smith!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by joshblack** [comment]
@cal-smith do we need another patch release for this?

**Comment by cal-smith** [comment]
> @cal-smith do we need another patch release for this?

Sorry, @joshblack I think this notification got lost somehow ... yes, absolutely 👍

**Comment by joshblack** [comment]
No sweat! We pulled this in for 10.3.1: https://github.com/carbon-design-system/carbon/pull/3024

**Comment by cal-smith** [comment]
I think that was the last PR on this topic ... this PR fixes a bug introduced there 😬 ... so I think we'll need a `10.3.2`

**Comment by joshblack** [comment]
Got it! Sounds good 😄

**Pull request merged**
