### PR TITLE
docs: remove old examples

### LINKED ISSUE #14599: Migrate off CRA: Determine which examples we should remove, and remove them

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #14599

#### Changelog

**Removed**

- `/examples/incremental-migration`
  - migrated to vite `/examples/incremental-migration-vite`
- `/packages/react/examples/codesandbox`
  - duplicate of `examples/codesandbox`
- `/packages/react/examples/create-react-app`
- `/packages/react/examples/custom-css-prefix`
  - duplicate of `examples/custom-css-prefix`
- `/packages/react/examples/next`
  - duplicate of `examples/nextjs`

#### Testing / Reviewing
Double check what I'm removing is ok to remove

### CODE REVIEW

**Comment by tay1orjones** [comment]
@alisonjoseph I think we'll probably want to keep `incremental-migration` for now until at least v10 is sunset. All the others look fine to delete to me 👍

**Review by tay1orjones — APPROVED** [review]

**Comment by alisonjoseph** [comment]
@tay1orjones its already been migrated to `/examples/incremental-migration-vite` so I think we can delete this version? Let me know if we need both for some reason though.

**Comment by tay1orjones** [comment]
@alisonjoseph Oh yeah! I totally forgot about that 😅 This looks good to merge 👍

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
