### PR TITLE
fix(selection): save onChange callback in useEffect

### LINKED ISSUE #6259: Infinite re-render with MultiSelect 10.13/7.13
## What package(s) are you using?

- [x] `carbon-components` 10.13
- [x] `carbon-components-react` 7.13

## Detailed description

With latest carbon-components, MultiSelect within Formik result in an infinite re-render. This does not happen with v10.12/7.12.

## Steps to reproduce the issue

- https://codesandbox.io/s/silent-breeze-oxhne?file=/src/index.js
- Replace `"` in the text field with a different character
- Infinite re-render (you can open the browser inspector to see the never-ending `console.log`s)

### PR DESCRIPTION
**Pull request by joshblack**
Closes #6259 

#### Changelog

**New**

**Changed**

- Update `useSelection` hook to only call `onChange` with changes to `selectedItems` to prevent infinite re-render when `onChange` may trigger a re-render

**Removed**

#### Testing / Reviewing

- Going to try and get an example up to run with these changes soon!

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by joshblack** [comment]
Quick steps to verify:

1. Download codesandbox from linked issue
2. Checkout this PR on your computer
3. Run `yarn lerna run build --scope='carbon-components-react' --include-dependencies` to build the react package
4. Set `carbon-components-react` in the codesandbox `package.json` to `file:./path/to/react/package` Mine looks like

```
"carbon-components-react": "file:/Users/joshblack/work/carbon/monorepo/packages/react",
```

5. Run `yarn start` and verify you can delete the `"` without an infinite loop being triggered

**Comment by joshblack** [comment]
@aledavila let me know if you want to sync up or have any questions!

**Review by tw15egan — APPROVED** [review]
Tested by following @joshblack steps, verified no infinite loop 🎉

**Pull request merged**
