### PR TITLE
fix(notification): resize and remove overrides

### LINKED ISSUE #2118: Incorrect notification icon size
we need to refactor the vanilla component. In the [vanilla HTML](https://github.com/IBM/carbon-components/blob/master/src/components/notification/notification.hbs#L14), we are using icon helpers for 16px icons in both toast and inline notifications, but we have some [CSS rules only on the inline notification icons](https://github.com/IBM/carbon-components/blob/master/src/components/notification/_inline-notification.scss#L170-L173) which upscale the icon to 20x20. This is fine because they are SVGs, but it might be less confusing to just directly use the 20x20 icon helpers in the markup and remove those style rules, especially since they are [different in the current toast notifications](https://github.com/IBM/carbon-components/blob/master/src/components/notification/_toast-notification.scss#L151-L154) when they should be the same

Related: https://github.com/IBM/carbon-components-react/pull/2020

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2118

This PR resizes our notification icons according to experimental spec and removes unneeded style overrides

Related: https://github.com/IBM/carbon-components-react/pull/2020

#### Changelog

**Changed**

- notification icons from 16px to 20px
- prevent icons from shrinking in flex container

**Removed**

- style overrides

### CODE REVIEW

**Review by chrisconnors-ibm — CHANGES_REQUESTED** [review]
There is no 20x20 asset for 
image
once it's created and added to elements, re-factor/review

**Comment by chrisconnors-ibm** [comment]
This pr adds those assets: https://github.com/IBM/carbon-elements/pull/438

**Review by jnm2377 — APPROVED** [review]
Looks good once Connors' comment is addressed! 👍

**Review by dakahn — APPROVED** [review]
👍

**Comment by chrisconnors-ibm** [comment]
IBM/carbon-elements#438 merged and provides all 4 assets @ 20x20 with a stylable `inner-path`. do other changes need to be made to call the correct `20/error--filled.svg` asset?

**Comment by emyarod** [comment]
@chrisconnors-ibm I believe we need to cut a `carbon-elements` release, and I need to target the new version for the changes to be reflected here

**Comment by asudoh** [comment]
@joshblack ^ Would you be able to do that? Thanks!

**Comment by chrisconnors-ibm** [comment]
@joshblack do any changes need to happen here to catch the `20/*.svg` now assuming they exist in `carbon-elements`?

**Comment by asudoh** [comment]
Adding a note just in case: IBM/carbon-elements#438 seems to have been merged a few hours ago whereas the latest `carbon-elements` release was 5 days ago. That said, to incorporate IBM/carbon-elements#438 in here we need a new release of `carbon-elements` as @emyarod said.

**Comment by emyarod** [comment]
this PR has been updated to include the new `carbon-elements` release

**Review by tw15egan — APPROVED** [review]
Looks good, waiting for @chrisconnors-ibm to review

**Review by chrisconnors-ibm — APPROVED** [review]

**Pull request merged**
