### PR TITLE
fix(date-picker): remove border radius

### LINKED ISSUE #8190: [Date picker] Remove rounded corner
Found in date picker: https://react.carbondesignsystem.com/?path=/story/components-datepicker--range
**Expecting sharp corners**
image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #8190

This PR removes the border radius of the flatpickr calendar to match the component spec

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Comment by shixiedesign** [comment]
Hmm... I think I still see it in the preview build? 
image

**Comment by tw15egan** [comment]
Hmm yeah, it seems like it's not picking up the border-radius from `flatpickr-calendar` and needs to be added to `.flatpickr-calendar.open` for some reason.

cc @emyarod

**Comment by emyarod** [comment]
will take another look

**Comment by emyarod** [comment]
I don't think it's related to the open class, it's just the rule a few lines down

**Pull request merged**
