### PR TITLE
fix(dropdown): fix the label position of inline variant

### LINKED ISSUE #1986: Inline dropdown: Wrong caret position
## Detailed description

> Describe in detail the issue you're having.

The caret position of inline dropdown goes below the label, like:

image

> Is this issue related to a specific component?

Dropdown, inline variant.

> What did you expect to happen? What happened instead? What would you like to see changed?

The caret position of inline dropdown should be right next to the label, like:

image

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

`v9.82.4` or latest `master`

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #1986.

#### Changelog

**Changed**

- `dropdown.hbs` not to use separate `<li>` for caret/chevron/label for the inline variant. The inline variant surrounds the text portion with `<span>` and thus #1895 doesn't happen.

#### Testing / Reviewing

Testing should make sure dropdown is not broken, for all combinations in `v9`/`v10` and regular/inline matrix.

### CODE REVIEW

**Comment by asudoh** [comment]
@emyarod Please don't hesitate to bring up if you think of a better logic - Thanks!

**Review by emyarod — APPROVED** [review]
looks good to me 👍

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Changes:**

- [ ] The text is still in Helvetica.  Needs to be Plex and body-short-01 type style (text-02 color token).
- [ ] In the preview the dropdown hover and drawer is very long compared to the items in the dropdown. It looks fine if you full render though, but they should match.
screen shot 2019-03-07 at 10 01 17 am

**Comment by emyarod** [comment]
regarding the type tokens, that change is contained in #1994 (still a WIP) so we can disregard it here I believe!

**Comment by emyarod** [comment]
@asudoh would this address https://github.com/IBM/carbon-components-react/issues/1651 eventually as well?

**Comment by asudoh** [comment]
@emyarod This fix is for inline dropdown, where as IBM/carbon-components-react#1651 is about inline select. So they are different.

**Comment by asudoh** [comment]
Thanks @laurenmrice for reviewing! @emyarod is right on type tokens. Given this is for fixing a regression, let me track the issue of hover/drawer in a separate issue.

**Comment by emyarod** [comment]
the hover/drawer width issue should be resolved in https://github.com/IBM/carbon-components/pull/2020

**Review by dakahn — APPROVED** [review]
Nice. Thanks! 🏄🏽‍♂️

**Review by laurenmrice — APPROVED** [review]
Since the type tokens and width/drawer problem are being covered in different open issues now, we can merge this PR for fixing label and icon spacing for inline dropdown.

**Pull request merged**
