### PR TITLE
[Documentation Typo] Typo in React Tabs Documentation

### PR DESCRIPTION
**Pull request by StevenSpeck**
Grammar and spelling fix:
"Which means a tab title can span as wide as long it's title is."  ->
 "Which means a tab title
can span as wide as its title is long."

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by StevenSpeck** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by StevenSpeck** [comment]
recheck

**Review by guidari — APPROVED** [review]
I checked both sentences and LGTM. 

Thanks for contrubuting!

**Comment by francinelucca** [comment]
@aubrey-oneal tagging you for a review on this copy change 🙏🏻

**Review by tay1orjones — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
