### PR TITLE
fix(breadcrumb-skeleton): use span elements to remove DAP violation

### LINKED ISSUE #4178: AVT 1 - Skeleton: Breadcrumb has a DAP violation for missing hyperlink label
##Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon v10 - React
DAP IBM Accessibility 1.8.0.0 Sept 2019 Ruleset

##Detailed Description
Go to the React skeleton for Breadcrumb
Run DAP and the following issue is found on the on each skeleton component (see screenshots):
breadcrumb

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4178 

Because the these anchors need to have link text for accessibility but they are part of a skeleton component that doesn't have link text, I opted to change these `<a>` elements to `<span>` elements (with no `href` attr) instead.

My reasoning:
Since this is a skeleton component, the required link text would need to be visually-hidden and readable for screen readers -- but since this is a skeleton component, the real link text for the non-skeleton version of the component wouldn't be available yet or interactive. So aside from the real link text, which isn't available during the skeleton/loading state, the only other text that could be used would be information text -- but what kind of information could be conveyed here that could be meaningful and not become extra noise for a screen reader? 🤔 This is why I went with a `<span>` instead.

Let me know what you think! (cc @dakahn)

#### Changelog

**Changed**

- change `<a>` elements in breadcrumb skeleton to `<span>` elements without an `href` attribute

#### Testing instructions

Run the DAP tool with the latest Sept 2019 ruleset 👍

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
I'm down for this, in a general note how should we be doing skeleton loading states @dakahn ?

**Comment by abbeyhrt** [comment]
I messaged you on slack @joshblack about what i think we have so far on the skeleton loading states. We also have a milestone in place to add in this work as well

**Review by dakahn — APPROVED** [review]

**Comment by dakahn** [comment]
Yeah the A11y Project team is taken on some problems with our skeleton states in upcoming work cycles. This seems great 👍 

And excellent PR description as always @jendowns

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by abbeyhrt — APPROVED** [review]
Looks great! Thank you!

**Pull request merged**
