### PR TITLE
fix(dropdown): ensure inline dropdown has transparent background

### LINKED ISSUE #5321: Inline Dropdown bg color in Gray 10 theme
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Inline dropdown with Gray 10 theme applied, the background color is using $ui-background which is f4f4f4. But our designer is saying it should be white

> Is this issue related to a specific component?
Yes, Dropdown

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Our designer Marion Brülls says it should be white

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
CP4D

## Steps to reproduce the issue

https://ibm-analytics.slack.com/archives/C046Y0YUD/p1581450533133200

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5321

Sets the background of inline dropdowns to transparent so it will always appear correct no matter the background

Screen Shot 2020-02-11 at 12 57 32 PM

#### Changelog

**Changed**

- Change background from `ui-background` to `transparent`

#### Testing / Reviewing

Ensure the inline dropdown does not have a background by manually setting a background color on the container of the inline dropdown.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Comment by aagonzales** [comment]
So inline dropdown actually should be transparent on enabled, it isn't supposed to have a background expect on hover/active.

(I still don't have a local build so I can't see it)

**Review by aagonzales — CHANGES_REQUESTED** [review]
So inline dropdown actually should be transparent on enabled, it isn't supposed to have a background expect on hover/active.

(I still don't have a local build so I can't see it)

**Comment by asudoh** [comment]
Hi @aagonzales just wanted to double-check if you can test it with https://deploy-preview-5322--carbon-components-react.netlify.com (given React deploy preview didn't fail)? If there was a different reason why you needed a local build my apologies.

**Comment by aagonzales** [comment]
@asudoh It's still wrong. Inline dropdown shouldn't have a background color except on hover.It should be transparent and therefor will not need the light variant.

**Comment by asudoh** [comment]
@aagonzales Thank you for your response! @tw15egan Does what @aagonzales pointed out happen in your local dev env?

**Comment by tw15egan** [comment]
@aagonzales that makes way more sense, not sure why I didn't do that in the first place. I blame dad brain 🤦‍♂ 

@asudoh ready for re-review

**Review by aagonzales — APPROVED** [review]
Perfect!

**Review by asudoh — APPROVED** [review]
Super 🎉 - Thank you for your update @tw15egan!

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
🤦‍♂ forgot to change commit message, should have been `fix(dropdown): ensure inline dropdown has transparent background`

**Pull request merged**
