### PR TITLE
fix(button): correct sizes for icon-only buttons

### LINKED ISSUE #5194: [Button]: Icon-only variant has wrong sizes
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The icon-only buttons should be squared regardless of their size (default, field, small)

> Is this issue related to a specific component?

Yes, `Button`

> What did you expect to happen? What happened instead? What would you like to see changed?

|Size|Current dimensions|Expected dimensions|
|:-|:-|:-|
|Default|47 x 48|48 x 48|
|Field|47 x 40|40 x 40|
|Small|47 x 32|32 x 32|

image

> What browser are you working in?
Chrome 79

> What version of the Carbon Design System are you using?
`carbon-components@10.9.2`

## Steps to reproduce the issue

1. Open http://react.carbondesignsystem.com/?path=/story/buttons--icon-only-buttons
2. Cycle through the sizes

### PR DESCRIPTION
**Pull request by janhassel**
Closes #5194

Fixes the sizing for icon-only buttons to make them square regardless of size (default, field, small)

#### Changelog

**Changed**

- `padding-left` and `padding-right` on icon-only button specific selectors

#### Testing / Reviewing

Run react storybook, inspect sizes with dev tools

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
looks good to me but just want confirmation from the design team regarding this

**Comment by laurenmrice** [comment]
@emyarod yes the icon button at each size we have should always be square.

**Review by tw15egan — APPROVED** [review]
Looks great, thanks for hopping in and fixing this. 👍 ✅

**Review by emyarod — APPROVED** [review]
looks good to me pending design approval

**Review by laurenmrice — CHANGES_REQUESTED** [review]
The tertiary icon only button (field) in Vanilla needs to be square still.
Screen Shot 2020-01-28 at 12 54 36 PM

Also I noticed some two other things which can be fixed separately in different prs.
- We don't have a tertiary button in the react storybook and need to add it.
- Vanilla needs to have the icon only button for all sizes, not just field.

**Comment by emyarod** [comment]
> * We don't have a tertiary button in the react storybook and need to add it.
> * Vanilla needs to have the icon only button for all sizes, not just field.

these will be addressed in #5201 so we can just update this PR to fix the tertiary icon button

**Review by dakahn — APPROVED** [review]

**Comment by janhassel** [comment]
Good catch, @laurenmrice!
Seems like the different border width (1px instead of 3px) was the cause of that issue. I increased the padding on tertiary icon-only buttons to account for the "missing" 2px on each side.

**Review by laurenmrice — APPROVED** [review]
looks good to me ! thanks for doing this ! 🙌🏻

**Pull request merged**
