### PR TITLE
chore(react): use babel runtime on es builds

### PR DESCRIPTION
**Pull request by salvoravida**
chore(react): use babel runtime on es builds

Hi guys!

This PR adds @babel/runtime on es builds. -> less **60/100k** on your bundle.js depended on how many components are used.

### CODE REVIEW

**Comment by salvoravida** [comment]
recheck

**Comment by salvoravida** [comment]
> @salvoravida Thanks for doing this! I think we'll also need to include `@babel/runtime` as a dependency, potentially? 👀
It is already included by babel. not needed.

**Review by joshblack — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Sorry - actually needs a `yarn` to update the lockfile. I'll pull this down and do it.

**Review by tay1orjones — APPROVED** [review]
Done 👍  LGTM if status checks pass

**Pull request merged**
