### PR TITLE
feat(helper-text): move helper text below form inputs

### LINKED ISSUE #5279: enhancement[helper text]: move helper text below input fields and dropdowns
### Problem:

- Product designers are having UI alignment issues with the helper text below the label

<br>

- The stacking of the helper text under the label and the subtle color shift between the two pieces of type is fussy and not differentiated enough. $label-01 token value had to be pushed from Gray 70 to Gray 80 to make the label stand apart from the helper text; the stacking under the label also creates weird ragging

<br>

- after a brief competitive analysis, many other best-in-practise design systems use the arrangement we are proposing including: Material, Atlassian, Patternfly and Quickbooks to name a few; not only is it more intuitive for uses but it's a better design.

<br>

- We wanted to do this earlier but were worried about screen readers semantically reading label > help text > input in order; however you can set the screen reader order apparently to avoid that issue according to elizabeth judd this should not be a blocker.

<br>

- [x] Move helper text below input fields and drop down

<br>

- [x] Change value of $text-02 to Gray 70... both labels and helper text can now use $text-02

<br>

- [x] Remove right padding on helper text in mobile breakpoint

<br>

**Proposed spec:**

Dropdowns with helper text will function the same way, and cover the helper text when it is open... we don't believe this is a problem:

**Motion specs:**

Error message will animate to replace helper text; when you start to retype your input to correct the error the helper text will reappear. Material has a much better example of this than I can animate:

https://material.io/components/text-fields/#anatomy

We will use our productive standard easing curves.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5279

This PR moves the helper text for form inputs below the input themselves.

#### Changelog

**Changed**
- Helper text now uses `$text-02`
- Moved helper text below form inputs
- Changed margin on helper text 
- Updated vanilla examples

**Removed**

- Wrong `line-height` on form requirement text
- Extra styles in `_textarea.scss`

#### Testing / Reviewing

Check form elements and make sure they render correctly when invalid and in all other states. 

- [ ] Combobox
- [ ] Dropdown
- [ ] Form
- [ ] Listbox
- [ ] Multiselect
- [ ] Select
- [ ] Text Input
- [ ] Textarea

### CODE REVIEW

**Comment by tw15egan** [comment]
@dakahn is there anything I need to add to the helper text for a11y purposes?

**Review by jeanservaas — APPROVED** [review]
lgtm

**Review by dakahn — APPROVED** [review]
I think since we're just moving stuff around here we should be good. Typically you'd want `aria-describedby` attributes on the inputs with IDs referencing the helper text. If we're missing those we can patch them up in another PR though.

**Comment by dakahn** [comment]
Anyway we can sit on this one for one more day while we get the Downshift upgrade in? The merge conflicts wont be a huge deal if we need this ASAP for something else though.

**Comment by tw15egan** [comment]
@dakahn for sure will wait to merge this until yours goes through. It will be much easier for me to fix merge conflicts 👊

**Review by aledavila — APPROVED** [review]

**Comment by dakahn** [comment]
🙏 sorry for the conflicts. Happy to help out if any of the changes seem weird though.

**Comment by tw15egan** [comment]
@dakahn @aledavila @jeanservaas updated this PR to account for the large Downshift changes we recently made, just want y'all to give it another look and make sure it still looks good! 👍

**Review by jeanservaas — COMMENTED** [review]
@tw15egan 

Looks good, I did notice one kind of weird thing... it's only for Text Area... and it's only in Safari, but the spacing looks off

all other components look fine... I also inspected Text Area in Chrome and it was fine... weird

image

but both the helper text and the input label look a little further away from the field.

**Review by aledavila — APPROVED** [review]

**Comment by tw15egan** [comment]
@jeanservaas nice catch, it seems like it was a safari only bug. I threw a `height: 100%;` on the `textarea` and it seems to render correctly now 👍

**Review by dakahn — APPROVED** [review]
Thanks so so so so so so much for scrapping through those probably gnarly merge conflicts. 🙏

**Review by asudoh — COMMENTED** [review]
LGTM basically, one question; Does the older version of markup in `.hbs` work with the newer CSS? Thanks @tw15egan!

**Comment by tw15egan** [comment]
@asudoh older markup will still work, the margin just may be a bit tight

**Pull request merged**
