### PR TITLE
feat: add readonly functionality to select

### LINKED ISSUE #12423: [Read-only inputs]: Select implementation
Needs specs

### PR DESCRIPTION
**Pull request by lee-chase**
Contributes to #2177

Closes #12423 

Adds the read-only feature to the Select component

#### Changelog

**Added**

- Adds readOnly property to Select and functionality
- Adds test for read-only Select
- Adds styling for read-only Select.

#### Testing / Reviewing

Reviewed the result in Storybook and a added read-only test.

Unfortunately, a way could not be found to test read-only preventing the selection of a value;

### CODE REVIEW

**Comment by lee-chase** [comment]
@quarryboy it was pointed out by @sstrubberg that we have no design for select. Can you rectify this?

**Review by aagonzales — CHANGES_REQUESTED** [review]
Cursor should remain as the `arrow` and should not be switched to a `hand`

Below is showing the incorrect implementation 
Nov-01-2022 14-55-18

**Comment by lee-chase** [comment]
@aagonzales cursor updated as requested. 

Did consider using 'text' cursor following last week's review, however, it does not appear possible to make text in a `<select >` component selectable.

**Review by aagonzales — APPROVED** [review]
Visually looks good, matches spec 👍

**Review by alisonjoseph — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
