### PR TITLE
chore(components): optimize component templates with each directive

### PR DESCRIPTION
**Pull request by asudoh**
## Overview

This PR is for consolidating repeating occurrences of HTML fragments in component demos, by more utilizing Handlebars features.

### Added

Handlebars `{{#each}}` usage in component demo templates.

## Testing / Reviewing

Testing should make sure no component demo is broken.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Thanks for going through and updating all of this @asudoh!! I went through all the components and the only thing that looked off was the **Data Table V2** 

screen shot 2018-07-31 at 2 31 39 pm
screen shot 2018-07-31 at 2 31 33 pm

**Comment by asudoh** [comment]
@alisonjoseph Thanks a lot for reviewing and spotting those! Fixed.

**Review by joshblack — APPROVED** [review]

**Comment by asudoh** [comment]
@joshblack Thank you for reviewing! @alisonjoseph does the fix look good to you? Please don’t hesitate to speak up if you still see any issues - Thanks!

**Review by alisonjoseph — APPROVED** [review]
looks good!

**Comment by asudoh** [comment]
Thanks @alisonjoseph!

**Pull request merged**
