### PR TITLE
fix(FilterableMultiSelect): call onMenuChange when mouse click outside

### LINKED ISSUE #16896: [Bug]: FilterableMultiSelect onMenuChange not called on click outside menu
### Package

@carbon/react

### Browser

Chrome

### Package version

1.57.0

### React version

v16.14.0

### Description

When clicking outside the menu when opened, the onMenuChange callback is not fired with the next opened state.

The change came between
[de133bea](https://github.com/carbon-design-system/carbon/blob/de133bea57dd3fef5ef45361e0906521b8c63991/packages/react/src/components/MultiSelect/FilterableMultiSelect.js)
and
[5f35edd6](https://github.com/carbon-design-system/carbon/blob/5f35edd666dfd2d30737d0095d1b3be31078f5e6/packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx)
when `FilterableMultiSelect.js` was renamed to `FilterableMultiSelect.tsx`.

The `Downshift` component had an `onOuterClick` prop set to `handleOnOuterClick` which called `handleOnMenuChange`.

### Reproduction/example

https://stackblitz.com/edit/github-wivrwb?file=src%2FApp.jsx&preset=node=

### Steps to reproduce

1. use `onMenuChange` prop on `FilterableMultiSelect` component
5. open dropdown
6. click outside menu to close
7. `onMenuChange` callback is not called

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by gi**
This fixes an issue where a mouse click event outside of the menu does not call the `onMenuChange` callback when the menu is open.

Closes #16896

#### Changelog

**Changed**

- FilterableMultiSelect: calls onMenuChange when mouse click outside of menu

#### Testing / Reviewing

Unit tests added.

### CODE REVIEW

**Comment by Gururajj77** [comment]
Hey @gi , could you please create a test story to test this fix?

**Comment by gi** [comment]
@Gururajj77 Sure thing! I added an action to be recorded in the `Filterable` story just like the current `onChange` action does.

**Review by guidari — APPROVED** [review]
LGTM! 
Thanks for doing that!

**Comment by gi** [comment]
@tay1orjones Do you have a minute to review this three-line change? 

It's blocking my team from upgrading past `@carbon/react@1.56`.

**Comment by gi** [comment]
The CI failure just requires that visual changes be reviewed/approved.

**Review by tay1orjones — APPROVED** [review]
Sorry for the huge delay on this, LGTM!

**Comment by gi** [comment]
> Sorry for the huge delay on this, LGTM!

@tay1orjones @guidari Thank you for the reviews and approvals! Can either one of you or other maintainer merge this? I don't think I can do that.

**Pull request merged**
