### PR TITLE
fix(data-table): remove extra padding on toolbar-action element

### LINKED ISSUE #3304: [TableToolbarSearch]: focus outline spacing is too tight
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The expanded `TableToolbarSearch` styles seem to be off:
 - The focus outline on the input spacing is really tight. 
 - The focus outline is interrupted between the input and the clear button

> Is this issue related to a specific component?
`TableToolbarSearch`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected the outline to match the hover color block outline

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.x

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Security Connect

## Steps to reproduce the issue

1. Go to the DataTable with toolbar [preview](http://react.carbondesignsystem.com/?path=/story/datatable--with-toolbar)
2. Click on the search icon in the toolbar
3. Notice the styling

## Additional information

image

image

### LINKED ISSUE #3305: [TableToolbarSearch] collapsed icon off center
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The hover styles for the TableToolbarSearch component make the icon appear off-center

> Is this issue related to a specific component?
`TableToolbarSearch`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
I expected the icon to be centered when the TableToolbarSearch has a hovering cursor

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.x

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Security Connect

## Steps to reproduce the issue

1. Go to the DataTable with toolbar [preview](http://react.carbondesignsystem.com/?path=/story/datatable--with-toolbar)
2. Hover over the search icon
3. notice the style issues

## Additional information
Kapture 2019-07-08 at 15 09 25

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3305 
Closes #3304 

#### Changelog

**Removed**

- removed extra padding on toolbar-action element that was causing issues identified in #3304 & #3305

### CODE REVIEW

**Comment by jendowns** [comment]
Hey so one thing I did notice was this fix highlights / draws attention to strange spacing between the "close" icon button in the search & then the rest of the search input field:

Screen Shot 2019-07-11 at 10 23 46 AM


How is that *supposed* to look? 🤔 No space at all? I could fix that really quick in this same PR.

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@jendowns I wonder if that border color is supposed to be a theme value? Definitely should fix before merging in haha, cc @designertyler if you have any thoughts on this.

**Comment by designertyler** [comment]
Yes, 100% that space should not be seen.

**Comment by jendowns** [comment]
Thanks @designertyler & @joshblack! I pushed an update that removes the space -- let me know what you think! 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Pull request merged**
