### PR TITLE
fix: respect max and min in NumberInput when using arrows

### PR DESCRIPTION
**Pull request by rudolpho1**
The arrow keys in the NumberInput allow users to step below the min and above the max value. This issue is fixed here.

#### Changelog

**Changed**

- Change the NumberInput to respect min and max values when using arrow keys

#### Testing / Reviewing

In order to reproduce the issue do the following:

- Create a NumberInput with min 0, max 100 and step 10

- manually enter the value 5 into the NumberInput

- click the arrow down.

actual behavior: the value of the NumberInput changes to -5

expected behavior: the value of the NumberInput changes to 0

### CODE REVIEW

**Comment by abbeyhrt** [comment]
Hi @rudolpho1! Thank you for taking the time to contribute. We are already addressing the issue with min/max not being respected as a part of an overhaul of NumberInput, here's the related issue: #2477, and we're taking a different approach UX-wise to address this problem. In the future, before creating a PR, could you open an issue with the problem you ran into? It would be really helpful for us so we can confirm the problem and make sure that no duplicate work is being done 👍

**Review by asudoh — COMMENTED** [review]
Hi 👋 thank you for jumping in! Could you please fix the logic at https://github.com/carbon-design-system/carbon/blob/a5f960e80a73ce9bfd5c1f226c3edc0123122854/packages/react/src/components/NumberInput/NumberInput.js#L221-L222 rather than adding logic? Specifically, we need to ensure that the event handler won't run if the value shouldn't be changed.

**Comment by abbeyhrt** [comment]
@rudolpho1  you can ignore my previous comment! I interpreted the arrows as the arrow keys, not the increment and decrement buttons.

**Comment by rudolpho1** [comment]
@asudoh changing the conditional instead of the logic would mean that if the current value is 5 and you hit the decrement button the value would still be 5. But my expectation would be that it changes to the lowest possible value i.e. 0. With my logic, it is correct that the change handler fires, because the value does in fact change. If the current value is already the min (or max) value, then the conditional would already be false and nothing would happen and no event would be fired. So, I think the behaviour is correct this way. What do you think?

**Review by asudoh — APPROVED** [review]
OK makes sense - Thank you for your additional explanation @rudolpho1!

**Review by emyarod — COMMENTED** [review]
looks good to me, would you mind adding/refactoring the existing tests for these scenarios (trying to increment past `max` or decrement below `min`)?

**Review by emyarod — APPROVED** [review]
this looks good to me but I just requested some testing for core component features since this seems like a common scenario

**Review by joshblack — APPROVED** [review]

**Pull request merged**
