### PR TITLE
fix(toggle): make props.labelText optional

### LINKED ISSUE #12999: [Bug]: Toggle storybook component needs better doc for hideLabel & consideration to not require aria-labelledby be used in conjuction with it.
### Package

@carbon/react

### Browser

Chrome

### Package version

11.21.0

### React version

any

### Description

The new functionality of `hideLabel` in `@carbon/react: "1.21.0` isn't documented very well.  For example, when I set `hideLabel={true}` I was expecting it to hide the label right away but it did not. Rather setting it to `true` put the `labelText` on the side of the toggle & when `hideLabel={false}` the label was on top of the toggle (see screenshot below).
image

Only after discussing internally, was it learned that for the Toggle's label to truly be hidden it requires `hideLabel={true}` AND that the `aria-labelledby` attribute be set properly (see screenshot below).
image

So the ask on this one is to see if we can better document the storybook's `hideLabel` and `aria-labelledby` props so that it is clear that in order for `hideLabel` to trigger it requires that the `aria-labelledby` prop also be set. Here's a screenshot of the current toggle storybook doc.
image

NOTE: I still think it might worthwhile to consider simplifying things and simply make `hideLabel` work without being tied to `aria-labelledby`.  The reason being is that the `for` attribute on the label can also be used to tie a label to a `Toggle` component and that should be A11Y compliant as well.  So by requiring `aria-labelledby` be used in conjunction with `hideLabel` it seems to not be supporting the alternate `for` attribute with the label. (see below for an illustration)
image

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Reproduction/example

https://stackblitz.com/edit/github-ccn2fg-gw95df?file=src/App.jsx

### Steps to reproduce

Have a look at the stackblitz and see that while it is a valid Toggle with the label specified separately the `hideLabel={true}` doesn't actually hide the label unless the `aria-labelledby` prop is used on the `Toggle` component.

The [Toggle storybook doc ](https://react.carbondesignsystem.com/?path=/docs/components-toggle--small-toggle)should be updated to mention this or simply remove the requirement that the `aria-labelledby` prop be also used.

image

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by janhassel**
Closes #12999 

#### Changelog

**New**
- Added "with accessible labels" story to demonstrate how to use the Toggle component

**Changed**

- `props.labelText` is no longer required
  - The prop docs have been updated to inform the user about the appropriate ways of using this component

#### Testing / Reviewing

As per https://github.com/carbon-design-system/carbon/issues/12999#issuecomment-1422643411
- `<Toggle labelText="Label" />`
  - The label is rendered on top
  - `.cds--toggle__label` is a `<label>` element with its `for` attribute set to the toggle's id
  - Side labels ("on" / "off") are rendered
- `<Toggle labelText="Label" hideLabel />`
  - The label is rendered on the side instead of "on" / "off"
  - `.cds--toggle__label` is a `<label>` element with its `for` attribute set to the toggle's id
  - `.cds--toggle__label-text` is visually hidden but still in the a11y tree
- `<Toggle hideLabel aria-labelledby="external-id" />`
  - The `<button>` receives the `aria-labelledby` attribute
  - `.cds--toggle__label` is a `<div>` element
- `<Toggle hideLabel />`
  - `.cds--toggle__label` is a `<div>` element

### CODE REVIEW

**Comment by tw15egan** [comment]
@janhassel I noticed that we're getting this violation in the storybook
Screenshot 2023-03-02 at 10 57 45 AM

This violation is already present in the current storybook, so it's not a regression, but I wanted to know if there was any way to address this since it seems related to these changes.

I could resolve all but 1 of the violations in the example by changing the `button` on `L101` to `aria-labelledby={ariaLabelledby ? null : id}`, but I was wondering about your thoughts on this issue. We can also roll this into a separate PR / Issue. The rest of the changes in this PR look great 👍🏻

**Comment by janhassel** [comment]
@tw15egan I think we talked about this presumedly false positive of the a11y checker last year in this PR: https://github.com/carbon-design-system/carbon/pull/11972#issuecomment-1219235336

**Comment by tw15egan** [comment]
@janhassel thanks for reminding me! 🙃

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
