### PR TITLE
fix(tabs): adjust focus outline size

### LINKED ISSUE #2073: IE11: Tab focus outline covers text of next tab
> Describe in detail the issue you're having.

The focus outline in IE11 appears to be too big.

> Is this issue related to a specific component?

Tabs

> What did you expect to happen? What happened instead? What would you like to see changed?

Here's IE11:

image

Here's Chrome (expected):

image

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

v10

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #2073.

Note that it's still slightly big, due to usage of `outline-offset` that is not supported by IE.

#### Changelog

**Changed**

- A change to make a tab item a flex box.

#### Testing / Reviewing

Testing should make sure our tab component is not broken.

### CODE REVIEW

**Comment by elizabethsjudd** [comment]
This changed the design.  Based on the issue the focus outline still had the wider border on the base of the tab item. Now that border disappears.  Was this intended?

**Comment by asudoh** [comment]
Hi @elizabethsjudd not sure where your comment came from, but let me share what this PR achieves - Original (`master`):

image

This PR:

image

IE with this PR:

image

**Comment by elizabethsjudd** [comment]
Thanks @asudoh for the updated designs. I was looking at @mattrosno's screen shots in this comment/issue: https://github.com/IBM/carbon-components/issues/2073#issue-420155504 where in Chrome (the desired design) had the wider border on the bottom.

**Review by jnm2377 — APPROVED** [review]
LGTM! Thanks for fixing this!

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Pull request merged**
