### PR TITLE
fix(button): incorrect focus color for tertiary button on dark themes

### PR DESCRIPTION
**Pull request by j1mie**
The tertiary button renders white text `$text-04` when focussed, which makes it illegible when using dark themes (white-on-white)

**Screenshot**

Screenshot 2019-10-04 at 13 03 18

**Changed**

- Uses `$inverse-01` rather than `$text-04` in tertiary button
- Removes `$active-primary` override which was rendering incorrect active colors

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
the fix looks good to me, pending visual review

**Review by aledavila — APPROVED** [review]
looks good

**Review by jillianhowarth — CHANGES_REQUESTED** [review]
Looks good! Please update the color token in the tertiary button color table on the Carbon website as well (https://www.carbondesignsystem.com/components/button/style/)
Screen Shot 2019-10-04 at 12 46 29 PM

**Review by dakahn — APPROVED** [review]

**Comment by j1mie** [comment]
@jillianhowarth https://github.com/carbon-design-system/carbon-website/pull/453

**Review by jillianhowarth — APPROVED** [review]
Thanks for updating the site!

**Review by designertyler — APPROVED** [review]

**Pull request merged**
