### PR TITLE
delete 16 px add*

### PR DESCRIPTION
**Pull request by chrisconnors-ibm**
removes bespoke 16 icons for add, they'll scale down from the 32s from now on

### CODE REVIEW

**Comment by chrisconnors-ibm** [comment]
This PR will require regeneration and publication of the  **IBM Icons(16px, 20px)** Sketch Library

**Review by dakahn — APPROVED** [review]

**Comment by chrisconnors-ibm** [comment]
made adjustments to 32/add.svg, 32/add--alt.svg, 32/add--filled.svg, 32/subtract--alt.svg and 32/subtract.svg so they will evenly divide when scaled down to 16 size

**Comment by chrisconnors-ibm** [comment]
@conradennis, have a look at 32/add.svg, 32/add--alt.svg, 32/add--filled.svg, 32/subtract--alt.svg and 32/subtract.svg (adjusted so they will evenly divide when scaled down to 16 size) and their 16 px counterparts on a @1x display. They'll look great on a retina.

here's the previews: 
https://deploy-preview-5175--carbon-elements.netlify.com/icons/examples/preview/#32%2Fadd--alt%20(Downsized%20to%2016)

https://deploy-preview-5175--carbon-elements.netlify.com/icons/examples/preview/#32%2Fadd--filled%20(Downsized%20to%2016)

https://deploy-preview-5175--carbon-elements.netlify.com/icons/examples/preview/#32%2Fadd%20(Downsized%20to%2016)

https://deploy-preview-5175--carbon-elements.netlify.com/icons/examples/preview/#32%2Fsubtract--alt%20(Downsized%20to%2016)

https://deploy-preview-5175--carbon-elements.netlify.com/icons/examples/preview/#32%2Fsubtract%20(Downsized%20to%2016)

**Review by aagonzales — APPROVED** [review]
They look like they're rendering as expected with this method. Not sure if we want to wait for @conradennis to give the 👍 as well on this issue.

**Review by laurenmrice — APPROVED** [review]

**Comment by conradennis** [comment]
👍look good to me

**Comment by joshblack** [comment]
Going to update CI real quick so the build passes!

**Review by joshblack — APPROVED** [review]

**Pull request merged**
