### PR TITLE
fix(multi-select): update experimental UI

### LINKED ISSUE #1648: v10 Multi-select dropdown Tag (design change)
We need a couple of changes to the tag inside of the multiselect dropdown.

Changes include:
-Text color/style to call new tokens
-Icon to call new token
-Background color to call new token
-New hover interaction on icon

@ibm/carbon-developers

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #1648.

#### Changelog

**New**

- Demo preview for list box, as it requires certain styling in the container to look well.
- Hover styling for close button next to selection count.

**Changed**

- Background/foreground colors for selection count UI.
- Icon the close button next to selection count.

**Removed**

- Custom width/height style for the close button next to selection count, as we are using fixed size icon for experimental.

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
🙌

**Review by aledavila — APPROVED** [review]
lgtm

**Comment by asudoh** [comment]
@laurenmrice Would you have a chance to review this...? Thanks!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
#### General question:
-Are we going to be previewing the closed and open version here? We should probably just preview the closed and the user can open and interact with it.

-Eventually there needs to be a Multiselect option with a label above it.

#### Multiselect (no label)
-After a discussion with Mike and Sadek during a component review, we came to the conclusion that we are taking off the Selected background color of the top row when the dropdown is open. Instead the background will be color field-01 (#F3F3F3) and a line underneath at 1px at color ui-03 (#DCDCDC).
artboard

-The text in the top bar should not be Semibold, it should be Regular.

-The text color for the Options in the dropdown need to be color text-02 (#565656) by default. When the get a hover, then the text color changes to text-01 (#171717)

-Sometimes when hovering over a row the rule lines are still exposed for that row. We need to only show the hover box and omit the rule lines for that row to get a clean edge.
screen shot 2019-02-14 at 8 48 02 am

-The hover state for the close icon in the tag is distorted. Ive outlined some specs for spacing
artboard copy

#### Multiselect (Inline)
-Same comments above about tag, no selected state when open, and rule lines exposed on hover, and no Semibold label.
-There should not be an underline underneath the label.

-Make sure the label background lines up with the checkboxes below it, right now it aligns to the text.
screen shot 2019-02-14 at 9 15 46 am

-When the dropdown is open, the top row tag and label hang too low. Here are some specs to get it aligned in the center.
artboard copy 2

**Comment by asudoh** [comment]
@laurenmrice Thank you for reviewing! I think I addressed all (or at least, most) of your comments. For your biggest question, multi select currently is a React-only component and thus the demo in vanilla dev env does not contain the interaction. I created a staging link with React storybook which may be an easier review: http://carbon-storybook-spectrohelioscopic-inculcator.mybluemix.net/?selectedKind=MultiSelect&selectedStory=default

**Review by laurenmrice — CHANGES_REQUESTED** [review]
The background color of the the top bar changes to the selected-ui color when the dropdown is open and hovering on items in the dropdown. it Should always remain field-01 with the rule underneath instead of becoming selected-ui color.
screen shot 2019-02-18 at 10 31 37 am

The rows that have a checkbox selected should also have a persistent background color of token selected-ui (#DCDCDC) and the text should be color text-01 (#171717)
screen shot 2019-02-18 at 10 46 54 am


The hover background color of rows should be hover-ui (#E5E5E5) I think right now it is the selected-ui color?

When selecting Option 2 first, Option 2 jumps to the top of the list in the dropdown, it should stay where it is in the dropdown list and should not move.
screen shot 2019-02-18 at 10 48 31 am

**Comment by asudoh** [comment]
@laurenmrice Addressed the first three, can be see at [the same staging link](
http://carbon-storybook-spectrohelioscopic-inculcator.mybluemix.net/?selectedKind=MultiSelect&selectedStory=default).

Given the last one is about how our React code works, I created IBM/carbon-components-react#1897 to track the effort to fix this. Thanks!

**Comment by asudoh** [comment]
@laurenmrice Do you have any remaining comments...? Thanks!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Just two more things-
- We need to change the behavior when selection options in the dropdown to not jump to the top . They need to stay in place.
screen shot 2019-02-22 at 9 23 39 am

- Also there is this slight line that comes up on hover or selections that shouldn't be there.
screen shot 2019-02-22 at 9 21 06 am

**Comment by asudoh** [comment]
Thank you for pointing these out @laurenmrice! Let's use a separate issue (IBM/carbon-components-react#1897) for the former. Fixed the latter and can be seen at [the same staging link](
http://carbon-storybook-spectrohelioscopic-inculcator.mybluemix.net/?selectedKind=MultiSelect&selectedStory=default).

**Review by laurenmrice — CHANGES_REQUESTED** [review]
When the dropdown is open, the top row is still getting a selected color. It needs to be background field-01 and have an underline of ui-03
screen shot 2019-02-25 at 1 27 23 pm

**Comment by asudoh** [comment]
Hi @laurenmrice the darker background color seems to be associated with hovering over, instead of the open state. That makes me wonder if the hover over color should be eliminated, or you are suggesting the hover over color should be gone as soon as the menu is open - What do you think? Thanks!

**Comment by asudoh** [comment]
Let me merge this as there is only one open review comments (created #1964 for this). Thank alot @laurenmrice for your patient review!

**Pull request merged**
