### PR TITLE
docs(tooltip): use Button instead of Information icons in stories

### PR DESCRIPTION
**Pull request by tay1orjones**
A small detail of https://github.com/carbon-design-system/carbon/issues/12921, https://github.com/carbon-design-system/carbon-design-kit/issues/721, https://github.com/carbon-design-system/carbon/pull/15887 that was missed, this PR modifies the Tooltip storybook examples to use a button as the trigger to avoid [confusion](https://ibm-studios.slack.com/archives/C0M053VPT/p1721399372450199?thread_ts=1709691755.992749&cid=C0M053VPT) stemming from information icons.

Related to https://github.com/carbon-design-system/carbon-website/issues/3956

#### Changelog

**Changed**

- Tooltip stories now use SquareOutline

**Removed**

- Removed an invalid Tooltip example from FormLabel stories, it already had a valid Toggletip example alongside it

#### Testing / Reviewing

- Tooltip stories should function and have no regressions

### CODE REVIEW

**Review by wkeese — COMMENTED** [review]
These changes look like an improvement to me, but I think the other issue (according to Michael Gower) is to update https://carbondesignsystem.com/components/tooltip/usage/#standard-tooltip to say that "standard tooltips" should be displayed using Toggletip.  Right now it says:

> If the content is essential for the user to interpret concerning their workflow, use a [toggletip](https://carbondesignsystem.com/components/toggletip/usage/) for this information instead.

Actually it seems like you should replace all the text to say "Informational tooltip" wherever it now says "Standard tooltip"?

**Comment by tay1orjones** [comment]
@wkeese Cool, yeah this is just the actionable piece for the storybook since the website repo is separate.

@kingtraceyj could you share the issue that is tracking the website updates you [mentioned](https://ibm-studios.slack.com/archives/C0M053VPT/p1709739388875479?thread_ts=1709691755.992749&cid=C0M053VPT)?

**Review by guidari — CHANGES_REQUESTED** [review]
Hey @tay1orjones 
The `SquareOutline` is not defined in the import, I guess that's why the stories are all blank https://deploy-preview-17006--v11-carbon-react.netlify.app/?path=/story/components-tooltip--playground

The FormLabel looks good to me!

**Review by guidari — DISMISSED** [review]

**Review by guidari — COMMENTED** [review]
@tay1orjones The stories doesn't have the `<Information />` icon anymore.


I added the `<Information />` back in to test the code locally and the focus looks weird.

```
<Tooltip align="bottom" label={label}>
      <Button className="sb-tooltip-trigger">
        <Information />
      </Button>
    </Tooltip>
```
Screenshot 2024-08-15 at 16 05 05

**Comment by tay1orjones** [comment]
@guidari sorry for the back and forth here, I need to update the tooltip styling and correct a few other things. I think that specific focus ring issue could be solved by adding `hasIconOnly` to the `Button`.

**Comment by alisonjoseph** [comment]
@tay1orjones I think you'll need to remove the custom styles to fix the weird display of the button in the Tooltip story. `/components/Tooltip/story.scss` (lines 24-40)

**Review by guidari — APPROVED** [review]
LGTM!

**Review by kennylam — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
