### PR TITLE
feat(data-table-v2): add expand styles

### PR DESCRIPTION
**Pull request by jnm2377**
Ref: #1303 

Adds expand styles 

**New**
- adds `div.#{$prefix}--child-row-inner-container` inside child row `td` to transition height for motion

**Changed**
- doesn't use js to hide/show the child row anymore

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hey I know @designertyler is the most familiar with data table so I'd defer to him if these comments are right, but I noticed a few things: 
- Primary button should be default height, to fill the gap and same height as the action bar
image
- Hovering a row works, but clicking a row doesn't expand nor select. Should probably be expanding the row. If not, hover should at least show the overflow menu? Having a hover state but no interaction afterwards feels wrong. 
- Expanded content should align with text in first col
image

**Comment by designertyler** [comment]
Thanks @shixiedesign I'm actually running through these with Josefina right now 👍

**Comment by jnm2377** [comment]
@shixiedesign 
> * Primary button should be default height, to fill the gap and same height as the action bar

I haven't added any styles for toolbar/batch actions. This is just the table styles.

> * Hovering a row works, but clicking a row doesn't expand nor select. Should probably be expanding the row. If not, hover should at least show the overflow menu? Having a hover state but no interaction afterwards feels wrong.

The expand click functionality being on the svg button only is an existing functionality from v9.  If this is something we're considering a bug, I think maybe it should be something we should update later since it wouldn't require breaking markup changes, just adding js. Reason being, we still have a few more PRs before release this Friday and I think that's a bigger priority than this since it's an existing functionality. Also this example doesn't have an overflow menu to show on hover.

> * Expanded content should align with text in first col

We're syncing up about this now 👍

**Comment by asudoh** [comment]
@shinytoyrobots @alisonjoseph `v10` feature completion item

**Review by asudoh — APPROVED** [review]
LGTM 👍 from the code perspective - Thanks @jnm2377!

**Comment by designertyler** [comment]
- [x] The child section of a selected row should be gray 20 `#dcdcdc`. Right now the child area is not changing on hover.
Mar-27-2019 08-36-43


- [x] Row height should be 48px including the 1px border. It's currently 50px including the 1px border.
Screen Shot 2019-03-27 at 8 42 13 AM

Screen Shot 2019-03-27 at 8 49 28 AM

- [x] The divider for the parent/child content should stop 48px from the left border. It currently stops at 40px.
Screen Shot 2019-03-27 at 8 52 54 AM

**Review by dakahn — APPROVED** [review]
Looks good 👍🏽

**Review by designertyler — APPROVED** [review]
Looks good!

**Review by lovemecomputer — APPROVED** [review]
yayyy! great work

**Comment by designertyler** [comment]
I'm still getting the issue where the border remains after I expand and collapse the row.

Mar-27-2019 16-45-02

**Comment by asudoh** [comment]
@jnm2377 Brought in code from #2220 to here ([the commit](https://github.com/IBM/carbon-components/pull/2209/commits/70b53e81808eae8d02c516752d8fff946469f3ef)), please don't hesitate to revert it if you think it shouldn't have been done - Thanks!

**Review by emyarod — APPROVED** [review]
great work! just want to make sure that this is the intended behavior for the expand button:

Kapture 2019-03-28 at 8 59 06

the clickable area is larger than the SVG but the cursor does not change on hover on the extended area

**Comment by jnm2377** [comment]
Thanks for helping out with this @asudoh. We actually need those conditionals for the v10 data table because it's not supposed to be removing the child rows from the dom. We're hiding it with css now so that it can be transitioned and given motion, so I'm gonna add those back in. 👍

**Comment by jnm2377** [comment]
For reviewers, see below visual for reference:

Screen Shot 2019-03-28 at 1 19 23 PM

**Review by designertyler — APPROVED** [review]
🎉

**Pull request merged**
