### PR TITLE
(feat|fix)Updating breakpoints to have unique file, support up|down|only functi…

### PR DESCRIPTION
**Pull request by DusanMilko**
…onality and match grid breakpoints. Added functionality to breakpoints and made consistent with gird-breakpoints.

#### Changelog

**New**

- breakpoints now support up|down|only functionality
- breakpoints match grid breakpoints (eventually should use same one)

**Changed**

- moved breakpoints to separate file

Any and all feedback is welcome

### CODE REVIEW

**Comment by joshblack** [comment]
Hi @DusanMilko! 👋 Thanks for taking the time to create this PR 😄 Before committing other changes, do you have an issue or reference that details the motivations behind these changes?

**Comment by DusanMilko** [comment]
@joshblack Currently there was a divide between breakpoints and grid-breakpoints. Breakpoints also did not match up with the mentioned breakpoints in docs, leading breakpoint include to use wrong data. This should ideally use 1 map accross the whole project not 2. I felt that breakpoints should be its own file and more descriptive than just 'layout'. Also I added the functionality to reference down(max-width) or only(min - max) in breakpoint allowing the dev to do more than just min-width.

**Comment by asudoh** [comment]
Thanks @DusanMilko for explaining the background! One question before I dig into the details - Did you simply try to fix our Sass design defect you have in your mind, or is your application affected negatively by our breakpoint code? I'm asking this especially because this PR contains a breaking change to our `breakpoint()` mix-in.

**Comment by DusanMilko** [comment]
@asudoh its a mix of both, it does affect my current application but is also a defect in the breakpoint mixin. 

Design Defect:
- lack of max-width, only(min+max) support
- 2 breakpoint maps that use very similar sizes, 500px in one 576px in the other, rest of sizes are the same (should be one map)

Affect to my application
- want to replace manual use of max + only use in my application with breakpoint mixin
- want to use breakpoint mixin with same sizes in grid-breakpoint map so when grid changes other aspects of application update at same breakpoint.

The current breakpoint mixin is very limiting (lack of max-width, and min+max). The current project I use has these manually specified. Would prefer to tap into the breakpoint mixin for these situations.  The current breakpoint mixin is fixed to use a specific map so the only solution is in my project to create my own copy of the map and modified mixin which is duplicative.

My update still uses min-width as default like old breakpoint mixin, I foresee 2 possible breaking changes. 1) need to import breakpoint.scss 2) is the new names in the breakpoint map(xs,sm,md etc instead of bp--xs--major). My changes do not merge the 2 breakpoint maps but just makes them the same. It would be good to consolidate them (could be included in this update? Appreciate any feedback or contributions to this update)

**Comment by asudoh** [comment]
Thanks @DusanMilko for your explanation. My knee-jerk reaction to your latter two bullets is it'd be best to maintain your proposed `@mixin breakpoint` in your own repo for now. One reason is the nature of breaking change as you described (very well). Another reason is that your proposed one does much more than existing one (we tend to do MVP to keep things flexible to consuming applications).

Given one of your concern is synced breakpoint between components/grid, it'd be great you can sync up with @joshblack, who is working on [next gen of grid](https://github.com/IBM/carbon-elements/pull/33), on this. Also great to understand why getting breakpoints in sync between components/grid is important for applications - My apologies if you think it's obvious, but trying to understand it well enough before giving the notion a green light.

Another of your concern seems `up`/`down` support, but haven't been able to find out any explanation in your PR comment or in your code. My apologies if I'm missing something, but otherwise, great to have more details. Thanks!

**Comment by DusanMilko** [comment]
@asudoh The ability for a breakpoint mixin to support max width and only width feels like MVP to me though. The proposed changes bring in functionality that is core to @media and missing in the mixin. The current mixin only supports up(min-width) meaning you can't currently do max-width or min+max meaning you can't target down or a specific breakpoint only. For example, a use case for only is where styles for breakpoints sm, md and xl are same but styles for lg are different so you can use the min+max to target only lg. Adding in support for max and only makes the mixin even more flexible for developers. I know these use cases may be uncommon but should be supported.

I will sync up with @joshblack about synced breakpoints. The easiest example I can give is that in the current grid, the grid changes at a breakpoint of 576px(labeled as sm). If I want to have my component do other changes at the same breakpoint I ideally should be able to reference the same label in the breakpoint mixin and get the same size. Currently, the breakpoint mixin uses different labels and sizes that don't match up. The closest one is "bp--xs--major: 500px" which isn't sm or 576 and bp--sm--major is 768px which in the grid map is md. This is very confusing and disconnected. We should use 1 breakpoint map accross all aspects for consistency and reusability.

**Comment by joshblack** [comment]
Definitely can understand the limitations of the existing code, it was never meant to be too sophisticated. Will echo @asudoh and say that we should limit contributions for this part of the codebase to bug fixes. I think you have a great point that the breakpoints are not in sync and we should definitely fix this 👍 

For additional functionality, I think these are things we'd want to leave in the hands of product teams, at least for the moment. With our push towards our X release later on in the year we are trying to minimize change as much as possible which is one of the larger motivations behind this, unfortunately.

As @asudoh mentioned, we are trying to see if we can fit in a more functional version of grid over in https://github.com/IBM/carbon-elements. Feel free to make a feature request issue over there if you feel like this functionality is essential for products teams and we can definitely take a look!

**Comment by DusanMilko** [comment]
@joshblack this feature would make breakpoints more manageable and reusable in my current project. I will take a look at carbon-elements. I don't see carbon-elements being used in this project, is it planned to be incorporated at some point?

Syncing up the 2 breakpoint maps is the part of my change that may cause any breaking changes. Do you have an idea of how they could be synced up without any issues?

**Comment by joshblack** [comment]
Definitely understand the value add, although for now I think we would want that to be in products versus in `carbon-components` 👍 

For the breaking change part, that's a good point. Typically for breaking changes we introduce them in our big releases. The next one is Carbon X in December and we can get these changes in for that, most likely 😄 Let me know!

**Comment by DusanMilko** [comment]
@joshblack Awesome, I'll start contributing to Carbon X. Is there a branch or something for Carbon X for me to send my p/r's? or how do I contribute some of my breaking changes to the next big release?

**Comment by joshblack** [comment]
Thanks for responding @DusanMilko! Right now, all the work related to grid is shifting over to https://github.com/IBM/carbon-elements

We're actually working this sprint on finishing up most of the packages in this project, so I think the best next action would be to make issues on the project describing what kind of feature sets you're looking for. Then we can go over them and see if they'd be a good fit. If they seem like a great addition, then we'd ask for some help from you for implementation if you'd be up for it 😄

**Comment by alisonjoseph** [comment]
Closing this for now as all new grid functionality is being handled in carbon-elements.

**Pull request closed without merging**
