### PR TITLE
Progress indicator focus, hover, active states; and text color

### PR DESCRIPTION
**Pull request by lovemecomputer**
addresses first comment in this issue thread: https://github.com/IBM/carbon-components-react/issues/2071#issuecomment-475410016

- all states have `text-01` color
- focus state is visually bottom border only
- transitions so the border looks nice :)

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] Hover needs to have `link-01` color text and rule underline. 

- [x] Focus state needs to have `link-01` color text and rule underline.

- [x] The active state needs to be `interactive-01` color text and rule underline.

**Comment by lovemecomputer** [comment]
@laurenmrice thanks! changes applied

**Review by laurenmrice — APPROVED** [review]
Looks good to me ! 👍

**Review by aledavila — APPROVED** [review]
lgtm

**Pull request merged**
