### PR TITLE
fix(ListBox): update focus states for listbox components

### LINKED ISSUE #15698: [Dropdown: Combobox & Multiselect]: Focus state dev implementation
Closes [#768](https://github.com/carbon-design-system/carbon-design-kit/issues/768)

## The problem

We recently have updated downshift which has resulted in changes to our focus states with the new guidance of [1.2 combo box change](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/). 
- Update Dropdown, Combobox and Multi-select (parent's and child's) focus states in the All themes Figma library to reflect these changes for both fixed and fluid styles.
- Add the missing state also 

## The solution

Ref : [Figma branch link](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/branch/YoOEBjLBbiZbGsU1C3AMXf/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-308516&mode=design&t=XODtWWTjax6UXS7m-0)

_To update:_

---

> **Fluid**
> - Remove the hover state from the Dropdown - Combo box - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291111&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291154&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> image

---

> **Fluid**
> - Add focus and hover state in the Dropdown - Multi-select - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291471&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291592&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> - [ ] The focus state for the child will be on the first selected option.
> image

> **Filterable - Multi-select**
> - Add focus state in the Dropdown - Multi-select - [Default](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291471&mode=design&t=2mhEzQaVO3ACmfuM-4) & [Fluid](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-291592&mode=design&t=2mhEzQaVO3ACmfuM-4)
> - [ ] The focus stroke or border of the parent state will be 1 px, while the stroke of the child state will be 2 px.
> - [ ] The focus state for the child will be on the first selected option.
> image

---

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15698

Updates focus states for `Listbox` components, as weel as setting focus to the first item in `MultiSelect` and `FilterableMultiSelect`

#### Changelog

**New**

**Changed**

- Focus state when `ListBox` component is open is now just `1px`
- Focus on first element when menu is opened for `MultiSelect` and `FilterableMultiSelect`
- Updated some tests to account for new behavior

#### Testing / Reviewing

Ensure focus border on `ListBox` components goes to `1px` when the menu is open, and that the first item is focused when the menu opens with keyboard

### CODE REVIEW

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi @tw15egan, have you modified the focus state for dropdowns and comboboxes? 🤔 
I'm not certain if it's a bug, but I'm unable to view the updated focus state in the multi-select and filterable multi-select options...

**Comment by tw15egan** [comment]
@Kritvi-bhatia17 Yes, they have all been updated and I am able to see the changes when looking at the latest deploy preview: 
- [ComboBox](https://deploy-preview-15980--v11-carbon-react.netlify.app/?path=/story/components-combobox--default)
- [Dropdown](https://deploy-preview-15980--v11-carbon-react.netlify.app/?path=/story/components-dropdown--default)  
- [Multiselect](https://deploy-preview-15980--v11-carbon-react.netlify.app/?path=/story/components-multiselect--default)
- [FilterableMultiselect](https://deploy-preview-15980--v11-carbon-react.netlify.app/?path=/story/components-multiselect--filterable)

**Comment by Kritvi-bhatia17** [comment]
Hi @tw15egan,
- In instances where both the parent and child have a focus state, there shouldn't be any gap between them. 
Screenshot 2024-03-26 at 2 16 47 AM
- I've reached out to Michael to clarify a few details and documented everything in the comments.
https://github.com/carbon-design-system/carbon/issues/15698#issuecomment-2018869183

**Comment by Kritvi-bhatia17** [comment]
Heyy @tw15egan! Could you please add Michael and Lauren as reviewers once you've updated everything?

**Comment by tw15egan** [comment]
@Kritvi-bhatia17 changes have been made and the deploy preview should be updated in a few minutes 👍🏻

**Comment by mbgower** [comment]
The focus handling on dropdown and combobox looks good.

This may not have been introduced here, but I was a little surprised to see the list in combobox wrapping around (i.e., when I got to the bottom item, it wrapped to the top item). This isn't a menu, so I was a little surprised to see that happen. I would call that atypical for this kind of function. Like I said, if that wasn't introduced in this change, this is probably a new issue to explore.

**Review by tay1orjones — APPROVED** [review]

**Comment by mbgower** [comment]
I had a look at the pre-existing version of this component and that 'wraparound' keyboard is doing it there too, so it’s not related to the changes here.
I think I would treat this an a new issue. I don’t think this is necessarily a failure, but I do think it warrants some discussion: when should and shouldn’t a dropdown list have wrap-around keyboard interaction from the bottom to the top item in a dropdown list?

**Comment by Kritvi-bhatia17** [comment]
Damn, nice point @mbgower! I totally agree with you and will create a separate issue for that.

**Review by Kritvi-bhatia17 — APPROVED** [review]
Awesome work, @tw15egan! You nailed those changes super quickly. ⚡️

**Review by laurenmrice — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
looks good to merge!

**Pull request merged**
