### PR TITLE
feat: add readonly dropdown

### LINKED ISSUE #12432: [Read-only inputs]: Dropdown implementation
### Reference #12241 

image

image

#### Acceptance Criteria

- [ ] Coded component in `/package/react`
- [ ] Add a prop for read-only, add styles for said prop
- [ ] Controls for each state in playground
- [ ] Default story for easy copy and paste
- [ ] RTL tests for the read-only class on the prop

### PR DESCRIPTION
**Pull request by lee-chase**
Contributes to #2177

Closes #12432 

Adds the read-only feature to the Dropdown component.

#### Changelog

**Added**

- Adds readOnly property to Dropdown and functionality
- Adds test for read-only Dropdown
- Adds styling for read-only Dropdown.

#### Testing / Reviewing

Reviewed the result in Storybook and a added read-only test.

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
LGTM! 

Looks like you have a couple merge conflicts, and one super small thing, would be nice to add
```

  readOnly: {
    control: {
      type: 'boolean',
    },
    defaultValue: false,
  }, 
```
to the Playground.argTypes in storybook

**Comment by lee-chase** [comment]
> LGTM!
> 
> Looks like you have a couple merge conflicts, and one super small thing, would be nice to add
> 
> ```
> 
>   readOnly: {
>     control: {
>       type: 'boolean',
>     },
>     defaultValue: false,
>   }, 
> ```
> 
> to the Playground.argTypes in storybook

The readOnly prop appears in the playground @alisonjoseph but has no default. I'm not sure adding a default value to an optional property would be correct. If anything Storybook should do allow an optional property to be reset to `undefined`.

**Review by tw15egan — APPROVED** [review]
LGTM pending design review 👍 ✅

**Comment by aledavila** [comment]
@thyhmdo if you could review this when you have time please !

**Review by aledavila — APPROVED** [review]

**Review by thyhmdo — APPROVED** [review]
Looks good.

**Pull request merged**
