### PR TITLE
feat(inputs): fixed old pr and added inputs and colors work

### PR DESCRIPTION
**Pull request by marijohannessen**
## Overview

Ref https://github.ibm.com/carbon/issues/issues/613
Ref https://github.ibm.com/carbon/issues/issues/446
Ref https://github.ibm.com/carbon/issues/issues/545
Resolves https://github.com/carbon-design-system/carbon-components/issues/690

This PR is a combination of https://github.com/carbon-design-system/carbon-components/pull/711 and https://github.com/carbon-design-system/carbon-components/pull/710. 

### Added

- `$field-02` and `$inverse-02`
- V2 and light version files for all the input fields.

### Changed

- Updated `Dropdown` hover colors
- Changed components using `$ui-05` to `$ui-04`
- Changed components using `$ui-04` to `$ui-03`
- Changed components using `$ui-03` to `$ui-02`
- Changed inputs using `$field-01` to `$field-02`
- Changed non-placeholder text using `$text-03` to `$text-02`

### CODE REVIEW

**Comment by marijohannessen** [comment]
@alisonjoseph 's comment from the last PR:

The placeholder text shifts 1px over on the active state because of the border. Is this intended behavior? Fix could be to add 1px transparent border to the input. We can't use outline because of the IE/modal issue right?

Oh wait, is the border even supposed to be there?

**Comment by marijohannessen** [comment]
@alisonjoseph which component are you referring to?

**Comment by alisonjoseph** [comment]
@marijohannessen I just checked the PR and I'm not seeing it anymore. 😅 you can ignore that comment

**Comment by asudoh** [comment]
The new input design looks splendid!! Thanks @marijohannessen and @tw15egan for getting this implemented!

It’d be nice to have another eyes on the transactional modal and the pagination with the new design. Thanks!

**Review by tw15egan — APPROVED** [review]
🙌

**Review by alisonjoseph — APPROVED** [review]
Looks awesome 🎉

**Pull request merged**
