### PR TITLE
fix(ui-shell): add border bottom back to shell header

### LINKED ISSUE #6142: Regression: Header border disappeared
## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

> Describe in detail the issue you're having.

`bx-header` class had a border on it before and it was removed. This really makes a page look wonky.

Before (version 10.10.3)
image

After (latest)
image

Change in question:
https://github.com/carbon-design-system/carbon/commit/49e87c8e1e507c2a24075ad244e4a961f7db8d72#diff-f8c1a41d640bb6e6c4213525998e936eL30

> Is this issue related to a specific component?

UI-Shell

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would like to see the border back because without it everything looks really messed up.

> What browser are you working in?

> What version of the Carbon Design System are you using?

Had to revert from latest to 10.10.3

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM CustomerSuccess360

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6142

Adds back in border-bottom to UI Shell header 

#### Changelog

**Changed**

- Adds back in border-bottom to UI Shell header 

#### Testing / Reviewing

Ensure border-bottom shows up on UI Shell header

### CODE REVIEW

**Comment by laurenmrice** [comment]
I am not sure why there is not a react build loading ? but I can review once that is up

**Review by laurenmrice — APPROVED** [review]
Looks good to me, I see the border bottom in all stories. 👍🏻

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by joshblack — APPROVED** [review]

**Comment by virkt25** [comment]
ETA for this to be released?

**Pull request merged**
