### PR TITLE
feat: allow custom classnames for dropdown wrapper

### LINKED ISSUE #4321: [dropdown] Can't provide classname to wrapper
When positioning a drop down, the user is unable to over-ride or style the Dropdown wrapper. The className prop is used in an interior container, so targeting that class name is not helpful.

The developer should be able to provide a className that is a sibling of `bx--dropdown__wrapper`, however we only allow them to provide a sibling to `bx--dropdown`.

Screen Shot 2019-10-14 at 12 46 39 PM

### PR DESCRIPTION
**Pull request by vpicone**
Closes #4321

**New**

- `wrapperClassName` prop on Dropdown that is included in the `wrapperClasses` we provide.

### CODE REVIEW

**Comment by joshblack** [comment]
I'm definitely torn by this, by default our components should be setting the given className on the top-level node (but this one clearly isn't). Can we get around this in the interim by just using a custom wrapper over the component and targeting `> *:first-child`? Or an equivalent selector

**Review by joshblack — COMMENTED** [review]
Left a comment above

**Comment by vpicone** [comment]
@joshblack there's definitely ways to style around this (we do this in a few spots in the website, create handles to style unreachable carbon elements). For this component, if we're compiling a list of wrapper classes, we need to let users provide their own class there as well.

**Comment by vpicone** [comment]
Definitely should be a big priority for prop normalization/theming (no unreachable elements). If you'd rather punt for that effort we should probably start an issue to document those punts.

**Review by emyarod — APPROVED** [review]
I don't mind this as a temporary measure but yeah I would like to finally address the larger issue when we can. IIRC this was something we couldn't address during the v9 to v10 effort and has been postponed since earlier this year https://github.com/carbon-design-system/carbon/issues/2529

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @vpicone!

**Comment by joshblack** [comment]
> Definitely should be a big priority for prop normalization/theming (no unreachable elements). If you'd rather punt for that effort we should probably start an issue to document those punts.

@vpicone agreed, I went ahead and created an issue for this in: https://github.com/carbon-design-system/carbon/issues/4356

I think when we look at short-term gaps and us trying to address them, we should only supply options if there is no solution that exists in user-space. Otherwise, we end up with a case where folks may be using something to address a problem that we know of and will address in a future release, ultimately making the migration path more difficult as things are being removed.

**Review by joshblack — COMMENTED** [review]
Left a comment above, let me know what you think!

**Comment by vpicone** [comment]
@joshblack after thinking about it, introducing a new style anchor could make future migrations more difficult.

**Pull request closed without merging**
