### PR TITLE
Fixed icon password visibility in `FluidPasswordInput`

### LINKED ISSUE #16314: [Bug]: FluidTextInput has a bug with invalid and isPassword state
### Package

@carbon/react

### Browser

_No response_

### Package version

v1.55.0

### React version

18.02

### Description

Screenshot 2024-05-03 at 08 48 27

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/experimental-fluid-components-unstable-fluidtextinput--playground&args=invalid:!true;isPassword:!true

### Steps to reproduce

Switch to true the `invalid` and `isPassword` state 

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by guidari**
Closes #16314

Added classes to fix the button visibility postion when the `FluidPasswordInput` is Invalid.

#### Testing / Reviewing

- Go to `FluidPasswordInput`  and add an invalid prop to true.
- Make sure there is no regressions.

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Fluid looks great, but looks like this also changed the default styling. 

Screenshot 2024-05-17 at 1 06 22 PM

**Comment by guidari** [comment]
> Fluid looks great, but looks like this also changed the default styling.

Now it is working both components. @alisonjoseph 

Screenshot 2024-05-20 at 10 07 04

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
I'm still seeing some visual issues with invalid state, all other states and variants seem ok.

Screenshot 2024-05-20 at 12 57 27 PM

**Comment by guidari** [comment]
> I'm still seeing some visual issues with invalid state, all other states and variants seem ok.

@alisonjoseph 
Screenshot 2024-05-21 at 08 56 05

**Review by alisonjoseph — APPROVED** [review]
Looks good!

**Review by Gururajj77 — APPROVED** [review]
Looks Good!

**Pull request merged**
