### PR TITLE
chore: add build step to generate react docgen metadata

### LINKED ISSUE #4635: [React]: Some components are compiled so awkwardly they can't be processed by react-docgen
When we use class components w/ static class properties the resulting compilation is so wonky that it can't be processed by react-docgen for component demo work on the website. The website can only consume the 'compiled' package for generating react-docgen info, unlike storybook which can use the uncompiled source.

Refactoring the component from a class to a functional component solves this.

There might be other's with this issue that'll get discovered as we add the demo component to each page

- [ ] CodeSnippet

### PR DESCRIPTION
**Pull request by vpicone**
Closes #4635 

**New:**
- BABEL_ENV `docgen`
	- includes `babel-plugin-react-docgen`
	- outputs a`build/docgen` (not published)
- Use `build/docgen` to generate a `react-docgen.json` file (published)

Testing:
- `yarn workspace carbon-components-react build`
- Should generate a `react-docgen.json` file with docgen data in the react package.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM basically - Would you fix the CI? Thanks @vpicone!

**Comment by vpicone** [comment]
@asudoh i honestly have no clue what’s up with the CI. Do you know?

**Comment by vpicone** [comment]
@asudoh fixed thanks! @jnm2377 @joshblack holler if you have any questions

**Review by emyarod — COMMENTED** [review]
looks good to me, `docgen` directory and `react-docgen.json` are generated

> Use `build/docgen` to generate a `react-docgen.json` file (published)

just wondering, does `react-docgen.json` need to be separate from `build/docgen` if they're both ignored? or does the json file need to be at the package root?

**Comment by vpicone** [comment]
@emyarod "publish" here refers to what get's pushed to npm. The build directory is ignored when publishing, the `react-docgen.json` file is not. 

It doesn't need to be at the package root per-se, but it makes it easy to find/import. It's also where we put metadata files historically (icons, pictograms).

**Review by emyarod — APPROVED** [review]
looks good to me, thanks for confirming

**Pull request merged**
