### PR TITLE
fix(type): update line height for expressive tokens

### PR DESCRIPTION
**Pull request by jeanservaas**
Need to update the leading on the:

I want to review the preview link before this is merged

$expressive-heading-03 Max breakpoint
$quotation-01 Large breakpoint
$expressive-paragraph-01 Mobile and Med breakpoints

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
Changes look good to me. Website won't reflect these changes until we update the website to `10.20.0` when it is released 👍

**Comment by jeanservaas** [comment]
Hey guys, I'm just trying to verify the line height change in the elements package but it's hard to tell if they've been made because the line doesn't break in the elements package. 

When I inspect it says the line height is still 1.25

image

Again, just trying to achieve a 24px / 30px line height for scale (5) in expressive type

**Comment by tw15egan** [comment]
I guess I'm a bit confused. I'm seeing `1.3` for `expressive-heading-03` 

Screen Shot 2020-09-11 at 9 45 18 AM

But that calculates to `24px / 31.2px` ...

image

---

The previous value, `1.25` computed to the correct values, so do we need to revert these changes? 


Screen Shot 2020-09-11 at 9 47 17 AM
Screen Shot 2020-09-11 at 9 47 20 AM

**Comment by jeanservaas** [comment]
OK no that's good! I'll take 24 / 31.2. That's perfect. If that's what it's reading we're all good.

I just couldn't really verify it from the preview so I was worried.

**Pull request merged**
