### PR TITLE
test(build): test tree-shakability

### PR DESCRIPTION
**Pull request by asudoh**
#### Changelog

**New**

- A Jest test for modules tree-shakability.

**Changed**

- Some files to make them tree-shakable.

#### Testing / Reviewing

Testing should make sure no component/test is broken.

### CODE REVIEW

**Comment by joshblack** [comment]
Would you want to add support for this in the private `@carbon/bundler` package? We could make it public and use it across the board if we want. There is also a useful `check` command that verifies that scss partials can independently be compiled that could replace that part of the setup, as well.

Reference: https://github.com/IBM/carbon-elements/blob/master/packages/bundler/src/bundler.js#L31

**Comment by asudoh** [comment]
@joshblack Reviewing what I wrote, and I see that most of the code ([`pure-modules-test.js`](https://github.com/IBM/carbon-components/blob/f38e1200a05ed5052a06555fb953ac1b38584e86/tests/pure-modules-test.js)) is environment-specific, e.g. it has its own Rollup config, it has its own lo-dash workaround, etc.

Therefore I don't think the code I wrote can directly be ported to `@carbon/bundler`. Assuming `@carbon/bundler` always uses fixed set of Rollup/Babel configs, I see `@carbon/bundler` would implement its own tree-shaking test with its own Rollup config.

**Comment by joshblack** [comment]
Sounds good, @asudoh!

**Review by joshblack — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Comment by joshblack** [comment]
_PR Reviews 1/11_

Notes:

- [ ] Update merge conflict and then ship it 🎉

**Pull request merged**
