### PR TITLE
feat(tag): respect type prop for filter tag

### PR DESCRIPTION
**Pull request by janhassel**
Related to #3318

Adds color to filter tags according to their `type`.

#### Changelog

**Changed**

- Extended `tag-theme` mixin

#### Testing / Reviewing

1. Run react storybook
2. View "Tag -> Filter"
3. Cycle through the types

---

*This PR is intended to implement a temporary solution for #3318*

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Looks good for the light themes 👍🏻

For the dark themes we do this a little differently. We have a tag background in the 80 color grade. And the text and icons are at a 30 color grade. The hover goes a grade lighter to 70

Example:
Artboard

**Comment by janhassel** [comment]
@laurenmrice It seems like the tag component is not up to spec then, since it always uses `$ibm-color__<color>-20` reagrdless of the theme (you can try out here: https://carbon-components-react.netlify.com/?path=/story/tag--default by switching through the "Carbon Theme" options).

@joshblack What would be the best way to implement the dynamic tag colors? Would it be adding each IDL color as a token (i.e. `$idl-red`, `$idl-blue`, `$idl-purple`) with its respective value per theme (`$idl-red` would be `$ibm-color__red-20` in light and `$ibm-color__red-80`)?

**Comment by joshblack** [comment]
@laurenmrice maybe we need to do tag tokens? What @janhassel shared above is accurate, the colors for the tag are computed based on the IDL colors and therefore don't change as part of theme changes.

**Comment by laurenmrice** [comment]
Can we not tokenize them and just have them follow idl colors? This is what we originally intended of our design specs.

**Comment by joshblack** [comment]
@laurenmrice Unfortunately, we don't really have a handle to say "when in theme XYZ, do this". Instead, we have to use the tokens and rely on their values changing when the theme changes.

What this might look like for us to do with tag:

```diff
.#{$prefix}--tag--red {
  @include tag-theme(
-    $ibm-color__red-20,
+    $tag-red-background,
-    $ibm-color__red-70,
+    $tag-red-text,
-    $ibm-color__red-30
+    $tag-red-hover
  );
}
```

```scss
// White
$tag-red-background: $ibm-color__red-20;
// g100
$tag-red-background: $ibm-color__red-80;
```

**Comment by laurenmrice** [comment]
ok got it. 👍🏻 We can have tokens for tags. And I think we should surface them on tag specific pages but not list them as the global tokens we have on our color usage page for example.

**Comment by janhassel** [comment]
@joshblack Could you guide me on where to implement the tokens? When I add them to `/packages/themes/src/tokens.js` and `/packages/themes/src/[ white.js, g10.js, g90.js, g100.js ]` they're automatically added to the documentation (`packages/[ components, elements, themes ]/docs/sass.md`). Also, to satisfy the tests, I'd need to add them to the `v9.js` theme.

Not sure if there is another way to have them more "scoped"

**Comment by joshblack** [comment]
Hi @janhassel! 👋 Sorry for the delay, I believe we'd want to add them in the `_tag.scss` file in `carbon-components` as opposed to the theme. There we could follow the structure:

```scss
/// @access private
$tag-<color>-<purpose>: <value>;
```

For example:

```scss
/// @access private
$tag-red-background: ...;

/// @access private
$tag-red-text: ...;
```

If the value list ends up getting distracting in the file (e.g. it gets too long) we could definitely move it under a `tags/_tokens.scss` file and import that 👍 

Let me know if this helps!

**Comment by janhassel** [comment]
@joshblack I'm not quite sure I can implement two theme maps (light and dark) and use them without exposing the tokens in the general theme map. Therefore I wrote a simple function to check whether the current `carbon--theme` is light or dark and set the token accordingly.

It seems to work when I run it locally in the react storybook. However, the CI failed and tbh I'm a bit confused by the error message. 

```
carbon-components: Error: Undefined variable: "$ibm-color--red-20".
carbon-components:         on line 9 of scss/components/tag/_tokens.scss, in function `if`
carbon-components:         from line 9 of scss/components/tag/_tokens.scss
carbon-components: >> nd: if(themeIsDark(), $ibm-color__red-80, $ibm-color__red-20);
carbon-components:    ------------------------------------------^
```

**Comment by janhassel** [comment]
@joshblack I fixed the ci error (forgot to import `globals/scss/vars` 🤦‍♂).

It works if the user implements the carbon theming by setting `$carbon--theme`, but not when they solely rely on the css emit properties feature (as the storybook does).

Any idea on how to apply dynamic colors on theme change without having them in the main token map?

**Comment by joshblack** [comment]
Hi @janhassel! 👋 Sorry for the delay. Yeah, definitely see what you're saying now since the colors come from the IDL and not our tokens so the CSS Custom Properties don't really apply 🤔 

I'm honestly unsure what is the best path moving forward with this stuff and am open to suggestions. I think the conditional bit of checking the theme will be hard to map over to CSS Custom Properties and might leave us stuck 🤔 

We could do a similar thing that we do with our tokens and in our dev environment have the tag component tokens be a part of the CSS Custom Properties that are omitted?

**Comment by janhassel** [comment]
@joshblack This is a much more complicated topic than I anticipated 😂

I pushed some changes which actually go the route of exposing the tokens in the general themes but do it in a pattern that hopefully allows easier extension in case another component has a similar problem.

My idea was to treat `[white.js, g10.js, g90.js, g100.js]` as the "core color tokens" and any additional (tag colors for now), "component color tokens".

If I'm not mistaken, it should be pretty easy to filter out the component tokens from the doc generator so they don't appear in the Sass API files, but actually I'm not sure if this is a good idea since those files are mainly for the maintainers, aren't they?

Let me know what you think about this approach!

**Comment by laurenmrice** [comment]
The focus needs to be switched color wise. It needs to be showing up blue in the light themes and white in the dark themes.

**Comment by janhassel** [comment]
@laurenmrice Thanks for catching that! Should be fixed now.

**Review by laurenmrice — APPROVED** [review]
Looks good to me from a visual perspective 🎉

**Comment by joshblack** [comment]
@janhassel thanks so much for going down this exploration! Really appreciate all this time/effort 🙏 

I think modifying the core themes package definitely can put us in a hard spot, although clearly it works out really well lol.

I think keeping the invariant of "themes is for core tokens" would be a great design goal with this work. One idea that I was thinking of for this could be: https://www.sassmeister.com/gist/88d991f5fc26278c325728c473c7001a

Definitely is a large example, apologize that I couldn't come up with a reduced case (this stuff is way too hard 🤦‍♂️)

This approach would be helpful for us in that we wouldn't expose these tokens in a public way through our themes package while still working in the default and experimental flags (CSS Custom Properties) use-case.

The way that it works is similar to the idea that you had already, essentially we have a map of tokens to their values for each theme. In the example, this is this bit:

```scss
$component-tokens: (
  'component-token': (
    (
      theme: $theme-a,
      value: $blue-40,
    ),
    (
      theme: $theme-b,
      value: $blue-50,
    ),
    (
      theme: $theme-c,
      value: $blue-60,
    ),
    (
      theme: $theme-d,
      value: $blue-70,
    ),
  )
);
```

Using this map, we could determine what value should be used depending on the current theme:

```scss
@mixin component {
  $component-token: get-token-value($theme, $component-tokens, 'component-token');

  .selector {
    color: $component-token;
  }
}
```

It could also help out with emitting CSS Custom Properties through the feature flag. Additionally, we could use a helper to emit the custom properties and add that to our existing storybook to enable viewing this work in our Netlify previews.

Let me know what you think of this work, also am happy to walk through it more if you want to chat about it! Also am definitely not tied to any of the naming conventions or anything with this work so if you think it might be worth trying out feel free to mix-and-match with whatever you think is best here 👍

**Review by joshblack — COMMENTED** [review]
Left a comment above, let me know what you think!

**Comment by janhassel** [comment]
@joshblack Thanks for the detailed example, that really helps!

I think we're getting there and I just pushed an implementation of that structure (slightly modified). I like this approach as it encourages decoupling of the component tokens.

However, I'm still wondering on how to detect the current theme to apply it regardless of the user's implementation technique (setting `$carbon--theme` globally vs. passing it as a parameter to the `carbon-theme()` mixin).
Maybe I missed something here?

**Comment by joshblack** [comment]
@janhassel, unfortunately, I think for the CSS Custom Properties example we won't be able to detect it 😞 we would need to instead apply it to the storybook config similar to the gist shared above.

When we move to shipping this feature as stable, one option we could end up doing is putting these kinds of properties on `:root` once the theme is initialized, potentially something like:

```scss
@include carbon--theme();

// Under the hood...
@mixin carbon--theme() {
  :root {
    // emit component properties
  }
}
```

However, we might run into some trouble if folks aren't using that component and don't want the additional fields so might not work out 😞

**Comment by janhassel** [comment]
What if we reserve an scss variable containing the theme identifier and set it through the `carbon--theme()` mixin?

```scss
$theme-white: 'white';
$them-g10: 'g10';
$theme-g90: 'g90';
$theme-g100: 'g100';

@function get-theme-identifier($theme) {
  @if $theme == $carbon--theme--g10 {
    @return $theme-g10;
  }
  @if $theme == $carbon--theme--g90 {
    @return $theme-g90;
  }
  @if $theme == $carbon--theme--g100 {
    @return $theme-g100;
  }

  @return $theme-white;
}

@mixin carbon--theme(
  $theme: $carbon--theme,
  $emit-custom-properties: false,
  $emit-difference: false
) {
  $carbon--theme-identifier: get-theme-identifier($theme) !global;

  $interactive-01: map-get($theme, 'interactive-01') !global;
  $interactive-02: map-get($theme, 'interactive-02') !global;
  ...
}
```

Or could we even have this in the generated theme maps themselves?

```scss
$theme-white: 'white';
$them-g10: 'g10';
$theme-g90: 'g90';
$theme-g100: 'g100';

$carbon--theme--white: (
  carbon--theme-identifier: $theme-white,
  interactive-01: #0f62fe,
  ...
) !default;

$carbon--theme--g10: map-merge(
  $carbon--theme--white,
  (
    carbon--theme-identifier: $theme-g10,
    ui-background: #f4f4f4,
    ...
  )
) !default;

$carbon--theme--g90: map-merge(
  $carbon--theme--white,
  (
    carbon--theme-identifier: $theme-g90,
    interactive-02: #6f6f6f,
    ...
  )
) !default;

$carbon--theme--g100: map-merge(
  $carbon--theme--white,
  (
    carbon--theme-identifier: $theme-g100,
    interactive-02: #6f6f6f,
    ...
  )
) !default;
```

What do you think?

**Comment by joshblack** [comment]
@janhassel ohhh, sorry I thought you meant at runtime.

At build time, I'm pretty sure we can do an equality check with `$carbon--theme` to determine the current theme (or at least that was the intent behind this snippet from the linked example)

```scss
@function get-token-value($theme, $map, $name) {
  $options: map-get($map, $name);
  @each $option in $options {
    @if map-get($option, 'theme') == $carbon--theme {
      @if $enable-css-custom-properties == true {
        @return var(--cds-#{$name}, #{map-get($option, 'value')});
      }
      @return map-get($option, 'value');
    }
  }
  
  @error 'Unable to find value for token';
}
```

More specifically, if `$carbon--theme == $carbon--theme-g90` then we know we're in the g90 theme

**Comment by janhassel** [comment]
@joshblack As far as I understand - and please correct me if I'm wrong - checking equality with `$carbon--theme` is not safe since the user has two options of including the `carbon--theme()` mixin:

**Option A**
```scss
$carbon--theme: $carbon--theme--g90;
@include carbon--theme();
```
*Here it would work*

**Option B**
```scss
@include carbon--theme($carbon--theme--g90);
```
*Here it wouldn't work since the global variable `$carbon--theme` is not modified and should probably fall back to `$carbon--theme--white`.*

That's why I think we need to set a variable from within the `carbon--theme()` mixin.

**Comment by joshblack** [comment]
@janhassel something that's important for option b is that this is operating as intended to support our "zones" concept. The intended way to use this would be:

```scss
@include carbon--theme($carbon--theme--g90) {
  @include tag();
}
```

[Reference](https://carbon-elements.netlify.com/themes/examples/preview/#theming)

Unfortunately, this ends up with duplicate CSS which is why we want to move to CSS Custom Properties to help alleviate this 👍

**Comment by janhassel** [comment]
@joshblack Oh, I didn't know that, thanks for the reference!

I just pushed some changes which make the tag colors compatible with the following implementation techniques:

**Technique A - The standard**
```scss
$carbon--theme: $carbon--theme--g90;
@include carbon--theme();
```

**Technique B - The zone**
```scss
@include carbon--theme($carbon--theme--g90) {
  @include tags();
}
```

**Technique C - The standard (with css emit properties)**
```scss
$feature-flags: (
  enable-css-custom-properties: true,
);

$carbon--theme: $carbon--theme--g90;
@include carbon--theme($emit-custom-properties: true);
```

---

Sadly, the following code will use the default (`white`) tokens for the tags...
**Technique D - The zone (with css emit properties)**
```scss
$feature-flags: (
  enable-css-custom-properties: true,
);

@include carbon--theme($carbon--theme--g90, true);
```
... and the developer would need to `@include tags()` in the zoned block in order to get it working.


---

I added the a `theme-identifier` variable to the mixin since *Technique B* wouldn't work when relying on equality check with `$carbon--theme`.
Actually, this `theme-identifier` could also be helpful for the relatively new `get-light-value()` function I think.

---

To show the appearance in different themes on storybook, we can modify the `styles.scss` for the storybook like this:
```scss
@if feature-flag-enabled('enable-css-custom-properties') {
  :root {
    @include carbon--theme($carbon--theme--white, true) {
      @include tags();
    }
  }

  :root[storybook-carbon-theme='g10'] {
    @include carbon--theme($carbon--theme--g10, true) {
      @include tags();
    }
  }

  :root[storybook-carbon-theme='g90'] {
    @include carbon--theme($carbon--theme--g90, true) {
      @include tags();
    }
  }

  :root[storybook-carbon-theme='g100'] {
    @include carbon--theme($carbon--theme--g100, true) {
      @include tags();
    }
  }
}
```

**Comment by joshblack** [comment]
@janhassel thanks for understanding, sorry this stuff just keeps piling on lol 🤦‍♂️

Instead of doing the zone approach in our storybook, honestly I think we could just get away with emitting the tokens using that map and helper I was sharing, specifically:

```scss
  :root[storybook-carbon-theme='g100'] {
    @include carbon--theme($carbon--theme--g100, true);
    // Whatever the variable ends up being for the tag component tokens
    @include emit-custom-properties($tag-tokens, $carbon--theme--g100);
  }
```

**Comment by janhassel** [comment]
@joshblack Good point! I added it.

**Comment by janhassel** [comment]
@joshblack I just added a step to the theme mixin builder that emits component tokens when `$emit-custom-properties == true`.
This actually makes implementation technique D possible (and therefore immediate support for the storybook)

Are okay with that?
If yes, then I think the last item on the list (hopefully 🙏) would be to make sure to import the component tokens into the generated mixin file.

**Comment by joshblack** [comment]
@janhassel real quick, what did we need the theme identifier for again? Could we do a direct comparison of the values instead using the current theme value? Feel like I might be missing something here 😅 

For reference, this situation is what I was thinking of:

```scss
$some-component-tokens: (
  'token-01': (
    (
      theme: $carbon--theme--white,
      value: #ffffff
    ),
    (
      theme: $carbon--theme--g100,
      value: #000000
    ),
  )
);

@function get-token-value($theme, $map, $token) {
  $values: map-get($map, $token);
  @each $theme-value in $values {
    @if map-get($theme-value, 'theme') == $theme {
      @return map-get($theme-value, 'value');
    }
  }
}

@mixin some-component() {
  // In this scope, $carbon--theme will be whatever the current theme is
  $token-01: get-token-value($carbon--theme, $some-component-tokens, 'token-01');
}
```

Is it potentially to support broader use-cases with things like zones? Or to avoid maybe the manual part of adding in the component token values? 👀

**Comment by janhassel** [comment]
@joshblack Yes, it's intended to support zoning since in the following scenario the tags (or component tokens at this point) wouldn't adapt otherwise while other components (such as a button) would:

```jsx
(
  <div className="some-dark-ui-part">
    <Tag type="blue">Experimental</Tag>
    <Button kind="ghost">Submit</Button>
  </div>
)
```

```scss
.some-dark-ui-part {
  @include carbon--theme($carbon--theme--g100);
}
```

**Comment by joshblack** [comment]
@janhassel got it, I think we could batch up that use-case with the work we want to do with theming with CSS Custom Properties in the future. I don't think zoning makes much sense right now with the mixin approach sadly due to duplicate CSS 😞 and CSS Custom Properties are still considered experimental until we can migrate over to them.

In the CSS Custom Property world, it does seem like we'll need some helpers for coordinating global tokens and component-level tokens with theming though, for sure 🤔 We might be able to roll that up into the carbon theme mixin or come up with some helpers with setting them based on theme.

**Comment by janhassel** [comment]
@joshblack As discussed earlier, I removed the `$theme-identifier` variable from the themes and rolled back to comparing the value of `$carbon--theme` directly.

Also, using `$carbon--theme` as a map key exceeds the limits set by sass, so every component token is now a map itself with two properties: `theme` and `value`.

When I tried emitting the tokens in storybook like the following, I've noticed however, that inside the mixin, `$carbon--theme` is not reassigned to the theme passed as a parameter, so zoning would also not work by manually calling the `emit-component-tokens` inside the `carbon--theme()` mixin.
```scss
:root {
  @include carbon--theme($carbon--theme--g100, true) {
    @include emit-component-tokens($tag-colors);
  }
}
```

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Yay, thanks so much for all your hard work and effort here @janhassel!!!

**Comment by joshblack** [comment]
@emyarod should be ready for re-review finally 😂

**Comment by laurenmrice** [comment]
Just one last thing @janhassel , from a design perspective. The `Default`tag in the dark themes doesn't get a hover color change. Everything else looks GREAT!
Apr-02-2020 10-53-01

**Comment by janhassel** [comment]
@laurenmrice  I addressed that in the latest commit actually. The storybook demo should be updated in about 15 minutes.

@joshblack Thank you for all the guidance! 😄

**Comment by joshblack** [comment]
@janhassel was that meant for @laurenmrice potentially??

**Comment by janhassel** [comment]
@laurenmrice Deploy preview is ready now, including the default tag styling.

**Comment by laurenmrice** [comment]
looks great ! Thanks so much for your patience and great work @janhassel ! 🎉

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
