### PR TITLE
fix: tooltip correctly displayed inside table

### LINKED ISSUE #15981: [Bug]: Tooltips broken when used inside DataTable
### Package

@carbon/react

### Browser

Firefox

### Package version

1.47.0

### React version

18.2.0

### Description

When using Tooltips inside a Table the tooltip message breaks

image

### Reproduction/example

https://stackblitz.com/edit/github-hpqkqe?file=src%2FApp.jsx

### Steps to reproduce

1. Inside a table add a Tooltip close to the borders (top, bottom, left, right) and hover the tooltip

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by FFahrenheit**
Closes #15981

Tooltips used inside Table are now correctly displayed when placed close to table borders
 
#### Changelog

**Changed**

- Changed overflow-x behaviour in data-table-content when a popover-container is used inside
- Also fixed all-contributors file, "{" missing 

#### Testing / Reviewing

Place a Tooltip in a header, or first / last column to check new behaviour
Bug recreation: https://stackblitz.com/edit/github-hpqkqe?file=src%2FApp.jsx

### CODE REVIEW

**Comment by FFahrenheit** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by FFahrenheit** [comment]
recheck

**Comment by tw15egan** [comment]
Thanks for the contribution @FFahrenheit , but this won't work because it will break horizontal scrolling inside the DataTable: https://stackblitz.com/edit/github-hpqkqe-di7xzg?file=src%2Findex.scss

Now that https://github.com/carbon-design-system/carbon/pull/14654 has been merged in, I wonder if this issue may be resolved in the next release.

**Comment by tay1orjones** [comment]
Yes https://github.com/carbon-design-system/carbon/pull/14654 solved this: https://github.com/carbon-design-system/carbon/issues/15981#issuecomment-2021304279


Thanks for taking a look at it!

**Pull request closed without merging**
