### PR TITLE
Upgrade webpack to v4

### LINKED ISSUE #1155: Maintenance: Upgrade WebPack
### Summary

This issue is for tracking a maintenance effort to upgrade to WebPack4.

### Justification

For continuous effort for us to maintain our toolstack up-to-date.

### Desired UX and success metrics

Ensuring our code work with the latest toolstack.

### "Must have" functionality

WebPack4 and code changes associated with that.

### PR DESCRIPTION
**Pull request by vividh**
Closes #1155 

This PR upgrades webpack to latest version, v4.

#### Changelog
**Changed**
- Updated webpack to `v4` in `package.json`
- Added `mode` option in webpack config. Value is set to `NODE_ENV` if present, or `development`. Read about mode option [here](https://webpack.js.org/concepts/mode/).
- Changed the `loaders` config field to `rules`
- Upgraded eslint to v4 (and upgraded related dependencies)

#### Testing / Reviewing
Build locally and run linters. Read webpack [v3 to v4 migration guide](https://webpack.js.org/migrate/4/) to find relevant changes to be done.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @vividh!

**Comment by vividh** [comment]
Any reason why the lint checks are failing? Seems unrelated to the webpack changes. Something I can help resolve?

**Comment by asudoh** [comment]
Seems that we hit issue# 487 at https://github.com/babel/babel-eslint unfortunately. The comment dated at April 18th explains it the best. Most teams who pinged me about this issue chose to upgrade to ESLint4+. Would you be able to do that (probably the latest 5)...? If so, [this link](https://github.com/IBM/carbon-components/compare/master...asudoh:upgrade-eslint) may work as a reference (feel free to ping me for any questions here). If not, it's totally fine and we can wait. Thanks!

**Comment by vividh** [comment]
Sure, no problem! Will look into upgrading eslint.

**Comment by asudoh** [comment]
🎉 for ESLint upgrade! Thanks @vividh for doing this!

**Comment by vividh** [comment]
No problem! Tried to upgrade to version 5, but that required a node upgrade, which is a whole another chore in itself.

**Review by marijohannessen — APPROVED** [review]

**Pull request merged**
