### PR TITLE
 feat(test-utils): support arbitrary sass renderers 

### PR DESCRIPTION
**Pull request by cal-smith**
Following on from the work and discussion started in #3174

### CODE REVIEW

**Comment by joshblack** [comment]
@cal-smith something I'd be curious about from your perspective is if we "render twice", or render for each supported renderer, by default.

**Comment by cal-smith** [comment]
We could definitely do that ... of course, to use the results in tests we'd want to return an object or array describing the results, and potentially some helper function to run each `it` or `describe` against that output.

something like:

```js
[
  {
    compiler: some identifier
    result: object returned by `render`
  }
]
```

The big thing here is that each test will likely need to modify it's behavior for a given compiler - largely due to subtle differences in output that we should account for.

**Comment by joshblack** [comment]
Ah okay, do you happen to know off-hand what the delta is between compilers that we'd need to consider?

**Comment by cal-smith** [comment]
The big exception that comes to mind is mixin hiding (https://github.com/carbon-design-system/carbon/pull/3540/files#diff-9c3cb7e7c0de3acc4e1d90fad682879bR74) ... there aren't _many_ cases where a test would want to diverge, but it's worth considering.

**Comment by joshblack** [comment]
Got it 👍 

In your opinion, would it be more valuable for us to add support for the dart renderer into this test: https://github.com/carbon-design-system/carbon/blob/master/packages/components/tests/styles-test.js#L25 versus plugging it into the `createSassRenderer` tool?

**Comment by cal-smith** [comment]
Perhaps not strictly _more_ valuable, but that test would definitely be the minimum required for checking dart compatibility. At the core we're most concerned with "does it even compile", the rest of the tests are mostly sanity checks that node-sass and dart-sass are behaving the same.

We can totally leave `createSassRenderer` alone and start with `styles-test.js`.

**Comment by joshblack** [comment]
Got it, just trying to understand! Thanks so much for helping me get a better picture of dart sass 😄 And also sorry this has been so back-and-forth on this, has been hard finding the right time to come back from project work.

**Comment by cal-smith** [comment]
No worries! I've been fitting this in around everything else as well, so the slower/async cadence is fine haha.

**Comment by cal-smith** [comment]
I think I've come up with a reasonable solution to some of the testing ugliness ... ultimately it seems like we'll need some kind of wrapper function to keep the test envs contained for each render _however_ we can do something like this:

```javascript
testAll(
  [createSassUtil(require('node-sass')), createSassUtil(require('sass'))],
  sassUtil => {
    const { createSassRenderer } = sassUtil;
    const render = createSassRenderer(/* skip */);

    describe( /* actual test logic here */ );
  }
);
```

This way we can be explicit about what renderers we're testing, but without adding too much overhead and ceremony to the test declarations.

**Comment by joshblack** [comment]
@cal-smith I think in the meantime we should just worry about adding a test harness for testing dart sass compilation. I was trying to do this but ran into a hiccup using `Fiber` 🤔 without it, it seems like the tests take ~3min with either `render` and `renderSync` which is a bit too much right now, I think.

**Comment by jnm2377** [comment]
Hi @cal-smith it seems like you've been working on this for a while! We are making an effort to no longer allow PRs to go stale, and thus would like to see this PR get merged in or closed in a week. Totally understand if you don't have the bandwidth to work on it in the next week, so we also want to encourage you to re-open the PR once it's ready.

**Comment by joshblack** [comment]
Gonna close this for now, let's revisit this soon!

**Pull request closed without merging**
