### PR TITLE
(fix) RTL styles for Accordion

### LINKED ISSUE #914: Accordion - wrong direction of arrow in RTL mode
Accordion component has arrow icon.
It should be displayed correctly in 'open' and 'closed' states.
Current display in 'closed' state:
image
Current display in 'open' state:
image

## Steps to reproduce the issue

1. run Accordion component on RTL screen
2. check the results

### PR DESCRIPTION
**Pull request by irafishbein**
## Overview

Resolves https://github.com/carbon-design-system/carbon-components/issues/914

I've added styles that are harmless for LTR mode and resolve issue in RTL mode.

Fixed:
image
image

Testing / Reviewing
Run Accordion on RTL screen,
Verify arrow direction when open and closed.

### CODE REVIEW

**Comment by irafishbein** [comment]
@alisonjoseph, @tw15egan 
Hello,
I was unable to set you as reviewer (probably my account issues).
Can you please take a look?
Thank you.

**Comment by irafishbein** [comment]
@alisonjoseph, @tw15egan 
Hello,
I was unable to set you as reviewers (probably my account issues).
Can you please take a look?
Thank you.

**Comment by alisonjoseph** [comment]
I checked this in Chrome on a mac and it didn't seem to change the arrow direction in RTL mode. 
screen shot 2018-06-20 at 7 51 06 am

**Comment by irafishbein** [comment]
@alisonjoseph 
Sorry, fixed, please retry.

**Comment by alisonjoseph** [comment]
Hmm, am I doing something wrong, it still doesn't appear to be adding this style `/*rtl:rotate(180deg)*/;`

I added `<body dir="rtl">` to my page, is there anything else I need to do?

**Comment by asudoh** [comment]
Great point @alisonjoseph - Seems that @irafishbein is using http://rtlcss.com/learn/usage-guide/control-directives/index.html or a like, and if it's the case, we need a PR in https://github.com/carbon-design-system/design-system-website to add a explanation of how to generate RTL version of the CSS.

**Comment by irafishbein** [comment]
@alisonjoseph 
dir='rtl' should be set at <html> level.
Please try it this way - it should work.

**Comment by irafishbein** [comment]
@asudoh 
You are right, I am using https://www.npmjs.com/package/webpack-rtl-plugin.
Please let me know if you want me to provide 'RTL support instructions'.

**Review by tw15egan — APPROVED** [review]
I'm also unable to get it to work properly in RTL mode, but since the styles still look fine in LTR mode, and the other RTL fix worked great, I'm fine with approving this

**Comment by tw15egan** [comment]
I agree with @asudoh that we should add some documentation on the main website regarding RTL mode, but maybe after we verify all the components work properly first 😄

**Review by alisonjoseph — APPROVED** [review]
Agree with TJ

**Pull request merged**
