### PR TITLE
fix(radio-button): left/right alignment

### LINKED ISSUE #2286: [Carbon 10: Radio button] styling issues
I don't believe the following are intended

1. there isn't a hover state when the user mouses over the label or input
1. vertical radio buttons are center aligned

> Is this issue related to a specific component?

Radio button

> What did you expect to happen? What happened instead? What would you like to see changed?

1. there should be a hover state to inform the user they are hovering over the input (or label)
1. the radio button inputs are aligned with each other when using the vertical modifier

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library (PAL)

## Additional information

Vertical alignment
Screen Shot 2019-04-10 at 4 04 06 PM

Use case when a label wraps to multiple lines (both horizontal and vertical layouts)
Screen Shot 2019-04-10 at 4 21 01 PM

### PR DESCRIPTION
**Pull request by youda97**
Closes #2286

### CODE REVIEW

**Comment by emyarod** [comment]
this appears to be a duplicate of https://github.com/carbon-design-system/carbon/pull/2870?

**Comment by asudoh** [comment]
@youda97 Are you trying to add right-aligned vertical radio button...?

**Comment by youda97** [comment]
@asudoh There's a class `#{$prefix}--radio-button-wrapper--label-left` that positions the labels to the left, so the radios need to be right aligned at that point

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @youda97!

**Review by emyarod — COMMENTED** [review]
should we expose this change in the react and vanilla documentation?

**Review by dakahn — APPROVED** [review]

**Comment by asudoh** [comment]
```diff
--- a/packages/components/src/components/radio-button/_radio-button.scss
+++ b/packages/components/src/components/radio-button/_radio-button.scss
@@ -144,16 +144,19 @@
     margin-bottom: $carbon--spacing-03;
   }
 
+  .#{$prefix}--radio-button-group--label-right .#{$prefix}--radio-button-wrapper .#{$prefix}--radio-button__label,
   .#{$prefix}--radio-button-wrapper.#{$prefix}--radio-button-wrapper--label-right
     .#{$prefix}--radio-button__label {
     flex-direction: row;
   }
 
+  .#{$prefix}--radio-button-group--label-left .#{$prefix}--radio-button-wrapper .#{$prefix}--radio-button__label,
   .#{$prefix}--radio-button-wrapper.#{$prefix}--radio-button-wrapper--label-left
     .#{$prefix}--radio-button__label {
     flex-direction: row-reverse;
   }
 
+  .#{$prefix}--radio-button-group--label-left .#{$prefix}--radio-button-wrapper .#{$prefix}--radio-button__appearance,
   .#{$prefix}--radio-button-wrapper.#{$prefix}--radio-button-wrapper--label-left
     .#{$prefix}--radio-button__appearance {
     margin-right: 0;
```

@youda97 Would you want to add above so the new class this PR adds works for flipping all radio buttons in the group?

**Comment by asudoh** [comment]
After mulling over about this addition, I saw that radio group users would have to add a class to radio group and another class to radio button to flip label/button positioning. Created #2914 to address that.

**Comment by emyarod** [comment]
superseded by #2914

**Pull request closed without merging**
