### PR TITLE
fix(slider): use mono font face for start and end values, remove input border for disabled state

### LINKED ISSUE #4012: [slider] start and end text values need to be mono
Start and end text values need to be `code-02`, `text-01`. Currently the values are `body-short-01`, `text-01`.

The spacing should be 8px between the start/end values and slide tracker. Right now it is 16px

Current:

Should be:

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4012 

This PR applies mono font face to the start and end label values for the `Slider`

#### Changelog

**New**

- font face rule to `Slider` label text

**Removed**

- remove border on the input for `disabled` state

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by jnm2377 — APPROVED** [review]

**Comment by jnm2377** [comment]
Thanks for the fix! We've got a code freeze this week before we release, but will merge this once we unfreeze next week! :)

**Comment by joshblack** [comment]
@laurenmrice for the original issue, for some reason I thought Plex Sans used Mono numbers? Is this not the case?

**Comment by laurenmrice** [comment]
@joshblack Yes that is right, but there are some differences for ex: the mono 0 is different and has a dot in the center.

**Comment by joshblack** [comment]
Perfect, thanks @laurenmrice! Added you as a reviewer too since it seems like you were the original issue creator, let me know if that works or if someone else would be better!

**Review by laurenmrice — APPROVED** [review]
Mono looks good 👍 Ive noticed some unrelated bugs in general with slider, but I will make an issue for that to be fixed in a separate pr.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Actually I noticed in the current code that the disabled state looks correct, but in this pr it is wrong. There should not be an underline on the field.

**Comment by jendowns** [comment]
Thanks @laurenmrice! Could you point out what you mean by an underline on the field when the `Slider` is `disabled`?

I don't see that in the deploy. Here's a screenshot of what I see I toggled the `disabled` state in the React storybook deploy:
Screen Shot 2019-10-03 at 2 43 29 PM

(Unless I"m looking at the wrong thing?)

**Comment by laurenmrice** [comment]
Hey @jendowns its only happening in Vanilla. Heres a screenshot:

Screen Shot 2019-10-03 at 4 09 53 PM

**Comment by jendowns** [comment]
Thanks @laurenmrice I see what you mean now! The code that I changed didn't affect this border, it looks like. I believe it is/was already in the code base, because I can see it on the website here: https://www.carbondesignsystem.com/components/slider/code#slider-disabled

However the change was small and easy, so I just pushed a commit to remove that border for `disabled` states. When the deploy finishes, do you mind taking another look?

(Also for previous reviewers @emyarod @asudoh @joshblack @jnm2377 is this additional change okay with you all? 😅)

**Review by laurenmrice — APPROVED** [review]
Yep that looks good !

**Comment by asudoh** [comment]
Yeah the additional change looks OK to me - Thanks @jendowns and @laurenmrice!

**Pull request merged**
