### PR TITLE
fix(pagination): fix tokens based on audit

### PR DESCRIPTION
**Pull request by tw15egan**
Refs  #10425

Screen Shot 2022-02-22 at 11 42 02 AM

Updates Pagination based on feedback 

#### Changelog

**Changed**

- Changed tokens based on feedback

#### Testing / Reviewing

Verify component renders as expected

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]
Looks good to me!

**Review by dakahn — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] The "1 – 10 of 103 items" text should be color token $text-secondary. Everything else looks great!
Artboard

**Comment by tw15egan** [comment]
@laurenmrice updated 👍🏻

**Review by laurenmrice — APPROVED** [review]
Looks good to me! 🎉

**Pull request merged**
