### PR TITLE
fix(multiselect): add useEffect to selection hook to update externally

### LINKED ISSUE #16124: [Bug]: Multiselect is no longer programmatically controllable
### Package

@carbon/react

### Browser

_No response_

### Package version

v1.53.1

### React version

v18.2.0

### Description

The MultiSelect component is no longer controllable programmatically, meaning that its selected items can no longer be controlled by outside state.

See working version in @carbon/react v1.52.0

https://stackblitz.com/edit/github-vdfyj4?file=src%2FApp.jsx

Versus v1.53.1

https://stackblitz.com/edit/github-vdfyj4-yeae6d?file=src%2FApp.jsx

### Reproduction/example

https://stackblitz.com/edit/github-vdfyj4-yeae6d?file=src%2FApp.jsx

### Steps to reproduce

1. Add a Multiselect that gets its state from `selectedItems`
2. Modify the value of the prop passed to the `selectedItems`

Using the reproduction example I provided:
1. Click the "Clear" button
2. Check that in v1.53.1 it does not clear the Multiselect while in v1.52 it does

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by ychavoya**
Closes #16124

Update MultiSelect's `useSelection` hook to include a `useEffect` that updates the selected items when they are updated externally (controlled component), since the recently added `useState` is only executed on initial render.

#### Changelog

**Changed**

- Ability to update a controlled MultiSelect's selected items externally

#### Testing / Reviewing

Added a [Storybook](http://localhost:3000/?path=/story/components-multiselect--controlled) to test controlled MultiSelect components. The MultiSelect in this storybook should update its selected values when the included buttons are pressed, and a storybook action should be triggered.

Also added a unit test that tests this behavior.

### CODE REVIEW

**Comment by ychavoya** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by ychavoya** [comment]
Hi, I noticed that an error in a different part of the `useSelection` hook was conflicting with the changes and therefore was causing a test to run indefinitely. I sent a commit to fix that

**Review by tay1orjones — APPROVED** [review]
Thanks for this!

**Comment by tay1orjones** [comment]
@guidari @preetibansalui This is something to look out for in https://github.com/carbon-design-system/carbon/pull/16147

**Comment by preetibansalui** [comment]
> @guidari @preetibansalui This is something to look out for in #16147

Thanks @tay1orjones, We will look into this. I have one doubt. For this PR, I know it is to provide controlled state only, but aren't we giving a wrong example here in storybook by selecting all items (including disabled item).
image

**Comment by tay1orjones** [comment]
This introduced two new bugs: 

* https://github.com/carbon-design-system/carbon/issues/16445
* https://github.com/carbon-design-system/carbon/issues/16469

**Pull request merged**
