### PR TITLE
feat(select): add height variations to select

### LINKED ISSUE #5229: [Select] Add size variants
## What packages are you using?

- [x] `carbon-components: "^10.9.2"`
- [x] `carbon-components-angular: "^3.35.4"`
## 
Please add to [select](https://angular.carbondesignsystem.com/?path=/story/components-select--documentation) possibility to change size like it implemented in dropdown

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5229

Select now mimics `Dropdown` and `TextInput`, and has 3 sizes available. 

#### Changelog

**New**

- `size` prop to `Select` (accepts `sm` and `xl`, defaults to standard size)
- Classes for the corresponding heights 

#### Testing / Reviewing

Should ensure `Select` renders at 3 different heights based on the size prop

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Comment by joshblack** [comment]
@tw15egan are we missing a step? Was surprised it went from sm -> lg -> xlg without a md bump 🤔 Code looks great otherwise! Just was curious about that bit

**Comment by tw15egan** [comment]
> @tw15egan are we missing a step? Was surprised it went from sm -> lg -> xlg without a md bump 🤔 Code looks great otherwise! Just was curious about that bit

I agree, which is why when I made this PR (https://github.com/carbon-design-system/carbon/pull/5076) I changed the prop names, but it caused a mismatch with the existing dropdown props, which caused issues.

See convo here https://ibm-studios.slack.com/archives/GCQ5R263T/p1579819071014900 
and here https://github.com/carbon-design-system/carbon-website/pull/845#issuecomment-577939803

This should be changed in v11, and it should be the default `medium`, with a `small` and `large` option.

**Review by emyarod — APPROVED** [review]
looks good to me pending visual review

**Review by aagonzales — APPROVED** [review]
LGTM!

**Review by aledavila — APPROVED** [review]
LGTM

**Comment by joshblack** [comment]
@tw15egan was the conflict with dropdown in a release yet? Or was it earlier work? If not in a release I bet we could update it before 10.10. Separately thanks for the links, reading up now 👀

**Comment by tw15egan** [comment]
Pretty sure Dropdown additions were released in early December, which is why we reverted my changes to be consistent with Dropdown.

**Comment by joshblack** [comment]
@tw15egan ah got it, you're totally right. Would it make sense if we updated Dropdown to also accept the intended value and use that in docs?

Just was trying to understand the ideal here and if we can coordinate the same sizes cross components or not

**Comment by tw15egan** [comment]
@joshblack do we want to merge this in? Or did we want to make the modifications to text input/dropdown to take in `large` and `small`?

**Comment by joshblack** [comment]
@tw15egan I think those modifications would definitely be worth it, what do you think? Also doesn't need to block this for sure, could always move over to a separate ticket and we can tackle it before releasing if we think it's worth it.

**Comment by tw15egan** [comment]
@joshblack I think they would be too, let's do that modification in another PR 👍

**Comment by joshblack** [comment]
Sounds good! Do we want to use that one button issue or should I go make another one?

**Comment by tw15egan** [comment]
@joshblack we can use the button one  👍

**Pull request merged**
