### PR TITLE
fix(ListBoxMenu): use arrayOf(Component) instead of childrenOfType

### PR DESCRIPTION
**Pull request by atikenny**
Relates to [#2785](https://github.com/carbon-design-system/carbon/pull/2785)

Fixes an issue where hot-loader changes the component's instance and === doesn't work properly.

#### Changelog

**Changed**

- ListBoxMenu prop types are validated with arrayOf instead of childrenOfType

#### Testing / Reviewing

- Make sure that no warning or error is thrown when using the ListBoxMenu with ListBoxMenuItem children

#### Screenshot

image

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
looks good to me, but just wondering, do you have an example that showcases the original error output?

**Comment by atikenny** [comment]
@emyarod there is a discussion about it in the linked issue, it basically happens when using hot-reload. It's just a dev time annoyance really nothing else, but would like to keep the noise in our console minimal. As far as I can tell there is no real difference between an array of nodes and the childrenOfType custom prop type.

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Pull request merged**
