### PR TITLE
feat(pictograms): update existing and add net new pictograms

### PR DESCRIPTION
**Pull request by emyarod**
ref #6923

This PR replaces the existing pictograms with newly exported assets and updates the names and aliases for a significant number of pictograms (the most recent asset revisions were made on Oct 20). For existing users this may be a breaking change as some name changes will mean the current asset names will not map to the same assets going forward. Several deprecations have been added to the list, and the current list of deprecated assets can be resolved in a future PR

#### Changelog

**New**

- various net new pictograms

**Changed**

- renamed assets which would have had naming collisions due to metadata changes. will be breaking changes for users of the current asset as the artwork that is mapped to the current name will be changing
- deprecated several assets

**Removed**

- all assets that would have caused name collisions

#### Testing / Reviewing

Ensure the updated pictogram metadata matches the requirements. This will require a manual process as there is no clear naming convention for the assets

### CODE REVIEW

**Comment by joshblack** [comment]
@emyarod it seems like this diff includes:

- newly exported assets
- updates to existing assets
- updates to the names and aliases for pictograms

Does that track everything that it's covering? 👀 

For the new assets, and updated ones, are these now on the 32px artboard instead of the 48px one? Similarly, it seems like they're using the `fill` version instead of the `stroke` version?

**Comment by joshblack** [comment]
Whoops, sorry hit wrong button 🤦‍♂️

**Comment by emyarod** [comment]
yes, those 3 points are what this PR covers, and the assets are updated on the 32px artboards without strokes cc @dudley-ibm

**Comment by joshblack** [comment]
@emyarod perfect, thanks. For release, what's the hope for coordinating the deprecations and the breaking change? Is this all going into one major change for the pictogram packages?

**Comment by emyarod** [comment]
I think it would be ideal to push the breaking changes and deprecations together, but we'd like to review these changes first before finalizing the list of assets to deprecate

**Comment by joshblack** [comment]
Makes sense! Would it help for previewing/reviewing if I ported over the icon preview that we have in elements for pictograms? Happy to put something together for it, don't want to add anything extra to your plate

**Comment by emyarod** [comment]
that's something to consider as well, not sure what the expected review process would be like esp since this is mostly on the design side but we could look into adding that

**Comment by joshblack** [comment]
@emyarod sounds good!

**Comment by joshblack** [comment]
FYI PR for adding pictogram preview: https://github.com/carbon-design-system/carbon/pull/7124

**Comment by mjabbink** [comment]
getting a 404 on digital--trust when clicking on “source”

https://deploy-preview-7094--carbon-elements.netlify.app/pictograms/examples/preview/

**Comment by mjabbink** [comment]
notice two farms. Only need one of these.

Screen Shot 2020-10-26 at 1 49 13 PM


Actually noticing this a lot. Why two of these on certain ones?

**Comment by mjabbink** [comment]
I don’t need this “alt” is needed.

Screen Shot 2020-10-26 at 1 53 14 PM

**Comment by dudley-ibm** [comment]
Can I assume that we're still seeing files that need to be deprecated? We do indeed have two "farm" pictograms now: `farm--01` and `farm--02`. There isn't even a `farm` currently live on the IDL anymore. Also, ALL "alts" had been removed from the new pictogram submission and replaced with either an "01 or "02".

**Comment by emyarod** [comment]
> getting a 404 on digital--trust when clicking on “source”

the preview is linking to `master` where these net new assets do not yet exist, so you’ll have to change the link to this branch, for example https://github.com/emyarod/carbon/blob/6923-picto-diff/packages/pictograms/src/svg/digital--trust.svg rather than https://github.com/carbon-design-system/carbon/tree/master/packages/pictograms/src/svg/digital--trust.svg

> notice two farms. Only need one of these.
> I don’t need this “alt” is needed.

[both of these are deprecated](https://github.com/carbon-design-system/carbon/pull/7094/files#diff-bc252697c2904d8e72af41ba260a44a252b2a3b3113f846575e5de259c37e33a)

**Comment by dudley-ibm** [comment]
Another question I have is why when I view the "source" for these, they still seem to have the extra pasteboard space around it? For example: `folder`
Screen Shot 2020-10-26 at 3 34 55 PM
Screen Shot 2020-10-26 at 3 36 20 PM

**Comment by emyarod** [comment]
@dudley-ibm you are viewing the source of the file on `master` branch (the current asset), rather than this PR branch (the changed asset)

image

you can view all of the changed files together here https://github.com/carbon-design-system/carbon/pull/7094/files

**Comment by mjabbink** [comment]
Is there anyway to improve the rendering quality in the thumbnail? A few seem to render nicely but most do not.

**Comment by emyarod** [comment]
@mjabbink you can view the actual asset rather than the GitHub thumbnails:

> View file

then

> Raw

image

image

**Comment by dudley-ibm** [comment]
@emyarod my apologies for not understanding this completely. The link you just provided in order for me to view all the changed assets doesn't have any 'preview' for the individual assets. Full disclosure: I'm still in the middle of a github learning curve, so again my apologies for these questions.

**Comment by emyarod** [comment]
https://github.com/carbon-design-system/carbon/pull/7094/files contains all of the changed files in this PR. you can see the option to view the rich diff under each SVG

image

which brings you here

image

and the ellipsis overflow menu will also allow you to view the asset directly 

> View file

image

then

> Raw

image

which should show the entire asset in your browser (or you could download it and view on your computer, etc)

**Comment by dudley-ibm** [comment]
Perfect. Thank you @emyarod!

**Comment by joshblack** [comment]
Just a heads up, here is the preview link now for pictograms to show how they will render in code at 32x32: https://deploy-preview-7094--carbon-elements.netlify.app/pictograms/examples/preview/

Noticed two things in the preview that might come up:

- It seems like the stroke width is potentially shrinking with asset, at larger sizes they seem fine but at 32x32 they seem blurry
- It seems like some of the assets still use stroke for styling (they show up as empty boxes in the preview)

**Comment by dudley-ibm** [comment]
@emyarod I’ve discovered some issues with a certain set of pictogram artwork. I’d used the same steps to export every pictogram to outlines, but upon closer inspection of the `Data Analytics` category, the artwork for the majority of them may have to be recreated. It seems the lines went a bit wonky. I'd like to resubmit those before this breaking change gets pushed. Is that a possibility? I can have the replacement artwork ready this afternoon. FYI @mjabbink

**Comment by emyarod** [comment]
@dudley-ibm yes let's roll those updates in with this PR

**Comment by dudley-ibm** [comment]
Thanks @emyarod. I'm attaching a zip file that has replacement artwork for the complete `Data Analytics` category. Thank you for letting this oversight get included in this breaking change. I'll continue to review the rest.
[Data_Analytics_SVG_outlined_UPDATE.zip](https://github.com/carbon-design-system/carbon/files/5446952/Data_Analytics_SVG_outlined_UPDATE.zip)

**Comment by emyarod** [comment]
@dudley-ibm the Data Analytics pictograms have been replaced with the new artwork

edit: Controls category pictograms have been updated with the ZIP below as well

**Comment by dudley-ibm** [comment]
@emyarod After further review I found another small set (`Controls` category) where the line art went wonky. Can we also swap out the attached 9 pictograms in that `Controls` category? Thank you in advance.
[Controls_SVG_outlined_UPDATE.zip](https://github.com/carbon-design-system/carbon/files/5452653/Controls_SVG_outlined_UPDATE.zip)

**Comment by dudley-ibm** [comment]
@emyarod I noticed that `prague.svg` should have been deprecated, as it's an outdated version and it's replacement was `prague--charles-bridge-tower.svg` I may have overlooked deprecating the old artwork because of the more detailed name. The version called `prague.svg` can be removed.

**Comment by dudley-ibm** [comment]
@emyarod I also noticed that what's showing in the PR (https://github.com/carbon-design-system/carbon/pull/7094/files) is an incomplete set. There are entire categories of Pictograms missing from there still, and I wondered if I was viewing it incorrectly again.

**Comment by andreancardona** [comment]
> @emyarod I also noticed that what's showing in the PR (https://github.com/carbon-design-system/carbon/pull/7094/files) is an incomplete set. There are entire categories of Pictograms missing from there still, and I wondered if I was viewing it incorrectly again.

Which set exactly is missing?

**Comment by dudley-ibm** [comment]
> > @emyarod I also noticed that what's showing in the PR (https://github.com/carbon-design-system/carbon/pull/7094/files) is an incomplete set. There are entire categories of Pictograms missing from there still, and I wondered if I was viewing it incorrectly again.
> 
> Which set exactly is missing?

The first category I realized was missing was `Weather` but I also don't see the following categories: `People` `Industry` `Transportation` `Watson` `Location` `Lifestyle` `Networking` `Retail` `Internet of Things` `Time` `Life Science` `Supply Chain` `Manufacturing` `Systems DevOps` `Strategy` `Learning` nor `Status`

The real indicator was at the top of the page "355 files viewed" when we actually have close to 650 pictograms currently in the library.

**Comment by joshblack** [comment]
@emyarod did the last rebase potentially undo the fill change to icon-build-helpers? Noticed that the preview was using stroke again 🤔  Pushed up the change again, just in case. Let me know and I can definitely revert!

**Comment by emyarod** [comment]
@joshblack I didn't realize you were pushing directly to this branch and it also looks like we've lost more than half of our work per @dudley-ibm's comment

**Comment by dudley-ibm** [comment]
Looks like the missing categories are back. I'll review the entire batch one more time today. Thanks guys.

**Comment by emyarod** [comment]
Initially we pushed around ~60 commits when we opened the PR and changed ~670 files but somewhere along the way half of our git history was erased and we ended up with 30 commits and 356 files changed.

image

just now we recovered the lost commits and added @joshblack's icon build helpers change on top to avoid potential git history rewrites, so we are looking at 61 commits and 671 files changed again

let us know if there are any more missing changes @joshblack @dudley-ibm

**Comment by emyarod** [comment]
it looks like the icon build helpers change needs a test update too so we'll have to look at that later/separately, but it shouldn't affect reviewing of the original scope of the PR

**Comment by emyarod** [comment]
updated the icon build helpers change to not overwrite `descriptor.attrs` and to keep the tests passing

**Comment by dudley-ibm** [comment]
@emyarod I found one pictogram that needs to be replaced. 
`yoga--01.svg` in Lifestyle. The outline was incorrect and I'm attaching the corrected SVG.

Also wanted to make sure that the following five pictograms get moved from the `Strategy` category to the `Finance` category (can't see in this PR whether or not that move is scheduled):

`financial--consultant.svg`
`financial--gain.svg`
`financial--news.svg`
`global--finance--euro.svg`
`global--finance--sterling.svg`

Other than that, I've reviewed them all and I think they're ready! @mjabbink please let us know if you saw any other anomalies.
[yoga--01.zip](https://github.com/carbon-design-system/carbon/files/5467343/yoga--01.zip)

**Comment by emyarod** [comment]
@dudley-ibm got it, will update the `yoga--01` asset. for the category updates you can refer to [`categories.yml`](https://github.com/carbon-design-system/carbon/blob/711ebc5f44604d9de843857087fbb16cb117f8ba/packages/pictograms/categories.yml)

**Review by andreancardona — APPROVED** [review]

**Comment by andreancardona** [comment]
**FYI**: pictograms were upscaled to 64x64  @dudley-ibm @mjabbink

**Comment by dudley-ibm** [comment]
Approved. Please merge.

**Comment by mjabbink** [comment]
Approved. 

FYI @vpicone Given the new updates with canvas and pictogram relationship the percentage will need to be adjusted for the pictogram library page so they display in a similar scale to current. If not they will display larger than they are now. FYI @joshblack Unless my presumptions are wrong. Let me know.

**Comment by vpicone** [comment]
@mjabbink sounds good; I'll disable the auto-updates for the next release so we can dial it in before it hits the glass.

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
