### PR TITLE
fix(date-picker): cherry pick flatpickr patch from dotcom

### LINKED ISSUE #17627: [Bug]: date-range picker web component throwing error `Uncaught TypeError: fp.getDateStr is not a function`
### Package

@carbon/web-components

### Browser

_No response_

### Package version

^2.10.0

### React version

_No response_

### Description

date-range picker web component throwing error `Uncaught TypeError: fp.getDateStr is not a function`

... broken in the Carbon monorepo b/c the patches for flatpickr were not moved from the C4IBM repo
- Here is the patch in C4IBM: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/.yarn/patches/flatpickr-npm-4.6.13-06399933fc.patch
- Does not exist in the Carbon monorepo:  https://github.com/carbon-design-system/carbon/tree/main/.yarn
- See also the reference in package.json: https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/main/package.json#L86

### Reproduction/example

n/a

### Steps to reproduce

Create a component
```
        <cds-date-picker>
          <cds-date-picker-input id="date-from" kind="from" label-text="Date Picker label" placeholder="dd/mm/yyyy" size="lg">
          </cds-date-picker-input>
          <cds-date-picker-input id="date-to" kind="to" label-text="Date Picker label" placeholder="dd/mm/yyyy" size="lg"> </cds-date-picker-input>
        </cds-date-picker>
```

check debug output in brower

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by annawen1**
Closes #17627

When we migrated `@carbon/web-components` from dotcom to core, we didn't migrate over the [`flatpickr` dependency patch fix](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/pull/10603) from the yarn cache that is needed to resolve a few `flatpickr` issues.

#### Changelog

**New**

- Bring over flatpickr patch 
- add resolution entry to the patch in the root package.json

#### Testing / Reviewing

A bug that is visible in the current prod storybook is with the `date-picker` with range - the dates clear prematurely like seen here:

https://github.com/user-attachments/assets/50592ded-f0a4-4c98-8374-8d52cd01f65f

Check the deploy preview link and see that the issue is resolved

### CODE REVIEW

**Review by ariellalgilmore — APPROVED** [review]
LGTM! thank you!!

**Review by Gururajj77 — APPROVED** [review]
Looks good

**Review by 2nikhiltom — APPROVED** [review]
Looks good, this should fix the similar [issue](https://github.com/carbon-design-system/carbon/issues/17794) in @carbon/react 🙌

**Review by 2nikhiltom — COMMENTED** [review]
https://github.com/user-attachments/assets/a326df3a-5cd1-4dd4-abe3-02b7db1e62aa

Small observation - 
When selecting a date range and clearing the End Date, if you click away or navigate elsewhere, the End Date field reverts to its previous value and does not stay cleared.

**Comment by annawen1** [comment]
> selecting a date range and clearing the End Date, if you click away or navigate elsewhere, the End Date field reverts to its previous value and does not stay cleared.

Hmm I'm seeing it doesn't revert to the previous value after being cleared - rather it populates with the start date instead. Yeah I see a difference in React where you can just select a start date and click out without selecting an end date, but with Web Components if you do that, the start date clears itself when clicked out.

I'll go ahead and merge this fix in since it addresses some higher severity issues, but in the mean time we can open up a ticket to see if we can align the behavior.

https://github.com/user-attachments/assets/adb69b3a-5b7b-46d2-bcad-fdde649295d1

**Pull request merged**
