### PR TITLE
fix(Tooltip): prevent focus hijacking by other tooltips with focus trap

### LINKED ISSUE #8653: Tooltip has closing issue on Firefox
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Using Firefox and the Tooltip component, I found cases where clicking on other widgets on the page does not close the tooltip and cause confusion.

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expect the tooltip to be closed when clicked elsewhere.  That is working for Chrome, Safari and Edge.

> What browser are you working in?

Firefox 88.0.1

> What version of the Carbon Design System are you using?

10.34

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud
Some functions already in production.

## Steps to reproduce the issue
Use Firefox browser:
1. Go to https://cloud.ibm.com/apidocs/hs-crypto#actiononkey
2. Scroll to "Request" and then "Request body" table with a dropdown and a "View" tooltip.
3. Click on "View".  The tooltip is opened.
4. Click on the left "one of" dropdown.    The dropdown does not open and the tooltip closed and reopened.

Second scenario
1. Go to https://dev.console.test.cloud.ibm.com/apidocs/cloudant#postbulkget.
2. Scroll to the Request body table which shows two Tooltip triggers.
3. Click on BulkGetQuery and the tooltip shows up.
3. Click on BulkGetAttsSinceQuery and notice both tooltips show up. Close outside would still open the tooltip once.

I only see these for firefox.

## Additional information
- Screenshots or code

https://user-images.githubusercontent.com/25369764/117868652-d7fd2800-b267-11eb-95be-2b8b76b73dc7.mov

https://user-images.githubusercontent.com/25369764/117868666-daf81880-b267-11eb-8746-9d77125b4554.mov

### PR DESCRIPTION
**Pull request by emyarod**
Closes #8653
related #7260
related #7319

#7260 reported focus hijacking when clicking from tooltip to tooltip and was resolved in #7319. However, this only addressed the use case where the tooltips contained no focusable children. Focus would be restored to a tooltip's trigger element on loss of focus and multiple tooltips with focus traps would conflict with each other, leading to situations where multiple tooltips could be open at once. The order of the focus events was different in Firefox, but this conflict of focus events occurred in all browsers. This PR updates tooltip focus logic so that pages with multiple tooltips (particularly ones with focusable children/focus traps) will not hijack focus from the already focused elements

#### Changelog

**New**

- (temporary) test story adapted from #7260

**Changed**

- tooltip focus logic on tooltip close

#### Testing / Reviewing

Verify that focus is applied to the expected elements when navigating pages with Carbon tooltips using the mouse or keyboard in all browsers, regardless of whether or not the tooltips contain focusable children

### CODE REVIEW

**Comment by jnm2377** [comment]
It's working fine with mouse, but ran into an issue on keyboard, that if I tab into a non interactive tooltip then tab somewhere else, it stays open, even if I open another tooltip. With the interactive tooltip, I couldn't tab out of it bc it had the focus trap, so I had to press esc, which then closed both of the tooltips.

https://user-images.githubusercontent.com/32556167/118712418-616fa580-b7e6-11eb-98c3-1b7a6ee8d863.mov

**Comment by emyarod** [comment]
this is the existing behavior and I believe also the expected behavior. these tooltips are more like toggletips in that they require explicit dismissal, so the tooltip with no interactive children needs an explicit <kbd>Esc</kbd> keypress or clicking on a non-child element to dismiss it (as opposed to the definition and icon tooltips which will dismiss on blur)

**Comment by jnm2377** [comment]
I'm not sure I would call that the expected behavior. I think if it's not interactive, it behaves more like an icon tooltip, whose [expected behavior](https://carbondesignsystem.com/components/tooltip/usage/#icon-tooltip) is to be shown on hover and focus. So I would expect the non interactive one to close when tabbing to another element since it no longer has focus. Similar to

**Comment by jnm2377** [comment]
I think if it's expected to work more like a toggle tooltip, then we need to add some sort of logic so that if the focus is on the "toggle" button, and the tooltip is shown, then you can't tab out of it until you press `esc` to close the tooltip, or if you can tab out of it, then the tooltip should close automatically.

**Comment by jnm2377** [comment]
cc: @dakahn any thoughts? (see comments above)

**Comment by emyarod** [comment]
I was referring to the behavior for the interactive tooltip above ("They persist [sic] until intentionally dismissed by clicking outside of the tooltip") which is meant to be different from the icon tooltip (remember the interactive tooltip's trigger doesn't require an icon)

If the expected behavior should be revised in that regard, I think it can be revisited by the design team. but in any case, given that it is not a regression and is not the topic of the referenced issues, I believe its scope lies outside of the current PR

**Review by joshblack — APPROVED** [review]

**Comment by emyarod** [comment]
regarding the point about keeping focus on the trigger button if the tooltip does not contain a focusable element, I believe that is an a11y violation and would also prevent selection of text within the tooltip (e.g. #4268 #4232)

**Comment by jnm2377** [comment]
> I was referring to the behavior for the interactive tooltip above ("They persist [sic] until intentionally dismissed by clicking outside of the tooltip") which is meant to be different from the icon tooltip (remember the interactive tooltip's trigger doesn't require an icon)
>
> If the expected behavior should be revised in that regard, I think it can be revisited by the design team. but in any case, given that it is not a regression and is not the topic of the referenced issues, I believe its scope lies outside of the current PR

Right. But if you're navigating via keyboard, you can't click outside of the tooltip. Moving focus is the equivalent of clicking outside of the tooltip for keyboard users, so shouldn't the non interactive one close? I thought the scope of this PR was to not have tooltips remain open if they lose focus (whether its via mouse or keyboard).

**Comment by jnm2377** [comment]
> regarding the point about keeping focus on the trigger button if the tooltip does not contain a focusable element, I believe that is an a11y violation and would also prevent selection of text within the tooltip (e.g. #4268 #4232)

I'm not sure what you mean. I wasn't suggesting that.

**Comment by emyarod** [comment]
this PR is resolving focus hijacking described in the referenced issues but it seems that you are describing keyboard navigation behavior which doesn't appear to be a regression WRT this PR or the referenced issues. on that topic, the dismissal action for keyboard users would be with <kbd>Esc</kbd>

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
