### PR TITLE
fix(modal): match experimental spec

### LINKED ISSUE #1843: Component Design Audit v1.2 - Modal
## Modal

- [x] No drop shadow on modal

image

- [x] Should have max-width set at 768px, but verify with design that this works 👍 

- [x] Should have margin-bottom set to 1rem in form

image

- [x] Should be calling light field inside of a form (field 02), background should end up being gray10

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1843

This PR incorporates feedback from the v1.2 component design audit

---

Questions for reviewers:

need some clarification on this point:

> * Should have max-width set at 768px, but verify with design that this works

and would the following point be left to the consumer to follow or are we going to enforce it at the component level:

>  * Should be calling light field inside of a form (field 02), background should end up being gray10

also where is the screenshot in the original ticket taken from?

### CODE REVIEW

**Comment by asudoh** [comment]
@IBM/carbon-designers Any thoughts on @emyarod's question? Thanks!

**Comment by aagonzales** [comment]
> and would the following point be left to the consumer to follow or are we going to enforce it at the component level:
> Should be calling light field inside of a form (field 02), background should end up being gray10

We should be forcing this for modal because modal backgrounds are $ui-01 and $field-01` fields will not show up on those backgrounds.

**Comment by emyarod** [comment]
typically the consumer composes their own modal content, so they would have to choose to use the light form fields themselves. would we want to nest form styles within the modal styles still, or do we just want to adjust our examples to use the light form inputs?

**Comment by asudoh** [comment]
@emyarod I have an impression that @aagonzales meant modal should dictate/control the content style, but wondering if you have a concern with that (flexibility or meeting a certain use case?). If so, would you articulate that...? Thanks!

**Comment by emyarod** [comment]
since the consumer would be composing their modal content, it may be confusing if they consciously choose to build their modal with regular form inputs but still see the light variants rendered. or have I misunderstood and this situation is not a possibility?

**Comment by asudoh** [comment]
@emyarod I see your concern. I think what @aagonzales is saying is that non-light virtually cannot be seen in the modal background we have (not having enough contrast). What do you you think of her point?

**Comment by emyarod** [comment]
I am alright with it, just want to confirm that this is our intention

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by aagonzales** [comment]
Is there a way to set the default size not at the max width? Can we keep the default width at 50% and then add a max width of 768px on top of that?

Follow up question: can the user specific what size modal they want or is it only ever going to be that max size?

**Comment by emyarod** [comment]
@aagonzales there should be some responsiveness again now. By default the modal width depends on screen width, so the modal will be 100% width at any screen narrower than 672px, then 50% of the screen width (up until 768px) on any screen wider than 672px. The consumer can override those styles if they would like

**Comment by aagonzales** [comment]
Ok yeah now its responding nicely.

Second thing, I'm not seeing the margin-bottom of 1 rem on the form modal. Its still at 0.5rem

**Comment by emyarod** [comment]
@aagonzales are you referring to this margin (the orange area)? 
image

**Comment by aagonzales** [comment]
No above that:

image

**Comment by emyarod** [comment]
ok so I originally changed the highlighted area I was referring to, should I revert that change as well?

**Comment by aagonzales** [comment]
Like this:
image

**Comment by emyarod** [comment]
alright I reverted the original change as well

**Review by tw15egan — APPROVED** [review]
Looks good on the dev side 👍

**Pull request merged**
