### PR TITLE
feat(box-shadow): remove deprecated layer, use box-shadow mixin

### PR DESCRIPTION
**Pull request by tw15egan**
Based on https://github.com/carbon-design-system/carbon/issues/2079#issuecomment-576909605

`layer` was supposed to be deprecated with the v10 release. This removes references to the `layer` mixin and relies on the ol' `box-shadow` mixin instead.

This can be deferred to a larger release, but I wanted to get it in so that it is not get forgotten again. 

#### Changelog

**Changed**
- All instances of `@include layer('overlay');` are changed to `@include box-shadow`;

**Removed**
- Removed global variable `$css--use-layer: true !default;`
- Removed entire `src/globals/scss/_layer.scss` file.
- Removed any imports of `@import '../../globals/scss/layer';`, many of which were unused in the file. 

#### Testing / Reviewing

Ensure components like Dropdown and Tooltip still have box shadows.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
Yes, perfect thanks for updating this TJ!

**Comment by vprasanth** [comment]
Shouldn't this have been a breaking change?

**Comment by joshblack** [comment]
Hi @vprasanth! 👋 It definitely seems like there was some miscommunication around this mixin, it was deprecated for the v9 -> v10 transition but that may not have been communicated when folks were migrating. In v10 we ended up removing it after the deprecation since it is no longer useful in the new design language.

**Comment by maniax89** [comment]
this also bit one of our projects as we had relied on it existing. for now we are going to pin our dependency package to `~10.9`

**Comment by joshblack** [comment]
Note for folks commenting on this PR, created a new PR to reintroduce this mixin and then add an official deprecation path for this utility: https://github.com/carbon-design-system/carbon/pull/5812

**Pull request merged**
