### PR TITLE
fix(code-snippet): use inverse-02 for copy-btn-feedback token

### LINKED ISSUE #3202: [Code snippet] Dark themes, "Copied" tooltip styling wrong
"Copied" tooltip styling is wrong in dark themes. Need to double check that tooltip is using below color tokens:

Tooltip background : `$inverse-02`
Tooltip text : `$inverse-01`

**Current:** 

image

**Should be**

image

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3202 

#### Changelog

**Changed**

- `$inverse-02` for `$copy-btn-feedback` theme token

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by asudoh — COMMENTED** [review]
Thank you for jumping in @jendowns - Just one question - Any reason behind not updating `$copy-btn-feedback` with `$inverse-02` but doing direct assignment?

**Comment by jendowns** [comment]
Hey @asudoh! Sorry I should have written my reasoning in the issue description 😅 I was following something similar that I did in this issue: https://github.com/carbon-design-system/carbon/pull/3424  Since the `$copy-btn-feedback` was used in one place, and the new token `$inverse-02` is themed already, the abstraction seemed unnecessary so I made an assumption & deprecated it. What do you think?

**Comment by asudoh** [comment]
OK AFAIK we have a notion of component-specific theming, though it's applied to limited areas. Such component-specific theming creates two layers of abstraction, one with global theme, another with component-specific theme. Does this make sense to you?

**Comment by jendowns** [comment]
Yeah that makes sense — my question is more like: what’s the purpose of continuing to single out this particular color for this particular component, and abstract it into another file? 

When I was hunting for this token to change the color, it took me longer than normal because the color doesn’t come from the tooltip, and then the token in the code snippet is defined in another file.

So the downside of continuing to use ‘$copy-btn-feedback’ is the abstraction makes it slightly more time consuming to find. And also, you lose the benefit of seeing ‘@carbon/themes’ tokens tell a story in a single file. You can understand right away in a single scss file what a certain intention is with a component’s colors (in this case, inverted colors) and perhaps even quickly tell how diff tokens would appear beside/with each other.

But the plus side of keeping ‘$copy-btn-feedback’ is not clear to me?

**Comment by asudoh** [comment]
@jendowns Actually we are not singling out that particular color. If you take a look at [`_theme-tokens.scss`](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/components/src/globals/scss/_theme-tokens.scss) where component-specific theme tokens are, you'll see what colors (in what components) employs two-layered color tokens (e.g. [here](https://github.com/carbon-design-system/carbon/blob/v10.3.0/packages/components/src/globals/scss/_theme-tokens.scss#L169-L179)), and how to follow color token definitions with following such two layers.

You also seem to have a question wrt why we have component-specific theme tokens, AFAIK it's for allowing applications to change theme of a particular component.

Do these make sense? I appreciate your thoughts and your questioning wrt trying to eliminate possibly redundant things, just wanted to share the history of the codebase and what approach will possibly achieve what you wanted to fix in the existing codebase.

**Comment by jendowns** [comment]
Thanks @asudoh! I think I'm still a little fuzzy on why the layer is necessary, but either way it's all good -- I just pushed an update to un-deprecate `$copy-btn-feedback` & set that token to `$inverse-02`. I appreciate all of the context 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks you for the update and again for your thoughts @jendowns!

**Pull request merged**
