### PR TITLE
fix(accordion-skeleton): add margin between icon & text when align=end

### LINKED ISSUE #4962: [AccordionSkeleton]: margins around arrow icon are off when `align="end"`
## Detailed description

When `align="end"` for the `AccordionSkeleton`, the margins appear off (i.e., flush with no margins / colliding) around the arrow icon:
Screen Shot 2020-01-07 at 11 20 54 AM

You can see the margin issue in the React storybook environment here: http://react.carbondesignsystem.com/?path=/story/accordion--skeleton

To me it seems like a good solution would be the mirror the same spacing for the `align="start"` variation.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4962

#### Changelog

**Changed**

- add left margin, to give more spacing between icon & text when `align` prop is set to `"end"`

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Can we do 16px instead of 8px after the skeleton header line and before the chevron to be consistent with the other spacings?

Screen Shot 2020-01-08 at 11 25 57 AM

**Comment by jendowns** [comment]
Thanks @laurenmrice! I just updated that left margin from `spacing-03` to `spacing-05`

**Comment by laurenmrice** [comment]
@jendowns thanks jen!  the react deploy failed  but once they are up again i will review

**Review by aledavila — APPROVED** [review]

**Comment by jendowns** [comment]
@laurenmrice it looks like the React deployment is finally working, so it should be good to look at now 👀

**Review by abbeyhrt — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
looks good, thank you !

**Pull request merged**
