### PR TITLE
Fix(dropdown)inline field height not adapting to prop size change

### LINKED ISSUE #5966: [dropdown] inline field height not adapting to prop size change
The `inline dropdown field` is not changing in height when changing the size prop. The menus are changing in height, just not the top field. 

--------------------------------------------------------------------------------------------------

#### Here is an example using the Default (40px) size:
dropdown-usage-2 copy 3

### PR DESCRIPTION
**Pull request by code-blooded-developer**
Closes #5966

Inline dropdown does not change the height is changed the size prop

#### Changelog
**Removed**

- Default height from the inline list box and dropdown

#### Testing / Reviewing

Just open the storybook and play with dropdown by changing the type to inline and size.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me pending visual review. in the future please check the issue assignment to see if it's already WIP

**Comment by code-blooded-developer** [comment]
@emyarod sure will do

**Review by laurenmrice — APPROVED** [review]
looks good to me! thanks for fixing this 🙌🏻

**Review by tw15egan — APPROVED** [review]
Thanks for the quick fix 👍 ✅ 🎉

**Review by joshblack — APPROVED** [review]

**Pull request merged**
