### PR TITLE
Fix <FlexGrid> closing tag

### PR DESCRIPTION
**Pull request by asihej**
**Changed**

- Fix closing tag for <FlexGrid>, missing "/" (slash)

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM once you accept the DCO agreement

**Review by abbeyhrt — APPROVED** [review]

**Comment by joshblack** [comment]
@asihej should be good to go after you follow the steps from this comment! https://github.com/carbon-design-system/carbon/pull/11699#issuecomment-1169826485

**Comment by tw15egan** [comment]
@asihej can you just comment on the DCO agreement so we can merge this in? Thanks!

**Comment by asihej** [comment]
Sorry for the delay guys. 😞
I have read the DCO document and I hereby sign the DCO.

**Comment by tw15egan** [comment]
No worries @asihej ! However, I believe the DCO signature needs to be in its own comment to trigger the action 🙃

**Pull request closed without merging**
