### PR TITLE
feat(inline-loading): add JavaScript component

### PR DESCRIPTION
**Pull request by asudoh**
## Overview

This PR adds live demo of inline loading component, by adding a JavaScript component.

CC @loganmccaul 

### Added

* `InlineLoading` JavaScript class
* Unit test for above

## Testing / Reviewing

Testing should make sure inline loading component is not broken.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Looks like both states are showing at once for me? Toggle state button doesn't seem to do anything.
screen shot 2018-07-20 at 10 32 35 am

**Comment by asudoh** [comment]
@alisonjoseph My apologies - The "Toggle state" button is demo-only code which requires additional code to work in the top-level page. Pushed a fix.

**Review by alisonjoseph — APPROVED** [review]
LGTM! Thanks

**Review by aledavila — APPROVED** [review]

**Comment by loganmccaul** [comment]
@asudoh You are amazing! This has been on my to do list for a few weeks and I haven't found time to do it. Thanks so much for tackling this!!

I totally owe you one 😄

**Pull request merged**
