### PR TITLE
chore(build): introduce CircleCI

### PR DESCRIPTION
**Pull request by asudoh**
#### Changelog

**New**

- `.circleci/config.yml`

#### Testing / Reviewing

Testing should make sure CircleCI works well.

### CODE REVIEW

**Comment by asudoh** [comment]
@shinytoyrobots @alisonjoseph - Something I was talking with @joshblack today. An file addition, not affecting others. OK to put it in `v10`? Thanks!

**Review by joshblack — APPROVED** [review]

**Review by shinytoyrobots — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]
🙌

**Review by emyarod — APPROVED** [review]
looks good to me!

just wondering, do we want to install dependencies from offline mirrors like the React repo?

**Comment by joshblack** [comment]
@emyarod I think we should, maybe in post-v10?

**Pull request merged**
