### PR TITLE
fix(multiselect): close button for tags

### LINKED ISSUE #4888: [MultiSelect]: the X icon is in the wrong position
Looking at the MultiSelect component [here](https://carbon-components-react.netlify.com/?path=/story/multiselect--default), `Close16` is completely to the right of the input box 

Screen Shot 2019-12-16 at 10 43 16 AM
Screen Shot 2019-12-16 at 10 42 10 AM

### PR DESCRIPTION
**Pull request by aledavila**
Closes #4888

Close svg for tags was not aligned. 

#### Changelog

**Removed**

- absolute positioning for close svg 

#### Testing / Reviewing

Make sure tag filter and multi select tags are working and close button is positioned correctly.

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]
This looks good to me as far as I can tell. Tag w/ filter looks the same and Multiselect is back to normal!

**Comment by abbeyhrt** [comment]
Could someone check this on IE11? Every time i've seen
 ```   
  top: 50%;	
  transform: translateY(-50%);
```
it's to address positioning there but I don't have a windows VM anymore to check.

**Comment by aledavila** [comment]
@abbeyhrt just checked and it seems fine. There's an issue with the arrow on multiselect but it shouldn't be connected as this is styling for svg of tag. 

Screen Shot 2019-12-16 at 3 51 51 PM
Screen Shot 2019-12-16 at 3 50 58 PM

**Comment by joshblack** [comment]
For design reviewers, it seems like our MultiSelect had a visual regression when making a selection (the X icon was misaligned). This PR should address it in all browsers.

**Comment by abbeyhrt** [comment]
Thank you for checking! @aledavila

**Review by joshblack — APPROVED** [review]

**Review by designertyler — APPROVED** [review]
LGTM

**Pull request merged**
