### PR TITLE
fix(data-table): fix row sizing with overflow menu

### LINKED ISSUE #4586: Table with overflow menu is showing bigger rows and vertically misaligned row content
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description
First reported here: https://github.com/IBM/carbon-components-angular/issues/886

This issue follows from that, as this appears to be a styling bug

## Steps to reproduce the issue

https://angular.carbondesignsystem.com/?path=/story/table--with-overflow-menu

https://react.carbondesignsystem.com/?path=/story/datatable--with-overflow-menu

## Additional information

It appears that the `2rem` height on the overflow menu button is interfering with the row styles

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/4586

Adds some negative margins so that `OverflowMenu` does not affect row sizing. Can be seen in our Storybook: https://react.carbondesignsystem.com/?path=/story/datatable--with-overflow-menu

Solution found here: https://github.com/IBM/carbon-components-angular/issues/886#issuecomment-550005367

#### Changelog

**New**

- Data Table specific Overflow Menu overrides. It should work for all table sizes. 

#### Testing / Reviewing

Make sure Overflow Menu is positioned properly on all size Data Tables, and does not increase the row height

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Comment by jeanservaas** [comment]
@tw15egan looks like react deploy failed.

**Comment by tw15egan** [comment]
@jeanservaas should be up now 👍

**Comment by abbeyhrt** [comment]
@tw15egan I don't think this needs to be addressed in this PR but it seems like the DataTable `with boolean column` story has the same problem

**Review by abbeyhrt — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Review by jeanservaas — APPROVED** [review]
nice!

**Pull request merged**
