### PR TITLE
fix: add area-describedby to components that use helperText

### LINKED ISSUE #12722: [a11y]: Dropdown does not use aria-describedby to link help text with component
### Package

@carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

React storybook

### React version

https://react.carbondesignsystem.com/?path=/story/components-multiselect--default

### Automated testing tool and ruleset

n/a

### Assistive technology

JAWS

### Description

Any helper text should be automatically surfaced to assistive technologies through the use of aria-describedby.
This should happen on ALL Carbon components that can have helper text.
it is in place for Text input, so it only needs to be emulated for Dropdown/MultiSelect Dropdown and any other components that do not have it
image
Steps to resolve:
1. Given the div holding the helper text an appropriate ID
2. use this ID with aria-describedby on the div holding the input.

This means that the input will have its programmatic label announced by a Screen Reader, and then have any helper text read out after a pause.

It also means that any caution or warning text appearing in the helper text area will also be announced.

### WCAG 2.1 Violation

https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-multiselect--default

### Steps to reproduce

1. Inspect the Helper text and confirm there is no ID associated with it.
2. If ID exists, inspect input and confirm there is no use of aria-describedby

OR
Turn on JAWS and tab to Dropdown. JAWS will read the input and any option value, but will not announce the helper text.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #12722 

Adds `aria-describedby` attribute to components that use helperText:

- [x] Multiselect
- [x] Dropdown
- [x] Combobox
- [x] DatePickerInput
- [x] NumberInput
- [x] ProgressBar
- [x] Select
- [x] TextArea
- [x] ControlledPasswordInput
- [x] PasswordInput
- [x] RadioButtonGroup -- todo: confirm with michael

#### Changelog

**Changed**

-  Added `aria-describedby` attribute in `Multiselect`, `Dropdown`, `Combobox`, `DatePickerInput`, `NumberInput`, `Select`, `ProgressBar`,`TextArea`, `ControlledPasswordInput`, `PasswordInput`, `RadioButtonGroup`

#### Testing / Reviewing

Components should behave and look exactly the same. Voiceover now reads helper text when focused on input

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
Tested all components and all are working as intended. 

One little thing, do we want to add helperText to the Playground Argtypes for DatePicker?

 ```
 helperText: {
    control: { type: 'text' },
    table: {
      category: 'DatePickerInput',
    },
  },
```

**Comment by francinelucca** [comment]
> Tested all components and all are working as intended.
> 
> One little thing, do we want to add helperText to the Playground Argtypes for DatePicker?
> 
> ```
> helperText: {
>    control: { type: 'text' },
>    table: {
>      category: 'DatePickerInput',
>    },
>  },
> ```

done!

**Review by aledavila — APPROVED** [review]

**Comment by aledavila** [comment]
LGTM! one thing I just merged in `helperText` for `RadioButtonGroup`. Could you add the `aria-describedby` to that component as well if you can please TIA

**Review by andreancardona — APPROVED** [review]
😎

**Comment by francinelucca** [comment]
Resubmitting for review. 

For RadioButtonGroup and CheckboxGroup I tried setting the `aria-describedby` on the `legend` instead of the `fieldset` but got the same result. couldn't get mac's VoiceOver to read it. For both instances the accessibility tree correctly shows the description text:
image
image

so I decided to leave it in the fieldset. I found this proof case that saw voiceover skipping over the aria-describedby in fieldset in VoiceOver while other a11y tools did read it https://russmaxdesign.github.io/accessible-forms/fieldset-error02.html 
FYI @mbgower

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by andreancardona — APPROVED** [review]

**Pull request merged**
