### PR TITLE
fix(UIshell): adds story for SkipToContent and removes the tabIndex prop requirement

### LINKED ISSUE #4802: [SkipToContent]: no documentation, fails DAP contrast, unnecessary required prop
The `SkipToContent` component and it's functionality are critical to accessible apps, we should definitely be polishing this.

Issues with the `SkipToContent` component:
- this component's existance/props are effectively undocumented (even in stories where it is used) storybook isn't picking up many of individual the shell components
- the component fails DAP contrast static analysis. DAP is comparing the default link color to the shell background. This could be fixed by making the link white at all times, not just during focus.
- The component **requires** an href but provides one as a default. Even in our stories, we don't provide one. Allowing use of default is fine, we shouldn't throw prop-type warnings when folks do so.

1. Navigate to [a story using `SkipToContent`]( https://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation-and-actions)
2. Click show info. Notice no prop table or story source
3. Run DAP

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #4802

This PR adds a story that more explicitly shows the use of `SkipToContent`. Because we use render props in all of the current stories that use `SkipToContent`, the Story Source doesn't provide prop tables or component names for them.

Example from Header Base w/ Navigation, Actions, and SideNav:
 
Screen Shot 2019-12-13 at 11 19 36 AM

The new story shows all of the components used and their prop tables and is the only story that shows the code example for SkipToContent. 

I'm waiting on confirmation from Sharon Sniders, but I believe the DAP violation related to SKipToContent is coming from when it is not visible and is not present when it is visible so it might not need to be addressed. If it does, #4865 will resolve the DAP violation. 

In the comment for the `tabIndex` proptype check, it is described as optional so I removed the `.isRequired` from the check and changed the comment for the `children` prop since it seemed to be describing the wrong thing. 

#### Changelog

**New**

- UIShell story to illustrate `SkipToContent` use

**Changed**

- A link added to `StoryContent` so there is something to tab to when `SkipToContent` is used. 
- Description of 'children' prop

**Removed**

- `.isRequired` from `tabIndex` proptype check 

#### Testing / Reviewing

Look at the story source for the new UIShell Story "Header Base w/ SkipToContent" and decide if we want this story included!

### CODE REVIEW

**Review by aledavila — COMMENTED** [review]
Yay! You figured it out. A story for it I think is better since we had a hard time finding it in the first place. Just one question is the typeIndex prop changing from required to optional a breaking change ?  I don’t think so but just making sure.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @abbeyhrt!

**Comment by abbeyhrt** [comment]
If it was going from not required to required, it definitely would be but since it shouldn’t affect anybody using tabIndex prop, I think we’re good? @joshblack, what do you think?

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
It should be good! I think it falls under:

https://github.com/carbon-design-system/carbon/blob/master/docs/guides/versioning.md#an-existing-prop-type-is-changed-to-be-more-generic

**Pull request merged**
