### PR TITLE
fix(tabs): hover style bugs

### LINKED ISSUE #13490: [Bug]: Default tabs do not have a hover state change
### Package

@carbon/react

### Browser

Chrome

### Package version

1.26.0

### React version

^17.0.2

### Description

Default tabs do not have a visual change on hover (hover state)

https://user-images.githubusercontent.com/40550942/230505814-3d191e92-4ee6-468e-8b06-dcc0980da074.mov

Note: this may need a design spec (what should the hover state look like?)

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-tabs--default

### Steps to reproduce

1. Hover over an unselected Tab
2. Notice no visual change indicating hover state

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #13490 

#### Changelog

**Changed**

- fix background, text and border color for tab hover

#### Testing / Reviewing

Check that tabs and contained tabs match spec in issue

### CODE REVIEW

**Review by andreancardona — APPROVED** [review]
checked it out, looks good 🔥

**Review by tay1orjones — APPROVED** [review]

**Comment by alisonjoseph** [comment]
@tay1orjones these are just hover styles, so I don't think Percy would test for that, right?

**Comment by tay1orjones** [comment]
Ah right, that makes total sense. Percy isn't snapshotting hover states. All good!

**Review by laurenmrice — APPROVED** [review]
LGTM!

**Pull request merged**
