### PR TITLE
fix: add missing pages to the carbon react index

### PR DESCRIPTION
**Pull request by mattrosno**
As found in https://github.com/carbon-design-system/carbon-platform/issues/907, this PR fixes some Carbon React indexing issues.

#### Changelog

**New**

Carbon React:

- Get started page
- Tutorial FAQ
- Ordered list and Unordered list docs (this will eventually get cleaned up in https://github.com/carbon-design-system/carbon-platform/issues/1374)

**Changed**

- N/A

**Removed**

- N/A

#### Testing / Reviewing

See comments below.

### CODE REVIEW

**Comment by mattrosno** [comment]
Usage, Style, and Accessibility page tabs now show up for `Ordered list` and `Unordered list` React components. For now, the page headers still say `List` here because the remote MDX source says `List`:
image

It's a known issue that there is a large gap above the Color heading here:
image

Other Accessibility page tabs don't render as well because of invalid imports. We're okay with this as it's a public beta. If we want, we should remove the imports in carbon-website. For example: https://next.carbondesignsystem.com/libraries/carbon-react/latest/assets/code-snippet/accessibility
image

**Comment by mattrosno** [comment]
React tutorial FAQ page:
image

**Comment by mattrosno** [comment]
Carbon React get started content:
image

**Review by alisonjoseph — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Review by francinelucca — CHANGES_REQUESTED** [review]
Confirmed can render library pages and see asset tabs, cannot render accessibilityPath for either component
image

**Comment by francinelucca** [comment]
why do we want to index a tab that won't render? 🤔 wouldn't it be better to hold off on it for now if we can't fix it? or keep it in but commented out

**Review by francinelucca — APPROVED** [review]

**Pull request merged**
