### PR TITLE
fix(structured-list): top align header text

### LINKED ISSUE #8157: Support _row_ headings for `StructuredList`
### Summary

I would like to have row headings for a `StructuredList`.

### Justification

I seek formatting akin to a dictionary, where there is a meaningful term on the left, and an elaboration for the term on the right:

unneeded | column headings
-- | --
**Purpose** | elaborate on purpose here
**Result** | elaborate on result... this is a long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long
**Associations** | list of associations...

Note that GitHub Markdown displays the row heading centered, above.

When I try to use the `head` attribute for the first `StructuredListCell` of a `StructuredListRow` the text formatting is applied, but the alignment of the field drops to the bottom, which looks awkward:
image

### Desired UX and success metrics

I seek a visibly distinct row heading which is even with the top line of the other cells in the row, or centered, or, ideally, a simple way to select which behavior is desired.

### "Must have" functionality

Row headings, bold by default, centered or top aligned.

### Specific timeline issues / requests

Nothing specific. 2021?

### Available extra resources

n/a

### PR DESCRIPTION
**Pull request by emyarod**
Closes #8157
related #721
related #753

This PR top aligns headers so that they stay aligned with non-header text in structured lists

#### Testing / Reviewing

Apply the header class to a list row cell and check its vertical alignment

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Looks good to me 👍

**Comment by tw15egan** [comment]
Should we check if the header is part of `tbody`, and if so change the line-height to match the rest of the row? It's currently getting the header line-height of `1.29` but the rest of the row has a `1.43` line-height 

Screen Shot 2021-03-23 at 4 05 38 PM

**Comment by emyarod** [comment]
the line heights are set by our type mixins so we will need to see if they need to be updated

**Review by laurenmrice — APPROVED** [review]
Looks good 🚀

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
