### PR TITLE
fix(table): remove default browser outline on table row focus

### PR DESCRIPTION
**Pull request by aliciahickman**
## Overview

fixing table row focus things

### Added

`outline: 0` for table rows on hover and focus

### Removed

redundant scss block for first-child row hover and focus

### CODE REVIEW

**Comment by aliciahickman** [comment]
sorry for confusion, just saw that the previous was reverted. Will try again with it all in one, ha

**Comment by aliciahickman** [comment]
trying again :)

**Comment by marijohannessen** [comment]
table
I'm seeing this issue when hovering over the table rows, but it looks like this is happening on the master branch as well.

**Comment by chrisdhanaraj** [comment]
Hey @aliciahickman - could you fix the merge conflict and see @marijohannessen comment? Could you include the updates with your first PR that includes the fix for both the focus and the hover

**Comment by aliciahickman** [comment]
@chrisdhanaraj 
This fix was working beautifully on my local, but both @tw15egan and @marijohannessen got this strange hovering problem. I can't reproduce what they're seeing :\

**Pull request closed without merging**
