### PR TITLE
fix(listbox): allows children prop to be node type, remove unused childrenOf prop-types utility

### LINKED ISSUE #3636: Setting ComboBox prop "invalid" to true gives warning in console
## What package(s) are you using?

- [x] `carbon-components` -> version 10.4.0
- [x] `carbon-components-react` -> version 7.4.1

## Detailed description

> Describe in detail the issue you're having.

I am trying to use the ComboBox component but when the "invalid" prop is given a value of true, the following warning is logged in the console:

Warning: Failed prop type: Invalid prop `children` of type `Unknown` supplied to `ListBoxField`, expected each child to be one of: `[ListBoxMenuIcon, ListBoxSelection, span, input]`.
   in ListBoxField (created by Downshift)
   in Downshift (created by ComboBox)
   in div (created by ComboBox)
   in ComboBox (at CreateProjectDialog.js:520)
You can reproduce this issue by looking at this codesandbox: https://codesandbox.io/embed/codesandbox-wrm5h

> Is this issue related to a specific component?
Yes, ComboBox

> What did you expect to happen? What happened instead? What would you like to
> see changed?
There should be no warning in the console when you set the 'invalid' prop to true in a ComboBox

> What browser are you working in?
Chrome and Edge

> What version of the Carbon Design System are you using?
Carbon-Components version 10.4.0
carbon-components-react version 7.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
DBA Studio, no

## Steps to reproduce the issue

1. Just open the codesandbox and look at the console. Also note that the error only occurs when the invalid prop is set to true. No warnings are logged if its set to false.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

https://codesandbox.io/embed/codesandbox-wrm5h

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3636 

#### Changelog

**Changed**

- `ListBox` prop `children` accepts `node`
-`ListBoxField` prop `children` accepts `node`

**Removed**

- Delete `childrenOf` propTypes utility (and related test file) since it is no longer used

### CODE REVIEW

**Comment by tw15egan** [comment]
I still seem to be getting the warning, since the type being passed down is ❓`unknown` ❓

Taking a look

**Comment by tw15egan** [comment]
Is there any reason why we can't just use `PropTypes.node`? I'm not quite sure why we weren't using that here anyway, as that's what we seem to use for most `children` types. Looks like `ListBox` is the only one using `childrenOf` ...

**Comment by jendowns** [comment]
Hey @tw15egan! I'm happy to change it to `PropTypes.node`, if that's what you'd prefer?

For now I've specified `WarningFilled16` in my latest commit, since it is used similarly here: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/ListBox/ListBox.js#L76

Looks like `ListBox` and `ListBoxField` are the only 2 components that use this particular kind of propTypes checking: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/prop-types/childrenOf.js

Is it necessary that `ListBoxField` be so strict for the props checking? 🤔

**Comment by tw15egan** [comment]
I'm pretty unfamiliar with this component, so I'll let @emyarod or @asudoh chime in as well.

**Comment by asudoh** [comment]
From https://github.com/carbon-design-system/carbon-components-react/blob/v5/src/components/ListBox/ListBox.js, seems that the original author didn't anticipate more complex React tree structure that has happened since then. That said, I'd agree with `node`.

**Comment by joshblack** [comment]
The original intent was to restrict the field and then have the list grow over time given usage feedback 👍 When first building this out, it was intended to only work with the pieces listed out and there was an unknown around if we could make it fully support any nested child.

**Comment by jendowns** [comment]
Thanks @joshblack & @asudoh! So just to confirm -- 

- Would you like for me to go ahead and make this `ListBoxField` children allow `node`? 
- Should `ListBox` children also allow `node`?
- If `ListBoxField` and `ListBox` children should allow `node`, would you like for me to delete the "childrenOf" propTypes utility, since it will no longer be required? (Only ListBox & ListBoxField use it, as far as I can tell) https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/prop-types/childrenOf.js

**Comment by joshblack** [comment]
@jendowns definitely down if you want to update all uses of `childrenOf` and remove it from the codebase 👍

**Comment by jendowns** [comment]
Okay sounds great! Changes are in now 👍

**Review by tw15egan — APPROVED** [review]
Thanks for fixing this, @jendowns! LGTM 👍

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
