### PR TITLE
Focus states: Text input, Text area, Number input

### PR DESCRIPTION
**Pull request by marijohannessen**
## Overview

Resolves https://github.ibm.com/Bluemix/design-system-website/issues/1077
Resolves https://github.ibm.com/Bluemix/design-system-website/issues/1068

Updated focus states for text input, text area and number input.

### CODE REVIEW

**Comment by tw15egan** [comment]
👍 ✅ ❗️ Getting a double focus on text-area, but everything else looks good!

**Comment by marijohannessen** [comment]
@tw15egan Do you have Grammarly activated? The double focus went away for me when I deactivated the Chrome extension on localhost.

**Comment by tw15egan** [comment]
Ahhh yup, that was it.

**Comment by hellobrian** [comment]
👍 ✅

**Pull request merged**
