### PR TITLE
fix(data-table): update skeleton style for v10

### LINKED ISSUE #3032: Update DataTableSkeleton component to v10
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

I'm using the DataTableSkeleton component as a loading pattern before the data from my DataTable renders. The difference in styles is creating a lot of jumping and repositioning. 

> Is this issue related to a specific component?

DataTableSkeleton component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I expected to see the v10 styles on the skeleton component. It still had v9 which caused the header styles and rows to be a bit different, and it didn't include the table title and description.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

This was discovered while working on the Developer Essentials tutorial

## Steps to reproduce the issue

1. Run the 3rd Tutorial step (completed) to see the DataTableSkeleton load in with different styles. 

## Additional information

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3032.

#### Changelog

**Changed**

- Skeleton style update for `v10`.

#### Testing / Reviewing

Testing should make sure data table skeleton is not broken.

### CODE REVIEW

**Review by aagonzales — CHANGES_REQUESTED** [review]
Can we actually remove the icons from the toolbar. I know they're in the spec images but now I think its better if they weren't shown because when the table loads it might not have those exact icons. 

image

**Comment by asudoh** [comment]
> now I think its better if they weren't shown because when the table loads it might not have those exact icons.

Got it @aagonzales - Updated.

**Review by tw15egan — APPROVED** [review]
🎉 👍 ✅

**Review by joshblack — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
Perfect!

**Pull request merged**
