### PR TITLE
fix(ui-shell): fix onclick menu bugs

### LINKED ISSUE #4413: React Sidenav Rail - Broken Interactions In Storybook
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Almost any interaction with the sidenav menu's results in peculiar behavior. Expanding all of the menus and then clicking any of the items then collapses all of the menus. Clicking one submenu has also resulted in another sidenav menu expanding or all of them being expanded again.

> Is this issue related to a specific component?

Sidenav Rail

> What browser are you working in?

Chrome Version 77.0.3865.120

> What version of the Carbon Design System are you using?

v10.7.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Rocket Software

## Steps to reproduce the issue

1. Open the storybook and navigate to either of the rail stories of the ui shell
2. Click to expand all of the sidenav menus
3. Click on any of the items of the sidenav menus

### LINKED ISSUE #4718: [UI shell] [react] Last header menu item dropdown is not expanded on click
While using Header menu and header menu items the **last menu item** is not expanded.

Packages and components used:
 
   HeaderNavigation,
   HeaderMenu,
   HeaderMenuItem

- [ ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

 Please navigate to this [codesandbox url]( https://codesandbox.io/s/header-with-actions-and-nav-2pf3p) and click the `Link 5` menu item then `Link  4`.

When I click `Link4 ` the sub menu items open and close properly whereas when I click `Link 5` the sub menu items open and close immediately. Also just clicking the `Link 5` when the `Link 4` is clicked the `Link 5` sub menu items open.

> Is this issue related to a specific component?

Yes. React UI Shell with Header actions and Nav
> What did you expect to happen? What happened instead? What would you like to
> see changed?

On clicking the menu item it should be active(expanded).

> What browser are you working in?

Google
> What version of the Carbon Design System are you using?

- carbon-components -10.4.1
- carbon-components-react -7.4.1

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/header-with-actions-and-nav-2pf3p

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/4718
Closes https://github.com/carbon-design-system/carbon/issues/4413

Issue 1 can be seen here: https://codesandbox.io/s/header-with-actions-and-nav-qre4k

For some reason, `will-change: transform` that is hardcoded on the SVG was causing issues on expansion in a few instances in `UI-shell`

#### Changelog

**Changed**

- Use `ChevronDown16` instead of `ChevronDownGlyph`

**Removed**

- unset `will-change` property on the chevron SVG's

#### Testing / Reviewing

Check the CodeSandbox, inspect the chevron SVG, and remove the `will-change` property. See how the dropdown works properly when this is removed.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Review by aagonzales — APPROVED** [review]
LGTM

**Review by xxxle0 — APPROVED** [review]

**Comment by xxxle0** [comment]
@tw15egan, i saw we have a lots of SVG have this property will-change: transform. I think we should investigate what is actual behavior of it. How do you think ?

**Comment by tw15egan** [comment]
@xxxle0 agreed, would like to know why this is causing issues

**Review by emyarod — COMMENTED** [review]
not sure why `will-change` needs to be on our icons by default, but if it's not necessary we could remove it from the icon builder package instead of overriding in UI shell

**Comment by tw15egan** [comment]
@emyarod I'm not sure why it is there by default either, @joshblack any idea where that attribute is coming from/if it is needed?

**Comment by joshblack** [comment]
Ah yeah, it has a specific purpose for rendering correctly in Firefox 😞 Reference: https://github.com/carbon-design-system/carbon/blob/master/packages/icon-helpers/src/getAttributes.js#L15-L17

https://github.com/ckeditor/ckeditor5/issues/668#issuecomment-344846429

It could easily not be needed anymore, but it did come up with our icons last year.

**Comment by emyarod** [comment]
it seems to be unnecessary now so we can probably remove it as well (https://github.com/ckeditor/ckeditor5/issues/1053 https://github.com/ckeditor/ckeditor5-ui/pull/529)? I didn't notice any blurriness when reviewing @tw15egan's PR on Firefox

**Comment by joshblack** [comment]
@emyarod nice, then yeah can 100% remove it upstream

**Comment by tw15egan** [comment]
@asudoh @emyarod @joshblack updated the PR to simply remove adding the `will-change: transform` to all SVG elements, as the reason for its addition _seems_ to be resolved on the Firefox end.

**Comment by joshblack** [comment]
@tw15egan it seems like the preview for icons from netlify ran into an issue 🤔

image

I believe it's related to this line: https://github.com/carbon-design-system/carbon/blob/master/packages/icons/examples/preview/index.js#L203-L204 which was assuming `style` was always defined and was a string, but now it's `undefined` and caused the preview to fial.

**Comment by tw15egan** [comment]
@joshblack should be resolved now

**Comment by joshblack** [comment]
🔥

**Review by joshblack — APPROVED** [review]

**Pull request merged**
