### PR TITLE
fix(text-input): position experimental password visibility toggle

### LINKED ISSUE #1734: Experimental password inputs broken
The experimental component changes did not account for the password visibility toggle introduced in #1060 so they look like this:

image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1734

Related: #1058 #1060

This PR styles the password visibility toggle for the experimental text input. It also accounts for the new experimental error states and icon prefixes

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by asudoh** [comment]
@emyarod Could you fix the default options test case...? Thanks!

**Comment by emyarod** [comment]
yes it should be resolved now @asudoh

**Comment by joshblack** [comment]
Would other frameworks need to set the data attribute in order for styles to be applied?

**Comment by emyarod** [comment]
I refactored it to avoid selecting data attributes

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
