### PR TITLE
fix(components): remove @carbon/icons from peerDependencies

### PR DESCRIPTION
**Pull request by joshblack**
We currently don't' use `@carbon/icons` in our Vanilla JS and this will prompt folks to install an additional dependency even if they won't use it directly, or if code they use from the library does not use it. Let me know if I'm missing a place where it's being used!

For reference, without this change folks would technically need to install the following packages to remove warnings:

```bash
npm install carbon-components @carbon/icons carbon-components-react carbon-icons
```

#### Changelog

**New**

**Changed**

- Update `package.json` for `components` to not have peerDependencies

**Removed**

### CODE REVIEW

**Review by vpicone — APPROVED** [review]

**Comment by asudoh** [comment]
Vanilla users need to write the HTML by their own. That said, how can vanilla users get the SVG contents without `@carbon/icons`?

**Comment by joshblack** [comment]
@asudoh I believe the dependency is still valid/needed to install, just that it doesn't need to be listed as a peer dependency 👍

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by asudoh** [comment]
@joshblack Did you want to add `@carbon/icons` to `dependencies` you mean...?

**Comment by joshblack** [comment]
@asudoh I think if a team would like to use the package they can install it, but there should no need to rely on `carbon-components` listing it as a dependency or peer dependency if the library itself does not use it.

Listing it as a peer dependency would lead to the warning in projects even if they don't need or want that dependency, and would be frustrating given that the library itself doesn't use it. Listing it as a dependency would mean that folks are consuming the dependency through hoisted node_modules which would lead to unintended behavior.

 If the library is using it in code, we 100% can bring it in but it seemed like that was not the case.

**Review by asudoh — APPROVED** [review]
Signing off based on @joshblack's latest response, though in most of the use cases of vanilla library application code needs `@carbon/icons` (or copy contents from it) to create its markup.

**Pull request merged**
