### PR TITLE
fix: implement unique dynamic id generation for FileUploader component

### LINKED ISSUE #17556: [a11y]: File uploader has static `id` that can cause conflicts
### Package

@carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

1.66.0

### React version

_No response_

### Automated testing tool and ruleset

devtools

### Assistive technology

_No response_

### Description

File uploader id are not unique:
- description has `id="description"` -> expected more complex id with incremental value like `fileuploader-description-1`
- label has `id="id1" -> expected more complex id like `fileuploader-input-1`

See screenshot 
image

File uploader could have ids like ie. Select - https://github.com/carbon-design-system/carbon/blob/a9bddc814172e64c1b617affda9e9b71b42350f1/packages/react/src/components/Select/Select.tsx#L209
Unique ID tool could have also similar complexity as above. https://github.com/carbon-design-system/carbon/blob/36685a0be5e62db11a60d938c76b1c49a402c99a/packages/react/src/tools/uniqueId.js#L8-L13

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://react.carbondesignsystem.com/?path=/docs/components-fileuploader--overview

### Steps to reproduce

1. check html of file uploader in storybook or in app

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Shankar-CodeJunkie**
Closes #17556

[{{short description}}](fix: implement unique dynamic id generation for FileUploader component)

- Replaced the Class component for FileUploader with functional component to use `useId` internal react hook

**Changed**
src/components/FileUploader/FileUploader.tsx

#### Testing / Reviewing

1. I have ran `yarn storybook` and confirmed that the FileUploader component now generates a unique id and it is being used in the component. 

Image

### CODE REVIEW

**Comment by Shankar-CodeJunkie** [comment]
I am working on to resolve the unit test failures for FileUploader component ..   I will fix the issue and push the changes by tomorrow 

```
FAIL packages/react/src/components/FileUploader/__tests__/FileUploader-test.js
  ● FileUploader › should clear all uploaded files when `clearFiles` is called on a ref

    TypeError: Cannot read properties of null (reading 'clearFiles')
    ```

**Comment by Shankar-CodeJunkie** [comment]
- I have fixed the above unit test failure, and now I am getting test failure on snapshot 

```● Public API should only change with a semver change

    expect(received).toMatchSnapshot()

    Snapshot name: `Public API should only change with a semver change 1`

    - Snapshot  - 3
    + Received  + 2

    @@ -3262,13 +3262,11 @@
            },
```

I will fix the above as well and push the updates to the PR

**Review by tay1orjones — APPROVED** [review]
Thanks for doing this! LGTM

**Review by guidari — APPROVED** [review]
Awesome change! Thanks!

**Pull request merged**
