### PR TITLE
chore(devenv): cope with PORT_SASS_DEV_BUILD not being defined

### PR DESCRIPTION
**Pull request by asudoh**
🙏 

#### Changelog

**New**

- Some code to make deployment to CF (an environment without PORT_SASS_DEV_BUILD) work again.

#### Testing / Reviewing

Testing should make sure our dev env is not broken.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
One note that might be worthwhile to fix in a subsequent update:

screen shot 2018-09-06 at 9 57 12 am

**Comment by asudoh** [comment]
@joshblack Seems that you tried to use the theme switcher, which wasn't meant to be supported for the use in CF. My apologies for the confusion - Did a couple of things to address that:

1. Disabled theme switcher in such env
2. Introduced `gulp build:dev --rollup -e` (meaning, the last `-e` option) to see the "next" version in CF build

**Comment by tw15egan** [comment]
@asudoh, would it be possible to enable a version of the dev environment to be deployed to a staging URL? Jeoff was thinking we could use that to share with stakeholders the progress of the current components mapping to the experimental components. 

I thought this was an easier solution than enabling the experimental components on the main website

**Review by alisonjoseph — APPROVED** [review]

**Comment by asudoh** [comment]
@tw15egan Yes - You can do this by:

```sh
> gulp build:dev --rollup -e
> cf push
```

**Pull request merged**
