### PR TITLE
fix(button): remove margin added by safari

### LINKED ISSUE #5155: Need to remove Safari's automatic margins around buttons
## What package(s) are you using?
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Safari places an automatic `2px margin` around all buttons and this needs to be removed because it's causing some misalignments (see screenshot below)

> Is this issue related to a specific component?

This issue is related to the `Button` component

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expect no automatic margins around buttons throughout the application, as seen in other browsers Chrome/Firefox/Edge

> What browser are you working in?

Safari 12.1.1 (14607.2.6.1.1)

> What version of the Carbon Design System are you using?

 `carbon-components: ^10.7.4`,
 `carbon-components-react: ^7.7.4`,

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Watson Assistant

## Steps to reproduce the issue

1. Open reduced test case in a Safari browser
2. Right click on 'Hello world' button > Inspect Element
3. Navigate to Computed tab
4. Scroll all the way down and see Box Model of button with `2px margin` all around

> Please create a reduced test case in CodeSandbox

https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information
Auto margin causes right-side misalignment of 'Create intent' on an intents page:
Screen Shot 2020-01-23 at 12 37 04 PM

Related pr:
https://github.ibm.com/watson-engagement-advisor/wea-conversational-ui/pull/6006

Related issue:
https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/33926

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/pull/5155

Removes margin placed on `button` by Safari

#### Changelog

**New**

- Safari specific selector to remove default borders on `button`

#### Testing / Reviewing

Ensure there is no 2px margin when viewing buttons on Safari.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thank you for jumping in @tw15egan! Just wondered if the Safari margin stuff should be in button reset style. Applying this to `.bx--btn` is fine, though.

**Comment by tw15egan** [comment]
> Just wondered if the Safari margin stuff should be in button reset style.

I just want to make sure users who are not using our reset still get the safari fix. We could put in both places, I guess?

**Comment by asudoh** [comment]
Yes both will make sense. Thanks @tw15egan for clarifying!

**Comment by tw15egan** [comment]
@asudoh updated, let me know if this works 👍

**Comment by asudoh** [comment]
Thank you for the update @tw15egan! Looks basically good, just one question; Do we want `margin: 0` regardless of non-Safari future UA style sheet change, or do we have any reason to limit the change to Safari only...?

**Comment by tw15egan** [comment]
Hmm, that's a good point. I guess we might as well just remove all margin from buttons, I can update it to that.

**Review by asudoh — APPROVED** [review]
Thanks @tw15egan for the update!

**Review by emyarod — APPROVED** [review]
looks good to me, the margins are now reset in safari

image

**Pull request merged**
