### PR TITLE
fix(styles): change form helper text mt

### LINKED ISSUE #11905: [Bug]: Form helper-text margin should be 8px
### Package

carbon-components-react

### Browser

Chrome

### Package version

v1.8.0

### React version

_No response_

### Description

The helper text for the form component is wrong. The margin-top is coming in at 4px but it should be **8px**.

image

### Reproduction/example

n/a

### Steps to reproduce

n/a

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by falsepopsky**
Closes #11905

#### Changelog

**New**

- Fix style margin-top

**Changed**

- Change the margin-top style on `#{$prefix}--form__helper-text` in the package `styles/comp/form` with `$spacing-03`

**Removed**

- $spacing-02

#### Testing / Reviewing

1. yarn build
2. yarn storybook on react package
3. Check the styles on the component `TextInput default`

form

----

4. Check deploy [preview](https://deploy-preview-11909--carbon-components-react.netlify.app/?path=/story/components-textinput--default)

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]
Looks good! 🎉 Thank you for the contribution!

**Review by tw15egan — APPROVED** [review]
LGTM, thanks for contributing back so quickly 👍 ✅

**Comment by aagonzales** [comment]
Yes, thank you for contributing! It was just pointed out that some of our docs actually say it should be 4px so I'm circling back to the other designers to confirm what the margin should officially be before approving.

**Review by aledavila — APPROVED** [review]

**Comment by aagonzales** [comment]
Unfortunately, @jeanservaas and I were wrong about this. It should actually remain 4px. We misremembered. All the docs and assets have it at 4 not 8. 

Our apologies for jumping the gun. Thanks so much for submitting the PR though @falsepopsky. This PR can be closed.

**Pull request closed without merging**
