### PR TITLE
fix(select): remove label on svg chevron

### LINKED ISSUE #3449: AVT 3 - React Pagination, JAWS does not read pagination text
## Environment
Windows 10 
FireFox Quantum 68.0
JAWS 18

## Description
1. Tab to Pagination Component, VO announces the items per page and the arrow keys should be used to change the selection in the dropdown.
2. Insert-Arrow to read the text across the pagination component and the items per page number changes.
Expected result: Focus should move to the text in the pagination and announce "1-30 of 103 items"
3. Tab to the next dropdown VO announces the page number of 4 pages as expected. 
4. Insert - Left arrow to navigate back across the pagination component to read the test and the page number changes.
Expected result: Focus should move to the text in the pagination and announce "1-30 of 103 items"

### LINKED ISSUE #3451: AVT 3 - React Pagination Component, iOS/VoiceOver navigation issues in dropdown and on images
## Environment
iOS 12.3.1
Safari
VoiceOver

## Description
1. Swipe R to the items per page dropdown, VO announces the number of items per page as expected.
2. Double-tap to activate the picker, VO doesn't say anything.
3. Swipe Right and nothing happens
4. Swipe Down and VO announces, "Form control not found"
5. Swipe Left and VO announces the last select in the drop-down.
6. Make a select other than 10, Focus moves out of pagination. 
7. Tab back to the first pagination dropdown and then swipe right, VO announces "open list of options image".
Note: Same issue exists when changing the number per page.
**Expected Result:** Swipe R should navigation down the list and when a select is made user should remain where they left off. When reading across the pagination the images should be ignored by the screen reader.

### LINKED ISSUE #4222: AVT 1 - Select Icon has DAP violations
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon v10 - React
DAP IBM Accessibility 1.8.0.0 Sept 2019 Ruleset

## Detailed Description
Go to the React Form Component 
Run DAP and the following violations are present (see screenshot):
Screen Shot 2019-10-04 at 9 08 15 AM

### PR DESCRIPTION
**Pull request by joshblack**
Closes #3451
Closes #3449
Closes #4222

#### Changelog

**New**

**Changed**

- Remove `aria-label` and `role="img"` from icon
- Deprecate `iconDescription` prop
- Remove tests for `iconDescription`

**Removed**

#### Testing / Reviewing

- Verify no DAP violations exist for the icon (which had `role="img"`):
  - [ ] Pagination
  - [ ] Select
- Verify fixes closed issues on JAWS and VoiceOver

### CODE REVIEW

**Comment by joshblack** [comment]
@aledavila @abbeyhrt @dakahn let me know if you want to go over the PR!

**Review by dakahn — APPROVED** [review]
Great!

**Comment by dakahn** [comment]
Sounds good. Checked with JAWS and NVDA on Win10 with Edge and Chrome latest.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Pull request merged**
