### PR TITLE
docs(storybook): use storybook-addon-accessibility-checker

### PR DESCRIPTION
**Pull request by tay1orjones**
The IBM Accessibility team has been working on a modified/forked @storybook/addon-a11y that serves the same purpose but allows the engine to be configurable to use accessibility-checker instead of axe. This PR is for testing the addon.

#### Changelog

**New**

- Use `storybook-addon-accessibility-checker` instead of `@storybook/addon-a11y`

#### Testing / Reviewing

- Look through the storybook and review the reported accessibility items in the addon pane, things should report correctly. 
- If we find any false positives or other issues, report them below

### CODE REVIEW

**Review by tay1orjones — COMMENTED** [review]
I'm seeing some errors when navigating to different stories, can anyone else confirm?

Screenshot 2023-10-23 at 8 44 19 PM

Screenshot 2023-10-23 at 8 44 37 PM

**Review by tay1orjones — COMMENTED** [review]
After resolving the yarn dedupe ci failure it looks like the issue is now resolved, but please flag if anyong sees the failures again.

**Comment by andreancardona** [comment]
> I'm seeing some errors when navigating to different stories, can anyone else confirm?
> 
> Screenshot 2023-10-23 at 8 44 19 PM Screenshot 2023-10-23 at 8 44 37 PM

I'm seeing these warnings also :/

**Comment by tay1orjones** [comment]
Hey @tombrunet we're unfortunately seeing some issues with this. I'm not sure exactly what the culprit is 🤔

**Comment by tay1orjones** [comment]
The latest rc of the addon fixes these issues, thanks @tombrunet!

**Review by andreancardona — APPROVED** [review]
looks good to me!

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
