### PR TITLE
fix: pagination nav adjacent double ellipses

### LINKED ISSUE #17628: [Pagination] Fix Adjacent ellipses in PaginationNav
Bug issue: https://github.com/carbon-design-system/carbon/issues/15830
Closes https://github.com/carbon-design-system/carbon/issues/15830

```[tasklist]
### Tasks
- [x] Create design specs for Pagination
- [x] Implement the specs for Pagination
```

### Design Specs

Image

### PR DESCRIPTION
**Pull request by riddhybansal**
Closes #17628 

Fix pagination nav adjacent ellipses 

#### Changelog

**New**

- Added logic and test case for page ===0

#### Testing / Reviewing

Render with props itemsShown = 4, totalItems = something >= 10
Select a page from the ellipses
Select the first page
There should not be adjacent elleipses

### CODE REVIEW

**Comment by guidari** [comment]
Hey @riddhybansal 
I pull down locally to check the test. It is passing regarding it has the fix or not.

I guess the best way to test that is to replicate the behaviour we did together while testing the fix.
- Click on `PaginationOverflow` to page 6.
- Click on the first `PaginationOverflow` to page 1
- Check if the page 2 is visible, which means the first `PaginationOverflow` is not being rendered as expected

I'm happy to pair on that if needed.

**Review by thyhmdo — APPROVED** [review]
Looks great!

**Comment by riddhybansal** [comment]
> Hey @riddhybansal I pull down locally to check the test. It is passing regarding it has the fix or not.
> 
> I guess the best way to test that is to replicate the behaviour we did together while testing the fix.
> 
> * Click on `PaginationOverflow` to page 6.
> * Click on the first `PaginationOverflow` to page 1
> * Check if the page 2 is visible, which means the first `PaginationOverflow` is not being rendered as expected
> 
> I'm happy to pair on that if needed.

Yeah , Got what you are saying .. Added the test case for more clear testing !! This is indirectly testing the overflow menu behaviour in the pagination nav also. Please check and do let me know !!

**Review by guidari — APPROVED** [review]
Awesome! LGTM 🚀

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Pull request merged**
