### PR TITLE
fix(select): align inline label and helper text

### LINKED ISSUE #2096: Inline invalid select title and helper text misaligned
image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2096

This PR fixes the alignment of invalid inline select labels and helper text

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
This LGTM! 

quick question, did we move away from styling `[data-invalid]` and using invalid classes instead across all form elements?

**Review by joshblack — APPROVED** [review]

**Comment by emyarod** [comment]
@alisonjoseph no we didn't, it's just that the `data-invalid` attribute selection no longer worked with some of our updated markup, so some helper classes were added. But we should probably refactor all form elements to be consistent about where the attribute is placed like in https://github.com/IBM/carbon-components/pull/2024

I refactored to remove the helper class @alisonjoseph

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by asudoh** [comment]
@aagonzales Please don't hesitate to speak up if you see any problems - Thanks!

**Pull request merged**
