### PR TITLE
feat(icons-react): reintroduce entrypoint with new icon strategy

### LINKED ISSUE #2707: [icons-react] GA Requirements
## Requirements

- [ ] Single module entrypoint
  - `icons-react/es/index.js`
  - `icons-react/lib/index.js`
- [ ] Icon module entrypoints
  - `icons-react/<icon-name>/package.json`
  - `icons-react/<icon-name>/<size>/package.json`
- [ ] Common `Icon` component as base

### `<Icon>` component

High-level:

```js
import { getAttributes } from "@carbon/icon-helpers";
import * as React from "react";

const Icon = React.forwardRef(function Icon(
  { className, children, style, tabIndex, ...rest },
  ref
) {
  const { tabindex, ...props } = getAttributes({
    ...rest,
    tabindex: tabIndex
  });
  if (className) {
    props.className = className;
  }
  if (tabindex !== undefined && tabindex !== null) {
    props.tabIndex = tabindex;
  }
  if (typeof style === "object") {
    props.style = {
      ...defaultStyle,
      ...style
    };
  } else {
    props.style = defaultStyle;
  }
  if (ref) {
    props.ref = ref;
  }

  return <svg {...props}>{children}</svg>;
});

Icon.propTypes = {
  // ...
};

Icon.defaultProps = {
  // ...
};
```

#### Specific icon component

```js
import * as React from 'react';
import { Icon } from './Icon';

const CustomIcon = React.forwardRef(function CustomIcon({ children, ...rest }, ref) {
  return (
    <Icon {...rest} ref={ref}>
      <path d="..." />
      {children}
    </Icon>
  );
});

CustomIcon.propTypes = {
  // ...
};

CustomIcon.defaultProps = {
  // ...
};
```

### PR DESCRIPTION
**Pull request by joshblack**
Closes #2707 

Updates `@carbon/icons-react` with new GA requirements.

#### Changelog

**New**

- `@carbon/upgrade`
  - Now has a migration for `@carbon/icons-react@10.4.0`. This has been applied to the react codebase to test that it works

**Changed**

The `@carbon/icons-react` package now uses a base `Icon` component found in `src/Icon.js`, tests have been updated in `src/__tests__/Icon-test.js` 👍 

The build script has also been updated to output a component per entry found in our icon build metadata. This means that each component takes on the form:

```js
const Icon16 = /*#__PURE__*/ React.forwardRef(function Icon16(props, ref) {
  return (
    <Icon width={16} height={16} viewBox="0 0 16 16" ref={ref} {...props}>
      <path d="..." />
    </Icon>
  );
});
```

We annotate this functions as pure so that they can be properly tree-shaken 👍 

In addition, we have re-introduced the entrypoint for ES2015 modules and CommonJS modules. The gzip size of this file is approximately `96.6kB` but can be tree-shaken down to just `icon-helpers`, `<Icon>`, and any components that are used.

Finally, these icons have been updated in the React codebase with the new import signatures.

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
@dakahn @carmacleod would you all have time to help validate that the icons function as expected? We have a couple of situations:

- By default, icons are un-focusable and are hidden to screen readers with `aria-hidden`

```html
<svg
  focusable="false"
  preserveAspectRatio="xMidYMid meet"
  xmlns="http://www.w3.org/2000/svg"
  width="32"
  height="32"
  viewBox="0 0 32 32"
  aria-hidden="true"
  style="will-change: transform;"
>
  <path
    d="M16 2C8.3 2 2 8.3 2 16s6.3 14 14 14 14-6.3 14-14S23.7 2 16 2zm-2 19.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
  ></path>
  <path
    d="M14 21.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
    data-icon-path="inner-path"
    opacity="0"
  ></path>
</svg>
```

- Developers can optionally add `aria-label` or `aria-labelledby`, this sets `role="img"` and removes `aria-hidden`. Note: this does _not_ treat the SVG as focusable

```html
<svg
  focusable="false"
  preserveAspectRatio="xMidYMid meet"
  aria-label="Label"
  xmlns="http://www.w3.org/2000/svg"
  width="32"
  height="32"
  viewBox="0 0 32 32"
  role="img"
  style="will-change: transform;"
>
  <path
    d="M16 2C8.3 2 2 8.3 2 16s6.3 14 14 14 14-6.3 14-14S23.7 2 16 2zm-2 19.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
  ></path>
  <path
    d="M14 21.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
    data-icon-path="inner-path"
    opacity="0"
  ></path>
</svg>
```

- Developers can optionally add `aria-label` or `aria-labelledby` alongside `tabindex` to allow the SVG to be focusable

```html
<svg
  focusable="true"
  preserveAspectRatio="xMidYMid meet"
  aria-label="Label"
  xmlns="http://www.w3.org/2000/svg"
  width="32"
  height="32"
  viewBox="0 0 32 32"
  role="img"
  tabindex="0"
  style="will-change: transform;"
>
  <path
    d="M16 2C8.3 2 2 8.3 2 16s6.3 14 14 14 14-6.3 14-14S23.7 2 16 2zm-2 19.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
  ></path>
  <path
    d="M14 21.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
    data-icon-path="inner-path"
    opacity="0"
  ></path>
</svg>
```

**Comment by joshblack** [comment]
Note to reviewers: CI build will fail until we update in the react package. Am saving this to try out the upgrade package to help with automatically updating files to use the new signature 👍

**Review by dakahn — CHANGES_REQUESTED** [review]
While researching and reviewing this PR I came across a credible and recent source that mentions that any SVG children should receive an `aria-hidden=true`:

_"If an SVG’s code is fully inlined, then unnecessary child elements and content should be optimized away. paths and any other direct child elements of the SVG should receive an aria-hidden="true" if they contain no information that should be made accessible."_

ref: https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html

Which I'm thinking would look something like this:
```html
<svg
  focusable="false"
  preserveAspectRatio="xMidYMid meet"
  xmlns="http://www.w3.org/2000/svg"
  width="32"
  height="32"
  viewBox="0 0 32 32"
  aria-hidden="true"
  style="will-change: transform;"
>
  <path aria-hidden="true"
    d="M16 2C8.3 2 2 8.3 2 16s6.3 14 14 14 14-6.3 14-14S23.7 2 16 2zm-2 19.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
  ></path>
  <path aria-hidden="true"
    d="M14 21.5l-5-5 1.6-1.5 3.4 3.4 7.4-7.4 1.6 1.6-9 8.9z"
    data-icon-path="inner-path"
    opacity="0"
  ></path>
</svg>
```

**Comment by joshblack** [comment]
@dakahn don't we fall under this section? https://www.scottohara.me/blog/2019/05/22/contextual-images-svgs-and-a11y.html#svgs-that-are-decorative

**Review by emyarod — COMMENTED** [review]
are the license header deletions in the UI shell components intentional?

on a side note could we start annotating the functions in our build packages? I think it would help reviewers and maintainers

**Comment by joshblack** [comment]
@emyarod ooo good catch, forget to preserve leading comments in the codemod 🤦‍♂️

For build functions, which ones are you referring to? In the case of: https://github.com/carbon-design-system/carbon/pull/3078/files#diff-6637b3afe65ec5a69c5a716ea74587b8 what annotations would have helped make it more clear?

**Comment by emyarod** [comment]
@joshblack I think JSDoc style annotations with parameter types and descriptions would generally be helpful

**Comment by joshblack** [comment]
@emyarod okay, just was wondering what specific knowledge these things could communicate that the code itself is not getting across.

**Comment by joshblack** [comment]
@emyarod updated with more docs and fixed the leading comment issue, I think 👍

**Review by dakahn — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
leading comment issue looks resolved, thanks for the annotations in the upgrade package!

**Review by dakahn — CHANGES_REQUESTED** [review]
We spoke offline, but it looks like adding `aria-hidden` to an accessible SVG's children might be worth doing after all 👍

**Review by dakahn — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
Looks good to me 👍

**Review by dakahn — CHANGES_REQUESTED** [review]
as per @joshblack request

**Review by dakahn — APPROVED** [review]
Great! Ran DAP 2019 ruleset on the demo page and it looks chill. 🏄

**Pull request merged**
