### PR TITLE
fix(sketch): update shared color names to include space

### LINKED ISSUE #267: AVT violation on modal of close button
Using URL http://carbondesignsystem.com/components/modal/live

Click Passive button and popup the modal, run the DAP test, and getting AVT violation of close button on the modal.

image

### LINKED ISSUE #267: [IDL v2 kit] need space between / for colors
We need to have a space between the "/" int he naming convention of color styles to be consistent with the rest of the kits.

Ex of current:
Screen Shot 2020-01-17 at 2 14 39 PM

### PR DESCRIPTION
**Pull request by joshblack**
Closes https://github.com/carbon-design-system/carbon-design-kit/issues/267

Update shared style name to include spaces around the dividing `/`.

image

#### Changelog

**New**

**Changed**

- Include space around dividing `/` in shared color names

**Removed**

### CODE REVIEW

**Comment by laurenmrice** [comment]
Thanks for putting a space between the `/` !  

We do not need a space though between the dashes and color name. gray - 40, for example. Those should be `gray-40` with no space. This is how we are treating it for our color tokens when they have a dash, so I just want to stay consistent with that. 👍🏻

**Comment by joshblack** [comment]
Lol, thanks for the catch @laurenmrice! I'll fix it 🤦‍♂️

**Comment by joshblack** [comment]
@laurenmrice updated!

**Review by laurenmrice — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by joshblack** [comment]
Ah shoot, made the mistake of merging in too soon @aledavila 

Let me know if you would want to go over this stuff and/or if you have any concerns about the e changes!

**Comment by aledavila** [comment]
@joshblack no it seems good to me. Understanding more now

**Pull request merged**
