### PR TITLE
feat(data-table-v2): add selectable row styles

### PR DESCRIPTION
**Pull request by jnm2377**
Ref: #1303 

- Adds selectable table styles. 
_Note: batch actions has still not been styled, this is specifically just row styles._

### CODE REVIEW

**Review by dakahn — APPROVED** [review]
👍🏽

**Review by aledavila — APPROVED** [review]
yayy !

**Comment by designertyler** [comment]
There's an extra 12px padding to the left and right of each `td` and 8px on `th` text. This causes the spacing to be too large between the checkbox and text. 

Screen Shot 2019-03-25 at 1 19 05 PM

The checkbox component is not 1-to-1 with design specs. That's a checkbox issue, but we would want to make sure it can be updated in data table when that's resolved. 

Screen Shot 2019-03-25 at 1 10 26 PM

**Review by designertyler — APPROVED** [review]
Selectable rows look good

**Pull request merged**
