### PR TITLE
feat(Dropdown): add hideTitleText prop

### PR DESCRIPTION
**Pull request by molyholy1**
Closes #

Addresses this issue https://github.com/carbon-design-system/carbon/issues/7571

#### Changelog

**New**

- Add a `hideTitleText` prop for the Dropdown. The `titleText` will still exist programatically but hiding it visually lends itself to smoother design (especially with inline Dropdowns). This sort of prop also exists in the Select component.

#### Testing / Reviewing
1. Start up the React Storybook and navigate to the Dropdown component
2. In the code, pass in the `hideTitleText` prop
3. (Optional but highly recommended) Run the [IBM Equal Accessibility Checker](https://www.ibm.com/able/toolkit/) with `hideTitleText` being true. There should not be an error for "The WAI-ARIA property must reference a non-empty unique id of an existing element that is visible"  which normally occurs when the `titleText` is missing entirely. However, because we have hidden it visually but not programatically, the error shouldn't appear.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
would you mind renaming the prop to `hideLabel` to match the other Carbon components? also it looks like you will need to update snapshots in order to pass CI

edit: yeah it looks like only the listbox components use "title" instead of "label" but this may need to be updated in the future to match the existing components like TextInput, Select, etc.

**Comment by brawl1111** [comment]
> would you mind renaming the prop to `hideLabel` to match the other Carbon components? also it looks like you will need to update snapshots in order to pass CI

Yep! I only changed it to `hideLabel` cuz there isn't a `label` prop for Dropdowns but yeah I can change it 👍

**Review by tw15egan — APPROVED** [review]
Not seeing any a11y errors with the `hideLabel` prop enabled. Thanks for contributing! LGTM 👍 ✅

**Review by kingtraceyj — APPROVED** [review]
looks good to me

**Review by emyarod — APPROVED** [review]

**Pull request merged**
