### PR TITLE
feat(UI icons): new icons may and june

### LINKED ISSUE #8788: WarningAltFilled32 icon not supporting "inner-path" for two-tone colors
## What package(s) are you using?

- [x]     "carbon-components": "latest",
- [x]    "carbon-components-react": "latest",
 - [x]   "carbon-icons": "latest",
- [x]   "@carbon/icons": "10.28.0",
 - [x]  "@carbon/icons-react": "10.28.0"

## Detailed description

> Describe in detail the issue you're having.

It looks like WarningAltFilled32 icon should support `[data-icon-path="inner-path"]` (two-tone) from this [issue](https://github.com/carbon-design-system/carbon/issues/5919) but it doesn't seem to be working. 

> Is this issue related to a specific component?

WarningAltFilled32
https://github.com/carbon-design-system/carbon/blob/main/packages/icons/src/svg/32/warning--alt--filled.svg?short_path=192d63c
The problem seems to be the name on this [line](https://github.com/carbon-design-system/carbon/blob/main/packages/icons/src/svg/32/warning--alt--filled.svg?short_path=192d63c#L9) 

It would be nice to add inner-path to the 16px version of `warning--alt--filled.svg`

> What did you expect to happen? What happened instead? What would you like to
> see changed?
- Fix the `inner-path` on packages/icons/src/svg/32/warning--alt--filled.svg
- Add `inner-path` to the 16px sized SVG as well  packages/icons/src/svg/16/warning--alt--filled.svg

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Watson Assistant

## Steps to reproduce the issue

1. Go to the code sandbox
2. View three different icons (WarningAltFilled32, WarningAltFilled16, WarningFilled16)
3. Only one supports `inner-path` currently for two-tone colors

> Please create a reduced test case in CodeSandbox
>
https://codesandbox.io/s/react-and-scss-forked-e0u7o?file=/src/index.js

## Additional information
Screen Shot 2021-05-27 at 4 35 57 PM

### PR DESCRIPTION
**Pull request by conradennis**
Closes #8788

Submitting new and updated UI icons from May and June 2021
all updates and additions approved by BXD

144 net new icons
12 updated icons
5 moved icons
2 new icon categories (Enterprise > App Catalogue, Organization > Systems)
updated categories.yml with additions
updated ui-icon-master.ai with additions and updates

#### Changelog

**New (144 total)**

– svg/glyph--critical-severity
– svg/glyph--low-severity
– 32/application--mobile.svg
– 32/application--virtual.svg
– 32/application--web.svg
– 32/autoscaling.svg
– 32/bare-metal-server.svg
– 32/bastion-host.svg
– 32/block-storage--alt.svg
– 32/block-storage.svg
– 32/carbon-accounting.svg
– 32/cell-tower.svg
– 32/chat--operational.svg
– 32/cloud--alerting.svg
– 32/cloud--auditing.svg
– 32/cloud--logging.svg
– 32/cloud--monitoring.svg
– 32/cloud--service-management.svg
– 32/cloud-services.svg
– 32/code-signing-service.svg
– 32/container-registry.svg
– 32/container-services.svg
– 32/content-delivery-network.svg
– 32/data--center.svg
– 32/data-accessor.svg
– 32/data-backup.svg
– 32/data-blob.svg
– 32/data-diode.svg
– 32/direct-link.svg
– 32/dns-services.svg
– 32/document--protected.svg
– 32/document--security.svg
– 32/document--signed.svg
– 32/document--unprotected.svg
– 32/dog-walker.svg
– 32/drone--delivery.svg
– 32/drone--front.svg
– 32/drone--video.svg
– 32/edge-node--alt.svg
– 32/energy--renewable.svg
– 32/file-storage.svg
– 32/firewall--classic.svg
– 32/firewall.svg
– 32/floating-ip.svg
– 32/flow-logs-vpc.svg
– 32/friendship.svg
– 32/gateway.svg
– 32/gateway--api.svg
– 32/gateway--mail.svg
– 32/gateway--public.svg
– 32/gateway--security.svg
– 32/gateway--user-access.svg
– 32/gateway--vpn.svg
– 32/group--access.svg
– 32/group--account.svg
– 32/group--resource.svg
– 32/group--security.svg
– 32/gui.svg
– 32/gui--management.svg
– 32/hardware-security-module.svg
– 32/hybrid-networking--alt.svg
– 32/ibm-cloud--dedicated-host.svg
– 32/ibm-cloud--internet-services.svg
– 32/ibm-cloud--subnets.svg
– 32/ibm-cloud--vpc-endpoints.svg
– 32/ibm-security--services.svg
– 32/id-management.svg
– 32/image-service.svg
– 32/infrastructure--classic.svg
– 32/instance--bx.svg
– 32/instance--classic.svg
– 32/instance--cx.svg
– 32/instance--mx.svg
– 32/instance--virtual.svg
– 32/intrusion-prevention.svg
– 32/kubernetes.svg
– 32/load-balancer--application.svg
– 32/load-balancer--classic.svg
– 32/load-balancer--global.svg
– 32/load-balancer--listener.svg
– 32/load-balancer--local.svg
– 32/load-balancer--network.svg
– 32/load-balancer--pool.svg
– 32/load-balancer--vpc.svg
– 32/logo--wechat.svg
– 32/message-queue.svg
– 32/mobility--services.svg
– 32/network--enterprise.svg
– 32/network--overlay.svg
– 32/network--public.svg
– 32/object-storage--alt.svg
– 32/phone--application.svg
– 32/phone--settings.svg
– 32/point-of-presence.svg
– 32/radio--combat.svg
– 32/radio--push-to-talk.svg
– 32/replicate.svg
– 32/result.svg
– 32/result--new.svg
– 32/result--old.svg
– 32/router--voice.svg
– 32/router--wifi.svg
– 32/router.svg
– 32/rule--cancelled.svg
– 32/rule--draft.svg
– 32/rule--filled.svg
– 32/rule--test.svg
– 32/security-services.svg
– 32/server--dns.svg
– 32/server--proxy.svg
– 32/server--time.svg
– 32/sim-card.svg
– 32/slisor.svg
– 32/solar-panel.svg
– 32/subnet-acl-rules.svg
– 32/switch-layer-2.svg
– 32/switch-layer-3.svg
– 32/temperature--celsius.svg
– 32/temperature--celsius--alt.svg
– 32/temperature--fahrenheit.svg
– 32/temperature--fahrenheit--alt.svg
– 32/train--profile.svg
– 32/train--speed.svg
– 32/transmission-lte.svg
– 32/two-factor-authentication.svg
– 32/user--military.svg
– 32/user--service-desk.svg
– 32/user--settings.svg
– 32/vehicle--api.svg
– 32/vehicle--connected.svg
– 32/vehicle--insights.svg
– 32/vehicle--services.svg
– 32/version.svg
– 32/virtual-desktop.svg
– 32/vlan.svg
– 32/vlan--ibm.svg
– 32/vpn--connection.svg
– 32/vpn--policy.svg
– 32/wifi-bridge.svg
– 32/wifi-bridge--alt.svg
– 32/wifi--controller.svg
– 32/wifi--not-secure.svg
– 32/wifi--secure.svg
– 32/wind-power.svg

**Changed (12 total)**

– svg/glyph--undefined
– 32/car.svg
– 32/checkmark--filled--error.svg
– 32/checkmark--filled--warning.svg
– 32/error--filled.svg
– 32/information--filled.svg
– 32/information--square--filled.svg
– 32/logo--linkedin.svg
– 32/pending--filled.svg
– 32/warning--alt--filled.svg
– 32/warning--alt-inverted--filled.svg
– 32/warning--hex--filled.svg

**Moved Categories (5 total)**

– 32/cloud-foundry--1
– 32/cloud-registry
– 32/cloud-satellite
– 32/cloud--data-ops
– 32/virtual-private-cloud--alt

### CODE REVIEW

**Review by andreancardona — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@laurenmrice the preview might still not be working, let me take a look at it for this PR and I'll see if I can figure out what's going on 🤔

**Comment by laurenmrice** [comment]
@joshblack ok sounds good!

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by conradennis** [comment]
@jeanservaas I added the two glyphs to this PR

**Comment by joshblack** [comment]
@conradennis would it be possible if the `glyph--` prefixed assets could instead not have `glyph--` in front of their names? In other words, `glyph--critical` would become `critical`. I think that, by default, we're assuming that icons in `src/svg` that aren't under a size are glyphs and so the names are being generated strangely (like `GlyphCriticalGlyph`)

**Comment by joshblack** [comment]
@laurenmrice should be good to go to review!

**Review by laurenmrice — APPROVED** [review]
Looks great! 🎉🚀

**Comment by LMapes** [comment]
@vpicone  Hi Vince, The updates to metadata for app icons have not been made live yet. Not sure what I missed doing here, but the code names are displaying on the IDL library page. Please advise.

**Comment by tw15egan** [comment]
@LMapes it looks like you pushed to this PR once it had already been merged. Can you create a new PR with the changes you had made?

**Comment by LMapes** [comment]
@tw15egan no, I don't know how to create a new PR.

**Pull request merged**
