### PR TITLE
fix(FloatingMenu): position calc in scroll element

### PR DESCRIPTION
**Pull request by jakubfaliszewski**
### Related Issue: #5768
[REACT]
This is fix for FloatingMenus placed in a different elements than `body` and are scrollable.
Details of problem can be find in Issue linked above - I present there bug referencing Tooltip and OverflowMenu, but, in the end, this bug is related to FloatingMenu.

#### Tooltip
<details>
  <summary>Standard behavior</summary>

   
</details>
<details>
  <summary>Wrong implementation</summary>

> Attribute `data-floating-menu-container` is not set to scrollable container.
image

</details>
<details>
  <summary>Tooltip in scrollable container</summary>
  
> Attribute `data-floating-menu-container` **is** set to scrollable container along with `position: relative`. 

</details>
<details>
  <summary>Complex layout</summary>
 

</details>

<details>
  <summary>Top position</summary>
 
image

</details>

#### OverflowMenu
<details>
  <summary>Standard behavior</summary>

</details>

<details>
  <summary>In scrollable container</summary>

</details>

### CODE REVIEW

**Comment by asudoh** [comment]
Hi @jakubfaliszewski :wave: thank you for reporting the issue and jumping in to fix it! In the scenario of non-`position:static` floating menu container, I'd like the floating menu code to switch to an algorithm of simply diffing the positoin of the trigger button and the position of the floating menu container, similar to [the one in date picker](https://github.com/carbon-design-system/carbon/blob/v10.10.0/packages/react/src/components/DatePicker/plugins/appendToPlugin.js#L20-L48).

Would you want to try that? I think it can be started by adding a parameter to [`getFloatingPosition()`](https://github.com/carbon-design-system/carbon/blob/v10.10.0/packages/react/src/internal/FloatingMenu.js#L265-L273), say `containerPosition`, which is the `getBoundingClientRect()`'s result of the floating menu container if the floating menu container has non-`position:static` computed style, and `undefined` otherwise. Then we can subtract the `left`/`top` of `containerPosition` from [the result of `getFloatingPosition()`](https://github.com/carbon-design-system/carbon/blob/v10.10.0/packages/react/src/internal/FloatingMenu.js#L98-L113) and ignore `scrollX`/`scrollY`, if `containerPosition` is available.

Please don't hesitate to let me know if you have any questions - Thanks!

**Comment by jakubfaliszewski** [comment]
@asudoh Thanks for this quick response 😄 
I'll give this solution a try, thank you for this clever idea.

**Comment by jakubfaliszewski** [comment]
New commit ready! Simpler and better, thank you so much 🎉

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jakubfaliszewski for your quick update!

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
