### PR TITLE
fix(code-snippet): update component to spec

### PR DESCRIPTION
**Pull request by emyarod**
Part of #7159

This PR adds an active style to the code snippet copy buttons and repositions the button to be aligned with the "show more" chevron in multiline snippets.

#### Changelog

**New**

- copy button active styles

**Changed**

- multiline code snippet copy button positioning
- light hover token for copy button

#### Testing / Reviewing

Confirm the code snippet matches the spec

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- The light prop needs to also have an active state change for the copying functionality for inline/single line/multi-line code snippets. It is not showing up. 

- I think the multi-line code snippet copy button is too large which is why it is misaligning with the ghost button below it. It needs to be a 32px icon button instead of 40px.
Artboard

**Comment by laurenmrice** [comment]
So it was noticed that we need to make a token for `active-light-ui` for the light prop to achieve the correct colors.
$active-light-ui

Also for the current `hover-light-ui` token, it would be better to have calculated hover values for the dark themes like we do for the light themes.
$hover-light-ui

**Comment by emyarod** [comment]
new active token and hover token updates will be here https://github.com/carbon-design-system/carbon/pull/7275

**Comment by emyarod** [comment]
currently waiting on #7275 for dark theme changes

**Review by laurenmrice — CHANGES_REQUESTED** [review]
When the light prop and hide copy functionalities are both on, the inline code snippet is getting a hover. There should be no hover state when hide copy is on.  
Nov-12-2020 11-31-32


Everything else looks great!

**Review by laurenmrice — APPROVED** [review]
Looks great! Thank you 🙌🏻

**Pull request merged**
