### PR TITLE
feat(project): add feature-flags package

### PR DESCRIPTION
**Pull request by joshblack**
This PR adds in first-class support for feature flags ahead of our October release 👀  The package, `@carbon/feature-flags`, provides JavaScript and Sass-based feature flag support with a YML config file for specifying feature flags. Maintainers can use these flags in work for Carbon, and consumers could use the package to build on top of experimental work (if needed) or use it to create their own feature flags.

The `@carbon/feature-flags` package is currently private, and we can move it to public when we set up our first feature flag for the October release if we found that this package helps with our use-cases. If not, we can remove the package as an unsuccessful experiment.

You can view the [README](https://github.com/carbon-design-system/carbon/pull/6401/files#diff-c0296741c3ff0bafc334967ba0d83dbc) to get a better understanding of the Public API of this package.

As a concrete example for maintainers, we might have a feature flag called `enable-component-prop-renaming` where we toggle our prop renaming efforts. In code, this may look like:

```js
import { featureFlagEnabled } from '@carbon/feature-flags';

function MyComponent() {
  // ...
}

if (featureFlagEnabled('enable-component-prop-renaming')) {
  MyComponent.propTypes = {
    b: PropTypes.string,
  };
} else {
  MyComponent.propTypes = {
    a: PropTypes.string,
  };
}
```

Similarly, `feature-flag-enabled` remains available in Sass to be used in component styles 👀 

Consumers will be able to enable these feature flags in JavaScript and Sass, for example:

```js
import { enableFeatureFlag } from '@carbon/feature-flags';

enableFeatureFlag('enable-component-prop-renaming');
```

#### Changelog

**New**

- Add `@carbon/feature-flags` package

**Changed**

**Removed**

### CODE REVIEW

**Comment by tw15egan** [comment]
Oooh, the example makes the prop renaming process much easier! 👍

**Comment by joshblack** [comment]
@tw15egan oh god yes, can't wait 🥳

**Comment by joshblack** [comment]
@tw15egan @dakahn let me know if you have any questions!

**Comment by tw15egan** [comment]
I may be doing something wrong, but for me, it is always setting the PropTypes to whatever is in the `else` statement. I've gone in to `@carbon/feature-flags` and ran `yarn build`. Anything else I need to do? Here's what I've tested with (have tried inside and out of the actual `Container` component)

Accordion.js
```jsx
import { featureFlagEnabled } from '../../../../feature-flags';

if (featureFlagEnabled('enable-component-prop-renaming')) {
  Accordion.propTypes = {
    a: PropTypes.node,
    b: PropTypes.string,
    c: PropTypes.oneOf(['start', 'end']),
  };
} else {
  Accordion.propTypes = {
    children: PropTypes.node,
    className: PropTypes.string,
    align: PropTypes.oneOf(['start', 'end']),
  };
``` 

Container.js

```jsx
import { enableFeatureFlag } from '../../feature-flags';

function Container({ story }) {
  useEffect(() => {
    enableFeatureFlag('enable-component-prop-renaming');
```


feature-flags.yml
```yml
feature-flags:
  - name: enable-css-custom-properties
    description: Describe what the flag does
    enabled: false
  - name: enable-component-prop-renaming
    description: Describe what the flag does
    enabled: false
```

**Comment by joshblack** [comment]
@tw15egan sorry for the delay! This one is a little tricky, basically the flag will need to be loaded/enabled _before_ the Accordion module is loaded. Let me see if I can do an example with storybook real quick 👀

**Comment by dakahn** [comment]
Hiya! So what's the preferred way to test this PR as it stands?

**Review by tw15egan — APPROVED** [review]
LGTM after our meeting this morning 👍

**Review by dakahn — APPROVED** [review]
Thanks for the cool walk through friendo

**Pull request merged**
