### PR TITLE
Overflow menu motion updates

### PR DESCRIPTION
**Pull request by wonilsuh**
## Overview

This request applies the System 360 motion specs to the `overflow-menu` -> `floating-menu` -> `collapsible-element` components.

### `overflow-menu`

- classTransient added
- SCSS updated to utilize the `collapsible-element` component

### `floating-menu`

- updated to utilize the `collapsible-element` component

### Global motion variables

The following variables in the following files were changes to the System 360 specs:

```
// src/components/button/_mixins.scss
$bx--ease-in
$bx--ease-out
$bx--standard-easing
$transition--base
```

Added

```
// src/globals/scss/_vars.scss
$bx--ease-in-out
```

### `@ibm/motion` package

@ibm/motion NPM package was imported as a dev dependency to ensure that the motion definitions are up to date and in sync with other codebases that use the System 360 motion.

- added as a dev dependency
- a proxy was created under `src/globals/js/misc/motion-generator.js`

- Updated bazier curve and duration

## staging URL:
http://carbon-dev-environment-bracteate-akvavit.w3ibm.mybluemix.net/demo/overflow-menu

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM - Let's see the thoughts from other devs in Carbon team.

**Comment by wonilsuh** [comment]
Thanks for all the help @asudoh.

**Comment by marijohannessen** [comment]
Hey @wonilsuh , can you put up a staging URL so the designers on our team can review this as well?

**Comment by wonilsuh** [comment]
@marijohannessen here is a staging URL: http://carbon-dev-environment-bracteate-akvavit.w3ibm.mybluemix.net/demo/overflow-menu

**Comment by aagonzales** [comment]
👀 ❗️ 
It looks like the caret at the top of the menu is disappearing before the transition gets to the top. Something about that last millisecond before the menu is closed feels off.

overflow-menu

**Comment by tay-aitken** [comment]
I slowed down the animation using google dev tools and Anna is right, the caret disappears before the menu starts to close. It also looks like a thin piece of the menu is remaining at the end when the box height is decreasing, than fading away after the fact, as opposed to the whole box disappearing in one fell swoop. I think both these issues need to be addressed before it is merged. 

overflow-menu

**Comment by marijohannessen** [comment]
Hey @wonilsuh ! We're unfortunately going to close these PR's as they are a bit out of date right now, and we want to make sure we add Duo motion in when we're ready to add it to all of our components. Thank you for taking the time to explore motion with our components, and we look forward to continuing this work later this year! 🙂

**Pull request closed without merging**
