### PR TITLE
chore: netlify settings for projects

### PR DESCRIPTION
**Pull request by joshblack**
Update projects to work with new Netlify setup.

#### Changelog

**New**

**Changed**

- Revert changes to `demo` folder
- Update rollup dev config

**Removed**

### CODE REVIEW

**Comment by asudoh** [comment]
@joshblack Pushed a change to make Netlify build of `packages/components` work, but feel free to back out if it doesn't match your intent. Thanks!

**Comment by joshblack** [comment]
Perfect, thanks!

**Review by alisonjoseph — APPROVED** [review]
🎉 LGTM!

**Review by tw15egan — APPROVED** [review]
Nice! 👍

**Pull request merged**
