### PR TITLE
chore(icons): add ci-check for metadata structure

### PR DESCRIPTION
**Pull request by joshblack**
Implements the following CI-time checks for the icon metadata:

- Icons defined in source are missing metadata
- Icon variant defined in source missing in icon metadata
- Icon defined in metadata has structural error (missing variants field)
- Missing/mispelled icons in categories, e.g. an icon exists in categories but does not have a metadata equivalent

#### Changelog

**New**

- `ci-check` command in icons

**Changed**

- `ci-check` command added to icons package

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @chrisconnors-ibm this is the first error we get:

```
Error: The following icons are missing or an error has occurred:
[
  "account",
  "audio-console",
  "branch",
  "carbon",
  "category--add",
  "category--and",
  "category--new-each",
  "category--new",
  "category",
  "concept",
  "enterprise",
  "fog",
  "fork",
  "help-desk",
  "hurricane",
  "language",
  "laptop",
  "no-image",
  "no-ticket",
  "partly-cloudy",
  "service-desk",
  "sunny",
  "sunset",
  "tablet--landscape",
  "tablet",
  "term",
  "text-link--analysis",
  "text-link",
  "text-mining--applier",
  "text-mining",
  "type-pattern",
  "types",
  "3D-software",
  "registration"
]
```

**Comment by vpicone** [comment]
@joshblack Is there any good way for us to make sure all of the fields are of the correct type data type? i.e. all string or all numeric

**Comment by joshblack** [comment]
@vpicone oh for sure, can definitely add that in.

**Comment by joshblack** [comment]
Just updated @vpicone 👍 Joi ftw

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Review by vpicone — APPROVED** [review]
Glad you thought to use Joi here, perfect tool for the job.

**Comment by joshblack** [comment]
After updating the `metadata.yml`, getting this error for categories:

```
Error: The following icons are missing or have been miscategorized:
[
  "non-editable",
  "text--spell-check",
  "overflow-menu",
  "flash--filled--off",
  "arrow--annotation",
  "dropdown-list",
  "SML",
  "travel",
  "connection--signal",
  "toolbox"
]
```

I think we need to do the following:

- `flash--filled--off` -> `flash--of--filled`
- `connection--signal` -> `connection-signal`
- `toolbox` -> `tool-box`
- `dropdown-list` -> `list--dropdown`
- `arrow--annotation` -> `arrow-annotation`
- `non-editable` -> `edit--off`
- Unknown/missing icons
  - `text--spell-check`
  - `overflow-menu`
  - `SML`
  - `travel`

**Comment by conradennis** [comment]
`text--spell-check` -> `spell-check`
`overflow-menu` does not exist -> `overflow-menu--vertical` and `overflow-menu--horizontal` are in repo
`SML` does not exist -> `SQL` is the closest named icon in repo
`travel` -> `plane`

**Pull request merged**
