### PR TITLE
chore(lint): fix style lint errors

### PR DESCRIPTION
**Pull request by tw15egan**
Fixes style linting errors now that #6170 has been merged. 

#### Testing / Reviewing

Ensure form components still render correctly

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Seems great to me! Only question is around if it fixes all violations, if it does holy hell you're amazing, TJ haha. If not, do we want to remove the `lint:styles` from CI check?

**Comment by tw15egan** [comment]
@joshblack It should pass the CI check 👍

**Review by emyarod — APPROVED** [review]

**Comment by joshblack** [comment]
Seems like there might be a stylelint violation @tw15egan maybe from a recent merge:

image

**Comment by tw15egan** [comment]
@joshblack 🧙  fixed

**Pull request merged**
