### PR TITLE
feat(Dropdown): render selected item rich content

### LINKED ISSUE #5576: Render rich content as dropdown selected item
currently the Dropdown only supports rendering string content for the selected item, when it should also render rich content if the dropdown item contains it

related #5519

image

### LINKED ISSUE #5698: Dropdown can not display selected element (string is fine)
## What package(s) are you using?

- [ ] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description
I am using itemToElement to show my dropdown options, but now Dropdown can not show the selected element because the line " {selectedItem ? itemToString(selectedItem) : label}" should try to invoke "itemToElement" if it is available but now only string can be displayed .
```
<ListBox.Field
                  id={id}
                  tabIndex="0"
                  disabled={disabled}
                  aria-disabled={disabled}
                  aria-labelledby={`${labelId} ${fieldLabelId}`}
                  aria-describedby={helperId}
                  {...buttonProps}>
                  <span
                    id={fieldLabelId}
                    className={`${prefix}--list-box__label`}
                    title={selectedItem ? itemToString(selectedItem) : label}
                    {...getLabelProps()}>
                    {selectedItem ? itemToString(selectedItem) : label}
                  </span>
                  <ListBox.MenuIcon
                    isOpen={isOpen}
                    translateWithId={translateWithId}
                  />
                </ListBox.Field>
```

This is my expected result  
image

### PR DESCRIPTION
**Pull request by emyarod**
This PR matches rich content in the selected item to match its appearance in the dropdown options list

Fixes #5576.
Fixes #5698.

#### Testing / Reviewing

Ensure the selected item appears and behaves the same as it does in the dropdown options list

### CODE REVIEW

**Comment by laurenmrice** [comment]
The link for the option number needs to be `link-01` color token

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod! Just one thing in case if you want to do; Would it worth using the new inner-component for each items in the dropdown, too?

**Review by tw15egan — APPROVED** [review]
LGTM 👍

**Comment by emyarod** [comment]
@asudoh do you have any suggestion on what to replace it with for the demo?

**Review by abbeyhrt — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
lgtm!

**Comment by asudoh** [comment]
@emyarod told me that this is ready to merge - Thanks @emyarod! (For the update of `itemToElement`/`itemToString` abstraction, too)

**Comment by joshblack** [comment]
Didn't we end up deciding against doing this in another PR?

https://github.com/carbon-design-system/carbon/pull/4977

Might be misinterpreting, let me know if so!

Related issue: https://github.com/carbon-design-system/carbon/issues/4913

**Comment by emyarod** [comment]
I think this change is warranted as we are finding that users are hacking `itemToString` to render rich content in the selected dropdown item (https://ibm-cloudplatform.slack.com/archives/C2K6RFJ1G/p1583529047246200), and this seems to be a a desired UX feature. it looks like the initial PR was closed due to concerns about potential a11y violations in custom content but that seems to be an application specific issue rather than an issue with the component behavior

**Comment by joshblack** [comment]
@emyarod would we want to support arbitrary rendering in the field, though? It seems like a situation where we would want to constrain markup to only a string in order to stay consistent with visual guidelines along with making sure accessibility is not a concern (in the case of rendering an interactive widget in the field position)

**Comment by emyarod** [comment]
@joshblack yes I believe so, given that design has expressed that this should be the expected behavior (dropdown option appears the same when it is the selected item) and that users are currently hacking `itemToString` to achieve this. as far as a11y concerns go, in this situation it is on the users to not violate a11y especially since they would have more control over what content to place in the dropdown component. but we are not shipping a component with any violations out of the box

**Comment by joshblack** [comment]
Just a quick note, it seems like the storybook environment may be off?
demo

Separately, should we using a link as the example? It seems like this might not pass AVT2 since the link is inoperable?

demo

---

I don't know if there is alignment around this feature with design, I believe they were only made aware of `itemToElement` through this PR. It seems like this feature in a broader sense enables unintended behavior in these controls as noted above. In particular, if we render something like a tooltip it causes problems not only in the option but also in the field position. This may also be unintended behavior if we move this method over as an individual who renders a tooltip in the options list may not want it in the field position.

Overall, this functionally seems to enable teams to create inaccessible and inconsistent UIs that often create a worse experience for users. As a result, I don't think this is functionality that we want to extend into the field position and potentially cause additional problems with this component.

**Comment by emyarod** [comment]
Storybook issue should be resolved now. It seems that the concern is about what our users could potentially come up with. Since we already allow rich content in the options menu we can at least provide the option to render the selected item unchanged as an escape hatch, especially after seeing previous requests for this and how users are currently hacking around component limitations to implement this. I don't see the benefit to attempting to limit this when users are already implementing this behavior (in a broken fashion) with the current component API

**Comment by joshblack** [comment]
> It seems that the concern is about what our users could potentially come up with.

The idea here is that there seems to be no defining use-case for this functionality and that providing it could make it easier to build inaccessible or inconsistent experiences.

Some of the cases that popped up here that we wouldn't want to enable:

- Custom colors in the field or listbox position (inconsistent experience)
- Tooltips in the field or listbox position (inaccessible experience)
- Links in the field or listbox position (inaccessible experience)
- Icons in the field or listbox position (inconsistent experience)

In addition, reusing the API for both option and field could be considered a bug for people who may only want to render the rich content in one place but not the other (even if doing so would provide an inconsistent or inaccessible experience)

Similarly, we should not use a link in our example regardless because it seems to fail AVT2. This type of situation is what we want to avoid. If folks want to hack around stuff to do this, they are well within their rights to do so. It doesn't mean that we make this a common or happy path when it doesn't align with a use-case of this component or the experience that we want folks to leverage while shipping product functionality.

**Comment by joshblack** [comment]
Closing based on above and resolution from support channel 👍 Feel free to reach out if this should be re-opened!

**Pull request closed without merging**
