### PR TITLE
docs(accordion): replace select with button in story

### LINKED ISSUE #4405: AVT 1 - Accordion has DAP violations
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon v10 - React
DAP Version 1.8.0.0 - IBM Accessibility WCAG 2.1 Sept. 2019 Ruleset

## Description
Go to the React Accordion component
Expand all sections
Start DAP and the following violations are present (see screenshot):
Screen Shot 2019-10-21 at 1 18 23 PM

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4405 

As @dakahn suggested in the comment of #4405 , the issue with the DAP violation identified in #4405 for the `Accordion` appears to related to storybook and using a `Select` component inside the accordion's content...

I experimented in the dev console with moving the select elements outside of the accordion's rendered HTML, and the DAP violation went away:

Screen Shot 2019-10-24 at 10 18 57 AM

So I think this is definitely something unique to how the DAP tool is interpreting accordion content that is inserted into the DOM when you open a given accordion 🤔 

I propose replacing the `Select` example with an `Button` example -- this keeps the spirit of the example (that is, having a node / component inside accordion content) while also removing the DAP violation 👍 

#### Changelog

**Changed**

- replace `Select` with `Button` inside the `Accordion` story

#### Testing / Reviewing

View the `Accordion` story in the `carbon-components-react` storybook deployment for this PR, open the 3rd section, and run the DAP tool using the latest Sept 2019 ruleset.

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]
This looks great to me! Thanks @jendowns !

**Review by emyarod — COMMENTED** [review]
I believe the intention of the `<Select>` inside the accordion panel was to demo behavior when a focusable element is in the content area. could we replace it with a different focusable element instead?

**Comment by jendowns** [comment]
Thanks @emyarod! I just replaced the list with a `Button` instead 👍

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
