### PR TITLE
feat(DataTable): add `Slug` to `DataTable` variants 

### LINKED ISSUE #15189: Add AI enhancements to React `DataTable`

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15189

Adds in the ability to add the `Slug` to either a table row or column

#### Changelog

**New**

- `TableSlugRow` component added. Inside `TableRow`, before mapping over the row cells, a user can place the `<TableSlugRow>` component. The `TableSlugRow` component has a `slug` prop to match the other implementations.
- Styles for slug inside a table row and column
- Added a `slug` prop to `TableHeader`

**Changed**

- Modified `TableExpandRow` to ensure the `slug` is placed before the expansion arrow
- Reworked background colors to be applied on the row itself, rather than on each table cell. This was needed to ensure the linear gradient was not hidden under the table cell backgrounds. Any background color applied to a `td` should have been removed from that style block, and applied to one level higher, [example here](https://github.com/carbon-design-system/carbon/pull/15276/files#diff-e683988da838e0ccef52fcf700591850afec7ad94ca732ee5427e4f06fc4e392R537-R549)
- Changed all instances of `background` to `background-color` so that it does not override the `background-image` that provides the linear gradient.  
- Aligned all transitions to be the same speed based on property
- Fixed padding inside expandable table rows if checkbox, checkbox + slug are present
- Updated snapshots

#### Testing / Reviewing

Go to `Experimental --> Slug --> DataTable` and ensure the slug stories render as expected. 

### Notes
- Question for @aagonzales - right now, when the table is unsorted, the sort icon is not visible (only shows on hover). Should the icon always be visible if it is adjacent to the Slug - since it is right aligned, rather than next to the table column label. This is how I have it now, but let me know if this should be changed. 
- The Slug inside the Table Header is running into the same issues as in https://github.com/carbon-design-system/carbon/issues/6728 . The tooltip is cut off unless the `overflow-x` on `table-content` is removed. Hopefully refactoring Popover to use `floating-ui` will resolve these issues

### CODE REVIEW

**Comment by tw15egan** [comment]
@tay1orjones I may break this apart and tackle the `Column` styles separately, since that may make this PR grow quite a bit. This already has quite a few changes to `DataTable`, and I want to make sure we don't have any regressions. Thoughts?
Screenshot 2023-11-28 at 4 29 32 PM

**Review by aagonzales — COMMENTED** [review]
Can we add the gradient just in the column headers like we talked about. So it looks like this: 

image

**Comment by aagonzales** [comment]
>Should the icon always be visible if it is adjacent to the Slug - since it is right aligned, rather than next to the table column label. This is how I have it now, but let me know if this should be changed.

@tw15egan No, I don't think the sort icon should be shown even if it is unsorted, it is visually confusing and actually makes it look like it is sorted. It feels weird to show sort with AI columns but not with the non-ai ones. 

Is that going to cause issues with the slug placements?

**Comment by tw15egan** [comment]
@aagonzales would the slug just stay next to the label when the sort icon is active?

**Comment by aagonzales** [comment]
@tw15egan Yeah I was just thinking that too, something like this instead for sort. Would the unsorted ones still have to have it beside the label, like shown?

image

**Comment by tw15egan** [comment]
Yeah, that way, it also aligns with the unsortable Table headers as well. I can make that change

**Review by aagonzales — APPROVED** [review]
Ok, everything looks good to me now! 👍 ✅

**Review by guidari — APPROVED** [review]
LGTM! 🚀

**Review by tay1orjones — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
💯

**Pull request merged**
