### PR TITLE
fix(notification): make audit adjustments

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/IBM/carbon-components/issues/1845

Changes icon size to 20px.
Ensure green is using `$support-02`.
Start as a single line, wrap to two when needed

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Comment by shixiedesign** [comment]
Looking great!!! 👍Let's hold on and don't merge yet. Give me a moment to go hunt down that black ! icon and hopefully we can get that done too.

**Comment by asudoh** [comment]
@shixiedesign Was the blocker IBM/carbon-elements#374? If so, should we incorporate the change and proceed...? Any thoughts to move this forward...? Thanks!

**Comment by shixiedesign** [comment]
Hi @asudoh the blocker was actually Chris wanting a different icon than the one I submitted in the above PR. But yesterday I saw that Chris's icon is merged! https://github.com/IBM/carbon-elements/pull/375 so we are unblocked!

@tw15egan Would you be able to make the update for warning icon today? Not sure if you are moving. Maybe Akira can help. The icon name we should use is `warning--filled.svg` and it contains 2 paths. Target one of them to color yellow and **change opacity from 0 to 1** and the other path should stay black. Correct me if I'm wrong @joshblack . Thanks!

**Comment by asudoh** [comment]
@joshblack The last release of `carbon-elements` seems to have been 22 days ago. Would you want to cut a release? Thanks!

**Comment by joshblack** [comment]
Hi @asudoh! There haven't been any changes until two days back which is why it's been a bit 😄 Cutting a release this morning with the icon fix that was just merged 👍

**Comment by asudoh** [comment]
Thanks @joshblack for cutting the release! Incorporated it.

**Review by shixiedesign — APPROVED** [review]
👍 Looks good! Thanks for making the changes guys.

**Pull request merged**
