### PR TITLE
fix(tabs): remove disabled item hover state

### LINKED ISSUE #1921: Disabled mobile tab items responding to mouse hover
On mouse hover (click on mobile) of disabled tab items, the item is responding with a color change, which gives the impression that the item is active despite it being disabled

kapture 2019-02-26 at 11 37 09

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1921

This PR prevents mobile tab items from reacting on hover, giving the false impression that the items are actionable

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Hi @emyarod thank you for creating the issue and this PR! One question - Do we want to eliminate hover style of non-disabled item, too...?

**Comment by emyarod** [comment]
@asudoh I don't think we do, but if we decide that we want to I can remove it for non-disabled items as well

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by tw15egan — APPROVED** [review]
👍

**Pull request merged**
