### PR TITLE
feat: text input and textarea character limit counter

### LINKED ISSUE #1672: [Text input] Add character limit/counter
### Summary

Text fields and text areas may have a maximum number of characters. This character limit might need to be communciated: 
1. to users ahead of time, so they can format their input,
2. Whilst a user is entering their input so they know how many characters remain
3. In the form of a validation error when the user reaches the limit

Design usage guidelines and/or enhancements to the components to support that design would be desirable. 

### Justification

It's a common pattern which you can see on a number of IBM products and tools and would be good to standardise. 

### Desired UX and success metrics

When a user is typing into a form field which has a maximum value, that value is communicated to the user, and if the limit is reached, they are informed whilst typing. 

### "Must have" functionality
Tell the user ahead of time what the value is
Tell the user clearly when they have hit the limit (and stop them entering text) 

Might also include a "x characters remaining" indicator so users know how many more they can enter.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1672 

This PR adds a character counter for `<TextInput>` and `<TextArea>` components in both React and vanilla Carbon. The character counter markup can be customized with the `renderCharCount` render prop

#### Changelog

**New**

- `<TextInput>` and `<TextArea>` character counter

#### Testing / Reviewing

Ensure the text inputs and textareas function as expected without any regressions (with and without character counters)

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod! One question BTW - Can vanilla text area be used without JavaScript if character counter is not there?

**Comment by emyarod** [comment]
@asudoh yes textarea without character counter can be used without JS

also not sure why CI output differs from running vanilla test suite locally

**Comment by asudoh** [comment]
Cool, BTW the unit test issue seems with FF - Would you want to try it locally (`--browser Firefox`) @emyarod?

**Comment by emyarod** [comment]
no errors when testing locally on Firefox Nightly (Firefox 68) @asudoh. on Firefox stable (Firefox 66) though, I get the same errors and the spec files are not accessible through dev tools sources either

**Comment by asudoh** [comment]
@emyarod I think you can put a `debugger` statement - Browser debuggers tend to show source as it breaks.

**Comment by emyarod** [comment]
@asudoh it appears that in FF66 `InputEvent` object `data` was not being assigned despite being in the `InputEventInit`dictionary

https://github.com/carbon-design-system/carbon/pull/2745/commits/34e290d347ad82b18f0bf3394dc61a43a7667c3c

**Review by shixiedesign — DISMISSED** [review]
This got done FAST! 🚤 A few small styling fixes:

- [x] Label got an extra margin bottom when Char count knob is turned on
May-16-2019 12-52-39

- [x] When label text is long, warp to second line before intersecting with Char count. There should be a 16px gap between label and Char count text. 
image

- [x] When label is hidden, long helper text should push charCount out, but not this far. Should be only a 16px gap between helper text and charCount.
image

- [x] CharCount knob visible for Password Input but doesn't do anything. Maybe password input shouldn't have this knob in the first place. 
image

**Review by shixiedesign — COMMENTED** [review]
For text area, a lot of the similar issues: 

- [x] Extra margin bottom on label when charCount is turned on
May-16-2019 13-00-50

- [x] Long label intersecting charCount
image

- [x] Large gap between helper text and charCount when label hidden
image

**Review by shixiedesign — COMMENTED** [review]
### Text Area

- [x] 16px padding-right needed so label doesn't touch charCount
image

- [ ] ~~Helper text currently occupies 75% of full width. This is not specified in the original design. I think we should allow helper text to take up full width of the text area width, and allow 16px margin right when there is a charCount.~~ Edit: my mistake, spec file is out of date -xs
image

### Text Input

- [x] Behavior of input when label is long differs from that of Text area's. I expected the text input to grow longer, but not sure width of input is dependent on something else. 
image

- [ ] ~~Distance between helper text and charCount looks like a percentage. Should just be a fixed 1 rem padding-right.~~ Edit: keeping 75% helper text width. Looks like this is the same as above item. 
image

- [x] **New**: keeping helper text full width at mobile, but we need to still add a 16px padding right so helper text doesn't touch charCount. 
image

**Comment by emyarod** [comment]
@shixiedesign regarding these points:

> Helper text currently occupies 75% of full width. This is not specified in the original design. I think we should allow helper text to take up full width of the text area width, and allow 16px margin right when there is a charCount.

> Distance between helper text and charCount looks like a percentage. Should just be a fixed 1 rem padding-right.

the 75% max width was the result of a previous ticket, do we want to modify that? https://github.com/carbon-design-system/carbon/issues/1997 https://github.com/carbon-design-system/carbon/issues/2000

**Comment by shixiedesign** [comment]
@emyarod Thanks double checking! I see, that make sense then. I will strike out that item.

**Review by shixiedesign — APPROVED** [review]
Love it! 🎉 Great work. Thank you!

**Review by asudoh — APPROVED** [review]
LGTM :tada: - Thanks @emyarod!

**Pull request merged**
