### PR TITLE
fix(toggle): change spacing to match style guide

### PR DESCRIPTION
**Pull request by FrivalszkyP**
#### Changelog

**Changed**

- **toggle** component switch element spacing has been modified [to be consistent with the description in the style guide.](https://www.carbondesignsystem.com/components/toggle/style/). The switch element should not have any top/bottom spacing by default, and should have a top 16px spacing when a label is present.

#### Testing / Reviewing

Please validate that the wording in the style guide matches the changes that I implemented.

Please note that I checked with my UI designer colleague and we found that the toggle button in the design kit **does not** have a bottom margin so I decided to omit it here as well. It seems more consistent to me.

### CODE REVIEW

**Comment by tw15egan** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/5367

It seems like it is getting the margin, even though no label is present

Screen Shot 2020-02-27 at 1 31 47 PM

I think I'm leaning towards removing the spacing completely until we refactor form element spacing in v11.

**Comment by FrivalszkyP** [comment]
> It seems like it is getting the margin, even though no label is present

Right. It seems like there's no way to write a selector for toggle switches that don't have a label. 

> I think I'm leaning towards removing the spacing completely until we refactor form element spacing in v11.

Not a bad idea, should I refactor my PR or is there an ongoing effort to clean up the random spacing issues all throughout the codebase?

**Comment by tw15egan** [comment]
No current efforts but it's been added to our planning. We can see what the other devs think in regards to removing this margin now though since you've already got the PR up.

**Review by dakahn — APPROVED** [review]

**Review by designertyler — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @FrivalszkyP!

**Pull request merged**
