### PR TITLE
fix(react): prevent default when handling react tooltip mouse events

### LINKED ISSUE #2686: Tooltip in form label with clickToOpen never opens
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
If you use Tooltip with clickToOpen in a TextInput with an id, the Tooltip never opens.  This is because the click on the Label forces a second click event on the Field contents.  We need to put a evt.preventDefault on this line of code to stop the default redirect to the Form Field from firing

> Is this issue related to a specific component?

Tooltip
> What did you expect to happen? What happened instead? What would you like to
> see changed?
I need to be able to use Tooltips in the Labels of form elements like this:
image

> What browser are you working in?

> What version of the Carbon Design System are you using?
6.111.0
```
 handleMouse = evt => {
    const state = {
      mouseover: 'over',
      mouseout: 'out',
      focus: 'over',
      blur: 'out',
      click: 'click',
    }[evt.type];
    const hadContextMenu = this._hasContextMenu;
    this._hasContextMenu = evt.type === 'contextmenu';
    if (this.props.clickToOpen) {
      if (state === 'click') {
        evt.stopPropagation();
      /* Need this extra line of code to prevent the default form event from firing */
  evt.preventDefault();
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

https://codesandbox.io/s/mrp45kj3x

Note that if you remove the "id" attribute of the TextInput it will work.  This is because the default label to Form field click doesn't happen.

### PR DESCRIPTION
**Pull request by cx0der**
Closes #2686

When handling mouse events invoke evt.preventDefault to stop the default
handler from firing when Tooltip is used inside a form element which has
an id.

#### Changelog

**Changed**

- packages/react/src/components/Tooltip/Tooltip.js - added `evt.preventDefault()` to `handleMouse` method

### CODE REVIEW

**Comment by abbeyhrt** [comment]
Hi @cx0der! Thank you for your contribution! We really appreciate it! Would you mind also adding `evt.preventDefault()` to the `handleKeyDown` function so everything works the same for keyboard users as mouse users?

**Review by abbeyhrt — APPROVED** [review]
Thank you! This looks good to me!

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by cx0der** [comment]
How do we go about merging this? Looks like one of the deployments timed out.

**Pull request merged**
