### PR TITLE
feat(UI icons): new icons march and april

### PR DESCRIPTION
**Pull request by conradennis**
Submitting new and updated UI icons from March and April 2021
all updates and additions approved by BXD

33 net new icons
4 updated icons
1 removed icon

updated categories.yml with additions
updated deprecated.yml with change
updated ui-icon-master.ai with additions and updates

**NOTE: I included the glyph status icons in the 32 folder but they are only to be sized at 16px and should not be scaled to other sizes. If this is an issue, happy to move them to another folder in the repo**

**EDIT: Moved the glyph icons out of the 32 folder**

#### Changelog

**New—33 total**

– svg/glyph--caution-inverted.svg
– svg/glyph--caution.svg
– svg/glyph--circle-fill.svg
– svg/glyph--circle-stroke.svg
– svg/glyph--critical.svg
– svg/glyph--incomplete.svg
– svg/glyph--square-fill.svg
– svg/glyph--undefined.svg
– 32/bookmark--add.svg
– 32/breaking-change.svg
– 32/connect--recursive.svg
– 32/connect--source.svg
– 32/connect--target.svg
– 32/connection--receive.svg
– 32/connection--send.svg
– 32/connection--two-way.svg
– 32/convert-to-cloud.svg
– 32/delivery--add.svg
– 32/folder--open.svg
– 32/folder--parent.svg
– 32/lifesaver.svg
– 32/location--filled.svg
– 32/parameter.svg
– 32/search--locate.svg
– 32/select--window.svg
– 32/text--font.svg
– 32/thumbs-down--filled.svg
– 32/thumbs-up--filled.svg
– 32/touch--1--filled.svg
– 32/touch--1-down--filled.svg
– 32/touch--1-down.svg
– 32/touch--2--filled.svg
– 32/zoom--fit.svg

**Changed—4 total**

– 32/data--base--alt.svg
– 32/thumbs-down.svg
– 32/thumbs-up.svg
– 32/zoom--area.svg

**Removed—1 total**

– 32/letter--Aa--large.svg (replaced with 32/text--font.svg)

### CODE REVIEW

**Comment by joshblack** [comment]
@conradennis do the glyphs have corresponding larger assets too? If they have larger assets I'd definitely just move them over to 16x16. If they only have the one size then I think you can put them outside of the sizes folders and it will interpret it as a glyph

**Comment by conradennis** [comment]
@joshblack it's just the one size. I'll move em outside the folder now. Thanks!

**Comment by joshblack** [comment]
Thanks @conradennis! 🙏 

Looking at the CI check, seems like we got the following error:

```
Expected the icon `glyph--caution-inverted` to be defined in the data metadata file
```

**Comment by conradennis** [comment]
> Thanks @conradennis! 🙏
> 
> Looking at the CI check, seems like we got the following error:
> 
> ```
> Expected the icon `glyph--caution-inverted` to be defined in the data metadata file
> ```

@joshblack hmmm not sure how to resolve this, I included it in the categories.yml file and I didn't touch any other files

**Comment by joshblack** [comment]
@conradennis Ah got it, let me generate out the metadata entry real quick for it then.

**Comment by joshblack** [comment]
It seems like now we're getting:

> Expected the metadata entry `letter--Aa--large` to have a corresponding .svg asset in the SVG folder

**Comment by conradennis** [comment]
> It seems like now we're getting:
> 
> > Expected the metadata entry `letter--Aa--large` to have a corresponding .svg asset in the SVG folder

oh yeah I removed that icon from the repo and categories.yml file. It's deprecated in favor of text--font.svg which is the same icon, just different name.

**Comment by joshblack** [comment]
@conradennis sounds good! I would keep it around in the different metadata files since it still needs to be in the package until we make a breaking change. When we do that, we can remove the deprecated asset 👍 

Keeping it in the metadata also makes sure that people using the icon now will get the deprecation notice and the recommendation for what icon to use next.

**Comment by joshblack** [comment]
@conradennis also make sure to sign the DCO when you get a sec!

https://github.com/carbon-design-system/carbon/pull/8546#issuecomment-830251222

**Comment by conradennis** [comment]
@joshblack ok cool, so I just need to add it back into the categories.yml file? Should I add the old icon file to the svg/32 folder as well?

**Comment by conradennis** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by joshblack** [comment]
@conradennis right, exactly. Basically, when we want to remove an icon, the only change that should happen is adding it to the deprecated file. This will kick off the whole process of hiding it from the website/kit and prompting developers to switch to the new asset. Then when we can do a major release we can remove the deprecated assets 👍

**Comment by conradennis** [comment]
@joshblack gotcha, just added the svg file and categories.yml metadata back

**Comment by joshblack** [comment]
@conradennis awesome, could you sign the DCO too real quick? Then should be good to go!

**Comment by conradennis** [comment]
it says I signed it. will post the text again just in case:

I have read the DCO document and I hereby sign the DCO.

**Comment by joshblack** [comment]
@conradennis oh duh, sorry I missed it. Thanks!

**Review by laurenmrice — APPROVED** [review]
✅ 🎉

**Comment by andreancardona** [comment]
@conradennis the ci is still failing - let me know how I can help in any way

**Comment by tw15egan** [comment]
@andreancardona we'll need to update the snapshots so that is passes CI. You can take a look [here](https://github.com/carbon-design-system/carbon/blob/main/docs/developer-handbook.md#working-with-icons-and-pictograms) for instructions, and then just push the changes up to this PR. Let me know if you have any questions!

**Comment by andreancardona** [comment]
@joshblack  hey I was looking into why this was failing with @tw15egan  and it seems because it doesn't have a size it failing in the `icon-build-helper process` any thoughts on how to fix this? :)

**Comment by joshblack** [comment]
@andreancardona yeah, something is going on with the builder for glyph assets specifically that I think we'll need to address next sprint. I'm not quite sure what the issue is so might take some time to investigate.

**Comment by emyarod** [comment]
the breakage is because no other size is specified for these new glyphs, whereas the existing glyphs have at least one other size defined. should we just include another size for the new glyphs? if not then we need to update the builder to accommodate glyph-only assets, if that's desired

**Review by emyarod — APPROVED** [review]
I fixed the icon build helpers and updated all of the snapshots after building the new assets (https://github.com/carbon-design-system/carbon/pull/8724)

**Review by joshblack — APPROVED** [review]

**Comment by LMapes** [comment]
@conradennis Completed metadata updates to yml file and created PR.

**Pull request merged**
