### PR TITLE
feat(data-table): add zebra styles

### PR DESCRIPTION
**Pull request by jnm2377**
Ref #1303 

#### Changelog

**New**

- add zebra/no-border

**Changed**

- select text color
cc: @laurenmrice

### CODE REVIEW

**Comment by designertyler** [comment]
Zebra stripes are spec'd as `#FCFCFC` and `#F3F3F3` but they look like `#f3f3f3`and `e5e5e5` in the screenshot

Screen Shot 2019-04-03 at 3 44 07 PM

**Comment by designertyler** [comment]
I'm seeing a weird border issue when hovering on the overflow of a selected row 
Apr-03-2019 15-55-14

**Comment by emyarod** [comment]
also seeing the behavior @designertyler is reporting on the 2nd and bottom row of the zebra table

Kapture 2019-04-04 at 8 31 02

on a side note, we should use unique IDs for each checkboxes. Since we are currently reusing IDs, selecting a checkbox will always cause the page to jump to the first table example and modify that table only

**Review by emyarod — COMMENTED** [review]
also seeing the behavior @designertyler is reporting on the 2nd and bottom row of the zebra table

Kapture 2019-04-04 at 8 31 02

on a side note, we should use unique IDs for each checkboxes. Since we are currently reusing IDs, selecting a checkbox will always cause the page to jump to the first table example and modify that table only

**Comment by aledavila** [comment]
To add when hovering over the rows that have the problem with the border bottom - the border bottom flickers back and forth when hovering in and out of the overflow menu and at times theres a white border bottom on that row

**Comment by jnm2377** [comment]
Thanks for catching those bugs. Will work on those 👍 @designertyler @emyarod @aledavila 

Re: 
> on a side note, we should use unique IDs for each checkboxes. Since we are currently reusing IDs, selecting a checkbox will always cause the page to jump to the first table example and modify that table only

@emyarod yeah this was something I noticed a long time ago and actually wanted to completely refactor some the config file for data table, but then but that on the back burner since there were a lot of other priorities re: data table before release. Definitely want to fix it now that we're released and have more time.

**Comment by jnm2377** [comment]
> Zebra stripes are spec'd as `#FCFCFC` and `#F3F3F3` but they look like `#f3f3f3`and `e5e5e5` in the screenshot
> 
> Screen Shot 2019-04-03 at 3 44 07 PM

@designertyler The odd rows are `#f3f3f3` since I'm not overriding any styles. That's the default row bg color. The even rows are `#fcfcfc` for zebra, and `#e5e5e5` on hover, which is also the default hover style. The screenshot looks like you were hovering on the even row. Is that wrong?

**Comment by aledavila** [comment]
Seems like now the border is removed but only to half of it. Sometimes. The flickering is gone though

Screen Shot 2019-04-04 at 3 47 38 PM

Screen Shot 2019-04-04 at 3 47 19 PM

**Comment by jnm2377** [comment]
@aledavila is that on the zebra select example or just zebra? the zebra select one was still having some bugs that _hopefully_ should be fixed with my latest push.

**Review by aledavila — APPROVED** [review]
Zebra select was fine yes. Latest commit shows the fix for the border issue. Looks good

**Review by emyarod — APPROVED** [review]
pending design approval, looks good to me now!

**Comment by aledavila** [comment]
cc: @designertyler for second pass at this to merge it

**Comment by designertyler** [comment]
Zebra Select rows are coming in at 54px and shoulud be 48px like the Zebra data table.
Screen Shot 2019-04-05 at 10 54 06 AM

**Comment by designertyler** [comment]
Check boxes are 12px from the left. There should be a 16px margin
Screen Shot 2019-04-08 at 10 19 23 AM

The zebra pattern should start with the lighter color (#FCFCFC) at the top like v9 and the design specs.
Screen Shot 2019-04-08 at 10 24 39 AM

Screen Shot 2019-04-08 at 10 21 24 AM

**Review by designertyler — APPROVED** [review]
Changes look good!

**Pull request merged**
