### PR TITLE
Optimize SVG assets and update builder interface

### LINKED ISSUE #5568: Icon bug: Using `information--filled` and `closed` icons together causes the info icon to render incorrectly
## What package(s) are you using?

- [x] `carbon-components` version 10.10.1
- [x] `@carbon/icons` version 10.9.1
- [ ] `carbon-components-react`

## Detailed description

We are using icons from `@carbon/icons` version 10.9.1 (latest at time of writing) in a vanilla js/css environment. We have `carbon-components` version 10.10.1.

We are inlining our SVGs straight from the package using the [inline_svg gem](https://github.com/jamesmartin/inline_svg).

When rendering an inline notification that has both the `information--filled` and `closed` icon in it, the styles of the two interact badly and produce the following:

Screen Shot 2020-03-07 at 10 09 07 AM

The info icon is a dark grey square.

Specifically, the style block embedded in the close icon specifies `.cls-1{fill:#231f20;}` while the style block in the info icon specifies `.cls-1{fill:none;}`. One is overriding the other leading to the transparent rectangle around the info icon to be filled grey.

I am able to reproduce this issue in FireFox 72 and Chrome 80

## Steps to reproduce the issue

1. Generate a page with `information--filled` and `close` icons inlined directly from the `@carbon/icons` package.
2. Render the page in a browser.

Codesandbox demonstrating the issue: https://codesandbox.io/s/wizardly-bhabha-igb9x

## Additional information

None

### PR DESCRIPTION
**Pull request by joshblack**
Closes #5568

This PR adds in the ability to optimize SVG assets in the output package directory, alongside including QOL fixes for our builder packages.

This PR also adds in tests for the `icons-vue` package since we ended up needing to update the builder with the new metadata format. A big source of the LOC changes comes from the snapshots generating its public API.

#### Changelog

**New**

- `e2e/icons-vue`
  - Add PublicAPI tests for `icons-vue`
- Add official vue builder to `icon-build-helpers`
- Add `svg` builder for optimizing SVG assets
- Add new `output` extension, this extension does the following:
  - Optimizes asset sources
  - Transform asset source to JS descriptor
  - Provides module name

**Changed**

- `svg` assets now live in `src/svg` instead of `svg`
- `icon-build-helpers`
  - `Metadata` now takes in an updated `input` option for SVG and extension directories
    - Update e2e tests to use new syntax for input
    - Update sketch task to use new syntax
  - Builders are now simplified with a new metadata structure
    - `react` builder has been updated
    - `vanilla` builder has been updated
  - Bugfix for metadata extensions where it was called with an empty object instead of letting default options be applied
- Update all icon/pictogram tasks with new metadata syntax

**Removed**

- Un-used files from `icon-build-helpers` package
- Remove old entrypoint test for `icons-vue`
- Remove unused icons-vue task files

### CODE REVIEW

**Comment by joshblack** [comment]
@laurenmrice just a heads up for changes, this is moving the SVG files from `svg` to `src/svg` 👀

**Comment by joshblack** [comment]
FYI @davidicus this is our PR which updates the entrypoints for the `@carbon/icons-react` package 👀 

Instead of the flat entrypoint it should now re-export so the `sideEffects` flag works as intended.

Let me know if you want to pair up and try it out in a product or on the IoT library 👀

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by joshblack** [comment]
@asudoh let me know if there is anything else I can do / write-up to help with reviews!

**Review by laurenmrice — APPROVED** [review]

**Comment by asudoh** [comment]
Some quick findings:

* Seems that `@carbon/icons/{es,lib}/{{iconName}}/index.js` is gone - Is it intentional? If so, do we need a backward-compatibility layer?
* Seems that `@carbon/icons/svg/*` is moved to another directory, though `svg` is in the `files` list of `@carbon/icons` package. Is it intentional?

**Comment by joshblack** [comment]
Hey @asudoh! 👋 

> Seems that @carbon/icons/{es,lib}/{{iconName}}/index.js is gone - Is it intentional?

I don't believe `index.js` files are in `@carbon/icons` presently IIRC 🤔 was trying to go back a couple of versions but can't seem to find `index.js` per-icon

> Seems that @carbon/icons/svg/* is moved to another directory, though svg is in the files list of @carbon/icons package. Is it intentional?

Yeah! Source files are moved over into `src/svg` but now there will be an optimized `svg` folder at `/svg` for folks to use 👀

**Comment by asudoh** [comment]
> I don't believe `index.js` files are in `@carbon/icons` presently IIRC 🤔 was trying to go back a couple of versions but can't seem to find `index.js` per-icon

Just in case it was not clear enough, I was referring to: https://unpkg.com/browse/@carbon/icons@10.10.2/es/chevron--down/index.js

> Yeah! Source files are moved over into `src/svg` but now there will be an optimized `svg` folder at `/svg` for folks to use 👀 

Sounds good, thank you for clarifying.

**Comment by joshblack** [comment]
@asudoh nice! Got it, thanks for clarifying 🙏 Will make sure to update `glyph.js` -> `index.js` 👀

**Comment by joshblack** [comment]
Should be updated now!

**Review by asudoh — APPROVED** [review]

**Pull request merged**
