### PR TITLE
fix(dropdown): restore space bar and enter key item selection

### LINKED ISSUE #3913: [Dropdown]: cannot select item with keyboard
## What package(s) are you using?

- [x] `carbon-components` 10.5.1
- [ ] `carbon-components-react`

## Detailed description

In the dropdown examples on the carbon site:
https://www.carbondesignsystem.com/components/dropdown/code/
if I focus a dropdown, I can use the up/down arrow to highlight selections, but if I hit Enter the dropdown doesn’t make a selection. 

## Steps to reproduce the issue

1. go to https://www.carbondesignsystem.com/components/dropdown/code/
1. focus on any dropdown
1. hit enter to open dropdown
1. use keyboard up/down to focus on an option
1. no keys allow making a selection

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3913

This PR fixes a regression introduced in #3586 and restores enter key and space bar item selection for the dropdown

Previously (pre-`v10.5`) individual items in the dropdown list fired click events on Enter keypress when selected, and the selected item information could be extracted from the event object. This behavior was changed so that focus is no longer placed on the individual dropdown items and is instead kept fixed on the dropdown menu. So in order to get the currently selected item information, we need to explicitly get the selected item info (`getCurrentNavigation`) and call `.select()`

on a side note, it seems that dropdowns now have 2 tab stops due to a `tabindex` on the dropdown menu even while hidden. this should probably be addressed in a separate PR

#### Changelog

**New**

- NPE check for focused item before removing focus class
- keyboard navigation tests for semantic markup introduced in #3586

**Changed**

- select item after space/enter keypress
- ignore nonrelevant events in `toggle` method
- focus on trigger after item selection with keyboard

#### Testing / Reviewing

Ensure that keyboard selection of dropdown items functions properly

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by elizabethsjudd — APPROVED** [review]

**Comment by tw15egan** [comment]
Should we add something to prevent the screen from scrolling when the spacebar is pressed when the menu is open?

**Comment by emyarod** [comment]
added in latest commit @tw15egan

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks alot @emyarod for taking a look at this issue!

**Review by tw15egan — APPROVED** [review]
LGTM ✅

**Pull request merged**
