### PR TITLE
fix(styles): port over data table fixes

### LINKED ISSUE #10571: Audit data-table styles
High level steps to take for each component are outlined in the [parent issue](https://github.com/carbon-design-system/carbon/issues/9805#issuecomment-1026166086).

If there's no actionable items to PR, just close this issue without a linked PR

### PR DESCRIPTION
**Pull request by joshblack**
Closes #10571

This PR ports over changes to data table that have occurred since this work was ported over this past June

#### Changelog

**New**

**Changed**

- Port over fixes to styles package

**Removed**

#### Testing / Reviewing

- Verify data table styles render as expected

### CODE REVIEW

**Comment by joshblack** [comment]
@abbeyhrt should be fixed

**Comment by joshblack** [comment]
cc @tay1orjones @abbeyhrt when you get a sec!

**Review by tay1orjones — APPROVED** [review]

**Comment by abbeyhrt** [comment]
It looks like the overflow for when there are a bunch of batch actions isn't working as expected :/ 

https://user-images.githubusercontent.com/17281178/156062072-657d2e4c-3c81-44e5-9fed-171e66db5d34.mov

**Review by aledavila — APPROVED** [review]

**Comment by joshblack** [comment]
@abbeyhrt ready for re-review!

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! 🎉 🎉

**Pull request merged**
