### PR TITLE
fix(selectable-tile): don't require deprecated property "value"

### LINKED ISSUE #16977: [Bug]: SelectableTile: deprecated `value` prop
### Package

@carbon/react

### Browser

_No response_

### Package version

1.61.0

### React version

18.0.0

### Description

The value prop is marked as `deprecated` despite being required.

### Reproduction/example

https://stackblitz.com/edit/vitejs-vite-dbavtk?file=src%2FApp.tsx

### Steps to reproduce

1. Use the SelectableTile component with TypeScript,
2. Add value prop
3. Have it marked as deprecated

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by wkeese**
Fixes #16977.
Refs #13537, #13631.

Update PropTypes so "name" and "value" are reported as deprecated. (The descriptions already included @deprecated, but that's different.)

More importantly, stop marking "value" as required. Properties cannot be deprecated and required at the same time.

#### Changelog

**Changed**

- declarations for SelectableTile "name" and "value" properties

#### Testing / Reviewing

Tested locally.  Updated snapshot, and updated test file to stop using the deprecated parameters.

### CODE REVIEW

**Comment by wkeese** [comment]
I saw that, but isn't that an infrastructure problem, some issue with Jenkins etc.?

For me, the tests are all failing locally even on the main/ branch, with an error that

> Cannot find module '@carbon/feature-flags' from 'packages/react/src/components/FeatureFlags/index.tsx'

That may be unrelated though.

**Review by tay1orjones — APPROVED** [review]
LGTM, just need to update the public api snapshot and push it up. `yarn test -u` at the root will do it

**Comment by wkeese** [comment]
Ah thanks, I got it to work via running this from the root:

```
yarn install
yarn run build
yarn test -u
```

(It's never clear to me when to run from root vs. when to run from packages/react.)

I force-pushed the latest.

**Comment by wkeese** [comment]
The visual diffs are unrelated to this PR, you can see the same thing happening in #18106.

**Review by kennylam — APPROVED** [review]

**Pull request merged**
