### PR TITLE
fix(modal): fix header padding for small variants

### LINKED ISSUE #4759: [Modal- Title only example]: close button overlaps text
When looking at the modal at https://carbon-components-react.netlify.com,  I found that, when changing the size of the window, the `X` icon overlaps the content pretty severely at times.  

Screen Shot 2019-11-22 at 11 34 45 AM

Or the focus for the button will overlap the text: 

Screen Shot 2019-11-22 at 12 45 27 PM 
the 's' in 'lines' is covered by the button.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #4759.

#### Changelog

**Changed**

- The right padding of modal header for smaller variants.

#### Testing / Reviewing

Testing should make sure our modal is not broken.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
do these values need to be tokens instead?

**Comment by asudoh** [comment]
@emyarod Makes sense - Updated.

**Review by joshblack — APPROVED** [review]

**Review by joshblack — CHANGES_REQUESTED** [review]
Any chance we could use spacing tokens from the spacing scale?

**Review by abbeyhrt — APPROVED** [review]
Looks good to me with the changes Josh suggested!

**Comment by asudoh** [comment]
@joshblack @abbeyhrt Do you guys mean `$layout-md` or something else...?

**Comment by joshblack** [comment]
If I understand correctly, the t-shirt sizes for spacing have been replaced by the spacing and layout scales. I believe `spacing-3xl` is 48px which maps over to `$spacing-09` or `$carbon--spacing-09` 👍

**Comment by asudoh** [comment]
Updated to `$carbon--spacing-09`

**Review by joshblack — APPROVED** [review]

**Review by designertyler — APPROVED** [review]

**Pull request merged**
