### PR TITLE
fix(skeleton): Moved skeleton animation to skeleton component import to avoid duplicate css

### LINKED ISSUE #985: Performance: Duplicated CSS code
## Detailed description

in the `_helper-mixins.scss` file `@keyframe skeleton` does not have an `import-once` wrapped around it . This causes the keyframe to be included every time the `helper-mixin` file is imported.  Within Carbon's minified CSS file it appears 91 times.

> Is this issue related to a specific component?

no

> What did you expect to happen? What happened instead? What would you like to see changed?

I expect the keyframe to only be exported once in the distributed files or when using Sass to create my own bundle. Currently this animation is in our bundled code 65 times and increases our un-minified file by almost 2000 lines.

> What browser are you working in? 

Chrome, Safari, Firefox, Edge, IE11

> What version of the Carbon Design System are you using? 

9.1.5

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Design System

## Steps to reproduce the issue

1. Search for `@keyframes skeleton` in carbon-components.css 
2. Note it appears 91 times

### PR DESCRIPTION
**Pull request by alisonjoseph**
Resolves #985

### Changed

Moved skeleton animation to skeleton component import

## Testing / Reviewing

Make sure skeleton states still work

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thanks @alisonjoseph for addressing this! Looks a minor breaking change (please correct me if I'm wrong here), given consumers need to import `_skeleton.scss` instead of `_helper-mixins.scss`. Do we want to a way to advertise a change? Thanks!

**Comment by alisonjoseph** [comment]
Oh good catch, I didn't think about that. I'd rather not push a breaking change, can we update this to keep the code inside helper-mixins but only have it once in the compiled css.

**Comment by asudoh** [comment]
I see thank you for your thoughts @alisonjoseph! How about using `import-once` (`@include exports`) while we keep the content in `_helper-mixins.scss`?

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks alot @alisonjoseph!

**Review by elizabethsjudd — APPROVED** [review]
Thank you for making this change!

**Review by aledavila — APPROVED** [review]

**Pull request merged**
