### PR TITLE
chore: change padding column to 1rem

### LINKED ISSUE #5360: [Data table] Column header padding wrong
Padding on table headers is currently 8px left/right but it should be 16px left/right

As-is:
image

### PR DESCRIPTION
**Pull request by xxxle0**
Closes #5360 

change padding of data table

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by tw15egan** [comment]
Small issue on first column of sortable data table

Screen Shot 2020-02-17 at 3 04 56 PM

**Review by aagonzales — APPROVED** [review]
Perfect! Thanks for fixing.

**Review by abbeyhrt — APPROVED** [review]
Thank you! @xxxle0 🎉

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Note for whoever merges this in, I think we'll need to update the commit line to:

```
fix(data-table): update spacing tokens for column padding
```

**Pull request merged**
