### PR TITLE
feat(number-input): add experimental number-input

### LINKED ISSUE #1210: Experimental Component - Number Input - Development
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

### PR DESCRIPTION
**Pull request by tw15egan**
Closes #1210 

Adds in Experimental Number Input component

#### Changelog

**New**

- Experimental Number Input

**Changed**

- Moved `input` and `label` before `bx--number__controls` so that on the first tab, the focus would go to the input rather than the up arrow. The Light styles seemed to already do this, so not sure why this one was changed 

- Changed `data-invalid` styles to outline across the board

**Removed**

- Extra styles

#### Testing / Reviewing

Preview Link: http://carbon-dev-environment-exp-number-wacky-possum.mybluemix.net/?nav=number-input

screen shot 2018-10-18 at 12 27 30 pm

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
LGTM!  you're so fast!⚡️

**Comment by laurenmrice** [comment]
Dang TJ! Looks Great  🎉

**Review by joshblack — APPROVED** [review]
Works great! Only had a question around if we wanted to undo the nesting from the classic implementation, or keep it as-is.

As an aside, would it be helpful to add an active style for the number input controls when they are clicked/interacted with? Curious what design would think

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Pull request merged**
