### PR TITLE
WIP/discussion: fix input label highlight on focus

### LINKED ISSUE #1173: Label is not color highlighting when user is interacting with an input field
## Detailed description
According to our carbon components spec, the labels should highlight when the user has focused on an input field.  

I believe this was injected by the a11y fix.  I believe this fix injected the issue because the css no longer finds the label field since it's been reordered: https://github.com/IBM/carbon-components-react/commit/f02c1f9a7ecb92bb42028b34b8b95bb09ac2e425

> Is this a feature request (new component, new icon), a bug, or a general issue?

bug
> Is this issue related to a specific component?

Select
> What did you expect to happen? What happened instead? What would you like to see changed?

expected label to highlight
> What browser are you working in?

Chrome
> What version of the Carbon Design System are you using?

6.18.4
> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue
Simply interact with the Select widget in this storybook.  The label should be highlighted red as you interact.
http://react.carbondesignsystem.com/?selectedKind=Select&selectedStory=invalid&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

* Screenshots or code
* Notes

### PR DESCRIPTION
**Pull request by lovemecomputer**
CSS updated in accordance with latest HTML structure to highlight labels on focus of their corresponding input elements.

one TODO remains in `_text-input.scss`

Closes https://github.com/IBM/carbon-components-react/issues/1173 (from `carbon-components-react`)

{{short description}}

#### Changelog

**Changed**

- Removed CSS rules from using `&:focus ~ .#{$prefix}--label` or `&:focus + .#{$prefix}--label` sibling label (which can only see following elements)
- Added rules that use `&:focus-within .#{$prefix}--label` on the parent container.
  - **NOTE**: the `label` element in most cases proceeds the input as a sibling, and CSS cannot see up the tree that way, so we must use `:focus-within` on the parent of the input and label. this CSS rule is not supported in Edge yet. an alternative would be a JS solution?
- removed extraneous `& ~ .#{$prefix}--label` rules that no longer apply (they were for flex which is no longer used)

**Elements affected**

- Date Picker
- Number Input
- Select (invalid state excluded)
- Text Area
- Text Input

---

### my notes:

Currently:
- Date Picker
  - `data-invalid` applied to `<input>` 
  - with `pattern="\d{1,2}/\d{1,2}/\d{4}"`
- Number Input
  - `data-invalid` applied to parent `<div>`
  - with `type="number" min="0" max="100"`
- Select 
  - `data-invalid` state applied to `<select>`
- Text Area
  - `data-invalid` state applied to `<textarea>`
- Text Input
   - `data-invalid` applied to `<input>` 
   - with `type="text"`

### CODE REVIEW

**Comment by tw15egan** [comment]
Oooo that's a nice little selector! Nice thinking! 

Seems like it isn't supported in IE11 / Edge, can you just make sure that nothing is broken when viewed on those browsers? I'm okay with this fix only working in some browsers versus none of them.

**Comment by lovemecomputer** [comment]
@tw15egan can do! 

also general issue: for this to work globally, **date picker** and **text input** need to be changed to have the `data-invalid` prop assigned to the parent container that would receive `:focus-within`. i need to look into what to change to make this happen!

**Review by asudoh — COMMENTED** [review]
Thank you for the proposal @lovemecomputer! One question is if IE/edge still works OK, given `:focus-within` is not supported by IE/edge: https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-within#Browser_compatibility

**Comment by alisonjoseph** [comment]
@lovemecomputer any updates on this? Am fine with this solution not working in IE/Edge for now as long as it doesn't break anything. Can you provide an update and swap the label from WIP to Ready for Review when ready. 😄 thanks!

**Comment by joshblack** [comment]
Going to close this due to inactivity, feel free to re-open!

**Pull request closed without merging**
