### PR TITLE
feat(accordion): add size variants to Accordion

### PR DESCRIPTION
**Pull request by tw15egan**
Related to https://github.com/carbon-design-system/carbon/issues/5455

Adds in `sm` (32px) and `xl` (48px) variants to `Accordion` 

#### Changelog

**New**

- `size` prop added to `Accordion`. Adds in two variants `sm` and `xl`. 

**Changed**

- Updated snapshots

#### Testing / Reviewing

Ensure all size variants look correct

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me pending visual review

**Review by jeanservaas — COMMENTED** [review]
This looks great and I want to approve. I just have one question, is it possible to call this a "Large" variant vs. an "Extra Large" variant? Since we're starting to add large variants everywhere, we should be consistent. The 64px button variant is only called "Large" and the 48px search I believe might even be default.

Thoughts on this?

**Review by aledavila — APPROVED** [review]

**Comment by tw15egan** [comment]
@jeanservaas we'll be able to do that on the next major release, but right now we're just aligning it to all the other form input sizes (`sm` and `xl`). In the next major release, we'll switch to `small` and `large` as the two variants.

**Review by johnbister — APPROVED** [review]
Weird Al would be proud.

weirdal

**Review by jeanservaas — APPROVED** [review]

**Pull request merged**
