### PR TITLE
refactor(project): add react package

### LINKED ISSUE #2383: Add carbon-components-react to monorepo
Following up on #2382, this issue is to add `carbon-components-react` as a package in the monorepo. This work includes:

- [ ] Using `git subtree` to import **all** git history from the react git repo
- [ ] Setting `carbon-components` as an exact version dependency for `carbon-components-react`
- [ ] Verifying CircleCI runs as expected
- [ ] Updating GitHub files for contribution
- [ ] Deprecating dedicated repo
- [ ] Renaming `carbon-components` to `carbon`
- [ ] Migrating over existing issues to carbon repo
- [ ] Migrating over existing PRs to carbon repo

### PR DESCRIPTION
**Pull request by joshblack**
Closes #2383 

Adds `carbon-components-react` to carbon monorepo.

Reviewer checklist:

- [ ] Lint staged works as expected
- [ ] Editor plugins work as expected in nested package (like prettier)
- [ ] Can still develop locally with storybook
- [ ] GitHub files are up-to-date
- [ ] CircleCI is running CI checks
- [ ] ESLint works as expected
- [ ] Tests run as expected, don't fail
- [ ] Builds work as expected

### CODE REVIEW

**Comment by asudoh** [comment]
FYI: I had an issue with my Storybook experimentation (after rebased to the version with monorepo) and below solved my issue:

```
"workspaces": {
  ...
  "nohoist": [
    "**/@storybook/**"
  ]
},
```

**Comment by joshblack** [comment]
@asudoh was this even with the latest update? I also had an issue with that but I thought the updated version fixed it

**Review by emyarod — COMMENTED** [review]
dev env and tests work as expected for me

**Review by tw15egan — APPROVED** [review]
Everything works great for me, and styles update in React package when updated in Components 🎉

**Pull request merged**
