### PR TITLE
fix(time-picker): vertically center caret

### LINKED ISSUE #2094: Experimental time picker: Wrong caret position
## Detailed description

> Describe in detail the issue you're having.

Saw wrong caret position of time picker in the experimental dev env, at: https://the-carbon-components.netlify.com/component/time-picker--default.html

image

> Is this issue related to a specific component?

Time picker

> What did you expect to happen? What happened instead? What would you like to see changed?

The caret position is verticall centered.

> What browser are you working in?

Chrome 72

> What version of the Carbon Design System are you using?

`v9.84.8`

### LINKED ISSUE #2098: Invalid time picker messages overflowing from container
image

related

https://github.com/IBM/carbon-components/issues/2023

https://github.com/IBM/carbon-components/pull/2024

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2094

Closes #2098

This PR adds style rules to position the time picker `<select>` carets properly after https://github.com/IBM/carbon-components/pull/1978

#### Changelog

**New**

- documentation examples for invalid and disabled states

**Changed**

- Carbon classes for text input and `<select>`s to share styling
- type styles

**Removed**

- redundant and unused styles

#### Testing / Reviewing

Ensure the component is not broken

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Changes:**

- [x] The ‘hh:mm’ text should call code-02 (text-03 color). Right now it looks too small?

- [x] Double check that the padding is 16px before and after the type/chevron in each field. And that we are pulling in the 16/chevron and not the glyph.
Screen Shot 2019-03-14 at 11 42 29 AM

- [x] Double check the label text above the field should call label-01 and the error message text should call caption-01.

**Comment by emyarod** [comment]
all labels in the library are using `label-01` (https://github.com/IBM/carbon-components/pull/1859) and all error messages are using `caption-01` (https://github.com/IBM/carbon-components/pull/2064). The placeholder value is inherited from text input, so it is `text-03`

the spacing changes should be addressed now

**Review by alisonjoseph — APPROVED** [review]
LGTM! 👍

**Review by laurenmrice — APPROVED** [review]
Yep, this looks good to me now 👍

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
