### PR TITLE
chore(tile-group): refactor to functional component

### PR DESCRIPTION
**Pull request by motou**
Ref #9712

Refactor the TileGroup component to the functional component using `React.forwardRef` to ensure refs were being forwarded appropriately.

- [x] TileGroup

#### Notes
`getDerivedStateFromProps` is modified using the recommendation in #9712. `renderLegend` is moved into the rendering method.

#### Testing / Reviewing

- Pull down the PR locally
- Run `yarn start:v11` from `packages/react`
- Alternate: use the PR storybook: https://deploy-preview-9955--carbon-components-react.netlify.app/ and v11 next storybook: https://deploy-preview-9955--carbon-react-next.netlify.app/
- Ensure that the following stories for Tile are working as expected: 
   - Radio
   - RadioWithLayer

#### Todo

- [ ] re-write tests to use RTL

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
🎉

**Review by dakahn — APPROVED** [review]

**Comment by jnm2377** [comment]
Hey @motou looks like some of the tests are failing. Do you have time to fix this in the next few days? It'll be ready to merge once that's fixed.

**Comment by motou** [comment]
@jnm2377 yes sure. I will try to find some time today to fix the test errors

**Comment by jnm2377** [comment]
hi @motou just wanted to check in on this and see how it's going

**Comment by motou** [comment]
> hi @motou just wanted to check in on this and see how it's going

Sorry for the delay. I will find some time this week to fix the failing unit tests

**Comment by motou** [comment]
@all-contributors please add @motou  for code and doc ✨

**Comment by jnm2377** [comment]
Hey @motou looks like this PR has gone stale. Just wanted to check in to see if you were still working on this. I'll be closing it at the end of the week otherwise. Thanks!

**Pull request closed without merging**
