### PR TITLE
fix(colors): updated tokens for tile and input fields

### PR DESCRIPTION
**Pull request by tay-aitken**
@mari I changed the token to box shadow from `text-02` to `ui-05`, they are the same hex value. Just wanted to reserve text for text. If we went with text-02 for a specific reason let me know. 

Also made a change to tile border based on feedback from Mina.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thanks @tay-aitken for doing this! Just wondering - Should we change [the box shadow of list box](https://github.com/carbon-design-system/carbon-components/blob/d60e9e1/src/components/list-box/_list-box.scss#L26) and [one of time picker](https://github.com/carbon-design-system/carbon-components/blob/3633cf0/src/components/time-picker/_time-picker.scss#L49), too?

**Comment by tay-aitken** [comment]
Added them in @asudoh, thanks for the suggestion!

**Review by asudoh — APPROVED** [review]
LGTM 👍 ✅ - Thanks alot @tay-aitken for the quick update!

**Review by alisonjoseph — APPROVED** [review]
Thanks for doing this, LGTM!

**Pull request merged**
