### PR TITLE
fix(icons): update condition for vue2/vue3 exports

### LINKED ISSUE #11836: [Bug]: Vue 2.7.x breaks icons
### Package

@carbon/icons-vue

### Browser

Chrome, Safari, Firefox, Edge

### Package version

10.48.0

### React version

_No response_

### Description

The SVG in icons is not rendered in latest version of vue2. Icons to render, bug SVG's were not rendered

### Reproduction/example

na

### Steps to reproduce

1. Set Vue and vue-template-compiler to 2.7.2
2. Icons will not render

## Additional information

This is being caused by 

utils.js in icons package,
```js
var createSVGComponent = function createSVGComponent(name, svgAttrs, svgContent) {
  return _objectSpread2({
    // We use title as a prop name for the component
    // as it is not a valid attribute for an SVG HTML element
    props: {
      title: String
    },
    name: name
  }, h ? {
    // Vue 3 component
```

Since `h` is defined in latest version, it causes vue3 component to be set even in vue2 environment
```
// automatically rewrite the binding into `import { h } from 'vue'` as this is
// currently causing issues in Vue 2 environments

function getVueExport(key) {
  return Vue[key];
}

var h = getVueExport('h');
```

ref: https://blog.vuejs.org/posts/vue-2-7-naruto.html 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #11847: [Bug]:
### Package

@carbon/icons-vue

### Browser

_No response_

### Package version

@carbon/icons-vue": "10.41.0"  @carbon/vue: "2.40.0"

### React version

_No response_

### Description

Recently we have noticed no icons are loading in our Vue application.
We are using many icons from the above carbon icon-vue  package. svg path for the icons are empty on screen.
import Home32 from '@carbon/icons-vue/es/home/32';
import Search16 from '@carbon/icons-vue/es/search/16';
import Information16 from '@carbon/icons-vue/es/information/16';
import FolderAdd16 from '@carbon/icons-vue/es/folder--add/16';
import FolderDetails16 from '@carbon/icons-vue/es/folder--details/16';
import FolderDetails32 from '@carbon/icons-vue/es/folder--details/32';
import Edit16 from '@carbon/icons-vue/es/edit/16';
import { Delete16 } from '@carbon/icons-vue/es/trash-can/16';

Please find attached the screens from application.
[Icon-Defect.docx](https://github.com/carbon-design-system/carbon/files/9166982/Icon-Defect.docx)

Initial analysis :

[Lee Chase](https://app.slack.com/team/W3EGC5230)  [3:24 PM](https://americas-bi-ar-tribe.slack.com/archives/CAM5P6NR1/p1658483650507749)
Looking at this old CodeSandbox the icons are still working https://codesandbox.io/s/carbonvue-carbonicons-vue-cvbuttons-j69zk?file=/src/TestComponent.vue
If I switch to Vue 2.7 they stop. I can upgrade the Carbon dependencies but not Vue to 2.7.  I suspect this has something to do with the way Carbon Icons Vue tries to support both Vue 2 and Vue 3. I believe Remya is going to raise an issue with Carbon, but it may need one of you to debug/fix.

### Reproduction/example

https://codesandbox.io/s/carbonvue-carbonicons-vue-cvbuttons-j69zk?file=/src/TestComponent.vue

### Steps to reproduce

lee.chase@uk.ibm.com helped me test , ran this in test sandbox and icons are not loading
<template>
  <div>
    <cv-link href="javascript:void(0)">The following icon should be the color of this text.
      <Edit16/>
    </cv-link>
    <br>
    <br>
    <span class="green">This is just some text with an icon after it.
      <Edit16/>
    </span>

    <br>
    <br>
    <cv-button>Hello world
      <Edit16/>
    </cv-button>
    <br>
    <br>
    <cv-button :icon="MyEdit16">Hello world</cv-button>

    <br>
    <br>
    <cv-button :icon="anEdit16">Hello world</cv-button>

    <br>
    <br>
    <cv-button :icon="AddFilled16">Hello world</cv-button>
  </div>
</template>

<script>
import Edit16 from "@carbon/icons-vue/es/edit/16";
import AddFilled16 from "@carbon/icons-vue/es/add--filled/16";

export default {
  name: "TestComponent",
  components: { Edit16 },
  created() {
    this.anEdit16 = Edit16;
  },
  data() {
    return {
      AddFilled16
    };
  },
  computed: {
    MyEdit16() {
      return Edit16;
    }
  }
};
</script>

<style scoped>
.green {
  color: green;
}
</style>
Please find more details on slack channel thread : #carbon-vue 

Thank You,

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #11836 
Closes #11847

#### Changelog

**Changed**

- Update the conditional for vue2 vs vue3 icons exports to use `createApp` instead of `h` due to [the most recent vue2 release](https://blog.vuejs.org/posts/vue-2-7-naruto.html)

#### Testing / Reviewing

* @m301 @lee-chase what would be the best way to test this one? Could we reuse the example applications used before? https://github.com/carbon-design-system/carbon/pull/7862#issuecomment-783683203

### CODE REVIEW

**Comment by m301** [comment]
I believe, yes this should be reproducible as you force higher vue version, I can test and confirm as well.

**Comment by tay1orjones** [comment]
@m301 Thanks! Let me know if I can help.

**Comment by tay1orjones** [comment]
Build for testing, if it's helpful: [icons-vue.zip](https://github.com/carbon-design-system/carbon/files/9184367/icons-vue.zip)

**Comment by m301** [comment]
@tay1orjones I tested it with following patch, and it works. 
```patch
diff --git a/node_modules/@carbon/icons-vue/es/utils-6832c513.js b/node_modules/@carbon/icons-vue/es/utils-6832c513.js
index d5c33490..1636c42d 100644
--- a/node_modules/@carbon/icons-vue/es/utils-6832c513.js
+++ b/node_modules/@carbon/icons-vue/es/utils-6832c513.js
@@ -91,6 +91,7 @@ function getVueExport(key) {
 }
 
 var h = getVueExport('h');
+var createApp = getVueExport('createApp');
 
 var getSvgAttrs = function getSvgAttrs(title, svgAttrs, componentAttrs) {
   return getAttributes(_objectSpread2(_objectSpread2({}, svgAttrs), {}, {
@@ -134,7 +135,7 @@ var createSVGComponent = function createSVGComponent(name, svgAttrs, svgContent)
       title: String
     },
     name: name
-  }, h ? {
+  }, createApp ? {
     // Vue 3 component
     setup: function setup(_ref, _ref2) {
       var title = _ref.title;
```

**Comment by tay1orjones** [comment]
Thanks @m301!

**Review by dakahn — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
