### PR TITLE
refactor(number-input): avoid absolute positioning input control and SVG

### LINKED ISSUE #1621: Number input warning icon position changes based on label and/or helper text length
When the number input component is rendered with a label and/or helper text, the length of the text can increase the overall height of the component, which affects the positioning of the warning icon when the input is invalid.

image

### PR DESCRIPTION
**Pull request by emyarod**
Related: https://github.com/IBM/carbon-components-react/issues/1710

Closes #1621

This PR will position the warning icon for invalid number inputs absolutely from the bottom rather than the top so that its position will not be affected by the length or existence of a label or helper text

image

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thanks @emyarod for jumping in! One that comes to my mind is "error without form validation message" scenario, another is `div.bx--number__controls`. Any thoughts...?

**Comment by emyarod** [comment]
@asudoh is "error without form validation message" a scenario that we support i.e. does it fall within the UX guidelines for Carbon?

it doesn't seem like we support number input without `div.bx--number__controls` either, since we add some event listeners onto that class, but I may be mistaken

**Comment by asudoh** [comment]
Thanks @emyarod for your thoughts - Not sure if we ever supported empty form validation message, but just wanted to bring up for thoughts. My latter comments came from that [the up/down buttons are placed from top position](https://github.com/IBM/carbon-components/blob/2d33c25720fac6830623950a0ea97a3ec3bce6b3/src/components/number-input/_number-input.scss#L320), and wanted to see your findings wrt how longer helper text affects that.

**Comment by emyarod** [comment]
@asudoh since this only affects the experimental version, I rewrote the markup and refactored the CSS to avoid `position: absolute` and the CSS `order` property, which should get around this problem

I also added an example of a number input component with error but without form validation message to show that the new markup and styles should be unaffected by that scenario

**Comment by emyarod** [comment]
would like to have your input on this @tw15egan since you initially created the experimental version of this component!

**Review by tw15egan — APPROVED** [review]
🙏 This is a great solution, seems much more stable than relying on absolute positioning

**Review by asudoh — APPROVED** [review]
Thanks @emyarod for making this change and @tw15egan for reviewing!!

**Pull request merged**
