### PR TITLE
feat(progress-indicator): adds 'vertical' variant

### PR DESCRIPTION
**Pull request by werdnanoslen**
This adds a vertical variant to the [progress-indicator component](http://www.carbondesignsystem.com/components/progress-indicator/code), like this:

image

#### Changelog

**New**

- Added vertical variant to the progress-indicator component

### CODE REVIEW

**Comment by werdnanoslen** [comment]
FYI the magic numbers used in the margins, top, etc are due to the icon's internal spacing. I tried to use only as many magic numbers as were already there, but let me know if there's a better way.

**Comment by asudoh** [comment]
Thamks @werdnanoslen for the contribution! Set our designers as the reviewer to see if they agree the new addition. In case they agree - Could you create `v10` variant as well? Thanks!

**Comment by werdnanoslen** [comment]
@asudoh created. Note that I'm using the normal [`label` instead of `overflowLabel`](https://github.com/IBM/carbon-components/pull/1717/commits/7acda2dce7c532f8f062c6a0984b08e3d63c5156#diff-59c2bb7fba6b8caa76011d66dc4c4f55L42) on the experimental vertical variant, as width is not necessarily a constraint.
image

**Review by laurenmrice — CHANGES_REQUESTED** [review]
It looks good to me other than the height of each section could be 96px instead of 48px. It needs some more breathing room.

screen shot 2019-02-04 at 4 38 55 pm

**Comment by werdnanoslen** [comment]
@laurenmrice Done, and for reference, this is the non-v10 version @ 6rem/96px min-height:
image

**Review by laurenmrice — APPROVED** [review]
Looks good to me, thanks Andy!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @werdnanoslen!

**Pull request merged**
