### PR TITLE
fix(ComboBox): prevent invalid option retention on `Enter`

### LINKED ISSUE #8170: ComboBox retains invalid option after typing and clicking enter
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
A value can be displayed in the ComboBox that doesn't refer to a valid option.

> Is this issue related to a specific component?
ComboBox

> What did you expect to happen? What happened instead? What would you like to see changed?
Typing then hitting enter... and typing then clicking away.... should have the same result.
The ComboBox selection should revert to the entry before the user started to type if no matched item is found.

Issue #6818 ComboBox doesn't support entry of Text not found in list items may be effected by this.
#6818 specifically mentions enter - but enter and click away should both be taken into account. 

> What browser are you working in?
FF/CH(Win + Mac), Safari(Mac), Edge(Win)

> What version of the Carbon Design System are you using?
With the latest version of Carbon, at https://react.carbondesignsystem.com/?path=/story/components-combobox--combobox 

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cognos

## Steps to reproduce the issue

1. invoke the ComboBox in CodeSandbox - https://react.carbondesignsystem.com/?path=/story/components-combobox--combobox
2. enter "XXX" in the ComboBox input field
3. click outside the input field (the input field reverts to what was there before you started to type)
4. enter "YYY" in the ComboBox input field
5. enter ENTER (the input field retains the value "YYY")

The ComboBox now looks like you selected a valid option of "YYY", but "YYY" is not a valid option.

Side note:
When the ComboBox is in this state - showing an option that does not match an item - clicking on the Combobox will show the drop down list and have the previous selected item still checked.
Essentially showing 'YYY' but having 'Option 1' still being the real selected item.

> Please create a reduced test case in CodeSandbox
You can see this easily enough via the CodeSandbox CodeSnippet above.

## Additional information

https://user-images.githubusercontent.com/5973642/112207534-9f3cbd00-8bed-11eb-91a6-d706a286832a.mov

## Attempted workaround

I created this CodeSandbox showing the attempt I made at addressing this issue.
But is does not work, the re-setting value does not work.
If anyone has any comments/suggestions how to fix this please let me know.
https://codesandbox.io/s/combobox-fix-enter-kpdne

### LINKED ISSUE #8179: Update icons-react to ship icon components with size prop
This issue tackles the integration of our new "icon with size prop" approach for our icons-react package. For this issue, we will need to:

- [ ] Emit icons as individual files, e.g. `@carbon/icons-react/IconName.js` or `@carbon/icons-react/namespace/IconName.js`
- [ ] Support the `size` prop for each component
- [ ] If an icon has bespoke assets per-size, the `size` prop should use that data to handle rendering.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #8170
Related #2823
Related #3862

This PR prevents an invalid option from remaining in the ComboBox on <kbd>Enter</kbd> keypress while retaining the functionality introduced in #3862 in response to #2823 (<kbd>Enter</kbd> expands the closed ComboBox menu). Alternatively, we may be able to remove the <kbd>Enter</kbd> key menu expansion due to this issue being closed as a wontfix https://github.com/carbon-design-system/carbon/issues/3861), but curious to hear others' thoughts on this

#### Testing / Reviewing

perform the test described in the referenced issue and confirm that pressing <kbd>Enter</kbd> when an invalid value is in the input field does not close the menu while retaining the previous selection (if one was made)

### CODE REVIEW

**Comment by jnm2377** [comment]
I can see why #3861 was closed, since that one gets a bit more complicated with multiselect/open/close on enter, but I think having an event listener for enter on combo box is fine since you're only selecting one item. That being said, when I tested the component, I realized enter only opens the menu box if there is no item already selected. If I've selected an item and the menu is closed, then I press enter to try to open again, it doesn't open. Is that expected?

**Review by jnm2377 — COMMENTED** [review]
Looks like it's mostly working. When I was testing, I noticed that if I selected an item, then tried to select an invalid item (`xxx`) and pressed enter, it didn't close. Great! But then if I deleted the `xxx` and closed the menu, the original selected item text was no longer displaying even though it shows as still selected when the menu is open. See video attached.


https://user-images.githubusercontent.com/32556167/115874806-29a15800-a40a-11eb-993c-10d60b9a3546.mov

**Review by andreancardona — COMMENTED** [review]
also seeing Josefina's comment / bug :/

**Comment by emyarod** [comment]
@jnm2377 @andreancardona this does not appear to be a regression, unless I am misunderstanding you. can you clarify what the expected behavior should be and what existing behavior is WRT #8170?

**Comment by emyarod** [comment]
> That being said, when I tested the component, I realized enter only opens the menu box if there is no item already selected. If I've selected an item and the menu is closed, then I press enter to try to open again, it doesn't open. Is that expected?

regarding this question, yes this is expected as Enter typically does not expand a combobox (ref https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html)

**Comment by jnm2377** [comment]
@emyarod you're right. After testing the current component, it seems that the bug already exists. I can open an issue for it. 

https://user-images.githubusercontent.com/32556167/116612324-080a0a00-a8fd-11eb-9fc0-d091d73ddf68.mov

**Review by jnm2377 — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
I think just ensuring enter **does not close the menu with an invalid option** is enough for this PR. I think if we want to change how the list-box menus are opened/closed via keyboard (Enter vs space vs down arrow) we should track in a separate issue and have a consistent pattern throughout. 

This LGTM in reference to the original ticket 👍🏻 ✅

**Comment by nertzy** [comment]
This also closes #6613.

**Pull request merged**
