### PR TITLE
fix(ComposedModal): add null check before querySelector

### LINKED ISSUE #5923: [ComposedModal] Cannot read property 'querySelector' of null inside Jest
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

If I render an open ComposedModal inside a Jest testcase, I get an error and the testcase fails.  This appears to be because the component relies on the focusButton ref to be set (which isn't guaranteed in JSDom).   I think it can be fixed with a null check before trying to focus the button

> Is this issue related to a specific component?

Composed Modal 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Forces me to mock the ref in test renderer to get the component to render
https://reactjs.org/docs/test-renderer.html#ideas

> What browser are you working in?

Jest/JSDom

> What version of the Carbon Design System are you using?
 
"carbon-components": "10.9.1",
    "carbon-components-react": "7.9.1",

## Additional information

image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5923

Adds a null check for `focusContainerElement` so that tests do not error.

#### Changelog

**Changed**

- Adds in a `if (focusContainerElement)` check before any `querySelector` calls 

#### Testing / Reviewing

Make sure everything still works properly

### CODE REVIEW

**Comment by joshblack** [comment]
@tw15egan do we know what the specific issue is for running in JSDOM? I am surprised that this would happen unless they were doing server-side rendering 🤔

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Comment by asudoh** [comment]
Ref: Issue# 7740 at facebook/react repo

**Comment by tw15egan** [comment]
@joshblack according to issue @asudoh posted: 

Report
>It's not possible to test component that use ref with the react-test-renderer utilitiesTesting: the refs are always null.

Response
> This is not a bug. react-test-renderer doesn’t actually use the browser (or jsdom), so there are no real divs we could give you.

**Comment by joshblack** [comment]
Thanks @tw15egan! 🙏

**Review by joshblack — APPROVED** [review]

**Pull request merged**
