### PR TITLE
feat(number-input): new decorator prop

### LINKED ISSUE #17976: Decorator: NumperInput

### LINKED ISSUE #18004: Decorator: NumberInput

### PR DESCRIPTION
**Pull request by ariellalgilmore**
Closes #18004

Updates numper-input to include new decorator prop

#### Changelog

**New**

- new decorator prop, classes, and styles

**Changed**

- deprecated slug prop
- update rendering slug to render the decorator component but still set the size if it's an AILabel
- updated tests

#### Testing / Reviewing

Check dropdown with AILabel storybook and form with AILabel storybook (numberInput & fluid numberInput)

TODO:

- [ ] remove NumberInput with tooltip before merging!

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by annawen1 — APPROVED** [review]
LGTM!

**Review by riddhybansal — APPROVED** [review]

**Review by riddhybansal — CHANGES_REQUESTED** [review]
There is a minified error in playground while setting decorator

image

**Comment by ariellalgilmore** [comment]
@riddhybansal updated! thanks!

**Review by riddhybansal — APPROVED** [review]
LGTM !! just some formatting

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
