### PR TITLE
revert(button): revert changes to button for v11

### LINKED ISSUE #10294: Identify areas where `Button#hasIconOnly` is used and determine replacement
We are running into a number of situations that come in response to us removing part of the icon functionality from `Button` that we need to figure out the response for. In particular, buttons that only render an icon are no longer appearing as intended.

Areas that are impacted so far:

- [UI Shell Header](https://github.com/carbon-design-system/carbon/discussions/10247#discussioncomment-1788201)
- [Pagination](https://github.com/carbon-design-system/carbon/discussions/10247#discussioncomment-1788194)

### LINKED ISSUE #10505: [Bug]: HeaderGlobalAction styles are broken in v11
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v0.12

### React version

v17.0.2

### Description

As can be [seen in the Storybook for v11](https://carbon-react-next.netlify.app/?path=/story/components-ui-shell--header-base-w-skip-to-content) the `HeaderGlobalAction` (on the top right in the UI Shell Header, not visible until you hover) has severely broken styles. The icons are not centered properly, and the color is set incorrectly (the button default is not overwritten) and thus renders the button invisible until you hover.

### CodeSandbox example

https://carbon-react-next.netlify.app/?path=/story/components-ui-shell--header-base-w-skip-to-content

### Steps to reproduce

Got to https://carbon-react-next.netlify.app/?path=/story/components-ui-shell--header-base-w-skip-to-content and hover over the right side of the UI Shell Header.

I expect to see a centered icon before the hover and during it.
Actual: No icon can be seen before hovering, and during hovering it is hard to see and not centered.

I could not provide a sandbox example as I could not find a compiled & hosted version of the new styles.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by joshblack**
Closes #10505 
Closes #10294 

This PR reverts the changes we made to button for icon support. This should address most of the issues with components using `Button` as an icon button.

#### Changelog

**New**

**Changed**

- Revert changes to button to mirror v10 behavior

**Removed**

#### Testing / Reviewing

- Verify issues identified in referenced issues have been resolved
- Verify `IconButton` still works as intended

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
This also fixes the Pagination forward/back buttons issue @tw15egan discovered today

**Review by jnm2377 — COMMENTED** [review]
I can see the buttons now, but they still have some weird alignment issues with the icons.
Screen Shot 2022-01-25 at 11 04 48 AM

**Comment by joshblack** [comment]
@jnm2377 good spot, thanks for catching that. It seems like our reset helper has changed a bit and now will set `display: block` 🤔 

Let me go and update that real quick!

**Review by jnm2377 — APPROVED** [review]
LGTM 👍🏽

**Comment by tw15egan** [comment]
@joshblack noticing that the tooltips do not appear when hovering over Icon buttons (noticed in Pagination). Is this new behavior intentional?

**Comment by joshblack** [comment]
@tw15egan great catch, this is currently coming up because we are not including the tooltip styles in v11 and are trying to supplement them with popover/icon button usage.

I think this is something that we can ship as a known issue and use the next couple of sprints to either:

- Restore the tooltip styles for button tooltips
- Update our internal usage of Button to use the new `IconButton`
- Some other option??? lol

Let me know what you think!

**Comment by tw15egan** [comment]
@joshblack gotcha! I see that they are working as intended in the v10 source just not in v11. I think option 2 makes the most sense going forward in the v11 source.

**Pull request merged**
