### PR TITLE
refactor: Added types to TableActionList and wrapComponent

### LINKED ISSUE #12518: Add TypeScript types to TableActionList

### PR DESCRIPTION
**Pull request by imp-dance**
Closes #12518

This adds types to `wrapComponent` - and technically TableActionList - since it implements the function.

#### Changelog

**New**

- wrapComponent now automatically adds HTMLElement types to element

#### Testing / Reviewing

Tested types in local dev environment, seems to work well.

### CODE REVIEW

**Comment by imp-dance** [comment]
Also, I'm aware that the guide technically disallows typing normal `.js` files - so another (less clean in my opinion) approach to this would be just declaring the types like such:

```typescript
const TableActionList = wrapComponent({
  name: 'TableActionList',
  type: 'div',
  className: (prefix) => `${prefix}--action-list`,
}) as (props: PropsDefinition) => ReactNode;
```

**Comment by tay1orjones** [comment]
@imp-dance Thanks for taking this on - the ci tests are failing here right now

**Comment by imp-dance** [comment]
@tay1orjones Should be fixed now!

**Comment by tw15egan** [comment]
@imp-dance just updated the file, and it's gone away, it seems like the subtle gradient is causing some issues with Percy. Nothing wrong on your end

**Review by tw15egan — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
