### PR TITLE
chore(build): support for generating static HTML with feature flags

### PR DESCRIPTION
**Pull request by asudoh**
Refs #1149.

#### Changelog

**Changed**

- Moved the dependency injection logic to change feature logic from `server.js` to `templates.js`, so it can be used from Gulp build logic, too.
- Changed `html:dev` Gulp task to build static HTML with feature flags in use

#### Testing / Reviewing

Testing should make sure our production build or our dev env, including CF deployment, are not broken.

### CODE REVIEW

**Review by aledavila — APPROVED** [review]
Thanks for this !!

**Comment by alisonjoseph** [comment]
Hi Akira, thanks for working on this. I'm still not sure this solves our use-case for the website. The website needs to access both the current v9 html for a component AND also the experimental html. Unless I'm missing what command to run? 

Or were you suggesting we copy the html manually for these cases to the website?

**Comment by asudoh** [comment]
Hi @alisonjoseph as I talked briefly personally, letting `carbon-website` code access experimental HTML via `carbon-components` NPM package means _shipping_ the experimental HTML which I guess we don't want to. And your guess is correct - What I'm thinking of is doing `gulp html:source -e` and checking the built HTML (in `/path/to/carbon-components/html` directory) into `carbon-website` repo. Wondering if it makes sense to you - We can work together on this. Please don't hesitate to ping me if you have any questions/concerns. Thanks!

**Review by joshblack — APPROVED** [review]

**Comment by alisonjoseph** [comment]
Makes sense @asudoh , thanks!

**Pull request merged**
