### PR TITLE
fix(icon): embiggen caret and sort carets icons

### PR DESCRIPTION
**Pull request by chrisconnors-ibm**
**"A noble spirit embiggens us all"**
_- Jedidiah Springfield_

2 for one. Enlarges the carets and sort caret variants per @mjabbink and adjusts their geometries to improve their scaling (especially to 16px) eliminating a host of bespoke 16 px icons

#### Changelog

**Changed**

- adjusts geometry of 
32/caret--down.svg
32/caret--left.svg
32/caret--right.svg
32/caret--sort--down.svg
32/caret--sort--up.svg
32/caret--sort.svg
32/caret--up.svg
deletes -16 props from packages/icons/icons.yml for removed assets

**Removed**

- deletes
16/caret--down.svg
16/caret--left.svg
16/caret--right.svg
16/caret--sort--down.svg
16/caret--sort--up.svg
16/caret--sort.svg
16/caret--up.svg

#### Testing / Reviewing

Review these preview icons on @2x and @1x screens:
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--down
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--down%20(Downsized%20to%2016)

https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--up
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--up%20(Downsized%20to%2016)

https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--left
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--left%20(Downsized%20to%2016)

https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--right
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--right%20(Downsized%20to%2016)

https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--sort
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--sort%20(Downsized%20to%2016)

https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--sort--up
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--sort--up%20(Downsized%20to%2016)

https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--sort--down
https://deploy-preview-5412--carbon-elements.netlify.com/icons/examples/preview/#32%2Fcaret--sort--down%20(Downsized%20to%2016)

### CODE REVIEW

**Comment by designertyler** [comment]
Here are the new caret sizes mocked up with the data tree. They seem huge and would probably require extra padding when paired with the file type icon.

Is this the result we were expecting from this PR?

image

**Comment by chrisconnors-ibm** [comment]
agree: was working w Conrad as you made that accurate observation :) .

original on the left, new size on the right:
image
image

**Comment by chrisconnors-ibm** [comment]
mocked up with the sizes just pushed:
image

**Comment by chrisconnors-ibm** [comment]
https://github.com/carbon-design-system/carbon/issues/5421 depends on this PR.

**Comment by mjabbink** [comment]
👍

**Review by laurenmrice — APPROVED** [review]

**Review by conradennis — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Pull request merged**
