### PR TITLE
docs(tag): remove role=listitem from Tag storybook demo

### LINKED ISSUE #4428: AVT 1 - Tag (default & filter) React Component has DAP violations
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon React Version 7.7.1
DAP 1.8.0.0 Sept 2019 WCAG 2.1 ruleset

## Description
Run DAP on the Tag component and the following violation is present:
Screen Shot 2019-10-22 at 2 44 38 PM

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4428 

~This PR follows up with https://github.com/carbon-design-system/carbon/pull/3017 by wrapping the `Tag` component in storybook in a div that has `role="list"` on it. (#3017 did this in the vanilla components.) This PR clears the DAP violation as well.~

Per feedback I just removed the wrappers & also removed the `role="listitem"` passed to the `Tag` components.

#### Changelog

**Changed**

- ~wrap `Tag` components in a div that has `role="list"`` remove `role="listitem"`

#### Testing / Reviewing

View the `carbon-components-react` storybook deploy, go to the default & filterable `Tag` stories, and run the DAP tool.

### CODE REVIEW

**Comment by joshblack** [comment]
Would it be better if we removed `role="listitem"` from `span` and just recommended folks place tags in a `ul` or `ol` with `li` so the roles are inferred?

**Review by joshblack — COMMENTED** [review]
Left a question above 👀

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by jendowns** [comment]
@joshblack  --

> Would it be better if we removed role="listitem" from span and just recommended folks place tags in a ul or ol with li so the roles are inferred?

Oh yes, the `ul` / `li` route would be much better IMO.
But this may involve adding some styles to reset the list element defaults?
Moreover was your idea here to also adjust the handlebars template in the `components` package? (as this PR is a follow-up of https://github.com/carbon-design-system/carbon/pull/3017)

Considering that -- do you still prefer to go the `ul` / `li` route & do you want me to change the handlebars template as well?

**Comment by joshblack** [comment]
@jendowns it would make sense to me to just remove the `role="listitem"` as a tag _could_ be used outside of a list context and if folks want the list semantics they should wrap in a ul/ol with an li with the appropriate resets. Let me check with our a11y project team though!

**Comment by abbeyhrt** [comment]
We might want to follow up with @snidersd but I agree that removing `role="listitem"` makes the most sense!

**Comment by jendowns** [comment]
Thanks @joshblack & @abbeyhrt! I went ahead and just removed the wrappers + also removed the `role="listitem"` that was passed to the `Tag` components in the story 👍

**Comment by snidersd** [comment]
@abbeyhrt  @jendowns The role="list" and role="listitem" were added to fix screenreader issues. Please see #2738, #3017 and #3034 which explain the issue when attempting to read multiple tags with JAWS and NVDA as well as the associated fixes.

**Comment by joshblack** [comment]
@snidersd I think this behavior was surprising given (what I thought) was a requirement that direct descendants of `<ul>` needed to be an `<li>`. It would seem that we could have kept `span` for the tag, but then arranged it such that it could be placed in a `<ul>` under an `<li>`. Meaning:

```jsx
<ul>
  <li><span>The tag</span></li>
</ul>
```

When digging through the issues, was trying to figure out details for why it was done in this way and it seems like in vanilla we were using `div` with a role of `list` which precipitated `role="listitem"` for the tag. Would the preference overall just be to use the native DOM elements, in this case?

**Comment by jendowns** [comment]
Thanks @joshblack & @snidersd!

I just wanted to point out that this proposed changed is only to a *demo* page of a single `Tag`. The component itself is just a `span` element with text inside of it.

Whether we wrap this single `Tag` *demo* in a `ul` & an `li`, or if we wrap it with a div that has `role="list"` and then pass in `role="listitem` to the `Tag` itself, the component will continue to render as a simple `span`. 🤔 

So I'm wondering if a good step here could be add like a sort of `TagList` / `Tags` component that would help people have the right structure when multiple `Tag` elements are lined up (with the right list reset styles applied and all that good stuff):

```jsx
<TagList> // renders as a `ul`
  <Tag>Blah</Tag> // renders as an `li` 
</TagList>
```

but for now, in this demo I can wrap the `Tag` in list elements.

**Comment by joshblack** [comment]
Great point @jendowns! Sorry for diverging so hard haha, I think you're spot on that if it's not in a list then there is no reason for this to be on there. Thanks for doing this!

**Review by joshblack — APPROVED** [review]

**Comment by jendowns** [comment]
Oh no worries @joshblack! So would you still like for me to wrap this in a `ul` + `li` to demonstrate best practices? (EDIT: And maybe if it helps, add another `Tag` or 2 to the storybook demo, inside the list?)

And/or what did you think of the idea of adding like a wrapper component that has all of this built in?  (EDIT: the wrapper would be a future thing, not for this PR...  and it would be easy enough do IMO 🤔 If the idea works, I mean)

**Comment by emyarod** [comment]
on a side note, one thing to be aware of with adding a wrapper is how it might affect styles for components that consume tags

**Comment by jendowns** [comment]
Yeah that's a good point @emyarod -- I feel like this hypothetical `TagList` / `Tags` wrapper would be optional 🤔 (and without the wrapper included, a normal `Tag` would just be the same old `span`)

**Comment by jendowns** [comment]
Hey everyone where have we landed on this one? I noticed it was approved but I was wondering on status and/or if there's any additional feedback for me? Thanks!

**Pull request merged**
