### PR TITLE
feat(breadcrumb): add support for current page, update text styles

### PR DESCRIPTION
**Pull request by joshblack**
Closes https://github.com/IBM/carbon-components/issues/1910

Work done for component audit. Add support for current page use-case, update text styles.

#### Changelog

**New**

- Breadcrumb now supports current page through `.bx--breadcrumb-item--current` and `[aria-current='page']`
- New variants, docs, and migration guide for breadcrumb

**Changed**

- Text styles in Breadcrumb

**Removed**

#### Testing / Reviewing

We are testing the following permutations:

image

Link styles (for underlines) will be handled under the Link component.

### CODE REVIEW

**Comment by joshblack** [comment]
For devs who are reviewing, I'm curious what you think would be best for the `--current` selector for breadcrumb 🤔 Had a couple options floating around, namely:

- `bx--breadcrumb-item--current`
- `bx--breadcrumb-item--current-page`
- `bx--breadcrumb-link--current`
- `bx--breadcrumb-link--current-page`

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Wrt class name, I think the choice seen in this PR is fine, but let's see what others thanks. Thanks @joshblack!

**Comment by alisonjoseph** [comment]
`bx--breadcrumb-item--current` makes the most sense to me 👍

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- Firefox and Chrome currently have a black box around the text and an underline for the active state. It should just have a #171717 underline. Looks correct in Safari.
screen shot 2019-02-25 at 2 22 31 pm

- I am not getting a focus if I tab with my keyboard in Firefox or Safari, but I do get it in Chrome.

**Comment by joshblack** [comment]
@laurenmrice I captured the link bit of this over in: https://github.com/IBM/carbon-components/issues/1909 want to comment there? I think since breadcrumb uses link it will be fixed once the link component goes green ✅ 

For the focus, firefox and safari doesn't focus links by default so I think you do `option+tab` 👍

**Review by tw15egan — APPROVED** [review]

**Comment by emyarod** [comment]
the link styles should now be carried over from https://github.com/IBM/carbon-components/pull/1960

**Review by laurenmrice — CHANGES_REQUESTED** [review]
One change- The active state should have a 1px underline instead of the large underline. This is something that needs to change for the Link component too. It is only happening in Firefox and Chrome. It looks correct in Safari.

**Comment by emyarod** [comment]
got it, spec change is being tracked here https://github.com/IBM/carbon-components/issues/1995

**Comment by asudoh** [comment]
Merging as the only open review comment is of another component and is tracked. @laurenmrice Please don't hesitate to speak up if we shouldn't have done it. Thanks!

**Pull request merged**
