### PR TITLE
fix(modal): replace width rule with padding

### LINKED ISSUE #3412: Modal body overflows unexpectedly and scroll bar is not in container
We recently had a user report that detailed that the modal body overflows unexpectedly, and the resulting scroll bar is also placed in an awkward location:

image

https://slkm7.codesandbox.io/

Can reproduce on latest Chrome.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3412

This PR replaces the width rule on modal header and content with a padding change instead

#### Testing / Reviewing

Ensure the modal appears correct

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by elizabethsjudd** [comment]
Not that I disagree with this change but I'm curious, isn't this a breaking change for any user of Carbon 10 that has asked how to overwrite the 75% width setup for modal (i've seen it multiple times in slack and the issue backlog)?

**Review by aagonzales — APPROVED** [review]
LGTM!

**Review by tw15egan — APPROVED** [review]
👍

**Comment by asudoh** [comment]
@elizabethsjudd I don't think it's likely, but let us know if you can think of any specific case.

**Pull request merged**
