### PR TITLE
Update project dependencies in-range

### PR DESCRIPTION
**Pull request by joshblack**
This is a quick PR to try and consolidate our dependencies into common versions within the range specified in `package.json`. This does **not** upgrade dependencies out-of-range, for example going from `v1.0.0` -> `v2.0.0` if `^1.0.0` is given as the range.

The goal of this is to create a slimmer profile with respect to our node modules, and will be helpful moving forward with updating dependencies in a future PR.

Note: this process was done using `yarn upgrade-interactive`.

#### Changelog

**New**

**Changed**

- `yarn.lock` and `.yarn-offline-mirror`

**Removed**

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Comment by joshblack** [comment]
@asudoh do you have any idea where the `add` handelbars helper comes from? Seems like it's missing with the bump to `express-handlebars` and `handlebars` to `4.1.2` but having a hard time tracking down where it's being defined.

**Comment by asudoh** [comment]
@joshblack It comes from `handlebars-helpers`: https://github.com/helpers/handlebars-helpers/blob/0.10.0/lib/math.js#L22-L39 We register that set of helpers at: https://github.com/carbon-design-system/carbon/blob/7a95a7d/packages/components/tools/templates.js#L34 - Need to see if there is a change in the way of registering helpers in recent Handlebars version.

**Review by emyarod — APPROVED** [review]
apparently React fragments are causing the tests to fail all of a sudden? and vanilla tree shaking test has some leftover code that isn't being trimmed

otherwise looks good to me

**Comment by joshblack** [comment]
Fixed the lint issue, however it seems like for pure-modules the lodash substitution isn't working anymore, pre-replace we have the following being emitted:

image

Any thoughts on the this @asudoh?

**Comment by asudoh** [comment]
@joshblack It's broken due to Rollup's introduction of pure annotation support in itself. #2817 should address it.

**Comment by joshblack** [comment]
Sounds good, thanks @asudoh!

**Pull request merged**
