### PR TITLE
feat(text-input): add warn prop

### LINKED ISSUE #6492: Contribution: Add yellow warning state to Select
Explanation: As a Front end developer, I would like to warn users sometimes on the Select component. The red warning bar exists, but unfortunately, using it may sometimes be the wrong choice because the red color implies an error. Therefore, I believe that Carbon should include a yellow warning bar as an alternative option to the the red error bar if the selected value is invalid.

Research: The DUX (developer user experience) squad at IBM needs to inform an IBM Cloud user on the free plan when they have exceeded the alloted number of Lite plan services used. Consider a user who is creating the "Watson Assistant With Discovery - Serverless" starter kit. The starter kit generates 2 IBM Cloud services, "Discovery" and "Watson Assistant". Unfortunately, the user is already using the "Watson Assistant" service on a different project so the user cannot generate this starter kit.

screenshot-localhost_3000-2019 07 17-11_43_09

When the user changes "Lite" to "Standard" under Watson Assistant, the warning above it disappears because now no violations occur.

screenshot-localhost_3000-2019 07 17-11_46_50

This is the current way we broadcast the warning to the user.

Our problem right now is that the warning notification is displayed twice rather unnecessarily. Therefore our solution is to contribute to carbon and add a new option for warning purposes.

Our proposed solution will look the following:

screenshot-localhost_3000-2019 07 17-12_04_38

To see more of our discussion: see https://github.ibm.com/arf/planning-devux/issues/2751

Developer: Jeffrey Wang (jeffreyw@ibm.com)

### PR DESCRIPTION
**Pull request by janhassel**
Related issue: https://github.com/carbon-design-system/carbon/issues/6492

This is a draft PR with a sample implementation of a warning state for the TextInput component to start a conversation around the technical side of things.

@aagonzales Right now, the icon is still the round warning icon. I haven't been able to change it yet, since the triangle one doesn't have a separate inner path to color the exclamation mark. I'll open an issue for it shortly.

@joshblack I'd love your input about the implementation and if this would be the right way to go. Also, for accessibility: I believe `aria-invalid` shouldn't be emitted since it could lead to confusion for users that rely on screen readers, would you agree?

### CODE REVIEW

**Comment by aagonzales** [comment]
The warning text color should match the label color and use `$text-02`. Other than and the using the warning-alt icon when its ready it looks fine from a visual perspective. 

Also a good thing to note is we are planning on moving the helper text to be under the input instead of under the label so this will override any helper text that is there as well.

**Comment by janhassel** [comment]
@aagonzales Thanks for the heads-up. The helper text update will be included in #5867 it seems. So I’ll make sure to update the warning text logic accordingly once that is merged 👍

**Comment by joshblack** [comment]
> I believe aria-invalid shouldn't be emitted since it could lead to confusion for users that rely on screen readers, would you agree?

Makes sense to me!

**Comment by janhassel** [comment]
I think the only thing blocking this then would be #5919. Once that is fixed, I can update the snapshot and this should be pretty much good to go. Support for the other inputs could then be added one by one in new PRs to keep them small and manageable.

**Comment by joshblack** [comment]
@andreancardona @rjhenriquez  let me know if you all have questions around this PR / review process!

**Review by andreancardona — APPROVED** [review]
@janhassel looks awesome! 🎉

**Review by rjhenriquez — APPROVED** [review]

**Comment by tw15egan** [comment]
Screen Shot 2020-07-20 at 10 14 50 AM


For visual review since Netlify is having problems

**Review by aagonzales — APPROVED** [review]
🎉 Looks awesome!!

**Pull request merged**
