### PR TITLE
fix(search,textarea): update placeholder-colors mixin with accessible text color

### LINKED ISSUE #3332: AVT 2 - Search Placeholder text in form input fields does not meet WCAG 2.0 color contrast requirements
## Environment
macOS Mojave version 10.14.5
Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
Voice Over

## Detailed Description
Use Color Contrast Analyzer to test the background color of the Search placeholder text against the background color of the text input field. See screenshot below:
Screen Shot 2019-07-10 at 11 02 01 AM

See [WCAG Form Tutorial for placeholder text guidance](https://www.w3.org/WAI/tutorials/forms/instructions/#placeholder-text). 
Note: All form inputs with placeholder text appear to have this issue.

### LINKED ISSUE #4187: AVT 2 - TextArea Placeholder text in form input fields does not meet WCAG 2.0 color contrast requirements
Environment
macOS Mojave version 10.14.5
Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
Voice Over

Detailed Description
Use Color Contrast Analyzer to test the background color of the Search placeholder text against the background color of the text input field. See screenshot below:
Screen Shot 2019-10-02 at 3 18 40 PM

See WCAG Form Tutorial for placeholder text guidance.
Note: All form inputs with placeholder text appear to have this issue.

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #3332 
Closed #4187 

This changes the text color in the mixin `placeholder-colors` from `$text-03` -> `$text-05` so that the placeholder text is accessible. It also updates `_search.scss` to use the `placeholder-colors` mixin. 

#### Changelog

**Changed**

- `placeholder-colors` mixin 
- `_search.scss` uses mixin instead of defining color inline

#### Testing / Reviewing

Use a color contrast analyzer to ensure that the placdeholder text meets AA requirements.

### CODE REVIEW

**Comment by dakahn** [comment]
@aagonzales this swap here would get all of our placeholder text within contrast requirements.

**Comment by aagonzales** [comment]
@dakahn @abbeyhrt Wait ok let's back this up for a minute. This quick fix is about to raise a sticky token issue. `$text-03`'s only purpose is for placeholder text. If the task is to update placeholder text across the system and not just in search (which was the original issue) then we need to look at this from the system level and potentially just update the value of `text-03` instead of changing the token. 

Question: are we wanting to update all placeholder text to pass 4.5:1 color contrast standards? If yes, the I think we need to figure out a system wide game plan for that regarding our tokens.

**Comment by aagonzales** [comment]
If we want to do this across the board (for all helper text) then we need to update `$text-03` to use the values that the new token `$text-05` uses. And hopefully, kill `$text-05` if its not too late.

**Comment by abbeyhrt** [comment]
My understanding is that we do want to update all placeholder text to pass 4.5:1 color contrast standards, but would definitely want @dakahn to weigh in! I know these are issues in Search (as you mentioned) and in TextArea so we could just change those in the mean time and defer this until later if we want?

**Comment by dakahn** [comment]
@aagonzales is it cool if we update Search and TextArea and defer this system wide change until later?

**Comment by aledavila** [comment]
@dakahn wouldn't this change update placeholder text system wide? we would only want to update then per component

**Comment by abbeyhrt** [comment]
@aledavila I think that's the main question here, do we want to update placeholder text system wide so it's all accessible or just fix it per component that there is an issue for. At least if I'm understanding this correctly

**Comment by aagonzales** [comment]
Yeah we change this now but we might have to change the token back again when we update the system.

**Review by vpicone — APPROVED** [review]

**Comment by abbeyhrt** [comment]
@aagonzales I changed it so the placeholder text color is only different for TextArea and Search!

**Review by aagonzales — APPROVED** [review]
Looks good!

**Review by dakahn — APPROVED** [review]

**Pull request merged**
