### PR TITLE
fix(date-picker): upgrade to latest flatpickr

### PR DESCRIPTION
**Pull request by tw15egan**
Refs https://github.com/IBM/carbon-components-react/issues/1899
Closes https://github.com/IBM/carbon-components/issues/1173

Upgrades Flatpickr to latest version

Adds in some overrides to hide browser default number input styles

### CODE REVIEW

**Comment by tw15egan** [comment]
cc @asudoh, not sure how this interferes with our current logic, but noticed in that issue that was a concern before we moved up to 4. Just want to make sure this doesn't have any unintended consequences. I did not notice anything off

**Comment by asudoh** [comment]
@tw15egan Thank you for doing this! Given we are just moving up the patch number I don't have any major concerns. One thing to be careful is tree-shakability, but given Travis didn't complained about that it seems fine. We need to look into unit test errors, though.

**Comment by asudoh** [comment]
https://github.com/flatpickr/flatpickr/issues/1682 seems to have caused the unit test error here.

**Comment by tw15egan** [comment]
Thanks for creating that issue! WIll keep an eye out for updates, we can hold off on this PR for now then

**Review by asudoh — APPROVED** [review]
LGTM :+1: - Thanks @tw15egan!

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
