### PR TITLE
Notification a11y color contrast

### LINKED ISSUE #13616: [a11y]: Notification - inline - close button not tabbable
### Package

@carbon/react

### Browser

Chrome

### Operating System

MacOS

### Package version

latest

### React version

_No response_

### Automated testing tool and ruleset

manual testing

### Assistive technology

_No response_

### Description

1. The close button on the inline variation of `Notification` doesn't seem to be tabbable.
2. Ran into this while doing our v11 syncing work with Carbon Web Components - @oliviaflory pointed out the fill for the warning icons are not consistent and they have to have a black fill to pass color contrast.

Screenshot 2023-04-17 at 5 20 21 PM

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-notifications-inline--playground

### Steps to reproduce

Go to storybook and try tabbing into the inline notification to the close button

https://react.carbondesignsystem.com/?path=/story/components-notifications-inline--playground

For the icon fill issue, go to the storybook
1. Select inline notification variation
2. Set 'low-contrast' prop to true
3. select between the different warning "kind" variations (warning-alt and warning) and compare the icon fill colors

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by guidari**
Closes #13616 

1 - The close icon button cannot be tabbable.

"Due to this they cannot contain interactive elements and do not receive focus. For this reason, the Close button is removed from the accessibility tree and is basically just an affordance for sighted users only."

________________

2 - Added the same style that `warning` icon has to the `warning-alt` in low-contrast.

For that to happen I'm checking the `first-of-type` in path and adding the color

#### Testing / Reviewing

Open the Notification stories and check if the `warning-alt` icon is black instead of white in **low-contrast** mode

### CODE REVIEW

**Review by francinelucca — APPROVED** [review]
LGTM!

**Review by tay1orjones — APPROVED** [review]
Awesome!

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Actually, check out percy, I think this could cause regressions. In the fluid inputs the warning icon has changed.

https://github.com/carbon-design-system/carbon/assets/3360588/f32611e9-8e8a-4fc4-a53a-6038b191d7f9

**Comment by tay1orjones** [comment]
https://github.com/carbon-design-system/carbon/assets/3360588/f32611e9-8e8a-4fc4-a53a-6038b191d7f9

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
