### PR TITLE
feat(docs): add WHCM support documentation

### PR DESCRIPTION
**Pull request by dakahn**
Addresses recent decisions around Carbon's Windows High Contrast Mode support on Firefox. Provides some background on WHCM and how browsers handle it. 👍

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by elizabethsjudd — APPROVED** [review]
Thanks for adding this documentation!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @dakahn!

**Comment by shinytoyrobots** [comment]
When is our next patch release, so I can update Cloud on when to test this?

**Comment by carmacleod** [comment]
@dakahn Just FYI, some recent discussion on WHCM starting here: https://github.com/w3c/aria-practices/issues/1132#issuecomment-534886650 and including upcoming CSS changes discussed in the MSFT slides from the 2019 TPAC talk.

**Pull request merged**
