### PR TITLE
fix(OverflowMenu): remove default tabindex and SVG focusable attribute

### LINKED ISSUE #6935: Unnecessary focusable and tabindex in an OverflowMenu component
## focusable="false" in a span component and tabindex="0" in a button component

Found while using OverflowMenu component of carbon-components-react

- [x] `carbon-components-react`

## Detailed description

--> The issue got reported as part of the Accessibility Testing of IBM Cloud Pipeline pages. @carmacleod, in [this](https://github.ibm.com/org-ids/roadmap/issues/12393#issuecomment-23781859) comment, has pointed out that:
- `focusable="false"` in a `span `element does not look okay as `span` doesn't support the focusable attribute.
- Also, `tabindex="0"` is set by default for a button whereas buttons are focusable and in the tab order by default.

--> These issues DO NOT cause any harm when it comes to the functionality of the component but it doesn't look good. 
--> I tried to get rid of these minor issues in the `pipeline-ui` code where `OverflowMenu` component is called. However, it looks like the default values are set at these places - for [focusable](https://github.com/carbon-design-system/carbon-components-react/blob/c3bf0123a2a98ca84acfc7e86e69840eaf57a89e/src/components/OverflowMenu/OverflowMenu.js#L524) and for [tabindex](https://github.com/carbon-design-system/carbon-components-react/blob/c3bf0123a2a98ca84acfc7e86e69840eaf57a89e/src/components/OverflowMenu/OverflowMenu.js#L219).

--> Please consider taking care of these minor issues inside the carbon-component itself or it would be helpful to provide a feature to disable these attributes inside the components where it is not necessary or recommended.

Screen Shot 2020-09-28 at 6 47 52 PM

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6935

This PR removes the redundant default tabindex value on the overflow menu trigger button and also removes the redundant `focusable` attribute from the icon props. It looks like the `focusable="false"` was meant to prevent extra tab stops in IE11, but I was unable to replicate that issue

#### Changelog

**Removed**

- default tabindex value
- `focusable` attribute on trigger button SVG

#### Testing / Reviewing

Confirm that the trigger button no longer receives a tabindex value by default and that there are no changes to focus behavior and tab stops particularly in IE11

### CODE REVIEW

**Review by dakahn — CHANGES_REQUESTED** [review]
Seems like this has broken keyboard controls for the menu itself on Firefox latest
image

**Comment by emyarod** [comment]
that was a separate existing issue fixed in https://github.com/carbon-design-system/carbon/pull/6978, try updating your branch to pull in the latest commits to Carbon

**Comment by joshblack** [comment]
bump @dakahn @tw15egan when you get a sec today 👀

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by dakahn — APPROVED** [review]

**Comment by carmacleod** [comment]
For the record, it was not the `focusable=false` on the SVG that was unnecessary, it was the `focusable="false"` on the span inside the SVG. A google of "SVG focusable=false IE11" still finds a lot of hits, so you may still need `focusable=false` on the SVG itself. (Note that the bug was fixed in old Edge, but as far as I know it was never fixed in IE11, so I'm surprised that you didn't see an extra tab stop in IE11)

**Comment by emyarod** [comment]
yeah the SVG itself still has `focusable=false` by default since that attribute is added when we generate our icons

**Comment by carmacleod** [comment]
Ah, ok. Thanks for the explanation. I was confused by the title and opening comment in this PR. :)
I just tested whether SVGs in IE11 still need the focusable=false, and they definitely still need it.
Here's my little test case: https://carmacleod.github.io/playground/svg-test.html
(Just FYI at this point, since you didn't actually delete the focusable=false from the SVG itself 😄 )

**Pull request merged**
