### PR TITLE
feat(styles): add initial entrypoints and tests for styles

### LINKED ISSUE #8294: Add style entrypoints to @carbon/styles
After our experiment converting to Sass Modules, it's time to create some of the entrypoints that came up from this exploration and add tests for them. These entrypoints include, but are not limited to:

- [x] Color
- [x] Motion
- [x] Type
- [x] Grid
- [x] Utilities
  - [ ] Focus
  - [x] Conversion
- [x] Theme
- [x] Settings
  - [x] prefix
- [x] Feature flags
- [x] Reset

### PR DESCRIPTION
**Pull request by joshblack**
Closes #8294

Updates our `@carbon/styles` package with new entrypoints and tests. This PR also adds in an initial style guide for testing Sass and a template for our README for `@carbon/styles`

#### Changelog

**New**

- Add new entrypoints for the `@carbon/styles` package
- Add scaffold for README for `@carbon/styles`
- Add tests for entrypoints in `@carbon/styles`
- Add initial style guide for testing Sass

**Changed**

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
bump @dakahn @jnm2377 if you have any questions!

**Review by dakahn — APPROVED** [review]
lgtm 🏄🏽

**Comment by joshblack** [comment]
bump @jnm2377 when you have a sec!

**Comment by joshblack** [comment]
bump @jnm2377 when you get a sec!

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
