### PR TITLE
Fix/misaligned number controls

### LINKED ISSUE #1312: NumberInput: Misalignment of number controls
@Joseph-Hitchcock moved from https://github.com/IBM/carbon-components-react/issues/1468

When a NumberInput's invalidText wraps onto another line, it causes the number controls to no longer be centered in the input field.

image

image

This [code sandbox](https://codesandbox.io/s/wqwmxpo435) illustrates this behavior.

### PR DESCRIPTION
**Pull request by vividh**
Closes #1312 

This PR addresses the misalignment of number input controls in the presence of invalid text error.

#### Changelog
**Changed**
- Use `top` to position number controls instead of `bottom`
- Adjust for input label / helpertext presence to calculate position offset
- Added new input demo (without label) in NumberInput demo page
- Fix a typo in number input README

#### Testing / Reviewing
Use the NumberInput demo page to test out. The last input demo has both helpertext and label. Test out the following remaining scenarios:
- **With only helper text:** Remove label, Add `bx--number--nolabel` class
- **With only label:** Remove helpertext, Remove `bx--number--helpertext` class
- **Without label and helper text:** Remove label and helpertext, Add `bx--number--nolabel` class, Remove `bx--number--helpertext` class

### CODE REVIEW

**Review by tw15egan — CHANGES_REQUESTED** [review]
Thanks for taking this on! Looks good for the most part, seems like we just need to handle the case of there being no label _as well as_ no invalid text.

screen shot 2018-10-30 at 9 45 41 am

**Comment by vividh** [comment]
@tw15egan That case is already handled as well (See screenshot below).

Since we're positioning off the top, presence or absence of invalid text won't affect the control's position. I think you just missed to add the `bx--number--nolabel` class in your test.

screen shot 2018-10-30 at 9 07 16 pm

**Review by tw15egan — APPROVED** [review]

**Comment by tw15egan** [comment]
My mistake, I had `bx--number__nolabel` rather than `bx--number--nolabel` 🤦‍♂️

**Review by alisonjoseph — APPROVED** [review]
LGTM! 

Created an issue over in the React library also so we don't forget to add these updates there https://github.com/IBM/carbon-components-react/issues/1506

**Comment by vividh** [comment]
Great! I was wondering about the React changes as well.

**Comment by alisonjoseph** [comment]
@vividh can you fix the merge conflict then we can merge this in! thanks

**Pull request merged**
