### PR TITLE
fix(dropdown): update overflow style rules for ie, edge, and safari support

### LINKED ISSUE #4067: [Dropdown] Scroll missing in non-chrome browsers
## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

> Describe in detail the issue you're having.

In non-chrome browsers, when a dropdown has more than 6 options in it and has been opened, the scroll is missing, all the content is visible, and only the first 6 options have a background

> Is this issue related to a specific component?

Dropdown

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
chrome, safari, firefox, ie11, edge

> What version of the Carbon Design System are you using?
10.6x

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Watson-Health

## Steps to reproduce the issue

1. Add more than six items to a dropdown
2. view in non-chrome browser (seen in Safari, Firefox, IE11, Edge)
3. open dropdown
4. see missing scroll and end of background color

## See an example

https://codepen.io/scottnath/pen/OJLdpar

## Additional information

* *left image: chrome*
* *right image: safari*
Screen Shot 2019-09-23 at 5 48 55 PM

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4067

The shorthand syntax `overflow: hidden auto` is not supported in Safari, unfortunately:

Screen Shot 2019-09-27 at 4 21 16 PM

See on `CanIUse` for Safari: https://caniuse.com/#feat=css-overflow

> Does not support the two value `overflow` shorthand

Screen Shot 2019-09-27 at 4 27 30 PM

EDIT: IE 11 and Edge also do not support the two value shorthand.

#### Changelog

**Changed**

- changed `overflow: hidden auto` to two separate rules: `overflow-x: hidden` and `overflow-y: auto`

### CODE REVIEW

**Review by dakahn — APPROVED** [review]
Cool solution and duley noted. Really great PR description as well 💯

**Review by emyarod — APPROVED** [review]
looks good to me, also resolves the issue in IE

**Review by joshblack — APPROVED** [review]
Could you add a quick comment to explain this? 🙏   Just so we don't change this in the future lol

**Comment by jendowns** [comment]
@joshblack done! Also updated the title to better reflect the 3 browsers affected.

**Pull request merged**
