### PR TITLE
docs(number-input): remove examples with incorrect usage patterns

### LINKED ISSUE #1947: Invalid number input without error text should be removed from docs
Including the invalid number input example without required error text is confusing and implies that this pattern is alright to use

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1947

Related: https://github.com/IBM/carbon-components/pull/1622 https://github.com/IBM/carbon-components/pull/1764

This PR removes number input documentation examples that showcased incorrect usage patterns

### CODE REVIEW

**Comment by asudoh** [comment]
Wanted to double-check on below from the originating issue (#1947):

> Including the invalid number input example without required error text is confusing and implies that this pattern is alright to use

@IBM/carbon-designers Does @emyarod's assessment here make sense to you...? Thanks!

**Comment by emyarod** [comment]
for additional context, this started from a discussion in Slack @asudoh https://ibm-cloudplatform.slack.com/archives/GD8JG6JR3/p1551305202000500

**Comment by asudoh** [comment]
OK @emyarod now I see it's from @aagonzales, thank you for clarifying! Wondering why removed some examples with `data-invalid` as well as error text...? Am I missing something...?

**Comment by emyarod** [comment]
those examples were missing labels, but if that is a valid pattern I can add those examples back

**Comment by asudoh** [comment]
Thanks @emyarod for clarifying! I think the complaint is against missing invalid text for error state, instead of missing label. Does it make sense to you...?

**Comment by emyarod** [comment]
yeah I figured we did not support the other case that I removed either, but I added it back @asudoh

**Review by aagonzales — APPROVED** [review]
Yeah this is good. It was about removing the example without the invalid error message text.

**Review by tw15egan — APPROVED** [review]
👍

**Review by asudoh — CHANGES_REQUESTED** [review]
> It was about removing the example without the invalid error message text.

Thank you for clarifying @aagonzales! I put my earlier comment because examples _with_ the invalid error message text are removed. Let's see what @emyarod comes up with.

> but I added it back

@emyarod Have you pushed your change...? Thanks!

**Review by asudoh — APPROVED** [review]
Got a clarification from @emyarod that the removed markup is just for testing icon position without invalid test, which makes everything reasonable - Thanks @emyarod for your clarification!

**Pull request merged**
