### PR TITLE
fix(ExpandableTile): resolves VO issues

### LINKED ISSUE #3375: AVT 3 - React Expandable Tile has multiple screenreader issues with VoiceOver or JAWS
## Environment
macOS Mojave version 10.14.5
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
Voice Over
Note: This issue may be related to the DAP issue #3374.
<and>
iOS 12.3.1
Safari
VoiceOver
<and>
Windows 10 
FireFox Quantum 68.0
JAWS 18
## Detailed Description
1. Start VO
2. Press Control-Option-Shift-Down Arrow to enter the Web area, Nothing focused and VO does not announce anything.
3. Press Control-Option-Right Arrow, VO announces “Expand button main”.
4. Press Control-Option-Right Arrow, VO announces “Above the fold content”.
5. Press Control-Option-Right Arrow, VO announces “Below the fold content”.

## Expected Result:
1. Press Control-Option-Shift-Down Arrow to enter the Web area, VO should announce “Above the fold text”
2. Press Control-Option-Right Arrow, VO announces “Expand button main”, but VO should announce the button label and the current state using aria-expanded=false. 
3. User should be required to press the button and VO should announce the expanded state using aria-expanded=“true” before the “Below the fold content” gets focus. 
4. Press Control-Option-Right Arrow, VO announces should announce “Below the fold content”.  Note: “Below the fold content” is announced when the Tile is not expanded. See screenshot below:
Screen Shot 2019-07-11 at 4 21 03 PM

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #3375 

(This does the same thing as #4052 just without that pesky .tgz file that was messing with the build)

This PR updates ExpandableTile so that the screenreader announces the above the fold content and the below the fold content and the state of the tile, expanded or not. 

#### Changelog

**Changed**

- splits the content of ExpandableTile into two divs, one with above the fold content and one with below the fold content so that the VO reads the Above -> button -> below content in that order.   
- update tests to verify aria-label on the button and not `ChevronDown16`

**Removed**

- `uid ` package, I removed where it was being used. 
- all the attributes on `ChevronDown16`, by default our icons are hidden so I moved the aria-label to the button that the svg is contained by. 

#### Testing / Reviewing
Verify in Storybook using VoiceOver that this happens: 
- Press Control-Option-Shift-Down Arrow to enter the Web area, VO should announce “Above the fold text”
- Press Control-Option-Right Arrow, VO should announce the button label and the current state of expanded.
- Press the button with Control-Option-Space and VO should announce the expanded state using aria-expanded=“true” before the “Below the fold content” gets focus.
- Press Control-Option-Right Arrow, VO announces should announce “Below the fold content”.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @abbeyhrt!

**Review by dakahn — CHANGES_REQUESTED** [review]
I'm seeing two bugs in testing: 

- [x] On Chrome. It successfully reads the above the fold content, but when I expand the dropdown it doesn't read the below the fold content. If you tab away and back the below the fold content is read. 

- [x] On Safari the above the fold content isn't read. It looks like that's happening because focus is going straight to the expand button rather than the surrounding container which includes the above the fold text. No text content is read whatsoever.

**Comment by abbeyhrt** [comment]
@dakahn I was able to get it working! This should be good to go 🤞

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]
Great work. Thanks so much for this.

**Comment by abbeyhrt** [comment]
Here is a video of the current voiceOver process that was created with this PR: 
[Screen Recording 2019-09-25 at 3.19.09 PM.zip](https://github.com/carbon-design-system/carbon/files/3659154/Screen.Recording.2019-09-25.at.3.19.09.PM.zip). We plan on refactoring the Expandable Tile so that a VoiceOver user can expand the tile when the tile is focused, like non-voiceOver users can currently do, and still have the content read and the expanded state announced. This and other additions/refactoring to Tiles are outlined here: (issue to come)

**Pull request merged**
