### PR TITLE
feat(elements): update colors, layout, and motion packages with experimental Sass Modules

### PR DESCRIPTION
**Pull request by joshblack**
This is part of our exploration into Sass Modules, both to help with authoring Sass files but also to assist in compilation times.

This PR introduces the following changes:

- Move the `colors/scss/module.scss` file to `colors/index.scss`. This allows us to reference the styles at `@carbon/colors` which is the current preference for Sass Modules going forward
- Update `@carbon/layout` to include an entrypoint and temporary `modules` folder
- Update `@carbon/motion` to include an entrypoint
- Add initial v11 docs for `@carbon/layout` and `@carbon/motion`

#### Changelog

**New**

- New Sass Module entrypoints for Colors, Layout, and Motion

**Changed**

- Moved colors module entrypoint from `scss/module.scss` to `index.scss`

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
Let me know if you have any questions @aledavila @tw15egan !

Noticed the build failing, will try and update the bundler check since it doesn't understand Sass Modules at the moment 👀

**Comment by joshblack** [comment]
Should be good after #7555 which uses `sass` under the hood now 👀

**Comment by joshblack** [comment]
Let me know if you have any questions @dakahn @aledavila !

**Review by aledavila — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
Not seeing any issues with a clean build, LGTM 👍 ✅

**Review by dakahn — APPROVED** [review]

**Pull request merged**
