### PR TITLE
fix(Tooltip): bring focus/blur handlers back

### LINKED ISSUE #3601: Vanilla JS Tooltip and React Tooltip components have inconsistent behavior
## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When experimenting with the tooltip component here - https://www.carbondesignsystem.com/components/tooltip/code if you tab through the tooltip components they each display the popup when they receive focus.

Looking at the react component here - http://react.carbondesignsystem.com/?path=/story/tooltip--default-bottom, it doesn't behave in the same way.

Also, looking at the code for the React tooltip there is a lot of code that looks as though it's meant to be handling hover events but those event handlers aren't hooked up to anything, certainly no popup appears on hover in the storybook example.

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I'd expect consistency between the two implementations.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by asudoh**
This change brings back focus/blur handling code that was inadvertently removed. This change also renames `_debouncedHandleHover` private method to better represent what the latest code does.

Fixes #3601.

#### Changelog

**Changed**

- Brought `focus`/`blur` event handling code back.

#### Testing / Reviewing

Testing should make sure React interactive tooltip is not broken.

### CODE REVIEW

**Comment by elizabethsjudd** [comment]
@asudoh doesn't this PR go in the opposite direction (we are removing focus/blur) of the changes (PR #3476) I'm making in Carbon Vanilla to support screen reader users?

**Comment by emyarod** [comment]
is there any more information about the behavior change from opening tooltips on focus to opening on click? it doesn't seem to be captured by #2284 which #3476 references

**Comment by elizabethsjudd** [comment]
@emyarod

Break down of the types of tooltips and their implementation:
* icon tooltip - we have content in the button and we just show and hide it based on hover or focus. There isn't really anything fancy with this one.  Screen reader users have access to the content because it's standard HTML markup with the content within the button.
* definition tooltip - because it's scoped to contain only a static string, we can use the `role="tooltip"`. Combining that with `aria-describedby` on the trigger informs screen reader to announce the text within the tooltip when focused on the trigger. This is why we can have them display on hover/focus. These tooltips are very limited in what they can contain and the fact that the user can't skip them isn't typically a huge impact to their task/workflow.
* interactive tooltips - because these contain interactive elements and/or rich text, we can't solely rely the `aria-describedby` attribute and we have to treat the tooltip as an `dialog`.  Dialogs have different behaviors and we have to be able to focus on the tooltip itself or an interactive element within it. The general practice with this is then to have it show up on click (`focus + space/enter`) so that it's clear to users the tooltip is persistent and can be interacted with.  However, WH does currently support hover/focus for tooltips but it's not our default or even a recommended practice because the experience is more confusing and/or frustrating for screen reader users because as they focus on the trigger they are automatically moved to new content without being able to explicitly say "yes i want to interact with the dialog" This could also throw off the flow of the page for them as they are forced to always be interrupted with content that is related but not necessarily part of the content they are currently navigating through.

Hope this helps. Let me know if you have any other questions.

**Comment by asudoh** [comment]
While @elizabethsjudd has been doing her splendid work on tooltip keyboard nav, I don't want the discussion brought into this PR here. This PR is solely for fixing a regression.

**Review by emyarod — APPROVED** [review]
yeah since this is a regression fix, further changes can be discussed in separate tickets, this looks good to me

**Review by aledavila — APPROVED** [review]
lgtm

**Pull request merged**
