### PR TITLE
fix: a11y modal heading issue

### LINKED ISSUE #17397: [a11y]: Composed Modal, Dialog heading is provided in h3 instead of h2
### Package

@carbon/react

### Browser

Firefox

### Operating System

Windows

### Package version

1.61.0

### React version

_No response_

### Automated testing tool and ruleset

manual

### Assistive technology

JAWS

### Description

Maintain hierarchical order for the Heading levels :
Recommended to present the Modal Main heading in H2.

### WCAG 2.1 Violation

1.3.1 Info & Relationships

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-composedmodal--default

### Steps to reproduce

storybook : https://react.carbondesignsystem.com/?path=/story/components-composedmodal--default

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by riddhybansal**
Closes #17397 

Maintain hierarchical order for the Heading levels :
Recommended to present the Modal Main heading in H2.

#### Changelog

**Changed**

- Modal and composed modal heading to h2

#### Testing / Reviewing

Modal and composed modal heading should be in h2

### CODE REVIEW

**Comment by kennylam** [comment]
I'm wondering if this is actually required since the current component structure looks correct. There is no content following the first `h2`, which would make having another `h2` immediately following it confusing to screen reader users. Maybe we could run this by Ragu to confirm?

**Comment by riddhybansal** [comment]
> I'm wondering if this is actually required since the current component structure looks correct. There is no content following the first `h2`, which would make having another `h2` immediately following it confusing to screen reader users. Maybe we could run this by Ragu to confirm?

I had the same concerns. Raghu told the product team to have this heirarchy in modal. Check here https://github.com/carbon-design-system/ibm-products/issues/6019 . So raised the PR , not sure its required or not.

**Comment by kennylam** [comment]
Ah ok. I'll reach out to Ragu to discuss during the next QA meeeting.

**Comment by alisonjoseph** [comment]
@riddhybansal whats the status on this one?

**Comment by riddhybansal** [comment]
> @riddhybansal whats the status on this one?

Heya @alisonjoseph I think @kennylam had a word with Raghu and this fix is required , so I think you can review it !! @kennylam can you confirm this ?

**Review by kennylam — APPROVED** [review]
Whoops, sorry for forgetting to update. Yes, spoke to Ragu about this and he said that either way is not really an issue.

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
