### PR TITLE
refactor(PasswordInput): use stateless pw input

### PR DESCRIPTION
**Pull request by emyarod**
This PR refactors `<TextInput.PasswordInput>` to consume the stateless `<TextInput.ControlledPasswordInput>`

refs https://github.com/carbon-design-system/carbon/issues/2489 https://github.com/carbon-design-system/carbon-components/pull/2427

#### Changelog

**Changed**

-  `<TextInput.PasswordInput>` now uses stateless `<TextInput.ControlledPasswordInput>`

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by joshblack — CHANGES_REQUESTED** [review]
Is there a better name than `PresentationalPasswordInput`? It's just so long, did we decide on this convention already in other parts of the codebase?

**Comment by emyarod** [comment]
@joshblack this was hand in hand with #2427 and the name change was determined last night. I will need to update this to follow the latest conventions set in that PR

**Comment by joshblack** [comment]
Sounds good @emyarod 👍 Just commented in the other thread.

**Comment by jnm2377** [comment]
Not sure if I missed something, but when I click the show password icon in the `Fully controlled toggle password visibility` story, it doesn't actually show the password. It always stays hidden.

**Comment by emyarod** [comment]
progress on this PR is stalled until we figure out how we want to proceed with ~~https://github.com/carbon-design-system/carbon/pull/2730~~ https://github.com/carbon-design-system/carbon/pull/3028

**Comment by joshblack** [comment]
bump @emyarod, is this going to be part of v10.4 now that the controlled stuff has been settled?

**Comment by emyarod** [comment]
that's still the goal but it may end up in 10.5 with #3018

**Comment by joshblack** [comment]
Closing as stale 👍

**Pull request closed without merging**
