### PR TITLE
feat(StructuredList): add prop for condensed list

### LINKED ISSUE #5736: feat(structured-list): Add React component support for the condensed structured list styles
### Summary

The `carbon-components` repo has styles for a condensed structured list using the class `{prefix}--structured-list--condensed`. The React component `StructuredListWrapper` should have a prop that toggles this class, similar to how there are props to change the sizing of `Button` and `DataTable`.

The styles can currently be added by manually including the class under the className prop.

### Justification

Since `carbon-components` have the styles, it should be supported in `carbon-components-react`.

### Desired UX and success metrics

A user can set a prop to toggle the class on the StructuredListWrapper.

### "Must have" functionality

An easy way to add the condensed class to the React component.

### Specific timeline issues / requests

As there is a workaround to add this feature, there is no specific timeline.

### Available extra resources

I've added this feature in my forked carbon repo already. I will be able to submit a PR to add this feature.

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #5736

**New**

- adds boolean for condensed list support (styles were already supported in vanilla)

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by aagonzales** [comment]
@jnm2377 Is there a design spec somewhere that you're referencing? Is the removal of the padding-left intentional?

**Comment by jnm2377** [comment]
@aagonzales I didn't do anything with the styles, these already exist. I simply added a prop to be able to toggle the styles in the react component. As far as the padding, it seems like that was removed several years ago bc of this issue: https://github.com/carbon-design-system/carbon/issues/693

**Comment by aagonzales** [comment]
"already supported in vanilla" I think it's that vanilla was never updated. This condensed style matches the old v9 styling of structure list. What you see in the "simple" story is the intended design. I don't think there was ever supposed to be a condensed version with the v10 update. I'll take this to the greater design team and ask them.

**Comment by jnm2377** [comment]
I guess on the dev side we assumed this issue was ok to work on bc no designers ever declined the enhancement in the original issue when Akira asked for input (this was about a year ago). Lmk what design decides.
Screen Shot 2021-04-19 at 12 48 00 PM

**Comment by aagonzales** [comment]
(in very joking a tone) we were a little distracted in March 2020 so I think this one just fell through the cracks. 

We talked about it in our design sync today, we think a condensed version is ok to have but this style is is flush as well as condensed and those would be two separate props. I'm going to mock-up a quick spec to demonstrate what I mean.

**Review by dakahn — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by aagonzales** [comment]
Ok so adding a condensed list is one issue and there's a second one about adding a prop for flush content instead of hanging content. 

I know this PR is just about enabling the prop but I think its an old one and was never properly updated with v10 styling. I have talked to the design team and we're ok with having these 4 variants. Or to start simply adding in the indented padding to the left of the first column on the condensed list to match the padding of the default list.

image

**Review by kingtraceyj — CHANGES_REQUESTED** [review]
For condensed, padding between columns should be 16px.

Current (8px):
image

Proposed (16px):
image

**Comment by jnm2377** [comment]
@kingtraceyj @aagonzales updated to include both options via props. There's a playground story where you can toggle the diff styles to test, and also added knobs to the selection story to view on there.

**Review by kingtraceyj — CHANGES_REQUESTED** [review]
**Condensed, Flush should have 16px between columns**
Current:
image

Proposed:
image

**Hang alignment, default spacing should have 16px spacing**
current is 32px (there's 16px before and after):
image

Proposed:
image

**Review by kingtraceyj — APPROVED** [review]
good to go 💥  thanks josefina! looks great.

**Pull request merged**
