### PR TITLE
Icon updates

### PR DESCRIPTION
**Pull request by tw15egan**
## Overview

Updates Icons to new Duo Icons

### Added
- New Icons

### Removed
- Large Search w/ Icons
- Old Icons

### Changed
- Fixed a bug where Danger/Tertiary buttons w/ Icon did not display properly
- Fixed a bug where Overflow Menu Danger Button used black text instead of white

## Testing / Reviewing

Check components that have icons and ensure they look correct

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
Looks awesome TJ! As far as I can see you got them all. 🎉 

Wondering if should we update the checkbox checkmark also? It's not currently using an icon, but we could make it thinner to match the new icon look.

**Review by asudoh — COMMENTED** [review]
LGTM 👍 once our designers sign this off - Thanks alot @tw15egan for getting this done!

**Comment by tw15egan** [comment]
@alisonjoseph I was unsure what to do there as well. I do like using only css to display the checkmark, I wonder if we could tweak that at all to achieve a thinner icon

**Comment by alisonjoseph** [comment]
@tw15egan We definitely can, might be able to re-use the work @joshblack did on the checkboxes in the duo repo to display them thinner.

**Review by marijohannessen — APPROVED** [review]
Looks great! 👍 ✅ 🎉

**Comment by tw15egan** [comment]
Going to merge this in for now, as we will do a major visual review with the designers at a later date (5/30). This will also allow us to use the new icons and see if there any issues in our local development cycles

**Pull request merged**
