### PR TITLE
fix(focus-states): fixed some focus state issues

### PR DESCRIPTION
**Pull request by marijohannessen**
## Overview

- Added focus state to Card link
- Added background color to focused element in Content Switcher
- Added underline to focused item in Dropdown

Fixes:
https://github.ibm.com/Bluemix/design-system-website/issues/1057
https://github.ibm.com/Bluemix/design-system-website/issues/1054
https://github.ibm.com/Bluemix/design-system-website/issues/1051

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
@marijohannessen Seems that there is no change in JS code? Vanilla version does not use Prettier ATM.

**Review by hellobrian — APPROVED** [review]
👍 ✅

**Comment by marijohannessen** [comment]
@asudoh Yes, that change happened because of Prettier. Do you want me to revert it?

**Comment by asudoh** [comment]
@marijohannessen Yes - I know it’d be an extra effort, but it’s always a good practice to keep commits/PRs dedicated to the original purpose, for better tracking of changes. It means that we can create another commit/PR if we want formatting change. Thanks alot! 🙂

**Comment by hellobrian** [comment]
> @marijohannessen Yes - I know it’d be an extra effort, but it’s always a good practice to keep commits/PRs dedicated to the original purpose, for better tracking of changes. It means that we can create another commit/PR if we want formatting change. Thanks alot! 

I thought we were using the same Prettier settings to avoid this but I guess I'm wrong. 
@asudoh is absolutely right and I agree but I think for now it's fine if @marijohannessen makes comments on her code of the actual changes to relevant to the PR.

**Comment by marijohannessen** [comment]
I reverted it back to how it was, thanks!

**Review by asudoh — APPROVED** [review]
Thanks @marijohannessen for making the change! LGTM 👍

**Pull request merged**
