### PR TITLE
feat(file-uploader): support drag and drop

### LINKED ISSUE #2288: [FileUploader] Drag and drop support in file uploader
### Summary

This issue tracks dev effort for implementing drag and drop-based file uploader and possibly beefing up design spec (some if there) from carbon-design-system/carbon-contribution#4.

### Justification

Drag and drop-based file uploader UI has been popular these days, often provides a better user experience than letting user choose file.

### PR DESCRIPTION
**Pull request by asudoh**
Closes: https://github.com/carbon-design-system/carbon/issues/2288

_Not_ for this milestone (`v10.3`), but creating a draft pull request to get designer's input. Notably:

* Does the color/thickness of the dotted line and hover-over line of drop area look good? Or should we choose some different tokens?
* The "list of files" UI in the spec has border, whereas the current `v10` doesn't. Was it a remaining `v10` item?
* Chose "add" cursor that seems to meet what it does, but I have an impression that the spec may intend custom cursor. If so, where can I grab the custom cursor from?

The latest demo can be seen at: https://deploy-preview-2848--the-carbon-components.netlify.com/component/file-uploader--default.html

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by shixiedesign** [comment]
Hi @asudoh! Thanks for starting on this issue. 
- [ ] Here's the drop zone's spec: dotted box border should be 1px, `$ui-04`, 8px dashes, 4px gaps. The border needs to be 3:1 accessible I believe. 
image

- [ ] Blue drop zone outline looks correct :tada:! 2px, blue. Just need to make sure the color is `interactive-03`, so the highlight outline is actually `#ffffff` on dark theme

- [ ] The cursor doesn't have to be custom. However, the `add cursor` should only appear inside the drop zone. This is currently reversed and should be fixed. The green `add` sign is a visual indicator to users that they can now "drop", so green `add` outside drop zone would be wrong. Cursor should be default outside the drop zone. 
May-29-2019 22-01-11

- [ ] Lastly, I think the drop zone needs to be taller to provide sufficiently big target area. I don't have the specific sketchfile too 🤦‍♀ so I'm gonna suggest 256px wide and 96px tall, with an internal padding of 16px all around: 
image

**Comment by asudoh** [comment]
@shixiedesign Thank you for the design review! - Updated the demo link with most of suggested design change, except the width of the drop container given the original one is wider than 256px. Please let me know if shortening to 256px is more desirable.

I'll get in sync with @emyarod on React implementation. Until then, let me keep this PR draft.

**Comment by shixiedesign** [comment]
Hi @asudoh I spec'ed out the file loader more completely after finding the sketchfile, so a few more small visual fixes: 

- Default width of the drop zone, let's not make it smaller, but make it 320px so it's a nice number divisible by 8.

- file list's `x` icon should use color `$icon-02`
image

- this loader should be 16x16 in overall size, with a ring thickness of 3px
Current
image
Should be
image

- do we have an error state for the file list? 
We should use `$support-01` for main error message, detailed error message is `$text-01`, type size 12px, `ui-03` for divider line. 
image

**Review by shixiedesign — COMMENTED** [review]
Hi @asudoh I spec'ed out the file loader more completely after finding the sketchfile, so a few more small visual fixes: 

- Default width of the drop zone, let's not make it smaller, but make it 320px so it's a nice number divisible by 8.

- file list's `x` icon should use color `$icon-02`
image

- this loader should be 16x16 in overall size, with a ring thickness of 3px
Current
image
Should be
image

- cursor should turn into "pointing hand" when hovering over the link for upload: 
May-31-2019 11-56-11

- bug: when dragging+hovering, the blue outline shouldn't cause the text inside to move.
May-31-2019 11-58-43

- do we have an error state for the file list? (see below spec img) We should use `$support-01` for main error message, detailed error message is `$text-01`, type size 12px, `ui-03` for divider line. 

Below is the complete spec for your reference:

image

**Comment by asudoh** [comment]
@shixiedesign Thank you for the more detailed spec - Updated https://deploy-preview-2848--the-carbon-components.netlify.com/component/file-uploader--default.html upon the update.

One question wrt the invalid state is that whether we need an invalid icon there. I'm wondering this because @emyarod originally had it, which can be seen at https://the-carbon-components.netlify.com/component/file-uploader--example-upload-states.html. I have https://deploy-preview-2848--the-carbon-components.netlify.com/component/file-uploader--example-upload-states.html for now.

**Comment by shixiedesign** [comment]
@asudoh investigating this right now along with issue https://github.com/carbon-design-system/carbon/issues/2901#issuecomment-497901445

**Comment by shixiedesign** [comment]
We've reached a consensus! Let's stick to below styling for both **drag & drop** and the **default** file uploader. A new issue can be opened for fixing default file uploader's error state to : 
image
Please note @asudoh the color of the divider line in this implementation is wrong, please use `$ui-03` instead.

**Comment by asudoh** [comment]
Cool thanks @shixiedesign for specing this and entering the issue!

**Review by shixiedesign — COMMENTED** [review]
Hi @asudoh in case I did missed giving proper review to this one, this looks pretty close and just need a few more corrects before merging:

- [ ] Please put file list **under** the drop zone to keep drop zone position constant. I realize this is my mistake in the previous specs. Sorry! We are moving file list under to be consistent with default file uploader. 
image

- [ ] File name truncation. Can we truncate the name and keep the extension? eg. instead of truncating `newyorkcity.jpg` to `newyorkcity...`, do `newyor....jpg` instead so file format is visible. 

- [ ] error state styling needs 2 small fixes, borders thickness and color: 
image

- [ ] Please update the loading spinner & success checkmark according to https://github.com/carbon-design-system/carbon/issues/3040. The changes are: updating the checkmark for success to blue 60, and reducing the size of the spinning loader to 14x14, but keep it's container 16x16. This matches the size of the spinner to the success icon.

**Comment by asudoh** [comment]
Thanks @shixiedesign for the additional comment! Will look at this with @emyarod, as he seem to be looking at another UX feedback from @laurenmrice, and he also is working on the React version.

**Comment by asudoh** [comment]
Addressed review comments except ellipsis one. As I mull over it 🤔 several edge cases comes to my mind that may be time-consuming for addressing. Nice if we can go without it for now.

@emyarod Could you merge the series of changes in this PR into your React PR? Thanks!

**Comment by emyarod** [comment]
just to clarify @asudoh, this is ready to be combined with #3016 and the PRs for #2916/#2917?

**Review by shixiedesign — APPROVED** [review]
That sounds good @asudoh ! I will make an issue for the truncation behavior so we don't forget.

**Comment by shixiedesign** [comment]
Hang on I noticed 1 thing. The checkmark should be thin like below:
image

But in https://deploy-preview-2848--the-carbon-components.netlify.com/component/file-uploader--default.html I'm seeing below: 
image

**Review by shixiedesign — COMMENTED** [review]
Hang on I noticed 1 thing. The checkmark should be thin like below:
image

But in https://deploy-preview-2848--the-carbon-components.netlify.com/component/file-uploader--default.html I'm seeing below: 
image

**Comment by asudoh** [comment]
Thank you for catch this @shixiedesign! Fixed.

**Comment by shixiedesign** [comment]
Perfect! Thank you Akira! 🙌

**Comment by asudoh** [comment]
Thanks @shixiedesign for reviewing!

> just to clarify @asudoh, this is ready to be combined with #3016 and the PRs for #2916/#2917?

@emyarod Now yes 😉.

**Comment by emyarod** [comment]
ok great I will combine the changes into those PRs, thanks @asudoh @shixiedesign !

**Comment by jnm2377** [comment]
Question, is this in need of dev review or is this getting closed if it's being added in another PR? based on this comment: https://github.com/carbon-design-system/carbon/pull/2848#issuecomment-503169419

**Comment by asudoh** [comment]
@jnm2377 Thank you for asking, this is just for referral. @emyarod is merging this work to his React file uploader work and once it happens this PR can be closed.

**Comment by asudoh** [comment]
Superseded by: #3175

**Pull request closed without merging**
