### PR TITLE
fix(loading): remove progress bar on inactive state

### LINKED ISSUE #9163: InlineLoading inactive state animation is broken
## Brief description
`InlineLoading` component inactive state animation is broken:

image

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

Looks like inactive state in `InlineLoading` component has some weird animation of circle spinning backwards (?).
Versions used:
carbon-components@10.29.0
carbon-components-react@7.29.0

Tested both in Firefox (89.0.2 (64-bit)) and Chrome (Version 91.0.4472.124 (Official Build) (64-bit))

## Steps to reproduce the issue

Have `InlineComponent` with `status='inactive'`.
You could reproduce it in react-components storybook e.g [InlineComponent](https://react.carbondesignsystem.com/?path=/story/components-inlineloading--inline-loading&knob-Description%20(description)=Active%20loading%20indicator)

## Notes:

Looks like it was introduced with` carbon-components-react 7.6.0`

### PR DESCRIPTION
**Pull request by emyarod**
Closes #9163

This PR updates the loading and inline loading inactive states to resolve a regression in appearance.

#### Changelog

**New**

- progress percentage function to calculate loading/inline loading appearance

**Changed**

- consolidate loading and inline loading styles further

#### Testing / Reviewing

Confirm the loading and inline loading spinners appear correct (small and default sizes, active and inactive states)

### CODE REVIEW

**Review by aagonzales — APPROVED** [review]
LGTM

**Review by tw15egan — APPROVED** [review]
Looks great!

**Comment by tw15egan** [comment]
@emyarod was just thinking, could you also port these styles to the `@carbon/styles` package? Looks like we've already got that component in and want to make sure we get it fixed there as well

**Comment by emyarod** [comment]
@tw15egan added them to `@carbon/styles` as well

**Comment by tw15egan** [comment]
Looks great, thanks for adding that 🎉

**Comment by emyarod** [comment]
bump @jnm2377 @tw15egan when you have a chance

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
