### PR TITLE
feat(DataTable): support radio button row actions

### LINKED ISSUE #2455: Radio button selection in the Carbon data table should support table actions
[Originally reported by Tom Ginader in IBM Slack](https://ibm-cloudplatform.slack.com/archives/C2K6RFJ1G/p1556634610314900):

>Hello. How would I use radio buttons in DataTable to have actions? I was able to get regular selection with batch actions working properly, but we realized that we only want our users to select one item at a time. I'm not seeing any examples that combines radio button selection with some kind of action.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2455 

#### Changelog

**New**

- support batch table actions for radio button row selection in data table
- storybook example

### CODE REVIEW

**Comment by emyarod** [comment]
WIP incorporating feedback from @asudoh https://github.com/carbon-design-system/carbon-components-react/pull/2347#discussion_r282325816

**Comment by emyarod** [comment]
@asudoh have the comments in the previous PR thread been addressed now?

**Comment by asudoh** [comment]
Thanks @emyarod for the update! The only one remaining is mutation of object in a React state (in `reduce()`)

**Comment by emyarod** [comment]
@asudoh I moved the object out of the `setState` call

**Comment by jnm2377** [comment]
Looks good! My only question is when you click "use radio button", the column header still has a checkbox, should that be there? Seems wrong but not sure what the design looks like for this.

**Comment by emyarod** [comment]
initially radio button selection did not have a table header...some changes got dropped in the story merging, added them back. afaik there is no design spec for radio button selection

**Comment by jnm2377** [comment]
I think it's just a matter of asking design what it should look like. We shouldn't be shipping new features without design's approval anyway. I know this was added a while back, but it was a new feature that wasn't implemented in vanilla components, so I don't think design reviewed it, but they should have. cc: @carbon-design-system/design

**Comment by emyarod** [comment]
fwiw https://github.com/carbon-design-system/carbon-components-react/issues/1796#issuecomment-459781401

**Comment by shixiedesign** [comment]
After speaking to @chrisconnors-ibm , looks like we might have made a hasty decision. Let's reconsider this feature and see if this is really something we want to support. Sorry about the confusion. We will temporarily put this on hold.

**Comment by asudoh** [comment]
@emyarod Uh I was referring to `val.isSelected = false` line which seems to mutate React state. Anyhow probably we can monitor how single selection topic goes.

**Comment by joshblack** [comment]
Should we put a hold on this based on: https://github.com/carbon-design-system/carbon/pull/2657#issuecomment-491436880 ?

**Comment by joshblack** [comment]
Closing this for now, feel free to re-open!

**Comment by chrisconnors-ibm** [comment]
We can revisit this if there are clear, generalizable requirements broadly expressed across several teams for this enhancement.

**Pull request closed without merging**
