### PR TITLE
fix(toggle): update colors

### LINKED ISSUE #3614: Off state of toggle (and small toggle) lacks 3:1 contrast with adjacent color (background)
## Off state of toggle lacks 3:1 contrast with adjacent color ( either internal circle or background)

-->

## Environment
v10, react, theme
> Operating system
Windows 7

> Browser
Firefox and Chrome

## Detailed description
There are different implementations of the toggle, but all fail contrast for the 'off' state. 

> What did you expect to happen?
The off state should meet the minimum contrast. 

> What WCAG 2.1 checkpoint does the issue violate?
[Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information
image
Storybook Toggle on (sufficient)
image
Storybook Toggle off (insuficient 2.5:1 between oval and lighter gray of circle)
image
Theme on and off toggle (same failure ratio as first screen shot)
image
V10 showing on and insufficient off toggle ( contrast for 1.8:1)
image
v10 Toggle small, with similar challenges for the 'off' toggle

### Notes
In a situation where ALL the toggle versions contained a visible text state (On/Off) the non-text contrast could likely be excused since the visual cue would be redundant to the text and thus not _required_ ("Visual information required to identify user interface components and states...)
That is, with a text state of "off" visible, the user no longer needs to discern the state of the toggle. However, this is a fairly easy issue to resolve -- just ensure the toggle border is 3:1 against the white background (for the v10 version) and that the circle is a lighter gray (or white) so that it is visible.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3614.

#### Changelog

**Changed**

Updated following according to the new spec:

- Circle colors in off state.
- Focus outline styles.

#### Testing / Reviewing

Testing should make sure toggle is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, token changes and focus styles appear to match the new spec now

image

image

**Review by vpicone — APPROVED** [review]
Could you add a comment these box-shadows or pull off into a variable or something? Hard to tell what's happening just by looking at it.

```css
box-shadow: 0 0 0 1px transparent, 0 0 0 1px transparent,
        0 0 0 3px transparent;
```

**Comment by asudoh** [comment]
@vpicone Updated.

**Review by shixiedesign — APPROVED** [review]
Looks great! Exactly as spec'ed. Thank you!

**Pull request merged**
