### PR TITLE
fix(ListBox): update listbox components to match spec

### PR DESCRIPTION
**Pull request by emyarod**
Ref #7325

This PR updates the Dropdown, Combobox, and MultiSelect components to match the component spec based on the recent component audit notes. The SVG changes will be related to the current ongoing issue with inner fills in icon SVGs (related https://github.com/carbon-design-system/carbon/issues/3216)

#### Changelog

**New**

- add inline dropdown to storybook example

**Changed**

- update menu option hover colors in light variant
- multiselect selection count tag matches Tag component spec

**Removed**

- input hover color on combobox

#### Testing / Reviewing

Confirm the 3 listbox components matches the expected appearance and behavior. Ensure that the new multiselect selection tags are accessible

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
### Dropdown
- [x] The inline variant needs to have 24px space between the label and the input
inline dropdown spec



----

### Combobox
- [x] When the light prop is on, there is a hover color change when you hover on the top field. There should not be a hover color change. 
giph hover combo
 
- [x] The close icon should be `icon-01`
- [ ] There needs to be a warning state added in for combobox

----
### Multi-select

**Filterable:**
- [x] Needs to have 16px space before the text in the input field.
multi-select filterable spec

- [x] There is a bug when a tag appears in the input field. The tag gets cut off. 
Jan-13-2021 17-32-11

- [x] There is a hover color change when you hover on the top field. There should not be a hover color change. 

- [x] The tag hover is not the right size. Here are the specs for the tag. (This is also wrong for the regular multi-select)
multi-select tag spec

**Comment by emyarod** [comment]
@laurenmrice for the last point about tag styles, these are lifted directly from the Filter Tag, so do those need to be adjusted as well?

**Comment by laurenmrice** [comment]
@emyarod yes!

**Comment by emyarod** [comment]
multiselect tags should now be inheriting the changes from #7664 and I will add the combobox warning state separately as it is not currently in the library (https://github.com/carbon-design-system/carbon/issues/7685)

**Review by laurenmrice — APPROVED** [review]
Looks good to me! 🙌🏻

**Pull request merged**
