### PR TITLE
fix(overflow): fix styling color for danger overflow to use danger to…

### LINKED ISSUE #7467: Overflow menu danger class gets support token
In the overflow menu the danger class gets the support-01 token. When doing theming the danger and support-01 can potentially be different colors. It makes more sense to me for overflow menu danger class to get danger token instead of support-01.

On my team the colors in custom themes can sometimes be different between the tokens and from our perspective the danger menu options should inherit the danger token color.

Screen Shot 2020-12-16 at 9 17 30 AM

### PR DESCRIPTION
**Pull request by DusanMilko**
…ken. Harness the power of currentColor

fixes: https://github.com/carbon-design-system/carbon/issues/7467

- fix overflow danger class to use danger token. (this effects theming, its referenced as danger so lets use the correct token)
- Also harness the all powerful currentColor to get fill color - this is a more dynamic and cross browser supported way that simplifies logic

### CODE REVIEW

**Comment by tw15egan** [comment]
`danger` was deprecated in a recent release (https://github.com/carbon-design-system/carbon/pull/7179) and the website specifies as `support-01`.  

Screen Shot 2020-12-16 at 10 02 12 AM


Is there an issue associated with these changes?

**Comment by DusanMilko** [comment]
@tw15egan added issue: https://github.com/carbon-design-system/carbon/issues/7467
Noticed when doing theming the danger and support-01 can have different colors. And the danger class in overflow menu should inherit danger color instead of support-01, no?

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by laurenmrice — COMMENTED** [review]
Looks good! Thank you 🙌🏻

**Review by laurenmrice — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
@DusanMilko looks good!

**Pull request merged**
