### PR TITLE
fix(DatePicker): fix programmatic set of date in range mode

### LINKED ISSUE #4803: React Carbon - Controlled DatePicker type='range', first input shows both values
## What package(s) are you using?

- [x] `carbon-components-react`

## Summary
I'm working on setting up a date range for a table filter. I seem to get the input data okay, but when I update the form state to have the array of the two dates, and that passes back to the DatePicker component, the first DatePickerInput shows both values.

Screen Recording 2019-12-02 at 11 04 13 AM 2019-12-02 11_05_15

## Relevant information

Our component for integrating formik with the date picker

```javascript
export const FormikDatePicker = connectFormik(
  ({
    formik,
    labelText,
    tooltipKey,
    field,
    datePickerType,
    rangeLabels,
    ...otherInputProps
  }) => {
    const isRange = datePickerType === 'range'
    const handleChange = (selectedDates, dateStr) => {
      const { setFieldTouched, setFieldValue } = formik
      setFieldTouched(field.name, true)

      if (isRange) {
        setFieldValue(field.name, selectedDates)
      } else {
        const date = moment(`${dateStr}T00:00:00`)
        setFieldValue(field.name, date.toISOString())
      }
    }

    let label = ''
    if (isRange) {
      label = rangeLabels[0]
    }

    return (
      <>
        {datePickerType === 'single' ? (
          <FieldLabel
            labelText={labelText}
            name={field.name}
            tooltipKey={tooltipKey}
          />
        ) : null}
        <DatePicker
          onChange={(selectedDates, dateStr) => {
            handleChange(selectedDates, dateStr)
          }}
          value={field.value}
          id={`datePicker-${field.name}`}
          datePickerType={datePickerType}
          dateFormat='Y-m-d'
        >
          <DatePickerInput
            id={field.name}
            placeholder='yyyy-mm-dd'
            pattern={DATE_PATTERN}
            labelText={label}
            {...otherInputProps}
          />
          {isRange ? (
            <DatePickerInput
              id={`${field.name}-end`}
              placeholder='yyyy-mm-dd'
              pattern={DATE_PATTERN}
              labelText={rangeLabels[1]}
              {...otherInputProps}
            />
          ) : null}
        </DatePicker>
      </>
    )
  }
)
```

### PR DESCRIPTION
**Pull request by asudoh**
This change adds a logic to re-format dates in `<input>` when Flatpickr's `setDate()` API is called. Flatpickr's range plugin has a similar logic to do that, but runs only if the second argument is `true`.

Fixes #4803.

#### Changelog

**New**

- A new logic in our custom Flatpickr plugin to ensure `setDate()` API call won't end up with `<input>` populated with wrong date format.

#### Testing / Reviewing

Testing should make sure our date picker is not broken.

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]

**Comment by joshblack** [comment]
@asudoh could you share more about this particular fix and why we needed to go down this route? Curious what your thoughts are on when we need to dive into the custom plugin versus what we can do in the component, and vice-versa (just due to my own lack of knowledge!) 🙏

**Comment by joshblack** [comment]
Would @aledavila or @dakahn want to go through this with @asudoh at some point too? 👀

**Comment by aledavila** [comment]
@joshblack yea I can join to go through it too

**Comment by asudoh** [comment]
I choose the plugin approach when the default behavior of Flatpickr does not align with what our design team dictates, or such default behavior is seen as a bug from our perspective. Another case is that such change is seen as it should apply to all framework variants.

**Review by emyarod — APPROVED** [review]
looks good to me, tested against the original codesandbox example and the input field no longer shows both parts of the date range

**Pull request merged**
