### PR TITLE
fix(tabs): truncate container tab header text with ellipses

### LINKED ISSUE #5016: [Tab] Container tabs needs text truncation.
The container tab text needs to elipse 16px from the edge like the default tabs do. 

Container tabs:
image

**Default tabs:**
image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5016

This PR adds ellipses for overflow text in container tab headers and mobile tabs. Instead of making the anchor a flex item we keep the inherited inline-block display value and set the line height based on the anchor height and vertical padding to center the text. An alternative approach would be to wrap the text in the anchor in another element

#### Changelog

**New**
- text truncation styles for mobile tabs

**Changed**

- remove flex display property to allow text truncation styles
- compute line height for container tabs based on tab height and vertical padding

#### Testing / Reviewing

Ensure that the tab variants appear correct, especially with longer tab labels

### CODE REVIEW

**Review by aagonzales — APPROVED** [review]
🎉  perfect!

**Comment by tw15egan** [comment]
Oooo, nice thinking! Looks great on desktop, but when I'm testing in mobile I'm seeing some minor issues with the chevron sizing

Screen Shot 2020-01-14 at 9 57 28 AM

Screen Shot 2020-01-14 at 9 57 34 AM

**Comment by emyarod** [comment]
looks like it's caused by the positioning of the chevron inside the padding

image

I resolved it by applying the same icon positioning logic as the listbox components

image

**Review by tw15egan — APPROVED** [review]
Looks great! 👍

**Review by abbeyhrt — APPROVED** [review]
Looks good to me!

**Review by asudoh — APPROVED** [review]
Thanks @emyarod for jumping in!

**Pull request merged**
