### PR TITLE
docs(data-table-v2): add ARCHITECTURE.md file for class names

### PR DESCRIPTION
**Pull request by joshblack**
Add initial docs for data-table-v2 for selector reference and hierarchy

#### Changelog

**New**

- Add `ARCHITECTURE.md` file for `data-table-v2`

**Changed**

**Removed**

### CODE REVIEW

**Comment by emyarod** [comment]
just to double check, this document is still WIP before all of data table has been merged in right?

**Comment by joshblack** [comment]
Partially @emyarod, just trying to document what exists in v9 while we are working on it 👍

**Comment by emyarod** [comment]
ok cool @joshblack just didn't want to approve while it's still being modified!

**Review by jnm2377 — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Pull request merged**
