### PR TITLE
docs(migration): update v10.x-type

### PR DESCRIPTION
**Pull request by joshblack**
Update v10 type migration guidance

#### Changelog

**New**

**Changed**

- Update v9 to v10 type table conversion

**Removed**

### CODE REVIEW

**Review by aagonzales — APPROVED** [review]
I had originally put the * in to show what was updated. Should we leave it in?

**Review by cal-smith — COMMENTED** [review]
Just jumping in ... would it be valuable to also add a short description of what `productive`/`expressive` means, and a sample code translation?

Something like (if I understand "type classes" correctly):

> v9 type classes such as `giga`
> ```html
> <h2 class="bx--giga">Giga text</h2>
> ```
> Become
> ```html
> <h2 class="heading-size-7>Giga</h2>
> ```
> and
> ```scss
> .heading-size-7 {
>   @extend $productive-heading-07;
> }
> ```

**Review by jnm2377 — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
if the asterisk means an updated token, we can probably include a footnote to make that clearer

**Comment by joshblack** [comment]
Went ahead and removed the `*` 👍

**Comment by joshblack** [comment]
@cal-smith we could definitely link out to: https://www.carbondesignsystem.com/guidelines/typography/overview#type-tokens-and-sets if you think it'd be helpful?

A big reason we aren't offering guidance like this is that we don't want folks to assume that a specific type style corresponds with a particular element (like h1, h2, etc). This is often a source of confusion where people assume the biggest type style corresponds with the semantic markup and we're trying to avoid that.

**Comment by cal-smith** [comment]
> @cal-smith we could definitely link out to: https://www.carbondesignsystem.com/guidelines/typography/overview#type-tokens-and-sets if you think it'd be helpful?

Definitly worth linking out to that as well, for clarity.

> A big reason we aren't offering guidance like this is that we don't want folks to assume that a specific type style corresponds with a particular element (like h1, h2, etc). This is often a source of confusion where people assume the biggest type style corresponds with the semantic markup and we're trying to avoid that.

Totally understand, and I tried to capture that intent in my example ... A more comprehensive example could highlight it better.

Perhaps something to this effect:

> v9 type classes such as `giga`
> ```html
> <h5 class="heading-level-5 bx--giga">Giga text</h5>
> <h3 class="heading-level-3 bx--giga">Giga text</h3>
> ```
> Can become
> ```html
> <h5 class="heading-level-5">Giga text</h5>
> <h3 class="heading-level-3">Giga text</h3>
> ```
> with the following scss
> ```scss
> .heading-level-5 {
>   @extend $productive-heading-07;
> }
>
> .heading-level-3 {
>   @extend $productive-heading-07;
> }
> ```

All super rough, but I feel it's important to give people a look at the whole picture.

**Review by emyarod — APPROVED** [review]
looks good to me aside from the prettier error

**Comment by joshblack** [comment]
@cal-smith just updated!

**Pull request merged**
