### PR TITLE
IBM Icons

### PR DESCRIPTION
**Pull request by seejamescode**
## Overview

I was asked to create a PR to show what full IBM Icons adaption into Carbon looks like.

20 components are updated, but two require further JavaScript changes:
- [ ] Checkboxes
- [ ] Radio buttons

You can check out the implementation at: http://carbon-with-ibm-icons.mybluemix.net/

I know this PR wasn't expected so soon, but please keep it open for a bit of exploration.

### Changed

- Accordion
- Button
- Card
- Carousel
- Code Snippet
- Data Table
- Date Picker
- Dropdown
- Interior Left Nav
- Lightbox
- Modal
- Notification
- Number Input
- Pagination
- Progress Indicator
- Search
- Select
- Structured-list
- Toolbar
- Tooltip

### CODE REVIEW

**Comment by marijohannessen** [comment]
I'm going to close this as I heard that icons are still being worked on, so we can re-open this when icons are finalized and we're ready to implement them 🙂 Thanks for taking the time to explore this work though, and we're looking forward to updating this later!

**Comment by seejamescode** [comment]
They are pretty finalized now. We now have private NPM packages for icons and grid if you would like to try implementing them.

**Comment by marijohannessen** [comment]
Okay cool, we're definitely going to do that when they're 100% finalized 🙂

**Comment by seejamescode** [comment]
They are 100% finalized.

**Pull request closed without merging**
