### PR TITLE
fix(placeholder) - Fix placeholder - #5976

### PR DESCRIPTION
**Pull request by DusanMilko**
Placeholder was prefix specific 

#### Changelog

**Changed**

- Updated old placeholder to not be prefixed

**Fixes**

https://github.com/carbon-design-system/carbon/issues/5976

### CODE REVIEW

**Comment by joshblack** [comment]
Hey there @DusanMilko! 👋 We don't ship with vendor prefixes as teams have different browser requirements. The recommendation is to use autoprefixer to help handle this for product 👍

**Comment by DusanMilko** [comment]
@joshblack Updated pr to remove webkit specific placeholders

**Review by joshblack — APPROVED** [review]

**Comment by asudoh** [comment]
CC @tw15egan just in case the original code was meant for WebKit-specific fix (and not needed for other browsers).

**Comment by tw15egan** [comment]
Hmm, not sure why, but this is causing differences between Firefox / Chrome, see examples:

This PR: 
Screen Shot 2020-04-29 at 8 58 33 AM

Master:
Screen Shot 2020-04-29 at 8 59 27 AM


Do you have any more info on the issue that prompted this PR?

**Comment by tw15egan** [comment]
~Playing around with this now and I couldn't get Chrome to take any placeholder styles.~

~I did some digging and found that Chrome must be setting the default placeholder styles with an `important!` tag. The only way I could get our placeholder colors to work across all browsers was to add an `important!` to the `placeholder-colors` mixin.~

Caused by my chrome extension

**Comment by DusanMilko** [comment]
@tw15egan I'm not seeing this issue in chrome, I dont see the important placeholder. Is this from an extension you are using?

In screenshot it says injected styles, these arent browser default

**Comment by tw15egan** [comment]
Confirmed that this was an issue with a local Chrome extension overriding styles. Removed offending extension and all work properly. Thanks for the fix @DusanMilko

**Review by tw15egan — APPROVED** [review]
✅ 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 as @tw15egan is good with the change - Thanks @DusanMilko (and @tw15egan for your review)!

**Review by aledavila — APPROVED** [review]

**Pull request merged**
