### PR TITLE
fix(notification): update color tokens for a11y

### LINKED ISSUE #2263: [Notification] background & dropshadow error
**Problems:**
1. Tinted notification backgrounds are not working on G10 themes
2. Missing drop shadow

### Tinted notification backgrounds are not working on G10 themes

image

Relevant discussion:

image

### Missing drop shadow
image

### LINKED ISSUE #2354: [Notification] Add high contrast style
Designers made a change to notification component styles. The colored styles were not working across the different themes so we switched them to high contrast moments.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2354
Closes #2263

This PR changes the new color tokens for toast and inline notifications.

#### Changelog

**Changed**

- notification color tokens
- consolidate notification mixins

**Removed**

- unused mixins and dead code

#### Testing / Reviewing

Ensure notifications display properly in all themes

### CODE REVIEW

**Comment by tw15egan** [comment]
Looking at the spec, shouldn't just the token _value_ be changing, but not the actual token we use? I.e. shouldn't they both use `$interactive-01`, and the dark theme has a different `01` value? 

Screen Shot 2019-04-30 at 12 15 36 PM

Screen Shot 2019-04-30 at 12 15 58 PM

Not sure we have a way of handling a different _token_ (rather than token  _value_) on a theme by theme basis.

**Comment by emyarod** [comment]
@chrisconnors-ibm @laurenmrice to add onto @tw15egan's point, right now the spec calls for different colors for the inside of the icons, but we currently can't assign different color tokens based on the theme. The inner parts of the icons are also transparent cutouts, so I think our options are to either create new icons (like https://github.com/carbon-design-system/carbon-website/issues/797, https://github.com/carbon-design-system/carbon-elements/issues/360) or to just modify the spec so that the inside of the icons matches the notification background color

**Comment by laurenmrice** [comment]
I have updated the spec again with what I propose we could do. The high contrast moments of these notifications cause some of the support colors to change in value for accessibility reasons. After discussing with Anna and Jeannie we were thinking in those areas where it wouldnt call the same support color token, we could just take the equivalent swatch color from IDL, instead of making custom tokens just for notification.

After speaking with Sadek about the adornments fillings of the icons, he said they chose pure black and pure white for accessibility reasons instead of knocking them out. Chris Connors may have some more direction on what should be done here.

**Comment by emyarod** [comment]
for now I'm going to mark this as blocked until we finalize how we want to proceed

**Comment by asudoh** [comment]
Ping @chrisconnors-ibm to see if he wants to chime in. Otherwise I think it'd make sense to proceed with @laurenmrice's thoughts.

**Pull request closed without merging**
