### PR TITLE
feat(accordion): support nested accordion

### LINKED ISSUE #16732: [Bug]: Child accordion's expand/collapse not working
### Package

@carbon/react

### Browser

Chrome

### Package version

1.53.1

### React version

18.2.0

### Description

In nested accordions any child accordion's expand/collapse not working.

### Reproduction/example

https://stackblitz.com/edit/github-tb1sze

### Steps to reproduce

Create any nested accordions. Click on any child accordion to expand/collapse and that's not working.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

IBM OpenPages

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tekno0ryder**
Closes #16732

Support rare case of using nested accordions

#### Changelog

**Changed**

- Changed active css selector from descendant combinator that targets all descendants regardless of their level to child combinator (>) that targets only the direct children.

#### Testing / Reviewing

- Unit test: Expanding parent shouldn't expand children accordion + Expand children works
- Video

https://github.com/carbon-design-system/carbon/assets/8721803/334f938a-dd72-4af6-be87-5912d88dadfd

### CODE REVIEW

**Comment by tekno0ryder** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Gururajj77** [comment]
Hey @tekno0ryder ! thanks for your contribution, could you please setup a test story, that can be excluded later if we approve it??

**Comment by tekno0ryder** [comment]
> Hey @tekno0ryder ! thanks for your contribution, could you please setup a test story, that can be excluded later if we approve it??

Hi! please find preview story [here](https://deploy-preview-16933--v11-carbon-react.netlify.app/?path=/story/components-accordion--nested-accordion)

**Review by guidari — APPROVED** [review]
LGTM! Thanks for the contribution! 🚀

Please don't forget to remove the Test stories before merging it, since it's something that Carbon don't formally support.

**Comment by tekno0ryder** [comment]
@alisonjoseph One more review pls 👀 🙏

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
