### PR TITLE
fix(devenv): fix floating menu container

### PR DESCRIPTION
**Pull request by asudoh**
This change ensures that the floating menus are put in the right element in dev env.

Refs #3181.

#### Changelog

**Changed**

- Fixed where `data-floating-menu-container` attribute in dev env, ensuring that our focus tracking code works.

#### Testing / Reviewing

Testing should make sure our dev env is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
tab order issue for floating menus looks resolved for me now

**Comment by elizabethsjudd** [comment]
Just out of curiosity for the usage/rules around how the `data-floating-menu-container` attribute is used?  I noticed that in both examples it's directly below the body element, does it always have to be there?  In one of them, there is nothing else in it (it's an empty div) but in the other, the contents of the page are children of the div? I'm trying to understand this to see if this is a valid location place to add some landmark roles as well to help with AVT 1 violations.

**Comment by joshblack** [comment]
Make sure to request a review from the dev team so pull panda works! 👍

**Review by joshblack — APPROVED** [review]

**Comment by asudoh** [comment]
@elizabethsjudd The only big requirement of `data-floating-menu-container` is the element not being the last element in `<body>`. It doesn't have to be direct child of `<body>`. No restriction of the contents in it.

**Pull request merged**
