### PR TITLE
fix(tooltip): prevent text truncation on tooltip

### LINKED ISSUE #5428: CodeSnippet action feedback tooltip truncated
## CodeSnippet component

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When I specify a longer text as feedback for the CodeSnippet component, the text gets truncated.

I tested with latest Firefox and latest Chrome.

I am seeing this issue with whatever version of Carbon/React is exposed here: https://react.carbondesignsystem.com/?path=/story/codesnippet--inline

## Steps to reproduce the issue

1. browse to https://react.carbondesignsystem.com/?path=/story/codesnippet--inline
2. In section "Knobs", field "Feedback text" enter a longer text
3. click the sample code snippet above labeld "node -v"
4. see the tooltip pop up.

The tooltip is truncated; it should not be truncated.

## Additional information

image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5428

Ensures long tooltip text does not get truncated. 

#### Changelog

**Removed**

- Removed `max-width` so that long tooltip text will not be truncated

#### Testing / Reviewing

Go to `CodeSnippet`, `inline`, then use the knob to add long tooltip text. Ensure the text is not truncated.

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by aagonzales — CHANGES_REQUESTED** [review]
I'm more inclined to remove or increase the `max-width` then letting the text wrap for this component. These tooltips should ideally stay on a single line and should only be a short confirmation of the action. We also don't want to encourage people putting excessive content in this tooltip since it disappear after a few seconds.

**Comment by Daniel-Schulz-Private** [comment]
**My to cents:** please keep in mind that a very short tooltip may work well in the English language. With other languages this might not be the case. German for example can be very long compared to their English counterpart.

For example:
> "Copied to clipboard!"
> "In die Zwischenablage kopiert!"

The first text ist the exact sample from the carbon-react storybook. This would fit the tooltip.
The German counterpart would not.

Also, concerning wrapping the text at white spaces - in Japanes you may write a whole sentence without any whitespaces.

**Comment by tw15egan** [comment]
@aagonzales I've updated the PR to just remove the `max-width`. I think this will allow for more edge-cases to work like long German strings, and we have guidance on the website to go along with it. I don't think we ever want a tooltip message to be cut off.

@abbeyhrt @emyarod changes were made if you want to take a 2nd look 👍

**Comment by aagonzales** [comment]
@Daniel-Schulz-Private we did consider translation, this is why the max-width is being removed. I think its better for the short phases (in whatever language) to remain on one line for legibility. I think it more awkward when these phases break to 2 line versus grows longer. 

image

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
