### PR TITLE
docs(number-input): add display name to the story source

### PR DESCRIPTION
**Pull request by jendowns**
### Summary

Storybook is not properly reading the `NumberInput`'s display name, even though it is set in the component. This affects the story source, where the component displays as `[object Ojbect]`. Go here and click on the "show info" button to see what I mean: http://react.carbondesignsystem.com/?path=/story/numberinput--default

An easy fix here is to set a display name in the story source, to help storybook out. Then that fixes the story source AND the prop types in the prop table.

### Context

This situation is slightly different from #4521  -- In *that* issue, the `Checkbox` shows up as `Anonymous` in the React component plugin, as a forwardRef without a name. *AND* storybook does not know it's name, so it cannot show a name in the story source or proptable.

However, for *this* `NumberInput`, you can see that the React component plugin knows the component's display name (NOTE: the `Anonymous` you see below is actually the caret up / down icons, which is a separate thing...)

Screen Shot 2019-11-01 at 11 16 02 AM

And indeed, you can see the display name is set in the component source --
https://github.com/carbon-design-system/carbon/blob/86e76f645b5fea05d5b0040931485a39bcf836ae/packages/react/src/components/NumberInput/NumberInput.js#L436-L440

But storybook still does not understand the `NumberInput` display name. In the story source, it shows the component's name as `[object Object]`:

Screen Shot 2019-11-01 at 11 17 37 AM

**So that's why my proposed solution here is to change the display name in the storybook source, as opposed to elsewhere** -- this issue appears to be isolated to the way that storybook is interpreting the display name of the component. 🤔 Whereas the React component plugin knows the component's name.

### Changelog

**New**

- add display name for `NumberInput` in the story source.

### CODE REVIEW

**Comment by abbeyhrt** [comment]
This is great, thank you @jendowns ! `NumberInput`  is showing up correctly for me now, definitely better than `[object Object]` 😂 All of the props are still just `node` though, is that something you are wanting to address in this PR? Totally cool if not!

**Comment by jendowns** [comment]
Thank you @abbeyhrt! You're right! In the PR deployment, I still see `node` proptypes in the prop table 🤔 

But locally, the prop table shows the correct prop types when I run the storybook environment! 😅 

Screen Shot 2019-11-01 at 1 34 41 PM


It's an interesting issue that probably requires more investigation... but for now, IMO, it's out of scope for this PR. I went ahead and updated my issue desc above to remove mention of the prop types listed in the prop table.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Review by abbeyhrt — APPROVED** [review]
That works for me! This looks great!

**Pull request merged**
