### PR TITLE
fix(NumberInput): Allow empty input for NumberInput with allowEmpty prop (#15985)

### LINKED ISSUE #15985: [Bug]: [NumberInput] Can't enter negative numbers
### Package

@carbon/react

### Browser

Chrome

### Package version

1.53.0

### React version

18.2.0

### Description

I can't type negative numbers (eg. -1) in the NumberInput field. Also when I want to remove all digits, number input is set to `0`. Even after setting `allowEmpty`.

Following screen recording from v10 (https://v10.carbondesignsystem.com/components/number-input/code/#live-demo) no longer works in v11 - 

https://github.com/carbon-design-system/carbon/assets/25124000/5fec90a3-69a6-4ec1-a7fc-9381659c37bb

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-numberinput--playground

### Steps to reproduce

Please see description

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #16016: [Bug]: NumberInput : Unable to clear number input textboxes they are defaulted to 0
### Package

@carbon/react

### Browser

Chrome, Safari

### Package version

 "@carbon/react": "1.53.0",

### React version

 "react": "17.0.2",

### Description

- Render the NumperInput component from carbon/react.
- By default, 0 is been assigned to the field.
- Try to clear and add a new value . This would not clear the value 0 instead append the newly added value to 0.
- Though allowEmpty prop is been set to true. The NumberInput field is never cleared.

### Reproduction/example

https://codesandbox.io/p/sandbox/numberinput-9587cm?file=%2Fsrc%2FApp.js%3A7%2C41

### Steps to reproduce

Render the NumperInput component from carbon/react.
- By default, 0 is been assigned to the field.
- Try to clear and add a new value . This would not clear the value 0 instead append the newly added value to 0.
- Though allowEmpty prop is been set to true. The NumberInput field is never cleared.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by hollyos**
Closes #15985
Closes #16016

There were multiple issues open for functionality in the NumberInput.

1. The input did not allow for an empty input, even with `allowEmpty = true`. `Number()` automatically assigns `0` to an empty string. A ternary was added to capture this instance and allow for the empty string when `allowEmpty = true`. It will still default to 0 when `allowEmpty = false`.
2. The input did not allow for negative input. I tested this in the [live demo](https://v10.carbondesignsystem.com/components/number-input/code/#live-demo) and Storybook. It works in both instances. This issue was likely due to the `min` value equaling 0. When `min` is updated to a negative value, the input allows for negatives.
    
    Screenshot 2024-04-01 at 00 16 05

#### Changelog

**Changed**

- allow empty inputs when `allowEmpty = true`

#### Testing / Reviewing

1. Start Storybook
2. visit [NumberInput Playground on localhost:3000](http://localhost:3000/?path=/story/components-numberinput--playground&args=allowEmpty:!true;min:-200;).
3. Ensure the following args are updated:
    | prop | value | purpose |
    | ---- | ------ | -------- |
    | `allowEmpty` | `true` | Ensures that an empty value can be used |
    | `min` | `-200` | Allows for negative values. The default of 0 causes an error to display. |
4. With these params set, select then delete the input value. It should be an empty input.
5. Then enter a negative value greater than the `min` value. Should allow the value and not show an error.

### CODE REVIEW

**Comment by hollyos** [comment]
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> I have read the DCO document and I hereby sign the DCO.
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the [DCO document](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) and I hereby sign the [DCO](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md).

**Comment by hollyos** [comment]
recheck

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅ Thanks for contributing and the detailed explanations! Would updating the helper text to display the minimum or maximum or updating the example to a minimum of `-100` help alleviate the original confusion?

**Comment by tw15egan** [comment]
@hollyos Yeah, that's a good point, I think updating the storybook is all that's needed. We can track that separately

**Comment by hollyos** [comment]
@tw15egan currently, the validity checker is only a bool response. There's no context as to the reason for the failure. Without adding a bunch of overhead, may just be worth updating `invalidText="Number is not valid"` to `invalidText="Number is not valid, update knobs below"` for the Playground implementation. Thoughts?

**Comment by 2nikhiltom** [comment]
Hey @hollyos  Thanks for your contribution, this looks good 🔥 
I've set the minimum value in the storybook example to -100,  I believe this should alleviate the original confusion
 ```
<NumberInput
      id="carbon-number"
      min={-100}
      max={100}
      value={50}
      label="NumberInput label"
      helperText="Optional helper text."
      invalidText="Number is not valid"
      {...args}
    />
```

**Review by andreancardona — DISMISSED** [review]
@hollyos there are also some failing AVT tests, do you mind fixing those? Thank you!

**Review by tay1orjones — APPROVED** [review]
I updated the avt tests to reflect the new `min` value in the default story. This prop isn't covered by any unit tests right now, I've opened https://github.com/carbon-design-system/carbon/issues/16207 to track addressing that so we can merge this.

**Pull request merged**
