### PR TITLE
chore(icons): update categories for icons for the app catalogue section

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
Making sure all icons that are an equivalent of an app icon are in "App catalogue" and those who are not, are not included.

Moved into app catalogue section:
-	Autoscaling
-	Block storage

Moved out of the app catalogue section into systems:
-	Cloud alerting
-	Cloud data-ops
-	Cloud service management
-	Cloud services

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
@DianaStanciulescu you'll need to sign the DCO before we can merge this

**Review by kingtraceyj — APPROVED** [review]
looks like object storage was added to the app catalogue as well. if that was intentional then approved!

**Comment by DianaStanciulescu** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by DianaStanciulescu** [comment]
@tracy yes it was! thanks!

**Comment by DianaStanciulescu** [comment]
recheck

**Review by jnm2377 — APPROVED** [review]

**Comment by jnm2377** [comment]
recheck

**Pull request merged**
