### PR TITLE
refactor(toggle): make toggle labels accessible

### LINKED ISSUE #2809: AVT 3 - React & Vanilla Toggle Component: VoiceOver does not announce labels
## Environment
Tested on macOS Mojave 10.14.5, Version 74.0.3729.157 (Official Build) (64-bit), with VoiceOver

## Description
Tab to the default toggle component. 
Click on the Enter or Space Key
VoiceOver does not announce the On / Off label

Note: It looks like aria-hidden="true" was recently added to the toggle component. If the aria-hidden is removed the label is read correctly. (see screenshot)
Screen Shot 2019-05-22 at 3 59 56 PM

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2809

This PR refactors the toggle and small toggle components to have accessible labels.

question for reviewers: Do we want to wrap the component in a `div.toggle`? Do we also want to support an inline toggle?

#### Changelog

**New**

- class names for accessible toggle version (old classes and markup will be deprecated)

**Changed**

- markup structure of toggle label and switch

**Removed**

- deprecated check mark in small toggle (not found in v10 spec according to images in https://github.com/carbon-design-system/carbon/pull/1267)
- redundant style rules

#### Testing / Reviewing

Ensure the toggle and small toggle function and appear correctly

### CODE REVIEW

**Comment by asudoh** [comment]
Great that you started this effort @emyarod! Any explanation on why you chose to rip/replace the markup/style?

**Comment by emyarod** [comment]
@asudoh primarily to use proper markup for labeled toggles without breaking how the component appears. The current `fieldset` and `legend` structure is not proper usage of those elements

**Comment by carmacleod** [comment]
@emyarod Nice! I tested Vanilla (https://deploy-preview-2885--the-carbon-components.netlify.com/?nav=toggle) with JAWS & NVDA in Chrome & FF, and things sound good.

I only noticed 1 problem: for the "Toggle with visible label", please delete the `aria-label` completely, because:
1. It is unnecessary, because the `<label>` has already been properly connected to the `<input>` using the `for` attribute in the markup.
2. It is harder to maintain 2 strings - they can easily diverge because one of them is invisible. 
(even in the example, `aria-label="example toggle with visible label"` differs from `"Toggle with visible label"`).
  - Differing strings is a problem because they can be misleading to screen reader users, and also because users of speech control systems like Dragon need to be able to say "Click Toggle with visible label", and since the aria-label overrides the visible label, the toggle's name is actually "example toggle with visible label" which is not the same, so the voice command may not work.

**Comment by snidersd** [comment]
@emyarod I have tested it on macOS & VO with the same results as @carmacleod and I agree with her comments.

**Comment by emyarod** [comment]
got it @carmacleod @snidersd! I've made those adjustments

vanilla toggle and small toggle should be ready for code and visual review (and need design feedback on the visual changes and possible inline variant before continuing with the React version)

**Review by laurenmrice — CHANGES_REQUESTED** [review]
We still need the checkmark in the small toggle, it should not be deprecated. The spec in the issue that is referenced was from Oct and is out of date. Please reference most up to date specs: https://ibm.ent.box.com/file/334120810490

Screen Shot 2019-06-13 at 11 16 21 AM

**Comment by emyarod** [comment]
restored the checkmark

**Comment by emyarod** [comment]
@laurenmrice I restored the checkmark to the small toggle. if the vanilla component is ok now after that change I can bring the changes over to the React version

**Review by laurenmrice — DISMISSED** [review]
I think last change for vanilla, is that the label for toggle should be `text-02`.
Screen Shot 2019-06-13 at 1 45 24 PM

**Comment by emyarod** [comment]
changed the label color, will now begin porting these changes to React

**Comment by asudoh** [comment]
@emyarod Good progress - Does older markup still work with your change?

**Comment by emyarod** [comment]
yes @asudoh I've left the original class names and styles (https://github.com/carbon-design-system/carbon/pull/2885/files?file-filters%5B%5D=.scss#diff-a09abac691f611c74ef26801c826e0b1R245), similar to the tooltip refactors

**Comment by emyarod** [comment]
@carmacleod @snidersd the React [toggle](https://deploy-preview-2885--carbon-components-react.netlify.com/?path=/story/toggle--toggled) and [small toggle](https://deploy-preview-2885--carbon-components-react.netlify.com/?path=/story/togglesmall--toggled) are now ready for review

**Review by tw15egan — APPROVED** [review]
👍

**Review by jnm2377 — APPROVED** [review]

**Comment by carmacleod** [comment]
Looks good.

**Review by aagonzales — APPROVED** [review]
Visually it looks correct to me.

**Comment by asudoh** [comment]
Last check before merging @emyarod - Does the style still support older markup? Great work!

**Comment by emyarod** [comment]
yes @asudoh none of the old classes were modified

**Pull request merged**
