### PR TITLE
chore(project): update storybook to 6.3.6

### PR DESCRIPTION
**Pull request by joshblack**
Update storybook to 6.3.6

#### Changelog

**New**

**Changed**

- Update storybook to 6.3.6

**Removed**

#### Testing / Reviewing

- Make sure netlify previews for storybook work as expected

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
Both storybooks rendering as expected 👍✅

**Comment by joshblack** [comment]
Nice catch by percy, cc @tay1orjones any idea why it might not be showing `show more` anymore? 🤔

**Comment by tw15egan** [comment]
Weird, they are showing in the previews and when running locally

**Review by dakahn — APPROVED** [review]

**Comment by tay1orjones** [comment]
@joshblack wow, sorry this fell through my notifications. I believe @jnm2377 pushed up a fix for the `show more` not rendering - we just needed to wait/assert that the show more button was settled in the dom before taking the snapshot.

I'll update with latest from main and I think it should resolve

**Pull request merged**
