### PR TITLE
chore(project): update to node 14.17 lts

### PR DESCRIPTION
**Pull request by sstrubberg**
This updates node to v14.17 LTS.

#### Changelog

**Changed**

- nvmrc to 14.17
- Updated `node-sass` & `gulp-sass` dependencies across the project to allow build process to complete successfully.
- Ran `yarn dedupe` to remove dupes.

#### Testing / Reviewing

Make sure this doesn't break our build!

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Looks great! I think all that's left is running `yarn dedupe` and you'll be good to go 👍

**Review by tw15egan — APPROVED** [review]
Everything seems to be working fine on my end 👍🏻 ✅

**Review by tay1orjones — COMMENTED** [review]
@sstrubberg should we also update the configs for circle ci and the github action workflows to be explicitly 14.17 vs 14.x?

**Comment by joshblack** [comment]
@tay1orjones in the other PR we were talking about it and 14.x should resolve to 14.17 now that it's LTS so it should be good 👀

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
