### PR TITLE
feat(icons): add statistics icons

### PR DESCRIPTION
**Pull request by janhassel**
Add data type icons for ordinal and nominal data as well as an icon to describe interactions (in the context of statistics)

#### Changelog

**New**
- Icon "ordinal"
- Icon "nominal"
- Icon "interactions"

#### Testing / Reviewing

1. Build `packages/icons`
2. Run `yarn develop` in `/packages/icons/examples/preview`
3. Look for the icons "ordinal", "nominal" and "interactions"

### CODE REVIEW

**Review by dakahn — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
looks good 🎉

**Review by joshblack — APPROVED** [review]

**Comment by janhassel** [comment]
@joshblack I have a quick follow-up question: Do the framework-specific icon packages (`@carbon/icons-react`, `@carbon/icons-vue`, `@carbon/icons-angular`) get updated automagically or do I need to submit a PR for them as well?

Also, how can I contribute them to the master sketch libraries? (https://www.carbondesignsystem.com/resources#color-grid-and-icons)

**Comment by joshblack** [comment]
@janhassel they should get updated automatically! If not, it definitely is an issue and let me know 😅 Should be in our next release! The same would go for our sketch library for icons as that is generated from code, as well 👍

**Comment by laurenmrice** [comment]
^For our next release we will need a dev resource so we can get the new icons into the plugin so we can update the libraries.

**Comment by joshblack** [comment]
@laurenmrice made a quick issue for this over in: https://github.com/carbon-design-system/carbon/issues/4849 for us

**Comment by janhassel** [comment]
@joshblack Awesome, sounds good. Thanks for the info!

**Pull request merged**
