### PR TITLE
feat(file-uploader): add button for a11y and refactor to hooks

### LINKED ISSUE #3437: AVT 3 - React FileUploader X icon is not announced by JAWS and it does not clear the selection
## Environment
Windows 10
FireFox Quantum 68.0
JAWS 18

## Description
1. Tab to the Add Files button. JAWS announces "Main region, add files, clickable."
2. Press Space or Enter to open the dialog, navigate to a jpg file and select it.
3. Tab to the X icon, JAWS announces "Provide item description."
**Expected Result:** JAWS should announce the purpose of the button, such as "Clear File"
4. Press Enter or Space on the icon and the file fails to clear the selected file. 
Note: The icon works as expected for keyboard-only users.

### PR DESCRIPTION
**Pull request by joshblack**
Closes #3437

Adds a `<button>` to the underlying edit icon to address #3437. Also updated some components to hooks and refactoring to match patterns for newer parts of the codebase.

#### Changelog

**New**

- Add `getByLabel` helper for getting interacting nodes as opposed to `getByText`

**Changed**

- Pull out `Filename` and `FileUploaderButton` into separate files
- Update `FileUploaderButton` to hooks
- Add `button` for filename edit in `Filename`

**Removed**

### CODE REVIEW

**Review by dakahn — CHANGES_REQUESTED** [review]
_Tested with JAWS 2020 on Windows 10 in Firefox Latest_

Looks like the there's some wonky focus styling going on
image

When the button is focused with JAWS it reads
"Delete file button, to activate press spacebar" Which is cool, except then user can also use `enter` to remove the file. 

Something else I thought about -- and feel free to ignore this as it's not directly related to this PR, but a successful upload is not announced in anyway. Savvy users may know to move ahead to the next interactable element and hear their file in the list though. 

It reads really nicely in NVDA though. "Button; delete file" 💟

**Comment by joshblack** [comment]
@dakahn is there anything I need to change for the JAWS announcement? Is that how it announces buttons by default?

Agreed on the update thing, would be a nice QOL update to show how to organize that with a form submission.

**Review by dakahn — APPROVED** [review]
Didn't mean to hold this up! yeah, that's default JAWS behavior 🤪

**Comment by dakahn** [comment]
That update idea could be a separate ticket -- not a blocker here sry sry

**Comment by joshblack** [comment]
Let me know if you want to take any time to chat about this @emyarod!

**Review by emyarod — APPROVED** [review]

**Pull request merged**
