### PR TITLE
fix(HeaderGlobalAction): provide visual text for link via title attribute

### LINKED ISSUE #7731: Action icons in the UI Shell Header do not provide visual text to describe the link purpose
## [Action icons in the UI Shell Header](https://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-actions) do not provide visual text to describe the link purpose
This is a failure of [WCAG 2.1 Success Criterion 2.4.4 Link purpose (In context)](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context#techniques) The intent of this Success Criterion is to help users understand the purpose of each link so they can decide whether they want to follow the link. 
If a user does not know what the icon means, there should be visible text to describe the link's purpose such as a tooltip.

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #7731

Adds a `title` attribute to the HeaderGlobalAction in the same fashion that HeaderMenuButton has to provide visual text for the link.

#### Changelog

**New**

- add `title`

#### Testing / Reviewing

Title text should be visible on hover of a HeaderGlobalAction

### CODE REVIEW

**Comment by tw15egan** [comment]
I'll defer to DA if a `title` will be sufficient enough, but if not, I think we can just change this from a `button` to `Button` and add a few props:

```jsx
<Button
      {...rest}
      {...accessibilityLabel}
      className={className}
      onClick={onClick}
      type="button"
      hasIconOnly
      iconDescription={ariaLabel}
      tooltipPosition="bottom"
      tooltipAlignment="end"
      ref={ref}>
      {children}
    </Button>
```

which renders as 
Screen Shot 2021-02-03 at 1 27 08 PM



Looks like we'd just need to add a `justify-content: center` to `.bx--btn.bx--btn--icon-only.bx--tooltip__trigger` to fix the alignment issues.


We'd also probably want to pass down the `tooltipAlignment` from `<HeaderGlobalAction>`, or figure out a way to determine if it is the last item.




This also then ties into the problem discovered here, but that can be fixed in a separate PR: https://github.com/carbon-design-system/carbon/issues/7040

Screen Shot 2021-02-03 at 1 33 42 PM

**Comment by tay1orjones** [comment]
@dakahn for context here, I _think_ the `title` is enough based on [the WCAG link](https://www.w3.org/WAI/WCAG21/Understanding/link-purpose-in-context#techniques) provided in the initial issue; `Sufficient technique #6, H33`, but let me know if that's off base. I'm happy to take the approach TJ outlined if it makes more sense

**Comment by tw15egan** [comment]
@tay1orjones for sure, this may be our best bet until we get the popover component (https://github.com/carbon-design-system/carbon/issues/7649) to avoid issues a few people have pointed out (#4560, #7040)

**Comment by aledavila** [comment]
I wonder the issues this would cause considering theyre not links but buttons that would open up the panels that are in the pipeline for v11. While I understand the need to descirbe a link they're not and shouldn't be used as such.

**Comment by dakahn** [comment]
**Sorry, missed this in my notifications.** `title` is pretty well supported with NVDA and JAWS, but gets sketchier on macOS and iOS using VoiceOver as seen [here in powermapper](https://www.powermapper.com/tests/screen-readers/attributes/#title). I think the better way to go moving forward when programmatically labeling our icon buttons is to have a visually hidden label and reference the hidden label via `aria-labelledby`
```html
<button aria-labelledby="button-label"> 
    <span id="button-label" hidden>Menu</span>
    <svg aria-hidden="true" focusable="false" width="24" height="28" viewBox="0 0 24 28">
        <!-- svg content -->
    </svg>
</button> 
```

**Review by dakahn — DISMISSED** [review]
**Sorry, missed this in my notifications.** `title` is pretty well supported with NVDA and JAWS, but gets sketchier on macOS and iOS using VoiceOver as seen [here in powermapper](https://www.powermapper.com/tests/screen-readers/attributes/#title). I think the better way to go moving forward when programmatically labeling our icon buttons is to have a visually hidden label and reference the hidden label via `aria-labelledby`
```html
<button aria-labelledby="button-label"> 
    <span id="button-label" hidden>Menu</span>
    <svg aria-hidden="true" focusable="false" width="24" height="28" viewBox="0 0 24 28">
        <!-- svg content -->
    </svg>
</button> 
```

**Comment by tay1orjones** [comment]
I just pushed an update to use `Button` and pass through the tooltip alignment 👍

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by dakahn — APPROVED** [review]
Very cool thanks so much

**Pull request merged**
