### PR TITLE
fix(AISkeleton): update token values

### LINKED ISSUE #15825: AI Skeleton: update token values
AI chat team has made some visual updates to the AI skeleton and we need to update the token values.

| Token | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme | 
|-------|--------------|---------------|----------------|-----------------|
| AI-skeleton-background | Blue 20 | Blue 20 | Blue 30 | Blue 30 |
| AI-skeleton-element | Blue 50 | Blue 50 | Blue 60 | Blue 60 |

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15825

#### Changelog

**Changed**

- Updates the `AI Skeleton` token values

#### Testing / Reviewing

Ensure the animation looks correct

### CODE REVIEW

**Review by guidari — APPROVED** [review]
LGTM! 🚀

**Review by alisonjoseph — APPROVED** [review]

**Comment by aagonzales** [comment]
Something isn't right here. Just looked at the example is its barely notificable. I just dropped the updated values Juan gave me but it might actually need some adjusting in code vs figma. Let me take a quick look at things and get back to you.

**Review by aagonzales — CHANGES_REQUESTED** [review]
Ok can we update the element values by two steps. Right now you can't see the dark animation at all. 

| Token | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme | 
|-------|--------------|---------------|----------------|-----------------|
| AI-skeleton-element | Blue 50 | Blue 50 | Blue 60 | Blue 60 |

**Comment by tw15egan** [comment]
@aagonzales updated

**Review by aagonzales — CHANGES_REQUESTED** [review]
Light theme looks good now but the dark is still too faded. For Gray 90 and Gray 100, let's take the element up to 'Blue 80'. I think that should do it.

**Review by aagonzales — APPROVED** [review]
Ok I think that's good now. Geez what a problem child the dark theme was here.

**Pull request merged**
