### PR TITLE
Fix(data-table): extend data table size modifiers to support th inside of tbody

### PR DESCRIPTION
**Pull request by ChevonNwosu**
Related #3946 

When a `th` is inside a Table Body, size modifiers are not affecting cells.

#### Changelog

**New**

- Extended css selectors to include `th` in table body 

#### Testing / Reviewing
- [ ]   Size modifiers work when `th` is inside table body

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @ChevonNwosu!

**Review by emyarod — APPROVED** [review]
looks good to me, the tests timed out previously but they are passing after rerunning them

**Review by elizabethsjudd — APPROVED** [review]

**Comment by aagonzales** [comment]
Which storybook example or knob should I look at to see this in play?

**Review by emyarod — COMMENTED** [review]
I may have prematurely asked for design review @aagonzales, for this change to show up in the docs we would need to edit the examples.

but actually taking another look at this PR, I just want to confirm whether or not the work is complete or if the plan is to split it into several PRs.

the height of `tbody tr th` is now being set to the same height as `thead tr` and `tbody tr`, but the `th` styles (particularly padding) are still inherited from the existing styles

image

so even though this is supposed to be a compact table the rows with `tbody th` are default sized still. was this meant to be tackled in a follow up PR? cc @ChevonNwosu @elizabethsjudd

**Comment by ChevonNwosu** [comment]
image

@emyarod Nice catch! Had those changes staged but never committed. They are in the most recent commit now!

**Review by emyarod — COMMENTED** [review]
the padding issue looks resolved now. is the zebra striping issue going to be addressed in a follow up PR or was it supposed to be in this one?

**Comment by tw15egan** [comment]
@emyarod I believe zebra striping is going to be resolved in another issue since we need to also come to a conclusion on the `th` in a table row background color. I believe we were going to implement something like the w3c

Screen Shot 2020-02-25 at 7 24 05 PM

**Comment by emyarod** [comment]
don't know if we should show this use case in the documentation but here's a full page screenshot for visual review. I just replaced the `td`s with `th`s

image

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
