### PR TITLE
fix: 3D-iCA metadata

### LINKED ISSUE #3708: [icons]: iCa icon using different naming conventions
This came up during the icon library component work. The `iCa-3D` icon should be `3D-iCA` to be inline with the other 3D Watson Health icons:

```
- 3D-Cursor
- 3D-curve--auto-colon
- 3D-curve--auto-vessels
- 3D-curve--manual
- 3D-MPR-Toggle
```

It should also use a more appropriate friendly name. 
Suggesting `3D iCa` to replace `I ca 3D`. 

Other Watson Health friendly names:

```
- 3D Cursor
- 3D curve auto colon
- 3D curve auto vessals
- 3D curve manual
- 3D mpr toggle
```

### PR DESCRIPTION
**Pull request by vpicone**
closes #3708

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
Will defer to chris/conrad on categorization 👍

**Comment by vpicone** [comment]
@joshblack not changing the categorization, just the name to match the other `3D` icons with the watson health prefix.

Any idea whats up with the ci-check error? The svg file was updated and it's a little vague. 

```bash
Error: The following icons are missing or an error has occurred:
[
  "3D-iCA"
]
```

**Comment by chrisconnors-ibm** [comment]
looks like this just makes an asset name = its references in `metadata.yml` and `categories.yml`

only question for @conradennis is, which is it supposed to be: `iCA-3D.svg` or `3D-iCa.svg`?

In my repo the assets is named `iCA-3D.svg` which I assume is intentional.

**Comment by conradennis** [comment]
I'm fine with renaming it 3D-iCA, I don't think the order of the name matters so it's probably better to group it with the other 3D named icons

**Comment by vpicone** [comment]
@chrisconnors-ibm 

This came up during the icon library component work. The iCa-3D doesn't follow the naming convention of the other 3D Watson Health icons:

- 3D-Cursor
- 3D-curve--auto-colon
- 3D-curve--auto-vessels
- 3D-curve--manual
- 3D-MPR-Toggle

It should also use a more appropriate friendly name, right now it's `I ca 3D`.

Other Watson Health friendly names:

- 3D Cursor
- 3D curve auto colon
- 3D curve auto vessals
- 3D curve manual
- 3D mpr toggle

**Review by joshblack — APPROVED** [review]

**Review by chrisconnors-ibm — APPROVED** [review]
this matches Objective per conrad "rename it 3D-iCA to group with other 3D icons"

**Review by joshblack — CHANGES_REQUESTED** [review]
Looks like CI is failing because the asset name is `3D-iCA` instead of `3D-iCa` 👍

**Review by joshblack — APPROVED** [review]

**Pull request merged**
