### PR TITLE
fix(select): reposition chevron SVG

### LINKED ISSUE #5651: Select component's arrow displays incorrectly on IE11
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-angular`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The arrow displays below the select component in IE11.
image

> Is this issue related to a specific component?

Select component
Also affects time picker selects in carbon-components-angular and carbon-components-react

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Similar problem fixed for the listbox in
https://github.com/carbon-design-system/carbon/pull/4898

In
https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/select/_select.scss
at
`  .#{$prefix}--select__arrow {
    fill: $ui-05;
    position: absolute;
    right: $spacing-05;
    pointer-events: none;
  }`

top: 0;
bottom: 0;
should be added to it like in the pull request.

and `height: 100%` should be added to the arrow SVG.
like in listbox `  .#{$prefix}--list-box__menu-icon > svg {
    fill: $icon-01;
    height: 100%;
  }
`

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

10.10.1

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5651

This PR resolves a chevron SVG positioning issue in the select component on IE11

#### Testing / Reviewing

Confirm the select component is visually correct on all browsers

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]

**Comment by jdcai** [comment]
The height: 100% needs to be on the svg instead for it to look correct
.#{$prefix}--select__arrow > svg { height: 100%; }

**Comment by emyarod** [comment]
`.bx--select__arrow` selects the svg

https://github.com/carbon-design-system/carbon/blob/5d8392dea3cffe18c90e7fe9c2741afd8c4b47bf/packages/react/src/components/Select/Select.js#L84

**Comment by jdcai** [comment]
Oh looks like its an angular specific thing. The class is not on the svg so it doesn't display properly without the `> svg`.
image

**Comment by emyarod** [comment]
I see, you may want to open that issue separately against `@carbon/icons-angular` (related https://github.com/carbon-design-system/carbon-icons-angular/issues/10?)

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by cal-smith** [comment]
> Oh looks like its an angular specific thing. The class is not on the svg so it doesn't display properly without the `> svg`.
> image

Check the `icons-angular` README: https://github.com/carbon-design-system/carbon-icons-angular#api

We support `innerClass` for the component form, but the directive form should be preferred in general, since it makes styling and positioning easier ... We should be able to use IBM/carbon-components-angular#1143 to update it to the correct form.

**Pull request merged**
