### PR TITLE
feat(tag): add high-contrast type

### PR DESCRIPTION
**Pull request by janhassel**
With the recent work on bringin over the normal tag colors in filter tags, the default dark-gray appearance is not supported anymore. However, there are situations where a higher contrast than the normal gray tag color is needed. In fact, the multi-select component uses a custom background-color override since it sits inside of an input element (and therefore usually on a light gray background).

image

This PR is a proposal on introducing a "high-contrast" tag type (name is not set in stone) which essentially inverts the default gray appearance from light and dark themes.
So, in white/g10 it will look like a default tag in g90/g100 and in g90/g100 it will look like a default tag in white/g10.

#### Changelog

**New**

- Extended tag component tokens to include `high-contrast`
- Added `high-contrast` type to React component

#### Testing / Reviewing

Verify new tag type on react storybook.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
could you update the snapshots to pass CI?

**Comment by janhassel** [comment]
@emyarod Sure thing. Fix is pushed!

**Comment by designertyler** [comment]
Would it be better to use the `$inverse-01` and `$inverse-02` tokens for type and background colors? This would be similar to the notification component.

**Comment by janhassel** [comment]
@designertyler Good point, haven't thought about that.
Just pushed an update appyling `$inverse-01` for the text, `$inverse-02` for the background and `$inverse-hover-ui` for the hover.

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@designertyler anything else you can think of after the updates from @janhassel using the inverse tokens? 👀

**Review by designertyler — APPROVED** [review]
@joshblack @janhassel No, this looks good 👍

**Pull request merged**
