### PR TITLE
chore(react): update storybook to re-enable theming panels

### LINKED ISSUE #5331: Enable theming panels in storybook
In a recent update, the panels that we had configured for our Netlify builds stopped appearing. This issue is for figuring out why these panels disappeared and re-enabling them so that they appear on Netlify deploy previews.

### PR DESCRIPTION
**Pull request by joshblack**
Closes #5331 

Update storybook config to remove dynamic import and update call signature for addons registration.

#### Changelog

**New**

**Changed**

- Update how our custom addon is registered

**Removed**

#### Testing / Reviewing

- Verify the netlify preview includes the theme and type panels
- Pull down locally and verify:
  - Running `yarn storybook` does *not* include the theme and type panels
  - Running `CARBON_REACT_STORYBOOK_USE_CUSTOM_PROPERTIES=true yarn storybook` *does* include the theme and type panels

### CODE REVIEW

**Comment by joshblack** [comment]
cc @aagonzales if you wanted to double-check!

**Review by aagonzales — COMMENTED** [review]
It's alive again!! Awesome, thank you.

**Review by aagonzales — APPROVED** [review]
Oops got too excited and selected the wrong thing

**Review by aledavila — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Pull request merged**
