### PR TITLE
fix(code-snippet): use transparent color instead of transparent keyword for linear gradients

### LINKED ISSUE #4769: Code snippet fade effect is inconsistent in Safari
## What package(s) are you using?

Mac os Catalina 10.15.1
Safari 13.0.3
carbon-components 10.7.4
carbon-components-react 7.7.4

## Detailed description

The ::after pseudo element of the code snippets are a dark gray.

## Is this issue related to a specific component?
Yes, the single and multi-line code snippets

## What did you expect to happen? What happened instead? What would you like to see changed?
The pseudo element for the text fade effect blends with the background

## What browser are you working in?
Safari

## Steps to reproduce the issue
1. Step one - Using safari browser http://react.carbondesignsystem.com/?path=/story/codesnippet--multi-line

## Additional information

- Screenshots or code
Screen Shot 2019-11-25 at 7 52 20 AM
Screen Shot 2019-11-25 at 7 52 42 AM

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4769 

Safari interprets `transparent` (which [maps to `rgba(0, 0, 0, 0)`](https://developer.mozilla.org/en-US/docs/Web/CSS/color)) differently & therefore the linear gradients used in the `CodeSnippet` component are darker, like a transparent black.

Here a couple links explaining this: 

- https://stackoverflow.com/a/56548711
- https://css-tricks.com/thing-know-gradients-transparent-black/

#### Changelog

**Changed**

- use the Sass `rgba()` color function to make primary gradient color transparent, rather than using `transparent` keyword

### CODE REVIEW

**Comment by jendowns** [comment]
Hey FYI if you notice a strange style regression with the `CopyButton` inside the `CodeSnippet`, that appears to be caused by a class name getting left out in an earlier change. 

I reported the issue here: https://github.com/carbon-design-system/carbon/issues/4772 & I'm working on a fix for that separately 👍

**Comment by abbeyhrt** [comment]
Hi @jendowns! For me, the linear-gradient isn't there anymore. Here's what I'm seeing now:  
Screen Shot 2019-11-25 at 1 43 13 PM

**Comment by jendowns** [comment]
Thanks @abbeyhrt!

I can see the gradients locally, but not in these deployments (like you just reported).

Looks like the reason is related to this issue I opened a couple weeks ago: https://github.com/carbon-design-system/carbon/issues/4345

Using the `rgba()` Sass function with color tokens is fine locally but then the deployments throw in CSS variables & things are compiled incorrectly, with the variables? 😭 

```scss
// Original Sass
background-image: linear-gradient(to right, rgba($ui-01, 0), $ui-01);

// Compiled *local* CSS, which looks great 🎉
background-image: linear-gradient(to right, rgba(244, 244, 244, 0), #f4f4f4);

// Compiled deployed CSS with variables, which is broken 😭 
background-image: linear-gradient(to right, rgba(var(--cds-ui-01, #f4f4f4), 0), var(--cds-ui-01, #f4f4f4));
```

@emyarod What do you think should be done here? Is this related to any work you are currently doing for https://github.com/carbon-design-system/carbon/issues/4345?

I was thinking a possible solution here would be to use the theme mixins & just target each theme... and then manually set these values to rgb, instead of using color tokens. To avoid the variables messing up the gradients in these deployments. 🤔

**Review by emyarod — APPROVED** [review]
looks good to me, the gradients are no longer present locally and in the deploy preview

**Comment by emyarod** [comment]
regarding #4345, it's on hold at the moment since we haven't come up with a good way to proceed yet and it should only be affecting experimental code (including the deploy preview) IIRC

**Comment by jendowns** [comment]
Thanks @emyarod! When you say "the gradients are no longer present locally" -- do you mean when you pulled down my branch & ran the storybook environment, you did not see them? (My observation is that they aren't visible on the deploy preview due to variable usage but *are* visible if running locally)

**Comment by emyarod** [comment]
> do you mean when you pulled down my branch & ran the storybook environment, you did not see them?

yes that's what I meant, I don't have the gradient locally with and without custom properties enabled

**Comment by jendowns** [comment]
@asudoh should I close this out given your PR #4781?

**Comment by asudoh** [comment]
Yeah makes sense - Considered regular `linear-gradient` approach but I saw a problem with CSS custom properties. Thank you for trying to address this problem @jendowns!

**Comment by jendowns** [comment]
Thanks @asudoh! In the future please let me know if you'd like me to adjust my existing PR -- always happy to take feedback. 😄 

Closing this one out

**Comment by asudoh** [comment]
@jendowns My apologies if it looked like I took over your work - I always recognize you are making great contributions to Carbon. This specific case I got a similar issue on Modal which needed a quick solution. I'll be extra careful if any of my work may conflict with your work and make sure it's communicated. Thank you for your contributions as always!

**Comment by jendowns** [comment]
No worries at all @asudoh! And thank you so much for your kind words. ❤️

**Pull request closed without merging**
