### PR TITLE
fix(Button): remove default tabIndex

### PR DESCRIPTION
**Pull request by tw15egan**
Refs https://github.com/carbon-design-system/carbon/issues/11095
Refs https://github.com/carbon-design-system/carbon/issues/6423

Removes the default `tabIndex` value from `Button`, as it was causing a11y violations when buttons were placed inside of an element with `aria-hidden="true"`

#### Changelog

**Removed**

- Removed the default `tabIndex` value

#### Testing / Reviewing

Ensure all Buttons still retain proper focus and tab order. `Button`, `DataTable` batch actions, etc..

### CODE REVIEW

**Comment by tay1orjones** [comment]
I think this makes sense. In particular, after looking at [the MDN topic](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex) on this, we probably shouldn't be adding 0 as a default:

> Some focusable HTML elements have a default tabindex value of 0 set under the hood by the [user agent](https://developer.mozilla.org/en-US/docs/Glossary/User_agent). These elements are an [`<a>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) or [`<area>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/area) with href attribute, [`<button>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button), ... Developers shouldn't add the `tabindex` attribute to these elements unless it changes the default behavior (for example, including a negative value will remove the element from the focus navigation order).

**Comment by tay1orjones** [comment]
IBMa [also thinks](https://ibm-studios.slack.com/archives/G01GCBCGTPV/p1676569885403589?thread_ts=1676565828.500929&cid=G01GCBCGTPV) this is the right direction to take.

I'm going to mark this as ready for review.

**Review by tay1orjones — APPROVED** [review]
The following areas look correct to me on the deploy preview:
- [x] DataTable/Batch actions
- [x] ButtonSet
- [x] ActionableNotification
- [x] Toggletip
- [x] UIShell
- [x] Pagination

**Review by andreancardona — APPROVED** [review]
tested and all looks good also ran the checker!

**Pull request merged**
