### PR TITLE
fix(dropdown): prevent chevrons from disappearing on option select

### LINKED ISSUE #1895: Dropdown chevron disappearing on option select
When a user selects an option from the dropdown component, the chevron is erased by the text of the new option

kapture 2019-02-25 at 10 23 12

regression caused by resolving https://github.com/IBM/carbon-components/issues/1765 (https://github.com/IBM/carbon-components/pull/1846)

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1895

Related #1765 #1846

This PR prevents the dropdown logic from erasing the chevron from the list item when a new option is selected.

To the reviewers: is there a more elegant way to get around this issue aside from appending the raw SVG string each time?

### CODE REVIEW

**Comment by asudoh** [comment]
> To the reviewers: is there a more elegant way to get around this issue aside from appending the raw SVG string each time?

Good question - I'd go for showing/hiding rather than changing DOM. Thank you for asking @emyarod!

**Comment by emyarod** [comment]
makes sense @asudoh, so we should probably refactor this to avoid completely erasing the SVG in the list item right? https://github.com/IBM/carbon-components/blob/master/src/components/dropdown/dropdown.js#L171

although I'm not sure if we can show/hide instead of changing DOM since we have to account for the possibility that the consumer won't wrap text nodes in another element, unless I am misunderstanding your suggestion

**Comment by asudoh** [comment]
> so we should probably refactor this to avoid completely erasing the SVG in the list item right? https://github.com/IBM/carbon-components/blob/master/src/components/dropdown/dropdown.js#L171

Another good question @emyarod - The code assumes that the DOM node in question only contains the content of the selected item. Seems that an earlier change made that assumption false. Wondering what DOM structure change caused that and why it was needed...? Thanks!

**Comment by emyarod** [comment]
it was caused by this #1765 and #1846 but I've added a wrapper `<li>` for the SVG as per our earlier discussion

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by tw15egan — APPROVED** [review]
Not sure of another way to handle, so it looks good to me 👍

**Pull request merged**
