### PR TITLE
fix(HCM): update Firefox HCM focus styles

### LINKED ISSUE #7301: Select component lacks focus indicator in Windows High Contrast Mode
## Environment

> Operating system

Windows 10

> Browser

Firefox 83.0

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

> What version of the Carbon Design System are you using?

I used the website to test, Carbon Components React v7.24.0 at the time of this writing.
https://react.carbondesignsystem.com/?path=/story/select--default

Also tested on Carbon Components
https://www.carbondesignsystem.com/components/select/usage/#main-content

> What did you expect to happen?

I expected to see some kind of focus indicator when using the keyboard to tab the focus onto the Select component.  A related issue https://github.com/carbon-design-system/carbon/issues/6882 was closed as fixed by a PR, but I am still seeing the issue with Select's focus indicator on Windows 10 High Contrast Mode.

> What happened instead?

There was no visual focus indicator on the Select component.  I confirm the focus is on the Select by pressing the Spacebar to open the Select's dropdown menu.

> What WCAG 2.1 checkpoint does the issue violate?

https://www.ibm.com/able/guidelines/ci162/focus_visible.html

### LINKED ISSUE #7313: UI Shell: Side navigation rail lacks focus indicator in Windows High Contrast Mode
## Environment

> Operating system

Windows 10

> Browser

Firefox 83.0 (64-bit)

> Assistive technology used to verify

Windows High Contrast Mode 
(Left Alt + Left Shift + PrtSc)

## Detailed description

> What version of the Carbon Design System are you using?

I used the website to test, Carbon Components React v7.24.0 at the time of this writing.
https://react.carbondesignsystem.com/?path=/story/ui-shell--side-nav-rail-w-header

My specific usage: 
```
<SideNav ...>
     <SideNavItems .../>
          <SideNavLink .../>
...
```

> What did you expect to happen?

When using the keyboard to tab to each of the menu items in the left side vertical menu, I expected some kind of visual indicator on which item was in focus.  A previous issue (https://github.com/carbon-design-system/carbon/issues/6897) reported this problem and was closed as fixed, but I am unable to verify the fix on the Carbon React live demo website.

> What happened instead?

When tabbing to the side navigation menu, the menu horizontally expands to show the icon with its corresponding label.  I expected to see the menu expand and see a focus indicator on the top most menu item.  Tabbing through the menu items also do not show a visual indicator on which item is in focus.

> What WCAG 2.1 checkpoint does the issue violate?

https://www.ibm.com/able/guidelines/ci162/focus_visible.html

## Additional information

On Edge, the focus visual indicator is the removal of the white border from the menu item.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes #7313 
Closes #7301 

This is a quick and dirty fix for the lack of focus state support in HCM when using Firefox. After some debugging with DA, it seems like Firefox's `prefers-contrast` overrides any type of custom colors when in HCM. Because of this, we were not seeing the same blue outline we would see on Windows Edge in HCM. To remedy this, I added media queries to the `focus-outline` mixin that will set the border/outline to be `dotted` instead of solid, which will offer _some_ affordance to the user when using a keyboard to navigate. Not a perfect solution, but until there is a better fix on the Firefox end, at least you will be able to tell which item currently has keyboard focus. 

#### Changelog

**New**

- Component specific media queries to alleviate any HCM issues in both Firefox and Edge

**Changed**

- `focus-outline` mixin now has a media query that only targets users on Windows 10 using Firefox with `prefers-contrast` to be enabled

**Removed**

- Extraneous HCM media queries

#### Testing / Reviewing

To test these changes, you'll need a Windows 10 machine and High Contrast Mode enabled (`Settings --> Ease of Access --> High Contrast Mode`)

To enable `prefers-contrast` in Firefox, type `about:config` in the address bar, search for `layout.css.prefers-contrast`, and set this to `true`

Verify focus is visible throughout the React Storybook for any component that is expected to receive focus. 

@dakahn I went through each component in both Firefox and Edge, so this _should_ address all outstanding HCM issues. Let me know if I missed any of them 👍

### CODE REVIEW

**Comment by tw15egan** [comment]
@kinueng This [link](https://deploy-preview-7314--carbon-components-react.netlify.app) has pending changes with this PR. Let me know if this fixes most of the issues you've been seeing in Firefox HCM 👍

**Comment by joshblack** [comment]
@tw15egan thanks for doing this! After the break, do you think you would have any time to talk about all the HCM fixes that are being done and explain what the process has been like? I feel like all of us could benefit from better understanding this stuff 👀

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]
Awesome! Hopefully Firefox recognizes system colors soon.

**Comment by tw15egan** [comment]
@joshblack yeah definitely!

**Pull request merged**
