### PR TITLE
feat: index styles package for platform

### PR DESCRIPTION
**Pull request by francinelucca**
Indexes @carbon/styles according to carbon-platform

- [x] index https://www.carbondesignsystem.com list components
- [x] Check spreadsheets and exported components to verify any other components we might want to index
- [x] Get missing thumbnails from design
- [x] Confirm tags with design
- [x] Confirm components' status

#### Changelog

**New**

- packages/styles/carbon.yml : indexed library and assets
- thumbnails/* : assets' thumbnails svg folder

#### Testing / Reviewing

See testing instructions over on: https://github.com/carbon-design-system/carbon-platform/pull/503

### CODE REVIEW

**Comment by francinelucca** [comment]
@mattrosno  this is ready for a preliminary review, I indexed the component list over on https://www.carbondesignsystem.com/ + `AspectRatio`, will take a look at the spreadsheet Josh provided and the exported react components tomorrow to see if we're missing anything. 

**Things to verify:**

  **Carbon Team**
    - Marked everything as stable, didn’t see any indication otherwise. Is this correct? Is there a particular webpage where I can see status?
  
  **Design (@jeanservaas, @kingtraceyj)**
    - I used ui-shell for ui-shell-left-panel and ui-shell-right-panel, should we have individual thumbnails for these? 
    - Need a thumbnail for aspectRatio 

  **Content (@aubrey-oneal)**
    - Used ‘input-control’ tag for multiselect component since couldn’t find a mapper, is this ok? https://www.carbondesignsystem.com/components/dropdown/usage/#multiselect
    - Used ‘content-element’ tag for aspectRatio component since couldn’t find a mapper, is this ok? https://react.carbondesignsystem.com/?path=/docs/components-aspectratio--aspect-ratio-story

**Comment by mattrosno** [comment]
@francinelucca I'd look at the folders here (https://github.com/carbon-design-system/carbon/tree/main/packages/styles/scss/components), and experimental section here (https://react.carbondesignsystem.com) to look for experimental components that aren't in Carbon website's side nav currently?

@francinelucca I'd also consider putting the thumbnails in `/packages/styles/thumbnails` directory or see what the system squad wants to do. They can live in the styles directory somewhere and still properly get inherited by the React library when we index that.

**Comment by francinelucca** [comment]
@mattrosno moved thumbnails to `/packages/styles/thumbnails` ✅

**Review by joshblack — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
🔥

**Pull request merged**
