### PR TITLE
Fix(data-table): table headers in table body

### LINKED ISSUE #2280: [Carbon 10: Data Table] Table heading in table body
## Detailed description

> Describe in detail the issue you're having.

`<th>` should be used within the table body to denote the row's heading but it's styling is odd.

> Is this issue related to a specific component?

Data Table

> What did you expect to happen? What happened instead? What would you like to see changed?

Table row heading should align with the rest of the cells. Often they don't visually look different from other cells but are semantically important for screen reader users

> What browser are you working in?

Chrome, FireFox, Safari

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library (PAL)

## Steps to reproduce the issue

1. Add a `th` as a cell within the `tbody`
2. View the table styles

## Screenshot
Screen Shot 2019-04-09 at 2 27 46 PM

### PR DESCRIPTION
**Pull request by vincentsnagg**
Closes #2280

Hello! This PR adds a styling fix for table headers used within the table body. The common use case (outlined in #2280) is that designating row headers is semantically important for accessibility / screen reader users.

Right now a `th` used within a table body row leads to some odd styling:

The proposed styling corrects this so that the accessible row headers look like the other cells:
Screen Shot 2019-06-21 at 4 54 28 PM

See the last demo called Row Header under https://deploy-preview-3150--the-carbon-components.netlify.com/?nav=data-table

#### Changelog

**Changed**

- Fixes styling when `th` is used within `tbody`

#### Testing / Reviewing

- [ ] Should be tested across all supporting browsers
- [ ] Should not affect any other styles / functionalities

### CODE REVIEW

**Comment by elizabethsjudd** [comment]
Per our conversation, I'd recommend scoping the current heading styles to the `thead` so we don't have accidental competing styles and use the ` > *` selector when you are styling a row and have to define both `th` and `td`.  They are the only allowed children of a `tr` so you are safe to use the global selectors.

**Review by asudoh — COMMENTED** [review]
LGTM 👍 at the glance, thank you for jumping in @vincentsnagg! Let's see what our designers think.

**Review by jnm2377 — APPROVED** [review]
This looks great! Thanks so much for contributing this! 🎉

**Review by shixiedesign — APPROVED** [review]
Styling appears correct! Thanks for making the fix 👍 !

**Review by tw15egan — APPROVED** [review]
👍

**Pull request merged**
