### PR TITLE
fix(Tabs):  fix the auto expanded of Tabs in mobile version

### LINKED ISSUE #867: Tabs in mobile version auto expanded
## Detailed description

> Is this issue related to a specific component? 
Tabs component

> What did you expect to happen? What happened instead? What would you like to see changed?
1.  I go to:
http://react.carbondesignsystem.com/?selectedKind=Tabs&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel

2.  Select Tab 1 by default.

3.  Select Tab 3.

4.  Narrow the browser so it is in mobile version.  The tabs become a dropdown list.
Note the list is auto-expanded.

I expect the list is collapsed at the beginning until I click on it.

> What browser are you working in? 
FF but same for other browsers.

> What version of the Carbon Design System are you using? 
    "carbon-components": "^8.18.3",
    "carbon-components-react": "^5.41.0",

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
console

(I don't seem to see any labels that I can choose)

### PR DESCRIPTION
**Pull request by rezak-otmani**
## Overview

Resolves #867

Where we click on a button, the state of the menu (`bx--tabs__nav`) changes (add or remouve the class `bx--tabs__nav--hidden`).
If we click on a button the state of the menu change, if the menu has a state hidden the state of the menu will be not hidden, so if we put the browser in mobile version the list will be displayed.

In this PR we modify the state of the menu only if we click in a button who is a child element of the menu, so only in the case of dropdown
By default the state of the menu is hidden so the list will not be displayed when we  put the browser in mobile version.

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
LGTM! Thanks for updating this.

I also noticed that the dropdown for this is using the old dropdown styles, I'll make a new issue to address that.

**Review by asudoh — COMMENTED** [review]
Thanks @rezak-otmani for jumping in! Though your fix sure seems to fix the specific issue, I see the cause of the problem is bigger - Basically duplicate code handling `keydown` event and `click` event at a glance. More investigation is required. [The change in this PR at the “closes dropdown upon selection” code](https://github.com/carbon-design-system/carbon-components/pull/934/files#diff-1c9a815164bf8abc0ef6d326c5b3d2fbR65) seems to work only given `keydown` handler changes the selection beforehand.

**Comment by rezak-otmani** [comment]
Hi @asudoh  thanks  for your feeback, it works in both cases even if we keep [This line](https://github.com/carbon-design-system/carbon-components/blob/bbf07a7a8dc0d505babe437bca53751ab0525576/src/components/tabs/tabs.js#L65), otherwise I do not really see the problem.

**Comment by tw15egan** [comment]
Definitely fixes the problem, I guess I am just a little unsure of what else @asudoh would like to see changed in this PR. 

Perhaps it could be in a separate PR, as I am seeing some other problems with the dropdown functionality itself, i.e I am unable to select a dropdown item with my keyboard

**Comment by asudoh** [comment]
Sorry for not being clearer. My concern stems from the specific change at https://github.com/rezak-otmani/carbon-components/blob/a8f9988/src/components/tabs/tabs.js#L65 - The line was for detecting if user is acting on one of the dropdown item and closing the dropdown if so. Making it handle only for selected one will kill the logic - Though the logic seems to have stopped working some while ago as @tw15egan found. A change killing a logic for the sake of a bug in another area should take care of ensuring that the logic being killed is properly handled by some other logic, and requires root cause analysis wrt why the logic being killed caused the problem. Also the logic being killed signals that we have to see if it should be cleaned up. Hope this makes sense to everybody.

**Comment by asudoh** [comment]
Further investigation revealed that the issue stems from clicking on tab item toggling the menu for mobile mode (which @rezak-otmani may have found). Given clicking on tab (menu item in mobile mode) item should close the menu instead of toggling (toggling was used there assuming that the menu is open when user clicks on the menu item), forcing the menu to be closed in such case solves the problem.

**Pull request closed without merging**
