### PR TITLE
fix(Notifications): add hcm media query for missing outlines

### LINKED ISSUE #6872: Accordion chevron inaccessible in Windows High Contrast Mode
## Environment

> Operating system

Windows 10 latest

> Browser

Edge, Firefox

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

While using Windows High Contrast Mode the chevron icons have issues in both browsers

Edge
image

Firefox
image

### PR DESCRIPTION
**Pull request by dakahn**
Closes #6872 

#### Changelog

- added media queries for Windows High Contrast Mode that set an outline width and style

#### Testing / Reviewing

In Windows High Contrast Mode you the borders for both notifications variants should be clearly visible.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
image

image

the outer outline now appears in high contrast mode. is the correct issue being referenced in the PR description? the ticket and the name of your feature branch reference accordion instead of notifications

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
I believe this is the correct issue: https://github.com/carbon-design-system/carbon/issues/7562

**Comment by dakahn** [comment]
Yeah, that's my bad. Just typed what I was looking at instead of what I should have been referencing 😓

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
