### PR TITLE
fix(MultiSelect): add filter tag class to <ListBoxSelection />

### LINKED ISSUE #2918: MultiSelect clear button interactive styles
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

As a mostly keyboard-only user, when I tab through the MultiSelect component, the clear selections button does not have sufficient focus (or even hover) style differences to make it clear that holds the keyboard focus.

> Is this issue related to a specific component?

Yes, the `MultiSelect`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I think it would improve the usability of this component to provide better focus and hover styles to the clear selections button.  

> What version of the Carbon Design System are you using?

10.x

## Additional information
Tabbing through `MultiSelect`
Kapture 2019-06-04 at 8 56 05

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2918

This PR adds filter tag classes to the listbox selection component in order to indicate interactivity

related #2360 #2654 

#### Changelog

**Changed**

- incorporate changes from #2360 and #2654 in listbox

#### Testing / Reviewing

Ensure the listbox selection is highlighted properly when focused

### CODE REVIEW

**Review by dakahn — CHANGES_REQUESTED** [review]
2019-06-05 15_50_02-Carbon Components React - Firefox Developer Edition

We should bump up the contrast on that focused closed button. Testing shows a contrast of 2.4:1 which is just shy of the 3:1 contrast target for user interface components against adjacent colors according to WCAG 2.1, 1.4.11

Can we use a brighter token here?
2019-06-05 17_01_34-Colour Contrast Analyser (CCA)

**Comment by emyarod** [comment]
cc @carbon-design-system/design

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by shixiedesign** [comment]
@dakahn We've never actually made hover states of controls pass. Hover states changes of controls (eg. checkbox, radio, tag) are supplementary, and the main visual indicator is the pointing-hand cursor. 

So I think this is okay. @emyarod  Though actually, to stick to the system, the background color of the close icon should not be `#565656`, but `#4C4C4C`, our `$hover-secondary` token: 
https://carbon-elements.netlify.com/themes/examples/preview/#hoverSecondary

**Comment by dakahn** [comment]
@shixiedesign It's not exclusively a hover-state. It's a focus state as well. If I focus that element with my keyboard the _only visual indication of focus_ is a (now with #4c4c4c) 2:1 contrast circle behind the x icon.

**That's an AVT 2 failure** 🙅‍♂

**Comment by aagonzales** [comment]
The style being shown above is used for `hover` not `focus`. Focus in our system are always outlines, 2px borders. 

I'd recommend using the `$inverse-01` token instead of the normal `$focus` color token since this is a high-contrast moment. 

image

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Looks good following design's comments 👍

**Review by shixiedesign — COMMENTED** [review]
Focus outline looks good! Hover state color however is still `#565656`. Should be `#4c4c4c`
image

**Review by dakahn — APPROVED** [review]

**Review by joshblack — CHANGES_REQUESTED** [review]
From @shixiedesign https://github.com/carbon-design-system/carbon/pull/2936#pullrequestreview-247787950

**Review by shixiedesign — APPROVED** [review]
Thank you! Looks great now :)

**Pull request merged**
