### PR TITLE
feat(react): add support for rollup in bundles

### PR DESCRIPTION
**Pull request by joshblack**
Add in support for creating ESM, CommonJS, and UMD bundles through a single rollup config. This change also keeps support for importing files directing to maintain backwards-compatibility. As a result, these changes generate (or maintain) the following bundles with rollup:

- `es/index.js`
- `lib/index.js`
- `umd/carbon-components-react.js`
- `umd/carbon-components-react.min.js`

#### Changelog

**New**

**Changed**

- Update `carbon-components-react` to use rollup for bundling ESM, CommonJS, and UMD

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
FYI @vpicone

**Comment by vpicone** [comment]
@joshblack nice! When messing around with typescript this seemed like a pretty necessary move.

**Comment by abbeyhrt** [comment]
@joshblack Could you go over the rollup config stuff with me? Config files are a complete mystery to me

**Review by abbeyhrt — CHANGES_REQUESTED** [review]
hey I noticed that the prop-types are still being included, is that supposed to happen?

**Comment by joshblack** [comment]
@abbeyhrt updated! Thanks for the catch

**Review by abbeyhrt — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Pull request merged**
