### PR TITLE
feat(IdPrefix): add component, docs, tests

### LINKED ISSUE #12378: [Bug]: Duplicate ids between AccordionItem and Footer
### Package

@carbon/react, carbon-components-react

### Browser

Chrome, Firefox

### Package version

@carbon/react@1.39.0, carbon-components-react@8.15.0

### React version

17.0.2

### Description

Using AccordionItem from `carbon-components-react` with a Footer element from `@carbon/react` on the same page leads to duplicate ids such as `accordion-item-1`.

Looks like [useId](https://github.com/carbon-design-system/carbon/blob/main/packages/react/src/components/Accordion/AccordionItem.js#L35) somehow does not have the same context between the libs? Can you expose the id prefix string as an optional prop?
Or is there a fix we can do on our side regarding the usage of AccordionItem?

This also shows up as an accessibility violation.
image

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Reproduction/example

https://codesandbox.io/s/rough-grass-o4drs0?file=/src/App.js

### Steps to reproduce

1. Navigate to [minimal example](https://o4drs0.sse.codesandbox.io/).
2. Open DevTools and search for `#accordion-item-1` in the elements tab.

#### Alternatively
1. Navigate to [live usage with async accordion items](https://ibm.com/docs/en/search/whatever).
2. 2. Open DevTools and search for `#accordion-item-11` in the elements tab.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #12378 

Adds a new component and hook to enable consumers to prefix the autogenerated IDs placed on certain DOM elements

#### Changelog

**New**

- add `IdPrefix`, related docs and tests

#### Testing / Reviewing

- Ensure `IdPrefix` is exported
- Ensure the new stories for IdPrefix work and make sense

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I'm not seeing this in storybook? 👀

**Comment by tay1orjones** [comment]
@alisonjoseph whoops - forgot to push up some changes 😅 Should be fixed now!

**Review by alisonjoseph — APPROVED** [review]
This LGTM, do we need to index this for Platform?

**Review by aledavila — APPROVED** [review]

**Comment by tay1orjones** [comment]
> This LGTM, do we need to index this for Platform?

@alisonjoseph We could, but we currently don't index it's sibling component/hook `ClassPrefix`, or `usePrefix`.

**Pull request merged**
