### PR TITLE
fix(Toggle): disabled color tokens

### LINKED ISSUE #9750: [Toggle] Text when Disabled does not provide enough contrast and is difficult to read
## Environment

All browsers

## Detailed description

Latest version of Carbon. We notice the colors chosen for when the Toggle component is disabled doesn't provide enough contrast to read the text. Furthermore, in our product specifically (SOAR Playbook Designer), we use Gray-90 as the background for the Toggle, and when disabled, the Toggle SVG's background matches the same color and isn't discernible.

> What WCAG 2.1 checkpoint does the issue violate?

Text contrast. Although disabled buttons are exempt from contrast requirements, we think it would still be beneficial to provide clearer contrast in these cases.

## Additional information

Example in product (SOAR Playbook Designer) Gray-90 background:
image

Example in Storybook, white background:
image

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #9750 

#### Changelog

- updates disabled color tokens which had a visual regression:
    - color tokens were fixed in this PR: https://github.com/carbon-design-system/carbon/pull/8514/files
    - but this change was reverted (bc they used v11 tokens) in this PR: https://github.com/carbon-design-system/carbon/pull/9067 however, the v10 tokens used don't align with the v11 tokens it was supposed to be
    - updates v10 tokens based on the color token migration table 

Screen Shot 2021-11-05 at 11 25 36 AM

#### Testing / Reviewing

- open v10 react deploy preview > test toggle playground story > check disabled > check that it works for all themes 
_note for dev reviewers: the v11 styles package is using the correct v11 tokens, so no need to update there_

### CODE REVIEW

**Comment by abbeyhrt** [comment]
@jnm2377 Do you happen to have a screenshot of what the toggle should look like now with the new tokens?

**Comment by jnm2377** [comment]
@abbeyhrt oh, there's a picture included in the old issue that was originally fixed: https://github.com/carbon-design-system/carbon/issues/6794#issuecomment-826968042

**Review by abbeyhrt — APPROVED** [review]
Thank you! Looks good to me!

**Review by aagonzales — APPROVED** [review]
woo-hoo! You figured it out!

**Review by dakahn — APPROVED** [review]
Nice work

**Pull request merged**
