### PR TITLE
test: add jest for testing styles

### PR DESCRIPTION
**Pull request by joshblack**
Just a quick change! Adds in Jest, although I'm sure it can be re-written in mocha if we want 😄 Wanted to bring this over from the add-ons repo as it is a strategy that's been pretty helpful there.

The thought process here is that we can use `glob` to find all `.scss` files in our project. We use those in Jest's table driven test setup to verify that every `scss` file that we export can compile by itself. This is useful for verifying that folks can directly import any part of our setup without encountering a compile-time error from `node-sass`.

Looking forward, it'd be nice if we could add file sizes as-well in order to catch any kind of regressions or mishaps when it comes to duplicating imports.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thank you for looking at this area @joshblack! LGTM 👍 once the test passes.

**Comment by joshblack** [comment]
~Have you seen `node-sass` fail like this before in TravisCI? Will try and debug and see what's going on.~ Got it!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thank you for making the test file location update @joshblack!

**Review by alisonjoseph — APPROVED** [review]
Thanks for adding this, LGTM!

**Pull request merged**
