### PR TITLE
docs(FormItem): remove FormItem story

### LINKED ISSUE #4573: [FormItem]: FormItem story issues
The FormItem story incorrectly uses the component to wrap a `NumberInput` which already has a FormItem wrapper. The 'documentation' is also non-existent and doesn't explain how the component is actually meant to be used.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes #4573 

`FormItem` story was not much help and was showing an incorrect example. It can possibly be added back in based on the outcome of https://github.com/carbon-design-system/carbon/issues/5367 when we go through and standardize default spacing on components. 

#### Changelog

**Removed**

- `FormItem` story

#### Testing / Reviewing

Make sure `FormItem` story does not show up in the storybook

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
maybe we can change the story to wrap a different component that doesn't have the form item wrapper? until we decide how we want to standardize component spacing for v11

**Comment by tw15egan** [comment]
@emyarod sounds good, I can update the PR to wrap `TextInput` instead

**Comment by tw15egan** [comment]
@emyarod actually it seems like all of our form elements are already wrapped in `FormItem`, so I think surfacing this may cause more confusion. 

Screen Shot 2020-02-19 at 10 42 01 AM

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by abbeyhrt — APPROVED** [review]
🎉

**Review by joshblack — APPROVED** [review]

**Pull request merged**
