### PR TITLE
feat(CodeSnippet): add scroll overflow indicators

### PR DESCRIPTION
**Pull request by emyarod**
part of #7159

This PR implements scroll overflow indicators to the single line and multiline code snippets

#### Changelog

**New**

- overflow scroll indicators

#### Testing / Reviewing

Confirm that the overflow indicators appear on the correct sides only when scroll is possible

### CODE REVIEW

**Comment by tw15egan** [comment]
Confirmed by running locally since the gradients don't render properly with css variables

Screen Shot 2020-11-09 at 1 03 30 PM
Screen Shot 2020-11-09 at 1 01 31 PM
Screen Shot 2020-11-09 at 1 00 52 PM

**Review by tw15egan — APPROVED** [review]
LGTM once the tokens are finalized 👍 ✅

**Comment by emyarod** [comment]
the gradients should be rendering correctly with CSS variables, are you seeing otherwise? I am using the method I used for overflow tabs which gets around previous gradient issues we had with CSS variables

**Comment by tw15egan** [comment]
@emyarod this is what I'm seeing in deploy preview: 

Screen Shot 2020-11-09 at 1 35 24 PM


I thought we had the same issue with Modal // Has scrolling content 

I thought this was just a storybook implementation issue but should work when using css variables in prod, so not a big deal just odd that it's not rendering for me 🤔 

Screen Shot 2020-11-09 at 1 36 35 PM

**Comment by tw15egan** [comment]
I thought this was just a storybook implementation issue but should work when using css variables in prod

**Comment by emyarod** [comment]
here are the deploy previews on my end on multiple platforms and browsers

image

image

modal (https://github.com/carbon-design-system/carbon/issues/6539) still has the issue because it isn't using the method I tried with tabs (and now this) so I will be backporting it to modal. storybook uses css variables under the hood, so for modal it will be broken in prod as well

my guess is for your single line deploy preview screenshot the fade area is probably not large enough to be visible, but it's there (so it would just be a style adjustment)

**Review by aledavila — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- When the text has the horizontal overflow with gradient and applying focus. The focus needs to be on top of the gradient, not underneath it
Screen Shot 2020-11-11 at 12 20 09 PM

- I can not get the gradient fade style when using Safari. It looks good in Firefox and Chrome though.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- The scroll fade gradient doesn't go all the way to the edge on either side of the code snippet area. It should be right next to the edges so the white text is still underneath the gradient.

Screen Shot 2020-11-12 at 11 56 49 AM


- I still can't get the fade gradient style to show up in Safari.

**Comment by emyarod** [comment]
the fade effects will not appear in Safari due to a browser bug (related https://github.com/carbon-design-system/carbon/issues/6539)

**Review by laurenmrice — APPROVED** [review]
Looks wonderful! Thank you 🙌🏻

**Pull request merged**
