### PR TITLE
fix(notification): remove height and width set on close icon, update vanilla close icon size

### LINKED ISSUE #4436: [notification] close icon should be 20px
The close icon should be 20px not 16px.

Specs:

Ref: #4330 . this bug needs to be fixed before theming

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4436 

Styles were shrinking the size of the close icon.

#### Changelog

**Changed**

- update size of vanilla notification close icon
- updated flex rules for `InlineNotification` so items are not `justify-content: space-between`

**Removed**

- remove height & width (1rem) being set on the close icons in both `ToastNotification` & `InlineNotification`

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! Thank you @jendowns !

**Review by emyarod — APPROVED** [review]
looks good to me, pending design review

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Vanilla
- The close icons need to be 20px still for both toast and inline notifications.

React
- Seems like something happened with the length of toast and inline notification and the placement of the action button. This is a screenshot of what’s currently in react and this prs react. The lengths should not have changed. 
Artboard


- The close icon on toast notifications needs to be 16px from the top to be inline with the notification title text, right now it is too high.
sw

**Comment by jendowns** [comment]
Hey @laurenmrice thanks for your notes --

### About the long notifications

OH haha, I didn't do that 😅 You can see it happening in all of the other PR deployments as well. For example:
* https://deploy-preview-4441--carbon-components-react.netlify.com/?path=/story/notifications--inline
* https://deploy-preview-4450--carbon-components-react.netlify.com/?path=/story/notifications--inline

I did a little digging into what is causing this -- in the deployments for PRs, which are more up-to-date than what you see in the http://react.carbondesignsystem.com storybook envrionment, there's an extra style rule getting added to a `div` that wraps all stories: `width: 100%`.

It's causing the problem here 😬 Looks like it was added in this PR: https://github.com/carbon-design-system/carbon/pull/4320

IMO the best thing to do in this case would be to open a new issue? It looks like that `width: 100%` was added for a specific reason so working around it or reverting it would require a little context. (@emyarod do you have any thoughts?)

### About the icon + text alignment

I just pushed an update that fixes that! Could you take another look when the deployment finishes?

### Vanilla component

Just updated the close icon size for the vanilla notification as well 👍

**Comment by jendowns** [comment]
@laurenmrice @emyarod 

Actually I had an idea to fix the stretched out notifications, so I opened a PR here: https://github.com/carbon-design-system/carbon/pull/4458

(I thought it might be better to keep the change separate since it's a different type of code change -- to the storybook, in this case. 🤔)

**Comment by emyarod** [comment]
the context can be found in the referenced PR (#4320). storybook injects a div within our flex container which causes it to fit to the content rather than be full width (which it should be by default). the spacing in the notification is caused by the `justify-content: space-between` rule on the notifications

even though modifying that width rule would revert the story appearance to how it looked previously, I think it would be misrepresenting how the component would actually look

**Comment by jendowns** [comment]
@emyarod Thank you, that's a good point! I'm going to close out #4458 then.

**Comment by jendowns** [comment]
Thanks for the heads up on `justify-content: space-between` -- just removed that & added `flex-grow: 1` to the details in the `InlineNotification`, so that should address the root cause. 😅

**Comment by laurenmrice** [comment]
@jendowns Awesome thanks for making that seperate pr to fix the width problem! 🙌

Close icons are all correct size and align with type now. I did notice that the icons for success, error, and warning are not aligning and are too low. Do you want me to file a bug for that and make a pr separately?

**Review by vpicone — APPROVED** [review]

**Comment by jendowns** [comment]
Thanks @laurenmrice!

I just pushed a commit that reduces the top margin on that status icon in `ToastNotification`s, so now it looks like this:

Screen Shot 2019-10-25 at 10 18 06 AM

For `InlineNotification`s' status icon, I didn't make any margin update because it looks good as-is? Do you agree? Here's a screenshot of what I'm looking at:
Screen Shot 2019-10-25 at 10 46 41 AM

**Review by laurenmrice — APPROVED** [review]
Yes they are aligned now ! thank you !👍

**Pull request merged**
