### PR TITLE
Fixed accessibility in Operational Tag

### LINKED ISSUE #17108: [a11y]: Interactive Tag - Operational - Open /Close status of the Tag controls not conveyed
### Package

@carbon/react

### Browser

_No response_

### Operating System

_No response_

### Package version

v11.62.2

### React version

18.02

### Automated testing tool and ruleset

Manual QA

### Assistive technology

VO & JAWS

### Description

Tag content Button in Interactive Tags acting as Expand /Collapse panels , However the Opened /Closed status of these Controls are not conveyed to screen reader users.

### Recommended Fix
Open /Closed status of these controls expected to convey to screen reader users by using ARIA Expand /Collapse properties  accordingly.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/experimental-unstable-interactivetag--operational

### Steps to reproduce

none

### Suggested Severity

None

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by guidari**
Closes #17108

After talking with Raghu and Lauren about accessibility in the operational Tag we decided to remove the `ToggleTip` example and keep only two `Popover` examples, one using the `highContrast` prop and the other not.

#### Changelog

**Changed**

- Removed `ToggleTip` example to add `Popover` with `highContrast`

#### Testing / Reviewing

- Check if the example workd as expected

### CODE REVIEW

**Comment by Gururajj77** [comment]
Hey @guidari , not able to find any story with the name Operational in the deploy preview, am I looking at the wrong thing??

**Comment by guidari** [comment]
> Hey @guidari , not able to find any story with the name Operational in the deploy preview, am I looking at the wrong thing??


Hey @Gururajj77 , here it is the [deploy preview](https://deploy-preview-17131--v11-carbon-react.netlify.app/?path=/story/experimental-unstable-interactivetag--operational) to the Operational Tag.

**Review by Gururajj77 — APPROVED** [review]
Looks good!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by laurenmrice — APPROVED** [review]
Looks good to me! ⭐️

**Pull request merged**
