### PR TITLE
fix(progress-indicator): apply support-01 to warning icon inner paths

### LINKED ISSUE #5815: [progress indicator] inner fill of validation icon needs correct color
The top line in the alert icon needs to be getting the `support-01` color like the rest of the icon.
Screen Shot 2020-04-06 at 2 54 38 PM

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5815

This PR applies support-01 fill to all inner paths in the progress indicator step warning SVG

#### Testing / Reviewing

Confirm that the warning icon is correct in all themes for the progress indicator

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Review by laurenmrice — APPROVED** [review]
looks great ! thanks 🙌🏻

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by asudoh** [comment]
@emyarod thinks this is ready to merge - Thanks @emyarod!

**Pull request merged**
