### PR TITLE
fix(combo-box): use inherited text input styles

### LINKED ISSUE #6528: [ComboBox]: Incorrect placeholder text color
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When I use a ComboBox with placeholder text, I see that the color of the placeholder text does not have the same color as TextField and TextArea placeholders.

Google Chrome

carbon-components-react 7.16.0

## Steps to reproduce the issue

1. See codesandbox: https://codesandbox.io/s/intelligent-vaughan-txqml?file=/src/index.js

## Additional information

Screen Shot 2020-07-23 at 10 17 22 AM

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6528

This PR removes the combobox placeholder text styles so that it uses the correct text input styles

#### Testing / Reviewing

Confirm the combobox enabled and disabled placeholder text is using the correct tokens

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
For some reason in Firefox the enabled state for combobox looks disabled. it looks correct in Safari and Chrome.

Artboard

**Comment by emyarod** [comment]
@laurenmrice does that mean the placeholder color is wrong in the enabled TextInput?

**Comment by laurenmrice** [comment]
Yes the enabled state with placeholder text for combobox should reflect `text-03`. It is doing so in Safari and Chrome but Firefox looks different for some reason as if it is disabled.

**Comment by emyarod** [comment]
ok that isn't a regression in this PR but I can make that change here as well

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by laurenmrice — APPROVED** [review]
looks great! 🙌🏻

**Review by andreancardona — APPROVED** [review]
@emyarod lgtm!! :)

**Pull request merged**
