### PR TITLE
fix(Dropdown): announce dropdown item position

### LINKED ISSUE #4373: AVT 3 Dropdown - VO does not announce the option after it is selected or the options position in the list..
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon v10 - React

## Detailed Description
Go to the React Component 
Start VO on macOS
1. Tab to the Dropdown, VO announces that it Open Menu pop-up 1 of 1.
**Expected Result** - VO announces the label "Option 1" and that it is a pop-up button.
2. Use the Enter key to open the dropdown and move to the next option. VO announces the option, but does not announce the position (i.e. 1 of 4, 2 of 4, etc).
**Expected Result**  - VO announces the Option # and position. 
3. Tab away from the dropdown and then tab back. VO announces, "Open Menu pop-up".
**Expected Result**- VO announces the that it is a menu pop-up and the current selection. 

See [ARIA Authoring Practices Dropdown Listbox example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/listbox/listbox-collapsible.html).

### PR DESCRIPTION
**Pull request by asudoh**
This change lets Downshift announce the position of dropdown item in
addition to its content, when it's highlighted.

Fixes #4373.

#### Changelog

**New**

- `getA11yStatusMessage` prop to `<Downshift>`, so that Downshift announce the position of dropdown item in addition to its content, when it's highlighted.

#### Testing / Reviewing

Testing should make sure `<ComboBox>`, `<Dropdown>` and `<MultiSelect>` are not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, VO properly announces item position

image

**Comment by joshblack** [comment]
I think we'll need to go down an alternate route for this component. Most likely the markup is not correct and that is what is causing the screen reader issues. Features like announcement position in a listbox is a screen reader feature that is computed by the underlying markup. Instead of tying this feature to VO-specific text, we should address the underlying markup issues which will in turn address the parent issue 👍

**Comment by asudoh** [comment]
While automatic way for screen reader to understand our markup structure may be desirable as above comment says, Downshift explicitly takes "announcer" pattern, presumably for de-touching actual keyboard focus visual keyboard focus. So going away from "announcer" pattern is not realistic, at least for now.

**Comment by joshblack** [comment]
Not sure I understand, could you share more? In particular where the ideal markup is unable to be implemented given Downshift and its intended usage.

**Comment by asudoh** [comment]
It's not about ideal markup not implementable. It's about such ideal markup won't come into play with how contents are announced by screen reader with Downshift, given Downshift takes "announcer" pattern (similar to https://www.thinkcompany.com/2017/09/introducing-the-react-a11y-announcer/).

**Comment by joshblack** [comment]
@asudoh got it! Don't think it clicked that Downshift was using an `aria-live` region under the hood, thanks for being patient!

**Comment by dakahn** [comment]
Testing both NVDA and JAWS 2019 on Windows 10 and we've got problems. I'll open separate issues for these and wont block this PR, but **the menu is navigable, but no menu items or selected options are announced whatsoever**. Will need to research into Downshift and see if there's any existing bugs 🤷‍♂ 

_As a reminder our target is JAWS 2019 on Firefox/Chrome/Edge on Windows 10 and VoiceOver on Safari for macOS as well as (although not a requirement) NVDA on Firefox for Windows 10 and any updates adding bug fixes/improvements/enhancements for one screen reader should be tested on all, on all platforms, on all browsers 👍 ._

**Comment by aledavila** [comment]
Closing in favor of #5373 
Updating downshift and the new implementation targets fixing both VO and JAWS/NVDA

**Pull request closed without merging**
