### PR TITLE
fix(button): center icon inside danger ghost icon only buttons

### LINKED ISSUE #16841: [Bug]: the icon inside `IconButton`  with `kind` prop `danger--ghost` is not aligned to center
### Package

@carbon/react

### Browser

_No response_

### Package version

v11.60.1

### React version

v18

### Description

The icon inside the `IconButton` is not center aligned when the `danger--ghost` is used with `kind` prop

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-button--icon-button&args=kind:danger--ghost;tooltipAlignment:center;tooltipPosition:bottom

### Steps to reproduce

Go to the above storybook link and hover on the `IconButton`.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by AliAldobyan**
Closes #16841

The icon inside the IconButton is not center aligned when the danger--ghost is used with kind prop

#### Changelog

**Removed**

- removed "padding-inline-end" in _button.scss file line 286

#### Testing / Reviewing

1- Go to react storybook.
2- Click on Button Component.
3- Choose Icon Button.
4- Choose danger--ghost as the button kind.

Recording is attached.

https://github.com/carbon-design-system/carbon/assets/17975825/305c55b8-5ef9-49b7-9eb7-0e565d1892b9

### CODE REVIEW

**Comment by AliAldobyan** [comment]
recheck

**Comment by AliAldobyan** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Hey thanks for taking a look at this! 

Removing this style causes the button to inherit the padding styling from the general button styles, which does not match [the spec](https://carbondesignsystem.com/components/button/style#ghost-button). Ghost buttons should not have additional padding like the other buttons.

This PR:
2024-07-08 at 13 19 57-MAIN-Google Chrome@2x

What's correct in prod right now:
2024-07-08 at 13 19 41-MAIN-Google Chrome@2x

You'll need to target a different selector to apply the proper modifications necessary. It could go after this selector in the icon-only styling block

https://github.com/carbon-design-system/carbon/blob/c8b452afa8f100df491ae2f88c9cee88595651e8/packages/styles/scss/components/button/_button.scss#L173-L176

**Comment by AliAldobyan** [comment]
Thank you @tay1orjones for you review, I have applied the modifications by adding `&.#{$prefix}--btn--danger--ghost {
      padding-inline-end: calc(
        layout.density('padding-inline') - convert.to-rem(16px)
      );
    }`

**Comment by AliAldobyan** [comment]
Hello @tay1orjones  @alisonjoseph , Can you review the latest update please.

Regards.

**Review by tay1orjones — CHANGES_REQUESTED** [review]
There is a slight upward pixel shift of the vertical icon alignment when comparing with the primary kind

https://github.com/user-attachments/assets/241f64ee-8160-4fda-a87f-e4ea375809b2

**Comment by AliAldobyan** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by AliAldobyan** [comment]
> There is a slight upward pixel shift of the vertical icon alignment when comparing with the primary kind
> 
>  2024-08-12.at.14.20.10-MAIN-Google.Chrome.mp4

There is a slight upward pixel shift of the vertical icon alignment when comparing with the primary kind has been fixed.


https://github.com/user-attachments/assets/367b49db-411b-4f49-8284-046e916a22e6

**Review by tay1orjones — APPROVED** [review]
Looks great! Sorry for the delay in review

**Review by kennylam — APPROVED** [review]

**Pull request merged**
