### PR TITLE
fix(button): use hover-primary-text for ghost button hover

### LINKED ISSUE #3386: [Ghost button] Incorrect text color on hover/active
The text color on hover should be `hover-primary-text` right now its a blue 60.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3386

NOTE: I went ahead and changed the color of the icons on hover as well, because it seemed like it should match the text 🤔 But let me know if you'd like me to change it back

#### Changelog

**Changed**

- ghost button hover text color now `$hover-primary-text`
- ghost button hover icon fill color now `$hover-primary-text`

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! I think we need a visual review to make sure confirm the colors are good though

**Review by laurenmrice — CHANGES_REQUESTED** [review]
The new color changes look correct! And yes the icon should be the same color as well good call.

For Ghost Button (Field) in vanilla and react there is too much padding to the right of the button (should be 16px and not 64px). Not sure why this is happening only for this size, all of the other ghost buttons look correct. 
Screen Shot 2019-07-15 at 12 07 20 PM

**Comment by jendowns** [comment]
Thank you @laurenmrice! So I believe the issue you identified with the field padding is fixed in this PR: https://github.com/carbon-design-system/carbon/pull/3364

(For this PR, I only changed the hover text and icon fill colors)

**Review by laurenmrice — APPROVED** [review]
got it! alright well color change looks good for this pr 👍

**Pull request merged**
