### PR TITLE
Add useid hook

### LINKED ISSUE #4675: Normalize unique id behavior across components
Some components need to generate a unique ID for private a11y concerns. We could use a hook to keep the behavior consistent across components.

### PR DESCRIPTION
**Pull request by vpicone**
closes #4675

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
is this meant to be a duplicate of https://github.com/carbon-design-system/carbon/blob/master/packages/react-hooks/src/useId.js inside the `react` package?

**Comment by vpicone** [comment]
@emyarod yeah the only difference is the signature and removing the hyphen. If we were to use this in components (like `CodeSnippet`) that use our id helper there's no `-` between the prefix and number so it'd technically change the snapshot a bit.

Also after thinking about it I'm not sure why that package exists, we can just publish the hooks from our react package. I wanted to use this PR to discuss moving the hooks were using to be alongside our other internal tools in this package. Planning to wait for @joshblack to get back to discuss further.

**Comment by joshblack** [comment]
Would we want to just bring in the hooks package? Don't have to export all of them. The package existed as a sandbox for hooks initially since folks weren't sure about what would go in there. I think we could offer a ton of helpers in there that we ourselves could use or that could be helpful in product/on the website.

**Comment by vpicone** [comment]
@joshblack going to defer to systems here, might be worth digging into generating truly unique ids rather than relying on some an imperative/global counter and manual prefixes.

**Comment by joshblack** [comment]
@vpicone any reason? Seems like it'd run into the same issue as the counter approach with respect to concurrent mode

**Comment by vpicone** [comment]
@joshblack i think a random number combined with a hash of the content/prefix would be more reliable than trying to orchestrate a global counter per component.  

The global incrementor also assumes there’s just one application on the page, which might not always.

**Comment by joshblack** [comment]
@vpicone totally fair about potentially having multiple of this kind of strategy and how that can cause issues 👍 Might make sense to seed the module on first initialize to help remedy this.

One thing I'm not quite sure of is how the hash approach would be simpler and more effective than the global counter, we could definitely try and generate a quasi-uuid if we want, but it seems equally effective to use the counter. Would love to see an example to wrap my head around this if you have a sec 👀 

Definitely agreed that if we have multiple "counters" that it'd conflict, one response may be to use a custom prefix but even that could lead to collisions. Maybe something like:

```js
// useId.js
import { useRef } from 'react';

const seed = Math.random().toString(36).substring(2, 13);
let id = 0;

function useId(prefix) {
  const { current } = useRef(++id);
  if (prefix) {
    return `${prefix}-${current}-${seed}`;
  }
  return `id-${current}-${seed}`;
}
```

**Pull request closed without merging**
