### PR TITLE
fix(components): update get-token-value helper to error out at end of loop

### PR DESCRIPTION
**Pull request by joshblack**
This fixes an issue consumers were having with 10.11.0 where `get-token-value` was error'ing out. It seems like the `@error` block was included in the `@each` block which causes it to throw if the theme was not the first match. This PR moves the `@error` call out of this loop such that if nothing is returned by the loop it throws. This also cleans up the error messages to be more detailed.

#### Changelog

**New**

**Changed**

- Update `_component-tokens.scss` to account for matching on the theme across all iterations

**Removed**

#### Testing / Reviewing

- Switch the default theme in our environment to something other than `$carbon--theme--white` and verify that it runs

### CODE REVIEW

**Review by vpicone — APPROVED** [review]

**Comment by joshblack** [comment]
Quick question @laurenmrice, for tags what should we do if someone has written a custom theme? Would there be a good set of fallback colors we could use?

**Review by tw15egan — APPROVED** [review]
Working as expected 👍 ✅

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Comment by aagonzales** [comment]
@joshblack What can we do with tags for theming? I always just assumed they would have to override the colors. Creating tokens for each tag color seems excessive.

**Comment by joshblack** [comment]
Chatted with @aagonzales real quick on Slack and she said that fallback colors should come from the white theme 👍 

We might need to do two additional things for custom theme support:

- Instead of doing a direct comparison for `$carbon--theme == $carbon--theme--g100` we should try and see if `$carbon--theme--g100` is a subset of `$carbon--theme`
- Add a fallback instead of error'ing out if no value is found

**Comment by joshblack** [comment]
Note to reviewers @asudoh @tw15egan @vpicone just added in some tests for the custom theme use-case and a new structure to handle the fallback situation shared above. 

Let me know if you have any feedback or questions!

**Pull request merged**
