### PR TITLE
chore(styles): deprecate misc features for v10

### PR DESCRIPTION
**Pull request by asudoh**
Refs #1626.

#### Changelog

**New**

- `_deprecate.scss` file to contain only `@mixin deprecate` - Having it in `_helper-mixin.scss` has caused import loop.
- `@deprecated` annotations for several variables/mixins/functions
- Deprecate message for deprecated mixins

#### Testing / Reviewing

Testing should make sure no component is broken.

### CODE REVIEW

**Comment by asudoh** [comment]
Questions primary for @joshblack:

* Does `carbon-elements` have "type reset" feature? (e.g. Applying `.bx--type-alpha` to `<h1>`)
* Does `cabron-elements` have a corresponding function to [`@function padding()`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_layout.scss#L27-L33)?
* Does `cabron-elements` have a corresponding feature to [`@mixin grid-container`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_layout.scss#L77-L86)?
* Does `cabron-elements` have a corresponding feature to [`@mixin font-smoothing`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_typography.scss#L72-L75)?
* Does `cabron-elements` have a corresponding feature to [`@mixin letter-spacing`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_typography.scss#L77-L79)?
* How do we want to handle [color reset for `<body>` found in `_css--body.scss`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_css--body.scss#L17-L18) in `v10`?
* Is `carbon--spacing()` is the right migration path for [`$spacing-*`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_spacing.scss#L41-L50)/[`$layout-*`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_spacing.scss#L52-L58)?

Thanks!

**Comment by joshblack** [comment]
> Does `carbon-elements` have "type reset" feature? (e.g. Applying `.bx--type-alpha` to `<h1>`)

Not currently, wasn't sure what we wanted to map over to the different headings. cc @jeanservaas do you think we should do this by default?

> Does `cabron-elements` have a corresponding function to [`@function padding()`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_layout.scss#L27-L33)?

No, this is no longer applicable to the new grid work.

> Does `cabron-elements` have a corresponding feature to [`@mixin grid-container`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_layout.scss#L77-L86)?

Would most likely correspond to these: https://github.com/IBM/carbon-elements/blob/master/packages/grid/scss/grid.scss#L14-L24

> Does `cabron-elements` have a corresponding feature to [`@mixin font-smoothing`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_typography.scss#L72-L75)?

> Does `cabron-elements` have a corresponding feature to [`@mixin letter-spacing`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_typography.scss#L77-L79)?

No, mostly because these mixins are no longer used because of type styles 👍 

> How do we want to handle [color reset for `<body>` found in `_css--body.scss`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_css--body.scss#L17-L18) in `v10`?

Good question, I think this is as intended right now but cc @aagonzales to confirm that we want `$text-01` as the default color and `ui-02` as the default background color?


> Is `carbon--spacing()` is the right migration path for [`$spacing-*`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_spacing.scss#L41-L50)/[`$layout-*`](https://github.com/IBM/carbon-components/blob/v9.70.0/src/globals/scss/_spacing.scss#L52-L58)?

This needs to be resolved, I think. cc @jeanservaas what did we end up doing for the spacing scale?

**Comment by asudoh** [comment]
Thanks @joshblack for your response! Added some additional `@deprecated` annotations where you provided the migration path.

@jeanservaas @aagonzales Great to have your feedback!

**Comment by aagonzales** [comment]
> Q: How do we want to handle color reset for <body> found in _css--body.scss in v10?
> Josh: Good question, I think this is as intended right now but cc @aagonzales to confirm that we want $text-01 as the default color and ui-02 as the default background color?

Yes, except the default background should be `$ui-background`

**Comment by jeanservaas** [comment]
Hey @joshblack sorry for the delay:

> Does `carbon-elements` have "type reset" feature? (e.g. Applying `.bx--type-alpha` to `<h1>`)

_Not currently, wasn't sure what we wanted to map over to the different headings. cc @jeanservaas do you think we should do this by default?_

**No, we don't want to do this, that's the whole point of the semantic structure that it's purposely not tied to the H classes**

> _@jeanservaas what did we end up doing for the spacing scale?_

 **We ditched the t-shirt sizes for the spacing scale, the tokens are correct as you see them on the site right now $spacing-01... $layout-01 etc.**

**Comment by joshblack** [comment]
Sounds good @jeanservaas 👍 Will track implementation in: https://github.com/IBM/carbon-elements/issues/389

**Comment by asudoh** [comment]
Thanks @aagonzales and @jeanservaas for the response!

* Updated `_css--body.scss` to reflect @aagonzales's comment wrt default background color for `v10`: https://github.com/IBM/carbon-components/blob/5f8b54236925659704cdba1ac8a13a16e7010961/src/globals/scss/_css--body.scss#L24-L32
* Removed "type reset" feature (applying specific type style to all e.g. `<h1>`s) from `v10`: https://github.com/IBM/carbon-components/blob/5f8b54236925659704cdba1ac8a13a16e7010961/src/globals/scss/_css--typography.scss#L138-L140
* Will incorporate change in IBM/carbon-elements#389 in a separate PR

@IBM/carbon-developers Could you proceed with code review? Please use "Diff settings" - "Hide whitespace changes" given some files have change in indent. Thanks!

**Review by dakahn — APPROVED** [review]
🐬 Great! Thank you so much 🐬

**Review by lovemecomputer — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]
Looks great!

**Pull request merged**
