### PR TITLE
fix(data-table): fix table with overflow menu bugs

### LINKED ISSUE #5792: [Overflow menu]: 3 dots are not centered
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

After upgrading, the 3 dots button that opens the overflow menu on a row-table is not centered/aligned.

> Is this issue related to a specific component?

Overflow menu inside a table

> What did you expect to happen? What happened instead? What would you like to
> see changed?

It should be centered

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.10.3

## Steps to reproduce the issue

1. Open https://vanilla.carbondesignsystem.com/?nav=data-table
2. Se section "Select"
3. Hover on any row

## Additional information

- Screenshots or code
image
image

- Notes
There seems to be a new negative margin. When removed, it works as expected
image

image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5792

Fixes an issue where negative margin was added to fix a react specific bug with overflow menu. Added in a more specific selector so it will only target the React implementation. Fixed a few other visual bugs when hovering over the overflow menu, see pics below:

Screen Shot 2020-04-02 at 12 07 11 PM
Screen Shot 2020-04-02 at 12 07 15 PM

#### Changelog

**Changed**

- Increased specificity with negative margin override so it only affects React implementation
- `light` overflow menu now uses the correct `field-02` token
- Changed hover styles so that a) the overflow icon would not disappear when hovering over a menu item and b) there was not a small bar with an incorrect color showing

#### Testing / Reviewing

Test out any Data Table with an Overflow menu, and make sure positioning is correct. Also, check out styles when hovering over an overflow menu, and hover styles when the overflow menu is opened. 

Worth checking out that the normal overflow menu is working as expected as well.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Comment by designertyler** [comment]
Hey @tw15egan I'm still seeing that bar at the bottom of the overflow icon.

I think it's actually the drop shadow peeking up from behind. It's more obvious on the white and g10 themes.

image

**Comment by tw15egan** [comment]
@designertyler should be fixed now 👍

**Review by aledavila — APPROVED** [review]
lgtm

**Comment by designertyler** [comment]
I think it's looking better, but there's still a very very slight color shift happening. Taking the eyedropper to it shows that it's only a couple values away.

What could be causing it? Is it possible to fix? 

image

**Comment by tw15egan** [comment]
@designertyler I'm guessing it is the drop shadow peeking out. If we increase the small pseudo `::after` element that we are using to hide most of the drop shadow, it's going to look strange since it will be larger than the focus outline. Not sure this will be noticeable to anyone as-is

**Review by designertyler — APPROVED** [review]
This subtle color shift is an improvement to the current component, a better tradeoff and will be less noticeable than the focus issue that trying to solve it would cause.

**Pull request merged**
