### PR TITLE
fix(data-table-v2): add child combinator for tds (#2006)

### LINKED ISSUE #2006: hover style incorrectly applied to a data-table-v2 nested into expandable-row-v2
## Detailed description

> Describe in detail the issue you're having.

When a data-table-v2 is nested into an expandable-row-v2, the hover styles are incorrectly applied to the nested one.

See the following codepen: https://codepen.io/marcosimioni/pen/bZqKxN (forked from https://codepen.io/team/carbon/full/gXGabM/ found here https://www.carbondesignsystem.com/components/data-table/code under the Expandable data table example)

Move your mouse on one of the "HOVER HERE" labels and observe the styles applied to the nested table.

wrong behaviour

> Is this issue related to a specific component?

data-table-v2

> What did you expect to happen? What happened instead? What would you like to see changed?

Hover styles should be correctly applied as per this old example -> http://react.carbondesignsystem.com/?selectedKind=Table&selectedStory=Nested%20Table&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel

expected behaviour

> What browser are you working in?

Google Chrome Version 72.0.3626.121 (Official Build) (64-bit) on macOS Mojave 10.14.3 (18D109)

> What version of the Carbon Design System are you using?

v9

### PR DESCRIPTION
**Pull request by marcosimioni**
#### Overview

Resolves #2006 

Added the child combinator selector '>' so that styles will be correctly applied only to direct TD children of TR. This fixes issues especially with the hover styles, when tables are nested into existing tables, but in general when tables are nested into a data table.

#### Changelog

**Changed**

- style of children TDs in data-table-v2

#### Testing / Reviewing

Test that proper :hover styles are still applied to the data-table-v2.
Test that proper :hover styles are applied to a table nested into a data-table-v2 expandable row.
Can be tested with the new storybook story i have created for IBM/carbon-components-react#2107

### CODE REVIEW

**Comment by emyarod** [comment]
hi @marcosimioni thanks for submitting this PR along with IBM/carbon-components-react#2107! it looks like the border that appears on the `<td>`s on table row hover is shifting elements around as we mouse over them

Kapture 2019-03-28 at 8 48 12

I think adding transparent borders on the non-hover states will help so that we don't see this movement, but cc @jnm2377 and @designertyler for possible overlap with https://github.com/IBM/carbon-components/pull/2209 and the remaining data table PRs

**Comment by designertyler** [comment]
Nesting data tables within data table rows is not something we were going to encourage or support for the v2 data table.

**Comment by marcosimioni** [comment]
@emyarod I wasn't seeing the same behaviour. I suspect I'm testing on v9 and you're testing on v10? Would the team prefer me to focus on using & testing the v10 instead?

hover

@designertyler Hey Tyler, I totally understand your point of view.

However, let me just point out that I see we have extensively been using the '>' selector for pretty much all the TD styles. Not having it for these styles seems inconsistent to me. And it would be a sort of free win :P

See here for example

https://github.com/IBM/carbon-components/blob/91d15e139075e7d07a3e47569efea6f4b61d51a7/src/components/data-table-v2/_data-table-v2-expandable.scss#L19

https://github.com/IBM/carbon-components/blob/91d15e139075e7d07a3e47569efea6f4b61d51a7/src/components/data-table-v2/_data-table-v2-expandable.scss#L41

https://github.com/IBM/carbon-components/blob/91d15e139075e7d07a3e47569efea6f4b61d51a7/src/components/data-table-v2/_data-table-v2-expandable.scss#L45

https://github.com/IBM/carbon-components/blob/91d15e139075e7d07a3e47569efea6f4b61d51a7/src/components/data-table-v2/_data-table-v2-expandable.scss#L49

**Comment by emyarod** [comment]
yes my mistake @marcosimioni, I was looking at v10 when your change only targets v9.

this change seems fine to me and it doesn't appear to cause any regressions, but since we don't officially support this pattern would it be fine to implement this fix in user land? I am open to adding this change to the library but would like to hear others' thoughts as well

**Comment by joshblack** [comment]
I'm definitely torn on this, the changes themselves are great 💯 but we don't want to signal that this is an intended use-case of data table. In fact, we would want to discourage this pattern unless UX defines better guidelines for when this is appropriate 👍

**Comment by asudoh** [comment]
Closing as the use case is not Carbon's intended UX pattern as people have mentioned, and there is a workaround (application can override our style). Probably the author can (more) elaborate why a thought of nested data table came up, in this way our design team may come up with a counter UX suggestion.

**Pull request closed without merging**
