### PR TITLE
feat(danger-button): add primary danger button, remove danger button …

### PR DESCRIPTION
**Pull request by tw15egan**
### Danger Button
**Added** 
- Primary Danger Button
- Primary Danger Button (small)

**Changed**
- Disabled styles for Danger buttons

**Removed**
- Danger button with icon

Closes https://github.com/carbon-design-system/carbon-components/issues/559

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM once designer’s review passes - Thanks @tw15egan! 👍

**Comment by bsonefeld** [comment]
❗️ 👍 
Looks good! Small thing: Can we change the content on the secondary danger button to say: 

* Secondary danger button
* Small secondary danger

**Comment by tw15egan** [comment]
@bsonefeld done!

**Review by marijohannessen — APPROVED** [review]
Looks great! 👍 ✅ 🎉

**Pull request merged**
