### PR TITLE
feat(Pagination): add support for sizes

### PR DESCRIPTION
**Pull request by emyarod**
related #8875

This PR adds support for Pagination component sizes and sets up the groundwork for scaling with data table sizes

#### Changelog

**New**

- `size` prop in Pagination

#### Testing / Reviewing

Confirm the pagination sizes (configurable with storybook knob) appear correct

### CODE REVIEW

**Review by andreancardona — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
cc @jeanservaas when you have a chance to review

**Comment by emyarod** [comment]
bump @jeanservaas when you have a chance

**Review by aagonzales — COMMENTED** [review]
I'm seeing the select background come in as the wrong color.

image

**Comment by emyarod** [comment]
is that an issue with the netlify previews or is it also present in local builds? this PR only adds more size options to the component

image

image

image

**Review by aagonzales — COMMENTED** [review]
I didn't really see a design spec for this but I think the previous/next page buttons need to be squared up in width. 

image

**Comment by tw15egan** [comment]
@aagonzales just pushed up a change to square the buttons

**Review by aagonzales — APPROVED** [review]
Looks good!

**Pull request merged**
