### PR TITLE
docs(ModalWrapper): expose `focusTrap` knob

### PR DESCRIPTION
**Pull request by emyarod**
Refs #4311

This PR exposes the `focusTrap` knob in the `ModalWrapper` story

#### Changelog

**New**

- `focusTrap` knob in `ModalWrapper` story

#### Testing / Reviewing

* check if the focus trap is enabled/disabled with the storybook knob

### CODE REVIEW

**Comment by vpicone** [comment]
Is there a reason we want to expose this as a knob?

**Comment by emyarod** [comment]
to enable the storybook "show info" button when the modal is open

**Comment by joshblack** [comment]
Would it be helpful to add an example with the focus trap as opposed to a knob? Or is that too much overhead?

**Review by joshblack — COMMENTED** [review]
Left a question above 👀

**Comment by emyarod** [comment]
the issue is that since the focus trap is enabled by default the storybook "show info" button is not interactable. adding an additional story with the focus trap disabled may be more confusing but if that's what we would rather do I can make that change

**Comment by abbeyhrt** [comment]
Since this is only an issue if the modal is open, is this something we want to add? I think it made sense for #4311 since that modal can't be closed but ModalWrapper shows the real expected behavior of the modal in action, where I think we do want any underlying buttons to not be interactive, right?

**Comment by vpicone** [comment]
I think it'd be better to just use the prop without exposing it as a knob, but looks like we already do for Modal.

**Review by vpicone — APPROVED** [review]
I think it'd be better to just use the prop without exposing it as a knob, but looks like we already do for Modal.

**Review by joshblack — APPROVED** [review]

**Pull request merged**
