### PR TITLE
fix(loading): adds label and aria so loading state is read by screenreaders

### LINKED ISSUE #3446: AVT 3 - React Loading Component, VO/iOS and JAWS/Windows do not announce Loading
## Environment
Windows 10 
FireFox Quantum 68.0
JAWS 18

iOS 12.3.1
Safari
VoiceOver

## Description
When page loads "Active Loading Indicator" is not announced by screen readers.
Expected Result: Screen reader should announce "Active Loading Indicator" on page load. 

Note: This is working with VoiceOver on macOS.

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #3446 

This PR addresses the loading state not being announced in Safari on iOS and and Firefox in JAWS. Adding the `aria-atomic=true` announces the loading state in JAWS and the added label makes it announce on mobile.  

#### Changelog

**New**

- `label`
- tests for aria-labels
- unique Id helper

#### Testing / Reviewing

When the screen loads for the `Loading` component, make sure in VO on macOS and iOS and JAWS in FireFox on Windows 10 that  "Active Loading Indicator"  is announced.

### CODE REVIEW

**Comment by snidersd** [comment]
Retested on Win 10 w/ JAWS & FF, iOS 13.1.3 w/VO & Safari, macOS w/VO & Chrome. No violations found.

**Review by joshblack — CHANGES_REQUESTED** [review]
Would you mind adding some docs to the component for all of these situations you ran into and tests for the right aria? Just to make sure we don't remove these 😬

**Review by emyarod — APPROVED** [review]
looks good to me, just curious about the different comment methods on [L83](https://github.com/carbon-design-system/carbon/blob/0e0ed07416f4ec0d51f29e69c6be268f140a93af/packages/react/src/components/Loading/Loading.js#L83) and [L88](https://github.com/carbon-design-system/carbon/blob/0e0ed07416f4ec0d51f29e69c6be268f140a93af/packages/react/src/components/Loading/Loading.js#L88)

**Review by aledavila — APPROVED** [review]
🎉

**Comment by abbeyhrt** [comment]
@emyarod I updated the comments so it's a block above `loading` and added more detail about the updated aria

**Review by joshblack — APPROVED** [review]

**Pull request merged**
