### PR TITLE
fix(RadioButton): remove unecessary aria-label

### LINKED ISSUE #4491: RadioButton React - Screen reader cannot read label
## Environment

> Operating system
OS X
> Browser
Chrome
> Assistive technology used to verify
VoiceOver / JAWS

## Detailed description

> What version of the Carbon Design System are you using?
10 
> What did you expect to happen?
The screen reader can read individual radio button content
> What happened instead?
It can't find it

## Steps to reproduce the issue

1. Activate VoiceOver
2. Select a radio button in the vanilla html (it reads the content)
2. Select a radio button in the React version (it doesn't)

This can be recreated on the main component documentation https://www.carbondesignsystem.com/components/radio-button/code and the react storybook page http://react.carbondesignsystem.com/?path=/story/radiobuttongroup--default

## Additional information

Here's what is reads in the vanilla component. The important bit is that is correctly gets "Radio button label"
image

Here's what it reads in the react component. It can't read the label
image

I dug into the code a bit here's the vanilla html:
```
<div class="bx--radio-button-wrapper">
   <input id="radio-button-unp8hnypvgd-1" class="bx--radio-button" type="radio" value="red" name="radio-button--vertical" tabindex="0" checked>
   <label for="radio-button-unp8hnypvgd-1" class="bx--radio-button__label">
   <span class="bx--radio-button__appearance"></span>
   <span class="bx--radio-button__label-text">Radio button label</span>
   </label>
</div>
```
and here is the html generated from the react component
```
<div class="some-class bx--radio-button-wrapper">
   <input id="radio-1" name="radio-button-group" type="radio" class="bx--radio-button" value="standard">
   <label for="radio-1" class="bx--radio-button__label" aria-label="Radio button label">
   <span class="bx--radio-button__appearance"></span>
   <span class="">Radio button label</span>
   </label>
</div>
```

I think the issue is the aria-label="Radio button label"` in the react version, which isn't needed.

### PR DESCRIPTION
**Pull request by dakahn**
Closes #4491 

Really quick one here. Removes an unneeded `aria-label` that was causing label duplication in Safari and just totally breaking labeling for VoiceOver in Chrome. 

#### Testing / Reviewing

In Safari with VO make sure that the label is only read once. In Chrome -- check and make sure the label is read.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
it looks like snapshots need to be updated to pass CI

**Comment by aledavila** [comment]
Make sure to update the snapshots

**Review by abbeyhrt — APPROVED** [review]
Once the snapshots are updated, this looks good to me! 🎉

**Review by aledavila — APPROVED** [review]
lgtm

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @dakahn!

**Comment by asudoh** [comment]
@dakahn Could you update the snapshot? Thanks!

**Review by joshblack — APPROVED** [review]

**Pull request merged**
