### PR TITLE
fix(combo-box): match experimental spec

### LINKED ISSUE #2186: Match combo box to experimental spec
Depends on listbox and required for `carbon-components-react`

#2167 

https://github.com/IBM/carbon-components/pull/2181

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2186

This PR updates the experimental combobox component to align with the v10 spec

related: #2206

#### Changelog

**New**

- incorporate v10 listbox
- add component variants to docs
- add overflow text menu option for testing

**Changed**

- input field spacing and outline offset to match v10

**Removed**

- unused legacy styles

### CODE REVIEW

**Comment by asudoh** [comment]
@shinytoyrobots @alisonjoseph Change looks well contained - Are you OK with putting this PR into `v10`? Thanks!

**Review by alisonjoseph — APPROVED** [review]
LGTM once @laurenmrice signs off!

**Review by dakahn — APPROVED** [review]
👍🏽

**Review by laurenmrice — CHANGES_REQUESTED** [review]
All combo box variations:
- [x] Filter text in the label should be `text-02`. it shouldnt be placeholder text.
- [x] There should be a bottom rule line calling `ui-04` for the default closed combobox
Screen Shot 2019-03-27 at 10 15 02 AM

- [x] For the opened drawer, there should be a full rule line (`ui-03`) separating the label and the drawer.
Screen Shot 2019-03-27 at 11 11 13 AM

- [x] Also for open drawer, on hover, the rule is showing next to the hover color which needs to be removed.
Screen Shot 2019-03-27 at 11 09 49 AM

- [x] The disabled states currently do not have the chevrons.
- [ ] Make sure all of the widths of the fields are the same size, some are longer than others.

Inline:
- [x] we do not have an Inline variation for Combo box, so we can take this out.

**Comment by emyarod** [comment]
> Make sure all of the widths of the fields are the same size, some are longer than others

the invalid element will get wider because we're not setting a width but we add padding to make space for the warning icon. the consumer will be able to set a width to prevent this from happening, but we won't be setting an explicit width value out of the box. (Resolved via Slack)

**Review by laurenmrice — APPROVED** [review]
Looks good to me ! 👍

**Pull request merged**
