### PR TITLE
fix(text-area): match experimental spec

### LINKED ISSUE #1946: [Audit] Text area
text area - white theme

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1946

This PR incorporates feedback from the February 2019 audit of the text area component

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
💪 🎉

**Comment by aagonzales** [comment]
The helper text is supposed to be above the field not below it:
image

**Comment by emyarod** [comment]
should be fixed now @aagonzales 

now just waiting on https://github.com/IBM/carbon-components/pull/1968

**Comment by emyarod** [comment]
#1968 has been merged, bump for re-review

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Saw a markup change (addition of helper text?) for `v9`, great if you can double-check if `v9` is OK - Thanks @emyarod!

CC @aagonzales to see if she has any additional comments.

**Review by aagonzales — COMMENTED** [review]
The helper text look correct now! But the label of the one without helper text is now off. There should be 8px of padding between the label and the field 

**As-is:**
image

**Comment by emyarod** [comment]
@asudoh I believe the only change affecting v9 is fixing the helper text which was placed incorrectly in a previous commit

**Comment by emyarod** [comment]
updated the margin without helper text @aagonzales

**Review by aagonzales — APPROVED** [review]
Ship it!

**Pull request merged**
