### PR TITLE
fix(datepicker): adds Optional chaining

### LINKED ISSUE #17794: [Bug]: Datepicker - Error Occurs When Clearing Dates in DatePicker Component of Carbon React
### Package

@carbon/react

### Browser

Chrome

### Package version

1.68.0

### React version

18.3.1

### Description

**Description**

When using the DatePicker component in Carbon React, if a user erases the entire date input (for a range) and then shifts focus to another input or component, an error is thrown.

https://github.com/user-attachments/assets/c74d1cd1-f944-42a7-be2f-d04c8071288d

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

### Steps to reproduce

- Open the DatePicker component configured for a date range.
- Select a start and end date.
- Clear the entire input field for end date.
- Move the focus to another input field (start date) or component.

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes https://github.com/carbon-design-system/carbon/issues/17794

 adds Optional chaining to fix  _Cannot read properties of undefined_ error

#### Changelog

**Changed**

Adds `?.` operator before calling `setHours` and `toString` functions 

#### Testing / Reviewing

Open the DatePicker component configured for a date range.
Select a start and end date.
Clear the entire input field for end date.
Move the focus to another input field (start date) or component
verify to errors in console 

Uploading Screen Recording 2024-11-12 at 14.50.07.mov…

### CODE REVIEW

**Review by preetibansalui — COMMENTED** [review]
Hey Nikhil, It looks good to me. Could you please add a test case for this condition as well?

**Review by riddhybansal — APPROVED** [review]
Looks Good !! Thanks for adding test cases

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by preetibansalui — APPROVED** [review]
Thanks for the test Nikhil

**Pull request merged**
