### PR TITLE
fix(TableToolbarAction): adds forwardRef so focus management works as expected

### LINKED ISSUE #2481: DataTableMenu is not keyboard/tab accessible
- [ ] the focus menu itself should be focused when clicked
- [ ] when activated via keyboard, the first menuItem should receive focus
Apr-22-2019 09-44-22

Focus management is currently a big issue for the OverflowMenu, especially when it is used in a compound component. We need to start work on an accessible replacement or not use that component for the DataTableMenu.

### LINKED ISSUE #3372: [DataTable] OverflowMenu doesn't have keyboard accessible styles
## Detailed description

When using an `OverflowMenu` component inside of a `DataTable` as highlighted [here](https://www.carbondesignsystem.com/components/data-table/usage#inline-actions), the keyboard actions of the `OverflowMenu` do not work. 

Once the menu is open, the user is not able to use their arrow keys to select an `OverflowMenuItem` option as one would be able to in an `OverflowMenu` that is not inside of a `DataTable` because there are no visual indicators of which option is currently active.

It is expected that a user would be able to make a selection inside of an `OveflowMenu` in a `DataTable` just using their keyboard.

> What version of the Carbon Design System are you using?
Version 10

## Steps to reproduce the issue

1. Go to sandbox https://codesandbox.io/s/carbon-react-datatable-overflowmenu-a11y-bug-c92rz
2. Using the keyboard only, open any overflow menu on the table
3. Use arrow keys to attempt to select an action
4. Notice that there are no visual indicators of which action is active to be selected

## Additional information

**Keyboard usage of standalone `OverflowMenu`**
Kapture 2019-07-11 at 15 36 36

**Keyboard usage of `OverflowMenu` inside of a `DataTable`**
Kapture 2019-07-11 at 15 38 15

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #2481
Closes #3372 

Components using OverflowMenuItem need to have the `primaryFocus` attribute on the first item so a user can use the arrow keys to go between options. This PR makes it so the README for OverflowMenu, which specifies this, shows up in the react Storybook (#3372 was just confusion around that). It adds forwardRef to TableToolbarAction, in conjunction with adding `primaryFocus`, so that focus management works as expected.

#### Changelog

**New**

- README visible in storybook for OverflowMenu

**Changed**

- adds forwardRef to TableToolbarAction

#### Testing / Reviewing
 
 - Go to DataTable with batch actions example, tab into gear and make sure you can use arrow keys to select options. 
Expected: 
Sep-05-2019 11-00-46

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Fix looks good 👍 I think some snapshots are failing on DataTable, though 👀

**Comment by tw15egan** [comment]
Do we have any examples using an `OverflowMenu` in a TableRow? Unable to verify this fixes https://github.com/carbon-design-system/carbon/issues/3372

**Comment by aledavila** [comment]
@tw15egan unsure it exists in react. It exists in vanilla, josefina worked on it but I'm not sure who worked on updating the v10 react datatable and if it was included.

**Review by dakahn — APPROVED** [review]
Great! 🏄 Approving, but there is one extra bonus fix if you feel up for it. It's out of the scope of the referenced issues, but since you have a familiarity with the component might be a good add on;

My expectation is that if I have the menu open with an item focused and I hit `TAB` focus should move to the next tabstop (in this case an "Add New" button). [Here's an example using an navigation menu.](http://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html) Tab to the menu, open it, and then hit tab and you'll see focus jump to a link (since the whole navbar itself is a tabstop in the example's case). 

The way it works now is the menu closes and focus is returned to the menu's button. 

Again, not a blocker and feel free to merge and we can roll this into another ticket 👍 

--

UPDATE
Discussed it offline and after some deliberation we're gonna move this to a ticket 💯

**Comment by abbeyhrt** [comment]
#3372 is a little weird, this fixes it because there was never really a problem in the first place. For the focus management to work, there needs to be the `primaryFocus` attribute on the first OverflowMenuItem and they weren't doing that. This is in the readme but the readme wasn't in the storybook, this adds it to the storybook. Hopefully people won't have this problem in the future!🤞

**Comment by tw15egan** [comment]
@abbeyhrt makes sense, thanks for clarifying! Looks good once tests are fixed

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
