### PR TITLE
fix: Fixed aria-current in `BreadcrumbItem`

### LINKED ISSUE #16749: [a11y]: Breadcrumb - With Overflow Menu - JAWS is not announcing the current breadcrumb
### Package

@carbon/react

### Browser

Firefox

### Operating System

_No response_

### Package version

v1.58.1

### React version

18.02

### Automated testing tool and ruleset

Manual QA

### Assistive technology

JAWS

### Description

While navigating through the arrow keys, JAWS is not announcing the current breadcrumb.

### Recommended Fix
aria-current is not implemented for the current breadcrumb.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-breadcrumb--breadcrumb-with-overflow-menu

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by guidari**
Closes #16749

Added prop `isCurrent` to the logic and also added an `href` to make the breadcrumb tabbable.

#### Testing / Reviewing

- Use VO or JAWS to test the change

### CODE REVIEW

**Review by 2nikhiltom — APPROVED** [review]
The current breadcrumb now gets the focus ring via keyboard navigation and VO is announcing the status 🔥 

One questions : 
via keyboard navigation: the last/current breadcrumb gets focus ring, and underline.
on mouse hover : underline and cursor pointer is missing on the last/current breadcrumb

Wanted to confirm the expected behaviour, It seems alright to me

https://github.com/user-attachments/assets/185a1852-e81a-40d0-afae-a6d089b4cce2

**Comment by guidari** [comment]
@2nikhiltom 
> One questions :
via keyboard navigation: the last/current breadcrumb gets focus ring, and underline.

I'm not sure about this one. I guess this is right.

> on mouse hover : underline and cursor pointer is missing on the last/current breadcrumb

This one is correct, if the breadcrumb item has `isCurrent` it shouldn't have cursor pointer.

**Comment by alisonjoseph** [comment]
Should the current page have the hover state, this feels odd without the cursor change. 🤔

**Comment by guidari** [comment]
@carbon-design-system/design

Can anyone help on this one?

**Comment by alina-jacob** [comment]
> @carbon-design-system/design
> 
> Can anyone help on this one?

---

As per the [Interaction guidelines](https://carbondesignsystem.com/components/breadcrumb/usage#interactions), the current page should receive no interaction, so no hover, no colour change. 

image

It technically shouldn't even receive tab stop as per [Accessibility guidelines](https://carbondesignsystem.com/components/breadcrumb/accessibility/#keyboard-interactions)
image

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
