### PR TITLE
feat(pictograms): rename city asset names

### LINKED ISSUE #4117: chore(pictograms): correct delimiter for two word main names (.svg, categories.yml, and metadata.yml)
mv `san--franscisco*` `san-frasncisco*`
mv `san--paolo*` `san-paolo*`
mv `washington--dc*` `washington-dc*`

the pictogram .svg filename, and the references in categories.yml, metadata.yml

### PR DESCRIPTION
**Pull request by joshblack**
Closes #4117

Updates city names to contain one dash in their name.

#### Changelog

**New**

**Changed**

- san--franscisco* -> san-frasncisco*
- san--paolo* -> san-paolo*
- washington--dc* -> washington-dc*
- `deprecated.yml` has been updated with updates

**Removed**

### CODE REVIEW

**Review by dakahn — APPROVED** [review]
seems chill 🏄

**Comment by joshblack** [comment]
Note to reviewers, seems like these assets generate identical names to the ones that they're replacing. We might not need to do a deprecation pass if the exports are the same

**Review by abbeyhrt — APPROVED** [review]

**Review by laurenmrice — COMMENTED** [review]
There is a typo for second friendly name. Should be `Francisco`
Screen Shot 2020-03-19 at 4 25 05 PM

**Comment by joshblack** [comment]
@laurenmrice fixed!

**Review by laurenmrice — APPROVED** [review]

**Pull request merged**
