### PR TITLE
feat(checkbox): Update checkboxes to match new icon set

### PR DESCRIPTION
**Pull request by alisonjoseph**
Updated the checkbox checkmark to better align with the new icon set

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @alisonjoseph!

**Comment by alisonjoseph** [comment]
Want to make sure @tay-aitken has a chance to look at this before merging in.

**Comment by tay-aitken** [comment]
Hey Alison! So checkmark is one of the exceptions. We made a 2px thick variation (in the box link I sent you) since 1px was so thin. We also made the indeterminate line 2px as well. Here is an example:
screen shot 2018-05-30 at 3 38 13 pm

**Comment by alisonjoseph** [comment]
Updated to look like this @tay-aitken 
screen shot 2018-05-30 at 4 41 04 pm

**Review by aledavila — APPROVED** [review]

**Comment by tay-aitken** [comment]
Looks good! Thanks @alisonjoseph

**Pull request merged**
