### PR TITLE
fix(ListBox): enable drawer animation

### LINKED ISSUE #2697: [Dropdown, react] Missing drawer animation
Dropdown is missing the drawer opening and closing animations. This should match vanilla's dropdown: https://the-carbon-components.netlify.com/component/dropdown--default.html

Motion spec: 
easing: `motion(entrance, productive)`
durration: `$duration--fast-02`

### PR DESCRIPTION
**Pull request by asudoh**
(Please use gear icon - "Hide whitespace changes" for reviewing)

This change adds was-missing animation to list boxes' drawers.

Fixes #2697.

#### Changelog

**New**

- Animation to list of drawers.

#### Testing / Reviewing

Testing should make sure `<ComboBox>`, `<Dropdown>`, `<MultiSelect>` are not broken.

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
the drawer open and close animations are now visible in all listbox components. looks good to me pending visual review

**Review by jeanservaas — APPROVED** [review]
looks good

**Comment by nertzy** [comment]
Should we be setting `aria-hidden` on the listbox when it is "closed"? We are no longer removing it from the DOM so it will still get picked up by screen readers, right?

**Comment by nertzy** [comment]
See #5949

**Pull request merged**
