### PR TITLE
feat(Toggletip): update `align` accepted props

### PR DESCRIPTION
**Pull request by tw15egan**
Noticed while working on the `ToggleTip` inside `FluidTextInput` that `ToggleTip` currently only allowed 4 `align` directions, but the underlying component (`Popover`) supports 12. I've updated the accepted props for `ToggleTip` to allow these extra variations.

#### Changelog

**Changed**

- `ToggleTip` now supports all directions provided by the underlying `Popover` component
- Updated the playground story to preview all possibilities. 
- Updated snapshots

#### Testing / Reviewing

Go to `Toggletip` playground story and try testing the different `align` variations.

### CODE REVIEW

**Comment by abbeyhrt** [comment]
I think it _might_ have been intentional to limit ToggleTip to only those 4 alignments, I'm not sure. I added design as a reviewer to see if it was on purpose.

**Review by abbeyhrt — APPROVED** [review]
If the intent is to have all alignments available, then this looks good to me!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Nice catch @tw15egan ! 

The `left-bottom` and `left-top` alignments do not have the 16px padding before or after the caret. Other than that, everything else looks great!

**Comment by tw15egan** [comment]
@laurenmrice nice catch! Updated 👍🏻

**Review by tay1orjones — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]

**Pull request merged**
