### PR TITLE
fix(content-switcher): add divider token

### PR DESCRIPTION
**Pull request by SimonFinney**
Experimental content switcher divider color values references `$ibm-colors__gray-30` instead of a token role value.

#### Changelog

**Changed**

- Update content switcher divider to use `$ui-03` token

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Hi @SimonFinney thank you for jumping in! I see the color has two-layered tokens, and thus I think `$content-switcher-divider: $ui-03 !default !global` is what you wanted. Thanks!

**Review by joshblack — CHANGES_REQUESTED** [review]
To echo @asudoh's point, would we we want to update `$content-switcher-divider` to be `ui-03`?

**Comment by SimonFinney** [comment]
@asudoh @joshblack Done - good to know! Just so I understand better, what's the reason for that?

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @SimonFinney for the update! The two-layer token system is for better flexibility. Recent discussion around that can be found at #1707.

**Review by tw15egan — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
🎉 you're awesome!

**Comment by asudoh** [comment]
Merging as all reviewer's concerns seem to have been addressed - Thanks @SimonFinney again for jumping in, and everybody for reviewing!

**Pull request merged**
