### PR TITLE
refactor: move ToggleSkeleton to TypeScript

### LINKED ISSUE #12565: Add TypeScript types to ToggleSkeleton

### PR DESCRIPTION
**Pull request by gerzonc**
Closes #12565 

Migrates `ToggleSkeleton` to TypeScript

#### Changelog

**New**

- Adds type `ToggleSkeletonProps` for `ToggleSkeleton`
- Adds partial type for `defaultProps`

**Changed**

- `ToggleSkeleton` is now a TypeScript file
- Ternary for `aria-label` now checks for `undefined` instead of `null` if there is a `labelText` present

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by gerzonc** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by alisonjoseph** [comment]
I think this may be an existing bug, but I quickly added a story for ToggleSkeleton locally so I can test and it looks like this 🤔 

Screenshot 2023-04-03 at 7 57 37 AM

**Comment by gerzonc** [comment]
> I think this may be an existing bug, but I quickly added a story for ToggleSkeleton locally so I can test and it looks like this 🤔
> 
> Screenshot 2023-04-03 at 7 57 37 AM

Yeah, that's how it looks like from the `main` branch. If there is some kind of design available just to see how it should look like, I would be glad to fix it right away. :)

**Comment by francinelucca** [comment]
Ran on main branch and confirmed broken styling:
image

Opened up new issue https://github.com/carbon-design-system/carbon/issues/13459. 
Other than that this LGTM , @alisonjoseph should we add that issue as blocker for this one or is this good to merge? 🤔

**Review by alisonjoseph — APPROVED** [review]
Approving this, we can handle the visual bug and adding to storybook in a separate issue/PR 😄 

@gerzonc looks like there is a small merge conflict in the readme

**Review by francinelucca — APPROVED** [review]
@gerzonc thanks for adding this, looks good! 🚀
After you solve the `Readme.md` merge conflicts and this should be good to go 🙏🏻

**Pull request merged**
