### PR TITLE
chore(components): extract out default component options

### LINKED ISSUE #460: Export class names in JS module
This is a future-facing feature request, the goal being to derive component classes from the `scss` we write and then publish those as part of the JS module so that implementations can derive their class names from this exported set, with the benefit being that an update in our `scss` would generate a new class name in the exported module which would then update in any consuming library.

The simplest way to get this to work would be to go through our generated CSS and convert the BEM-style to a camelCase convention, and just export the resulting object with the key being the camelCase variation and the BEM style being the value.

The usage from a consumer standpoint would look like:

```
import { classNames } from 'carbon-components';

classNames.dropdown; // 'bx--dropdown'
```

### PR DESCRIPTION
**Pull request by asudoh**
## Overview

For reusing them, especially of selectors, with React, etc. variants.

Resolves #460.

### Added

* options.js file for each components, working as the bast of static/default component options
* index.js file for each components to import component code as well as their options
* Code in src/index.js to import options of each components

## Testing / Reviewing

* Should CSS-related options have its own place, separate from other options?
* Testing should make sure no component is broken.

### CODE REVIEW

**Comment by joshblack** [comment]
Love this PR! How would you imagine frameworks/libraries importing this stuff to use?

**Comment by asudoh** [comment]
Thanks @joshblack! The goal here is something like (though we need more work separate from this PR):

```javascript
import { accorionOptions } from 'carbon-components';

const Accordion = ({ children, className, ...other }) => {
  const classNames = classnames(accorionOptions.classAccordion, className);
  ...
};
```

**Comment by joshblack** [comment]
What is the scope of options you think it'd hold? Now and potentially in the future 😄

**Comment by asudoh** [comment]
@joshblack Great question! The only must-haves I’m thinking of for now is selectors and class names. Good to discuss other in item-by-item basis.

**Review by tw15egan — APPROVED** [review]
I like this approach! 👍 ✅

**Review by marijohannessen — APPROVED** [review]
Works great! 👍 ✅   I think regarding CSS selectors - is that something we want to tackle in a bigger conversation regarding extracting our styles and possibly switching to a more CSS modules approach?

**Comment by marijohannessen** [comment]
Feel free to merge this @asudoh if you want to continue the discussion somewhere else!

**Comment by joshblack** [comment]
Only thing thinking through this is import ergonomics. Sucks that if we put it in the default export than we have to prefix all the options like `accordionOptions` versus just doing a direct import to the get the options.

Also makes it hard to use the import path in scss as well, which I would imagine add-on teams would want to use in order to verify their selectors get updated.

In other words, would be nice to be able to do something like:

```js
import { selectors } from 'carbon-components/lib/accordion';
import selectors from 'carbon-components/lib/accordion/selectors';

selectors.container; // string
```

```scss
@import 'carbon-components/lib/accordion/selectors'

$accordion__container // string
```

**Comment by marijohannessen** [comment]
@asudoh what are your thoughts on this?

**Comment by asudoh** [comment]
My apologies @marijohannessen after some inputs from @joshblack wrt relevant area I began to think this area need to be put more thoughts before we go forward with this - At least making the options module pure JSON so that several tools can consume them directly. Let me withdraw this PR for now.

**Pull request closed without merging**
