### PR TITLE
feat(ContentSwitcher): add support for light variant

### LINKED ISSUE #6309: Add `light` prop / variant for `ContentSwitcher`
### Summary

The `ContentSwitcher` does not currently contrast visually on `ui-01` backgrounds:

ContentSwitcher

It may be that the tokens need to be adjusted, or that a `light` prop / variant should be included, similar to the `TextInput`.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6309 

This PR adds support for the `light` prop in the content switcher

#### Changelog

**New**

- hover-light-ui token
- `light` prop support in content switcher

#### Testing / Reviewing

Confirm the light content switcher matches the new component spec

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
The `ui-01` enabled sections need to change to `ui-02` for the light prop. The white and gray 10 theme content switchers are currently blending into the background

Spec example :
Artboard Copy 4

**Review by joshblack — CHANGES_REQUESTED** [review]
Looking great!

One small thing that I ran into:

image

This seems to show up with light enabled and theme set to g10. Let me know if this is to spec and feel free to dismiss if so!

**Comment by laurenmrice** [comment]
Yes that rule shouldn't be showing up either upon selection.

**Comment by emyarod** [comment]
> The ui-01 enabled sections need to change to ui-02 for the light prop ...

this should already be the case, unless am I misunderstanding? https://github.com/carbon-design-system/carbon/blob/bd346ffc4b5d8c8d9fdd6ccf5390ff636b88eeea/packages/components/src/components/content-switcher/_content-switcher.scss#L76-L82

for the dividers showing up with the incorrect colors, can I get confirmation on the token values? it would also be good to post the updated expected token values here or in the issue since right now that information is only contained in slack AFAIK

you can see the values I am currently using in the theme files (white.js, g10.js, g90.js, g100.js) here https://github.com/carbon-design-system/carbon/pull/6442/files

**Comment by laurenmrice** [comment]
Ok good about `ui-02` 👍🏻 I was just making sure. At one time the light props used to have demos that had the background applied ontop of the ui-background, but I don't see it anymore.

For rules:
The token being used for the light prop is correct for the rules (decorative-01), it's just that they are showing up on top of the selected state, they should be hidden like they are when the light prop is not applied.

Light prop token for rules:
`decorative-01`
White | G10 | G90 | G100 |
| --- | --- | --- | --- |
| G20`#e0e0e0` | G20 `#e0e0e0` | G60 `#6f6f6f` | G70 `#525252` |


Ligh prop token for hover state:
`hover-ui-light`
White | G10 | G90 | G100 |
| --- | --- | --- | --- |
| G20 hover `#e5e5e5` | G20 hover `#e5e5e5` | G60 `#6f6f6f` | G70 `#525252` |

**Review by dakahn — APPROVED** [review]
LGTM :smile_cat:

**Review by laurenmrice — APPROVED** [review]
looks good to me! thank you 👍🏻

**Review by joshblack — APPROVED** [review]

**Pull request merged**
