### PR TITLE
fix(FileUploaderDropContainer): pass through empty `accept` attr

### LINKED ISSUE #4519: FileUploaderDropContainer - Cannot read property 'uuid' of undefined when dragging a file
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Summary
two issues:-

1) When dropping a file into the drag & drop panel I'm getting this error:
"Uncaught TypeError: Cannot read property 'uuid' of undefined"

BTW: same issue with the example provided by carbon in this sandbox:
https://codesandbox.io/s/github/emyarod/carbon/tree/dnd-uploader-codesandbox/packages/react/examples/drag-and-drop-file-uploader

2) I had set multiple: false to prevent from selecting more than one file.
So currently I can choose one file each time I browse, but the list of files will be incremented each time I pick a new file.

How to force the list items to display only the last selected one?

## Relevant information

Sandbox:
https://codesandbox.io/s/brave-voice-bdrx0

### PR DESCRIPTION
**Pull request by emyarod**
Closes #4519

Previously if the user did not supply any file type restrictions, the resulting validated files array would be empty. This PR adds a check for empty `accept` attribute on drop events to pass through drag and dropped files when the `accept` attribute is not specified

This PR also adds a code sandbox example application using the dnd uploader

#### Changelog

**New**

- Code Sandbox drag and drop file uploader example

**Changed**

- `accept` prop check in `validateFiles` method
- move `max-width` rule to drop container label to fix a visual bug where the focus outline extended past the drop area

#### Testing / Reviewing

* Remove the default `accept` knob value in storybook
* ensure the component functions as expected

### CODE REVIEW

**Comment by Georgegriff** [comment]
bit confused did empty accept ever work? if so when was it changed? 
Also when would you predict this fix would be available? trying to decide if i should do the mime type work around for now, which will be tricky since we pretty much allow any files to be uploaded

**Comment by emyarod** [comment]
this PR only affects drag and drop behavior. `accept` by default only affects the operating system's native file picker, and empty `accept` becomes `*.*` in the native file picker.

currently the mime types in `accept` are followed when the user performs a drag and drop upload, but an empty value for `accept` will cause an error, which is what this PR should address. in this PR empty `accept` now allows any file to be uploaded via drag and drop just like it would for the native file picker. until this PR is merged in, if you want to be able to accept all mime types for drag and drop uploading specifically, you would have to pass in mime types to `accept` or modify the component source to match this PR

**Comment by Georgegriff** [comment]
@emyarod thanks for the clarity :)

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by dakahn — APPROVED** [review]

**Review by joshblack — APPROVED** [review]
Seems great, any chance we need to add a test for this or should be good?

**Comment by emyarod** [comment]
sure I can look into that

**Pull request merged**
