### PR TITLE
fix(search): remove role attr and label from skeleton

### LINKED ISSUE #4179: AVT 1 Skeleton: Search has a DAP violation for missing unique search label and label w/ descriptive text
## Environment
macOS Mojave version 10.14.6
Chrome Version Version 77.0.3865.90
Carbon v10 - React
DAP IBM Accessibility 1.8.0.0 Sept 2019 Ruleset

## Detailed Description
Go to the React skeleton for Search
Run DAP and the following issue is found on the on each skeleton component (see screenshots):
search

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4179 

Proposal to remove the `role="search"` attribute from this component and replace the `label` element with a simple `span`.  My reasoning here is that there doesn't appear to be a real need for the role attribute and a `label` element since this is a non-interactive `div`. This would also remove the DAP violations.

#### Changelog

**Changed**

- change `label` element to a `span` 

**Removed**

- remove `role="search"` attribute
- remove `htmlFor` attribute

### CODE REVIEW

**Comment by jendowns** [comment]
Hey also, side note -- I noticed that this component is a class but maybe it doesn't need to be? I could do a quick little refactor to turn it into a simple functional component 🤔 Want me to do that in this PR?

**Review by joshblack — APPROVED** [review]

**Review by emyarod — APPROVED** [review]

**Comment by emyarod** [comment]
it looks good to go as-is but feel free to do the refactor in a separate PR if this gets merged in before you're able to push it and get re-reviews

**Review by vpicone — APPROVED** [review]
If you wanna make it a fc that'd be great! Thanks for the pr.

**Comment by jendowns** [comment]
Thanks @emyarod & @vpicone! I just converted it into a functional component in my latest commit, if you don't mind taking another quick look.

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! 🎉

**Pull request merged**
