### PR TITLE
chore(release): v10.38.0-rc.0

### PR DESCRIPTION
**Pull request by andreancardona**
Release PR for v10.38.0-rc.0

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]
lgtm once CI is passing

**Review by tay1orjones — COMMENTED** [review]
I think the `yarn.lock` should be updated with this

**Comment by jnm2377** [comment]
@andreancardona did you run `yarn`?

**Comment by andreancardona** [comment]
> @andreancardona did you run `yarn`?

yep I did...looking into the issue now

**Comment by jnm2377** [comment]
@tay1orjones I just updated the yarn lock

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
