### PR TITLE
fix: type definition for onSelect prop in TreeView component

### LINKED ISSUE #17151: [Bug]: TypeScript TreeView onSelect event handler seems to have wrong type definition
### Package

@carbon/react

### Browser

_No response_

### Package version

v1.64-rc.0

### React version

v18.x

### Description

Seems like the current TS types definition for `TreeNode` has an error:

```ts
// Current TreeViewProps type in v1.64.0-rc.0

export type TreeViewProps = {
  // ... more properties

  /**
   * Callback function that is called when any node is selected
   */
  onSelect?: (selected: Array<string | number>, payload: any) => void;

  // ...  more properties
} & React.HTMLAttributes<HTMLUListElement>;
```

I am getting a TS error when I try to assign a handler like the one defined for the `onSelect` property:
> Type '(selected: string[]) => void' is not assignable to type '((selected: (string | number)[], payload: any) => void) & ReactEventHandler<HTMLUListElement>'.
  Type '(selected: string[]) => void' is not assignable to type 'ReactEventHandler<HTMLUListElement>'.
    Types of parameters 'selected' and 'event' are incompatible.
      Type 'SyntheticEvent<HTMLUListElement, Event>' is missing the following properties from type 'string[]': length, pop, push, concat, and 25 more.

See the reproducible example here: https://stackblitz.com/edit/react-ts-tygjwx?file=App.tsx

### Reproduction/example

https://stackblitz.com/edit/react-ts-tygjwx?file=App.tsx

### Steps to reproduce

Just assign a handler like `(selected: Array<string | number>) => console.log(selected)` to the `onSelect` prop from `TreeView` component, using Version `1.64.0-rc.0`, I get an error on that property. (See reproducible example).

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by jacobodeharo**
Closes [#17151](https://github.com/carbon-design-system/carbon/issues/17151)

### CODE REVIEW

**Comment by jacobodeharo** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by jacobodeharo** [comment]
> Hey @jacobodeharo I see that he CI is failing. Try to run `yarn test -u` to see if it fixes some of those issues.

Done!

**Review by guidari — APPROVED** [review]
LGTM!  🚀
Thanks!

**Review by emyarod — APPROVED** [review]
looks good to me!

**Pull request merged**
