### PR TITLE
chore(project): add www for support stats

### PR DESCRIPTION
**Pull request by joshblack**
This PR adds in our experiment for tracking support and overall scaffolds a Next.js app that we can use for other project opportunities that we've been spinning up one-off apps for 👀 

#### Changelog

**New**

- Add `www` package as a Next.js app

**Changed**

**Removed**

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
@joshblack I pulled it down and ran it, I see the index page 👍 

Should I be able to see anything meaningful from the `insights` route? Navigating to `http://localhost:3000/insights/carbon-design-system/carbon` gives me an error.

```
Server Error
Error: ENOENT: no such file or directory, open '/Users/taylorjones/dev/carbon/monorepo/www/data/snapshot.json'

This error happened while generating the page. Any console logs will be displayed in the terminal window.
```

**Comment by joshblack** [comment]
@tay1orjones ah yeah, you'll need to run:

```bash
export GH_TOKEN=<your-gh-token>
node tasks/collect.js
```

And that should populate the data to see!

**Comment by joshblack** [comment]
bump @aledavila

**Review by aledavila — APPROVED** [review]
lgtm

**Pull request merged**
