### PR TITLE
refactor(17034): deprecate alternative status in notifications

### LINKED ISSUE #17034: Notification: deprecate alternative status inline notifications
## Acceptance criteria

- [ ] Deprecate the `warning-alt` and `info-square` alternative status inline notification options since they are not being used and it will streamline our notification status options. 
- Refer to the telemetry metrics in [this issue](https://github.com/carbon-design-system/carbon-design-kit/issues/812#issuecomment-2236853495)

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes https://github.com/carbon-design-system/carbon/issues/17034

This PR deprecates `warning-alt `and `info-square` alternative status  so we can ensure consumers know to stop using them.

NOTE : 

`warning-alt `and `info-square`  are used across all types of notifications

1. ActionableNotification
2. InlineNotification
3. StaticNotification

**I have deprecated this for all, let me know if this is only required on **`InlineNotification`****

#### Changelog

**New**

uses deprecateValuesWithin() to pop a warning in console when a deprecated value is used

**Changed**

Snapshot updated

#### Testing / Reviewing

Pass any desecrated value  and verify that console warns about deprecated usage
(I have updated in storybook examples with desecrated values to help verify this quick , just visit notification component and verify the margin present in console ) story book changes will be removed before merging

### CODE REVIEW

**Comment by alisonjoseph** [comment]
This looks good, one question, can we bring back the dropdown control for the kind prop on the playground story?

**Review by alisonjoseph — APPROVED** [review]

**Comment by 2nikhiltom** [comment]
Hey @alisonjoseph !
Yes, updated `Playground.argTypes` to include the dropdown control for the kind prop on the playground stories

**Comment by 2nikhiltom** [comment]
Hey ! As discussed with Thy this is currently on hold as design team may have to consider those icons again

**Comment by thyhmdo** [comment]
hi @2nikhiltom turns out that we're not deprecating these icons so I think we can just close this issue without resolving it for now. Thanks for the patience!

**Pull request closed without merging**
