### PR TITLE
Fix(Dropdown): Made the titleText required property

### LINKED ISSUE #17843: [Bug]: Dropdown props.titleText is marked as optional in typescript but required in prop-types
### Package

@carbon/react

### Browser

_No response_

### Package version

1.68.0

### React version

_No response_

### Description

In typescript, the `titleText` prop is marked as optional while in the propTypes it's defined as required. This causes a warning in the console even if TS validation succeeds.

https://github.com/carbon-design-system/carbon/blob/b5430795bc444c65e3561b6c64c5566cadc6906c/packages/react/src/components/Dropdown/Dropdown.tsx#L222

https://github.com/carbon-design-system/carbon/blob/b5430795bc444c65e3561b6c64c5566cadc6906c/packages/react/src/components/Dropdown/Dropdown.tsx#L799

### Reproduction/example

-

### Steps to reproduce

```tsx
import { Dropdown } from '@carbon/react';

function MyComponent() {
  return (
    <Dropdown
      id="id"
      label="Label"
      items={['Lorem', 'ipsum', 'dolor']}
    />
  );
}
```

This passes TS validation but fails propTypes validation.

### Suggested Severity

Severity 4 = Unrelated to a user task, has a workaround or does not need a workaround.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by Thamjith**
Closes #17843

This PR makes the `titleText` an optional property in the propTypes, since we are only showing `titleText` conditionally.

#### Changelog

**Changed**

- Made the `titleText` optional in propTypes.

#### Testing / Reviewing

- Remove the `titleText` property from <Dropdown /> in _"packages/react/src/components/Dropdown/Dropdown.stories.js"_
- Navigate to the **packages/react** directory using `cd packages/react` and run `yarn storybook`
- Check the console in browsers's developer tools

### CODE REVIEW

**Comment by Thamjith** [comment]
recheck

**Comment by Thamjith** [comment]
recheck

**Review by tay1orjones — CHANGES_REQUESTED** [review]
I think this should be required even though it's conditionally rendered.

* https://github.com/carbon-design-system/carbon/issues/12809
* https://github.com/carbon-design-system/carbon/pull/13016

**Comment by Thamjith** [comment]
@tay1orjones updated the code to make the titleText property required instead of optional.

**Review by tay1orjones — APPROVED** [review]
LGTM!

**Comment by annawen1** [comment]
There was a duplicate ticket and the fix was already merged in https://github.com/carbon-design-system/carbon/pull/17886, but I'm going to go ahead and approve so @Thamjith can get credit for his contribution!

**Review by annawen1 — APPROVED** [review]

**Pull request merged**
