### PR TITLE
fix(text-input): match experimental spec

### LINKED ISSUE #1944: [Audit] Text input
text input - white theme

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1944

This PR incorporates feedback from the February 2019 audit for the text input component

### CODE REVIEW

**Comment by asudoh** [comment]
@emyarod Just double-checking if you are doing more work here...? (As this PR is in draft state)

**Comment by emyarod** [comment]
@asudoh just wanted confirmation first that the remaining changes should for all form elements before changing this PR's status

**Comment by tw15egan** [comment]
I would move those to a proper form audit, as they will affect more than just this component

**Comment by asudoh** [comment]
@emyarod Given we are separating out ones affecting form elements code - Any list wrt what should be reviewed in this PR? Thanks!

**Comment by emyarod** [comment]
@asudoh the original ticket #1944 (only the checked boxes) contains the list of changes that this PR includes. The remaining unchecked boxes will be addressed as part of the Form component audit

**Review by tw15egan — APPROVED** [review]
This looks great! Only thing I noticed is that the examples for V9 have the icons still shown. ANy easy way to hide them on V9?

screen shot 2019-03-01 at 10 11 36 am

**Comment by emyarod** [comment]
yes @tw15egan it should be fixed now

**Comment by aagonzales** [comment]
I want to make sure the help text issues get addressed first before approving this: 
https://github.com/IBM/carbon-components/issues/1944#issuecomment-468055824

**Comment by emyarod** [comment]
I've opened https://github.com/IBM/carbon-components/pull/1968 to address the form component issues

**Comment by emyarod** [comment]
#1968 has been merged, bump for re-review

**Comment by emyarod** [comment]
from https://github.com/IBM/carbon-components/issues/1997

### 2. Remove right padding on helper text in mobile

**Problem:**
Right padding is correct at all other breakpoints... we want to keep it, but allow helper text to go full screen at mobile. Otherwise we lose too much real estate. This fix needs to be made on Text Input component @aagonzales 

- [ ] Remove right padding on helper text in mobile

**Review by aagonzales — COMMENTED** [review]
Input without helper text should have 8px padding between label and field:
image

Also I'm still seeing the rounded corner on mobile devices in this issue, just wanted to check on it since it says it being fixed with this PR https://github.com/IBM/carbon-components/issues/2001

**Comment by emyarod** [comment]
@aagonzales I will open a new issue to refactor the label + helper text + component/label + component margins since it affects all form items, and I just opened PR #2002 to address #2001 since it addresses more than just text input

marking this PR as blocked until those issues are resolved

**Comment by emyarod** [comment]
this should be ready to go after #2007 and #2011 are merged in

**Comment by asudoh** [comment]
Both #2007 and #2011 have been merged in - Changing this to ready-to-review state. @aagonzales Does the latest visual look good to you...? Thanks!

**Review by aagonzales — APPROVED** [review]
Yup, looks like everything is to spec now!

**Pull request merged**
