### PR TITLE
docs(storybook): add type token switcher

### LINKED ISSUE #4329: Add ability to change type tokens in theme switcher
In v10.7.0, we shipped support for type tokens in our themes. However, our theme panel in storybook only supports swapping out the color theme. In order to allow design to review how a component changes with respect to type changes, we will need to provide a way for designers to change the type for a given component story. This change could mean:

- Switching between productive and expressive themes
- Bumping the base font-size

### PR DESCRIPTION
**Pull request by emyarod**
Closes #4329

This PR creates a storybook addon for modifying Carbon type token font size and line height. When a type token font size/line height pairing is selected for a particular type token, the corresponding custom properties for those rules is modified

#### Changelog

**New**

- Carbon Type storybook addon

**Changed**

- rename Carbon Theme switcher addon vars and components

#### Testing / Reviewing

Change type token font size/line height pairings in the new Carbon Type storybook panel

Ensure the type tokens change as expected and are reflected in the DOM and storybook

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by laurenmrice — APPROVED** [review]
🎉

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! Out of curiosity, is there any way to quickly tell which type token applies to the component? I just changed random ones until I found one that changed the component

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@abbeyhrt really the only fast way is to inspect the styles, sadly 😞 There is the SassDoc too that might help: https://github.com/carbon-design-system/carbon/blob/master/packages/components/docs/sass.md#accordion-mixin

**Pull request merged**
