### PR TITLE
fix(multi-select): add styles for filterable multiselect inputs

### LINKED ISSUE #2264: Filterable Multiselects with items selected have broken styles
image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2264 

This PR adds styles for the input fields in the filterable multi select component

#### Changelog

**New**

- filterable multi select exposed in docs

**Changed**

- adjust left padding of filterable multi select input field. Note: this value will need to be adjusted by the consumer based on the number of selections in the component. i.e. the input field needs adjusted padding to account for the width of the number in <ListBox.Selection>

#### Testing / Reviewing

Ensure that the filterable multiselect is displaying properly

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
if the new class is approved, the migration doc will need updates as well

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] There needs to be 8px padding from the left of the tag and to the right of the tag (before text)
Screen Shot 2019-04-04 at 2 46 04 PM

**Review by laurenmrice — APPROVED** [review]
looks good to me 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
