### PR TITLE
FIX: New geometry 32 switcher, overflow menus

### PR DESCRIPTION
**Pull request by chrisconnors-ibm**
spacing adjustments to 32/switcher and app-switcher, 32/overflow-menu--*, and removed  16, 20, 24 variants. adjustments reduce or eliminate the need for bespoke assets at the scaled sizes.

**app-switcher:**
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fapp-switcher
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fapp-switcher%20(Downsized%20to%2024)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fapp-switcher%20(Downsized%20to%2020)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fapp-switcher%20(Downsized%20to%2016)

**switcher:**
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fswitcher
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fswitcher%20(Downsized%20to%2024)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fswitcher%20(Downsized%20to%2020)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Fswitcher%20(Downsized%20to%2016)

**overflow-menu--horizontal:**
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--horizontal
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--horizontal%20(Downsized%20to%2024)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--horizontal%20(Downsized%20to%2020)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--horizontal%20(Downsized%20to%2016)

**overflow-menu--vertical:**
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--vertical
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--vertical%20(Downsized%20to%2024)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--vertical%20(Downsized%20to%2020)
https://deploy-preview-5314--carbon-elements.netlify.com/icons/examples/preview/#32%2Foverflow-menu--vertical%20(Downsized%20to%2016)

### CODE REVIEW

**Comment by joshblack** [comment]
Would you mind keeping the deprecated assets btw? We currently still need them to support folks without doing a breaking change 😬

**Comment by chrisconnors-ibm** [comment]
PR only removes 16/20/24 of app-switcher and switcher, overflow-menu--* (in order to test scaled outcomes of adjusted 32 assets), shouldn't break anything.

**Comment by joshblack** [comment]
Got it, my mistake! Thanks @chrisconnors-ibm

**Review by joshblack — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]

**Review by conradennis — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Comment by chrisconnors-ibm** [comment]
What’s the mechanism that triggers a re-run of the plugin? Just a new issue?

**Comment by joshblack** [comment]
@chrisconnors-ibm yeah, we'll capture this with our other icon work, I think.

**Pull request merged**
