### PR TITLE
fix(react): fixed styling of med size search component

### LINKED ISSUE #11169: [Bug]: Search size prop with md value icon is misaligned in carbon 11
### Package

@carbon/react

### Browser

Firefox

### Package version

v11

### React version

v18

### Description

I noticed that for the `Search` component in carbon 11 that it has a `size` prop and passing in sm and lg values are fine, but passing in md the icon has no padding or something 

image
image

### CodeSandbox example

N/A

### Steps to reproduce

See Description 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by TannerS**
The Search component has some extra css styling just for md size.
Which seems to make a breaking positioning for the icon.
This fix removes this without affecting any other styling

Closes #11169

#### Closes 

Found this issue but not yet reported if this issue is valid or not. But I opened up a PR to be ready with a possible fix if so. 

#### Changelog

**Removed**

- Removed extra set of stylings for the `md` size for the `Search` component. I am no sure why this styling was added as it seems to not affect anythign when removed but fix the issue at hand. 

Tagging @joshblack since he was on the blame for this and may have some insights! 

#### Testing / Reviewing

Ran unit test and verified `Search` component on storybook

### CODE REVIEW

**Comment by TannerS** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by TannerS** [comment]
recheck

**Review by dakahn — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Comment by alexandertrefz** [comment]
Is anything holding this PR up?

**Comment by tay1orjones** [comment]
@alexandertrefz Nothing holding it up, I think we just forgot to turn on auto-merge. Sorry for the delay, this should be merged shortly!

**Comment by TannerS** [comment]
@tay1orjones  or @joshblack  is this change released in prod yet ?

**Comment by tay1orjones** [comment]
@TannerS Yeah, looks like the commit merged in was tagged with `v11.2.0`, so should be released. Equivalent `@carbon/react` version would be `v1.2.0`

**Pull request merged**
