### PR TITLE
chore(tile): update storybook to show tile

### LINKED ISSUE #11097: Fix `Tile` storybook docs page
The following are not showing previews in the doc section:

- [x] Breadcrumb
- [x] DataTable
- [x] Loading
- [x] OrderedList
- [x] Pagination
- [x] Slider(missing props)
- [x] StructuredList (missing props)
- [x] Tile
- [x] Toggle (missing props)
- [x] Tooltip Icon
- [x] Unordered List
- [x] Heading

### PR DESCRIPTION
**Pull request by aledavila**
Closes #11097 

Update storybook tile and add examples to docs

#### Changelog

**New**

- added tile variants to docs examples
- added mdx file so that tile docs appear

#### Testing / Reviewing

Make sure tile storybook is good. Make sure tile docs appear and props show correctly.

### CODE REVIEW

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Are the tiles missing some default text styles? @carbon-design-system/design

<details>
  <summary>The default and expandable tile text styling is different than clickable</summary>
  
  
image
image
image
</details>



The [selectable with layer story](https://deploy-preview-11182--carbon-components-react.netlify.app/?path=/story/components-tile--selectable-with-layer) doesn't work and gives a minified react error.

Docs page looks great! 🎉

**Comment by laurenmrice** [comment]
- The text in all tile variants can use `$body-compact-01` as a default type token in our examples. When a link is shown in a tile it should be using the medium size link (which is also at `$body-compact-01`). Teams can change these tokens depending on their usecase if they need a larger/different heading and link size, etc.

- We should not be referencing `light` in the docs. This appears on the Docs tab and on the Canvas tab --> Controls.
- Also noticed a couple bugs unrelated to this PR which I will add to the open v11 Tile audit issue.

**Comment by aledavila** [comment]
@laurenmrice thanks Lauren for taking a look I will update that accordingly

**Comment by aledavila** [comment]
@laurenmrice @tay1orjones updated the storybook and fonts can you recheck please

**Review by tay1orjones — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Pull request merged**
