### PR TITLE
fix(icons): rename indeterminate checkbox icon

### LINKED ISSUE #3783: "Undeterminate" should be "indeterminate" for checkbox icon name
There is a typo where `undeterminate` should be `indeterminate`

- [ ] replace the `u` with an `i`

|Current state | Expected state |
|---|---|
|`Checkbox undeterminate filled`|`Checkbox indeterminate filled`
|`Checkbox undeterminate`|`Checkbox indeterminate`|

image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3783

#### Changelog

**Changed**

- indeterminate checkbox icon name

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by asudoh — COMMENTED** [review]
LGTM basically, one question; What happens to existing applications that use our `v10.x` of `undeterminate` checkbox icon?

**Comment by emyarod** [comment]
if this is considered a breaking change I can add the `undeterminate` file and metadata back and make a note to remove it in v11

**Comment by chrisconnors-ibm** [comment]
name also needs to change where referenced in the Sketch kit(s). may be picked up in the generation step though.

**Comment by joshblack** [comment]
@emyarod would you mind adding in the fallback just to prevent the breaking change? We need to figure out this deprecation workflow, for sure, but until then I think that'd be enough to help out here.

**Comment by emyarod** [comment]
added the old files and metadata back

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
