### PR TITLE
feat: add read only time picker

### LINKED ISSUE #12409: [Read-only inputs]: Timepicker implementation
image

image

#### Acceptance Criteria

- [ ] Coded component in `/package/react`
- [ ] Add a prop for read-only, add styles for said prop
- [ ] Controls for each state in playground
- [ ] Default story for easy copy and paste
- [ ] RTL tests for the read-only class on the prop

### PR DESCRIPTION
**Pull request by lee-chase**
Contributes to #2177

Closes #12409 

Adds the read-only feature to the TimePicker component.

#### Changelog

**Added**

- Adds readOnly property to TimePicker and functionality
- Adds test for read-only TimePicker
- Adds styling for read-only TimePicker.

- Fixes disabled dropdowns. Could move this to a separate PR but relies upon work required for this too.

#### Testing / Reviewing

Reviewed the result in Storybook and a added read-only test.

### CODE REVIEW

**Review by aagonzales — CHANGES_REQUESTED** [review]
Visual styles are correct but cursor interactions need to be updated.
- On hover the cursor should remain as an arrow and not switch to the hand.

**Comment by lee-chase** [comment]
@aagonzales @quarryboy adjusted the cusror. One thing to note is that this leaves use with the odd situation that it is possible to select and copy the time, but not AM/PM or timezone.

**Review by aagonzales — APPROVED** [review]
Visually looks good, matches spec 👍

**Review by alisonjoseph — APPROVED** [review]
LGTM once merge conflicts are fixed

**Review by tw15egan — APPROVED** [review]
@lee-chase cleaned up the merge conflicts, everything else looks great to me 👍🏻 ✅

**Pull request merged**
