### PR TITLE
docs(deployment): add docs for deploying changes

### PR DESCRIPTION
**Pull request by joshblack**
Adds documentation for deploying changes to IBM Cloud for Pull Requests.

#### Changelog

**New**

- `docs/deploying-changes.md`

**Changed**

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @lovemecomputer

**Comment by lovemecomputer** [comment]
rad, thanks for the info @joshblack . sorry looks like i still can't review

**Review by asudoh — COMMENTED** [review]
Thank you for writing this up @joshblack! Do you want to add `gulp scripts:dev --rollup` as a step to reflect dev’s change to what’s pushed to CF? Thanks!

**Comment by joshblack** [comment]
Hi @asudoh! Is that step captured in `yarn build`, or not?

**Comment by asudoh** [comment]
@joshblack No - `gulp scripts:dev --rollup` is for creating a staging build for dev, whereas `yarn build` is for creating a production build.

**Review by alisonjoseph — APPROVED** [review]
lgtm after you address Akiras latest comment

**Review by aledavila — APPROVED** [review]
LGTM

**Comment by lovemecomputer** [comment]
thanks for this!

**Comment by joshblack** [comment]
@asudoh is that just for JavaScript files? Was trying to see if it did styles, as well.

**Comment by asudoh** [comment]
@joshblack Oops good question - We should: `gulp build:dev --rollup`

**Comment by joshblack** [comment]
Added 👍

**Pull request merged**
