### PR TITLE
fix(fonts): warn usage of default font path

### LINKED ISSUE #1011: pointing to font @ latest causes errors
## Detailed description

We use carbon in our application. We keep carbon locked to a specific version so that we can control when we get updates. Part of the testing we do involves visual regression testing (vrt), which can catch the most minor differences a styling change might have. We noticed our vrt tests we being inconsistent, but almost always due to typography. This error is caused by a non-locked version of plex.

in [_css--plex-core.scss](https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_css--plex-core.scss) you create `$font-path` with this line:

`$font-path: 'https://unpkg.com/carbon-components@latest/src/globals/fonts' !default;`

But because you choose to use `@latest`, then any application that ingests Carbon is forced to always use the _latest_ version of plex. Recently there was an update to plex, but not an update to carbon, and now a majority of our vrt tests are failing.

## Additional information

screen shot 2018-08-02 at 9 31 17 am
screen shot 2018-08-02 at 9 32 05 am

## Solution

Lock your `$font-path` to a specific version of plex

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #1011.

#### Changelog

**New**

- Warning message when default `$font-path` is in use.

#### Testing / Reviewing

Testing should make sure our CSS, especially font usage, is not broken.

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
This feels like a large diff for what is potentially just an `@if` block. Just was thinking something like:

```
$font-path: '...' !default;
// ...
@if (str-index($font-path, 'https://unpkg.com' == 1)) {
  @warn '...';
}
```

Is there some increased scope/edge cases that we need to support for the form present in the diff?

**Comment by asudoh** [comment]
Hi @joshblack if you select Diff settings - Hide whitespace changes or you use https://github.com/IBM/carbon-components/pull/1040/files?w=1 you see the diff is way smaller - Hope this helps!

**Comment by joshblack** [comment]
Totally, just trying to understand the machinery behind the change, that's all. I think with/without whitespace that question is still there.

**Comment by asudoh** [comment]
OK just to avoid duplication of the same logic, but if you prefer replicating `str-index`, or you meant something else, let me know - Thanks!

**Comment by joshblack** [comment]
Ah, that's why. Didn't know that `font-path` was used in two locations, thanks!

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by joshblack — APPROVED** [review]

**Pull request merged**
