### PR TITLE
fix(code-snippet): Update templates

### PR DESCRIPTION
**Pull request by alisonjoseph**
## Overview

Updates hbs template for new code snippet updates

### Testing

Make sure all variants are showing up and working for code snippet.
```
- single
- multi
- inline
- inline light
```

### CODE REVIEW

**Comment by asudoh** [comment]
Hi @alisonjoseph do you mean client-side JavaScript (`CodeSnippet` class) or something else? Also should we merge https://github.com/carbon-design-system/carbon-components/pull/774 to this PR (or does this PR supercede #774?)?

**Comment by alisonjoseph** [comment]
I had a typo 😉 

Oops, I forgot about #774 I think this will supercede it, but will make sure everything in there is here before closing it. Thanks!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks alot @alisonjoseph for merging #774 and getting code snippet working again!

**Review by marijohannessen — APPROVED** [review]
👍  ✅

**Comment by alisonjoseph** [comment]
@asudoh just realized that the show more/less button only works sometimes? Any ideas? 😞

**Review by tw15egan — APPROVED** [review]
Looks great! 👍

**Comment by tw15egan** [comment]
@alisonjoseph I'm seeing that as well. It seems like it only happens when the click originates from the `svg`. I know @asudoh has fixed event propagation with `svg` in other components, I'm guessing this might be a similar situation. Number Input (the down / up arrows) might have a similar workaround

**Pull request merged**
