### PR TITLE
fix(list-box): Fix top calculation as all browser don't handle it the…

### PR DESCRIPTION
**Pull request by DusanMilko**
… same and clean up variation

Not all browsers calculate the vertical or horizontal position the same so base valued should be added. This fixes positions in ie, firefox and other browsers

#### Changelog

**Changed**

- added top for list box since not all browsers calculate this correctly when not specified

**Removed**

-  removed unnecessary classes for up variation of list box

### CODE REVIEW

**Comment by joshblack** [comment]
Hey there @DusanMilko! 👋 Thanks for taking the time to make this PR 🙏 Would you mind providing some additional information so we can understand what the issue is that this PR is solving? 👀

**Comment by DusanMilko** [comment]
@joshblack In some browsers if a position absolute element does not have a top value specified it will calculate it incorrectly. This can be seen in ie11 and certain version of firefox and some mobile browsers.

**Comment by emyarod** [comment]
I'm not seeing an issue with listbox menus in IE11, can you describe how to replicate the issue or create a code sandbox that shows the problem?

**Comment by joshblack** [comment]
Hey there @DusanMilko! 👋 Just wanted to check-in to see if you had a sec to respond to @emyarod's question above.

**Comment by tw15egan** [comment]
Closing due to inactivity, feel free to reopen if you have time to clarify

**Pull request closed without merging**
