### PR TITLE
Re-enabled All-Contributors to help recognize public maintainers of Carbon

### LINKED ISSUE #6963: Re-enable All-Contributors to help recognize public maintainers of Carbon
Back in the day, we had the `all-contributors` [plugin](https://github.com/all-contributors/all-contributors) enabled that would populate our readme with a nice grid of our contributors and their contributions. 
> Link: https://www.npmjs.com/package/carbon-components#contributors

Screen Shot 2020-10-02 at 10 31 58 AM

Coupled with an effort to showcase individuals who help maintain Carbon on the main Carbon website, this could be used as the source of truth. I would imagine we would also enable this plugin on the `carbon-website` repo as well.

Plugin: https://github.com/all-contributors/all-contributors
Possible automation: https://allcontributors.org/docs/en/bot/overview

### PR DESCRIPTION
**Pull request by NishithP2004**
Closes #6963 

Hi, I have added all the necessary files for the ``all-contributors bot``  to function, please have it installed to this repo to complete the installation process.

#### Changelog

**New**

- ``all-contributors bot`` added

#### Testing / Reviewing

Once merged, install the ``all-contributors`` bot via Github and run the following command to check if it works: ``@all-contributors please add NishithP2004 for plugin``

[all-contributors bot](https://github.com/apps/allcontributors/installations/new) -- Installation link on Github

### CODE REVIEW

**Comment by NishithP2004** [comment]
@all-contributors please add NishithP2004 for plugin

**Review by emyarod — COMMENTED** [review]
it looks like you need to run `prettier` to format the changed files in order to pass CI

**Comment by NishithP2004** [comment]
> it looks like you need to run `prettier` to format the changed files in order to pass CI

Hi, I tried formatting it with ``prettier`` but it doesnt seem to work, Could you please assist me with the same.

**Comment by emyarod** [comment]
you may want to try running [`yarn format`](https://github.com/carbon-design-system/carbon/blob/master/package.json#L24) in the repository root

**Comment by tw15egan** [comment]
@NishithP2004 should just need to run `yarn format -u` from root, add and commit the changes. 👍

**Comment by NishithP2004** [comment]
> @NishithP2004 should just need to run `yarn format -u` from root, add and commit the changes. 👍



> you may want to try running [`yarn format`](https://github.com/carbon-design-system/carbon/blob/master/package.json#L24) in the repository root

$ yarn format                                                                                                           yarn run v1.22.5                                                                                                        warning package.json: No license field                                                                                  error Command "format" not found.                                                                                       info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.          

Im getting this error

**Comment by NishithP2004** [comment]
> > @NishithP2004 should just need to run `yarn format -u` from root, add and commit the changes. 👍
> 
> > you may want to try running [`yarn format`](https://github.com/carbon-design-system/carbon/blob/master/package.json#L24) in the repository root
> 
> $ yarn format yarn run v1.22.5 warning package.json: No license field error Command "format" not found. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
> Im getting this error

Thank you :)

**Review by tw15egan — APPROVED** [review]
Thanks for adding that in! I will enable the bot once we've got this merged.

**Review by dakahn — APPROVED** [review]

**Pull request merged**
