### PR TITLE
fix(styles): v11 OverflowMenu audit changes

### LINKED ISSUE #10424: Overflow-menu: v11 audit
## Audit
A designer and developer will pair on this audit, some tasks may be discipline focused. Follow the checklist below for the features and items to review. If there are no issues with the item then check the item as complete. If any problems or bugs come up when auditing add a comment to this issue with the problem and how to correct it (if you know how). Bugs do not need to be fixed while auditing. 

## Resources
- [Design spec in Sketch](https://ibm.box.com/s/v4hk50eol2wkurvtxz295kw6pz094lq5)
- [V11 Website](https://v11.carbondesignsystem.com/)
- [SCSS](https://github.com/carbon-design-system/carbon/tree/next/packages/components/src/components)
- [Storybook](https://carbon-react-next.netlify.app/?path=/story/getting-started-welcome--welcome)

## Checklist

**Visual** (in React code) 
_Design and dev check_
- [x] Component is using the correct design tokens (color and type), see design spec and scss code.
- [x] Component is rendering correctly across themes and layers, see design spec and storybook.
    - [x] White theme
    - [x] Gray 10 theme
    - [x] Gray 90 theme
    - [x] Gray 100 theme
- [x] Component is rendering correctly across browsers (check themes across browsers as well), see storybook.
    - [x] Firefox
    - [x] Safari
    - [x] Chrome
- [x] Component sizes are rendering and named correctly ([if applicable](https://v11.carbondesignsystem.com/migrating/guide/develop#size-prop-updates-breaking))

 **Website** (v11)
 _Design checks_
- [ ] Style tab has correct design tokens listed 
- [ ] Style and usage tabs are using the correct [size props](https://v11.carbondesignsystem.com/migrating/guide/design#sizing) names (if applicable)
- [ ] Usage tab is up-to-date for with any [v11 behavioral](https://v11.carbondesignsystem.com/migrating/guide/develop#changelog) changes (if any)
- [ ] Live Demo has applied v11 changes
   - [ ] Themes are rendering correctly
   - [ ] Size props are named correctly
   - [x] No `light` props included

**Design Kits** (Sketch only)
 _Design checks_
- [x] Correct design tokens (type and color) are used
- [ ] Component using the correct size prop names
- [x] Any additional v11 behaviors have been added

**Storybook**
 _Dev checks_
- [ ] Confirm that prop table is populating 
- [x] Take note of missing examples/stories (if any)

**React package**
 _Dev checks_
- [x] Go to https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox and confirm that you can use the component as expected from `@carbon/react` 

**Accessibility** 
 _Dev checks_
- [x] Confirm that there are no violations in Accessibility checker
- [x] Confirm that component works as expected with VoiceOver

**Migration docs**
_Design and dev check_
- [x] Any breaking changes to this component are present in the v11 [migration guide](https://v11.carbondesignsystem.com/migrating/guide/overview).
   - [x] Design
   - [x] Develop

### LINKED ISSUE #10551: Priority list for component audit - development
_Each component in a subsection could be audited in any order, the sections are overall listed by priority._ 

**Big v11 changes or very commonly used:**
- [x] https://github.com/carbon-design-system/carbon/issues/10413
  - just since it’s a big component that so many people use. 
- [x] https://github.com/carbon-design-system/carbon/issues/10422
- [x] https://github.com/carbon-design-system/carbon/issues/10439
   - Definition Tooltip
- [x] https://github.com/carbon-design-system/carbon/issues/10438
- [ ] Grid
- [x] https://github.com/carbon-design-system/carbon/issues/10412
- [x] https://github.com/carbon-design-system/carbon/issues/10409
- [x] https://github.com/carbon-design-system/carbon/issues/10440
  - HeaderNavigation and SideNavMenu have v11 specific changes

**Refactored to functions:**
- [ ] ComposedModal
- [ ] DatePicker/DatePickerInput 
- [x] https://github.com/carbon-design-system/carbon/issues/10596
- [ ] Modal
- [ ] NumberInput
- [x] https://github.com/carbon-design-system/carbon/issues/10424
- [ ] Pagination
- [ ] RadioButton
- [ ] Search
- [ ] Structured List
- [ ] Tile
- [ ] TimePicker/TimePickerSelect
- [ ] Toggle

**Wrapped in createClassWrapper:** 
- [ ] Slider
- [ ] FileUploader

**New Components:**
- [ ] Layer
- [ ] Popover
- [ ] IconButton
- [ ] Stack
- [ ] Theme
- [ ] ProgressBar(?)
- [ ] TreeView(?)

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #10424 

#### Changelog

- updates tokens based on https://github.com/carbon-design-system/carbon/issues/10424#issuecomment-1058169988

#### Testing / Reviewing

- Ensure v11 OverflowMenu looks as expected
- Ensure tests pass

### CODE REVIEW

**Review by laurenmrice — COMMENTED** [review]
I am still not seeing the props for `Flipped (flipped)` and `Menu direction (direction)` in the react storybook. Is this being solved in a different PR? @jnm2377

**Comment by jnm2377** [comment]
> I am still not seeing the props for `Flipped (flipped)` and `Menu direction (direction)` in the react storybook. Is this being solved in a different PR? @jnm2377

@laurenmrice see https://github.com/carbon-design-system/carbon/issues/10424#issuecomment-1062272929 and https://github.com/carbon-design-system/carbon/issues/10424#issuecomment-1062307937

**Review by laurenmrice — APPROVED** [review]
@jnm2377 Oh, thank you! Didn't scroll down all the way :). Looks good !

**Review by abbeyhrt — APPROVED** [review]
🎉

**Review by aledavila — APPROVED** [review]

**Pull request merged**
