### PR TITLE
Feat/notification icon

### PR DESCRIPTION
**Pull request by webadam1**
It's now possible to pass an icon to the notifciation components as an elementType prop, which will overwrite the default icon that's based on the notification kind.

#### Changelog

**New**

- Add icon prop to InlineNotification, ToastNotification and NotificationIcon

**Changed**

- The iconDescription prop was mistakenly supplied to the decorative icon displayed on the left side of the notification as well as the close icon. I renamed the close icon's description prop to closeIconDescription, and iconDescription now only gives description to the decorative icon.

**Removed**

#### Testing / Reviewing

Trying the ToastNotification and InlineNotification components with and without an icon prop supplied to them should be enough. The icon prop should optimally be a carbon icon component from icons-react.

### CODE REVIEW

**Comment by asudoh** [comment]
Hi 👋 seems that you are trying to add custom icon there. Any reason background why...? Also we encourage people writing issues first except for minor chores. Thanks!

**Comment by webadam1** [comment]
Hi! While building a page we came across the limitation of the notification component. We wanted to create a notification that tells the user that file uploading is in progress and they should not close the window.
The Carbon design system guideline says about notification icons that "Icons may provide additional clarity. Icons should be placed to the left of a title."
In our use case the designer figured a warning notification with a rotating 'renewal' icon would provide more clarity about the notification's message than the standard warning icon. Our understanding is that the guideline says nothing about the icons being limited to the three we are currently using based on the notification kind, so I thought an extension like this would benefit the component.
Yes you are right about the issue part, should I now create one?

**Comment by asudoh** [comment]
Thank you for clarifying.

> Yes you are right about the issue part, should I now create one?

Please, with that we can discuss the design with our Carbon designers.

**Comment by webadam1** [comment]
Created the issue 👍
https://github.com/carbon-design-system/carbon/issues/3699

**Comment by jnm2377** [comment]
Hi @webadam1 We appreciate your interest in contributing to Carbon! ❤️ However, I'm closing this PR based on https://github.com/carbon-design-system/carbon/issues/3699#issuecomment-521806577 design feedback. If your team is interested in contributing an uploading notification, we would love to see some proposed designs in an issue and a subsequent PR! 🙏

**Pull request closed without merging**
