### PR TITLE
Chas moseley content switcher radio

### PR DESCRIPTION
**Pull request by chas-moseley**
#### Changelog

**Changed**

- Create a content switcher component using radio buttons

#### Testing / Reviewing

Should be able to pass ADA testing with this version as versus the <button> style version while having the same look-and-feel to the user.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
it looks like the test suite needs to be updated to pass CI

**Comment by tw15egan** [comment]
@chas-moseley is there any issue associated with these changes?

**Comment by emyarod** [comment]
@tw15egan I believe it is this https://github.com/carbon-design-system/carbon/issues/5696

**Comment by chas-moseley** [comment]
The issue specified below is the correct one.
 
Note that I did not change any of the JavaScript code, but should.  And the test suite also needs to modified, but I will need some help with that because it is in a form of which I am not familiar.  .
 
 
Chas B. Moseley
Principal  Software Programmer 
Truven Health Analytics
an IBM company
Phone: 303-486-9185
cmoseley@us.ibm.com
 
 
----- Original message -----From: emyarod <notifications@github.com>To: carbon-design-system/carbon <carbon@noreply.github.com>Cc: chas-moseley <cmoseley@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [carbon-design-system/carbon] Chas moseley content switcher radio (#5891)Date: Mon, Apr 20, 2020 11:45 AM 
 
@tw15egan I believe it is this #5696

**Comment by asudoh** [comment]
Oops I just saw a comment saying that the JS change has not been done yet. Cleared the review state (reviewers my apologies), and turned the change to draft for now.

@chas-moseley Thank you for contributing - Feel free to turn this to "ready to review" state once your work is complete. I'm aware that several people brought up "styled radio button" notion for content switchers, but we haven't had a chance to try it out. BTW have you tried to see what screen render announces and how keyboard nav works with your approach...?

**Comment by chas-moseley** [comment]
I have not tested this fully with JAWS, but the initial results are good.  I see no errors from DAP.  Keyboard navigation is as expected for radios. 
 
May get to the JS in a couple of days.  Also noticed that I may need to clean up the unused CSS.  It is the test suite that concerns me because I do not know what system is being used.  I was hoping that maybe if I threw it out there someone would clean up after me.  ;)
 
 
Chas B. Moseley
Principal  Software Programmer 
Truven Health Analytics
an IBM company
Phone: 303-486-9185
cmoseley@us.ibm.com
 
 
----- Original message -----From: Akira Sudoh <notifications@github.com>To: carbon-design-system/carbon <carbon@noreply.github.com>Cc: chas-moseley <cmoseley@us.ibm.com>, Mention <mention@noreply.github.com>Subject: [EXTERNAL] Re: [carbon-design-system/carbon] Chas moseley content switcher radio (#5891)Date: Mon, Apr 20, 2020 6:37 PM 
 
Oops I just saw a comment saying that the JS change has not been done yet. Cleared the review state (reviewers my apologies), and turned the change to draft for now.
@chas-moseley Thank you for contributing - Feel free to turn this to "ready to review" state once your work is complete. I'm aware that several people brought up "styled radio button" notion for content switchers, but we haven't had a chance to try it out. BTW have you tried to see what screen render announces and how keyboard nav works with your approach...?

**Comment by asudoh** [comment]
We use Karma for vanilla JS testing and Jest for the rest. Let us know if you need any help on those.

**Comment by joshblack** [comment]
Hey there! 👋 Thanks so much for taking the time to make this Pull Request 😄 

We're going through and trying to clean up PRs that may have been around for a bit without much activity. Let me know if you'd like to keep working on this and we can always re-open it!

**Pull request closed without merging**
