### PR TITLE
feat(data-table-v2): use new type styles

### PR DESCRIPTION
**Pull request by vpicone**
ref: #1303

Use new type-style mixin behind a feature flag

#### **New**
- head and batch actions use `type-style('heading-01')`
- tbody uses `type-style('body-short-01')`

### CODE REVIEW

**Comment by vpicone** [comment]
@alisonjoseph @shinytoyrobots we might want to get this in during the freeze.

There's some font-weight changes that could alter rendering maybe?

**Review by aagonzales — APPROVED** [review]
That all looks correct to me

**Comment by jnm2377** [comment]
Since v10 stuff has its own mixin that is calling the updated type tokens, I don't think we need to have conditionals in the v9 mixins for this.

**Comment by vpicone** [comment]
@jnm2377 I could be wrong, but I was getting deprecation warnings for using typestyle (just for data-table-v2)

**Comment by jnm2377** [comment]
Maybe it's because it's used in the v9 mixin? the experimental mixin has the new tokens: https://github.com/IBM/carbon-components/blob/f6d325ef559351e95c13f4a86aa499b1433e1b69/src/components/data-table-v2/_data-table-v2-core.scss#L213-L222

I haven't opened a PR for batch actions so there's no mixin for it yet, but when it does get added it'll get the new type tokens as well.

**Comment by vpicone** [comment]
@jnm2377 gah you're super right haha still getting used to the mixins. 

Let me know if I can help with anything!

**Comment by asudoh** [comment]
@vpicone While @jnm2377 is right that elimination of deprecated mixin refs is waiting for data table code to complete, thank you for trying to help out @jnm2377 anyway - Great team work!

**Pull request closed without merging**
