### PR TITLE
fix(list-box): reset multiselect selection count position

### LINKED ISSUE #5404: Multiselect selection count not centered
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

after making a selection in the multiselect component, the selection count chip is no longer vertically centered in all browsers

image

related https://github.com/carbon-design-system/carbon/pull/5362

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5404

This PR resets the positioning of the selection counter for multiselects only

#### Testing / Reviewing

Ensure the selection counter is properly aligned for comboboxes and multiselects

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
Thank you for your quick fix @emyarod!

**Comment by emyarod** [comment]
looks like a11y tests are timing out?

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by aagonzales — COMMENTED** [review]
This is unrelated but can we have the title not wrap in the example. 
image

**Review by abbeyhrt — APPROVED** [review]

**Comment by emyarod** [comment]
@aagonzales that's because in storybook we're setting an arbitrary 300px width on the component container. if I remove the rule entirely we would end up with something like this for the non-inline multiselect (similar to the text input story) if that's alright

image

otherwise I can just bump up the container width but depending on your screen size you would still see the title wrap behavior

**Comment by aagonzales** [comment]
Ok i guess if its just the react storybook where that's happening then leave it (still not an ideal example), I'll just make sure the demo on the website doesn't do that.

**Review by aagonzales — APPROVED** [review]

**Comment by asudoh** [comment]
Got a green light to move this to "ready to merge" state - Thanks @emyarod!

**Pull request merged**
