### PR TITLE
refactor(react): update tests from DAP to AC

### PR DESCRIPTION
**Pull request by joshblack**
This PR is some clean-up for some of our old AAT files as they relate to DAP. It removes DAP files, matchers, and updates test files to use the new AC matcher.

#### Changelog

**New**

**Changed**

- Update Jest config to omit `toHaveNoDAPViolations`
- Update test files to use `toHaveNoACViolations`

**Removed**

- `aat` folder was removed
- `toHaveNoDAPViolations` was removed

### CODE REVIEW

**Comment by joshblack** [comment]
FYI @dakahn

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by joshblack** [comment]
bump @andreancardona let me know if you have any questions!

**Review by andreancardona — APPROVED** [review]
@josh looks good!

**Pull request merged**
