### PR TITLE
feat(Pictograms): new pictograms and categories v21

### PR DESCRIPTION
**Pull request by dudley-ibm**
Closes #

Closes following pictogram issues: 103/104/158/198/200/204/207/212

#### Changelog

New Categories added:
AI
Workplace

New pictograms and their (category):
flexible	(Action)
scalable	(Action)

trash--burnable	(Workplace)
trash--non-burnable	(Workplace)
cardboard	(Workplace)
waste--electronic	(Workplace)
literature	(Workplace)
library	(Workplace)
fountain--drinking	(Workplace)
station--hydration	(Workplace)
silence	(Workplace)
loop--hearing	(Workplace)

cloud--pal	(IBM) *Changed to carbon--for-cloud via Kevins request
carbon	(IBM)

storage--for-data-and-ai	(Data storage)
storage--for-resiliency	(Data storage)

ai-governance--model-tuned	(AI)
ai-governance--model	(AI)
ai-governance--prompt	(AI)
ai-governance--lifecycle-factsheet	(AI)

#### Testing / Reviewing

Please ensure all additions appear in both carbon design system and IBM Design Language sites. Thank you!

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by KevinCamelo** [comment]
Hi all @tw15egan @dudley-ibm, since its approval the name of the cloud-pal pictogram has been changed to carbon-for-cloud, in alignment with the other PALs at IBM. Is there anyway to change the name of that in the kit? 

Much appreciated. Please let me know how we can follow up if needed.

**Comment by tw15egan** [comment]
@KevinCamelo @dudley-ibm I've updated the file name [here](https://github.com/carbon-design-system/carbon/pull/15135/commits/8c5da67638f1206f1b67a22b68a4955b8cb08447#diff-17cfee3c274fcf6545c779f01208359f97e4cfc06ed3a5075041d55e232ae30a). Any changes to the kit will have to be made by someone else though

**Comment by KevinCamelo** [comment]
@tw15egan @laurenmrice Great!!! Thank you all so much for the quick action. It is much appreciated!

**Review by laurenmrice — APPROVED** [review]
Looks good!

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
