### PR TITLE
fix(BreadcrumbItem): remove href check for children of type string

### LINKED ISSUE #9224: React Breadcrumb uncaught error if string without href
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The breadcrumb has the option of last item being the current page. In this scenario the breadcrumb may well be a string with no href supplied. This however produces an unhandled error.

e.g.
```
    <BreadcrumbItem isCurrentPage={true}>
      The current page
    </BreadcrumbItem>
```

produces

image

It is possible to work around this by wrapping the text in a an element e.g.

```
    <BreadcrumbItem isCurrentPage={true}>
      <span>The current page</span>
    </BreadcrumbItem>
```

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

BreadcrumbItem

> What did you expect to happen? What happened instead? What would you like to
> see changed?

No unhandled error should occur

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

10.38

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

IBM Cloud Cognitive components package

## Steps to reproduce the issue

See above.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #9224

This PR resolves an uncaught type error where breadcrumbs without `href` s and with children of type string were incorrectly being processed as React elements

#### Changelog

**Changed**

- breadcrumb item typechecks
- add additional breadcrumb item to storybook examples

#### Testing / Reviewing

Confirm the breadcrumb stories function as expected with the added breadcrumb items

### CODE REVIEW

**Review by andreancardona — APPROVED** [review]
🎉

**Comment by tw15egan** [comment]
If a breadcrumb does not have a link, should it still be styled as a link?

**Comment by emyarod** [comment]
bump @jnm2377 when you have a chance

**Comment by emyarod** [comment]
I believe so assuming it is still interactive, but that would be left up to the application to make sure

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
