### PR TITLE
fix(data-table): correct spacing for radio buttons as table selection

### LINKED ISSUE #6493: [DataTable]: Radio selection: first column wider than with multi selection
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

When using the DataTable as a single-select (radio buttons) the first column / selection column is wider than when using the DataTable as amulti-select (checkboxes).

> Is this issue related to a specific component?

DataTable

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Both selection columns should be the same width.

> What browser are you working in?

Chrome 83

> What version of the Carbon Design System are you using?

`carbon-components@10.15`
`carbon-components-react@10.15`

## Steps to reproduce the issue

1. Visit react storybook with DataTable radio buttons: https://react.carbondesignsystem.com/?path=/story/datatable--with-radio-button-selection
2. Switch to "with selection" story (checkboxes)

You'll see the "Name" column jump.

## Additional information

On my screen the react storybook has the following widths:
image
image

### PR DESCRIPTION
**Pull request by janhassel**
Closes #6493 

This PR fixes the difference between radio button and checkbox spacings as the first column in data tables.

#### Changelog

**New**

- Added CSS rule to adjust `margin-right` for any `.bx--radio-button__appearance` inside a `.bx--table-column-radio`

#### Testing / Reviewing

Check if styling of single-select and multi-select data table in react storybook is consistent across browsers and platforms.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
both screenshots below are taken from the PR netlify preview but they seem to be identical to the released storybook build if I'm not mistaken. does the new selector in the PR stylesheet target the right element?

image

image

**Comment by janhassel** [comment]
@emyarod Ah sorry, the netlify storybook is built with emitting tokens whereas my local setup doesn't do that. Therefore `-$spacing-01` was translated to `-var(--cds-spacing-01)` resulting in invalid syntax.
On a second thought I actually don't think a spacing token was the right choice here anyways and I just pushed an update to use the `rem()` function. Deploy preview should be ready in like 15min.

**Comment by emyarod** [comment]
oh that's right, that CSS custom properties issue seems related to https://github.com/carbon-design-system/carbon/issues/4426 as well

**Review by emyarod — APPROVED** [review]
tested locally and the change looks good (pending design review) with CSS custom properties enabled and disabled

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Thanks for catching this Jan! The actual space we want would be 16px/1rem in between the checkbox/radio and the text. This should also be the same for the types that have chevrons for consistency.

Ex:
Artboard

**Comment by janhassel** [comment]
👍  should be up to spec now

**Review by laurenmrice — APPROVED** [review]
Looks great ! Thanks Jan 🎉

**Review by rjhenriquez — APPROVED** [review]
LGTM

**Pull request merged**
