### PR TITLE
feat(FileUploader): FileUploader size prop update

### PR DESCRIPTION
**Pull request by tw15egan**
Refs https://github.com/carbon-design-system/carbon/pull/8459
Refs #8369 

Updates the `FileUploader` and subcomponents to use the standardized size values found across the system.

Branched off of #8459 so will need to wait for that to be merged. 

#### Changelog

**New**

- `field` maps to `md`
- `small` maps to `sm`

#### Testing / Reviewing

Ensure all variants of `FileUploaderItem` and `FileUploaderButton` render as expected

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by johnbister — APPROVED** [review]
lgtm!

**Comment by tw15egan** [comment]
ping @andreancardona to review when you get a chance, should be the last PR for the size updates

**Review by andreancardona — APPROVED** [review]
looks good!

**Pull request merged**
