### PR TITLE
Consolidates 16, 32 px assets

### LINKED ISSUE #3494: Consolidate bespoke 16x16 assets with 32x32
We currently have a folder of 16x16 assets that should instead be 32x32 assets and downsampled. This issue is to identify duplicate assets and consolidate.

Tagging development to help figure out the difference and design to add the assets

### PR DESCRIPTION
**Pull request by chrisconnors-ibm**
Part one of #3494

Assures that all 16 px assets have a 32 px counterpart and vice versa. in some cases required new asset, in some cases renaming to support existing duplication.

#### Changelog

**New**

16/arrows--vertical.svg
16/light.svg

32/add--filled.svg
32/apps.svg
32/arrows.svg
32/awake.svg
32/back-to-top.svg
32/caret--sort--down.svg
32/caret--sort--up.svg
32/chevron--mini.svg
32/chevron--sort--down.svg
32/chevron--sort--up.svg
32/close--filled.svg
32/close--outline.svg
32/delete.svg
32/error--outline.svg
32/misuse--outline.svg

**Changed**
changed pixel straddling single px `+` to 2px stroke `+`
16/add--alt.svg
16/add--filled.svg
16/add.svg

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by lovemecomputer — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]

**Review by vpicone — DISMISSED** [review]
Thanks for taking care of this! I have a couple of questions/suggestions.

1. For the new 16px icons: If a 16px icon is the same as the 32px version halved I don't think we should add the asset. There's two reasons for this
	1. Signaling to contributors which icons have been hand tweaked
	2. Simplify downsizing by indicating where hand-tweaked asset that should trump the downsized version. 

2. The IDL has guidance around not using different strokes for different sizes of a single icon:

>One icon should not look heavier or lighter than other icons of the same size. 

We should consider updating the 32px icon to use a wider stroke let the downsizing take care of it. This would prevent different weights within a single icon. Extending the counter strokes to be closer to the regular add icon's length could help with making it less blocky after widening the stroke. @aagonzales

**Comment by vpicone** [comment]
Here's an example for 2. The point is to _only break one rule at a time._ The DL has exceptions for alternative stroke weights but not for the rule on weight variations between sizes. So if we're going to break only one rule, I think it should be the more lenient of the two (stroke width)

```
<svg focusable="false" preserveAspectRatio="xMidYMid meet" style="will-change: transform;" xmlns="http://www.w3.org/2000/svg" height="32" aria-hidden="true" viewBox="0 0 32 32" width="32">
    <path d="M14 0a14 14 0 1 0 14 14A14 14 0 0 0 14 0zm2 16v8h-4v-8H4v-4h8V4h4v8h8v4z"></path>
</svg>
```

Screen Shot 2019-07-23 at 5 42 57 PM


The strokes extends out to the most inner keyline. This creates a ring around the icon that's the same width as the stroke (4px). 

Screen Shot 2019-07-23 at 5 57 11 PM

**Comment by chrisconnors-ibm** [comment]
Changing the stroke weight of the `+` to 4px at the 32 px sizes is an unacceptable solution to cleaning up the 16px instance of the icon.

The proposed changes requires breaking a major rule in all resolutions and also any scaled sizes.

I intentionally did not combine the removal of the 16px that are now redundant with this introduction of scaled up assets. Please open a separate issue for that if that's a priority.

**Comment by chrisconnors-ibm** [comment]
@vpicone as you can see here, the current asset is the correct proportions at 6x6 and 1 px stroke:
image
but because it straddles a pixel border, the anti-aliased render at this size is already occupying 6x6 and 2px stroke.

proposed iteration is to reduce fuzziness while maintaining the same relative proportions of the `+` to the bg circle:
image
by committing to the already rendered pixels with a 2 px stroke here.

**Comment by vpicone** [comment]
@chrisconnors-ibm definitely understand the intent, but this creates a dramatic difference between the 16px and the 20px.

Screen Shot 2019-07-23 at 9 54 53 PM


The design language gives some exceptions for when stroke width can diverge from 2px, but it doesn't give any exceptions for weight differences within a single icon.

irt the 16px icons: I wasn't proposing removing any, just that we not add `arrows--vertical` or `light` in this PR if they're not being hand tweaked.

**Comment by chrisconnors-ibm** [comment]
in practice it's unlikely the 20 and the 16 would ever be seen together and certainly not right next to each other.

There is no bespoke 20 asset and a scaled asset for this icon @ 20 is, as we've discussed elsewhere multiple times, is going to be a mess. If someone needed one we'd make it.

**Review by laurenmrice — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Pull request merged**
