### PR TITLE
fix(Modal): set default focus to secondary button

### LINKED ISSUE #6939: Modal: Set default primary focus to something besides primary button
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Currently the default focused button on a modal is the primary button if it exists. In situations where users are interacting quickly with the UI, they might inadvertently trigger the primary button event which could include things like deleting.

> Is this issue related to a specific component?

Modal that has `passiveModal = false`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Set default primary focus to be either the secondary button or close button.

> What browser are you working in?

Brave Version 1.12.114 Chromium: 84.0.4147.135 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?

carbon-components-react 7.21.0-rc.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Cloud IKS UI, no

### PR DESCRIPTION
**Pull request by asthas**
Closes #6939

Change default focus to secondary button

#### Testing / Reviewing

- Check storybook for the modal component
image

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
rather than setting the secondary button to always be the primary focusable element by default, can we add the fallbacks as suggested in the original ticket?

**Comment by asthas** [comment]
@emyarod The previous implementation follows fallbacks as `selectorPrimaryFocus || primary button || close button`

The changes I made change fallbacks as `selectorPrimaryFocus || secondary button || close button`

The same was mentioned in the issue.

**Comment by emyarod** [comment]
not sure if we should directly search for the secondary button, but I think it would be better to still search for the primary button first before the secondary button. before anything else though, I just want to confirm the expected autofocus behavior with design cc @carbon-design-system/design

**Comment by tw15egan** [comment]
I wonder if we can focus the secondary/close button if `danger` is set to true (only for `Danger` modals)?

**Comment by asthas** [comment]
@tw15egan Yeah sure! I can try that . Can you please update  #6939 because it doesn't mention about danger modal?

**Comment by tw15egan** [comment]
@asthas let's wait to get some design input before we do any more work 🙂

**Comment by laurenmrice** [comment]
Briefly spoke with Andrew about this in slack, so posting here. I think we should go with this approach.
1. add secondary button in between primary button and close button in the order of fallbacks (so the order is custom selector -> primary -> secondary -> close)
2. if the current element to focus on is disabled, move to the next one in the order

**Comment by chrisconnors-ibm** [comment]
@asthas -  If the secondary button has focus by default and receives the keyboard handler for return or enter, it is, by definition, the _Primary Button_.

More important than whether a secondary button should be the defacto Primary Button by intercepting the keyboard event that should be going to the Actual Primary Button by definition, but what action the design in question is assigning to each button. There's no reason the default button has to be action that confirms or takes the action the dialogs is referring to; Primary does not have to always be confirmation.

image

If the Primary button is something consequential or dangerous, it's not uncommon to add friction so that the likelihood of inadvertent  keyboard entry is reduced. You see this in patterns where user is forced to type a specific string before the dangerous or irreversible Primary Button is enabled.

**Comment by tw15egan** [comment]
@chrisconnors-ibm I would post that in the actual issue, @asthas just volunteered to open a PR to add this in, not the original issue creator 👍

**Comment by chrisconnors-ibm** [comment]
> @chrisconnors-ibm I would post that in the actual issue, @asthas just volunteered to open a PR to add this in, not the original issue creator 👍

Will do, wanted to get some friction as close to the merge button as possible.

**Comment by joshblack** [comment]
Just wanted to bump this PR, is this something that is still being pursued or is it still blocked? 👀

**Comment by emyarod** [comment]
I believe we can close this PR and possibly the original ticket if there is no response to the latest comment about modal action UX

**Comment by aledavila** [comment]
I'm going to close this PR. If you have additional information feel free to open another issue :)

**Pull request closed without merging**
