### PR TITLE
chore(icons): update friendly names for UI icons

### PR DESCRIPTION
**Pull request by DianaStanciulescu**
I updated some friendly names for UI icons. Some icons also need to be moved from one category to another - I do not know how to do that. List of changes done and requred below:

App catalogue friendly name changes:

Cloud monitoring > > IBM Cloud® Monitoring
Cloud logging > > IBM Cloud® Log Analysis
IBM® Cloud Foundry 1 >> IBM® Cloud Foundry
Cloud registry >> IBM Cloud® Container Registry
Cloud satellite > > IBM Cloud® Satellite
Content delivery network >> IBM Cloud® Content Delivery Network
Database DataStax >> IBM Cloud® Databases for DataStax
Database elastic >> IBM Cloud® Databases for Elasticsearch
Database enterprise Db2 > > IBM Cloud® Databases for EnterpriseDB
Database etcd >> IBM Cloud® Databases for etcd
Database MongoDB >> IBM Cloud® Databases for MongoDB
Database PostgreSQL >> IBM Cloud® Databases for PostgreSQL
Database Rabbit>>IBM Cloud® Databases for Rabbit
Database Redis>> IBM Cloud® Databases for Redis
Direct link >> IBM Cloud® Direct Link 2.0
DNS services >> IBM Cloud® DNS services
flow-logs-vpc >> IBM Cloud® Flow Logs for VPC
IBM Cloud® dedicated host >> IBM Cloud® Dedicated Host
IBM Cloud Pak® Applications>>IBM Cloud Pak® for Applications
IBM Cloud Pak® data >> IBM Cloud Pak® for Data
IBM Cloud Pak® Integration >> IBM Cloud Pak® for Integration
IBM Cloud Pak® Multicloud Management>> IBM Cloud Pak® for Multicloud Management
IBM Cloud Pak® Security>> IBM Cloud Pak® for Security
Infrastructure classic>>IBM Cloud® Classic Infrastructure
Load balancer VPC>> IBM Cloud® Load Balancer for VPC
Virtual private cloud alt>>IBM Cloud® VPC
VLAN IBM>>IBM Cloud® VLAN

Other changes:
Bastion-host>>Bastion host
data--center >> Data center
Data diode - data - diode - systems >> Data diode
file-storage >> File storage
floating-ip >> Floating IP
intrusion-prevention >> Intrusion prevention 
Volume block storage >>Block volume
Volume file storage >> File system
Volume object storage>>Object bucket

To be moved to app catalogue section:

-	Autoscaling >> IBM Cloud® autoscaling
-	Block storage >> IBM Cloud® Block Storage for VPC

To be moved to systems section:
-	Cloud alerting
-	Cloud data-ops
-	Cloud service management
-	Cloud services

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by sstrubberg** [comment]
recheck

**Comment by DianaStanciulescu** [comment]
recheck

**Review by aledavila — APPROVED** [review]

**Comment by aledavila** [comment]
Hey @DianaStanciulescu would you mind commenting “ I have read the DCO document and I hereby sign the DCO.” please 😊

**Comment by DianaStanciulescu** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by DianaStanciulescu** [comment]
recheck

**Pull request merged**
