### PR TITLE
fix(Copy): add aria-live to announce text updates

### LINKED ISSUE #2523: Code snippet screen reader issues in JAWS 2020
@dakahn 
AVT 3 issues found with macOS Mojave, Chrome and VoiceOver.
For the inline code snippet VO does not:
- [x] announce what the button is for. VO should announce that it is a "copy" button.
- [x] announce that the text is a code snippet.
- [x] announce "copied" after the button is pressed the first time. (note: copied is announced after the button is pressed twice).

For the single and multi-line code snippet VO:
- [x] Incorrectly announces that the code snippet is an editable text field.
- [ ] Does not announce "copied" after the button is pressed the first time. (note: copied is announced after the button is pressed twice).

_Originally posted by @snidersd in https://github.com/IBM/carbon-components/issues/1531#issuecomment-458255961_

### LINKED ISSUE #5385: CopyButton does not announce state change with screen readers
## Environment

macOS, Chrome 79, Voiceover

## Detailed description

related https://github.com/carbon-design-system/carbon/issues/2523

> the CopyButton Component is also affected by this issue. "copied" is not announced after the button is pressed.

from https://github.com/carbon-design-system/carbon/issues/2523#issuecomment-566209585

## Steps to reproduce the issue

Navigate to the `<CopyButton>` story and interact with the component with a screen reader. The change in copy button state is not announced when the button is clicked.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5385 
Closes #2523

This PR updates WAI-ARIA state so that changes in the `<CopyButton>` are read by screen readers

#### Changelog

**New**

- `aria-live` region

**Changed**

- change `aria-label` based on animation state

#### Testing / Reviewing

Interact with the copy button using a screen reader and observe if button label changes are immediately read

### CODE REVIEW

**Comment by emyarod** [comment]
this may address #2523 as well cc @tw15egan

**Comment by abbeyhrt** [comment]
This looks great! I'm not sure why but for me it's announcing 'Copied' twice: 
Copy

**Comment by emyarod** [comment]
for me inside storybook it does not repeat the text in the voiceover dialog, it just reads it twice

image

but this seems to be only in storybook, I can't reproduce it when viewing the component outside of storybook or even in the storybook canvas on a new tab

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by tw15egan — APPROVED** [review]
Fix looks great! Confirmed on MacOS voiceover util, getting 1 "Copied!" when the button is clicked. No longer seeing the issue where CodeSnippet is announced as an editable text field as well so this should take care of #2523

Screen Shot 2020-02-19 at 11 00 53 AM

**Review by abbeyhrt — APPROVED** [review]

**Comment by asudoh** [comment]
Got a green light from @emyarod to move this to "ready to merge" state - Thanks @emyarod!

**Pull request merged**
