### PR TITLE
chore(date-picker): fix date picker disabled state colors

### LINKED ISSUE #2498: Date picker missing disabled styles in all variants
below are screenshots of the disabled state for each date picker variant. the placeholder text color and icon colors are incorrect. This likely needs changes in the vanilla repo

simple

image

single with calendar

image

range with calendar

image

range with calendar and min/max dates

image

### PR DESCRIPTION
**Pull request by aledavila**
Closes #2498 

Adds correct disabled state colors to all variants

#### Changelog

**Changed**

- added `disabled-02` color tokens 

#### Testing / Reviewing

check disabled state in react

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
In Firefox and Chrome, these look different. Chromes input text looks darker, make sure its calling the disabled-02.

Firefox:
Screen Shot 2019-08-19 at 2 21 18 PM

Chrome:
Screen Shot 2019-08-19 at 2 21 31 PM

**Review by jnm2377 — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
this still needs the user agent opacity override we talked about on slack right?

**Comment by aledavila** [comment]
Yes sorry was stuck in meetings all day but will get that in @emyarod

**Comment by aledavila** [comment]
@emyarod @laurenmrice can you guys check now if it is correct please

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by emyarod — COMMENTED** [review]
actually just want to double check the icon colors for the "date picker with range" are ok

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Yep, the only thing I am seeing now is that the calendar icon needs to be `disabled-02` and cursor needs to be changed to nonclickable

**Review by laurenmrice — APPROVED** [review]
Looks good ! 👍

**Pull request merged**
