### PR TITLE
Revert "feat(plex): add latest IBM Plex package for updates #602"

### LINKED ISSUE #620: Revert `@ibm/plex` peerDependency requirement
We introduced `@ibm/plex` in a recent release which caused a lot of our production services to miss out on the Plex styles we introduced in our v8 release. This issue is to revert this added peerDependency in a patch release so that we're no longer breaking these services. This peerDependency should be included in a future major release.

### PR DESCRIPTION
**Pull request by joshblack**
Closes #620

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
compared this to a previous release and it LGTM 👍

**Comment by joshblack** [comment]
Trying out #627 as well to see if we can get the best of both worlds 😄

**Review by marijohannessen — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
👍 - Thanks @joshblack!

**Comment by joshblack** [comment]
Closed in favor of #628 which is an automated diff (better than my manual one 😅)

**Pull request closed without merging**
