### PR TITLE
fix(table): Missing border in firefox

### LINKED ISSUE #680: Expandable Data table does not have grey divider in Firefox
## Detailed description

In Chrome and Safari, there is a grey divider line to separate rows. It does not display in Firefox.

> Is this issue related to a specific component? 
Data Table

> What did you expect to happen? What happened instead? What would you like to see changed?
I expected to see a grey line between rows in firefox. 

> What version of the Carbon Design System are you using? 
Carbon Design Website

Expandable Data Table on Chrome. (Also checked Safari and it looked fine there as well)
screen shot 2018-03-29 at 1 50 22 pm

Expandable Data Table on Firefox
screen shot 2018-03-29 at 1 49 47 pm

### PR DESCRIPTION
**Pull request by alisonjoseph**
## Overview

Resolves #680 
Missing border on expandable data table in firefox

### Changed

Corrected file name for expandable data table so it shows in dev env. 

## Testing / Reviewing

Check all **data table** styles to make sure nothing is broken

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]

**Review by marijohannessen — APPROVED** [review]

**Review by marijohannessen — CHANGES_REQUESTED** [review]
I noticed a file name change here, can we do that in a separate PR and target it to V9?

**Comment by alisonjoseph** [comment]
@marijohannessen the file name was just missing the second dash so it didn't show correctly in dev env.

**Comment by marijohannessen** [comment]
Or is the file change needed to make it show up in the dev env? I just need to make a note to update the website before deploying if that's the case

**Review by marijohannessen — APPROVED** [review]

**Comment by alisonjoseph** [comment]
@marijohannessen yea, it was a fix to have it show in the dev env.

**Pull request merged**
