### PR TITLE
fix(ui-shell): remove role='menu' from ui-shell

### LINKED ISSUE #3583: AVT 2 & 3 - React Header Base w/Navigation or the Header Base w/Navigation and Actions UI Shell has keyboard navigation issues
## Environment
macOS Mojave version 10.14.5
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
DAP - July 2019 Ruleset

## Detailed Description
1. Open the React Header Base w/Navigation and ensure the links are displayed in the horizontal menu bar. 
2. Tab to the first menu item, then arrow right to the next menu item and nothing happens.
**Expected result:** right and left arrow keys should navigate right and left across menubar
3. Tab to Link 4 and use up and down arrows to navigate the submenu and nothing happens. 
**Expected result:** arrow keys should navigate up and down the sub-menu
4. Make the browser window smaller so the menu displays as a hamburger icon.  In addition to the issues mentioned above the following issues are also present:
- Press Esc does not close the menu
- After tabbing to open the menu tabbing again moves focus to the next focusable item in the banner.
Expected result: Navigation should focus on the next menu item and Esc should close the menu.
See [ARIA Authoring Practices for menu](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) and menubar for keyboard navigation.

### LINKED ISSUE #3584: AVT 2 & 3 - React Header Base w/Navigation, Actions & SideNav UI Shell has keyboard navigation issues
## Environment
macOS Mojave version 10.14.5
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
DAP - July 2019 Ruleset

## Detailed Description
1. Open the React Header Base w/Navigation and ensure the links are displayed in the horizontal menu bar.
2. Tab to the first menu item, then arrow right to the next menu item and nothing happens.
**Expected result:** right and left arrow keys should navigate right and left across menubar
3. Tab to Link 4 and use up and down arrows to navigate the submenu and nothing happens.
**Expected result:** arrow keys should navigate up and down the sub-menu
4. Tab to the side menu and use up and down arrows to navigate the menu and nothing happens.
**Expected result:** arrow keys should navigate up and down the menu
5. Hit Enter or Space on an expandable menu item and it expands and collapses as expected. 
6. Make the browser window smaller so the menu displays as a hamburger icon. In addition to the issues mentioned above the following issues are also present:
- Press Esc does not close the menu
- After tabbing to open the menu tabbing again moves focus to the next focusable item in the banner.
**Expected result:** Navigation should focus on the next menu item and Esc should close the menu.
See [ARIA Authoring Practices for menu and menubar](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) for keyboard navigation.

### LINKED ISSUE #3590: AVT 2 & 3 - React Header Base w/SideNav, Fixed SideNav, & SideNav w/Icon UI Shell has keyboard navigation issues
## Environment
macOS Mojave version 10.14.5
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
DAP - July 2019 Ruleset

## Detailed Description
Tab to the side menu and use up and down arrows to navigate the menu and nothing happens.
Esc does not close the menu.
**Expected result:** Up and down arrow keys should navigate up and down the menu. Esc key should close the menu. 

See [ARIA Authoring Practices for menu and menubar](https://www.w3.org/TR/wai-aria-practices-1.1/#menu) for keyboard navigation.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/3583
Closes https://github.com/carbon-design-system/carbon/issues/3590
Closes https://github.com/carbon-design-system/carbon/issues/3584

We erroneously had role="menu" implying an application menu. 

#### Changelog

**Removed**

- All references to `role="menu"` and 'role="menuitem"`

#### Testing / Reviewing
 
Make sure UI Shell still looks the same, and there are no new DAP errors.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
🎉

**Comment by emyarod** [comment]
duplicate of https://github.com/carbon-design-system/carbon/pull/5234? I self assigned those tickets...will close in favor of this

**Review by emyarod — APPROVED** [review]
👍

**Comment by emyarod** [comment]
couldn't add this in the review but I also edited [this comment](https://github.com/carbon-design-system/carbon/blob/4f5342e96d0d5b69daaf3521ebfd6f2036e5c975/packages/react/src/components/UIShell/HeaderMenu.js#L209-L211) and removed the role on L222

**Comment by tw15egan** [comment]
@emyarod updated

**Review by abbeyhrt — APPROVED** [review]

**Pull request merged**
