### PR TITLE
fix: add isSelected prop to IconButton

### LINKED ISSUE #14594: [Bug]: IconButton doesn't support props.isSelected
### Package

@carbon/react

### Browser

_No response_

### Package version

1.37.0

### React version

_No response_

### Description

`IconButton` doesn't support `props.isSelected`.

The alternative way of using `<Button hasIconOnly>` supports it as expected.

### Reproduction/example

https://stackblitz.com/edit/github-goaxgp?file=src%2FApp.jsx

### Steps to reproduce

Try applying `props.isSelected` to both `<IconButton kind="ghost">` as well as `<Button hasIconOnly kind="ghost">`.

### Suggested Severity

None

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by azizChebbi**
Closes #14594

The IconButton component doesn't support a "isSelected" property.

#### Changelog

**New**

- IconButton component support isSelected prop. 

**Changed**

- IconButton component.

### CODE REVIEW

**Comment by azizChebbi** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by azizChebbi** [comment]
The test fails because Public API should only change with a semver change, @tw15egan I'm not sure how to deal with this. 
Apparently this change will be present in the next version release if I'm getting it right.

**Comment by tw15egan** [comment]
@azizChebbi you can run `yarn test -u` from the root of the monorepo to update the snapshots 👍🏻

**Review by andreancardona — APPROVED** [review]
@azizChebbi Thank you for the contribution! 🎉

**Comment by tw15egan** [comment]
@azizChebbi looks like a few merge conflicts

**Pull request merged**
