### PR TITLE
fix(TimePicker): Split timezone into Time Zone

### LINKED ISSUE #1015: "Timezone" should be two words
@cdmauney commented on [Thu Aug 02 2018](https://github.com/IBM/design-system-website/issues/317)

## Detailed description

In the examples and code for the time picker component, "timezone" should be written as two words. 

## Steps to reproduce the issue

1. Expand **Components** and click **Date Picker** in the nav.
2. Click any of the three tabs. 
3. Scroll to the "Time picker" section.

## Additional information

image

---

@alisonjoseph commented on [Fri Aug 03 2018](https://github.com/IBM/design-system-website/issues/317#issuecomment-410247060)

This will need to get update in carbon-components, moving the issue to that repo

### PR DESCRIPTION
**Pull request by havesomeleeway**
fixes #1015

## Overview

Resolves {{ issue number(s) here }}

{{ Description about the PR }}

{{ Include images and gifs when applicable }}

### Added

{{ Description of things added }}

### Removed

{{ Description of things removed }}

### Changed

{{ Description of things changed }}

## Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Thanks for tackling this fix! Can you switch "Time Zone" to be sentence case? So it would be `Select time zone` and `Time zone 1`

**Comment by havesomeleeway** [comment]
All done, switched the spelling

**Review by alisonjoseph — APPROVED** [review]
LGTM! Thanks!

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @havesomeleeway!

**Pull request merged**
