### PR TITLE
 feat(sketch): add sketch package

### LINKED ISSUE #2438: Generate elements sketch library from carbon-elements
**Is your feature request related to a problem? Please describe.**
Current IBM Design Language Sketch library is not maintained and requires manual creation/revision. For example it's currently hundreds of icons behind the /icons package. Designers and developers now see icons on https://www.carbondesignsystem.com/guidelines/iconography/library that don't exist in the IBM Design Language Sketch library Library, and are engaged in work arounds (downloading individual icons, orphaning them) to get the complete set.

**Describe the solution you'd like**
Automatically build a `carbon-elements` Sketch Library from the contents of carbon-elements including type, type styles, icons, colors, etc.

**Describe alternatives you've considered**
Right now we tell designers to download the IBM Design Language sketch library to get Type symbols, spacing, colors and icons. this library was created by hand and is currently wildly (perhaps 50%) out of date from just the icons in carbon elements/icons. fixing it by hand would be a significant undertaking, and will soon get out of date from the repo again.

**Additional context**
This is high priority work

### PR DESCRIPTION
**Pull request by joshblack**
Closes #2438

Add `@carbon/sketch` package responsible for creating the Carbon Elements sketch plugin. This plugin provides the following commands as defined by its [`manifest.json`](https://github.com/carbon-design-system/carbon/blob/36aad61fa568310be02f23e2aeff30118a5a7158/packages/sketch/src/manifest.json):

- Colors
  - Sync shared styles
  - Generate a colors page with swatch artboards
- Themes
  - Sync shared styles
  - Generate a themes page with token artboards
- Icons
  - Generate an icons page with symbols
- Type
  - Sync shared styles
  - Generate a type page

Notes to reviewers:

- The full end-to-end demo of this plugin is available here: https://github.com/carbon-design-system/carbon/pull/2720#issuecomment-494907305
- The package [`README.md`](https://github.com/carbon-design-system/carbon/blob/36aad61fa568310be02f23e2aeff30118a5a7158/packages/sketch/README.md) has some details around building and running sketch plugins, alongside project structure
- The package itself is `private` and will not be published as a part of our regular release process
- The package can run on machines that don't have Sketch installed
- We need to verify what machines the plugin can be run on, the plugin itself is available here: https://github.com/carbon-design-system/carbon/pull/2720#issuecomment-494909483

#### Changelog

**New**

- `@carbon/sketch` package

**Changed**

- `@carbon/icons`
  - `16/checkmark--filled` update to correct `id` to `inner-path`
  - `32/checkmark--filled` update `fill-opacity` to `opacity`

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
Color command preview: 

https://ibm.box.com/s/agplb4glg7dgfxje27qxymsoushz6nr8

**Comment by joshblack** [comment]
cc @lovemecomputer if you have a chance to review! Going through and adding docs on how the plugin flow works but wanted to point this your way in case you had time before then 😄

**Comment by joshblack** [comment]
Video demo of sketch plugin (edited to speed up each command): https://ibm.box.com/s/8pd2jql9ac87brdtwxmdb3m15xxfpo40

**Comment by joshblack** [comment]
Plugin download: https://ibm.box.com/s/ag1noz1ueh25rc0f1rlbc2f6klyo10tv

**Review by aagonzales — APPROVED** [review]
woo-hoo! Everything worked for me! I didn't check the accuracy of all the values, but I'm assuming they're right since its being generated from code. I can go through and check that though if you want me too.

**Comment by joshblack** [comment]
@aagonzales I know one thing I noticed that was off were the type font weights 😞 for some reason Sketch is thinking we are specifying extra light for plex instead of light (at least on my machine).

We might want to just document what are the differences for things like that which will need to be fixed before syncing to a library. I think for colors/themes we should be fine, and icons I think we just will have to wait for someone to tell us when something is busted lol. There are so many and Sketch lags so much 😭

**Comment by aagonzales** [comment]
@joshblack oh wait the icons all have borders on them
image

**Comment by joshblack** [comment]
Oh whoa, weird 🤔 Locally it shows me this:

image

Have any idea what the difference might be?

**Comment by joshblack** [comment]
Couple of TODOs:

- [x] Figure out how to reset border if user has border option on by default for new layers
- [x] Figure out how to sync color shared style with text styles

**Comment by joshblack** [comment]
@aagonzales here's a link with the latest updates for border issues, let me know if it works!

https://ibm.box.com/s/8htauxuu7mjuyj11j86y7gnde9wibdva

**Comment by aagonzales** [comment]
@joshblack yup! They're back to normal now. No strokes/borders

**Review by dakahn — APPROVED** [review]

**Review by lovemecomputer — COMMENTED** [review]
josh gave a walkthrough of the code & plugin, and it seems to be on a pretty good track! it will be good to continue the conversation of ensuring this codebase works for our designers, and the package seems like it has solved the hardest must-have features and is in a good state to merge and keep pushing on it!

**Review by alisonjoseph — APPROVED** [review]
🙌 Nice work on this Josh!

**Comment by lovemecomputer** [comment]
bitmoji
yayyyy

**Pull request merged**
