### PR TITLE
feat(Search): add support for `light` prop

### LINKED ISSUE #3199: Search (react) component—`light` prop not applying style for light theme
http://react.carbondesignsystem.com/?path=/story/search--default

the `light` knob does not seem to change the component. it didn't work when using in `carbon-website` either. i had to manually add the `bx--search--light` as a classname to get the light bg color.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3199

support for the `light` prop was removed a few months ago in the `<Search>` component (https://github.com/carbon-design-system/carbon-components-react/pull/2247/files#diff-66e09d5cca737eb23cd9bd3b28171d7b) but this was not part of a spec change (most likely a change to fit v10 table toolbar styles?)

#### Testing / Reviewing

Ensure `<Search>` and anything that depends on it have no regressions

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
⚡️ Super fast ⚡️

**Review by jnm2377 — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Side-note: for the commit should it be a `feat` instead of a `fix`?

**Comment by emyarod** [comment]
I just labeled it a fix because we used to support it until it got taken out

**Comment by joshblack** [comment]
@emyarod yeah, definitely get the background. I only bring this up because it is adding to the API surface area which tends to fall under the `feat` range versus fixing something that already exists.

**Comment by emyarod** [comment]
either one works for me

**Comment by lovemecomputer** [comment]
rad, thanks!

**Pull request merged**
