### PR TITLE
Switch btn text to nodes for Modal

### PR DESCRIPTION
**Pull request by sgregoire**
Closes #

Official documentation recommends to use `InlineLoading` in a loading Modal.
I just changed the proptypes from `text` to `node`. [source](https://www.carbondesignsystem.com/components/modal/usage#loading)

#### Changelog
**Changed**
- Changed propTypes of Modal from text to node

#### Testing / Reviewing
I've created a unit test, and added an entry to your Storybook.

### CODE REVIEW

**Comment by asudoh** [comment]
Oops... I added visual review tag given there is a new story, but it doesn't seem to be working. My apologies designers.

Are you planning to do more work @sgregoire?

**Comment by sgregoire** [comment]
Hello, I did not plan to do much more work around that. I can try to fix the build, but I couldn't find the procedure to run all the tests / lint used by the CI.

**Comment by tw15egan** [comment]
@sgregoire you should be able to update the tests by running `yarn test -u` and format with `yarn format`.


Also, the story you've added is not currently displaying. However, I'm not sure we need another story for this prop change, unless the story is showing how to use inline loading inside a modal.

**Comment by sgregoire** [comment]
> @sgregoire you should be able to update the tests by running `yarn test -u` and format with `yarn format`.
> 
> Also, the story you've added is not currently displaying. However, I'm not sure we need another story for this prop change, unless the story is showing how to use inline loading inside a modal.

I removed the story, and fixed the tests.

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @sgregoire!

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
