### PR TITLE
feat(SkeletonIcon): add SkeletonIcon component

### PR DESCRIPTION
**Pull request by tw15egan**
Refs https://github.com/carbon-design-system/carbon/pull/10835

Introduces a new `SkeletonIcon` component to align with the existing skeleton components, like `SkeletonPlaceholder` and `SkeletonText` 

#### Changelog

**New**

- `SkeletonIcon` introduced as a replacement for `IconSkeleton` 
- Introduced a new story, export, and tests for `SkeletonIcon` component

#### Testing / Reviewing

Ensure `SkeletonIcon` renders as expected, and all tests pass

### CODE REVIEW

**Review by abbeyhrt — CHANGES_REQUESTED** [review]
Looks good to me! I think the only thing I see is that we also need to export it in [this file](https://github.com/carbon-design-system/carbon/blob/main/packages/carbon-react/src/index.js) as well so it's released in `@carbon/react`

**Comment by tw15egan** [comment]
@abbeyhrt good catch! Updated 😄

**Review by abbeyhrt — APPROVED** [review]
🎉

**Comment by joshblack** [comment]
bump @tay1orjones when you get a sec!

**Review by tay1orjones — APPROVED** [review]
So sorry for the delay!

**Pull request merged**
