### PR TITLE
fix(text-area): allow wrapper to span the full width of its container

### LINKED ISSUE #4994: TextArea react component not inheriting the width from it's container
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Text area is not inherting it's parent's width which is the set through className props on the component.  
Screen Shot 2020-01-09 at 3 24 47 PM

It used to on v9 
Screen Shot 2020-01-09 at 3 25 05 PM

> Is this issue related to a specific component?
TextArea

> What did you expect to happen? What happened instead? What would you like to
> see changed?
can control the width

> What browser are you working in?
Chrome Version 79.0.3945.88 (Official Build) (64-bit)

> What version of the Carbon Design System are you using?
carbon-components-react: 7.9.0
carbon-components: 10.9.0

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

https://codesandbox.io/s/dawn-snow-2zc94
## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by jendowns**
Closes #4994 

Set the `TextArea` wrapper to `width: 100%` so that it can span the full width of its container (like the `TextInput` does).

#### Changelog

**New**

- add `width: 100%` style rule to `TextArea` wrapper

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Review by tw15egan — APPROVED** [review]
👍

**Review by joshblack — APPROVED** [review]

**Comment by abbeyhrt** [comment]
@jendowns, thank you for doing this! This might be the intended effect here but the TextArea for the storybook example is now spanning the whole page
Screen Shot 2020-01-10 at 11 08 35 AM

**Comment by jendowns** [comment]
@abbeyhrt Yeah now I believe it is super similar to the `TextInput` story for example, which I believe also spans the whole page. But I can add a width to the story if you prefer that?

**Comment by abbeyhrt** [comment]
@jendowns Gotcha, thanks for clarifying!

**Review by abbeyhrt — APPROVED** [review]

**Comment by jeanservaas** [comment]
hey @jendowns can you just provide a screen grab of what is changing? I looked at the preview link, but I'm not really sure what's different. Thanks!

**Comment by jendowns** [comment]
Hey @jeanservaas - no problem!

Currently, the `TextArea` component does not span the full width of its parent. 
If you go to the current React storybook deployment, you can see that the `TextArea` appears to be about 467 pixels wide but actually it should be much wider, because its parent container is `width: 100%` -- http://react.carbondesignsystem.com/?path=/story/textarea--default
Screen Shot 2020-01-13 at 8 51 37 AM


So this change shown in the PR deployment makes the `TextArea` truly expand to fill the available space: https://deploy-preview-4995--carbon-components-react.netlify.com/?path=/story/textarea--default
Screen Shot 2020-01-13 at 8 51 27 AM

**Review by jeanservaas — APPROVED** [review]
lgtm!

**Pull request merged**
