### PR TITLE
Added divider to `ComboBox` and `Filterrable MultiSelect`

### LINKED ISSUE #15492: Dividers in components: Dev Implementation
### **Developer implementation**

_Important Links_
[Design Solutions and Guidelines for Dividers in Components - Figma](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=78-32710&mode=design)

---

### Tasks
- [x] Introduce vertical divider across all states under "Option Selected" for Combobox - Default
- [x] Introduce vertical divider across all states under "Option Selected" or Combobox - Fluid
- [x] Introduce vertical divider across all states "Option Selected" for Filterable Multiselect - Default
- [x] Introduce vertical divider across all states "Option Selected" for Filterable Multiselect - Fluid
- [x] Remove vertical divider from the Search component - Fluid 
- [x] Ensure that the following updates are reflected in the Form and Modal components as well

---

Visual Context to the Specs
Specs for Dividers in Combobox and Filterable Multiselect

Combobox Default and Fluid
Combo box - Default

Combo box - Fluid

Filterable Multiselect Default and Fluid
Filterable Multiselect - Default

Filterable Multiselect - Fluid

Search Fluid
Search Fluid

Visual Context to the Guidelines (EXTRA INFORMATION)
Dividers in Carbon Components (Input fields)

### PR DESCRIPTION
**Pull request by guidari**
Closes #15492

Added dividers to `ComboBox` and `Filterrable MultiSelect`. The divider was added in the list box scss.
There is no divider when there is only an warn/invalid icon and the selector icon.

#### Changelog

**New**

- Dividers in `ComboBox` and `Filterrable MultiSelect`.
- Added divider for AI Slug in `ComboBox`, `Dropdown`, `Multiselect` and `FilterableMultiSelect`

**Removed**

- Removed divider from `Fluid Search`

#### Testing / Reviewing

- Go to the storybook and test the divider by addind warn/invalid

-ComboBox
-Fluid ComboBox
-Filterable Multiselect
-Fluid Filterable Multiselect

### CODE REVIEW

**Comment by tw15egan** [comment]
@guidari I just pushed up some changes that add dividers to `ComboBox` `MultiSelect` `FilterableMultiSelect` and `Dropdown` when the `Slug` is present. I was able to achieve the effect by using pseudo-elements and modifying the `Slug` positioning a bit

**Comment by guidari** [comment]
Hey @tw15egan that looks good! Thanks for helping.

I changed just this code, and now it is exactly 8px from the other button.

```
- inset-inline-end: calc($spacing-08 + 8px);
+ inset-inline-end: calc($spacing-08 + 4px);
```
Also, what would happend if we have a slug that is not intereative? Would that be another class?
Because it can not get trigger the divider.

**Comment by tw15egan** [comment]
@guidari, I'm just going to do the interactive tags for now. It seems there are talks of replacing the default with the hollow slug and making them all have the callout, so to reduce our work, we'll focus on the interactive positioning. And yeah, that change to  `4px` looks much better 👍🏻

**Review by tw15egan — APPROVED** [review]

**Review by alina-jacob — APPROVED** [review]
Looks good Gui! 
Thanks for re-updating it at pixel details, super awesome! 🚀 ❤️

**Review by andreancardona — APPROVED** [review]
Tested and looks good! 🔥

**Pull request merged**
