### PR TITLE
fix(components): bugs & hard-coded colors

### PR DESCRIPTION
**Pull request by tay-aitken**
Made updates to a handful of components so that they were consistent with the way it was designed and/or attached to a class.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
Were the changes to the icon tooltip intentional? 
screen shot 2018-06-25 at 1 45 11 pm

screen shot 2018-06-25 at 1 45 06 pm

**Comment by tay-aitken** [comment]
Yes! I just realized the caret was int he wrong place, just fixed it though (its centered again).

**Review by asudoh — COMMENTED** [review]
Thank you for fixing these @tay-aitken! LGTM basically :+1:, want to see if other devs are comfortable. Thanks again!

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by asudoh — APPROVED** [review]

**Pull request merged**
