### PR TITLE
feat(tabs): added hover and active styles

### PR DESCRIPTION
**Pull request by soumyaraju**
Part of #15961

It adds the active and hover states to the line and contained scrollable icon buttons and also fixes the Background missing on left scroll button for line tabs. 

Rest of the issues mentioned are handled in a different PR #16522 

#### Changelog

**New**

Screenshot 2024-05-21 at 7 51 55 PM
Screenshot 2024-05-21 at 7 50 25 PM

### CODE REVIEW

**Comment by soumyaraju** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by soumyaraju** [comment]
recheck

**Comment by soumyaraju** [comment]
recheck

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Hover states look good. I see you added the active styling but for some reason the active styling is not applied when clicking down and holding the mouse down. You can see here I toggle the active styling on and it's correct, but when I click and hold to scroll it doesn't change from the hover styling:

https://github.com/carbon-design-system/carbon/assets/3360588/9ffa98c6-23ad-4d9c-a5a0-a621e0664c7c

**Comment by tay1orjones** [comment]
The contained tabs have the same issue. There's something odd going on with the gradient. I'm not sure if it's related to your changes or not, but holding down the right arrow a second time after it's already scrolled all the way to the right makes it go backwards the other way.

https://github.com/carbon-design-system/carbon/assets/3360588/aeee01a5-f693-4636-81de-3ea0f4890854

You might consider moving these changes into https://github.com/carbon-design-system/carbon/pull/16522#pullrequestreview-2123384223 or moving those changes into this PR so we can make sure it's fully correct with all these changes together.

**Comment by tay1orjones** [comment]
@soumyaraju any thoughts on my thoughts in my previous comment?

**Comment by soumyaraju** [comment]
> Hover states look good. I see you added the active styling but for some reason the active styling is not applied when clicking down and holding the mouse down. You can see here I toggle the active styling on and it's correct, but when I click and hold to scroll it doesn't change from the hover styling:
> 
>  CleanShot.2024-06-17.at.11.47.33.mp4

Hi @tay1orjones i have corrected the active style for the tabs, could you please check it. Thanks

**Comment by tay1orjones** [comment]
@soumyaraju active styles look good, the scroll is still not properly working at the rightmost end of the tab list. The final tab is obscured and can't be viewed.

https://github.com/user-attachments/assets/83096cae-c5ff-4542-9616-b0fa0d9173a8

**Comment by tay1orjones** [comment]
@soumyaraju I redeployed the deploy preview with the latest from `main`, unfortunately the issue remains where the last tab is being partially hidden.  I can't reproduce the issue in the production storybook at react.carbondesignsystem.com, so it must be related to something here. My guess is it's a result of the removing of `position: absolute;` on the buttons.

**Review by tay1orjones — APPROVED** [review]
Functionality looks great, thanks!

**Review by aagonzales — COMMENTED** [review]
I'm seeing some issues with the left arrow on hover and active. The background is not a uniformed color. 
Sep-24-2024 16-22-20

**Comment by soumyaraju** [comment]
Hi @aagonzales, thank you for your review! The background color fade you mentioned has been addressed in another PR, which I noted in the description here: https://github.com/carbon-design-system/carbon/pull/16522.

**Comment by aagonzales** [comment]
@soumyaraju Ok without that fixed its hard to tell if this version is correct. Perhaps we need to wait until that PR is merged so we can see those changes here. I would not want to merge this glitch in as it is now. @tay1orjones thoughts on merge order? 

image

**Comment by soumyaraju** [comment]
Hi @aagonzales @tay1orjones i have rebased and verified the background color fade you mentioned, its removed. Could you re-review this pr and approve my changes. Thanks.

**Comment by alisonjoseph** [comment]
@aagonzales the other PR (https://github.com/carbon-design-system/carbon/pull/16522) has been merged and both set of changes should be visible here for you to re-review.

**Review by aagonzales — APPROVED** [review]
Yup, everything looks good now! Thanks for fixing all of that.

**Comment by soumyaraju** [comment]
Thanks @aagonzales for the review, @alisonjoseph  could you help me merge these changes. TIA

**Pull request merged**
