### PR TITLE
feat(styles): incorporate experimental color tokens

### PR DESCRIPTION
**Pull request by asudoh**
From `@carbon/colors`.

Refs #1513.

#### Changelog

**New**

- A build tool to create Sass mix-in to define color variable from color data from `@carbon/colors`.
- A file in `src/globals/scss/vendor/@carbon/colors` generated by above tool.

**Changed**

- Color token names:
    - From `$active-01` to `$active-ui`
    - From `$hover-field` to `$hover-ui`

#### Testing / Reviewing

Testing should make sure no component, especially stable, is broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]

**Comment by asudoh** [comment]
@IBM/carbon-designers Can any of you see if [the changelist](https://github.com/IBM/carbon-components/pull/1556/files#diff-33cbf362ba01c1f9228298d3b7df2ac0) represents the correct set of changes to our color tokens? Thanks!

**Comment by aagonzales** [comment]
Brand-01-03 should be deprecated or at least on it was to being deprecated. The "interactive" colors replace brand. 

Also we have sense add a few additional color token in order to make themes work: https://github.com/IBM/carbon-elements/issues/220#issuecomment-451512313

**Comment by joshblack** [comment]
@asudoh might want to hold off on elements-related packages till the tokens and themes are settled and merged in 👍

**Comment by asudoh** [comment]
Thanks @aagonzales for your comments, updated [color changelist](https://github.com/IBM/carbon-components/pull/1556/files#diff-33cbf362ba01c1f9228298d3b7df2ac0).

@aagonzales @joshblack - Any ideas on when the updated color tokens will be available?

**Comment by joshblack** [comment]
@asudoh it's included in this sprint 👍 should be included under https://github.com/IBM/carbon-elements/issues/220 and from Shixie's contributions

**Comment by asudoh** [comment]
Incorporated the work from IBM/carbon-elements#220.

**Review by aagonzales — APPROVED** [review]

**Review by joshblack — CHANGES_REQUESTED** [review]
I think we should close this one for the work I'm doing for the component audit next week 👍

**Comment by asudoh** [comment]
@joshblack Could you please articulate what change you are planning to make? Also please be reminded that this PR blocks #1582. Thanks!

**Comment by joshblack** [comment]
@asudoh we are doing a component audit next week for which I am bringing in the updated color and type tokens. This will be a time to try them out and verify usage (similar to icons before). Because of this, it'd be great if we could close this and other elements-related PRs so that the work is coming from the same place. This will help out if we need to make changes to elements work as we wouldn't have to keep it in sync across multiple places.

RE: #1582 I understand that it is blocked and added the associated issue that is blocking it in Zenhub 👍

**Comment by asudoh** [comment]
@joshblack Good to have more explanation - IIUC the color tokens have been finished in `@carbon/colors` alpha 27 release. Do you think otherwise? This PR has brought in color tokens from alpha 27 release with an automatic script.

**Comment by joshblack** [comment]
@asudoh in this case, it would be great if we could refactor the usage to use the mixins from the color package and remove the custom script. It would be preferred if I handled the elements integrations so that work isn't wasted or duplicated because of things like this, or in the case of design changes for tokens.

**Comment by asudoh** [comment]
Looking at https://unpkg.com/@carbon/colors@0.0.1-alpha.28/scss/ - Cannot find a mixin representing  our color tokens. @joshblack Did you mean themes package or am I missing something?

**Comment by asudoh** [comment]
Incorporated alpha 28 of `@carbon/themes` and `@carbon/colors`, and migrated theme mixin from one generated from custom script to one seen at https://unpkg.com/@carbon/themes@0.0.1-alpha.28/scss/mixins.scss.

@joshblack Please let me know if you have any structural changes you are planning to make at `@carbon/themes` and `@carbon/colors` so we can plan for acceptance. Changes in theme token value can be incorporated after initial color incorporation here. Thanks!

**Comment by shinytoyrobots** [comment]
As per Josh's comments above - please leave the integrations for elements to him through the next couple of sprints. I would prefer a single voice driving this work, to avoid lengthy debates, until after Think.

**Comment by joshblack** [comment]
Closed by #1643

**Pull request closed without merging**
