### PR TITLE
feat(Tooltip): support controlled and uncontrolled modes

### LINKED ISSUE #2849: Tooltip - unable to control using *open* props
## What package(s) are you using?
Same happens also for version *6.x*:
Screenshot 2019-05-28 at 12 47 46

- [ ] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description

Unable to control visibility state of the Tooltip (open/close), using already existing *open* prop. It could be easy observed using provided codesandbox.

Screenshot 2019-05-28 at 12 50 37

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
We need this functionality in IBM SPSS Statistics. Tooltips are the last components we are trying to migrate from ap-components-react to Carbon.

## Steps to reproduce the issue

1. Assign Tooltip *open* prop to state variable (e.g. showTooltip).
2. Change value of state variable (true->false, false->true)
3. Result: Tooltip doesn't react on changes on *open* prop.

*Expected:* Tooltip will react on change for *open* prop

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/embed/codesandbox-lo5ox

Issue exists on both carbon-components-react versions 6.x and 7.x.
We are expecting a fix for version 6.x.

It's a *blocking issue* for us.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2849 

This PR adds uncontrolled mode support to the interactive tooltip

#### Changelog

**New**

- add support for controlled and uncontrolled tooltip (based on `open` prop value)
- feature flags for initial state based on controlled mode

**Changed**

- rename `_handleHover` method to be more accurate

#### Testing / Reviewing

Ensure both controlled and uncontrolled modes function as expected

### CODE REVIEW

**Comment by asudoh** [comment]
Thank you for jumping in @emyarod! One question - Does this change allow app to control `open` prop as well?

**Comment by emyarod** [comment]
@asudoh unless I am misunderstanding, `open` prop control for the app is already handled by `gDSFP` isn't it?

**Comment by asudoh** [comment]
I think the author of #2849 is saying that that feature is broken somehow, probably due to our logic reflecting `open` state.

**Comment by emyarod** [comment]
from what I observed it's broken because of how we are handling `handleClickOutside`

I reused their sandbox code for a temporary demo fix here https://deploy-preview-3357--carbon-components-react.netlify.com/?path=/story/tooltip--test

**Comment by asudoh** [comment]
Super 🎉 - Would we demo the control-ability with a knob?

**Comment by emyarod** [comment]
not sure how we want to demo it yet since there are still some bugs with this I want to address first

I think we may need to allow refs to be passed into the tooltip trigger node as well as the floating tooltip body to properly determine the source of click events

right now if the tooltip is shown and the user clicks on the tooltip body itself, the tooltip will hide (so tooltip contents are not interactable)

**Comment by asudoh** [comment]
Just wondering - Does the `ref` stuff have something to do with controlling `open`, or is it just another enhancement you are thinking about interactive tooltip?

**Comment by emyarod** [comment]
I see it as more of a bug fix depending on how we proceed with handling `handleClickOutside`. This is an interactive tooltip right? so the user should still be able to click buttons or select text inside the tooltip. but right now, that's not possible because we aren't preventing the tooltip from closing if the click event target is the tooltip body

**Comment by asudoh** [comment]
The interactive tooltip code seems to use `<ClickListener>` in it, so probably you are talking about just getting refs of those two DOM nodes?

**Comment by emyarod** [comment]
yeah, probably need a ref of the tooltip body since right now we only forward the ref for the trigger node IIRC

**Comment by asudoh** [comment]
OK wanted to distinguish forward-ref vs. "just getting ref" - Given forward-ref is for exposing ref to outside of the component, wondering what led you to think of forward-ref even if `<ClickListener>` usage seems internal in interactive tooltip code?

**Comment by emyarod** [comment]
but the `<ClickListener>` is only associated with the tooltip trigger right? when the tooltip is controlled, the app needs a ref to the tooltip body. not sure if forwarding multiple refs is the most elegant way but I'm wondering if there are other options

**Comment by asudoh** [comment]
Wrt `<ClickListener>` I was imagining that it simply needs an interface to add another DOM refs so that we can implement "unless the click is on none in the tracked elements then we call `onClickOutside()`". Given you said "the app needs a ref to the tooltip body", wondering if you were thinking of letting application code handle click-outside.

**Comment by emyarod** [comment]
yeah I see, that's also an option. I don't have a preference for either solution so would you rather refactor `<ClickListener>` instead of allowing application to handle outside click? also not sure why the PR keeps getting automatically closed, probably when I change git history to kick off another netlify build

**Comment by asudoh** [comment]
Another approach we can take is interactive tooltip code taking over `<ClickListener>`'s event and does another check wrt tooltip body.

**Comment by emyarod** [comment]
@asudoh is there any preference for either of these approaches?

**Comment by asudoh** [comment]
@emyarod Probably we start with the approach of taking over `<ClickListener>`'s event and does another check wrt tooltip body? Thanks!

**Comment by emyarod** [comment]
@asudoh but will this approach affect how `<ClickListener>` is used in other components like data table toolbar?

**Comment by asudoh** [comment]
@emyarod Wondering what concrete adverse effect you are thinking of. Just in case I should mention, I'm _not_ suggesting to change `<ClickListener>`.

**Comment by emyarod** [comment]
@asudoh I see, sounds similar to the commented code in this PR then? or am I misunderstanding what you meant by taking over `<ClickListener>`'s event and checking WRT tooltip body?

**Comment by asudoh** [comment]
> I see, sounds similar to the commented code in this PR then?

Yes!

**Comment by emyarod** [comment]
@asudoh what are your thoughts on checking for the value of `this.props.open` in the `handleMouse` method as well (see latest git diff)?

**Comment by asudoh** [comment]
@emyarod Are you referring to https://github.com/carbon-design-system/carbon/pull/3357/commits/c7df7593ef263c69ac02612c854ab2d87a6465db or something else? I'm asking this because https://github.com/carbon-design-system/carbon/pull/3357/commits/c7df7593ef263c69ac02612c854ab2d87a6465db seems story-only change. Thanks!

**Comment by emyarod** [comment]
@asudoh I am referring to https://github.com/carbon-design-system/carbon/pull/3357/commits/b794a8c196d83a9ce6b71daf71c7910413bdc980, which can be tested in the netlify preview. https://github.com/carbon-design-system/carbon/commit/c7df7593ef263c69ac02612c854ab2d87a6465db just contains the example app from the code sandbox in the issue

**Comment by asudoh** [comment]
I see, what is the change for?

**Comment by emyarod** [comment]
in the second example provided by the issue author, the tooltip is controlled by the focus state of the number input. the focus state is passed into the tooltip via props, but the `handleMouse` method only looks at the tooltip's internal state to determine if the tooltip should be open or not. so this change checks if the `open` prop is non-null before looking at internal state

**Comment by asudoh** [comment]
I see, but I thought in the `<Tooltip>` code the `open` prop and the `open` state are in sync? Did you find it differently?

**Comment by emyarod** [comment]
yeah it seems to get out of sync when dealing with mouse clicks. still trying to determine why that's the case

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod for having been looking at this and finishing this up!

**Review by tw15egan — APPROVED** [review]
LGTM 👍

**Pull request merged**
