### PR TITLE
fix(link): remove visited styles by default

### LINKED ISSUE #3581: [Link]: Inline option should be same color as text and underlined by default

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/3581

Removes `:visited` styles by default. If the link has a `bx--link--visited` class, it will receive visited styles once a link has been visited.

Not sure if `bx--link--visited` is the greatest name, since it will have that class _before_ it is actually visited, so open to suggestions. 

#### Changelog

**New**

- `bx--link--visited`, which will add `:visited` styles once a link has been clicked
- `visited` prop that will add the class that will allow visited styles when using React `Link`

**Removed**

- Links will no longer receive `:visited` styles by default.

#### Testing / Reviewing

Click the first link, and see that it **does not** change to visited styles. 
Click the second link, and see that it **does** receive visited styles.

### CODE REVIEW

**Comment by joshblack** [comment]
Quick question, do we know when links should have the visited style versus not? Or is it up to a product team versus a system decision

**Comment by tw15egan** [comment]
> Quick question, do we know when links should have the visited style versus not? Or is it up to a product team versus a system decision

I believe we as a system want visited styles disabled but with the added functionality for a team to have visited links if they are required to have them.

**Comment by aagonzales** [comment]
Most of the time in product links don't have a `visited` state because they aren't one time instances. They're intended for the user to visit anytime they need too. I actually don't really understand when you would use a `visited` state unless it was for learning material and you need to know what you've read already.

**Review by jeanservaas — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 assuming making visited state optional is the design intent. Thanks @tw15egan!

**Comment by abbeyhrt** [comment]
Do we know why the visited link color change was added? It was added pretty recently, v10.7 or 10.6 I think and it never seemed like anybody on our side wanted it

**Comment by laurenmrice** [comment]
I believe that was a v10 design language addition to add the purple visited link option.

**Comment by aagonzales** [comment]
We added it for the website I think and somehow it became default in the component/

**Comment by abbeyhrt** [comment]
Isn't it overwritten in the website?

**Comment by mjabbink** [comment]
Would love to see it go away in product for sure. The dot com team may have some research to back up keeping it in their world but not sure if they do. My hunch is it can be removed in dot com experiences as well.

**Review by dakahn — APPROVED** [review]

**Pull request merged**
