### PR TITLE
feat(MultiSelect): new hideLabel prop

### PR DESCRIPTION
**Pull request by kinueng**
Add a `hideLabel` prop similar to the `Dropdown` component (ref #7594 ref #7571).  The `titleText` is the currently the only way to set the `<label>` but there is no way to visually hide the `titleText` when it is set.  

image

#### Changelog

**New**

- `hideLabel` prop to allow for the hiding of the title text

#### Testing / Reviewing

I am not sure how to build and test this pull request.  I am hoping opening this pull request will deploy my pull request in a demo site where I can try the file changes.

### CODE REVIEW

**Comment by sstrubberg** [comment]
recheck

**Review by sstrubberg — CHANGES_REQUESTED** [review]
Thanks for the PR.

Couple of things that might help resolve your CI errors.

1) Run `yarn test packages/react/__tests__/PublicAPI-test.js -u` from the root of the project. That might resolve the following error. If you made any manual changes to this file, I would undo them first, then run the command.
image

2) Run `yarn format:diff` from the root of the project to clean up any formatting errors.

**Comment by kinueng** [comment]
recheck

**Review by sstrubberg — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
Looks good

**Pull request merged**
