### PR TITLE
refactor(button): convert to flex container

### LINKED ISSUE #2103: Convert buttons to flex containers
We currently use absolute positioning to place icons within buttons, and one of the reasons behind this is due to an outdated assumption that buttons are not supported as flex containers (https://github.com/IBM/carbon-components/blob/master/src/components/button/_button.scss#L180)

That issue has since been resolved (see https://bugzilla.mozilla.org/show_bug.cgi?id=984869 and https://bugzilla.mozilla.org/show_bug.cgi?id=1176786). We also were already making our ghost buttons flex containers, so it may be worth refactoring the base button mixin to reflect that change in all button types

This change would also help with custom button content positioning such as the custom feature tiles on https://next.carbondesignsystem.com/

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2103

This PR converts our button classes to display as flex containers and adds additional documentation examples related to https://github.com/IBM/carbon-components-react/pull/1891

#### Changelog

**New**

- component examples with different root nodes using button classes

**Changed**

- convert button classes to display as flex containers
- spacing rules

**Removed**

- absolute positioning rules

#### Testing / Reviewing

Ensure any components consuming buttons or button classes are not broken

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by dakahn — APPROVED** [review]
Looks great

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] The only thing I am seeing that needs to be changed is the ghost buttons spacing. There needs to be 8px between the text and the icon but still keeping the 16px padding on either side of the background color. This is only for ghost button.
Screen Shot 2019-03-15 at 10 28 13 AM

**Comment by shixiedesign** [comment]
- [x] Looks like all the `Alternate root node` buttons only got the Blue 3px border, missing white inset outline.
image
- [x] The thing Lauren said. Sorry, nitpick, 16padding include the 1px border. Now things add together, edge of button is 17px away from copy.
image

**Comment by emyarod** [comment]
@laurenmrice @shixiedesign 

just to clarify: we want 1px border with 15px left and right padding, is that correct?

the alternate root node example is a `<p>` element, and `<p>` normally cannot receive focus. I've added a tabindex so it can now be focused and you can see the focus styles will be applied now

**Comment by asudoh** [comment]
@emyarod Is this PR ready for re-review? Thanks!

**Comment by emyarod** [comment]
@asudoh yes, although I need clarification on the padding values

**Comment by shixiedesign** [comment]
@emyarod Yeah. The type should be 16px away from edge of button, so including the border. If how it works is padding doesn't include border, we should make padding 15px + 1px border to make sure type align when buttons shows up in any layout. (below image not to scale)
image

**Comment by emyarod** [comment]
got it, side spacing should now be fixed @shixiedesign

**Review by laurenmrice — APPROVED** [review]
Looks good to me ! 👍

**Pull request merged**
