### PR TITLE
refactor(tooltip): avoid calc inside `transform` for IE support

### LINKED ISSUE #3671: ToolTip Icon: Tooltip in IE is separated from pointer
## What package(s) are you using?

- [x ] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
 Looking at the tooltip in IE, the tooltip is separated from the pointer (triangle).

> Is this issue related to a specific component?
tooltip icon
https://angular.carbondesignsystem.com/?path=/story/tooltip-icon--basic

I've been asked to open an issue here since seems to be an issue with the base css. 

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Tooltip attached to the tip. In IE the bottom tooltip placement is looking like a top since its separated from the tip

> What browser are you working in?
IE 11

> What version of the Carbon Design System are you using?
v10.4.1
carbon-angular - 3.13.2

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IWR 

Angular issue that I opened up: https://github.com/IBM/carbon-components-angular/issues/684

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3671

Related: #2781, #3115, #3151

This PR refactors tooltip positioning logic to avoid `calc()` usage inside of CSS `transform` (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/104773/). We now use a combination of TRBL positioning and CSS transforms rather than relying solely on CSS transforms.

We use explicit `rem` values for TRBL positioning (dictated by the spec), and we use percentage values to further translate the position of the tooltip caret and body depending on the desired position and alignment

#### Changelog

**New**

- media query for IE tooltip width and inline block `display`

**Changed**

- tooltip body positioning logic (pure `transform` to TRBL + `transform`)
- tooltip caret positioning logic (pure `transform` to TRBL + `transform`)

**Removed**

- now unused Sass variables
- unsupported `initial` and `max-content` values in IE

#### Testing / Reviewing

Ensure tooltips appear correct on all platforms and all existing use cases (including password input, icon-only button)

---

Regarding the point made by @tw15egan in the issue, we have a few options WRT `width: max-content` usage:

we can either apply a workaround for all browsers or add IE specific rules (I guess this is progressive enhancement vs graceful degradation?)

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
Looks that you figured out! 🎉 Thank alot @emyarod for doing this!

**Comment by emyarod** [comment]
@asudoh any thoughts on the `width: max-content` usage problem?

**Comment by asudoh** [comment]
@emyarod Thank you for double-checking, either way is fine. I'd choose "all browsers" solution if it's straightforward, and choose IE-override solution otherwise.

**Review by joshblack — APPROVED** [review]

**Comment by asudoh** [comment]
@emyarod Should we go ahead with this PR or do you still have some open questions...? Thanks!

**Comment by emyarod** [comment]
@asudoh I will add IE overrides so that we can continue to use `max-content` for browsers that support it

**Comment by emyarod** [comment]
tooltip width is now hard coded for IE, so users will have to modify that to fit their tooltip content on IE

**Comment by asudoh** [comment]
@emyarod Thank you for the update - The latest code LGTM 👍, do you think this PR is ready to go?

**Comment by emyarod** [comment]
@asudoh yes if IE looks good for the reviewers as well

**Review by tw15egan — APPROVED** [review]

**Comment by tw15egan** [comment]
@carbon-design-system/design does this look good?

**Comment by shixiedesign** [comment]
@emyarod Is this refactor supposed to not change the design/behavior? There are some changes to the tooltips from a quick look – is this PR supposed to change how alignments are done? If not calculated, how are the triangles going to line up to "start, center, end"? Eg. below screenshot is supposed to be end alignment, but is not correct: 

image

**Comment by emyarod** [comment]
@shixiedesign this is a refactor, so the behavior is identical to what we settled on previously. IIRC we decided the caret would always be centered and the alignment would only affect the tooltip body

~~I'm still tracing the history of the discussion and will add related tickets below~~ but the behavior you're describing is the current (approved) behavior in `master` branch if I'm not mistaken

the result of our discussion https://github.com/carbon-design-system/carbon/issues/2748#issuecomment-494070401

**Comment by vincentsnagg** [comment]
Hi @emyarod ! I confirmed this fix is working in IE11, but it doesn't seem to work in the latest Edge. Is this something that can also be fixed in this issue?

Screen Shot 2019-08-21 at 1 31 56 PM

**Comment by emyarod** [comment]
@vincentsnagg got it, I was testing on Chromium Edge but I just added a feature query for Edge 12-15 and 16

**Comment by asudoh** [comment]
@shixiedesign Thank you for doing the design review! Does the latest comment from @emyarod make sense? Probably if something has to be changed from UX perspective we can enter a new issue to track it...?

**Review by shixiedesign — APPROVED** [review]
I see. My mistake confusing definition tooltip & icon tooltip. This looks consistent with current behavior. Thanks!

**Pull request merged**
