### PR TITLE
fix(react): uishell headermenu blur handler

### LINKED ISSUE #14614: [Bug]: React HeaderMenu blurHandler does not close menu as expected
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

116.0.5845.140, 117.0

### React version

18.2.0

### Description

When tabbing through a sub-menu, after tabbing off of the last menu item, the menu should close. It only closes when tabbing to another submenu heading.

Also, when trying to extend the HeaderMenu to implement a flyout for third-level navigation, the third level menu also fails to close in many scenarios.

The menu should close whenever the user clicks or tabs out of the menu, unless they are moving to a submenu under the current menu item. 

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-ui-shell-header--header-w-navigation

### Steps to reproduce

In the storybook story, click on "Link 4" to focus on the link and open the submenu.
Press the Tab key to move down through items in the submenu
Note that, when on "Sub-link 3" and Tab key is clicked, focus moves out of the submenu, but the submenu remains open.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by cordesmj**
Closes #14614 

This PR modifies the HeaderMenu React component (part of the UIShell) such that when the menu loses focus, the menu is closed.

#### Changelog

**Changed**

- onBlur handler for React `HeaderMenu` changed so that when the menu loses focus the menu is closed, unless focus is going to a child menu.

#### Testing / Reviewing

A basic test can be done on the storybook, as described in the referenced issue. That is, with this change, when tabbing through the submenu under "Link 4" in the storybook, upon pressing the Tab key from "Sub-link 3", focus passes to a link in the page content and the menu should close.

A more significant test can be done by adding a sub-submenu to the submenu. For example, in `packages/react/src/components/UIShell/UIShell.HeaderBase.stories.js`, after line 200, one could add the following:
```
              <HeaderMenu aria-label="Link 4" menuLinkName="Link 4">
                <HeaderMenuItem href="#">Sub-link 1</HeaderMenuItem>
                <HeaderMenuItem href="#">Sub-link 2</HeaderMenuItem>
                <HeaderMenuItem href="#">Sub-link 3</HeaderMenuItem>
              </HeaderMenu>
```
Tabbing around the menus should result in menus closing when losing focus, except when tabbing or clicking into child menus.

This will also facilitate extending the `HeaderMenu` to support a second level 'flyout' with the desired blur behavior.

image

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by cordesmj** [comment]
Hey @tw15egan, just noticed @andreancardona is on vacation this week. Is there some way I can request a review from someone else? I'm kind of eager to incorporate this change into my project, and I don't want to miss a version update. Thanks!

**Review by andreancardona — APPROVED** [review]
Just took a quick look thank you for the contribution @cordesmj !

**Comment by cordesmj** [comment]
> Just took a quick look thank you for the contribution @cordesmj !

Thank you so much, Andrea! Didn't mean to disturb your vacation 🤦

**Pull request merged**
