### PR TITLE
fix(tooltip): ensure esc closes tooltip, avoid bubbling beyond the body

### LINKED ISSUE #10204: Tooltip with focusable element is not accessible on React 17
### Package

carbon-components-react

### Browser

Chrome

### Package version

7.48.1

### Description

We previously opened an issue where a tooltip within a Pal side panel, when it has focusable content like a link, would close the whole side panel when the escape key is pressed.

Carbon released the following fix:

https://github.com/carbon-design-system/carbon/pull/9875

This has fixed the issue for our App if we would be running on React 16. However, we are running on React 17 and it has made things worse:
1. a tooltip on a regular page (not on a side panel) that has focusable content will now NOT close when pressing escape key, it gets stuck.
2. The fix on react 17 does not solve the issue, the side panel still closes (the event escapes)

### CodeSandbox example

https://codesandbox.io/s/stupefied-surf-gtf4z

### Steps to reproduce

(To reproduce first problem)
1. press tab until tooltip icon gains focus, opening the tooltip
2. observe tooltip opening, with focus on the button
3. press ESCAPE key
4. Observe that tooltip does not close
(then for second problem:)
5. press TAB key again so that the button inside the tooltip no longer has focus, and tooltip still open
6. press ESCAPE key
7. Observe that while tooltip closed, key handler on the outside div is being called, when it shouldn't

Then, open this code sandbox, https://codesandbox.io/s/fast-butterfly-d8t4t
this code sandbox is IDENTICAL to the previous sandbox, except it has React version 16. You will see both problems are not present in this sandbox.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tay1orjones**
Closes #10204 

#### Changelog

**New**

- test(tooltip): add test to cover "<kbd>esc</kbd> to close" functionality

**Changed**

- fix(tooltip): remove global/document <kbd>esc</kbd> keyDown handler, replace it with scoped onKeyDown handler on tooltip body
- docs(tooltip): remove interactive elements from the tooltip body in the default story
- docs(modal): add a tooltip to the WithStateManager story to more easily test tooltips inside an element with it's own "<kbd>esc</kbd> to close" handler.

#### Testing / Reviewing

I'm sorry this has quite a few steps to fully test the changes here:

- In the `carbon-components-react` storybook deploy preview:
  - Ensure tooltip without interactive body contents can be closed via <kbd>esc</kbd>
  - Ensure tooltip with interactive body contents can be close via <kbd>esc</kbd>
  - Ensure Modal WithStateManager tooltip can be closed via <kbd>esc</kbd> and _does not close the modal_. A _second_ press of <kbd>esc</kbd> should close the modal.
- Pull this down to test locally - we need to ensure the same steps from above work w/ React v16
  - Modify the react deps in the root `package.json` to be 16.8.6 ([here is a reference](https://github.com/carbon-design-system/carbon/pull/10029/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519) from the PR updating it to v17)
  - Modify the react deps in the `packages/react/package.json` to be 16.8.6
  - `yarn install` at the root
  - `yarn start` the `packages/react` storybook
  - You can validate the storybook is using React v16 by adding a `console.log(React.version);` (anywhere, in a component, etc) - it should output to the console `v16.8.6`
  - Redo the tests that you did on the deploy preview:
    - Ensure tooltip without interactive body contents can be closed via <kbd>esc</kbd>
    - Ensure tooltip with interactive body contents can be close via <kbd>esc</kbd>
    - Ensure Modal WithStateManager tooltip can be closed via <kbd>esc</kbd> and _does not close the modal_. A _second_ press of <kbd>esc</kbd> should close the modal.

### CODE REVIEW

**Comment by tay1orjones** [comment]
@amortiz @lji00 If you have time, I would appreciate your eyes on this to double check we've hit the mark on fixing this one.

**Review by joshblack — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Comment by amortiz** [comment]
@tay1orjones not sure if i'm testing correctly. I went here:
https://deploy-preview-10220--carbon-components-react.netlify.app/?path=/story/components-tooltip--render-custom-icon

So i can click on the tooltip, press ESC when focus is on link/button, and it closes correctly. Once it merges and a new version is available i can test in my code sandbox links i created to confirm on both react 16 and 17

thanks

**Comment by tay1orjones** [comment]
@amortiz thanks! Yeah that's perfect. The storybook is running with React v17 right now.

**Comment by tay1orjones** [comment]
This has been published in v10.49.1. 

Here's two identical sandboxes demonstrating the fix with tooltip <kbd>esc</kbd> working as intended with both React v16 and React v17:

React 16: https://codesandbox.io/s/carbon-tooltip-escape-delegation-react16-l1ih9
React 17: https://codesandbox.io/s/carbon-tooltip-escape-delegation-react17-pydv4

**Pull request merged**
