### PR TITLE
refactor(react): update ProgressIndicator to FC

### LINKED ISSUE #10281: Wrap remaining class components with function export
For components identified as lower priority in the functional refactor workstream https://github.com/carbon-design-system/carbon/issues/9712#issuecomment-962238781, we should explore providing a functional wrapper export for these components so we can refactor them away from classes at a later date without requiring a major version bump.

**Checklist**

- [x] InlineCheckbox
- [x] ProgressIndicator
- [x] FileUploader
- [x] Slider

### PR DESCRIPTION
**Pull request by joshblack**
Closes #10281

This PR updates `ProgressIndicator` to a functional component

#### Changelog

**New**

- Add `next/ProgressIndicator.js` and corresponding tests

**Changed**

- Toggle on classic vs next ProgressIndicator behind feature flag

**Removed**

#### Testing / Reviewing

- Verify Progress Indicator continues to work in classic storybook
- Verify Progress Indicator works in next storybook

### CODE REVIEW

**Comment by jnm2377** [comment]
Screen Shot 2022-01-11 at 10 38 47 AM

Looks like some of the progress indicator styles are off in the v11 progress indicator, but I don't think it's bc of your PR. Some styles might've not been ported over, bc the carbon-next current storybook has these bugs too.

**Review by jnm2377 — APPROVED** [review]
approving since the style bugs already exist

**Comment by joshblack** [comment]
bump @dakahn when you get a sec!

**Review by dakahn — APPROVED** [review]
🏄🏾

**Pull request merged**
