### PR TITLE
feat(tabs): add support for secondaryLabel

### LINKED ISSUE #12843: ContainedTabs: provide contained w/ secondary label tab layout helper/component
This issue is for providing a layout helper component for contained tabs a secondary label.

Open questions:
- Can contained tabs with secondary labels be dismissable?
  - If so, it could potentially create a ui shift if the last tab with a secondary label is dismissed causing the entire tab list to be shorter.
- Can contained tabs with a secondary label be mixed with other contained tabs without secondary labels?
  - A: Yes, but the height remains the same (taller than default tabs)
- Could/should this just be a prop instead of a layout helper component?

[Spec](https://carbondesignsystem.com/components/tabs/usage#anatomy-of-contained-tabs)

https://github.com/carbon-design-system/carbon/issues/12843#tasklist-block-f601d63f-ad41-4ab2-8097-6f6a8ac35601

### PR DESCRIPTION
**Pull request by francinelucca**
Closes #12843 

Adds `secondaryLabel` prop to `Tab` renderable in contained tabs. Also adds styling and tests to support functionality.
 
#### Changelog

**New**

-  new `secondaryLabel` prop in Tab
- `Contained With Secondary Label` Tabs story
- Percy e2e for new `Contained With Secondary Label` Tabs story
- RTL test cases for new `secondaryLabel` prop in Tab

#### Testing / Reviewing

https://deploy-preview-13366--carbon-components-react.netlify.app/?path=/story/components-tabs--contained-with-secondary-label should match [spec](https://github.com/carbon-design-system/carbon/issues/8487#issuecomment-1472662769)

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by tay1orjones — APPROVED** [review]
🎉

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Actually I just saw something on Percy - the alignment of icon only tabs has shifted slightly.

https://user-images.githubusercontent.com/3360588/226920704-46a2ce95-9ec7-4424-96ce-e9f5b0c6a06b.mov

**Comment by francinelucca** [comment]
> Actually I just saw something on Percy - the alignment of icon only tabs has shifted slightly.

Fixed!

**Review by laurenmrice — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
