### PR TITLE
fix(tooltip): match experimental spec

### LINKED ISSUE #1954: [Audit] Tooltip
## Interactive Tooltip

- [x] Button should not have vertical padding

Expected:

screen shot 2019-02-28 at 10 23 39 am

Actual:

screen shot 2019-02-28 at 10 23 42 am

- [x] Label should be label-01, #565656

- [x] Icon should use #565656, what's the token @jeanservaas?

- [ ] What should the vertical distance be between the tooltip box and the icon? Seems like it's 13px in the spec but 16px in the implementation cc @jeanservaas 

- [ ] Test needs to use `body-long-01`

## Icon Tooltip

- [x] Direction of tooltip seems flipped, should go down but is going up
- [x] Height should be 24px, right now it's 32px
- [x] Text should use `body-short-01` token

## Definition Tooltip

- [x] Tooltip background should not have right padding

Expected:

screen shot 2019-02-28 at 10 30 33 am

Actual:

screen shot 2019-02-28 at 10 30 37 am

- [ ] Tooltip text should be centered

- [x] What type style should this use @jeanservaas? `body-short-01`? In spec it's IBM Type C

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1954

This PR incorporates feedback from the February 2019 tooltip component audit

### CODE REVIEW

**Comment by jeanservaas** [comment]
Looks great one last comment on icon tooltip, the niche is a little bit smaller than the design spec

- [x] could you update the size of the icon tooltip niche to 9px (width) by 5px (height)

image

Dev right now:
image

Also, this is OUR BAD... we found a problem with the geometry of our Definition tooltip when it's used in progress indicator, the 16px top margin just seemed like too much real estate... we decided to change it to make it more compact:

- [x] change top and bottom margin on definition tooltip to 8px (from 16px)... sides stay 16px

image

**Comment by emyarod** [comment]
got it, let me know how the updates look now @jeanservaas

**Comment by jeanservaas** [comment]
@emyarod this looks great

one last thing, looks like there's some leftover right padding on defintion tooltip, can we remove it?

image

spec just specifies 16px

image

**Comment by emyarod** [comment]
@jeanservaas I believe that extra bit of space is unavoidable because of how text wrapping is handled

**Comment by jeanservaas** [comment]
OK if there's nothing we can do about that padding than LGTM

**Review by jeanservaas — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
