### PR TITLE
fix(radio-button): match experimental spec

### LINKED ISSUE #1810: Component Design Audit v1.1 - Radio button
## Radio Button

- Focus state on un-selected needs to not have black stroke

image

- double-check that vertical has 8px of spacing between each

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1810

This PR incorporates the requested radio button changes from the v1.1 component audit

#### Changelog

**New**

- vertical radio button group support and examples

**Changed**

- spacing and colors based on component audit feedback

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]
LGTM! Is `{{@root.prefix}}--radio-button-group--vertical` a new class? If so, we should add it to the migration doc Akira was working on for the components.

**Comment by emyarod** [comment]
yes @jnm2377 I added that since I did not see support for that variation even though it's mentioned in the audit if I understood correctly

cc @asudoh

**Review by aledavila — APPROVED** [review]
lgtm

**Comment by asudoh** [comment]
Yeah the addition makes sense - @emyarod Could you update the migration doc? Thanks!

**Comment by asudoh** [comment]
@jeanservaas @aagonzales Would either of you have a chance for viz review...? Thanks!

**Review by aagonzales — APPROVED** [review]
lgtm

**Pull request merged**
