### PR TITLE
fix(search): add styles for custom search buttons

### LINKED ISSUE #2042: [Carbon X] Search button styles not present in search--x mixin
## Detailed description

The optional buttons that can be added to a `Search` component have no styles in the `search--x` mixin for Carbon X. In the React library, those buttons are referring to as `SearchFilterButton` and `SearchLayoutButton`

(See React storybook for example for the buttons I'm referring to: http://react.carbondesignsystem.com/?selectedKind=Search&selectedStory=custom%20buttons&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel)

These are styles for v9 (https://github.com/IBM/carbon-components/blob/master/src/components/search/_search.scss#L113):

```
  .#{$prefix}--search-button {
    @include reset;
    border: 0;
    transition: $transition--base;
    height: rem(40px);
    width: rem(40px);
    min-width: rem(40px);
    margin-left: $spacing-2xs;
    background-color: $ui-01;
    position: relative;
    padding: 0;
    outline: 1px solid transparent;
    order: 2;
  }

  .#{$prefix}--search-button svg {
    position: relative;
    top: -1px;
    box-sizing: border-box;
    vertical-align: middle;
    transition: $transition--base;
    fill: $hover-primary;
    height: 1rem;
    width: 1rem;
}
```

However there are no equivalent styles for v10 & the buttons currently render as un-styled.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #2042 

Adds some styles for custom `Search` buttons. Please let me know what you think 🤔 I just went with the look of the close button + what we have in our storybook, so I'm happy to adjust. 👍 

The buttons basically look like this:
Screen Shot 2019-07-01 at 4 20 27 PM

#### Changelog

**New**

- add styles for `.bx--search-button`

**Changed**

- ended up rearranging `.bx--search-close` styles a little so it could share styles for `.bx--search-button`

**Removed**

- extra/repeated focus style rule for `.bx--search-close`

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by shixiedesign — COMMENTED** [review]
Hi Jen, style looks good! But just wondering if adding buttons is something we can achieve with Toolbar component? https://the-carbon-components.netlify.com/?nav=toolbar

**Comment by jendowns** [comment]
Thanks @shixiedesign! I'm not familiar with that component 🤔 Looks like it is styled a little strangely when I interact with it? 

Screen Shot 2019-07-02 at 10 02 00 AM

I was looking at this particular React variation of the `Search` here: http://react.carbondesignsystem.com/?path=/story/search--custom-buttons

Perhaps the styling could be consolidated but it seems like the `Toolbar` needs a little work first? 🤔 What do you think?

**Comment by shixiedesign** [comment]
Ouch yes I'm doing another QA pass on the components so thanks for pointing that out about the tool. Will need to fix that. Thanks for the Search variant fix! I think we can merge since this is an update to existing component and think about consolidation / guidance later.

**Review by shixiedesign — APPROVED** [review]

**Comment by jendowns** [comment]
Thanks @shixiedesign! Just FYI I think the react version of the `Tooltip` has some interesting things going on as well -- for example it has a different (older styled?) close button when you enter text in the search field:

Screen Shot 2019-07-02 at 11 17 27 AM


See: http://react.carbondesignsystem.com/?path=/story/toolbar--default

**Comment by shixiedesign** [comment]
Thanks @jendowns , I'm double checking with other designers and will make an issue for this component once I'm sure! Looks like it's lumped into data table at the moment so I'm not exactly sure where the styling went coz data table (last I checked) looked okay...

**Review by dakahn — APPROVED** [review]

**Pull request merged**
