### PR TITLE
feat(icons): new icons june thru august

### PR DESCRIPTION
**Pull request by conradennis**
Submitting new and updated UI icons from June through August 2023 all updates and additions approved by BXD

**NOTE: this batch includes UI icons for the new watsonx platform and product offerings so expedited approval and merging into the repo would be greatly appreciated.**

44 net new icons (47 including the 3 renamed icons) 
4 updated icons
3 renamed icons
3 deprecated icons

The 3 renamed icons correspond to the 3 deprecated icons and are technically considered new icons by Github

updated categories.yml with additions and updates
updated deprecated.yml with deprecated file names
updated ui-icon-master.ai with additions and updates

#### Changelog

**Net New**
– 32/add--large.svg
– 32/business-processes.svg
– 32/carbon-for-mobile.svg
– 32/chart--dual-y-axis.svg
– 32/close--large.svg
– 32/data--unreal.svg
– 32/global-loan-and-trial.svg
– 32/ibm--ai-on-z.svg
– 32/ibm--aiops-insights.svg
– 32/ibm--cloudant.svg
– 32/ibm--db2-warehouse.svg
– 32/ibm--event-automation.svg
– 32/ibm--event-endpoint-mgmt.svg
– 32/ibm--event-processing.svg
– 32/ibm--event-streams.svg
– 32/ibm--power-vs-private-cloud.svg
– 32/ibm--saas-console.svg
– 32/ibm--turbonomic.svg
– 32/ibm--vpn-for-vpc.svg
– 32/ibm--wazi-deploy.svg
– 32/ibm-cloud--bare-metal-server.svg
– 32/ibm-cloud--bare-metal-servers-vpc.svg
– 32/ibm-cloud--hpc.svg
– 32/ibm-cloud--virtual-server-classic.svg
– 32/ibm-cloud--virtual-server-vpc.svg
– 32/ibm-watsonx--code-assistant.svg
– 32/ibm-watsonx--code-assistant-for-z.svg
– 32/ibm-watsonx--orchestrate.svg
– 32/ibm-z-os.svg
– 32/logo--gitlab.svg
– 32/model--tuned.svg
– 32/prompt-session.svg
– 32/settings--edit.svg
– 32/subtract--large.svg
– 32/sustainability.svg
– 32/text--long-paragraph.svg
– 32/text--short-paragraph.svg
– 32/tuning.svg
– 32/vegetation--encroachment.svg
– 32/vegetation--height.svg
– 32/watsonx.svg
– 32/watsonx-ai.svg
– 32/watsonx-data.svg
– 32/watsonx-governance.svg

**Updated**
– 32/close.svg
– 32/data--reference.svg
– 32/data--set.svg
– 32/ibm--db2.svg

**Renamed**
– 32/database--enterprisedb.svg
– 32/ibm-cloud--vpc.svg
– 32/ibm-watsonx--assistant.svg

**Deprecated**
– 32/database--enterprise-db2.svg
– 32/virtual-private-cloud--alt.svg
– 32/ibm-watson--assistant.svg

### CODE REVIEW

**Comment by jaywarfield** [comment]
Looks great.  An update to ibm-cloud--transit-gateway.svg is also needed, whether it's included now or in a future batch.  The update had already been made but may not have had a UI issue opened for it until now with [issue 263](https://github.ibm.com/brand/ui-icons/issues/263).

**Review by laurenmrice — APPROVED** [review]

**Comment by laurenmrice** [comment]
> NOTE: this batch includes UI icons for the new watsonx platform and product offerings so expedited approval and merging into the repo would be greatly appreciated.

Hey @conradennis , how soon do you need these to appear in code/website/design kit? Our next release is scheduled for next week, is that soon enough?

**Review by tay1orjones — APPROVED** [review]
I just generated the updated `icons.yml` file 👍

**Review by tw15egan — APPROVED** [review]

**Comment by DianaStanciulescu** [comment]
hi, conrad is out - if you can do a push sooner we would appreciate it :D

**Pull request merged**
