### PR TITLE
chore(test): upgrade Karma

### LINKED ISSUE #1159: Maintenance: Upgrade Karma
### Summary

This issue is for tracking a maintenance effort to upgrade to Karma 3.

### Justification

For continuous effort for us to maintain our toolstack up-to-date.

### Desired UX and success metrics

Ensuring our code work with the latest toolstack.

### "Must have" functionality

Karma 3 and code changes associated with that.

### PR DESCRIPTION
**Pull request by asudoh**
This change also removes space/enter key handling code in search toolbar, because that never runs as `<button>`'s click event handler takes care of the user gesture.

Another note is that the newer Karma/Jasmine combination makes test execution order random by default. I tried to fix the tests depending on execution order, but turned that off to avoid flaky test results in Travis.

Fixes #1159.

#### Changelog

**New**

- `--random` option for `gulp test:unit`, to enable random test execution order

**Changed**

- Upgraded Karma/Jasmine, both to `v3`
- Fixed tests that depend on test execution order

**Removed**

- Enter/space handling code in search toolbar, which never runs as `<button>`'s click event handler takes care of the user gesture

#### Testing / Reviewing

Testing should make sure our unit tests as well as search toolbar are not broken.

### CODE REVIEW

**Comment by alisonjoseph** [comment]
screen shot 2018-10-11 at 8 41 11 pm
seeing this when I run `yarn test`

**Comment by asudoh** [comment]
@alisonjoseph Thank you for reporting - The log indicates that some tests were failed, but cannot see what test they were. What were they?

**Comment by alisonjoseph** [comment]
screen shot 2018-10-11 at 8 58 34 pm
Sorry, didn't scroll up before. Looks like Test number input is failing for me

**Comment by asudoh** [comment]
Thanks @alisonjoseph! Added an attempt to fix the test.

**Review by alisonjoseph — APPROVED** [review]
Tests are passing now 🎉

**Review by joshblack — APPROVED** [review]

**Pull request merged**
