### PR TITLE
fix(code-snippet): fix gradient in Safari

### LINKED ISSUE #4769: Code snippet fade effect is inconsistent in Safari
## What package(s) are you using?

Mac os Catalina 10.15.1
Safari 13.0.3
carbon-components 10.7.4
carbon-components-react 7.7.4

## Detailed description

The ::after pseudo element of the code snippets are a dark gray.

## Is this issue related to a specific component?
Yes, the single and multi-line code snippets

## What did you expect to happen? What happened instead? What would you like to see changed?
The pseudo element for the text fade effect blends with the background

## What browser are you working in?
Safari

## Steps to reproduce the issue
1. Step one - Using safari browser http://react.carbondesignsystem.com/?path=/story/codesnippet--multi-line

## Additional information

- Screenshots or code
Screen Shot 2019-11-25 at 7 52 20 AM
Screen Shot 2019-11-25 at 7 52 42 AM

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #4769.

#### Changelog

**Changed**

- The way the scroll overflow indicator is created with gradients.

#### Testing / Reviewing

Testing should make sure code snippet and modal are not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, the Safari issue is resolved

**Review by jendowns — COMMENTED** [review]
So this is a different approach to my PR #4770 😅 
Should I close mine out?

**Comment by joshblack** [comment]
What's the difference in the two approaches @jendowns?

**Comment by jendowns** [comment]
Hey @joshblack! My PR used the `rgba` Sass function which unfortunately won't work with these demo environments... it looks like the custom properties output prevents the `rgba` function from compiling into valid CSS. 😅 I went ahead and closed by PR. @asudoh's fix here looks great 👍

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! I checked Safari, FF,  and Chrome with all the themes and all seems good!

**Comment by joshblack** [comment]
Would we want to explore the rgba fix as opposed to what's been proposed here? I know personally I'm pretty unfamiliar with `mask-image` and it seems we also need to handle high contrast for ms. Is this a case in either PR, or for this approach?

**Comment by asudoh** [comment]
I guess the scroll overflow UI is a supplemental UI (for better user assistance for limited use case) instead of the primary UI, and thus I don't think high contrast was the scope of the original scroll overflow UI - We can see it from the gradient nature.

I'd like to limit the scope of this work, focusing on fix the Safari problem. As @jendowns alluded to, `rgba(var(--cds-ui-01), 50%)` thing doesn't work, which led to the code in this PR.

**Comment by joshblack** [comment]
@asudoh definitely understand that it doesn't work with the CSS Custom Properties but we don't publish anymore with this feature turned on so shouldn't be a problem outside of dev/preview sites, right? Since that feature is behind a flag I think we would be fine with having it not work for this use-case.

**Comment by asudoh** [comment]
Can we keep using the flag to turn on CSS Custom Properties feature when the code behind the flag matures, If we make components not work with CSS Custom Properties for the sake of "CSS Custom Properties is behind the flag"?

**Comment by joshblack** [comment]
Not sure I understand, what are you asking? If I understand things correctly, it seemed like the only reason we couldn't go with #4770 was because of custom properties. If that's the case, it seems fair to say we could move forward with that approach since custom property support is not stable. The specific issue for the rgba case is tracked over in: https://github.com/carbon-design-system/carbon/issues/4426

**Comment by asudoh** [comment]
We can replace the change here with `rgba()` once #4426 has been merged.

**Comment by joshblack** [comment]
My hope was that we can move forward with an approach that is seemingly more familiar with folks on the team if the problem it introduces is behind a flag and is considered experimental. I think that is fair and something we should consider 👍

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Vanilla:

Multi line:
This shouldnt be getting a fade gradient on the right hand side.
Screen Shot 2019-12-06 at 2 48 59 PM

React:
copy button is broken in both single line and multi line. 
Screen Shot 2019-12-06 at 2 50 03 PM

**Comment by alisonjoseph** [comment]
Recommend that we go with the `rgba()` solution here. (it is ok for now that this will not work with the css custom properties)

**Comment by asudoh** [comment]
Closing upon above comment, and reopening #4770.

**Pull request closed without merging**
