### PR TITLE
fix(react): use slider label for slider and input by default in V11

### LINKED ISSUE #10172: [a11y]: slider label is not used for slider input label
### Package

carbon-components

### Browser

Chrome

### Operating System

MacOS

### Package version

https://react.carbondesignsystem.com/?path=/story/components-slider--default

### Automated testing tool and ruleset

n/a

### Assistive technology

_No response_

### Description

The label for the slider should be associated with both the thumb slider and the input.

Fully discussed in internal discussion https://ibm-studios.slack.com/archives/G01GCBCGTPV/p1631717241028100

### WCAG 2.1 Violation

3.3.2 Label or Instructions

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-slider--default

### Steps to reproduce

Inspect the code. The input's label is hard-coded by aria-label, instead of pointing to whatever value the designer has assigned for the text appearing as "Slider label"

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #10172 

Updates `Slider` label to be `for` the `input` by default and removes the default prop for `ariaLabelInput` in v11. I could be wrong but it felt weird to have an aria label and a label for the input so that's why I removed the default prop value. 

Question, should `labelText` be required since it's automatically used to label the slider and now the input potentially? I know users could still provide an aria label for the input but without `labelText` the slider has no associated label. 

#### Changelog

**Changed**

- Slider label now optionally labels the input

#### Testing / Reviewing

Go to the storybook Slider's playground story and remove `ariaLabelInput` and verify that the `for` from `label` has the same id as the `input`.

### CODE REVIEW

**Comment by tay1orjones** [comment]
> should `labelText` be required

That might be more a question for @carbon-design-system/design. I'd lean towards no. If it's required, users won't be able to configure a slider without a visible label. 

It's one of those odd situations where the props are sort of conditionally required based on one another. If there's no `labelText`, ideally `ariaLabelInput` would be required (or have a default). That might be a reason to leave in the default for `ariaLabelInput`? Also would it make sense to apply `aria-label={ariaLabelInput}` to the slider if there's no `labelText`?

**Comment by abbeyhrt** [comment]
@tay1orjones I see what you mean and I think I would prefer to keep the default for `ariaLabelInput` too but then `{ariaLabelInput ? ariaLabelInput : null}` would just always be the default unless someone explicitly says `ariaLabelInput=''`, right?  

Thinking about what you said, I’m kind of not sure if I agree with Michael Gower’s original point in [the thread](https://ibm-studios.slack.com/archives/G01GCBCGTPV/p1631717241028100) that kicked off the issue. I think it would make sense for the `label` to label the slider and `input` if `labelText` was required, but since that is optional, it feels strange to me to rely on it in two places. Especially if that means not having a default for `ariaLabelInput`. To me, there are two tracks: the label for the input and the label for the slider and it seems okay to me if they stay separate like they are now

**Review by tay1orjones — COMMENTED** [review]
@abbeyhrt Yeah, I agree with what you're saying. Especially about there being two tracks. 1. labelling the slider and 2. labelling the input. 

Would it be best if we could cover both together, but also enable each to be individually labelled as well in the event `labelText` isn't provided? If so, this is most of the way there:

- [x]  Cover both tracks by leaving `labelText` optional and have it linked to both the slider and the input 
- [ ] Cover track 1 by providing the option to label the slider via a new prop `ariaLabelSlider` (with no default)
- [x] Cover track 2 by providing the option to label the input via the existing prop `ariaLabelInput` (with no default)

**Review by tay1orjones — APPROVED** [review]
@abbeyhrt Worth stating that despite my thoughts above, I'm also totally fine merging this as is! 

The primary feedback from Michael is covered by you adding ``htmlFor={`${id}-input-for-slider`}`` to the `label` 👍

**Review by dakahn — APPROVED** [review]
Tested with NVDA and JAWS latest on Windows 11

Nice work! I can detect no discernable difference between our previous implementation and this one, except that with NVDA the number input reads the Slider label whereas before it did not. Which is awesome 👍🏾 🏄🏾

**Comment by abbeyhrt** [comment]
Okay, I think i'm going to leave this as is for now and merge it in. Slider still needs to be refactored to a functional component so we might be able to revisit this then.

**Comment by mbgower** [comment]
> I think it would make sense for the label to label the slider and input if labelText was required, but since that is optional, it feels strange to me to rely on it in two places. Especially if that means not having a default for ariaLabelInput. To me, there are two tracks: the label for the input and the label for the slider and it seems okay to me if they stay separate like they are now

@abbeyhrt and @tay1orjones Thanks for implementing a change for this issue!

I just wanted to respond to this comment. The accessibility challenge here is to try to reduce the effort to make a consistently named slider and input. If the designer must always annotate the name of the slider input in addition to naming the slider, there's more work. If the developer must always implement the slider input name, there's more work. There's also obviously more chance for the name to be overlooked. At that point, you end up with one or both of the slider inputs inheriting whatever generic label is in the code. The latter is "Label for slider value" which I think we can agree not great. (At the _least_ , shouldn't it be improved to something like "slider value"?)

It might be easier to think of the construct this way: the slider must have an accessible name.

One of two things must occur. Either the slider has a (properly constructed) visible label or it has an accessible name (usually set by aria). The input for the slider is optional, but if it is there, it never has a visible label. If it always takes whatever name is specified for the slider, it's tough for an implementer to get it wrong.

When you do refactor the slider component, ideally the code can be constructed such that this always comes about.

**Pull request merged**
