### PR TITLE
chore(rename): renames all -test files to .test

### LINKED ISSUE #2535: Babel is failing to ignore stories and tests during build
## Detailed description

As of know, the `-story.js` and `-test.js` ignoreGlobs aren't matching so we're compiling and shipping tests and stories to end users.

> Is this issue related to a specific component?
No

> What did you expect to happen? What happened instead? What would you like to see changed?
The naming strategy could be altered to fit the more traditional .test.js and .story.js format

## Steps to reproduce the issue

1. yarn build
2. inspect the `es` and `lib` individual component folders

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/2535

Updates all  `-test.js` files to  and `.test.js` so that the glob successfully matches and does not include these files in our build. We also now get the custom icons for test files 🎉

Screen Shot 2020-06-12 at 1 51 05 PM

#### Changelog

**Changed**

- Lots of filenames

#### Testing / Reviewing

Make sure all tests still run, and the storybook environment is the same.

Run `yarn build` in the react package, and ensure no test files are included in the `es` or `lib` output folders

### CODE REVIEW

**Comment by joshblack** [comment]
@tw15egan this _might_ impact some of the teams pulling in our stories potentially, just as a heads up.

cc @jendowns @tay1orjones do you all still bring in stories for your storybooks or no? 👀

**Comment by joshblack** [comment]
Do we know why the glob wasn't working previously btw? Story changes seem great, test files would be great to keep the test file strategy consistent between standalone and ones in `__tests__` if we could (`*-test` pattern)

**Comment by tw15egan** [comment]
👍 I threw this up to start a discussion around this, because definitely not sure how far-reaching this change can be

Not sure how much work would need to be put into exporting the stories, but can definitely look into that first if this will break people
https://github.com/carbon-design-system/carbon/issues/2570

**Comment by tw15egan** [comment]
@joshblack after doing some research into why the globs weren't working it seems like babel doesn't utilize the glob package directly, so `*-story` was trying to match to files literally named `*-story`

**Comment by tay1orjones** [comment]
@joshblack @tw15egan Yeah, we import stories from your build and include them in [our storybook](https://carbon-addons-iot-react.com/). We have them placed in [the 'others' section](https://carbon-addons-iot-react.com/?path=/story/accordion--default) and renamed it to 'Carbon' via a pseudo element overlay.

This would break that for us - we'd probably be looking at copy/pasting stories from your codebase and then manually keeping them up to date when we update to new releases. We could potentially script that, but a more formal solution for story reuse would be nice.

**Comment by tw15egan** [comment]
@tay1orjones yeah definitely don't want to break it for y'all. I haven't dug into much regarding Component Story Format, but if we could add the knobs as parameters then that seems like the next step before we go any further with these renames.

**Comment by tw15egan** [comment]
@tay1orjones I threw up a PR that is switching our Accordion to the new storybook format. Is this all that would be needed (for each component)? 

https://github.com/carbon-design-system/carbon/pull/6284

**Comment by tw15egan** [comment]
@tay1orjones @joshblack I've updated this PR to just included a change to the test file names. I have a PR up exploring exporting storybook stories in the CSF format (just Accordion for now) if y'all want to take a look. I'm not sure exactly how you are importing them now vs what you would need to do differently with the proposed format but would love to get some eyes on it.

**Comment by tay1orjones** [comment]
@tw15egan I think that would work for us. I posted a comment on the other PR with some thoughts/questions around what it specifically might look like.

Currently we re-export Accordion in our library with no modifications. So we directly reuse your story file by having an `Accordion.story.jsx` that contains

```js
export {
  default as AccordionStory,
} from 'carbon-components-react/lib/components/Accordion/Accordion-story';
```

**Comment by joshblack** [comment]
@tw15egan would we want to add `**/*-test.js` to our `.npmignore` file? It might be a good short-term fix instead of needing to rename files.

**Comment by tw15egan** [comment]
@joshblack if we are concerned with unintended problems with the name change we can go that route

**Comment by joshblack** [comment]
@tw15egan just was to minimize the number of changes that needed to happen for the issue. If we want to start communicating that test files should be written with `*.test.js` we could definitely make that change, just was offering something else that seemed like fewer changes in the PR and for the team.

**Pull request closed without merging**
