### PR TITLE
fix: datepicker onchange trigger issue

### LINKED ISSUE #13128: [Bug]: manually input end date for range in DatePicker make dateFormat wrong
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.22.0

### React version

v17.0.2

### Description

when set DatePicker's dateFormat="d/m/Y", the date format will wrong after change end date manually

### Reproduction/example

https://stackblitz.com/edit/github-bcvgpb?file=src/App.jsx

### Steps to reproduce

1. Select start and end date (29/01/2023 and 09/02/2023)
2. change the end date manually to `08/02/2023`, onblur the input box
3. the end date input value become `02/08/2023`
4. the start date input value become `aN/aN/0NaN`

### Suggested Severity

Severity 1 = Must be fixed ASAP. The response must be swift. Someone from the team must drop all current work and be immediately reassigned to address the issue.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #14047: [Bug]: Datepicker range: Picking a 1st date which is beyond the date selected will automatically make that as the 2nd date but going out of the date picker component will change the 2nd date to be the max date from the previous selection.
### Package

@carbon/react

### Browser

Chrome

### Package version

v1.3.11

### React version

v18.1.0

### Description

[Bug]: Datepicker range: Picking a 1st date which is beyond the date selected will automatically make that as the 2nd date but going out of the date picker component will change the 2nd date to be the max date from the previous selection.

Expection is that the end date should be cleared and focus should move to end date.

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

### Steps to reproduce

Go to https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar

Select start date as June 1st.
Select end date as June 3rd.
Go back to start and and select June 4th, this in turn will automatically change end date to June 4th while making the previous end date (June 3rd as the start date)

Click outside the date picker and it will automatically change the end date to be the same as start date (June 3rd)

### Suggested Severity

None

### Application/PAL

URP

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #14465: [Bug]: Date Picker calls onChange twice
### Package

@carbon/react

### Browser

Chrome

### Package version

1.36.0

### React version

18.2.0 (In Stackblitz.  We're actually still on  16)

### Description

onChange is called both when clicking a date in the calendar and again in onBlur.

### Reproduction/example

https://stackblitz.com/edit/github-y8nl8z

### Steps to reproduce

Click on the calendar icon in a DatePicker field and select a date.  See the onChange console message printed.  Click off the DatePicker such that it loses focus.  See that the onChange is called again.

This is a problem because a xhr request is launched with the onChange so it's happening twice.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

OpenPages

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #15925: [Bug]: DatePicker with Range Component Sets Dates to 2001 When Clicking Outside
### Package

@carbon/react

### Browser

Chrome

### Package version

1.52.0

### React version

v16.14

### Description

When clicking outside the DatePicker with Range component after selecting a range and then reopening the component, it will set the dates to 2001 and not close until you select new dates.

### Reproduction/example

https://stackblitz.com/edit/github-unsz1w?file=src%2FApp.jsx

### Steps to reproduce

Navigate to your [storybook](https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar) for the component. Select a date range. Open the picker back up and click outside the picker.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #16125: [Bug]: Datepicker in range mode fires onChange handler when clicking outside, leading to unexpected dates
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

1.53.1

### React version

_No response_

### Description

When clicking outside a DatePickerInput (after having already set a date previously) the on Change handler fires with unexpected dates in the payload of the handler.

The calendar cannot be closed if the focus is on the second input

### Reproduction/example

The behaviour is present on the online storybook

https://react.carbondesignsystem.com/?path=/story/components-datepicker--range-with-calendar-with-layer

### Steps to reproduce

1) set two dates with the datepicker.

2) click again on one of the inputs to open the calendar

3) click outside or click on another form element or tab away, the onChange will be fired and the date (or both) will change.

If the calendar is open with the click on the second input, it can never be closed clicking outside, and the date will keep change untl it settles to some date in the year 2001

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by riddhybansal**
Closes #16125 
Closes #13128 
Closes #15925
Closes #14047
Closes #14465   

When clicking outside a DatePickerInput (after having already set a date previously) the on Change handler fires with unexpected dates in the payload of the handler.

#### Changelog

**Changed**

- set the allowInput prop on DatePicker to false

#### Testing / Reviewing

- set two dates with the datepicker.

- click again on one of the inputs to open the calendar

- click outside or click on another form element or tab away, Dates should be unchanged .

### CODE REVIEW

**Comment by riddhybansal** [comment]
Using allow input will restrict user for inputing dates without calendars and may led to many a11y issues. The actual issue was in range plugin. From and to dates are not correctly fetched from the flatpicker configs , resulting in formating of dates.

**Review by tay1orjones — APPROVED** [review]
@riddhybansal This looks great! Could a unit test be added to ensure this continues to work as expected in the future?

**Review by alisonjoseph — APPROVED** [review]
LGTM after test is added!

**Review by guidari — CHANGES_REQUESTED** [review]
Hey Riddhi! The fix LGTM!

Just one comment regarding the test case.

I was testing the current version and the bug happens on this sequence:
1 -  The user will add a start and end date
2 - Datepicker has to be closed after the user click in the `document.body` to remove the focus from the component.
3 - The user have to place the focus again in the Datepicker by clicking on the start or end date and the Datepicker will open
4 - Repeat step 2 and the bug will happen

Maybe if you add a step to return focus to one of the inputs before simulate a click, it will cover the bug.

**Review by guidari — APPROVED** [review]
LGTM!

**Pull request merged**
