### PR TITLE
fix(radio-button): use scale instead of px values for checked

### LINKED ISSUE #5163: Radio button alignment is off on Chrome at 110% or 90% zooms, 13" MacBook Pro
## What package(s) are you using?
- carbon-components": "^10.5.0
- carbon-components-angular": "^3.26.0

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
Radio buttons from Carbon Components at 90% or 110% zoom on Chrome is not centered. Seen on Angular and React Carbon Components.
> Is this issue related to a specific component?
Yes
> What did you expect to happen? What happened instead? What would you like to
> see changed?
- The radio button dot in the middle when selected should be centered regardless of zoom on Chrome

> What browser are you working in?
Chrome Version 79.0.3945.130
> What version of the Carbon Design System are you using?
- carbon-components": "^10.5.0"
- carbon-components-angular": "^3.26.0
> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Go to https://www.carbondesignsystem.com/components/radio-button/code/
2. Look at the radio button examples on Chrome and zoom to 90% or 110%.

1. Go to https://www.carbondesignsystem.com/components/radio-button/code/
2. Look at the radio button examples on Chrome and zoom to 90% or 110%.

## Additional information

- 
110% zoom
Screen Shot 2020-01-23 at 4 34 01 PM
normal 100% zoom
Screen Shot 2020-01-23 at 4 34 07 PM

### PR DESCRIPTION
**Pull request by joshblack**
Closes #5163 

Addresses some issues when using zoom for Radio button styles. Instead of using px values, this PR adds in the use of `scale` to correctly size to 8px. It seems like when using exact pixel values the browser will downsize it from 8x8 to nearly 8x8 (7.997 x 7.997) for rastering, which ends up causing the visual regression at certain zoom perspectives.

#### Changelog

**New**

**Changed**

- Use `scale` instead of explicit px values for radio buttons

**Removed**

### CODE REVIEW

**Review by aledavila — APPROVED** [review]
lgtm scales well

**Comment by tw15egan** [comment]
Just an FYI, still seeing some issues at larger/smaller zooms (this is 50%), but this seems to have fixed the 90% / 110% zoom issues.

Screen Shot 2020-05-19 at 12 50 28 PM

**Review by tw15egan — APPROVED** [review]
Approving because it is an improvement (90% and 110% render correctly) and I'm not sure what else we can do since this seems like a browser issue

**Comment by andreped** [comment]
@tw15egan Just out of curiousity? Did you manage to resolve this completely? I have been seeing this for one of my projects, and it is driving med mad.

**Pull request merged**
