### PR TITLE
docs: correct typo in style guide

### PR DESCRIPTION
**Pull request by brnnnfx**
#### Changelog

**Changed**

- Corrected the spelling of `identitiy` in `style.md`

#### Testing / Reviewing

Read the sentence and look for issues with spelling

### CODE REVIEW

**Comment by brnnnfx** [comment]
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> _**I have read the DCO document and I hereby sign the DCO.**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the DCO document and I hereby sign the DCO.

**Comment by brnnnfx** [comment]
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> _**I have read the DCO document and I hereby sign the DCO.**_
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the DCO document and I hereby sign the DCO.

**Comment by brnnnfx** [comment]
recheck

**Comment by brnnnfx** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by brnnnfx** [comment]
recheck

**Review by abbeyhrt — APPROVED** [review]
Thanks for the contribution! 🎉

**Review by joshblack — APPROVED** [review]

**Pull request merged**
