### PR TITLE
chore: remove duplicate scss-to-json dependency

### PR DESCRIPTION
**Pull request by jendowns**
I noticed the following error in the build output of `carbon-components`:

```console
warning package.json: "dependencies" has dependency "scss-to-json"
with range "^2.0.0" that collides with a dependency in "devDependencies"
of the same name with version "1.1.0"
```

It looks like `scss-to-json` is defined in two places:

1. Dependencies: https://github.com/carbon-design-system/carbon/blob/master/packages/components/package.json#L169
2. Dev dependencies: https://github.com/carbon-design-system/carbon/blob/master/packages/components/package.json#L72

I removed the older version in the dependencies but please let me know if you have any concerns. 

#### Changelog

**Removed**

- remove duplicate older version of `scss-to-json` in `package.json`

### CODE REVIEW

**Comment by joshblack** [comment]
cc @vpicone should this be listed in our dependencies? Don't know if I realized it was listed there with the update 🤔

**Review by joshblack — APPROVED** [review]

**Comment by vpicone** [comment]
@joshblack @jendowns yeah it would appear I accidentally added it as a dependency rather than replacing the old devDependency. I actually don’t think we use this library anymore? We should either remove it all together or move it to be a devDep as it was before I failed miserably at updating it.

**Comment by jendowns** [comment]
@vpicone Right now, I have removed it from `dependencies` and kept the more updated version in `devDependencies`. But do you want me to remove it here?

**Comment by vpicone** [comment]
@jendowns I'd defer to @joshblack, but best I can tell we don't use this dependency anymore (I could be missing something).

**Comment by tw15egan** [comment]
I mean I guess we can just remove both, do a `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install` and see if anything breaks with it removed?

**Comment by joshblack** [comment]
Just pulled down and tested and seemed fine so I just removed it lol. If there is an issue we can add it back 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Pull request merged**
