### PR TITLE
fix(TimePicker): set invalid outline on invalid focused text input

### LINKED ISSUE #6518: Time picker invalid state does not match component spec
The time picker invalid state does not match the component spec. The error text should be red, and when the input field is focused, the focus outline should not override the error state outline

originally reported by @laurenmrice 

Jul-22-2020 10-40-51

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6518

This PR correctly sets the invalid outline on the invalid time picker's text input to match the behavior throughout the system and sets the correct invalid text color on the error message

#### Testing / Reviewing

Confirm the invalid time picker matches the component spec

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
looks good to me in Firefox, Chrome and Safari 👍🏻. Thanks !

**Comment by tw15egan** [comment]
Like I brought up in the related issue to this, I think this could cause a11y concerns and think this functionality to be revisited. I don't think we should be removing any focus states, even if an item is invalid. If there were multiple invalid items next to each other, a keyboard user would have no way of knowing which input is focused. cc @dakahn

**Comment by dakahn** [comment]
Yeah, that design spec might need to get a revisit like you suggested @tw15egan 

Wayfinding and error states should be distinct.

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
This should be resolved with https://github.com/carbon-design-system/carbon/pull/6533

**Pull request closed without merging**
