### PR TITLE
feat(themes): add values for v11 tokens

### LINKED ISSUE #8832: Add layer tokens to theme
We decided on a hybrid strategy for tackling theming where we will add in a set of tokens that we're calling layer tokens. This issue is to add these tokens to our themes to then build out our contextual tokens in another issue.

### PR DESCRIPTION
**Pull request by joshblack**
Closes #8832

This PR adds in the set of tokens for v11. It also adds in a new preview, `preview-v11`, to interact with the token background groups and sets that we would like to include for this release.

#### Changelog

**New**

- Add token values for v11 in `next` to not conflict with any existing theme work
- Add new format to TokenFormat for formatting scss identifiers
- Add `preview-v11` for previewing v11 tokens in a new token explorer

**Changed**

**Removed**

#### Testing / Reviewing

- Verify all tests pass for themes (meaning that all tokens exist and are defined in each theme)
- Visit the deploy preview for elements
- Verify that the themes -> preview-v11 site renders correctly
- (For design) verify that tokens match the final token list in Notion

### CODE REVIEW

**Review by aagonzales — APPROVED** [review]
I didn't really check the values but the functionality works great! And the properties all look correctly assigned.

**Comment by joshblack** [comment]
@aagonzales would you have a sec (or 30min lol) to confirm the values? I think they have changed from when TJ/Josefina implemented this previously since we're adding in the layer sets for the first time.

**Comment by aagonzales** [comment]
STILL REVIEWING, JUST SAVING SO I DONT LOSE WORK.

**Elements:**
- [ ] `White-hover` should always `#E8E8E8` but its showing up as `#f2f2f2`

**White theme**
- [ ] `background-hover` should be `#E8E8E8` White-hover
- [ ] `layer-selected-hover-01` should be `#d1d1d1` Gray20-hover

Gray 10 theme:
- [ ] `layer-hover-01` should be `#e8e8e8` White-hover
- [ ] `layer-selected-hover-01` should be `#d1d1d1`Gray20-hover

Gray 90 theme: 
- [ ] `layer-selected-hover-01` should be `#63636` Gray70-hover

**Gray 100 theme**
- [ ] `layer-active-01` should be `Gray80`

**Review by jnm2377 — APPROVED** [review]
Awesome! lgtm! 🔥

**Review by tw15egan — APPROVED** [review]
LGTM pending changes based on Anna's feedback

**Comment by aagonzales** [comment]
@joshblack ok I'm done reviewing, there are quite a few changes. Good thing we reviewed it 😆

**Review by aagonzales — CHANGES_REQUESTED** [review]
Changes listed here: https://github.com/carbon-design-system/carbon/pull/8994#issuecomment-867170428

**Comment by joshblack** [comment]
Thanks so much @aagonzales! Just pushed up the changes for the colors that we have from the IDL. For the other changes, I think the `adjustLightness` stuff is giving us the wrong value 😞  Once we get:  https://github.com/carbon-design-system/carbon/pull/8942 merged then I can use those values and we should be good to go.

**Comment by joshblack** [comment]
@aagonzales updated to the hover colors, also updated any instance of `#f2f2f2` with `white-hover`

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
