### PR TITLE
fix(content-switcher): fix file name

### PR DESCRIPTION
**Pull request by asudoh**
Refs #604. Suspecting there was an issue with Mac "fancy dash".

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
👍

**Comment by RajkiranJogu** [comment]
Hi @asudoh ,  Could you please merge this fix.

**Comment by RajkiranJogu** [comment]
Hi @marijohannessen, Thanks for merging the fix. 
In which version this fix will be available?

**Comment by marijohannessen** [comment]
@RajkiranJogu https://github.com/carbon-design-system/carbon-components/releases/tag/v8.15.3 🙂

**Pull request merged**
