### PR TITLE
fix(ComposedModal): remove scroller class on unmount

### LINKED ISSUE #3945: Vertical scroll disappears after opening a Modal when updating to newer carbon-components version
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

After updating to newer version of carbon-components I started facing a weird symptom when opening a modal (from any component - it doesn't matter).
The vertical scroll of the browser is disabled after opening a modal, and when closing the modal it doesn't come back and I can't navigate in the screen up/down!!!

> Is this issue related to a specific component?
No

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?

Chrome / Firefox

> What version of the Carbon Design System are you using?

10.4.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

https://codesandbox.io/s/fragrant-morning-267l5

1.  From the menue of any Project component choose action that opens a modal
2.  Choose "Duplicate" for example
3.  The Modal window is opened
4.  The vertical scroll disappears!
5. Close the Modal window, the scroll is still gone

## Additional information

You can compare between package.json.old and the new package.json that I'm using

## Add labels

Please choose the appropriate label(s) from our existing label list to ensure
that your issue is properly categorized. This will help us to better understand
and address your issue.

### PR DESCRIPTION
**Pull request by asudoh**
Ports #4066.
Fixes #3945.

#### Changelog

**New**

- Code to remove scroller CSS class on ummounting `<ComposedModal>`.

#### Testing / Reviewing

Testing should make sure `<ComposedModal>` is not broken.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
it looks like `.bx--body--with-modal-open` isn't removed on the `Using child nodes` story on modal close, but it is for the other two stories. is that expected behavior?

**Review by joshblack — APPROVED** [review]

**Comment by abbeyhrt** [comment]
Similar to Andrew, `.bx--body--with-modal-open` doesn't seem to be removed when I close `Using child nodes` but it also wasn't removed on `Using header / footer props`.  It works in `Example usage with trigger button` though.

**Review by joshblack — DISMISSED** [review]
Ah just saw what you two were talking about above. Would it make sense for this class to be applied on state update (open/close) versus its mount lifecycle?

**Comment by abbeyhrt** [comment]
@joshblack with the class being applied and removed in the mount lifecycle, when should we expect the class to be removed? I kinda assumed that unmounting was equivalent to when the modal closes.

**Comment by asudoh** [comment]
Good catch @abbeyhrt @emyarod - Fixed.

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! 🎉

**Comment by asudoh** [comment]
Updated review status given I see all review comments have been addressed - Please speak up otherwise. Thanks!

**Pull request merged**
