### PR TITLE
feat(pictograms): add pictogram batch for February 2021

### PR DESCRIPTION
**Pull request by dudley-ibm**
Closes #

{{Closes multiple enterprise pictogram issues including #s 55, 61, 63, 67, 77, 78, 79, 82, 86, 88 & 89 }}

#### Changelog

**New**

- {{New additions and their (category)
- Issue #55
bluepages.svg	(Networking)
mail--verse.svg	(Networking)
professional--marketplace.svg	(Networking)
sales--connect.svg	(Networking)
workday.svg	(Networking)

Issue #61
tablet--device.svg	(Device interaction)
tablet--device--check.svg	(Device interaction)

Issue #63
art--tools--01.svg	(Design and development)
content--design.svg	(Design and development)
design--leadership.svg	(Design and development)
design--research.svg	(Design and development)
organization.svg	(Design and development)
user--experience-design.svg	(Design and development)
visual--design.svg	(Design and development)

Issue #67
sprout.svg	(Industry)

Issue #77
microphone.svg	(Electronics)

Issue #82
overview.svg	(Design and development)

Issue #86
rotate--device.svg	(Device interaction)

Issue #88
eyewash--station.svg	(Healthcare)

Issue #89
do-not--02.svg	(Action)
no--smoking.svg	(Building structure)
stairs.svg	(Building structure)
stairs--up.svg	(Building structure)
stairs--down.svg	(Building structure)
emergency--exit.svg	(Building structure)

}}

**Changed**

- {{Changed following three pictograms with replacement art:
- Issue #78
dialogue.svg	(Watson - REPLACEMENT ART)

Issue #79
faucet.svg	(Home - REPLACEMENT ART)
shower.svg	(Home - REPLACEMENT ART)}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ All should appear on carbon and on Design Language @vpicone  }}

### CODE REVIEW

**Comment by dudley-ibm** [comment]
Forgot to include that I made the following changes to the `pictograms.yml` file:

- Changed friendly name `birthday--cake` to `Birthday cake`
- Changed friendly name `IBM Z and LinuxOne multi-frame` to `IBM Z® and LinuxOne multi-frame`
- Chagned friendly name `IBM Z and LinuxOne single frame` to `IBM Z® LinuxOne single frame`

**Review by emyarod — APPROVED** [review]
fixed an incorrectly named asset in `categories.yml` and updated snapshots, looks good to me

**Comment by joshblack** [comment]
@dudley-ibm does this PR cover https://github.com/carbon-design-system/carbon/issues/5327 or is that going to be in a separate update?

**Review by joshblack — APPROVED** [review]

**Comment by dudley-ibm** [comment]
> @dudley-ibm does this PR cover #5327 or is that going to be in a separate update?

@joshblack it was supposed to! I'll process another PR real quick for that oversight.

**Pull request merged**
