### PR TITLE
fix(ContentSwitcher): resolve text contrast violations

### LINKED ISSUE #6745: Content switcher fails WCAG 1.4.11 Non-text Contrast
## Content switcher fails to provide sufficient contrast for information required to identify the user interface component

[1.4.11 Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) requires that a minimum 3:1 contrast exists for "visual information required to identify user interface components"

The Content switcher is a complex UI component, made up of at least two tabs that "allow users to toggle between two or more content sections within the same space on screen."

As described on the [usage page](https://carbondesignsystem.com/components/content-switcher/usage), the component consists of a selected tab (1)  and one or more selectable tabs (2), each with a text label.

2-tab content switcher. 'All' is selected with black background. 'Read' has a light grey background

### Automated testing tool and ruleset
N/A There are no automated test tools that detect failures of 1.4.11

### Assistive technology used to verify
Colour contrast analyzer (or any similar tool) can be used to measure the contrast of the  visual elements

## Detailed description
The contrast failure takes place because the light grey outline of the unselected tab does not achieve a 3:1 contrast against the background. In the version shown on the usage page, the contrast is only 1.1:1

Lacking any visual 'binding' between the selected and unselected tabs, the switcher can easily be mis-identified as a black button. This is especially the case given the 'button' is always present. The problem is especially pronounced in a 2-tab implementation. 

In a real-world implementation, the confusion can be shown in the following image from a prototype.
screen detail of IBM accessibility checker with 2-tab content switcher

The lower resolution of a conference call this morning rendered the "document" tab as simply a piece of text, resulting in perception of the All tab as a separate black button. Chris Connors asked me to open an issue, based on that discussion.

To understand why some kind of outline around the unselected tab must meet 3:1 contrast, it is helpful to strip the background entirely. This is a recommended test to identify whether any particular  visual detail of a UI component is "required to identify" the component.

variations on content switcher style in 2 columns, the first showing a 2-tab switcher, the second showing a 3-tab switcher

The default Carbon component is shown at the top of each row of the above image.

Version 1, in each column, strips out all the light grey background (which fails to meet 3:1) on the unselected tabs.

I hope it is clear to anyone viewing versions 1, that the content switcher is not obvious as a component when it is lacking any visual treatment on the unselected tabs.This is especially confusing in a 2-tab implementation.

Version 2 shows the same treatment with the addition of a 1px stroke around the unselected tabs. The component immediately becomes clear as a single component. There are other ways to achieve this minimum contrast, but this seems like the most obvious (especially for demo purposes).

Version 3 shows the same stroke treatment, with all other low contrast info removed. The unified component is still clearly decipherable.

Another piece of visual information which fails 3:1 is the divider between the 2 unselected tabs in the second column. Based on version 3, it is difficult to argue that this divider is required to understand the component or its states. The spacing of the text labels alone provides visual affordance between the 2 unselected tabs.

That said, versions 4 and 5 show there is some benefit to bumping up the contrast of the divider as well. 
Version 4 bumps up the contrast of the divider to 3:1.
Version 5, like version 3, shows this clearer divider with the low contrast info removed.

As stated, a case can be made that neither treatment 4 or 5 is required to meet 1.4.11 for this component; however, a better-contrasted divider may be more understandable by some users, and I would recommend doing some user testing with  this enhanced divider, especially in an implemented page where other content adds 'noise' to the experience..

### Non-text contrast assessments of other Carbon components
I recommend a similar assessment of other Carbon components be carried out (using the procedure of stripping out low-contrast visual features) to determine which visual elements need increased contrast in order for each component  to pass 1.4.11 Non-text contrast.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6745

This PR updates the content switcher styles to match the updated spec which passes new text contrast requirements. 

cc @aagonzales should we deprecate the light variant of this component and make it identical to the base style?

### CODE REVIEW

**Comment by aagonzales** [comment]
> should we deprecate the light variant of this component and make it identical to the base style

Yes, the light variant won't be needed anymore.

**Comment by aagonzales** [comment]
Also just talked to Jeannie and we want to change the small divider between the tabs to `$ui-03` instead. Since I don't think that one needs to pass 3:1 (the space between them should be enough on its own). 

image

**Review by joshblack — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
🎉 Looks great!

**Comment by aagonzales** [comment]
We should make sure we call out this change with the next release notes so people are aware since its a larger visual change.

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
