### PR TITLE
chore(tag) - clean up styles with inheritance

### PR DESCRIPTION
**Pull request by DusanMilko**
Updated svg in tag to use currentColor, this allows us to remove unnecessary css and simplifies the code (The power of inheritance, yay!)

#### Changelog

**Removed**

- removed unnecessary css in favor of inheritance

### CODE REVIEW

**Comment by asudoh** [comment]
Visual review note: Need to ensure the tag with different color options are not broken.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thaks @DusanMilko!

**Comment by asudoh** [comment]
CC @tw15egan

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by designertyler — APPROVED** [review]
LGTM

**Pull request merged**
