### PR TITLE
feat(number-input): update number input controls to new spec

### LINKED ISSUE #5417: [Number input] control update
**Original prompt:**
Explore other control options besides the up/down carets.
image

-------------------

**Final decision:**
https://github.com/carbon-design-system/carbon/issues/5417#issuecomment-598831165

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5417

unblocks #7570

This PR updates the number input step controls and invalid/warning states to match the updated component spec. This PR is only focused on the input controls and the remaining ticket issues will be addressed in separate PRs related to #7570

#### Testing / Reviewing

Confirm all size variants and warning states for the number input match the new spec

### CODE REVIEW

**Comment by tw15egan** [comment]
More of a design question, but should we set `.bx--number` to `width: 100%;` to conform with the changes we've made to `Select` and `Dropdown` and the existing `TextInput`? Or let the end-user determine how large it should be? 

Currently, it is getting cut off after 3 digits when it exceeds the max
Screen Shot 2021-01-28 at 12 40 58 PM

Edit: 

Actually, nevermind. It seems like it adjusts the width based on the `max` value of the `NumberInput`. If I set it to 
Screen Shot 2021-01-28 at 12 45 58 PM

I get

Screen Shot 2021-01-28 at 12 46 07 PM

So I think this actually is working great. Disregard! 👍

**Comment by emyarod** [comment]
yeah this is caused by an arbitrary max-width we placed on the number inputs

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by joshblack — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Disabled state**
- [x] The - and + icons should not get the bottom rule.
Screen Shot 2021-02-01 at 11 36 11 AM

**Light variant**
- [x] There are small strips of color around the - and + icons that should not be showing up in the input.
Screen Shot 2021-02-01 at 11 52 03 AM

**Invalid state**
- [x] The - and + icons seem to shift down a pixel when the invalid state is applied. This happens with all sizes.
Feb-01-2021 11-37-24


Is it possible to hide the divider rule between the warning state/invalid state icon when hovering on the - icon?
Screen Shot 2021-02-01 at 11 50 23 AM

**Review by dakahn — APPROVED** [review]

**Comment by emyarod** [comment]
the icons shifting seems to be a Firefox only issue but it should be resolved now

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Hover:**
- [x] The hover colors on the - and + need to be `hover-light-ui` for the light prop.

**Divider rules:**
- [x] The divider rules needs to be `decorative-01` in the light prop.
- [x] The divider rules needs to be `disabled-02` for the disabled state. Looks a little lighter right now in all themes.

**Invalid state:**
- [x] When hovering over the - and +, there are little dot glitches at the bottom of the input.
- [x] When hovering over the +, the divider rule between the - and the error/warning icon should not go away.

Feb-03-2021 15-21-17

**Comment by emyarod** [comment]
when should the dividers be hidden/not hidden?

**Comment by laurenmrice** [comment]
@emyarod 

Artboard

**Comment by emyarod** [comment]
got it, the divider rule styles should be updated now

**Review by laurenmrice — CHANGES_REQUESTED** [review]
There are still some issue with the divider rules:

- [x] **Enabled state**: the divider rule needs to be present between the - and +. Right now it is not there. Should be:
enabled


- [x] **Disabled state:** the divider rule isn’t showing up in the disabled state. Needs to be disabled-02. Should be:
disabled


- [x] **Invalid/Warning states:** need to have two divider rules by default to separate out the icons. Needs to also follow the hovering logic mentioned in my last comment. Should be:
invalid

**Comment by emyarod** [comment]
@laurenmrice all of those points have already been in the story so I'm a bit confused. were you seeing an outdated or cached version of the story maybe?

**Review by laurenmrice — CHANGES_REQUESTED** [review]
**Light prop**
-When the light prop is applied, the focus states on the -/+ buttons are not squares and get cutoff. This happens in Firefox/Chrome/Safari.
light prop

**Safari bug**
-When the full input has focus, hovering over the -/+ buttons causes little blue dots at the bottom of the input. Same goes for the invalid state, red dots appear at the bottom of the input on hover.
dots

**Review by laurenmrice — APPROVED** [review]
Looks great! Thanks for updating this component! 🎉

**Pull request merged**
