### PR TITLE
fix(a11y): fixing Selectable Tile HCM accessibility

### LINKED ISSUE #6895: Selectable Tile is not accessible in Windows High Contrast Mode
## Environment

> Operating system

Windows 10 latest

> Browser

Edge, Firefox

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

The focus state and icons indicating a selection

Firefox 
image

Edge
image

### PR DESCRIPTION
**Pull request by rjhenriquez**
Closes #6895

Fixing Selectable Tile focus state and icons indicating a selection in Hight Contrast Mode

#### Changelog

**Changed**

Selectable Tile component

#### Testing / Reviewing

On a Windows 10 machine, go to `settings --> ease of access --> high contrast` and flick the switch. Compare the storybook in Edge (Should be in High Contrast) to Chrome (Should look normal). 
For **Firefox**, you'll need to open it up and type `about:config` into the address bar. Then, search for `layout.css.prefers-contrast` and set it to `true`.

- Visit [Tile Multiselect](http://192.168.1.158:9000/?path=/story/tile--multi-select) component
- Verify that the icon shows when selecting a tile
- Verify the focus state works on the tile

### CODE REVIEW

**Comment by tw15egan** [comment]
Looks good! 

Can we also fix the `ExpandableTile`  chevron? Doesn't look like it is appearing

image

**Comment by rjhenriquez** [comment]
@tw15egan Fixed :)

**Review by tw15egan — APPROVED** [review]
Nice! 👍 ✅

**Comment by andreancardona** [comment]
FF looks good ✅ 
Chrome looks good ✅ 
 @rjhenriquez I'm seeing some weird behavior when selecting the tile on Windows 10 - Edge
Screen Shot 2020-10-01 at 12 48 48 PM
Screen Shot 2020-10-01 at 12 48 57 PM

**Review by andreancardona — CHANGES_REQUESTED** [review]
see screenshots above

**Comment by tw15egan** [comment]
@andreancardona this is what I'm getting on my Win10 machine running Edge. Wondering if this is a parallels issue? cc @dakahn since I know he's running Windows 

image

**Comment by andreancardona** [comment]
> what I'm getting on my Win10 machine runn
ahh it very well could be! I'll wait for a response from @dakahn

**Review by dakahn — APPROVED** [review]
image
Looks good to me on latest edge, window 10

**Review by andreancardona — APPROVED** [review]
:)

**Pull request merged**
