### PR TITLE
chore(readme): Add reference to Angular and Vue

### PR DESCRIPTION
**Pull request by youda97**

### CODE REVIEW

**Comment by joshblack** [comment]
Hi @youda97! We don't include the Angular and Vue projects because the core team doesn't support them. I think we can definitely link out to them, but probably shouldn't put them in the table since they aren't present in the monorepo 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @youda97!

**Review by emyarod — CHANGES_REQUESTED** [review]
looks good, just need to remove the changes to the table of packages

**Comment by joshblack** [comment]
cc @connor-leech what do you think of the copy? Any changes you would make?

**Review by connor-leech — CHANGES_REQUESTED** [review]
As far as I can tell, we're still referencing carbon-components. If users are just getting started, they should reference source of truth. To the best of my knowledge, the [monorepo](https://github.com/carbon-design-system/carbon) (Vanilla and React) are that source of truth. Is this correct? @joshblack If so, we shuold reference these instead of carbon-components.

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Pull request merged**
