### PR TITLE
chore(data-table): update overflow menu storybook

### LINKED ISSUE #10747: [Bug]: DataTable overflowMenuOnHover is broken
### Package

@carbon/react

### Browser

Chrome, Safari, Firefox, Edge

### Package version

v0.13.0

### React version

v17.0.2

### Description

###Expected

`DataTable` sets `overflowMenuOnHover` to true by default. This should hide `OverflowMenu`s in `DataTableRow`s. 

### Actual
`OverflowMenu`s are never hidden.

### Reason
Documentation is rather poor on this behaviour, but digging through the commit history turned up [this commit](https://github.com/carbon-design-system/carbon/commit/6795904e0875165dcfb4be11e252b107b807163f). Even when `.cds--table-column-menu` is set on the correct `TableCell`, the `OverflowMenu` within it never disappears, because the SVG inside the Button that triggers the Menu is lacking the `.cds--overflow-menu__icon` class.

### CodeSandbox example

https://carbon-react-next.netlify.app/?path=/story/components-datatable-toolbar--with-overflow-menu

### Steps to reproduce

Go to https://carbon-react-next.netlify.app/?path=/story/components-datatable-toolbar--with-overflow-menu and note that the overflow menu is always visible, not just on hover.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by aledavila**
Closes #10747

Overflow menu wasn't hiding.

#### Changelog

**Changed**

- fixed classname in stories

#### Testing / Reviewing

Check data table overflow menu

### CODE REVIEW

**Comment by aledavila** [comment]
@jnm2377 & @tay1orjones I wanted your take on this if possible. So the issue as it stands is that the overflow menu wasn't hiding when `overflowMenuOnHover` is true. There are 2 places where that exists I'm not even sure if the prop in Table works. The other is in DataTable component I think that is the one that works. (we can look into that another time)

So to my issue as you see in my change it wasn't working because the prefix was incorrect. In order for this prop to work the user needs to pass in `className="cds--table-column-menu"` to the `TableCell` containing the overflow menu. We don't exactly surface this or tell people they need to pass it in unless theres other ideas on how to integrate it into our code(the css might be too intertwined to do that). Do you guys have any ideas on the best way to do that ? So its not exactly a bug just a lack of documentation.

**Comment by tay1orjones** [comment]
@aledavila Based on https://github.com/carbon-design-system/carbon/pull/5822 and https://github.com/carbon-design-system/carbon/issues/5804, `DataTable` should be passing `overflowMenuOnHover` down to `Table`. `Table` is the only spot where the `cds--data-table--visible-overflow-menu` class is toggled on/off. 

If `overflowMenuOnHover` requires placing `cds--table-column-menu` on a `TableCell` (and rendering an actual OverflowMenu), I agree we need to at the very least document it. A blurb in storybook docs could be enough.

On the bigger picture of how to integrate this more into our code, I wonder if the `TableCell` should have a `containsOverflowMenu` prop that toggles the `cds--table-column-menu` class so we avoid this problem in the future?

**Comment by jnm2377** [comment]
@aledavila @tay1orjones I'm wondering if there is a different selector that can be used to toggle on/off the overflow menu so that users don't have to forcibly add `cds--table-column-menu` (since I'm assuming that classname is part of the selector that hides the overflow menu)?

**Comment by aledavila** [comment]
@jnm2377 yes the way the styles were written it expects it to have that. And I thought about removing it but then other styles use that class

**Comment by jnm2377** [comment]
I don't mean necessarily removing it from the stylesheet, but adding a selector that will support the use case of a column w/o that class so that it'll still work if a user doesn't add that class.

**Comment by tay1orjones** [comment]
Would it work if the selectors using `.#{$prefix}--table-column-menu` were reconfigured to instead apply the styles if a table cell has an overflow menu as a descendant/child?

 Something maybe like `td:has(> .#{$prefix}--overflow-menu)`

**Comment by tay1orjones** [comment]
Bah, nope, that's a [level 4 selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:has) not available in browsers yet. Bummer.

We might not be able to get out of having to apply the class to the table cell.

**Review by jnm2377 — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
