### PR TITLE
fix(date-picker): fix JavaScript error for mobile

### PR DESCRIPTION
**Pull request by asudoh**
Refs IBM/carbon-components-react#968.

#### Changelog

**New**

- Code to guard for NPE from missing `calendarContainer` property in Flatpickr instance. Such property won't be there in Flatpickr's mobile mode.

#### Testing / Reviewing

Testing should make sure date picker is not broken.

### CODE REVIEW

**Review by jnm2377 — COMMENTED** [review]
👍 Date picker is working for me, but it is jumping back to the bottom again when I click on the end range date. I thought that was fixed?

**Review by marijohannessen — APPROVED** [review]
It seems to be working fine for me - I'm not getting the same error as @jnm2377 but maybe I'm not testing it properly?

**Comment by asudoh** [comment]
Thanks @jnm2377 and @marijohannessen for reviewing! I think the "jumping to bottom" issue was because this PR was originally based on old `master` (without the fix to the "jumping to bottom" issue).

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
