### PR TITLE
chore(sass): add spacing variables for dynamic generation of classes

### PR DESCRIPTION
**Pull request by tomratcliffe**
Adds a variable ($carbon-spacing) that includes all of the Carbon spacing
information so developers can iterate through these and generate classes for all
spacing and layout options. For example:

```scss
@each $spacing-type, $spacing-details in $carbon-spacing {
    @each $size-name, $size in $spacing-details {
        .myapp-padding-top-#{$spacing-type}--#{$size-name} {
            padding-top: $size;
        }
    }
}
```

#### Changelog

**New**

- Variable `$carbon-spacing`

**Changed**

None

**Removed**

None

#### Testing / Reviewing

Try running the example shown above, as a demo of how we could now iterate through the Carbon spacings. I welcome any suggestions for naming this slightly different! Not sure on the spacing vs. layout names that I chose.

I prefixed with `carbon` but noticed that this isn't done anywhere else - not sure of your approach for this.

### CODE REVIEW

**Comment by asudoh** [comment]
Hi 👋 thank you for trying to address this problem space - Given spacing is now getting managed by [`carbon-elements`](https://github.com/IBM/carbon-elements) repo, would you try making a change there?

**Comment by joshblack** [comment]
Hi @tomratcliffe! 👋 Thanks so much for taking this on! Mind making a corresponding change over in: https://github.com/IBM/carbon-elements/blob/master/packages/layout/scss/_spacing.scss ?

Ideally it would be:

```scss
$carbon--spacing: (
  $spacing-01,
  $spacing-02,
  // ...
);

$carbon--layout-spacing: (
  $layout-01,
  $layout-02,
  // ...
);
```

This will match the corresponding JavaScript variant 👍

**Comment by joshblack** [comment]
Hi @tomratcliffe! 👋 Going to close this for now due to inactivity, feel free to comment if you would like to move forward with this! Appreciate your time here 🙏

**Comment by tomratcliffe** [comment]
Hey @joshblack, apologies for not replying on here - I'll follow up on this on the other repo, thanks for pointing me in the right direction! :+1:

**Pull request closed without merging**
