### PR TITLE
fix(NumberInput): deprecate mobile variant

### LINKED ISSUE #5231: [NumberInput] Mobile variant width sizing issue
Visual issue with mobile variant knob on number input

## What package(s) are you using?
- [X] `carbon-components-react`

## Detailed description
The number input mobile variant knob, when used in a form, does not size/justify well with other components (text, dropdown, ext) and causes a visual "rag"
See screen shots:
Screen Shot 2020-01-31 at 9 17 47 AM
Screen Shot 2020-01-31 at 9 18 09 AM

> Is this issue related to a specific component?
NumberInput, Mobile Variant Knob
https://react.carbondesignsystem.com/?path=/story/numberinput--default

> What did you expect to happen? What happened instead? What would you like to
> see changed?
Component should be the same width as others when placed within a container

> What browser are you working in?
Chrome, FF
> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Maximo, March first D-cut of Application Suite

### LINKED ISSUE #5421: fix(component): adjustments to Number Input
Adjustments to Number input component to improve the spacing and size of the up/down arrows and ensure they are not using the soon to be deprecated glyphs.

number input

### LINKED ISSUE #7570: [number input] audit bugs
- [ ] We need to change the caret controls to a plus and a minus. Here is the final design spec [5417](https://github.com/carbon-design-system/carbon/issues/5417#)

- [ ] There needs to be a 12px space between the control icons and the end of the field container.
md-672px-8 column

- [ ] In Safari, the input text is the wrong color for the disabled state in the dark themes. Should be `disabled-02`.
Screen Shot 2021-01-14 at 11 32 18 AM

- [ ] The mobile variant will be the same as the enabled state for the regular number input.
md-672px-8 column copy

### PR DESCRIPTION
**Pull request by emyarod**
Closes #7570
Closes #5231
Closes #5421

This PR deprecates the mobile number input now that the number input component styles are consistent across variants

### CODE REVIEW

**Comment by tw15egan** [comment]
@emyarod should we leave the styles with a TODO: REMOVE comment until v11? Unsure if this will break anyone unintentionally

**Comment by emyarod** [comment]
@tw15egan given that the current mobile styles are currently broken, I have left the class names but removed the styles so they can still be targeted but there won't be underlying mobile specific styles to wrestle with

**Comment by tw15egan** [comment]
If they're currently broken then yeah let's nuke em 👍🏻

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
