### PR TITLE
fix(actionable-notification): provide a name for alertdialog role

### PR DESCRIPTION
**Pull request by tay1orjones**
[Surfaced in slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1663108123574489), the `alertdialog` is not given an associated name.

image

#### Changelog

**New**

- associate `title` as the name when given one

#### Testing / Reviewing

- There should be no errors when running accessibility-checker on the actionable notification stories

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
Not seeing any a11y violations 👍🏻

**Review by aledavila — APPROVED** [review]

**Comment by shunguoy** [comment]
hi, @tay1orjones   do you have a page that shows the issue?  for example, a carbon storybook link or some page that I can access. thanks.

**Comment by tay1orjones** [comment]
@shunguoy For the issue fixed in this pull request? The current storybook link for this component is here https://react.carbondesignsystem.com/?path=/story/components-notifications-actionable--default

**Comment by shunguoy** [comment]
Thanks & sorry, @tay1orjones  I am looking at [this issue](https://github.com/IBMa/equal-access/issues/1299).  I tried to find the page that actually has the issue to understand what needs to be fixed.  Could you please help?

**Comment by tay1orjones** [comment]
@shunguoy are you able to access the slack links in that issue? It links to a conversation where code was posted showing the issue. It's anytime a Modal is rendered via createPortal, I believe?

**Comment by shunguoy** [comment]
thanks, @tay1orjones   I will try to duplicate with the code in the slack.

**Pull request merged**
