### PR TITLE
test: increase coverage for ControlledPasswordInput

### PR DESCRIPTION
**Pull request by emil-ep**
Increases test coverage for ControlledPasswordInput #17476

### CODE REVIEW

**Review by annawen1 — CHANGES_REQUESTED** [review]
Thanks @emil-ep! There is a `__tests__` folder within `TextInput`, can this test file be placed there?

**Comment by emil-ep** [comment]
> Thanks @emil-ep! There is a `__tests__` folder within `TextInput`, can this test file be placed there?

@annawen1  Moved the test file to `__tests__ ` directory

**Review by annawen1 — APPROVED** [review]

**Comment by emil-ep** [comment]
@tay1orjones Can you please take a look at this PR ?

**Review by 2nikhiltom — APPROVED** [review]
LGTM

**Comment by emil-ep** [comment]
There is 1 more review required on the `percy/Carbon-Monorepo` check.  @annawen1  @2nikhiltom  Can you please help on that ?

**Pull request merged**
