### PR TITLE
fix(checkbox): move padding to label instead of checkbox

### LINKED ISSUE #5461: Checkbox with hidden label is not square
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`
- [x] `carbon-components-vue`

## Detailed description

> Describe in detail the issue you're having.
When hiding the label of the Checkbox component the component does not become square making it harder to align it horizontally.

> Is this issue related to a specific component?

Checkbox

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Checkbox should be square with the visual elements centred.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.9

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

Carbon-Components-Vue adding the hideLabel feature when shape of Checkbox was noticed https://github.com/carbon-design-system/carbon-components-vue/issues/835

## Steps to reproduce the issue

1. Go here https://react.carbondesignsystem.com/?path=/story/checkbox--checked
2. Hide the checkbox

E.g. https://codesandbox.io/s/peaceful-dawn-k9dpj

## Additional information

image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5461

Removes padding on the checkbox, and places it on the label so it only appears if the label is present. 

#### Changelog

**Changed**

- Moved `padding-left` from `checkbox-label` to `checkbox-label-text`

#### Testing / Reviewing

Ensure Checkbox still looks the same visually, and that nothing moves when `hideLabel` knob is checked.

### CODE REVIEW

**Comment by lee-chase** [comment]
How about this instead @tw15egan so that space is still reserved

How about this instead

.bx--checkbox-label {
  padding-left: 1.25rem;
}

.bx--checkbox-label-text {
  padding-left: 0.4rem;
}

I have updated https://codesandbox.io/s/peaceful-dawn-k9dpj with .fixed-it class

**Review by joshblack — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
will you be splitting the padding between the label and label text?

**Comment by tw15egan** [comment]
@emyarod Yes, just updated 👍

**Review by lee-chase — APPROVED** [review]
Looks good to me

**Pull request merged**
