### PR TITLE
feat(FileUploader): add onDelete hook to standard uploader

### LINKED ISSUE #5851: FileUploader should provide an onDelete hook for deleting files
Currently the FileUploader does not provide an onDelete method for performing actions when an uploaded file is deleted. Users must hook into onClick and catch the cases where the target is the deleted file. Not only is this not very efficient since onClick is triggered for other events, it's also unintuitive with no documentation that this is how you should handle this functionality. Providing an onDelete hook would take care of these issues.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5851

Currently the click handler is attached to the entire component so it fires on click of any element in the file uploader container. This PR adds a separate `onDelete` hook for when the click target is the 'x' icon of an uploaded file. The current click behavior remains the same for backwards compatibility, but will probably need to be changed in the future.

~~This change may be a breaking change for current users who are hacking around the current `onClick` behavior to perform actions when a file is removed. I guess we can check if `props.onClick` exists and `props.onDelete` doesn't exist to fire `onClick` method in `handleClick` for full backwards compatibility?~~ The current `onClick` behavior is left intact

#### Testing / Reviewing

confirm the actions log in storybook is correct when interacting with the standard file uploader

### CODE REVIEW

**Comment by tw15egan** [comment]
Is it expected that it fires the onClick twice? 

onClick

**Comment by emyarod** [comment]
I believe that's what the current component does as well

**Comment by tw15egan** [comment]
@emyarod yeah just noticed that as well. In regards to the backward compatibility, might the good to do what you suggested as well as maybe a comment explaining it so we remember to remove it in v11.

**Review by joshblack — COMMENTED** [review]
Seems great 🎉 could we add a test for the new API in `FileUploader-test` just to help catch any regressions? 👀

**Comment by emyarod** [comment]
this should already be in our Filename tests (`should support events on interactive icons when 'edit' or 'complete' is the status`)

**Review by tw15egan — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by asudoh** [comment]
@emyarod thinks this is ready to merge - Thanks @emyarod!

**Pull request merged**
