### PR TITLE
feat(layout): update breakpoint-down to use sm breakpoint query

### LINKED ISSUE #4020: Carbon layout media query mixins Incorrect
The carbon layout mixin carbon--breakpoint-down incorrectly handles small breakpoints.

## What package(s) are you using?

- [x] `carbon-components`
- [x] `@carbon/layout`

## Detailed description

> Describe in detail the issue you're having.

Setting styles to work below the smallest size does not work.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

To be able to set styles only applied at the smallest size.

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
10.6.1

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

See https://codesandbox.io/s/carbon-breakpoint-mixin-issue-q8vgx

Define styles starting with the largest and working down
e.g. 
```css
.a-box {
  &::after {
    font-size: 24px;
    content: "I am default sized content";
  }

  @include carbon--breakpoint-down("max") {
    &::after {
      content: 'I am content for "max" sized screens';
    }
  }

  @include carbon--breakpoint-down("md") {
    &::after {
      content: 'I am content for "md" sized screens';
    }
  }

  @include carbon--breakpoint-down("sm") {
    &::after {
      color: red;
      content: 'I am content for "sm" sized screens';
    }
  }
}
```

The last style should only be applied below "sm" sizes but is applied in all the time.

### PR DESCRIPTION
**Pull request by joshblack**
Closes #4020

Update `breakpoint-down` mixin to use `sm` breakpoint in a media query instead of just outputting its content. This makes more logical sense because `breakpoint-down` specifies the max-width that the media query is applied to and so defaulting `sm` to not be wrapped in a media query leads to unexpected outcomes with this mixin.

#### Changelog

**New**

**Changed**

- `breakpoint-down` now wraps `sm` breakpoints in a media query 

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
FYI @jendowns curious if you have any thoughts on this 🤔

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
