### PR TITLE
fix(button): carbonX ghost button needs to be interactive-04

### PR DESCRIPTION
**Pull request by jendowns**
PR #1930 made the Carbon X ghost button text & icon colors `$interactive-01` (blue60) for ALL themes. 

However, ghost button text and icon color should be ~blue40~ blue50(?) to be accessible in dark themes, per my closed issues #1692 and https://github.com/IBM/carbon-elements/issues/302

~PR #1930 undid my changes in PR #1694 to fix the text colors in ghost buttons by making them `$interactive-03` (a color that satisfies both light and dark theme requirements in `@carbon-themes`: https://carbon-elements.netlify.com/themes/examples/preview/)~

EDIT: My apologies, looks like I misread the themes preview. `$interactive-04` is now blue50 and should be used instead of `$interactive-01` (or previously, `$interactive-03`?) I updated my PR to reflect the token update 👍 

#### Changelog

**Changed**

- change ghost button theme

### CODE REVIEW

**Comment by jendowns** [comment]
**Is there any way that "verify in all themes" become a requirement for future changes to Carbon X components?** We primarily use the g100 dark theme, so a regression issue like this affects us directly. 🙏

**Comment by jendowns** [comment]
One additional note about ghost buttons in dark themed UIs...

~While blue50 on gray100 is accessible, blue50 isn't accessible on the hover background color gray80 (neither was blue40, for the record 😅 )~

OH! please disregard this comment -- was comparing blue50 on gray80, not blue50 on #353535 😇

**Review by emyarod — APPROVED** [review]
so it seems even after #1694 we did not update our button tokens to account for dark themes, as the sheet I was working off of defined the button text and button icon color as `$interactive-01`. my fault on undoing the change, and I will defer to the designers here to confirm this token change. otherwise, looks good to me after merge conflict is resolved

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
Looks good once @IBM/carbon-designers sign off

**Review by aagonzales — APPROVED** [review]
LGTM!! 👏

**Pull request merged**
