### PR TITLE
fix(FileUploaderDropContainer): fix a11y violations, update tests

### LINKED ISSUE #12498: [a11y]: FileUploaderDropContainer component has critical violation "The tabbable element's role 'none' is not a widget role"
### Package

carbon-components-react

### Browser

Chrome

### Operating System

MacOS

### Package version

7.56.0

### React version

17.0.2

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker - Latest Deployment

### Assistive technology

_No response_

### Description

The `FileUploaderDropContainer` component has a critical a11y violation `"The tabbable element's role 'none' is not a widget role"` that was found in our product using the IBM Accessibility Checker tool and is re-producible on the [v10]( https://v7-react.carbondesignsystem.com/?path=/story/components-fileuploader--drag-and-drop-upload-container-example-application) and [v11](https://react.carbondesignsystem.com/?path=/story/components-fileuploader--drag-and-drop-upload-container-example-application) storybook as well.

v10 storybook
FileUploader-v10

v11 storybook
FileUploader-v11

### WCAG 2.1 Violation

_No response_

### Reproduction/example

Carbon v10 storybook - https://v7-react.carbondesignsystem.com/?path=/story/components-fileuploader--drag-and-drop-upload-container-example-application and/or Carbon v11 storybook - https://react.carbondesignsystem.com/?path=/story/components-fileuploader--drag-and-drop-upload-container-example-application

### Steps to reproduce

On the storybook link (either v10 or v11) for the FileUploader -> FileUploaderDropContainer story, run the IBM Accessibility Checker scan. The scan should report the critical violation mentioned above (scroll to the bottom of the violations list).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/12498
Refs https://github.com/carbon-design-system/carbon/issues/13039
Refs https://github.com/carbon-design-system/carbon/issues/12725
Refs https://github.com/carbon-design-system/carbon/pull/13061

Refactors `FileUploaderDropContainer` to mimic the changes made in #13061. This creates a `button` element that handles all click/key down behaviors.

I've also added in the `name` prop to `Filename` for better screenreader support. Before, when tabbing to the delete icon, it would just say `delete file` without any indication of the file. 

#### Changelog

**New**

- Refactor `FileUploaderDropContainer` to use a `button`
- `onClick` added to `FileUploaderDropContainer` as well as `composeEventHandlers` to support existing usage of `onClick` by our users

**Changed**

- Updated tests to anticipate new `filename` `aria-label` structure
- Added a `button-reset` to the scss file, and combined the label + "button" classes in the react file

**Removed**

- deprecates `role`, `tabIndex` from `FileUploaderDropContainer` since it now uses a `button` and these are not needed

#### Testing / Reviewing

- Ensure there are no visual regressions
- Ensure all click / keyboard functionality remains the same
- Ensure there are no a11y violations when there are no items uploaded
- Ensure there are no a11y violations when there **are** items uploaded
- Ensure screenreader support is as expected, especially when files have been updated and you are trying to delete them

### CODE REVIEW

**Review by francinelucca — CHANGES_REQUESTED** [review]
I'm experiencing a weird behavior when trying to select a file to upload. The file selector reopens after I select a file:

https://user-images.githubusercontent.com/40550942/224762492-1aadb6d7-2260-4499-9535-57fc520701a7.mov

**Review by francinelucca — CHANGES_REQUESTED** [review]
Previous issue is now solved but now when deleting an uploaded file via keyboard (enter), the file uploader reopens. I don't see that behavior in prod

**Comment by tw15egan** [comment]
@francinelucca alright that one should be taken care of now, let me know if you can find any more bugs 🐞 ☠️

**Review by francinelucca — APPROVED** [review]
LGTM!

**Review by alisonjoseph — APPROVED** [review]
Everything seems to be working as expected from what I can tell

**Pull request merged**
