### PR TITLE
fix(datatable): add padding so search clear button doesn't obstruct text

### LINKED ISSUE #5142: DataTable ToolbarSearch: long input texts overlap with the 'x' btn.
in DataTable with Toolbar, long input texts overlap with the 'x' btn. By looking at its css styles, it could possibly be the padding-right of the input element not being set properly. By comparing with the default search component, I found out that the padding-left both exist, but the padding right only exist in the default search

## Environment

> Operating system

> Browser

> Automated testing tool and ruleset

> Assistive technology used to verify

## Detailed description

> What version of the Carbon Design System are you using?

> What did you expect to happen?

> What happened instead?
image
> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5142

Adds right padding to more clearly mimic the default search behavior. This will make sure the search text does not tuck under the close button. 

#### Changelog

**Changed**

- Add padding to the right of the search input

**Removed**

- weird style bug on a persistent search box

Screen Shot 2020-01-22 at 2 16 31 PM

#### Testing / Reviewing

Add lots of text to a data table toolbar search input and ensure it stops before the close button

### CODE REVIEW

**Comment by abbeyhrt** [comment]
@tw15egan This isn't coming from this PR but i noticed that the focus for the search clear button is off: 
Screen Shot 2020-01-23 at 1 39 21 PM
would we want to address that in this PR too or do it in a separate PR/issue?

**Comment by tw15egan** [comment]
@abbeyhrt should be fixed now! Good catch 👍

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by laurenmrice — APPROVED** [review]
looks good to me 🙌🏻

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Pull request merged**
