### PR TITLE
chore(project): update Node.js version to v12 LTS

### PR DESCRIPTION
**Pull request by vpicone**
### Motivation
Node 12 is the LTS version, we'll need to update eventually. This brings us in line with the theme/website minimum node versions as well.

### Changelog
- update all workflows to use node 12,
- update min version in package.json to reflect 12
- update `scss-to-json` v2 which removes its dependency on `node-sass` v3 which is `node 12` incompatible.

### CODE REVIEW

**Comment by joshblack** [comment]
Yeesh, no idea what's going on with node-sass. If you end up needing to force one version that's totally fair, can place it in `/package.json` under resolutions with the other stuff 👍

**Comment by vpicone** [comment]
@joshblack yeah not sure :/ it looks like we have a node-sass@3 in our yarn lock and offline mirrors for some reason not sure if it’s trying to build that?

**Comment by joshblack** [comment]
@vpicone when looking at the error messages locally it seems like `scss-to-json` was the dependency causing issues and it had a nested `node-sass` in its node_modules, maybe it's something with that?

Can always try pinning it to the version we want to use too to see if that helps address it.

**Comment by vpicone** [comment]
@joshblack ah nice that was it. Updating `scss-to-json` removed the dependency on `node-sass` v3.

**Review by tw15egan — APPROVED** [review]
Not seeing any issues after updating 👍 ✅

**Review by dakahn — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Pull request merged**
