### PR TITLE
fix(data-table): expanded row border styles

### LINKED ISSUE #2723: [React] Data-table: expandable row border missing
The bottom border of the child row `td`'s are missing when it's expanded, and the bottom border of the parent row `td`'s when it's expanded are also missing. These are used as dividers for each expanded row, so it's a bit odd to look at when there's a missing border which makes it seem like 3 rows are connected. 

The hover styles on expand are also incorrect. The border disappears if you hover on the child but re-appears if you hover on the parent (parent hover is correct). See gif below.

`As is`
Screen Shot 2019-05-09 at 12 28 15 PM

`As is: hover`
Screen Shot 2019-05-09 at 12 28 29 PM
react-dt

`Should be: (vanilla)`
Screen Shot 2019-05-09 at 12 30 23 PM
Screen Shot 2019-05-14 at 3 08 41 PM

### PR DESCRIPTION
**Pull request by hshockley**
Closes #2723

Adds borders to expanded rows

#### Changelog

**Changed**

- `$ui-03` border color to parent rows not including the first column when expanded
- `$ui-03` border color to bottom of visible child rows

#### Testing / Reviewing

'with expansion' story for DataTable

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
this looks good to me, pending design approval

**Review by joshblack — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
-The rules dividing rows that are not currently expanded should extend to both ends of the data table. Right now all rules are breaking. The red lines indicate where it is currently breaking.
Screen Shot 2019-10-28 at 10 06 19 AM

-When a row is expanded then it should only get a top break on the left side. The red line shows where the one break in the rule should be upon an expanded row.
Screen Shot 2019-10-28 at 10 09 09 AM

Also the example header text that is showing upon expansion is not correctly speced and something we shouldn't be showing. It needs to be corrected but I can open an issue for that separately if that is preferred.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
React:
Looks great!

Vanilla:
When the row is expanded, on hover, the separating rule of the row and expanded area disappears. It should always be persistent on hover.

Oct-29-2019 12-16-32

**Review by laurenmrice — APPROVED** [review]
thanks! looks good 👍

**Pull request merged**
