### PR TITLE
fix(icons): update ci-check to fail with exit code 1

### PR DESCRIPTION
**Pull request by joshblack**
When handling our refactor, we had assumed `console.error` would set `process.exitCode` to `1`, instead the `ci-check` fails silently (with `exitCode` as `0`). This updates it so that the catch handler exits with an exit code of `1`, signaling that an error has occurred and failing CI.

#### Changelog

**New**

**Changed**

- Add `process.exit(1)` to fail with code `1`

**Removed**

### CODE REVIEW

**Comment by vpicone** [comment]
@joshblack is 2d7d006 to test that the fail working properly?

**Comment by joshblack** [comment]
@vpicone I think we renamed it to 3D-iCa right? It seems like our ci-check didn't pick up that we wanted to remove the asset, if we still want it totally fair! I can add back in the metadata

**Review by dakahn — APPROVED** [review]
👍

**Comment by vpicone** [comment]
@joshblack ah nvm Coulda sworn I renamed it properly in my PR...

**Review by vpicone — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
looks good to me. I guess there will be a follow up PR to add that missing subcategory?

**Comment by joshblack** [comment]
Note to reviewers, couple of TODOs left on my end:

- Update ci-check to respect no subcategory on pictograms metadata
- Verify pictograms metadata passes CI checks 👍

**Comment by joshblack** [comment]
Issue to update mis-categorized or misnamed icons: https://github.com/carbon-design-system/carbon/issues/3877

**Pull request merged**
