### PR TITLE
fix(tooltip): tooltip autocloses in forms

### LINKED ISSUE #2686: Tooltip in form label with clickToOpen never opens
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
If you use Tooltip with clickToOpen in a TextInput with an id, the Tooltip never opens.  This is because the click on the Label forces a second click event on the Field contents.  We need to put a evt.preventDefault on this line of code to stop the default redirect to the Form Field from firing

> Is this issue related to a specific component?

Tooltip
> What did you expect to happen? What happened instead? What would you like to
> see changed?
I need to be able to use Tooltips in the Labels of form elements like this:
image

> What browser are you working in?

> What version of the Carbon Design System are you using?
6.111.0
```
 handleMouse = evt => {
    const state = {
      mouseover: 'over',
      mouseout: 'out',
      focus: 'over',
      blur: 'out',
      click: 'click',
    }[evt.type];
    const hadContextMenu = this._hasContextMenu;
    this._hasContextMenu = evt.type === 'contextmenu';
    if (this.props.clickToOpen) {
      if (state === 'click') {
        evt.stopPropagation();
      /* Need this extra line of code to prevent the default form event from firing */
  evt.preventDefault();
```

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

https://codesandbox.io/s/mrp45kj3x

Note that if you remove the "id" attribute of the TextInput it will work.  This is because the default label to Form field click doesn't happen.

### PR DESCRIPTION
**Pull request by scottdickerson**
Closes #2686

If you render a Tooltip with clickToOpen in a form label, the default behavior is to focus on the form field, which causes the tooltip to automatically close.

#### Changelog

**Changed**

- Stopped the default event from triggering so clickToOpen can be supported in forms.

#### Testing / Reviewing

See the code sandbox listed in the issue above to reproduce.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Hi 👋 thank you for reporting the issue and creating this PR! Creating more reduced case simply putting a click-to-open tooltip inside a `<label>` associated with `<input>` (and seeing `<input>` getting focus upon clicking on the tooltip trigger button in `<label>`) gives me an impression that the tooltip trigger button shouldn't be placed into `<label>`. You can manually lay out `<label>`, `<Tooltip>` and `<TextInput>` separately with empty `labelText` for `<TextInput>` and with some styling.

Feel free to enter an issue for the complete story BTW, which is, a text input with a tooltip as a form field hint. I have seen @carbon-design-system/design has gathered some thoughts on this.

**Comment by scottdickerson** [comment]
But couldn't this fix also prevent problems rendering the tooltip inside Form submission buttons for instance?  Basically anywhere where the Tooltip happens to render inside a place with default browser behaviors. @asudoh

**Comment by asudoh** [comment]
@scottdickerson The click-to-open tooltip has a scenario of some specific UX patterns that is applied to, rather than "tooltip of general purpose". We have seen a bunch of issues from attempts to use our React `<Tooltip>` as a general-purpose tooltip, ending up with drifting away from our design intention. BTW our designers doesn't seem to be against the tooltip UI associated with `<TooltipIcon>` used more general-purpose, and thus we have made the styles for that a series of Sass mix-ins for our icon-only button effort (#2366).

**Comment by scottdickerson** [comment]
hmm, unfortunately our tooltips are pretty heavyweight so the <TooltipIcon wouldn't work for us probably.  They have actions and multi-line content within them.  We're using them to show a learn More link for instance.  Very similar to this picture   
image

 Unfortunately before the clickToOpen={false} was deprecated, we were pretty happy with the <Tooltip/> function.  Is there any downside with stopping the default event from firing?

**Comment by asudoh** [comment]
@scottdickerson The question is more of defining the use case for our interactive tooltip, than of specific API/implementation details. Accepting every use case beyond the design language Carbon is based on will introduce confusions among our users, and thus our maintenance effort goes to unreasonable state.

`carbon-addons-cloud-react` seems to still want hover-over version of our interactive tooltip UI. Would you want to go there and make the change you want?

**Comment by scottdickerson** [comment]
I'm okay @asudoh with this being clickToOpen to true instead of hover, but unfortunately the tooltip isn't opening for me even on click.  This is because of the default event behavior ends up sending two clicks.

**Comment by asudoh** [comment]
> This is because of the default event behavior ends up sending two clicks.

Understood, as I noted, it's just avoiding extra maintenance effort of fixing stuffs coming from unintended usage (tooltip trigger in `<label>`).

**Comment by joshblack** [comment]
Hi all! 👋 Just wanted to bump this thread to see if there is anything we can do to help this move forward 😄

**Comment by scottdickerson** [comment]
hey @joshblack I think it's either a cancel or an integrate. 

1.) Cancel because I should be using TooltipDefinitions with hover in this usecase instead of Tooltip

or 

2.) Support the preventDefault for Tooltip even though my usecase is less that desirable from a UX perspective (I'm using Tooltips within a Label).  

I've talked to my designer and we're okay either way just lemme know :)

**Comment by joshblack** [comment]
Sounds good @scottdickerson! Let's go ahead with option 1, feel free to re-open if this changes! (or if I misunderstanding 🤦‍♂)

**Pull request closed without merging**
