### PR TITLE
feat(HeaderMenu):  include isCurrentPage props to HeaderMenu component

### LINKED ISSUE #9784: Add isActive style for HeaderMenu
### Summary

My suggestion is a design/development enhancement.
I would like to set a boolean prop to set a style for HeaderMenu when it's active like already is made for HeaderMenuItem component.

Example of enhancement result:
isactive2

### Justification

As described in one item of [W3 WAI (Web Accessibility Tutorials)](https://www.w3.org/WAI/tutorials/menus/styling/) it's important to:
"Convey menu items and their states by using color and other styling options. For example, alter the shape of a menu item, or add an icon, in addition to changing its color when it is selected."

I couldn't find a way to do this state change demonstration when a page inside the HeaderMenu is active, then I'm purposing this enhancement.

### Desired UX and success metrics

Clear and consistent styling allows users to find and recognize menus more quickly. Such styling includes consistency in the behavior, appearance, and relative location on pages across a website.

I believe this enhancement will contribute to the user experience with the Header Menu as described above and, as is already done in the HeaderMenuItem component.
Also, this provides best-practice guidance on implementing accessibility for Menus.

HeaderMenuItem example:
tday

### Required functionality

_No response_

### Specific timeline issues / requests

_No response_

### Available extra resources

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by RianTavares**
Closes #9784 

Currently, the links of a HeaderNavigation component (HeaderMenuItem) already have this behavior of Convey menu items and their states setting border-bottom style. Example: 

tday

The point is that when creating a dropdown menu, I mean a HeaderMenu with HeaderMenuItems as children, like in "link 4" in the image above, there isn't a prop expected to set it as an active menu. 

There is already a way to set the items inside the HeaderMenu as Active like below: 
menu-open

As described in one item of [W3 WAI (Web Accessibility Tutorials)](https://www.w3.org/WAI/tutorials/menus/styling/) it's important to:
"Convey menu items and their states by using color and other styling options. For example, alter the shape of a menu item, or add an icon, in addition to changing its color when it is selected."

When the HeaderMenu is closed and a page inside is active the user has no signal of wich page is select looking at the menu. 

Before 
4select-n

After
<img width="510" alt="4selected" src="https://user-images.githubusercontent.com/8935295/135545416-ef7e69ef-0801-4ef5-89e3-a793eaf5d409.png"

###

# Changelog

**New**

- added inside the `carbon/packages/components/src/components/ui-shell/_header.scss` and the `carbon/packages/styles/scss/components/ui-shell/header/_header.scss` a new class (${prefix}--header__submenu--current) to set the active border style (same style as HeaderMenuItem).

**Changed**
- ClassName const inside HeaderMenu to link the new class created, when the prop isCurrentPage is equal true

#### Testing / Reviewing

- Run react storybook
- Go in the file `react/src/components/UIShell/UIShell-story.js`
- Put the prop isCurrentPage in the HeaderMenu component tag. Example: 
```javascript 
<HeaderMenu aria-label="Link 4" menuLinkName="Link 4" isCurrentPage>
```
- Ensure that the border was added to the bottom of the HeaderMenu on the storybook  "Header Base w/ Navigation" example

### CODE REVIEW

**Comment by RianTavares** [comment]
Related to issue #9784

**Comment by RianTavares** [comment]
recheck

**Comment by RianTavares** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by RianTavares** [comment]
recheck

**Review by tay1orjones — CHANGES_REQUESTED** [review]
@RianTavares Thanks for the PR! I think we should just modify the story to have `Link 4 / Sub-link 2` have `isCurrentPage` so we can easily view the functionality in storybook

**Review by johnbister — APPROVED** [review]
lgtm!

**Review by aledavila — APPROVED** [review]
lgtm

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
