### PR TITLE
fix(checkbox): fixed alignment issue on IE11

### LINKED ISSUE #856: [V9] Checkbox misalignment in input + label variant in IE11
screen shot 2018-06-04 at 11 14 39 am

### PR DESCRIPTION
**Pull request by marijohannessen**
## Overview

Resolves #856 

Seems like IE11 needs both `min-height` and `height` set in order to center align items in a flex container (ref https://stackoverflow.com/questions/19371626/flexbox-not-centering-vertically-in-ie). So added a `height` smaller than the `min-height` to make IE happy - and it doesn't affect the component in other browsers.

### Changed

- Added `height: rem(8px)` to `bx--checkbox-label`

## Testing / Review

Make sure the checkbox label is aligned properly in IE11.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
LGTM basically 👍 - Thanks @marijohannessen for doing this! One thing it’d be great to do is adding the detailed reasoning you have to the comment.

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Unfortunately adding a fixed height here will break any checkboxes that are multi-line w/ text wrapping.

**Comment by marijohannessen** [comment]
Ah I didn't think about that @alisonjoseph 🙁 Will see if I can find another solution to this

**Comment by marijohannessen** [comment]
Closing this to find a different solution to this bug.

**Pull request closed without merging**
