### PR TITLE
fix(Search): add `disabled` prop

### LINKED ISSUE #6915: Search component missing `disabled` prop and definition
- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The library already has disabled styles for the Search component but the prop definition and storybook knob are missing. Even though adding the `disabled` prop to the component currently works as expected since it's being spread into the underlying `input`, it would be best to document this prop in code and on Storybook

> Is this issue related to a specific component?

Search

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6915

This PR adds an explicit `disabled` prop and prop type definition to the Search component and updates the corresponding stories. Even though the prop currently works as expected, we should document this prop separately and add it to the storybook

#### Changelog

**New**

- `disabled` prop on Search component and stories

#### Testing / Reviewing

Confirm that the Search component disabled state is still applied when passing in the `disabled` prop, and that there are no style regressions due to missing or incorrect selectors (the styles are already in the library)

### CODE REVIEW

**Comment by tw15egan** [comment]
Should the search icon use `disabled` token when disabled? 

Screen Shot 2020-09-25 at 10 33 46 AM

**Comment by aagonzales** [comment]
Yes, the icon should also be `disabled-02`

**Comment by emyarod** [comment]
I don't think the component currently changes the icon color when you add the `disabled` prop so this isn't a regression but I can make that change here as well

**Comment by tw15egan** [comment]
Looks great! Just seeing a tiny flicker of focus if you click directly on the `x` when it is disabled

search

**Review by tw15egan — APPROVED** [review]
Looks great! 👍 ✅

**Comment by joshblack** [comment]
bump @andreancardona when you get a sec today 👀

**Review by andreancardona — APPROVED** [review]
@emyarod looks good :)

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
