### PR TITLE
fix(content): remove background color from .bx--content

### LINKED ISSUE #9877: [Bug]: .bx--content background disruptive for dark themes
### Package

carbon-components

### Browser

Chrome

### Package version

v10.46.0

### Description

The [`.bx--content` container](https://github.com/carbon-design-system/carbon/blob/main/packages/components/src/components/ui-shell/_content.scss) which is part of the UI shell (not really documented properly anywhere and not used in the UI shell examples) has a background color that causes poor contrast/visibility in darker themes. For some components it clashes with existing colors.

Examples for the different themes:

image
image
image
image

Maybe `.bx--content` should not set a background at all?

### CodeSandbox example

https://codesandbox.io/s/bx--content-l1bnj

### Steps to reproduce

- Set theme to g90 or g100
- Add a content container (`.bx--content`)
- Add components like `ProgressIndicator` to it which use conflicting colors

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by metonym**
Fixes #9877

This PR removes the background color for the `.bx--content` selector, which is used by the `Content` component.

#### Changelog

**Removed**

- fix(content): remove background color from .bx--content

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by jnm2377** [comment]
@aagonzales you were part of the issue discussions, so I requested your review. Is it ok to remove this background-color token for `.bx--content`?

**Comment by aagonzales** [comment]
Yes, I remember now. The content area didn't span the full available area so was causing confusion. I'm good with remove the background color if it doesn't effect anything else.

image

**Review by dakahn — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]

**Comment by tay1orjones** [comment]
I've changed the base branch to be `v10`. I'll open a quick PR to mirror these changes in `main` for v11.

**Review by aagonzales — APPROVED** [review]

**Comment by joshblack** [comment]
cc @tay1orjones or @dakahn, when you get a sec could you help out with the snapshots failing for the test job?

**Comment by tay1orjones** [comment]
@joshblack I'm confused why the check is failing. I've pushed up the correct snap. 

Working off this PR locally there are no changes to commit from `yarn test -u` and `yarn test` passes 🤔

**Comment by tay1orjones** [comment]
Sorry for the delay on this one. We had some issues with workflow config that caused the invalid snapshot problem.

This will be included in v10.56.0, which should go out today.

**Pull request merged**
