### PR TITLE
feat(list-box): update selection style

### LINKED ISSUE #3988: Design Needed to signify 'selected' item (current value) in List Box and other controls.
### Summary

List box currently uses focus ring to indicate current value. need a design to indicate current value that doesn't collide with focus. see https://github.com/carbon-design-system/carbon/pull/3124 for context.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3988.
Refs #4376.

#### Changelog

**New**

- New selection style for list box item.

#### Testing / Reviewing

Testing should make sure combo box and dropdown are not broken.

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [x] Make sure we are using the 16px icon for chevron and the checkmark.

- [x] Hover and selected states look like the same color. Should be using `hover-ui` for hover and `selected-ui` for selected
Screen Shot 2019-11-22 at 9 31 43 AM


- [x] Inline listbox in vanilla and inline dropdown in react: The checkmark icon should be vertically aligned with the chevron icon. Right now it’s too far left.
Screen Shot 2019-11-22 at 9 32 41 AM


- [x] The checkmark icon looks like the wrong color in the dark themes. It should be calling `icon-01`


- [x] Combobox is getting a secondary invalid border when it is set to invalid and disabled. 
Screen Shot 2019-11-22 at 9 37 49 AM


- [x] When we have overflow content inside an item that is selected, we need to still keep enough padding on the right hand side to allow space between the ellipses and to keep the checkmark aligned vertically with the chevron. Right now the checkmark icon is overlapping the ellipses.
Needs to look like this:
Screen Shot 2019-11-22 at 9 49 04 AM

**Comment by joshblack** [comment]
Hey @asudoh! 👋 This looks like an enhancement PR, I think as a group we're tackling fixes through end of year (in particular accessibility) Would be great to focus our attention on those and reserve these types of PR for the new year 👍

**Comment by asudoh** [comment]
Seems that the referring issue (#3988) is an attempt to address the color contrast issue with selected dropdown item. @laurenmrice Any thoughts on the highlights? Thanks!

P.S. for @laurenmrice will take a look the comments next week.

**Comment by asudoh** [comment]
Thanks again @laurenmrice for reviewing!

* Yes, 16 pixels version of checkmark icon is in use
* I can see that the hover highlight is using `$hover-ui` and the selected item is using `$selected-ui`. Probably the difference was not observed because they are close (`#e5e5e5` for `$hover-ui`, `#e0e0e0` for `$selected-ui`)
* Fixed the selected icon position in the inline variant
* Fixed the checkmark icon color
* Fixed the right margin of the long (selected) menu item
* Fixed the invalid outline for `disabled`/`invalid` combination

**Review by laurenmrice — CHANGES_REQUESTED** [review]
-There is still something odd going on with the hover and selected states. Here is an example of when something is already is selected it gets a lighter hover change if you move the cursor on that selected item. Then when you hover to an item that is not selected it still gets the same color as the selected item.
Nov-26-2019 13-00-39

---------------------------------------------------------------------------------------------------

-For long strings of text with ellipses, can we have 16px padding on the left and right before and after the checkmark, and when there is no checkmark present have 48px? Right now the elipses going full line and then changing to shorten even more when selected with the checkmark gets jumpy.

Spec:
Screen Shot 2019-11-26 at 1 11 19 PM

**Comment by asudoh** [comment]
Thanks @laurenmrice for another round of review! Fixed the right margin and the background color of the selected item.

**Comment by joshblack** [comment]
@laurenmrice how should this behave if scrollbars are enabled? Was running into:

image

**Review by joshblack — APPROVED** [review]
Looks great! Just had the one question with scroll bars

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Vanilla and React
- [ ] The rules separating the items in the dropdown is getting cutoff on the right. they should be the same distance away as they are on the left.

To joshs comment: Checkmark should still stay vertically aligned with chevron if there is a scrollbar.  would rather always have them in place instead of them jumping around.

**Comment by joshblack** [comment]
@laurenmrice I'm not sure if that is do-able in CSS as we don't know if a fixed scrollbar is being displayed, or not since it's an OS-level setting. I think we also will run into this with Windows/Edge, and the scrollbars themselves may have variable width (e.g. 15 vs 16px for macOS vs Windows)

**Comment by laurenmrice** [comment]
@joshblack sorry for delayed response, have been consumed by patterns project.  just curious, do you know how often people keep scrollbars persistant? just trying to guage how often this kind of scenario would occur

**Comment by joshblack** [comment]
@laurenmrice it tends to come up for Windows/Linux users and for folks who have a mouse connected to their Mac through a USB (not a trackpad). I personally fall under that last situation, for example, since I always use a mouse when at work/at home.

**Comment by joshblack** [comment]
bump @laurenmrice if you have a sec!

**Comment by laurenmrice** [comment]
@joshblack oh ! sorry for delayed response on this. im going to discuss this with design tomorrow to get a consensus. 👍🏻

**Comment by laurenmrice** [comment]
@joshblack https://opensource.adobe.com/spectrum-css/components/dropdown/ adobe is treating the select state of a dropdown similarly to what we are trying to accomplish. Could you test to see how their checkmark adjusts with a persistent scrollbar in the scenarios you are talking about? (i don't use a mouse or have one with a usb)

**Comment by joshblack** [comment]
@laurenmrice for sure!

image

So for people on Windows/Linux and for those on Mac with a mouse wheel they'll end up seeing this version when it overflows 😞

**Comment by laurenmrice** [comment]
Thanks Josh for trying that out  ! I would like to see if @asudoh could tryout some ways to see if it is possible to keep the checkmark inline with the chevron even if scrollbars are enabled. If he ends up finding its def not possible to keep them aligned in that scenario, then we can go this route.

**Comment by asudoh** [comment]
@laurenmrice Thank you for clarifying the goal you had in mind. I used to work on a logic of detecting if there is a scroll bar or not, and found out that it's error-prone and [has performance problems](https://gist.github.com/paulirish/5d52fb081b3570c81e3a).

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Ok if thats the case from that issue that trying to align things with enabled scrollbars is finicking and my not be a consistent experience then we can just leave it. 

A couple more changes though:

- The rules separating the items needs to be 16px away from the right hand side. Right now they are too short.
Screen Shot 2020-01-13 at 10 42 38 AM

- Double check to make sure we are using the right checkmark icon from elements. https://carbon-elements.netlify.com/icons/examples/preview/#16%2Fcheckmark

**Comment by asudoh** [comment]
Thank you for your review @laurenmrice! Fixed dropdown item border. Wrt checkmark icon, confirmed that checkmark/16 is used.

**Review by laurenmrice — APPROVED** [review]
So everything regarding the new selection state looks good for listbox, dropdown, combobox in vanilla and react. (However I see lots of bugs with these components in other aspects in Vanilla. I can make separate issues for those.)

**Comment by asudoh** [comment]
Cool thanks @laurenmrice for reviewing! Don't hesitate to file other bugs you found!

**Pull request merged**
