### PR TITLE
feat(search): Add in experimental search

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/IBM/carbon-components/issues/1323

Adds in experimental `Search` component

#### Changelog

**New**

- Experimental Search
- A new variation, extra large (`48px`)

**Changed**

- Added a new variation to `search.config.js`

**Removed**

- Extra styles

#### Testing / Reviewing

[Staging Link](http://carbon-dev-environment-exp-search-intelligent-pangolin.mybluemix.net/?nav=search)

### CODE REVIEW

**Review by jnm2377 — APPROVED** [review]
Looks good to me! 💯 I just have a question, it really applies to all components, but I've noticed that a lot of the component sketch files have designs for disabled view but the component examples don't always show a disabled component. I've been adding them, so I was wondering if this was something we stray away from or should disabled examples be added as we go along?

**Comment by tw15egan** [comment]
@jnm2377 Good point. I will temporarily add a disabled state while I am developing/reviewing to make sure the styles work properly, but it may be a good idea to add a variation in the config file that shows the disabled state at all times.

**Review by asudoh — COMMENTED** [review]
LGTM 👍 once design review finishes - Thanks @tw15egan and great point @jnm2377 wrt disable state!

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Comment by alisonjoseph** [comment]
@jeanservaas you can merge it if it looks ok

**Pull request merged**
