### PR TITLE
feat(Pagination): add support for custom page sizes label

### LINKED ISSUE #6387: Allow developer to define custom label for Pagination's pageSizes list
### Summary

Currently, in Pagination component, we can provide a list of page size to the prop `propSizes`

```
<Pagination
    totalItems={totalItems}
    backwardText="Previous page"
    forwardText="Next page"
    page={currentPage}
    pageSize={currentPageSize}
    pageSizes=[5, 10, 15, 25]
    itemsPerPageText="Items per page" />

```

However, there's no way to define a custom text to the value of the pageSizes. In my case, I want to implement a `All` selection to display all data. I can manually handle `All` selection to display all data. However, the problem is with the other labels in the Pagination components which became NaN due to the dropdown having 'All' value instead of the value of the `totalItems`.

image

### Justification

One of the use case is to allow user to make selection to all data at once (e.g. for Export, Delete)

### Desired UX and success metrics

Basically, developer should be able to define the dropdown value and text separately, e.g:

```
const pageSizeList = [
    {value: 5, text: '5'},
    {value: 10, text: '10'},
    {value: 15, text: '15'},
    {value: 25, text: '25'},
    {value: totalItems, text: 'All'},
]
```

### PR DESCRIPTION
**Pull request by akmalmzamri**
Closes #6387

Allow developers to define custom labels for Pagination's `pageSizes` prop without removing support for passing in only numbers in the previous versions

#### Changelog

**New**

- Developers can now use custom labels in `pageSizes` by passing an array of objects with `text` and `value` property instead of an array of numbers as before. 

```
    <Pagination
        {...props()}
        pageSizes={[
          { text: 'Ten', value: 10 },
          { text: 'Twenty', value: 20 },
          { text: 'Thirty', value: 30 },
          { text: 'Fourty', value: 40 },
          { text: 'Fifty', value: 50 },
        ]}
      />
```

The older method of passing an array of numbers will still work:

```
    <Pagination
        {...props()}
        pageSizes={[10, 20, 30, 40, 50]}
      />
```

**Changed**

- N/A

**Removed**

- N/A

#### Testing / Reviewing

- N/A

### CODE REVIEW

**Comment by dakahn** [comment]
Not sure if this enhancement was an accepted proposal -- i've tagged up the linked issue, lemme know if i'm missing something.

**Comment by joshblack** [comment]
Wanted to make sure design had a chance to take a look at this (cc @aagonzales 👀 )

**Comment by jeanservaas** [comment]
Hey @joshblack is this what the change is? The number written out vs. digits?

image

**Comment by tw15egan** [comment]
Yes, that's the proposed change @jeanservaas 👍

**Comment by aagonzales** [comment]
I'm good with adding this `text` feature in relation to this statement:
> There's no way to define a custom text to the value of the pageSizes. In my case, I want to implement a All selection to display all data. I can manually handle All selection to display all data. However, the problem is with the other labels in the Pagination components which became NaN due to the dropdown having 'All' value instead of the value of the totalItems.

However, in the coded example I don't like the actual page number being spelt out instead of using numerals. Is that just for demonstration purposes?

**Comment by akmalmzamri** [comment]
> However, in the coded example I don't like the actual page number being spelt out instead of using numerals. Is that just for demonstration purposes?

Hi, @aagonzales. Yes, it is only for demo purpose. A more real-life example would be:

    <Pagination
        {...props()}
        pageSizes={[
          { text: '10', value: 10 },
          { text: '20', value: 20 },
          { text: '30', value: 30 },
          { text: '40', value: 40 },
          { text: '50', value: 50 },
          { text: 'All', value: totalItems },
        ]}
      />

which will render:
image

**Comment by joshblack** [comment]
bump @aagonzales if you have a sec to confirm based on the usage example above 👀

**Review by jeanservaas — APPROVED** [review]
@aagonzales seems like it is just for demo purposes

**Review by dakahn — APPROVED** [review]
this seems okay to me as long as designs cool with it

**Review by joshblack — APPROVED** [review]

**Pull request merged**
