### PR TITLE
Allow for HTML elements in rendered <fieldset>

### LINKED ISSUE #7797: TileGroup - Allow for passing of HTML elements in addition to Carbon Tiles into a TileGroup
### Summary

Any element passed to the `<TileGroup>` component is rendered as a Carbon Tile. This prevents customizing the contents of the `<fieldset>` HTML element that gets rendered on the page:

Screen Shot 2021-02-12 at 1 49 33 PM

### Justification

Allowing for the ability to add traditional HTML elements to the `fieldset` is ideal because it allows us to group elements underneath the fieldset's `legend` header, making it more WARIA compliant. 

As an example, our page currently renders like so:
```html
<h3>Scope</h3>
<p>...</p>
<fieldset>
  <legend style="display:hidden">Scope</legend>
</fieldset>
```
where we must hide the `legend` element to have the page render properly.

Additionally, this feature would bring us into compliance with the w3 spec for `fieldset`, which allows for "flow content" elements (like `<p>`) to exist inside `fieldset`: https://html.spec.whatwg.org/multipage/form-elements.html#the-fieldset-element.

### "Must have" functionality

Being able to add reasonable HTML elements to the TileGroup component.

### Specific timeline issues / requests

N/A

### Available extra resources

A PR has been created for this issue: https://github.com/carbon-design-system/carbon/pull/7798

### PR DESCRIPTION
**Pull request by 3dfoster**
Closes #7797 

#### Changelog

**New**

Allows for HTML elements to be provided to the TileGroup component without forcing them into becoming `<RadioTile>` components

#### Testing / Reviewing

1. Create a TileGroup
2. Pass "Tile" type children to the TileGroup as well as any HTML element
3. Notice the tiles render as Carbon tiles, and the HTML element renders as an HTML element

### CODE REVIEW

**Comment by dakahn** [comment]
Circling back to this -- did you want to add an example to the storybook demonstrating this? In my testing other children in a control group is fine, but would we want to limit extra children to paragraphs? @tay1orjones

**Comment by tay1orjones** [comment]
Really sorry about the delay here! I agree, let's limit this to paragraph tags (or a couple others) only _for now_ and then selectively add in other accepted elements as needs arise. A storybook example would be helpful to properly frame a conversation with @carbon-design-system/design about this, as we'll need their consideration as to what other elements we could allow/encourage.

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Really sorry about the delay here! I agree, let's limit this to paragraph tags (or a couple others) only _for now_ and then selectively add in other accepted elements as needs arise. A storybook example would be helpful to properly frame a conversation with @carbon-design-system/design about this, as we'll need their consideration as to what other elements we could allow/encourage.

**Comment by dakahn** [comment]
@3dfoster do the proposed limitations sound good?

**Comment by dakahn** [comment]
@3dfoster any updates on this?

**Comment by dakahn** [comment]
Closing this up. It's gone quite stale, but we can reopen if we need to later

**Pull request closed without merging**
