### PR TITLE
fix(progress-indicator): design audit changes

### LINKED ISSUE #1976: [Audit] Progress Indicator

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #1976 

- note: the carbon-components repo example shows the last state as disabled, the website html just needs to be updated to include the disabled class `.bx--progress-step--disabled` in the last `<li>`. For some reason right now it's using disabled attribute instead of the class.

*current*
```
<li class="bx--progress-step bx--progress-step--incomplete" disabled >
   ...
</li>
```
*should be*
```
<li class="bx--progress-step bx--progress-step--disabled" aria-disabled="true" >
   ...
</li>
```

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jnm2377!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Looks good! Just one last change: We need to make the type inside of the tooltip menu to be type style: body-long-01 and color token: inverse-01. Right now the line spacing is too cramped.

Also the overflow text is in Helvetica but I think that change is being tracked in another issue.

**Comment by jnm2377** [comment]
@laurenmrice just updated!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Design had to make some design changes for tooltip to align across the board for different components. The spacing and specs are included below.

**Overflow step name:**
artboard

**Review by laurenmrice — APPROVED** [review]
Looks good to me ! 👍

**Pull request merged**
