### PR TITLE
feat: Content switcher example with icon

### PR DESCRIPTION
**Pull request by alisonjoseph**
#552 

Add html with icons to content switcher html

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Looks great - Thank you for doing this @alisonjoseph! One question - Can it be a separate file? e.g. content-switcher—with-icon.html

**Comment by alisonjoseph** [comment]
@marijohannessen suggested putting it int he same file since it's not really a variation but an enhancement. Similar to how we have the button and button with icon in the same file.

**Comment by tw15egan** [comment]
I also think this should be in it's own file, simply because the markup is a lot larger than a simple `button`. In the dev environment, I'm not even able to scroll down to see the code, so I'm just afraid it could cause users some confusion when trying to copy / paste this component when deployed on the website

**Comment by marijohannessen** [comment]
Okay, I'm fine with a separate file!

**Review by marijohannessen — APPROVED** [review]
👍 ✅  Good to merge once extracted to its own file!

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Pull request merged**
