### PR TITLE
feat(@ibm/plex): Update plex dependency to use new packages

### PR DESCRIPTION
**Pull request by tw15egan**
Updates `@carbon/styles`  to use individual `@ibm/plex-${font-style}` packages rather than importing all from `@ibm/plex`

#### Changelog

**New**

- 8 new packages for each of the `@ibm/plex` families 

Screenshot 2024-07-25 at 9 17 15 AM

- `font-feature-settings: 'liga' 1;` added to `_reset.scss` to ensure ligatures render even with `letter-spacing` set
- `$package-name` field added to font src resolver

**Changed**

- Updated the `url` field in font src resolver to use new package name format 

**Removed**

- Split fonts do not seem to ship `.woff`, so [they have been removed](https://github.com/carbon-design-system/carbon/pull/17025/files#diff-95fa1084e7c21be991e52f92b77cc405b040c0356534cd670dc5db7708739dafR16) from the individual font formats

#### Testing / Reviewing

Ensure the fonts are loaded correctly, either using the Akamai CDN or not. Ensure the `fi` ligature renders properly.

### CODE REVIEW

**Comment by tay1orjones** [comment]
One thing to verify here is the ligature fixes from #11175 https://github.com/IBM/plex/issues/438 are coming through. The storybook doesn't turn on the `$use-akamai-cdn` flag, so the `fi` ligature is still broken. For example in the notification component:



This should be fixed by this PR where we consume the new packages that contain these updates to the font files. I know this is still in draft, but right now I don't see the ligatures in the deploy preview.

**Comment by tw15egan** [comment]
@tay1orjones it seems like a component-level issue for some reason. I will take a deeper look. I see the ligatures when just putting text outside of the notification Screenshot 2024-07-24 at 2 38 04 PM

**Comment by tay1orjones** [comment]
@tw15egan wow, yeah it's part of the [current css-fonts-3 spec](https://www.w3.org/TR/css-fonts-3/#:~:text=setting%20a%20non%2Ddefault%20value%20for%20the%20%E2%80%98letter%2Dspacing%E2%80%99%20property%20disables%20common%20ligatures.) and the working draft [css-fonts-4 spec](https://www.w3.org/TR/css-fonts-4/#:~:text=setting%20a%20non%2Ddefault%20value%20for%20the%20letter%2Dspacing%20property%20disables%20optional%20ligatures.)

> setting a non-default value for the ‘letter-spacing’ property disables common ligatures.

**Review by tay1orjones — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]
🔥

**Pull request merged**
