### PR TITLE
feat(cli): add component command

### PR DESCRIPTION
**Pull request by joshblack**
Reference #7360 

This PR creates an initial command for creating a component. This does not include the package scaffold, instead it scaffolds out files inside of our react project following our current practices.

#### Changelog

**New**

- Add `component` command to `@carbon/cli`

**Changed**

**Removed**

#### Testing / Reviewing

- Try and create your own component with it! You can reference the CLI with the path `./packages/cli/bin/carbon-cli.js` and can call it directly from your shell
- See if tests and stories work 😬

### CODE REVIEW

**Comment by dakahn** [comment]
Should there be output when the command is run?
image

**Comment by joshblack** [comment]
@dakahn sorry, to be specific the command would be:

```bash
./packages/cli/bin/carbon-cli.js component
```

**Comment by tw15egan** [comment]
cli

Screen Shot 2020-12-02 at 12 36 03 PM

Very cool!

**Comment by dakahn** [comment]
maybe not a blocker, but there's a permission denied error on WSL
image

**Comment by joshblack** [comment]
@dakahn I _think_ that's because the path you gave `/caverns` is at `/caverns` instead of a relative path (like `components/caverns`) and the profile trying to run the command doesn't have permissions to write to that path

**Review by dakahn — APPROVED** [review]
That worked! More WSL weirdness

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
