### PR TITLE
fix(Dropdown) Dropdown option - remove extra right padding

### LINKED ISSUE #6074: bug(Dropdown Option)Fix extra right padding
## Dropdown extra padding

Dropdown has extra padding that isnt needed and would allow for longer text

Screenshots:

Screen Shot 2020-05-13 at 4 24 12 PM
Screen Shot 2020-05-13 at 4 24 18 PM

### LINKED ISSUE #6078: bug(Table) - table sort height broken in Firefox
When the table is a sort table there is a fixed height set on th, the button within it has a height set to 100%. The button scales fine in chrome and etc but in firefox the height breaks.

Screen Shot 2020-05-13 at 6 06 55 PM

Firefox 76.0.1

### PR DESCRIPTION
**Pull request by DusanMilko**
Closes #6074

Remove right padding on option as it isnt needed and makes truncation happen too soon

### CODE REVIEW

**Comment by dakahn** [comment]
tagging you in @aagonzales. Is this right padding spec and are these changes a-okay?

**Comment by aagonzales** [comment]
Yes, the menu items themselves should only have 16px padding on the right. The main input will have different padding.

image

**Review by aagonzales — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
I believe that space is needed for Combobox selection, as now the text will lay under the checkmark. 

Perhaps this change should only affect rows that do not have the checkmark added?

Screen Shot 2020-05-14 at 10 36 17 AM

**Comment by DusanMilko** [comment]
@tw15egan i see, ill do a follow up pr to address the situation

**Pull request merged**
