### PR TITLE
fix(number-input): add aria attributes for a11y

### LINKED ISSUE #1743: Number Input Buttons need Descriptive Labels and Input Needs aria-live
copied from https://github.com/IBM/carbon-components-react/issues/1658

---

## Detailed description

The [latest version of number input](https://deploy-preview-1657--carbon-components-react.netlify.com/?selectedKind=NumberInput&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel) has two buttons that when clicked increment the number box. The plus button should be labeled "+ increment" and the - button should be labeled "- Decrement". The input also needs to have aria-live="polite" and aria-atomic="true" so that the screen reader always reads the whole number in the input box rather than just the numbers React changes.
As the buttons are currently, they both have the same label. Here are the button elements:

	<button class="bx--number__control-btn up-icon" type="button"><svg class="up-icon" fill-rule="evenodd" height="5" role="img" viewBox="0 0 10 5" width="10" aria-label="choose a number" alt="choose a number"><title>choose a number</title><path d="M0 5L5 .002 10 5z"></path></svg></button>
	<button class="bx--number__control-btn down-icon" type="button"><svg class="down-icon" fill-rule="evenodd" height="5" role="img" viewBox="0 0 10 5" width="10" aria-label="choose a number" alt="choose a number"><title>choose a number</title><path d="M0 0l5 4.998L10 0z"></path></svg></button>

## Steps to reproduce the issue

1. Using NVDA visit the [components page](https://deploy-preview-1657--carbon-components-react.netlify.com/?selectedKind=NumberInput&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel)
2. hit m to jump to the frame
3. NVDA announces: "Button choose a number graphic choose a number". This is the up arrow.
4. Hit down arrow
5. NVDA announces "Button choose a number graphic choose a number". This is the down arrow.
6. hit enter on one of the buttons and NVDA says nothing.

## Expected Behavior

NVDA should say an informative text on the button and when one hits enter NVDA should say what is changed.
The svg does not need any role, alt, or aria-label. The text that should change is in the title element. (I need to test to make sure this is correct, but text should not be duplicated).

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1743

Related: https://github.com/IBM/carbon-components-react/issues/1658

This PR adds `aria-live` and `aria-atomic` attributes to improve a11y

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
cc @dakahn to confirm 👍

**Review by jnm2377 — APPROVED** [review]

**Comment by asudoh** [comment]
@emyarod Could you please solve the merge conflict...? Thanks!

**Comment by emyarod** [comment]
should be resolved now @asudoh

**Comment by asudoh** [comment]
Oh @emyarod could you please also solve Handlebars errors seen in the Netlify build...? Thanks!

**Comment by emyarod** [comment]
yes taking a look right now

**Comment by emyarod** [comment]
@asudoh a bad rebase broke the netlify build, it should be fixed now although I'm not entirely sure if I dropped any changes

**Comment by asudoh** [comment]
Thanks @emyarod! The latest code looks good to me, let's see what @dakahn thinks.

**Comment by dakahn** [comment]
👋 Hi! The error state should have a role="alert" with aria-atomic="true" so screen readers announce the value is invalid when an error is made. Other than that it looks good to me!

**Review by dakahn — CHANGES_REQUESTED** [review]
👋 Hi! The error state should have a role="alert" with aria-atomic="true" so screen readers announce the value is invalid when an error is made. Other than that it looks good to me!

**Review by dakahn — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
This may the most approved PR in the history of Carbon 😂

**Pull request merged**
