### PR TITLE
fix(uishell): close HeaderMenu on blur

### LINKED ISSUE #4930: Multiple nav menus can be open at the same time, instead of closing onBlur
## What package(s) are you using?

- [ ] `carbon-components`
- [ ] `carbon-components-react`

When moving between two tabs within a header menu nav bar, I would expect that with each tab's respective dropdown menu, the previously open one would close to prevent weird overlap on cascade. Currently it does appear that such an onBlur event does exist but is not consistently firing.

> What browser are you working in?
Google Chrome 78
> What version of the Carbon Design System are you using?
carbon-components 10.7.4
carbon-components-react latest
## Steps to reproduce the issue

1. Open a HeaderMenu tab so that the dropdown appears
2.  Select another HeaderMenu tab
3. Observe bug

- Screenshots or code
image

### PR DESCRIPTION
**Pull request by GregDevProjects**
Closes #4930 

{{short description}}

Close the HeaderMenu on blur, to prevent multiple HeaderMenus from being open at once 

**Changed**

If the selected element that triggered the blur has the attribute of `href=#`, then it's another menu, so the expanded HeaderMenu should be closed

#### Testing / Reviewing

1. `cd packages/react && yarn storybook`
2. go to http://localhost:9000/iframe.html?id=ui-shell--header-base-w-navigation&viewMode=story#
3. expand `Link 4`
4. select `Link 3`
- notice the expanded menu will close, this doesn't happen currently on http://react.carbondesignsystem.com/iframe.html?id=ui-shell--header-base-w-navigation&viewMode=story#

### CODE REVIEW

**Review by tw15egan — DISMISSED** [review]
LGTM, thanks for adding this! 👍

**Comment by tw15egan** [comment]
Hmm, one thing I noticed is that tab navigation is now unable to navigate into the opened nav panel..

**Comment by GregDevProjects** [comment]
thanks for the save @tw15egan! I added a check to ensure the element triggering the blur isn't one of the sub menu items before closing the `HeaderMenu`

**Review by tw15egan — APPROVED** [review]
Changes look great! Thanks for updating so quickly

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @GregDevProjects!

**Pull request merged**
