### PR TITLE
fix(tabs): Update mobile dropdown view styles to match v9

### LINKED ISSUE #935: Tabs: Mobile dropdown view needs updated dropdown styles
screen shot 2018-06-26 at 9 03 01 am

Mobile view for tabs switches to a dropdown that has the old styles, needs to be updated to match the v9 styling for dropdowns.

### PR DESCRIPTION
**Pull request by alisonjoseph**
## Overview

Resolves #935 

Updates to the dropdown mobile view styles for tabs.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @alisonjoseph for finding the discrepancy!

**Comment by tw15egan** [comment]
Looks great, I guess my only question is whether the Dropdown should use the default background (`$field-01`) or the light background (`$field-02`)

**Comment by alisonjoseph** [comment]
@tw15egan I added in code for both colors if you look at line 58, although theres no documenation anywhere that it exists.

**Comment by tw15egan** [comment]
Ah perfect! Could we just add that in under the `Modifiers` section in the `readme` file? After that I'm good to merge this

**Comment by alisonjoseph** [comment]
added @tw15egan

**Comment by alisonjoseph** [comment]
added @tw15egan

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
