### PR TITLE
fix(datatable): move minwidth of datatable to table element

### PR DESCRIPTION
**Pull request by paul-sachs**
Since overflow is on the container, it doesn't make sense to put the min-width on it as well. Move it to the table element itself.

An example of the issue can be found here: https://codesandbox.io/s/mzkl5mlz3y

Note that the width of the wrapper element should cause a scroll bar on the container.

#### Changelog

**Changed**

- Moved min-width to table element instead of container

### CODE REVIEW

**Comment by asudoh** [comment]
Thanks @psachs21 for jumping in! The change basically looks good. I'm thinking of potential impact to existing applications, though. CC @IBM/carbon-developers to see anybody has any thoughts. One possible way to mitigate the risk is roping off the change with [`feature-flag-enabled()`](https://github.com/IBM/carbon-components/blob/v9.26.0/src/globals/scss/_functions.scss#L4).

**Comment by alisonjoseph** [comment]
I agree with the change, but am also worried this may be potentially breaking for a current user.

**Comment by paul-sachs** [comment]
A feature flag feels a little... forced. I would hesitate to use feature flags to gate bugs. Instead, i would suggest it be released as a version change, following semver, if it changes behavior. Semver is a little weird though, when it comes to CSS, due to it's unavoidably global nature. I dunno, however ya'll want to handle.

**Comment by alisonjoseph** [comment]
We've committed to only releasing breaking changes twice a year, so would need to wait until later this year for our v10 release planned for December.

**Comment by paul-sachs** [comment]
Guess i'll just introduce some overriding CSS for now. If anyone is reading this looking for the solution, the following will fix it:

```css
.bx--data-table-v2-container {
  min-width: 100% !important;
}

.bx--data-table-v2 {
  min-width: 31.25rem !important;
}
```

**Comment by joshblack** [comment]
@asudoh we could wrap this behind our `breaking-changes-x` flag now, right?

**Comment by joshblack** [comment]
Just pushed change guarding it with `breaking-changes-x` so we could merge in! cc @asudoh

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @psachs21 and @joshblack!

**Review by alisonjoseph — APPROVED** [review]
👍 LGTM!

**Pull request merged**
