### PR TITLE
fix(PasswordInput): use updated tooltip for password visibility toggle

### LINKED ISSUE #3462: [PasswordInput]: Toggle text styles
## Detailed description
Text under toggle in `PasswordInput`, with class`bx--text-input--password__visibility::after`, is extending from input outside of his size. Its fine if we have padding above 3rem from left and right.

This is mostly problem on my login page,  when screen size gets smaller for mobile users and my padding is only 1.5rem around form. I was looking for some information, if its required to have at least 3rem padding, but couldnt find any.
U can see it in codesandbox exmaple. Scroll shouldnt be there, I think? Thanks :)

> Carbon Version
latest

> CodeSandbox
https://codesandbox.io/s/codesandbox-2dxtk

> Web browser 
Edge
Chrome

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3462

This PR updates the tooltip in the password input visibility toggle button to match our updated icon tooltip strategy. This PR also allows users to control the positioning and alignment of the password visibility toggle tooltip

#### Changelog

**New**

- `.bx--text-input--password__visibility__toggle` class as a replacement for `.bx--text-input--password__visibility` to avoid using deprecated mixins
- `tooltipPosition` and `tooltipAlignment` props to control visibility toggle button tooltip

**Changed**

- update tooltip to WCAG 2.1 compliant tooltip (Refs #2287, #2366, #3115, #3368)

**Removed**

- unused props

#### Testing / Reviewing

Ensure there are no regressions with the password visibility toggle button tooltip and that it is configurable as expected

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
LGTM basically, just one question - Is older markup still work? Thanks @emyarod!

**Comment by emyarod** [comment]
@asudoh yeah the styles are fully backwards compatible. do we need to keep the old selectors for the vanilla js code?

**Review by jnm2377 — APPROVED** [review]
LGTM, I'd say that it's probably still good to keep the old selectors until they're deprecated in another major version. We've had users pushback on this with other PRs when we remove selectors in minor versions. Just my opinion.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Unlike markup, vanilla JavaScript code is upgraded upon `carbon-components` upgrade, so we don't need compatibility for older vanilla JavaScript code.

**Pull request merged**
