### PR TITLE
feat(TooltipIcon): add new direction prop types

### LINKED ISSUE #5050: TooltipIcon shows Invalid prop warning for direction 'left'
## Title line template: [Title]: Brief description
Although direction left and right are supported by the specification, the `TooltipIcon` displays a property warning in the console of the browser:
```
checkPropTypes.js:20 Warning: Failed prop type: Invalid prop `direction` of value `left` supplied to `TooltipIcon`, expected one of ["top","bottom"].
    in TooltipIcon (created by SamplePanel)
...
```

This is due to the restriction of the direction property to `top` and `bottom` in https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/TooltipIcon/TooltipIcon.js#L58:
```
direction: PropTypes.oneOf(['top', 'bottom']),
```

## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5050

This PR adds missing prop types for the `left`/`right` tooltip icon `direction`

#### Changelog

**New**

- new `direction` prop types

#### Testing / Reviewing

Ensure no console errors are emitted when setting `TooltipIcon` direction

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Would this count as `feat` since we're expanding the prop type definition? Happy to add an example over to versioning guide if so 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by tw15egan** [comment]
@emyarod can you update this branch so we can merge this in? 

Screen Shot 2020-01-20 at 2 17 14 PM

**Comment by emyarod** [comment]
I thought it was possible for maintainers to manually update branches

**Pull request merged**
