### PR TITLE
feat(search): "medium-sized" search input height

### LINKED ISSUE #3457: [Search] add 40px search size
Spec:

We have a 48px and 32px search but we want to also have a 40px search so it will align if its sitting next to 40px field heights.

We have seen some usecases where this would be a valuable size to add to our existing component. There have been instances where it could be useful when filtering content on a page or a data table and having a search inline with the filter field.

### PR DESCRIPTION
**Pull request by AlexanderLyon**
Closes #3457

Adds a "medium" size for search input with a height of `40px`, as well as updated documentation.

#### Changelog

**Changed**

- `_search.scss`
- `search.config.js`
- `search/README.md`

image

### CODE REVIEW

**Comment by AlexanderLyon** [comment]
@laurenmrice

**Review by asudoh — COMMENTED** [review]
Thank you for jumping in @AlexanderLyon! Some comments:

* Can you make the suffix `lg` because we used have `lg` whose size was `40px`? (Side note: The default (`48px`) variant is called `xl`)
* Can you make sure `Close16` is used?

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Looks good in Vanilla, we do need to have the close icon popup if you start typing in the field, currently it is not showing. You can reference the xlg and sm versions.

For react I don't see a way to change the search to the lg version. I see the search is xlg by default and there is a knob option for small, but there should also be a knob option for lg.

**Comment by jnm2377** [comment]
@laurenmrice I think this is a vanilla only contribution

**Comment by laurenmrice** [comment]
Oh okay thanks Josefina! @AlexanderLyon Do you feel comfortable making this in React as well? I just noticed the file wasn't updated for React, if not that is okay and I can open a separate issue for someone to tackle.

**Comment by AlexanderLyon** [comment]
@laurenmrice I can definitely give it a shot later today!

**Review by jnm2377 — CHANGES_REQUESTED** [review]
Thanks for the contribution! It's looking really good. Just a few comments: 
- [ ] Looks like the clear search button is there, but the svg blends in with the background, so we just need to update the svg color. 
Screen Shot 2019-10-07 at 10 55 06 AM

- [ ] Like @asudoh said, let's update the suffix to be `lg` and the scss selector to be `.#{$prefix}--search--lg`. Sorry for the confusion. I know the design specs say medium but this would technically be our `lg` version since our normal search bar is `xl`. I think it's ok if the label says "Medium search" (`search.config.js`: line 32)

**Comment by jnm2377** [comment]
@laurenmrice @AlexanderLyon actually, just realized it looks like Akira has a draft pr in progress for react changes that relies on this fix #4238 

So I think you can just fix the style changes we asked for and it should be good to go. We'll make sure your PR gets merged in before Akira's since his PR relies on this. 👍

**Comment by AlexanderLyon** [comment]
@jnm2377 sounds good, I should have this ready to go by tomorrow 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @AlexanderLyon for the updates!

**Comment by AlexanderLyon** [comment]
@jnm2377 @asudoh - requested changes have been made! Let me know if you'd rather change the label from "medium" to "large", as this may also require changing the descriptions for the existing sizes too

**Review by jnm2377 — APPROVED** [review]
Looks good! thanks! 🎉

**Review by laurenmrice — APPROVED** [review]
looks good 🎉

**Review by abbeyhrt — APPROVED** [review]
Looks great! 🎉

**Pull request merged**
