### PR TITLE
feat(grid): add modifier to remove outer margin

### LINKED ISSUE #2792: [Grid] Add option to not add page gutters at large viewports
Looking at https://carbon-elements.netlify.com/grid/examples/preview, on small viewports, the grid goes wall-to-wall.

image

At 42rem viewport width, the grid adds "page gutters" to the left and right of the grid.

image

The `bx--grid--full-width` modifier is nice to remove the max-width in the default grid, but it still has the page gutters to the left and right. This is problematic if you want to nest grids.

I propose we add the modifier `bx--grid--no-gutter` to remove the outermost left and right gutters at all viewports. Like:

```css
@media (min-width: 42rem) {
  .bx--grid--no-gutter {
    padding-left: 1rem;
    padding-right: 1rem;
  }
}
```

And document it [here](https://carbon-elements.netlify.com/grid/examples/preview/#no-gutters) for when the grid itself should not have gutters, as we currently handle `bx--no-gutter` on columns (set on column or row).

With this, you could set `bx--grid bx--grid--no-gutter bx--grid--full-width` to nest grids.

Referencing our [guidelines](https://www.carbondesignsystem.com/guidelines/layout/#margins), this would prevent the grid from ever having these pink regions.
image

### PR DESCRIPTION
**Pull request by mattrosno**
Closes #2792 

The Carbon grid has an outer margin at most viewport sizes. See image here: https://www.carbondesignsystem.com/guidelines/layout/#margins

Per the breakpoint table (https://www.carbondesignsystem.com/guidelines/layout/#breakpoints), only small viewports don't have grid margin.

There are scenarios where you need to nest grids (e.g. tab container that needs a nested grid inside the page's top-level grid https://react-step-6--carbon-tutorial.netlify.com/#/). This new modifier supports this usage scenario.

#### Changelog

**New**

- `bx--grid--no-margin` class

#### Testing / Reviewing

https://deploy-preview-3435--carbon-elements.netlify.com/grid/examples/preview/#no-margin

This could seem confusing as "no margin" actually overrides CSS `padding` property. But, for consistent naming with the design spec, I think it's best to call this "no margin". If you look at our breakpoint map (https://github.com/carbon-design-system/carbon/blob/master/packages/components/docs/sass.md#carbon--grid-breakpoints-variable), we call it "margin" there too.

### CODE REVIEW

**Comment by asudoh** [comment]
Hi @mattrosno great to see you jumping in! Looking at the code you changed and the linked issue made me think that we should have better support for nested grid, or a grid in a non-full-width-of-viewport container. Not sure if `.bx--grid--full-width` was for that purpose. Let's see what other reviewers think. Thanks!

**Comment by alisonjoseph** [comment]
I didn't think our grid supported nested grid at all currently. I haven't tested it though. 🤔 

Is design ok with us removing these outer margins? Would it make more sense to automatically collapse them if a grid is inside a grid? Also, does the grid actually work inside another grid?

**Comment by mattrosno** [comment]
> Also, does the grid actually work inside another grid?

@asudoh @alisonjoseph this enhancement makes it possible to nest grids.

See https://react-step-6--carbon-tutorial.netlify.com/#/ for a valid scenario where nesting grids is necessary (tab container needs a grid inside the page's grid). In the tutorial, I accomplished this through a custom declaration `bx--grid--no-gutter` that this PR properly provides, better called `bx--grid--no-margin`.

> Not sure if .bx--grid--full-width was for that purpose. Let's see what other reviewers think.

@asudoh `bx--grid--full-width` just removes the default `max-width` on the grid. This PR is about removing grid outer margins through a modifier class.

> Is design ok with us removing these outer margins?

@alisonjoseph this doesn't modify the default grid. Its intended usage is for when a grid needs to be nested, which is a technical not design consideration.

> Would it make more sense to automatically collapse them if a grid is inside a grid?

@alisonjoseph I don't think it's preferable to support nested grids without a new class (e.g. `.bx--grid .bx--grid { ... }` as that's too opinionated.

**Comment by alisonjoseph** [comment]
I definitely agree we need nested grids, we've "faked it" across the website inside of tabs and other container components because I didn't think we had any support for it currently. 

This looks good to me, but we really need some better docs around grid though, I'm not sure how anyone would know that `no-margin` means "use when nesting. Woudl we want a `bx--grid--nested` class instead? Or is that too opinionated since someone could use it when it's not nested?  Just thinking outloud, no-margin might make the most sense.

**Comment by mattrosno** [comment]
@alisonjoseph I considered `bx--grid--nested` but agree, that's not generic enough.

I mentioned "nested" in the explanation here: https://deploy-preview-3435--carbon-elements.netlify.com/grid/examples/preview/#no-margin

That's far from good enough. When we update https://www.carbondesignsystem.com/guidelines/layout with live examples, we need to call out and demonstrate common scenarios like fluid grids, fixed grids, hybrid grids, **nested grids**, etc. which won't map one-to-one with class names.

Hopefully this set us up to better document on carbon-website in the future.

**Review by alisonjoseph — APPROVED** [review]
👍

**Review by joshblack — COMMENTED** [review]
Quick question, if we're targeting nested grids would we want to just target `.bx--grid .bx--grid` versus having an explicit class for this?

**Comment by mattrosno** [comment]
> Quick question, if we're targeting nested grids would we want to just target `.bx--grid .bx--grid` versus having an explicit class for this?

I think that adds unwanted specificity on that nested grid.

It also seems pretty opinionated. E.g. for whatever reason, what if the outer grid needs the margin removed for some reason and the inner grid wants the default margin? Also, what if the outer grid needs the margin cleared to achieve the design (no nesting)?

For those reasons, an explicit class seems like the safest and most future-friendly approach.

**Comment by joshblack** [comment]
@mattrosno I'm trying to think through this usage-wise and had assumed that most of the time using nested grid you'd want this behavior versus not. In other words trying to figure out what our happy path is and optimize for that.

Going through tutorial stuff, is this often not the case? I think if we make the happy path solid, with easy-enough ways to deviate from it, we should be good.

**Comment by mattrosno** [comment]
@joshblack if we assume intent, then are wrong, only way for a product team to fix is to add an override. We can avoid that by using a modifier class.

With our grid, the mental model is "to achieve X, set these classes". For nesting, I don't think it's too much to ask to add a class so the user remains in control of which grid has margin applied.

**Comment by joshblack** [comment]
@mattrosno definitely don't think it's too much to ask, for sure. I was just trying to think about frequency in this case. Might be annoying to always specify an extra class if that's what someone thinks should be the default. 

I'm not suggesting that this means don't support a selector to opt out of that, just that whatever behavior is more frequent or is the intended happy path we should do by default but still supply the classes to opt out of that or customize it in some way.

**Comment by mattrosno** [comment]
@joshblack if we expect the majority of nested grids won't need margin, we could do this:

```scss
.bx--grid {
  // has margin by default
}

.bx--grid .bx--grid {
  // remove margin
}

.bx--grid .bx--grid--margin {
  // add margin back in when wanting to opt out of the grid's default
}
```

Seems like a lot of specificity. Plus it's awkward because the default grid has margin yet the nested grid has to specify `--margin`. It's a lot cleaner to leave it in control of the user:

```scss
.bx--grid {
  // has margin by default
}

.bx--grid--no-margin {
  // opt out of default margin
}
```

We can't rely on any child (`>`) selectors here, so there's no good way to protect against side affects of assuming styling when `.bx--grid .bx--grid`.

I'm all for catering to most common use case, but in this scenario I don't think it's worth the extra specificity?

**Comment by asudoh** [comment]
@mattrosno Just to share my $0.02 - Some of our `v10` codebase applies responsive design to wider areas, including the margin in question. However, due to the limitation in CSS, it's responsive only to viewport width, instead of the container width that nested grid needs. Wondering if it clarifies what I brought up earlier.

**Comment by joshblack** [comment]
Just to try and ground this, what would this situation look like/when would this occur:

> E.g. for whatever reason, what if the outer grid needs the margin removed for some reason and the inner grid wants the default margin?

**Comment by mattrosno** [comment]
> E.g. for whatever reason, what if the outer grid needs the margin removed for some reason and the inner grid wants the default margin?

@joshblack let's say your platform team controls the app's shell and provides a page-level grid. They want to give you full control of your view's container, so they clear the margin. That way if your view needs outer grid margin or not, you have the flexibility to do so?

It's hard to predict how the grid could be used, so for ultimate flexibility it should be as least opinionated as possible.

@asudoh are you referencing components, or the grid?

**Comment by joshblack** [comment]
@mattrosno I think something that I'm still not understanding is why this team would structure a page with a grid that is invalid by default (invalid meaning no margin applied). 

If they want to collapse margins to support grid influencers, wouldn't the grid class only be applied on the content influenced by the grid influencer?

Let me know if this is being nitpicky, just trying to think through when this would occur and why it makes sense to do so.

**Comment by mattrosno** [comment]
@joshblack my main concern with a `.bx--grid .bx--grid` declaration is that it's opinionated.

Another scenario, let's say the nested grid has to be in an iframe. Where all these edge cases feel very rare, my goal with this PR is to keep our grid as flexible and accommodating as possible.

**Comment by joshblack** [comment]
@mattrosno I think the driver for the opinion is to make the common case fast/predictable/simple, but like you said this shouldn't mean we don't allow cases that deviate from the common case.

Are there examples of nested grids from other libraries that we could lean on to see how they tackle this? I'm only aware of [Bootstrap](https://getbootstrap.com/docs/4.0/layout/grid/#nesting) personally

**Comment by alisonjoseph** [comment]
Looks like bootstrap doesn't expect another `grid` class when nesting, that's another good point. Would be nice for it to "just work" when nesting row's inside of columns. 🤔

**Comment by mattrosno** [comment]
@joshblack I get it, all examples in https://www.carbondesignsystem.com/guidelines/layout have the outer margin. Bootstrap doesn't have an outer margin and remains flexible that way. What happens when somebody wants to use our grid (no nesting) and doesn't want to use the default outer margin. Let's say they are accomplishing that margin through the grid's container. How would we support that?

We can be super opinionated that our grid always has an outer margin (all viewpoints), and all nested grids have the outer margin turned off (all viewports). It's just asking for a CSS override when somebody has to deviate in the slightest to achieve their IDL-compliant page.

You want the first snippet in https://github.com/carbon-design-system/carbon/pull/3435#issuecomment-512998764 or do you have a better recommendation?

**Comment by joshblack** [comment]
> What happens when somebody wants to use our grid (no nesting) and doesn't want to use the default outer margin. Let's say they are accomplishing that margin through the grid's container. How would we support that?

Honestly not sure, if someone was motivated to accomplish this it feels like they still could with custom selectors in the current iteration, or they could re-arrange their markup such that the grid container takes on the necessary classes. 

Like I was saying earlier, it's hard personally to understand this stuff without a discrete use-case that someone is running into. If folks can agree that this would be valuable then I'm totally down for it, I'm just being dense right now while trying to figure out what this looks like in practice and how we can help out

**Comment by joshblack** [comment]
Let's close this and align with the work Jeannie is doing this sprint to better figure this out 👍 (feel free to re-open!)

**Comment by j1mie** [comment]
Hey @joshblack just wondering where you guys landed with this. Thanks! 😎

**Comment by joshblack** [comment]
Hey @j1mie! 👋 No updates as of late, have you all been running into this recently?

**Pull request closed without merging**
