### PR TITLE
fix(pagination): fix render issue in IE11

### PR DESCRIPTION
**Pull request by tw15egan**
### Fixes IE11 text issue

Closes https://github.com/carbon-design-system/carbon-components/issues/201

### CODE REVIEW

**Comment by chrisdhanaraj** [comment]
Looks like there's a total of four files that use the initial property in some way - think you could expand this to cover those as well?

https://puu.sh/wwtut/6c24b50439.png

**Comment by tw15egan** [comment]
@chrisdhanaraj will fix

**Comment by tw15egan** [comment]
@chrisdhanaraj added fixes for `flatpickr` and `accordion`, but the `top-nav` issues do not seem to be causing any issues in IE11. Switching them to values causes more issues. Also, added `width: 100%` to `accordion` to fix an issue in IE. Ready to merge.

**Comment by chrisdhanaraj** [comment]
Excellent 👍 ✅

**Review by hellobrian — APPROVED** [review]

**Pull request merged**
