### PR TITLE
fix(inline-dropdown): set min width to prevent shrinkage

### LINKED ISSUE #6296: Inline dropdown shouldn't dynamically resize options
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The user

> Is this issue related to a specific component?

Dropdown with type `inline`.

> What did you expect to happen? What happened instead? What would you like to

That the dropdown entry point size is dynamic but not the size of the options.

> see changed?

Inline dropdown's option's width has a minimum width instead of matching the width of the top. 

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

No.

## Steps to reproduce the issue

1. Open storybook: https://react.carbondesignsystem.com/?path=/story/dropdown--inline
2. Take note of the the last option and how many letters are shown to the user.
3. Select any option **EXCEPT THE LAST**.
4. Try to go through options and notice that the last option is more cut of because now the entire dropdown is resized to match the selected item

**Exaggerated Sandbox example:** https://codesandbox.io/s/ancient-framework-mhel3?fontsize=14&hidenavigation=1&theme=dark

## Additional information

- Screenshots or code

image

- Notes

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6296

Prevents list box menu from shrinking on the inline variant

#### Changelog

**Changed**

- set `min-width` to prevent shrinking on inline `Dropdown`

#### Testing / Reviewing

Ensure choosing an option smaller than `288px` does not cause the inline variant to shrink

### CODE REVIEW

**Comment by tw15egan** [comment]
@laurenmrice while testing I noticed the listbox menu also grows when a really large item is selected. Do we want to set any type of `max-width`? Or should this be left up to the end-user?

Screen Shot 2020-06-16 at 3 22 17 PM

Screen Shot 2020-06-16 at 3 22 20 PM

**Review by dakahn — APPROVED** [review]

**Comment by laurenmrice** [comment]
I think we could set a max-width of 480px.

**Comment by tw15egan** [comment]
@laurenmrice updated 👍

**Review by laurenmrice — APPROVED** [review]
thanks! looks good to me !! 👍🏻

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
