### PR TITLE
Allow font weights and styles to be overidden

### PR DESCRIPTION
**Pull request by j1mie**
Add !default to allow variations on plex.

## Overview

Allow weights var to be overridden 

### Added

!default 

 Please review @asudoh

### CODE REVIEW

**Comment by marijohannessen** [comment]
Hi! Thanks for making this PR. What is the motivation behind wanting to override font weights and style? We're using the recommended weights and styles from IBM Plex https://github.com/ibm/type.

**Comment by marijohannessen** [comment]
@asudoh do you know what the motivation behind this PR is? We'd prefer not letting our users override type styles.

**Comment by asudoh** [comment]
@marijohannessen @j1mie The only guess I can make is application-specific reason - e.g. The designer for the app asked for different font weight from our guide. That said, whether or not to take this PR highly depend on how strictly we want to enforce the font weight per our style guide.

@j1mie Great to understand the background - Thanks!

**Comment by j1mie** [comment]
@asudoh that's exactly it, our designers have chosen different font weights for our application.

@marijohannessen Apologies for the delay in getting back on this. If this approach isn't possible we can review our chosen font weights to see how we proceed.

Thanks!

**Comment by marijohannessen** [comment]
I'm going to double check with our designers on this before closing or submitting this PR - @aagonzales or @bsonefeld we probably don't want to allow font weights to be overridden, or am I wrong?

**Comment by aagonzales** [comment]
This is kind of a mix answer:
- If you're in the IBM Cloud family then no you shouldn't override the typestyles.
- If you're a completely separate product that never interacts with IBM Cloud then I think its ok to override the typestyles to fit your need. 
- However, we do only use the 3 weights that Duo specifies as correct for Plex usage. Where exactly are you diverging from the Carbon typestyles? What other weights do you need?

**Comment by kamilzal** [comment]
Hi @aagonzales & @marijohannessen. We used 3 weights of Plex which are:

- Regular
- Medium
- SemiBold

While experimenting and exploring we did not find much use for a "light". As well "medium" works really nice for buttons, titles and tabs. We swapped light for medium to do not have more than 3 as recommended.

**Comment by aagonzales** [comment]
@kamilzal So are you then systematically swapping out the weight? Like everywhere Carbon Default uses `light` you'll replace with `medium`. And then you're not changing the places where we're using Regular and SemiBold? 

If its more custom than a one to one swap then this will be non-consistent overriding and it won't be theme-able on our end. Theming only works when the usage is the same across the board and only the style changes.

**Comment by j1mie** [comment]
@aagonzales We're using custom type mixins and classes (similar to your giga, mega etc. ones) for several components.

In terms of theming I agree, it'd be better to be able to do this all via sass variables rather than overriding. We hope to continue removing overrides in future and instead using more theming variables as they are added.

**Pull request merged**
