### PR TITLE
docs: update modal state manager examples

### LINKED ISSUE #6591: Update docs for Modal
This issue is to update the stories that we have for the Accordion component in our storybook. This work includes the following:

- [ ] Update each story in `<Component>-story.js` to Component Story Format
  - There is an optional codemod that you can use from storybook:
  - `npx -p @storybook/cli@next sb migrate storiesof-to-csf --glob='packages/react/src/<Component>/<Component>-story.js'`
- [ ] Update stories in the existing file, including:
  - [ ] Create a default example named after the component without any knobs (should match the first example in the overview section)
  - [ ] Clean-up or streamline any stories that seem to need it
  - [ ] Create a `Playground` story that uses knobs for the component
    - For any other components that use knobs, add a `<Component> Playground` story
- [ ] Create an `Accordion.mdx` file and fill it out according to the template below
  - You should import the `mdx` file in your story and pass it as an option to the story config (see example below)
  - You can refer to stories by their story id from `Accordion-story.js` in `Accordion.mdx`
- [ ] Document any usage mishaps for v11

<details>
<summary>Template</summary>

```mdx
import { Story, Preview, Props } from '@storybook/addon-docs/blocks';

# <Component name>

## Overview
<!--
This should include the default use-case(s) for a component, at most 2.
This should be the most common way the component is used.
It should summarize what this common is for and provide snippets for how
to accomplish these common use-cases
-->

<Preview>
  <Story id="story-id" />
</Preview>

## [Use case, for example, Skeleton state or Sorting]
<!--
Each use-case of this component becomes its own section. For example,
if an accordion had a skeleton then you would name this section Skeleton.

If the component had a specific piece of functionality or behavior, like
how you can sort with a Data Table, then Sorting would be the name of this
section.

This section should include an explainer for the use-case and when to use it,
along with a code snippet that someone could bring into their project.
-->

## Component API

<Props />

### [Component name] [prop name]
<!--
Used to clarify prop usage, provide additional info or snippets
-->


## References
<!--
A place for references, links, or a way clarify points made earlier
in the documentation.
-->

## Feedback

Help us improve this component by providing feedback through, asking questions on Slack, or
updating this file on GitHub
[GitHub](https://github.com/carbon-design-system/carbon/edit/master/packages/react/src/components/<Component>/<Component>.mdx).
```
</details>

<details>
<summary>Configure story to use MDX page</summary>

```bash
import mdx from './Component.mdx';

export default {
  title: 'Component',
  component: Component,
  parameters: {
    docs: {
      page: mdx,
    },
  },
}
```
</details>

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6591

This PR updates the MDX docs for Modal and ComposedModal to remove references to ModalWrapper which should be deprecated in the future. ModalWrapper is a simple state manager for modals which was not initially meant to be exported and is now replaced by storybook examples under Modal and ComposedModal

#### Testing / Reviewing

Review the updated modal and composed modal storybook Docs tabs updates

### CODE REVIEW

**Comment by emyarod** [comment]
it may be worth removing `ModalWrapper` from the list of exported components and just providing a recommendation for creating a custom state manager, similar to #6801 for DataTable

**Comment by joshblack** [comment]
@emyarod I think your suggestion to remove it from the exports makes a ton of sense, if you have a sec would appreciate if you added that into the [WIP component updates](https://www.notion.so/carbondesignsystem/Components-dab2cba3afa949a789a6064a5726e57a) for v11 👀  (Just started consolidating there)

Would it similarly make sense to drop the docs for the component and steer them towards the correct/intended solution?

**Comment by emyarod** [comment]
I think it still makes sense to have some documentation around an example (I added one in #6804) but an explicit export like ModalWrapper may no longer be needed in the library

should I use this PR to deprecate ModalWrapper then?

**Comment by joshblack** [comment]
@emyarod definitely your call, whatever makes the most sense!

**Comment by emyarod** [comment]
ok, I think it makes sense to deprecate the component export in the next major version and keep something in storybook for users to reference as an example

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
bump @aledavila when you get a chance today 👀

**Review by aledavila — APPROVED** [review]

**Pull request merged**
