### PR TITLE
fix(date-picker): apply disabled styles to disabled input elements

### LINKED ISSUE #6231: Date picker disabled elements have incorrect styles
the existing disabled styles on our date picker are not correct. the disabled elements still have some changes on hover interaction, and the color tokens are at least 2 years out of date

found by @laurenmrice in #6217

> Screen Shot 2020-06-09 at 11 01 44 AM

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6231

This PR applies the correct color tokens to disabled date picker elements in all themes. The flatpickr styles were consolidated back into `flatpickr.scss` and much of the unused or overwritten pre-v10 code was removed

#### Changelog

**Changed**

- updated to CSS3 selectors
- disabled styles

**Removed**

- autoprefixer covered rules
- commented code
- duplicate selectors

#### Testing / Reviewing

Confirm the date picker matches the v10 spec

### CODE REVIEW

**Review by tw15egan — DISMISSED** [review]
Changes look good to me, thanks for refactoring 👍 ✅

**Review by tw15egan — CHANGES_REQUESTED** [review]
Noticed the year is now getting the wrong color on g90 when _enabled_ (disabled is now correct 👍 )

Screen Shot 2020-06-10 at 4 10 34 PM

**Review by tw15egan — APPROVED** [review]
Looking good 👍 ✅

**Review by laurenmrice — APPROVED** [review]
Disabled styles look great. thanks for updating the code for this component !! 🙌🏻

**Pull request merged**
