### PR TITLE
feat(pictograms): update artwork for customer service pictogram

### PR DESCRIPTION
**Pull request by dudley-ibm**
Closes #

{{closes issue #54}}

#### Changelog

**Changed**

- {{replaced `customer--service.svg` with new, gender-neutral artwork
- 
Screen-Shot-2021-01-15-at-6 06 36-PM
}}

#### Testing / Reviewing

{{ New gender-neutral picto for `Customer service` in `Retail` category should appear on both carbon and on Design Language @vpicone  }}

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, but is the correct ticket being referenced in the PR description?

**Comment by dudley-ibm** [comment]
@emyarod, which ticket are you questioning?

**Comment by emyarod** [comment]
> Closes #

> {{closes issue #54}}

in your PR description @dudley-ibm

**Comment by dudley-ibm** [comment]
Gotcha @emyarod. Those are enterprise pictogram issue numbers. I'll make sure to identify them as such next time.

**Review by joshblack — APPROVED** [review]

**Pull request merged**
