### PR TITLE
fix(progress-indicator): make unclickable step look non-interactive

### LINKED ISSUE #5515: Progress Bar step labels look like a link tag but nothing happens when clicking on it
This is a usability issue. The labels of a step look like a link tag. As a user I would expect more information when clicking on the step label but nothing happens.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #5515.

#### Changelog

**Changed**

- Changed the style of unclickable progress step to make it look non-interactive.

#### Testing / Reviewing

Testing should make sure progress indicator is not broken.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
I think we need to account for the scenarios where the progress step has overflow content and becomes trigger elements for a tooltip. Maybe a check on `renderLabel` in `ProgressStep`?

**Comment by asudoh** [comment]
@emyarod Good point - It was something I was on the fence and went to the route of not making it look interactive for now. Wanted to have designer's feedback on this. Thanks!

**Comment by aagonzales** [comment]
I actually still don't think the overflow one needs the link indicator. the `...` severs as the indicator and the tooltip should appear on hover or focus, not just on click.

**Comment by asudoh** [comment]
Thanks @aagonzales for your feedback - Updated.

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
