### PR TITLE
fix(number-input): use button for keyboard a11y

### PR DESCRIPTION
**Pull request by hellobrian**
## Overview

Resolves https://github.ibm.com/Bluemix/carbon-issues/issues/256

- copy `@mixin button-reset` from https://github.com/carbon-design-system/carbon-components/pull/262
- wrap up and down arrows with `<button>` for keyboard a11y

### CODE REVIEW

**Comment by marijohannessen** [comment]
I wonder if we can adjust the focus states a bit so it doesn't look off like this?

screen shot 2017-08-14 at 11 16 17 am

**Comment by marijohannessen** [comment]
👍 ✅ ❗️

**Comment by hellobrian** [comment]
image

@marijohannessen Yeah, I agree that the focus outline looks off but the larger click target helps a lot with clicking.
The outline represents the click area for each icon and I'm guessing that trying to make this look better will result in a smaller click area. Anything smaller than that is pretty tough to click.

**Comment by tw15egan** [comment]
can we target the svg when the click area has focus and add the outline to that?

```scss
.whatever-has-focus {
     &:focus {
          outline: none;
          
          & > svg {
               @include focus-outline;
          }
     }
}
```

**Comment by hellobrian** [comment]
image

I tried your suggestion, @tw15egan and ☝️ that's what it looks like. 

The reason why this focus outline looks the way it does is so that we can center the icons. To do this I tweaked the `viewBox` coordinates. I haven't been able to find another way of implementing this yet so I think this will have to do for now.

**Comment by chrisdhanaraj** [comment]
Hey @hellobrian - I think if we can't make the mixin work, we just need to create a custom focus outline for the button; can't ship the outline in that state (we'll get deluged with comments hah)

**Comment by hellobrian** [comment]
Lol okay, how about this:

image

☝️ My only minor gripe with this is that now we're making the click target even smaller than it already is. With this change it'll be about `20px x 10px`. But, then again, our click target for the number input carets were already below the `40px` squared recommended standard for usable click targets. 🤷‍♂️

**Review by bsonefeld — COMMENTED** [review]
I'm fine with the design you have proposed in your last screenshot.

✅ 👍

**Comment by tay-aitken** [comment]
✅ 👍

**Comment by tw15egan** [comment]
👍 ✅

**Pull request merged**
