### PR TITLE
rfc(themes): css custom properties

### PR DESCRIPTION
**Pull request by mattrosno**
This RFC builds on previous theming explorations (https://github.com/carbon-design-system/carbon/pull/3306) (https://github.com/carbon-design-system/carbon/pull/3502) (https://github.com/carbon-design-system/carbon/pull/3554) with the 
goal of aligning on Carbon's theming direction, including the detailed tasks to get there. 
Once alignment, turn this RFC into an epic - no merge intent.

# Background

A few relevant definitions and principles from
[About Carbon](https://www.carbondesignsystem.com/getting-started/about-carbon):

- Carbon is IBM's open-source design system for digital products and experiences
- Carbon's foundation is the IBM Design Language (IDL)
- Carbon's elements and components elegantly work together to ensure consistent,
  cohesive user experiences
- Carbon's modularity ensures maximum flexibility in execution

Carbon is a lot, but at the same time, an important distinction is that Carbon
is not a utility-first CSS framework. Carbon is uniquely positioned by the
guiding philosophy and principles of the IDL. Carbon is opinionated towards IDL
adherence but there are scenarios where "maximum flexibility in execution" is
needed via theming:

- End-user customization
- Incremental adoption strategies
- IBM brand variances
- IBM services and community adoption

# Tokens and variables

#### Design tokens

Carbon uses tokens to provide consistency and shared vocabulary between design
and development. Those tokens are often authored in JavaScript so they can be
shared across platforms, tooling, and assets.

#### Sass variables

Carbon elements and components implement those tokens through Sass variables.
These build-time tokens make dynamic and zoned theming difficult by having to
deal with complex Sass builds (and re-builds), increased specificities, CSS
de-duping, etc.

#### CSS variables

The `@carbon/themes` package has an option to emit CSS custom properties, but
that has yet to be implemented throughout the components. Being run-time, custom
properties open many doors for advanced theming. Going forward in this RFC we'll
reference custom properties as "CSS variables".

# Recommendation

There is no one single theming approach that will fit all needs; theming
strategy depends the application's user experience, browser support, etc. But,
with the guiding IDL and modern styling practices, we can provide multiple
theming options to achieve the desired outcome.

#### Global theming

Our global tokens should remain in our public Sass API. That provides the
baseline theming capabilities through a Sass build. By default (with the ability
to disable), certain token categories should be implemented as CSS variables to
accommodate common theming scenarios.

| Category   | Package             | Sass variables | CSS variables |
| ---------- | ------------------- | -------------- | ------------- |
| Colors     | `@carbon/themes`    | Yes            | Yes           |
| Icons \*   | `@carbon/icons`     | Yes            | Yes \*\*      |
| Shape \*\* | `carbon-components` | Yes            | Yes \*\*      |
| Typography | `@carbon/type`      | Yes            | Yes \*\*      |
| Grid       | `@carbon/grid`      | Yes            | No            |
| Layout     | `@carbon/layout`    | Yes            | No            |
| Motion     | `@carbon/motion`    | Yes            | No            |
| Spacing    | `@carbon/layout`    | Yes            | No            |

\* Inline icon size, maybe best set in `@carbon/type` so if overriding type
token font size, you could also easily override inline icon size too (e.g. 14px
font pairs with 16px icon, 16px font pairs with 20px icon, etc.)

\*\* New

#### Component theming

Carbon currently supports a mix of global and component tokens in
`_theme-tokens.scss`. To prevent an unmaintainable number of component tokens to
support various theming needs, the recommendation is that all component
variables are designated as private in our Sass API. Instead, encourage CSS
overrides to customize components (through CSS variables if possible) when the
customizations can't be handled by the global tokens.

#### Browser support

It's up to you how you want to handle IE11, as IE11 does not support CSS custom
properties. One option would be the
[css-vars-ponyfill](https://www.npmjs.com/package/css-vars-ponyfill), although
it has limitations like only supporting `:root` declarations.

Another option is to embrace graceful degradation where IE11 only gets the
build-time default theme.

Or, take a blended approach. For example, create a color theme through your Sass
build so IE11 picks up the color customizations, and a typography theme through
CSS variables that IE11 gracefully ignores.

# Tasks

Here's an initial list of high-level tasks that would need to be done to support
this theming strategy.

#### (1) Consolidate theming Sass map

The `@carbon/themes` has a mixin called `carbon--theme` that lets you set custom
color tokens, apply content, then reset the color tokens. E.g.:

```scss
@include carbon--theme($custom-theme-map) {
  @include button();
}
```

It would be great if the theming mixin supported all global token categories so
there was one way to override tokens > print styles > reset tokens in a Sass
build.

#### (2) Component entrypoint public mixins

Most, but not all, components have entrypoint mixins to prevent side-effects.
Every component needs a public entrypoint mixin, so you can use those in Sass
zoned themes. E.g.:

```scss
.my-dark-theme {
  @include carbon--theme($carbon--theme--g90) {
    @include accordion();
    @include button();
    @include breadcrumb();
  }
}
```

#### (3) Isolate component functions, mixins, variables

Related to (2), every component should have standardized `_functions.scss`,
`_mixins.scss`, and `_variables.scss` files that live alongside the rest of that
component's source. Isolating component styles will be necessary for future
component packages. This will clean up the `_theme-tokens.scss` to only global
tokens.

#### (4) Use CSS variables

Behind a feature flag that is defaulted to true, define all global CSS variables
on root. E.g.:

```scss
:root {
  --interactive-01: #0062ff;
  --interactive-02: #3d3d3d;
  --body-short-01-font-size: 0.75rem;
  --body-short-01-font-weight: 400;
  // couple hundred other variables
}
```

Then use the global CSS variables with appropriate fallbacks. E.g.:

```scss
.bx--btn--primary {
  background-color: #0062ff; // IE11 fallback
  background-color: var(--interactive-01);
}
```

Since the CSS variables are used at run-time, we'd need to namespace them to
prevent collisions. E.g. `--carbon-interactive-01`,

#### (5) New icon tokens

Inline icons are sized relative to font size. Currently, icons are hardcoded to
16px. If inline icons had a global token for size, they could easily be themed
alongside font-size customizations.

| Font size | Icon size |
| --------- | --------- |
| 14px      | 16px      |
| 16px      | 20px      |
| 20px      | 24px      |
| 24px      | 32px      |

#### (6) New shape tokens

One new global token that gets used on component elements that could receive a
non-zero border radius.

#### (7) PostCSS build

The idea is to identify CSS properties that would be good theming candidates:
`color`, `fill`, `background-color`, `margin`, `padding`, `border`, `height`,
`width`, `min-height`, `min-width`, `flex-basis` for starters.

With no changes to our SCSS source, we create unnamespaced CSS variables per
"themable property". This PostCSS build provided by Carbon. E.g. this:

```scss
.bx--element {
  color: $text-01;
  display: flex;
  padding: rem(6px) 0;
  transform: rotate(90deg);
}
```

Becomes:

```scss
.bx--element {
  --color: var(--text-01);
  color: #171717; // IE11 fallback
  color: var(--color);
  display: flex;
  --padding-top: 0.375rem;
  --padding-right: 0;
  --padding-bottom: 0.375rem;
  --padding-left: 0;
  padding: 0.375rem 0; // IE11 fallback
  padding: var(--padding-top) var(--padding-right) var(--padding-bottom) var(
      --padding-left
    );
  transform: rotate(90deg);
}
```

Unpacking this example: there is a build-time IE11 fallback. Color uses the
`text-01` global color token whose value would be its most immediate parent that
sets `--text-01`. That could be the page's root:

```scss
:root {
  --text-01: pink;
}
```

Or a zoned theme:

```scss
.my-pink-theme {
  --text-01: pink;
}
```

Also, properties could be set at the element level. E.g.:

```scss
.bx--element {
  --color: pink;
  --padding-right: 8px;
}
```

The theming mindset is that everything is a zone. That could be the entire page,
a container, or element. Theming at the element level feels very "CSS override",
but it allows ultimate flexibility and by using CSS variables, you could have
IE11 gracefully fall back to the default theme like any uses of page or
container-level themes.

#### (8) Document everything

Document everything from high-level theming strategy to technical approaches to
examples with pro/cons of each.

# Scenarios

TODO: Would it be helpful to provide examples and the pros/cons of each?

#### CSS variables

# Changed files

Files changed in this PR are for demonstration purposes only, so components are
built using CSS variables. The first commit demonstrates how you could apply an "editorial theme" to the accordion (larger font-sizes, icon size, paddings). https://deploy-preview-3705--carbon-components-react.netlify.com/?path=/story/accordion--default

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
@mattrosno Cool that you came up with a new RFC! One comment I have here is - Great that if we can separate scope and namespace of CSS custom properties from selectors. It means that CSS custom properties are defined in a similar manner to Sass variables. The former derived from the latter even.

**Comment by mattrosno** [comment]
> Great that if we can separate scope and namespace of CSS custom properties from selectors. It means that CSS custom properties are defined in a similar manner to Sass variables.

@asudoh is your comment on global variables or component variables?

**Comment by joshblack** [comment]
> Since the CSS variables are used at run-time, we'd need to namespace them to
prevent collisions. E.g. --carbon-interactive-01,

I'm curious if we need the namespace or not, would it really be that common for two parts of an HTML sub-tree to share the same CSS Custom Property but want their values to be different? If not, then one could imagine setting the variables on their respective roots instead of having to deal with namespace collisions.

> Inline icons are sized relative to font size. Currently, icons are hardcoded to
16px. If inline icons had a global token for size, they could easily be themed
alongside font-size customizations.

One thing I'd be curious about on the design side is how the type relates to the sizes, and what should happen if a type size doesn't map to one of the sizes given? Should it "round up/down" to the nearest icon size? Stuff like that would be great to codify, in particular as you suggested how they work along custom font-sizes (or even custom fonts).

> One new global token that gets used on component elements that could receive a
non-zero border radius.

Is there a way we can introduce this such that if your build is standard these result in no CSS being emitted?

> The idea is to identify CSS properties that would be good theming candidates:

Would it be worth pursuing the custom white-labelling step instead of trying to predict what folks might want to use?

**Review by joshblack — COMMENTED** [review]
Left a comment above ☝️

**Comment by mattrosno** [comment]
@joshblack thanks for the comments!

Namespacing CSS custom properties - this protects more against third-party libraries that also happen to use un-namespaced custom properties like `--focus` (one of our color tokens) where that would result in a collision. If their `--focus` is more specific than our `--focus`, the theme just went rogue.

Icon sizing - I'm all for codifying that relationship with font-size.

Border radiuses - if the concern is adding a bunch of `border-radius: 0;` in the default theme, I agree it makes sense to not emit unnecessary style "resets".

Themable properties - maybe we're thinking of the same thing. I'm hoping that subset of themable properties could be modified in the Sass build so we provide a default subset, but you can customize it if you want to expose more or fewer custom properties in your build.

**Comment by asudoh** [comment]
> @asudoh is your comment on global variables or component variables?

@mattrosno It's for both.

**Comment by mattrosno** [comment]
@asudoh do you have a recommendation? The RFC states:

> To prevent an unmaintainable number of component tokens to
support various theming needs, the recommendation is that all component
variables are designated as private in our Sass API. Instead, encourage CSS
overrides to customize components (through CSS variables if possible) when the
customizations can't be handled by the global tokens.

I'm proposing CSS variables get namespace and scope for global tokens only. For components, we don't namespace or scope so we can have them map directly to CSS property names, so we don't have to support component tokens in our public API.

**Comment by asudoh** [comment]
> To prevent an unmaintainable number of component tokens to
support various theming needs, the recommendation is that all component
variables are designated as private in our Sass API. Instead, encourage CSS
overrides to customize components (through CSS variables if possible) when the
customizations can't be handled by the global tokens.

Interesting, thank you @mattrosno for bringing up the reference. My question then is; what is the purpose of those private CSS custom properties? I'm asking this especially that component-specific theme tokens are for component-specific theming. Your response got me under an impression that your notion of component-level (private) CSS custom properties may be for a different purpose. My apologies if I'm totally mistaken.

**Comment by mattrosno** [comment]
> My question then is; what is the purpose of those private CSS custom properties?

@asudoh we would need to add and maintain hundreds of component-level tokens (public Sass variables) to support the four theming scenarios presented at the top of this RFC. Our `_theme-tokens.scss` currently has 57 pubic Sass variables. In comparison, [Bootstrap](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss) has close to 400 for a smaller number of overall components.

As Carbon is not a CSS utility-first framework, I'm suggesting that those 57 Sass variables (component tokens) become private so they can still be used in Carbon's default build and we don't add more. Our global tokens remain public. If a user wants to theme a component in a way that can't be handled by global token changes, then they use CSS class name overrides.

The goal here is to make IBM Design Language adherence easy, but provide a documented way to deviate (theme) when necessary. I'd like to not add ~400 component tokens to our public API to support such theming. That's why I'm recommending that our global tokens are public, and component tokens are private.

**Comment by scottnath** [comment]
Hey @mattrosno 

Does this mean that the official stance of Carbon will be that the only way to do white-labeling (component-level theming) is via CSS overrides?

Does this also mean that Carbon is officially not going to support the requested flexibility for white-labeling/blue-washing for IBM BUs?

Not adding these tokens forces Carbon add-on libraries and offerings to continue copy/pasting styles, making it difficult to ensure conformity to the IDL. Is Carbon officially not supporting style extensions in add-ons?

**Comment by mattrosno** [comment]
Hi @scottnath can you share an example BU white-label / blue-wash theme (visuals)? With that I'd be happy to share an estimate on what percentage of the theme could be done with zoned global token overrides vs CSS overrides.

**Comment by asudoh** [comment]
@mattrosno From your demo in our meeting, I got an impression that your "private" word is more of scoping CSS custom properties in component selectors (rather than not allowing consumer to change the values). Is it correct?

**Comment by elizabethsjudd** [comment]
@mattrosno @shinytoyrobots Following up on Scott's comment, the lack of flexibility in Sass has been a large pain point for adopting Carbon across Watson Health.  Because of the proprietary nature of the offerings, I can't share examples in public GH but I have uploaded some examples behind the IBM firewall that can be viewed here: https://github.ibm.com/Watson-Health/design-library/issues/4112#issuecomment-13867932

WH has been told multiple times that Carbon is the one design system for **ALL** IBM offerings and we should be using Carbon for all new development. If this is not the case and Carbon does not expect to support this type of development, _it needs to be documented_ so that when offerings need to use a different method they have a place to point to for justifying their reasons. Having a flexible structure does not mean that the main focus for styling can't be to provide styles that align to IDL, it means that the underlining code has the flexibility to support the requirements of the users.

Carbon actively promotes that developers/designers extend what the core team provides as the core team can not be expected to own and maintain every component needed by all IBM BUs, especially when some are BU specific. This philosophy combined with the contribute-to model used by Carbon should allow IBM users the ability to externally extend as well as contribute flexibility back to the system so that Carbon can support their needs. Here are some examples of where WH had to copy and paste styles from Carbon in order to extend flexibility needed for our users: [extensions.scss.zip](https://github.com/carbon-design-system/carbon/files/3507560/extensions.scss.zip)

**Comment by mattrosno** [comment]
Hi everyone - I built a themed page with three different approaches.

https://github.com/carbon-design-system/carbon-app-themed/pull/1

https://github.com/carbon-design-system/carbon-app-themed/pull/2

https://github.com/carbon-design-system/carbon-app-themed/pull/3

I believe the third approach to be on track for what we're after. Feel free to comment here or in those PRs. We'll provide an update as theming makes its way into the October release.

**Comment by asudoh** [comment]
Thanks @mattrosno for gathering the proposals - Do you have quick list of pros/cons for each approaches?

**Comment by mattrosno** [comment]
> Do you have quick list of pros/cons for each approaches?

@asudoh I don't - PRs are self-contained with such information.

**Comment by asudoh** [comment]
@mattrosno I saw each PRs are packed with lots of information and had a hard time reading it through, and wanted to see a hint for better reading. That's why I would have liked a quick comparison. Hope this makes sense to you - Thanks!

**Comment by joshblack** [comment]
Thanks for doing this again, @mattrosno! Gonna close this with the theming project finally kicking off 👀

**Pull request closed without merging**
