### PR TITLE
feat(Skeleton-states): Add skeleton state styles

### PR DESCRIPTION
**Pull request by alisonjoseph**
## Overview

Ref https://github.ibm.com/carbon/issues/issues/614
Ref https://github.ibm.com/carbon/issues/issues/559
Ref https://github.com/carbon-design-system/carbon-components/issues/470

Skeleton state styles

### Added

Skeleton state mixin, skeleton state styles 
Skeleton state demo html (for components that work in vanilla library)

## Testing / Reviewing

Review components listed here. 
[http://localhost:3000/demo/skeleton](http://localhost:3000/demo/skeleton) 
**Note: background color(s) aren't final, needs design review/input**
(react staging url for skeleton states carbon-storybook-interciliary-isooctane.stage1.mybluemix.net)

**Make sure no components are broken**

## Component List
✅Has working skeleton state
🔶Animation doesn't run on form elements, skeleton state is just a light blue square, user could manually update html instead of just adding the skeleton class to achieve the required effect. 
❌No skeleton state

|                    |                                                                           |       | 
|--------------------|---------------------------------------------------------------------------|-------| 
| Component          | Vanilla                                                                   | React | 
| Skeleton Text      | ✅                                                                         | ✅     | 
| Button             | ✅                                                                         | ✅     | 
| Label              | ✅                                                                         | ✅     | 
| Textarea           | 🔶                                                                        | ✅     | 
| Text input         | 🔶                                                                        | ✅     | 
| Number Input       | ✅                                                                         | ✅     | 
| Date Picker        | 🔶                                                                        | ✅     | 
| Search             | 🔶                                                                        | ✅     | 
| Radio Button       | 🔶                                                                        | ✅     | 
| Checkbox           | 🔶                                                                        | ✅     | 
| Data Table         | ❌(can add skeleton state manually to individual content inside component) | ✅     | 
| Breadcrumb         | ✅                                                                         | ✅     | 
| Accordion          | ❌(can add skeleton state manually to individual content inside component) | ✅     | 
| Code Snippet       | ❌(can add skeleton state manually to individual content inside component) | ✅     | 
| Content Switcher   | ❌(can add skeleton state manually to individual content inside component) | ❌     | 
| Dropdown           | ✅                                                                         | ✅     | 
| Progress Indicator | ✅                                                                         | ✅     | 
| Toggle             | ✅                                                                         | ✅     | 
| Small Toggle       | ✅                                                                         | ✅     | 
| Slider             | ✅                                                                         | ✅     | 
| Tag                | ✅                                                                         | ✅     | 
| Tabs               | ✅                                                                         | ✅     | 
| Pagination         | ❌(can add skeleton state manually to individual content inside component) | ✅     | 
| Icon               | ✅                                                                         | ✅     | 
| Structured List    | ❌(can add skeleton state manually to individual content inside component) | ✅     | 
| Don't use skeleton |                                                                           |       | 
| Loading            | ❌                                                                         | ❌     | 
| Notification       | ❌                                                                         | ❌     | 
| Modal              | ❌                                                                         | ❌     | 
| Tooltip            | ❌                                                                         | ❌     | 
| Overflow Menu      | ❌                                                                         | ❌     |

### CODE REVIEW

**Review by marijohannessen — APPROVED** [review]
This looks so good! 👍 🎉

**Review by tw15egan — APPROVED** [review]
This looks awesome! Nice work @alisonjoseph

**Review by asudoh — APPROVED** [review]
LGTM 👍 once our designers sign off (it may have been done already) - Thanks @alisonjoseph for completing this work!!

**Comment by alisonjoseph** [comment]
Thanks for reviewing! Just want to get final approval from @tay-aitken and @aagonzales before we merge it in. 😄

**Comment by tay-aitken** [comment]
@alisonjoseph looks good to me. My only request is on data tables the skeleton part is moved down to the first row as opposed to the header. The column names shouldn't need a skeleton state since they arent pulling in data. 

Other than that good to go ✅ 👍

**Review by tay-aitken — APPROVED** [review]

**Pull request merged**
