### PR TITLE
fix(tabs): use padding instead of margin

### LINKED ISSUE #1970: Tabs margin-left causes overflow
## Detailed description

> Describe in detail the issue you're having.

.#{$prefix}--tabs__nav in _tabs.scss adds margin-left when tabs component is small, this causes the component to overflow out of the parent

> Is this issue related to a specific component?

tabs

> What did you expect to happen? What happened instead? What would you like to see changed?

Not sure why margin-left and margin-right is set for this specific size (768-1200px) in the first place. I think it would make sense to just remove them. However if we want to keep the same behaviour I think using padding instead would be appropriate.

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

8.18.0

## Steps to reproduce the issue

1. Go to CodeSandbox and change screen size so that screen width is between 768 and 1200 px, you'll see a horizontal scroll bar which indicates the overflow.

https://codesandbox.io/s/r5263v3ljm

screen shot 2019-03-02 at 6 54 56 pm

### PR DESCRIPTION
**Pull request by ivanzvonkov**
Closes #1970 

Replaced margin with padding in nav-bar to not cause overflow on smaller screen sizes.

#### Testing / Reviewing
Can be tested with storybook in #1970

### CODE REVIEW

**Comment by asudoh** [comment]
Hi :wave: thank you for reporting! Have you tried applying `display: flex` or `display: inline-block` to `<div id="root">`?

**Comment by ivanzvonkov** [comment]
@asudoh Hi! Your suggestion does fix the issue, however, I think the PR still stands as it fixes the issue more directly. Is there any particular reason the margin-left is there in the first place?

**Comment by asudoh** [comment]
Looks that the `margin` approach is there from the beginning (`v6`). @jnm2377 @tw15egan - Any thoughts on this? Thanks!

**Comment by jnm2377** [comment]
Hmm.. I'm not sure if there was a specific reason for doing it that way in v9. I do know that margin and padding were both removed in v10. Design wise, it doesn't seem to be breaking anything, so I think it should be fine to merge.

**Review by jnm2377 — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
OK let's move forward as there seems no objection. Thanks @ivanzvonkov!

**Pull request merged**
