### PR TITLE
feat(date-picker): add style for date picker with time picker

### PR DESCRIPTION
**Pull request by yasotnik**
Closes IBM/carbon-components-react#1140

Style fix for date picker with time picker.
This PR is directly connected to https://github.com/IBM/carbon-components-react/pull/1704

#### Changelog

**New**

- Add style fix for date picker with time picker.

#### Testing / Reviewing

Should be checked _**only**_ with new js code for react _DatePicker_ from another PR.

image

### CODE REVIEW

**Comment by aagonzales** [comment]
I do not see the variation in the preview link.

**Comment by asudoh** [comment]
Great point @aagonzales! @yasotnik Can you do a couple of things?

1. Host a demo of your code somewhere and put a link in here
2. Create an experimental version of CSS (one in `@mixin date-picker--x`), too - You can test your experimental CSS by clicking on the toggle button at the top right in dev env

Thanks!

**Comment by joshblack** [comment]
Hi @yasotnik! 👋 Just wanted to follow up on @asudoh's comments. Are you still interested in working on this PR? Would love to see this get merged in!

**Comment by yasotnik** [comment]
Hey, @joshblack 
For now our team found a workaround for this issue. I do not think that I will have some time in near future to fix that. Have a tight deadline 😢  
Sorry.

**Comment by asudoh** [comment]
Thanks @yasotnik for your reply - Let me close this given that, feel free to let us know anytime you want to restart the effort!

**Comment by mrinasugosh** [comment]
@asudoh I would like to restart the effort around adding a time picker to the date picker...Is that still a possibility?

**Comment by asudoh** [comment]
I think it depends on if you can come up with a UI that our designers can agree with, but if you think you can, I think it's worth trying.

**Pull request closed without merging**
