### PR TITLE
fix(tooltip): unable to control using open prop

### LINKED ISSUE #2849: Tooltip - unable to control using *open* props
## What package(s) are you using?
Same happens also for version *6.x*:
Screenshot 2019-05-28 at 12 47 46

- [ ] `carbon-components`
- [ x] `carbon-components-react`

## Detailed description

Unable to control visibility state of the Tooltip (open/close), using already existing *open* prop. It could be easy observed using provided codesandbox.

Screenshot 2019-05-28 at 12 50 37

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
We need this functionality in IBM SPSS Statistics. Tooltips are the last components we are trying to migrate from ap-components-react to Carbon.

## Steps to reproduce the issue

1. Assign Tooltip *open* prop to state variable (e.g. showTooltip).
2. Change value of state variable (true->false, false->true)
3. Result: Tooltip doesn't react on changes on *open* prop.

*Expected:* Tooltip will react on change for *open* prop

> Please create a reduced test case in CodeSandbox
https://codesandbox.io/embed/codesandbox-lo5ox

Issue exists on both carbon-components-react versions 6.x and 7.x.
We are expecting a fix for version 6.x.

It's a *blocking issue* for us.

### PR DESCRIPTION
**Pull request by tomkdgun**
Fixes #2849

Making open prop single source of truth.

#### Changelog

**Changed**

- Tooltip.js

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thank you for writing up a PR. Seems that this change forces `open` from the prop whenever it's different from one in state without detecting the change in that prop, and thus it's a breaking change. You may be interested in introducing a "controlled mode" (behind feature flag), where the code simply reads one from prop whenever `props.open` is non-`undefined`.

**Comment by tomkdgun** [comment]
@asudoh If **open** prop doesn't change e.g. is true, tooltip should be always opened, regardless of internal click handling.
If we want to have something which only control initial open state, it should be named, **initiallyOpen**, and handled in constructor, not in getDerivedStateFromProps.

**Comment by emyarod** [comment]
this should be addressed by https://github.com/carbon-design-system/carbon/pull/3357

**Comment by asudoh** [comment]
Superseded by: #3357

**Pull request closed without merging**
