### PR TITLE
fix(Modal): render correct backgrounds for NumberInput on Modal (#12230)

### PR DESCRIPTION
**Pull request by nelsonchen90**
* fix(Modal): render correct backgrounds for NumberInput on Modal

* chore(modal): remove numberinput example

Closes https://github.com/carbon-design-system/carbon/issues/12229

#### Changelog

**Changed**

- Added more overrides to Modal to properly style form elements, in this case the NumberInput controls

#### Testing / Reviewing

This is a cherry pick to v10, refer to the #12230

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by alisonjoseph — APPROVED** [review]

**Comment by nelsonchen90** [comment]
@tw15egan thanks for updating the PR. it's interesting to see why it's happening in this pr but not fixed earlier?

**Comment by tw15egan** [comment]
@nelsonchen90 I think it's because our a11y tests pull the latest deployment, and we haven't had a PR on the V10 branch since the new ruleset was released.

**Comment by nelsonchen90** [comment]
@tw15egan would there be any chance we can publish a new version today to include this fix?

**Comment by tw15egan** [comment]
cc @carbon-design-system/release

**Comment by nelsonchen90** [comment]
@tay1orjones seems like the release failed. can you check?

**Comment by tay1orjones** [comment]
@nelsonchen90 The release was successful, it's just the sketch plugin asset that failed to upload to the github release. `carbon-components-react@7.59.7` was published just fine

**Pull request merged**
