### PR TITLE
fix(DataTable): prevent overlap with sortable selection table

### LINKED ISSUE #11356: [Bug]: Sortable data table with selection - column header hover overlaps with checkbox
### Package

@carbon/react, @carbon/styles, carbon-components, carbon-components-react, @carbon/colors, @carbon/elements, @carbon/grid, @carbon/icons, @carbon/themes

### Browser

Chrome

### Package version

v10

### Description

When hovering over the first column header in a selectable, sortable data table, the hover color extends to far to the left, overlapping with the top left checkbox. The same is true of the focus state. It looks like this is no longer an issue in v11.

### Screenshots

Screen Shot 2022-05-06 at 10 44 16 AM
Screen Shot 2022-05-06 at 10 44 24 AM

### Steps to reproduce

These screenshots were taken from the live demo of the data table in v10: https://v10.carbondesignsystem.com/components/data-table/usage/

Data table must be selectable and sortable (it is the sort capability that activates a hover state for each column header).

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/11356

Fixes an issue so that when the screen size is reduced, the sortable header does not overlap the checkbox.

image

image

#### Changelog

**Changed**

- Changed the Checkbox column `width` to a `min-width`

#### Testing / Reviewing

Go to DataTable --> Selection --> With Selection and Sorting and reduce the screen size. The Sort header should not overlap the checkbox when hovered or focused.

### CODE REVIEW

**Review by dakahn — APPROVED** [review]

**Review by tay1orjones — COMMENTED** [review]
@tw15egan Any idea why the VRT tests in Percy are showing a change in spacing for tables with radio button selection? I'd think this change would be isolated to the checkbox only, but maybe the classes are reused? [Here's a direct link](https://percy.io/538fc19a/Carbon-Monorepo-/builds/19446932/changed/1092219337?browser=chrome&browser_ids=23&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1366&widths=360%2C1366) to a diff in percy of it

image

**Comment by tw15egan** [comment]
@tay1orjones looks like the classes are reused

Screen Shot 2022-07-08 at 8 29 20 AM

**Comment by tw15egan** [comment]
@tay1orjones is there anything we wanted to do with this, or is this okay?

**Review by tay1orjones — APPROVED** [review]
@tw15egan Sorry I missed your last comment, looking at this again I think it's good. The percy diff just threw me off with invalid concern.

**Pull request merged**
