### PR TITLE
feat(pictograms): add four new pictograms to education category

### PR DESCRIPTION
**Pull request by dudley-ibm**
Closes #

{{closes enterprise issue #6 add 4 pictograms}}

#### Changelog

**New**

- {{focus.svg
goals.svg
growth.svg
insights.svg}}

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
updated snapshots, looks good to me once CI passes

**Comment by dudley-ibm** [comment]
@tw15egan @joshblack after I created this PR, I was asked to change the name of one of the SVGs. The previously submitted `focus.svg` needs to be `feedback--02.svg`-- this would require me to remove `focus.svg` because that SVG has layers in it that also say `focus`. What's the easiest way to make this swap at this stage of the pull request?

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Hey @dudley-ibm! 👋  Feel free to rename focus.svg to whatever the preferred name would be! Since you are adding this in this PR, and it's not in the library yet, there's also no need to worry about the deprecation flow and you can just make the changes directly.

**Comment by tw15egan** [comment]
@dudley-ibm I've goen ahead and updated `focus` to `feedback--02`. This included:

- Updating `pictograms.yml`
- Updating `categories.yml`
- Changing the `svg` name in the `src` directory, as well as editing the `id` of the actual `svg` element

Let me know if this is what you had intended to change 👍

**Comment by dudley-ibm** [comment]
Thanks @tw15egan! Here's what I was trying to accomplish:

1. Downloadable file from IDL should be the asset I provide. For a while @joshblack made that happen but in this last release of pictograms, that is not the case (attachment, see pasteboard size difference/layer naming). 
2. In submitted SVG, the artwork lives on a layer that has a matching name to the file itself. Wasn't sure how to accomplish that through the UI without flat out replacing the file.
3. All this may be moot with the upcoming replacement files that will be outlined (not stroked) and a 32x32px paste
board instead of 48x48px.


svg_carbon_discrepancy

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
