### PR TITLE
fix(multiselect): listbox hidden when closed

### LINKED ISSUE #11341: [a11y]: MultiSelect - The descendent <div> element with "option" role has no focusable child element
### Package

carbon-components-react

### Browser

Chrome, Firefox

### Operating System

MacOS

### Package version

v7.52.x (~7.52.0)

### React version

v17.x.x (^17.0.2)

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker - Latest Deployment

### Assistive technology

_No response_

### Description

1. Go to the [MultiSelect default storybook](https://react.carbondesignsystem.com/?path=/story/components-multiselect--default)
2. Open the MultiSelect (use inspect element on one of the entry to open DevTools without closing the menu)
3. Scan with IBM Equal Access Accessibility Checker (while the MultiSelect is opened)
4. You get the following accessibility violation:
   - `2.1.1 Keyboard: The descendent <div> element with "option" role has no focusable child element`

The error comes from the fact that the div that encompasses the different values has `tabindex="-1"` and the children elements don't define `tabindex` so they are considered not focusable by the accessibility checker.

Note: I'm still able to navigate through the elements using keyboard.

Screenshot 2022-05-04 at 10 58 51

### WCAG 2.1 Violation

Criterion 2.1.1: Keyboard

### CodeSandbox example

https://react.carbondesignsystem.com/?path=/story/components-multiselect--default

### Steps to reproduce

I'm not able to reproduce from the CodeSandbox, I don't understand why... but the storybook does have the same error we have.

1. Go to the [MultiSelect default storybook](https://react.carbondesignsystem.com/?path=/story/components-multiselect--default)
2. Open the MultiSelect (use inspect element on one of the entry to open DevTools without closing the menu)
3. Scan with IBM Equal Access Accessibility Checker (while the MultiSelect is opened)
4. You get the following accessibility violation:
   - `2.1.1 Keyboard: The descendent <div> element with "option" role has no focusable child element`

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #11341 

#### Changelog

- make listbox menu hidden in the a11y tree when multiselect is closed

#### Testing / Reviewing

- go to multiselect storybook and run the a11y checker on the closed menu
    - this a11y warning should no longer appear
    Screen Shot 2022-08-11 at 4 28 39 PM

- ensure all tests are passing and component is working as expected

### CODE REVIEW

**Comment by tw15egan** [comment]
I seem to be still seeing the issue when the Multiselect is open

Screen Shot 2022-08-12 at 10 05 31 AM


>Go to the [MultiSelect default storybook](https://react.carbondesignsystem.com/?path=/story/components-multiselect--default)
Open the MultiSelect (use inspect element on one of the entry to open DevTools without closing the menu)
Scan with IBM Equal Access Accessibility Checker (while the MultiSelect is opened)
You get the following accessibility violation:
`2.1.1 Keyboard: The descendent <div> element with "option" role has no focusable child element`

**Comment by dakahn** [comment]
This might be fine as-is. While the multi select is _technically_ visible in the accessibility tree, it's not actually accessible until the user opens it up. This could be a case of IBM Accessibility Checker just being a little too thorough fwiw

**Comment by jnm2377** [comment]
@tw15egan @dakahn this is ready for re-review. I added a tab index of -1 to the listbox menu item component bc the same accessibility error was present in Dropdown which also uses this component. ComboBox uses it as well, however, we added tabIndex -1 to that component so it wasn't failing a11y checker. So this change just adds it to all menu items by default. The components should all still work as expected.

**Review by dakahn — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
Not seeing the violation anymore, nice work 🔥

**Pull request merged**
