### PR TITLE
refactor(DropdownSkeleton): convert DropdownSkeleton to TypeScript

### LINKED ISSUE #12543: Add TypeScript types to DropdownSkeleton

### PR DESCRIPTION
**Pull request by lewandom**
Closes #12543.

Convert React DropdownSkeleton component to .tsx to add TypeScript support.

#### Changelog

**New**

- added DropdownSkeletonProps interface

**Changed**

- converted DropdownSkeleton component to TypeScript format (.tsx)

#### Testing / Reviewing

The DropdownSkeleton component imports for the storybook should be valid and rendering. In a TypeScript environment, you should be able to import and reference the DropdownSkeleton component and its typings (DropdownSkeletonProps).

### CODE REVIEW

**Comment by lewandom** [comment]
@francinelucca @tay1orjones would you mind taking a look at this PR? Seems to be sitting quite a while here.

**Review by francinelucca — APPROVED** [review]
LGTM

**Comment by tw15egan** [comment]
@lewandom Looks good, but there are some merge conflicts to resolve first

**Comment by lewandom** [comment]
@tw15egan resolved.

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
