### PR TITLE
fix(SideNav): disregard hover on non-rail SideNav when closed

### LINKED ISSUE #3710: SideNav does not collapse when it should
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

This is a corner case: on a large viewport, the SideNav is always collapsed per default, but with a combination of resizing and actions, you can have it displayed it anyway.

> What did you expect to happen? What happened instead? What would you like to
> see changed?

SideNav shall always be hidden per default on large viewports, even if it is in state expanded or hover.
```SCSS
  .#{$prefix}--side-nav:not(.#{$prefix}--side-nav--fixed):hover,
  .#{$prefix}--side-nav--expanded {
    width: mini-units(32);
  }
``` 

> What version of the Carbon Design System are you using?

10.4

## Steps to reproduce the issue

Example app on: https://jtrzb.csb.app/#/

Test with `expanded`:
1. Reduce the browser window (viewport) width so that the HeaderMenuButton displays on the top-left corner:
image
2. Click on the HeaderMenuButton , the SideNav opens:
image
3. Enlarge the window width again. The HeaderMenuButton and the overlay collapse, but the SideNav remains, and hides the content:
image

Test with `:hover`:
1. Same as 1. above
2. Same as 2. above. Notice that the current active Element is the HeaderMenuButton, which now displays as a cross
3. Put the mouse cursor (not displayed on the screenshot below) over SideNav link "One":
image
4. Without moving the mouse cursor, press the Enter-key, which "clicks" on the cross:
image

Responsible seems to be in _side_nav.scss line 113:

> Please create a reduced test case in CodeSandbox

Cose in CodeSandbox: https://codesandbox.io/s/sidenavissues-jtrzb

## Additional information

- Screenshots or code: see above.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3710
Ref #3626

This PR avoids keeping the (non-rail variant) sidenav in the expanded state on hover after it has been collapsed

#### Changelog

**New**

- rail variant specific tests

**Changed**

- specify rail variant hover width
- default non-rail event handler assertions
- test markup to avoid passing nonstandard attributes to DOM elements

#### Testing / Reviewing

Ensure all side nav variants behave as expected

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]

**Comment by aagonzales** [comment]
I'm having a hard time discerning what's changed. I've compared it when the currently deployed version and I'm not seeing a visual or interactive difference. Is that intended or is there a visual/interaction change somewhere I'm missing.

**Comment by tw15egan** [comment]
@aagonzales if you follow the instructions in the original issue to see what's changed

Screen Shot 2020-03-09 at 3 16 36 PM

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by emyarod** [comment]
@aagonzales to add on to @tw15egan's comment, there is a 2nd case to test as well (both are from the linked issue):

image

**Review by aagonzales — APPROVED** [review]
I went over this in person with Andrew, looks good to me!

**Review by aledavila — APPROVED** [review]

**Comment by asudoh** [comment]
@emyarod told me that this is ready to merge - Thanks @emyarod!

**Pull request merged**
