### PR TITLE
fix(data-table-v2): revert table-header-label class name

### PR DESCRIPTION
**Pull request by joshblack**
Removes usage of `table-header-label`.

#### Changelog

**New**

**Changed**

- Remove usage of `bx--table-header-label`

**Removed**

### CODE REVIEW

**Review by aledavila — APPROVED** [review]
lgtm

**Review by lovemecomputer — APPROVED** [review]
👍🏻

**Comment by jnm2377** [comment]
Is there a specific reason we can't have these? Since it's an existing class I've used it as a selector in v10 changes, especially in truncated table styles/js.

**Comment by joshblack** [comment]
@jnm2377 it most likely was something in the markup for inline editing for truncation purposes. However, it's important to note that there are no associated styles with this class name in v9. This PR exists to revert the usage in preference of keeping existing v9 markup or behavior where applicable 👍  I think we'll want to add this feature in, but it should have defined scope and come in with v9 and potentially inline edit styles.

**Comment by joshblack** [comment]
bump @jnm2377, should we address this before #2176?

**Pull request closed without merging**
