### PR TITLE
fix(accordion): minor UI changes

### PR DESCRIPTION
**Pull request by asudoh**
Refs #1671.

#### Changelog

**Changed**

- Focus outline on expand button instead of on chevron
- Expand button's padding from `7px` to `6px`

#### Testing / Reviewing

Testing should make sure accordion is not broken.

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
cc @laurenmrice if you have time to review 👍

**Review by emyarod — APPROVED** [review]

**Review by laurenmrice — COMMENTED** [review]
Looks good. But one thing I did notice on the focus states is that the blue outline is within the two line dividers of each row. When the focus is activated, the lines for that row should not be visible.
screen shot 2019-01-24 at 9 46 55 am

**Comment by joshblack** [comment]
cc @asudoh how should we track the design feedback for accordion? Should we just do another issue?

**Comment by asudoh** [comment]
@joshblack The issue this PR refers to hasn't been closed - And thus let's track @laurenmrice's above point there. And good point offline that we need to make sure designers' feedback won't be lost.

**Pull request merged**
