### PR TITLE
fix(a11y): Increase Windows / Firefox HCM support

### LINKED ISSUE #6471: Checkbox focus outline not visible in high contrast mode
## Environment

> OS

Windows 10 etc.

> Browsers

IE11, Edge Chromium, Firefox

> Settings

High Contrast Theme #1 enabled

## Detailed description

> What version of the Carbon Design System are you using?

10.14

> What did you expect to happen?

To see a focus outline on the checkbox, like when high contrast mode is disabled.

> What happened instead?

No focus outline.

> What WCAG 2.1 checkpoint does the issue violate?

https://www.w3.org/WAI/WCAG21/Understanding/focus-visible.html

## Steps to reproduce the issue

The problem is not specific to react but you can see it at https://react.carbondesignsystem.com/?path=/story/checkbox--checked.

## Additional information

Here's what it looks like, regardless of whether or not it's focused:

Screen Shot 2020-07-15 at 15 32 26

The problem  is that the focus outline is rendered via `box-shadow` rather than outline:

```
  // Unchecked
  .#{$prefix}--checkbox:focus + .#{$prefix}--checkbox-label::before,
  .#{$prefix}--checkbox-label__focus::before,
  // Checked
  .#{$prefix}--checkbox:checked:focus + .#{$prefix}--checkbox-label::before,
  .#{$prefix}--checkbox-label[data-contained-checkbox-state='true'].#{$prefix}--checkbox-label__focus::before,
  // Indeterminate
  .#{$prefix}--checkbox:indeterminate:focus + .#{$prefix}--checkbox-label::before,
  .#{$prefix}--checkbox-label[data-contained-checkbox-state='mixed'].#{$prefix}--checkbox-label__focus::before {
    // Must use box-shadow for appearance of multiple borders with rounded corners.
    box-shadow: 0 0 0 2px $inverse-01, 0 0 0 4px $focus;
  }
```

The obvious fix is to use `outline` instead of `box-shadow` but assuming there's some reason you aren't doing that already, a possible alternative fix is:

```
@media screen and (-ms-high-contrast: active) {
	// Unchecked
	.#{$prefix}--checkbox:focus + .#{$prefix}--checkbox-label::before,
	.#{$prefix}--checkbox-label__focus::before,
	// Checked
	.#{$prefix}--checkbox:checked:focus + .#{$prefix}--checkbox-label::before,
	.#{$prefix}--checkbox-label[data-contained-checkbox-state='true'].#{$prefix}--checkbox-label__focus::before,
	// Indeterminate
	.#{$prefix}--checkbox:indeterminate:focus + .#{$prefix}--checkbox-label::before,
	.#{$prefix}--checkbox-label[data-contained-checkbox-state='mixed'].#{$prefix}--checkbox-label__focus::before {
		outline: 1px solid highlightText;
		outline-offset: 2px;
	}
}
```

### LINKED ISSUE #6748: Icon Only Ghost Button and Radio selection dots are invisible in Windows High Contrast
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

With Windows10's High Contrast mode enabled, using the Edge (Chromium) browser, the Icon in the Icon only Ghost button is not visible. Similarly, the dot in a Radio button is not visible either.
This can be observed at the sample: https://www.carbondesignsystem.com/components/button

> Is this issue related to a specific component?

Button and Radio Button 

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected to see the icon in the Icon Only button, and the dot in the selected radio button

> What browser are you working in?

Identified on the Edge (Chromium) browser, version 85.0.564.41 (Official build) (64-bit)

> What version of the Carbon Design System are you using?

Going to assume the latest because I reproduced it on the Sample ages.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

WFfH Application Framework, expecting to complete our first ACS certification by the end of September. Which this will impact.

## Steps to reproduce the issue

1. Step one
Enable Windows 10's High Contrast mode

2. Step two
Launch (Edge Chromium) and navigate to the Live Demo section of the Button sample:, https://www.carbondesignsystem.com/components/button/usage/#live-demo

3. Step three
From the type menu change Button to Icon Only.
Set the Kind to Ghost.

This will demonstrate both the invisible icon and the radio button's dot.

## Additional information

- Screenshots

### LINKED ISSUE #6755: In Windows High Contrast Select's list has no border and the chevron is difficult to see
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

The attached annotated screenshot demonstrates the observations.

With Windows High Contrast enabled, the Selector's opened list has no border, this **may** look to some users that the content of the select are part of the element behind the select (for example contents of a cell in a table).

The Select's chevron is a very dark grey, almost impossible to see against the black background. Should it take on the same colour as the rest of the Select's styling (in my HC config from the screenshot that would be Yellow). Without the chevron being obvious, the select could be mistaken for a regular button.

The Chevron does become visible when choosing either of the two dark grey themes, but that's only because the chevron is a light grey from the theme rather than taking on the HC styling.

> Is this issue related to a specific component?

Select https://www.carbondesignsystem.com/components/select/usage

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Could a visible border be placed on the select list to help put context on the items in the list relative to what's behind.
Could the chevron be styled so that it's visible without having to change the theme?

> What browser are you working in?

Identified on the Edge (Chromium) browser, version 85.0.564.41 (Official build) (64-bit)

> What version of the Carbon Design System are you using?

Assuming the latest because I reproduced it on the Sample pages.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

WFfH Application Framework, expecting to complete our first ACS certification by the end of September. Which this will impact.

## Steps to reproduce the issue

1. Step one
Enable Windows 10's High Contrast mode

2. Step two
Launch (Edge Chromium) and navigate to the Live Demo section of the Select sample: https://www.carbondesignsystem.com/components/select/usage#live-demo

3. Step three
Examine the Chevron, it will be there, but very difficult to see.
Open the list, there will be no border.

## Additional information

- Screenshots: 

This screenshot is heavily annotated, hopefully it'll be clear enough. One thing to call out is in the top right corner is an example of a select we're using from the Pagination, it opens over a table and initially looks like the elements in the list are part of the cells in the table behind.

### LINKED ISSUE #6767: In Windows High Contrast the Pagination's Next and Previous buttons are difficult to see
- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

With Windows10's High Contrast mode enabled, the Pagination Control's Next and Previous buttons are difficult to see.
In the Disabled, Hovered and resting states the borders don't surround the buttons. They just present on the left edge.
In Disabled, the icon in the button is visible, but in all other states it is almost impossible to see.

Also noticed that the tooltip is disconnected from its anchor, and is aligned to the left of the button it belongs too.
I've seen this elsewhere, so likely a separate problem?

> Is this issue related to a specific component?

Pagination

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Expected to see the buttons outlined so that they can easily be identified as buttons.

> What browser are you working in?

Identified on the Edge (Chromium) browser, version 85.0.564.41 (Official build) (64-bit)

> What version of the Carbon Design System are you using?

Assuming the latest because I reproduced it on the Sample pages.

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

WFfH Application Framework, expecting to complete our first ACS certification by the end of September. Which this will impact.

## Steps to reproduce the issue

1. Step one
Enable Windows 10's High Contrast mode

2. Step two
Launch (Edge Chromium) and navigate to the Live Demo section of the Pagination sample: https://www.carbondesignsystem.com/components/pagination/usage#live-demo

3. Step three
Examine the Next and Previous page buttons' states to observe the styling.

## Additional information

- Screenshots or code

### LINKED ISSUE #6859: Slider is inaccessible in Windows High Contrast Mode
The slider component is not accessible with Windows High Contrast Mode enabled in either Firefox or Edge.

## Environment

> Operating system

Windows 10

> Browser

Firefox, Edge

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

image

### LINKED ISSUE #6862: Modal close button is not accessible in Windows High Contrast Mode
The Modal close button is not accessible with Windows High Contrast Mode enabled in either Firefox or Edge.

## Environment

> Operating system

Windows 10

> Browser

Firefox, Edge

> Assistive technology used to verify

Windows High Contrast Mode

## Detailed description

image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6859 [Slider]
Closes https://github.com/carbon-design-system/carbon/issues/6767 [Pagination]
Closes https://github.com/carbon-design-system/carbon/issues/6471 [Checkbox]
Closes https://github.com/carbon-design-system/carbon/issues/6862 [Modal]
Closes https://github.com/carbon-design-system/carbon/issues/6748 [Radio Button]
Closes https://github.com/carbon-design-system/carbon/issues/6755 [Select]

Adds in Windows and Firefox HCM support. This PR focuses on ensuring all elements are `visible`, especially icons. Focus issues will be addressed in a separate PR (mainly for the Firefox HCM support, Edge is pretty good).

#### Changelog

**New**

HCM changes to the following components
- Accordion
- Button
- Checkbox
- Data Table
- Dropdown
- List Box
- Modal
- Overflow Menu
- Pagination
- Radio Button
- Search
- Select
- Slider
- Tooltip

**Changed**

- Modified the `stylelint` package to not throw an error with the unreleased `prefers-contrast` flag 

#### Testing / Reviewing

On a Windows 10 machine, go to `settings --> ease of access --> high contrast` and flick the switch. Compare the storybook in Edge (Should be in High Contrast) to Chrome (Should look normal). 
For **Firefox**, you'll need to open it up and type `about:config` into the address bar. Then, search for `layout.css.prefers-contrast` and set it to `true`.

 Ensure there are no missing UI elements for the following components: 
- [ ] Accordion
- [ ] Button
- [ ] Checkbox
- [ ] Data Table
- [ ] Dropdown
- [ ] List Box
- [ ] Modal
- [ ] Overflow Menu
- [ ] Pagination
- [ ] Radio Button
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Tooltip

### CODE REVIEW

**Comment by joshblack** [comment]
@tw15egan would this help out at all as a top-level reset? https://github.com/carbon-design-system/carbon/blob/master/packages/icons/scss/mixins.scss

Not sure if it overlaps or not, just saw that this involved icons and remember that we used that for HCM at some point 🤔  Maybe if we update it to include the `prefers-contrast` query?

**Comment by joshblack** [comment]
bump @dakahn when you have a sec to review 👀

**Comment by tw15egan** [comment]
@joshblack I noticed that, and it looks like we already pull it in via our reset:

https://github.com/carbon-design-system/carbon/blob/5408d0bf9943bf960692b761bd1feb9af838cc49/packages/components/src/globals/scss/_css--reset.scss#L198

Problem is, anywhere we define a `fill` (that is not `currentColor`), it takes precedence over this selector. We could slap an `!important` on there and call it a day though 🤔

**Review by dakahn — APPROVED** [review]
Awesome freakin job! 💪

**Comment by joshblack** [comment]
@tw15egan ah that makes a ton of sense, thanks for explaining.

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
@joshblack @dakahn do we want to go forward as-is? Or do we want to change it so that mixin takes precedence in HCM with an `important!`?

**Comment by joshblack** [comment]
@tw15egan I think going forward as-is works out, maybe we could add a lint rule to stylelint to warn us about this in the future?

**Pull request merged**
