### PR TITLE
fix(cli-reporter): fix undefined _style (TypeError: Cannot read properties of undefined (reading '0'))

### PR DESCRIPTION
**Pull request by tongyy**
```chalk.bold._styles``` is only supported in chalk version 2. Since we already upgraded to version 4. This code should be removed otherwise it casuses ```TypeError: Cannot read properties of undefined (reading '0')```
Also the bold close sequence is already got fixed. This is no longer an issue. refer to https://github.com/chalk/chalk/pull/229

#### Changelog

**Removed**

- remove unsupported and unnecessary code for fixing the bold close sequence issue in windows which is no longer an issue 

#### Testing / Reviewing
tested in windows 10 Version	10.0.19044 Build 19044

image

### CODE REVIEW

**Comment by tongyy** [comment]
> **DCO Assistant Lite bot:** Thanks for your submission! We ask that you sign our [Developer Certificate of Origin](https://github.com/carbon-design-system/carbon-dco/blob/main/dco.md) before we can accept your contribution. You can sign the DCO by adding a comment below using this text:
> 
> I have read the DCO document and I hereby sign the DCO.
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the DCO document and I hereby sign the DCO.

**Comment by tongyy** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tay1orjones — APPROVED** [review]
Great catch, thank you!

**Review by andreancardona — APPROVED** [review]
Thank you!!

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
