### PR TITLE
fix(date-picker): wrong font weight

### LINKED ISSUE #1432: Bug:: Date Picker > month/year font weight
Month/year `font-weight` should be 600 not 700.

image

### PR DESCRIPTION
**Pull request by mattrosno**
Closes #1432

Fixes date picker calendar widget year font weight from bold to semi-bold.

### CODE REVIEW

**Comment by asudoh** [comment]
@aagonzales Does #1432 applies to stable, too, or is it solely for experimental...? Thanks!

**Comment by mattrosno** [comment]
@asudoh documentation states 700 font weight should not be used, so my guess is that #1432 applies to stable. https://www.carbondesignsystem.com/guidelines/typography/overview#font-weight

**Review by alisonjoseph — APPROVED** [review]
LGTM as long as design signs off.

**Comment by aagonzales** [comment]
We actually shouldn't be using 700 with Plex only 600. I think that's a carry over from the old components that didn't get updated. We'll need to update those docs

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
