### PR TITLE
fix(NumberInput): add top offset to fix vertical controls alignment IE11

### LINKED ISSUE #2069: IE11: Icons in number input component are misaligned
> Describe in detail the issue you're having.

The validation icon and up/down arrows are sitting too low.

> Is this issue related to a specific component?

Number input

> What did you expect to happen? What happened instead? What would you like to see changed?

Here's IE11:

image

Here's Chrome (expected):

image

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

v10

### PR DESCRIPTION
**Pull request by kbondanza**
Closes https://github.com/carbon-design-system/carbon/issues/2069

This PR adds a top offset of 50% with transform: translateY(-50%), to vertically center the number input controls in IE11. position: relative is also added to `--number__input-wrapper`, so then `--number__controls` will be positioned relative to `--number__input-wrapper` which will now be its nearest positioned ancestor.

#### Changelog

**New**

- add `position: relative` to `--number__input-wrapper` to position `--number__controls` relative to `--number__input-wrapper`.
- add `top: 50%` and `transform: translateY(-50%)` to `--number__controls` to vertically center the controls in IE11.

#### Testing / Reviewing

go to http://localhost:9000/?path=/story/numberinput--default in IE11

### CODE REVIEW

**Comment by vpicone** [comment]
Do we know why this works? What css properties are we using that don’t work for ie 11?

**Review by emyarod — APPROVED** [review]
looks good to me, issue is resolved. I believe these and the related IE11 issues are caused by flexbox usage (ref #4213 #4235 #4315)

image

**Review by emyarod — COMMENTED** [review]
we can also wrap these rules in a media query for quicker find and replace once we drop IE support

**Review by jeanservaas — COMMENTED** [review]
@kbondanza and @mattrosno 

This PR does what it says in that it fixes the vertical controls, but the error icon would still be misaligned... do we want to deal with that in a separate PR, deal with it here... or do we not care for some reason about the error icon?

Vanilla:

image

React:

image

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@jeanservaas I think we could address this in a separate PR if it's still the case 👍

**Pull request merged**
