### PR TITLE
docs(css): add an example of selector namespacing

### PR DESCRIPTION
**Pull request by asudoh**
## Overview

This PR addresses a concern from a team thinking that Carbon cannot be used along with another design system. Though whether we should allow doing so would raise a discussion, I added an example of how it’s possible.

### Added

An example of “selector namespacing” technique.

## Testing / Reviewing

Reviewing should determine if we should allow such technique.

### CODE REVIEW

**Comment by marijohannessen** [comment]
Hey @asudoh , thanks for making this! Do you have an issue or more background for why this is needed? Is it just one team that has been requesting this or several?

**Comment by asudoh** [comment]
Thank you for asking @marijohannessen! Selector namspacing is a technique that allows you to apply CSS only to specific portions of your web page. Other solutions in this problem space are [`<style scoped>`](http://html5doctor.com/the-scoped-attribute/) that [virtually no browser supports it today](https://caniuse.com/#feat=style-scoped), and [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) that is the latest spec is problem this space but older browsers don’t support it and it’s hard-to-polyfill.

**Review by marijohannessen — APPROVED** [review]
👍 ✅

**Comment by asudoh** [comment]
Merging - Anybody please don’t hesitate to speak up if there are any concerns/suggestions. Thanks!

**Pull request merged**
