### PR TITLE
fix(copy-button): add aria-label for the copy button

### LINKED ISSUE #3734: AVT 1 - Single line, Multi line CodeSnippet, and CopyButton has DAP violation
## Environment
macOS Mojave version 10.14.5
Chrome Version 75.0.3770.100 (Official Build) (64-bit)
Carbon v10 - React
DAP IBM Accessibility July 2019 Ruleset

## Detailed Description
Go to Single line React CodeSnippet
Run DAP and the following issue is found on the copy button (see screenshot):
Screen Shot 2019-08-14 at 4 14 23 PM
Note: The button is missing an aria-label.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3734 

The originating issue identified a labeling problem with the `CopyButton`, and also with the `CopyButton` used inside the single-line and multi-line `CodeSnippet` variations.

* **For the `CopyButton`**, I added an `aria-label`. (The `aria-label` on the inner svg can be removed, in this case.) This removes the DAP violation for the `CopyButton`.

* **For the single- and multi-line `CodeSnippet`**, the fix for the `CopyButton` helps, plus I also made sure to include default values for the a11y-related props in those storybook demos. This removes the DAP violations identified in #3734 

#### Changelog

**Changed**

- use `aria-label` in the `CopyButton`
- add default values for a11y props in the `CodeSnippet` storybook demo

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jendowns!

**Review by dakahn — COMMENTED** [review]
I think we totally need an `aria-label` for this icon button and I agree the tooltip we get for `title` isn't up to spec (should be displayed on focus, be persistent, dismissable etc). 

That said having a poorly accessible tooltip is better than none at all here I think -- if for no one else than our sighted users who expect this interaction. Can we wait to remove the `title` attribute and open a ticket to add our Tooltip component to CopyButton and remove `title` with that work?

**Comment by jendowns** [comment]
Thank you @dakahn -- that makes a lot of sense. I just restored the `title` attribute in my latest commit 👍

**Review by emyarod — APPROVED** [review]
looks good to me, not seeing any more DAP violations

**Review by dakahn — APPROVED** [review]
Wonderful!

**Pull request merged**
