### PR TITLE
fix(multi-select): update filterable multiselect default styles

### LINKED ISSUE #7041: Issue: Filterable Multiselect inline property not displaying correctly
## What package(s) are you using?

- [ ] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The filterable Multiselect component does not look "inline" when you apply the inline property to it.

Screen Shot 2020-10-13 at 4 03 11 PM

> What did you expect to happen? What happened instead? What would you like to
> see changed?

It should look like an inline multiselect like:
image

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
v7.20.0 - https://react.carbondesignsystem.com/?path=/story/multiselect--filterable

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
Cloud Pak for Data

> Please create a reduced test case in CodeSandbox
> Go to https://react.carbondesignsystem.com/?path=/story/multiselect--filterable and select Inline knob

### PR DESCRIPTION
**Pull request by emyarod**
Closes #7041

This PR updates the filterable multiselect styles to match the updated component spec

#### Testing / Reviewing

Confirm the filterable multiselect variants are visually correct

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by laurenmrice** [comment]
This change needs to only happen for the `inline` variant of the filterable multiselect. The default filterable multiselect needs to keep its field-01 background (and field-02 background for the light prop).

We just need to change the `inline` version to not have a field background color. When the menu is open, only the options should still get the field-01 (and field-02 for the light prop)

**Review by andreancardona — APPROVED** [review]
@emyarod looks good to me! 🎉

**Review by tw15egan — CHANGES_REQUESTED** [review]
Should only apply to inline variant

**Review by tw15egan — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
looks great! thanks ! 🙌🏻

**Pull request merged**
