### PR TITLE
feat(eslint-config-carbon): update config and externalize package

### PR DESCRIPTION
**Pull request by joshblack**
This is current a WIP progress PR to update our eslint config so that we can externalize it for folks to use.

This is currently used as a discussion for what rules should be applied, along with collaborating on fixing potential violations.

#### Changelog

**New**

**Changed**

**Removed**

### CODE REVIEW

**Comment by joshblack** [comment]
cc @jendowns if you have any recommendations here 👀

**Comment by joshblack** [comment]
- Globally preventing ESLint rules can cause some bugs
  - https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-abusive-eslint-disable.md

From @tay1orjones

**Comment by tw15egan** [comment]
@joshblack updated this PR with linting fixes across the repo 🧙

**Comment by joshblack** [comment]
bump @aledavila @dakahn this should be good to go now after @tw15egan's updates!

**Review by dakahn — APPROVED** [review]

**Review by aledavila — APPROVED** [review]
lgtm

**Pull request merged**
