### PR TITLE
fix(date-picker): increase height on DatePicker, add styles for prev/next month days

### PR DESCRIPTION
**Pull request by echarpibm**
It is necessary to display a 6th row of weeks in the calendar for the
dates to show properly for all months

## Overview

Resolves https://github.com/IBM/carbon-components-react/issues/1055

### Changed

_date-picker.scss modified to add extra space in the calendar to display a 6th row of weeks which is necessary to display all days in a month for some months

## Testing / Reviewing

Assuming the change works, the calendar will display a 6th line of weeks.

The result was achieved by modifying the resulting CSS as follows:

```
.flatpickr-innerContainer,
.flatpickr-rContainer {
  width: 14.0625rem;
  height: 12.5rem; } /* orig 10.5rem = 168px */ /* New 200px = 12.5rem */

.bx--date-picker__days,
.dayContainer {
  width: 14.0625rem;
  min-width: 14.0625rem;
  max-width: 14.0625rem;
  height: 10.25rem; } /* orig 8.25rem = 132px */  /* New 164px = 10.25rem*/

  .bx--date-picker__calendar,
.flatpickr-calendar.open {
  -webkit-box-shadow: 0 12px 24px 0 rgba(0, 0, 0, 0.1);
          box-shadow: 0 12px 24px 0 rgba(0, 0, 0, 0.1);
  background-color: #fff;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
      flex-direction: column;
  -ms-flex-align: center;
      align-items: center;
  -ms-flex-pack: center;
      justify-content: center;
  padding: 0.875rem 1rem 0.25rem;
  width: 17.8125rem;
  height: 16.375rem; /* orig 14.375rem = 230px */ /* New 16.375rem = 262px*/
  border-radius: 0;
  border: none;
  overflow: hidden;
  margin-top: -1px; }
```

### CODE REVIEW

**Comment by tw15egan** [comment]
Hmm, I think we need to do something a little more specific to account for the months that this is needed. 

On months where this is not needed, you can see almost half of the next month, which could be confusing: 

screen shot 2018-07-12 at 11 03 33 am

**Comment by tw15egan** [comment]
I wonder if we can add an opacity to the non-current month dates, to improve the scanability

**Comment by tw15egan** [comment]
Could you also add this block, to enforce a difference between the current month and the next month? 

``` css
.#{$prefix}--date-picker__day.nextMonthDay,
.#{$prefix}--date-picker__day.prevMonthDay {
    opacity: 0.5;
    color: $ui-05;
}
```

**Comment by echarpibm** [comment]
I agree about the opacity, but that was not the original issue. Your fix actually does not seem to work except when loading the calendar the first time.. If you navigate to next or previous month the display is the same...

I will submit the following instead

```
  .nextMonthDay,
  .prevMonthDay {
    opacity: 0.5;
    color: $ui-05;
  }
```

**Comment by tw15egan** [comment]
Works fine locally for me, might need to make sure the styles are far enough down in the stylesheet so that they are not overwritten

date-picker

**Comment by echarpibm** [comment]
I leave it to you of course. When I tried the fix you proposed it was not working for me with the React component.

When I inspect the html this is what I see:

```
  <div class="flatpickr-days bx--date-picker__days" tabindex="-1">
  <div class="dayContainer">
  <span class="flatpickr-day prevMonthDay" aria-label="July 29, 2018" tabindex="-1">29</span>
  <span class="flatpickr-day prevMonthDay" aria-label="July 30, 2018" tabindex="-1">30</span>
  <span class="flatpickr-day prevMonthDay" aria-label="July 31, 2018" tabindex="-1">31</span>
  <span class="flatpickr-day " aria-label="August 1, 2018" tabindex="-1">1</span>
  <span class="flatpickr-day " aria-label="August 2, 2018" tabindex="-1">2</span>
  <span class="flatpickr-day " aria-label="August 3, 2018" tabindex="-1">3</span>
```

And the css change you proposed does not work.

I have tried `.bx--date-picker__day.nextMonthDay` as well as `.bx--date-picker__days.nextMonthDay` (with the additional s) in the CSS and they don't work.

I'm new to this, so I might be missing something else... But for sure the one that I suggested works.

I tried (in the CSS) (and this works, but note the space after "days"):
```
  .bx--date-picker__days .nextMonthDay,
  .bx--date-picker__days .prevMonthDay {
    opacity: 0.5;
    color: #5a6872;
  }
```
The same with the singular "day" did not work. And the same with no space did not work.

**Comment by tw15egan** [comment]
Ahhh, okay, so it seems like there is a difference in implementation between the React version. The React version is not applying the `bx--date-picker__day` to each individual day! I was only checking here on the vanilla side, my apologies. 

I just want to ensure we have some specificity over our code.  This is so that we don't clobber anyone that may have a global `.prevMonthDay` class in their code, and then gets unexpected styles from this addition.

I like your second suggestion, as it will work for both cases (React / Vanilla), as well as improve the specificity. My only nit is that we use the `#{$prefix}` variable.

```css
.#{$prefix}--date-picker__days .nextMonthDay,
.#{$prefix}--date-picker__days .prevMonthDay {
    opacity: 0.5;
    color: $ui-05;
}
```

Thanks for adding this in!

**Comment by echarpibm** [comment]
There you have it, the change is complete...

**Review by marijohannessen — APPROVED** [review]
Looks good to me! 👍 ✅

**Review by tw15egan — APPROVED** [review]
Thanks for taking the time to add this in 👍 ✅

**Pull request merged**
