### PR TITLE
chore: upgrade jest to incorporate jsdom bugfix

### PR DESCRIPTION
**Pull request by emyarod**
This PR upgrades Jest to the latest version (v25.1.0) in order to incorporate a `jsdom` bugfix. The outdated `jsdom` dependency was causing test failures in our `FloatingMenu` component due to an upstream bug which would dispatch a `focus` event when the `focus()` method was called on an already focused element, leading to endless cycling between `focus` and `blur` event handler calls. Discovered while working on #5365 

refs:
https://github.com/jsdom/jsdom/pull/2621
https://github.com/jsdom/jsdom/pull/2700

`jsdom` is also now handling `document.activeElement` differently from previous versions, so some tests have been revised to account for that breaking change

refs:
https://github.com/ant-design/ant-design/pull/21185
https://github.com/jsdom/jsdom/issues/2586
https://github.com/jsdom/jsdom/issues/2723
https://github.com/airbnb/enzyme/issues/2337

#### Testing / Reviewing

Ensure none of our tests are broken

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Comment by emyarod** [comment]
re-requesting review due to some test refactoring (edited PR description for more context and added relevant tickets for context)

**Review by joshblack — APPROVED** [review]

**Review by asudoh — COMMENTED** [review]
One comment - I see several tests are change to add a `<div>` under `<body>`. Wondering if it'll be cleaned up once the test finishes?

**Comment by emyarod** [comment]
I remove them in test suites where they are reused, but I can add the line to each modified individual test case https://github.com/carbon-design-system/carbon/pull/5456/files#diff-e6bde0b208435880662cb06911ee85c1R246

**Review by dakahn — APPROVED** [review]

**Comment by asudoh** [comment]
Thank you for the update @emyarod! Given you added a clean-up code at the last line of each test case, it won't run if there are any assertions failures, etc. You could use a try ... catch block, but I tend to do:

```javascript
describe('suite', () => {
  let div;

  it('does the right thing', () => {
    div = document.createElement('div');
    document.body.appendChild(div);
    (Your test)
  });

  afterEach(() => {
    if (div && div.parentNode) {
      div.parentNode.removeChild(div);
    }
    div = null;
  });
});
```

Note: Ensuring clean-up stuffs done after (each) tests avoids flaky tests.

**Review by asudoh — APPROVED** [review]
Thank you for the update @emyarod!

**Pull request merged**
