### PR TITLE
refactor(project): move to monorepo

### LINKED ISSUE #2382: Reorganize carbon-components as a monorepo
We'd like to re-organize carbon-components into a monorepo. This work includes:

- [x] Setting up yarn workspaces
- [x] Moving core files to `packages/components`
- [x] Setting up lerna
- [x] Configuring CircleCI with new structure update
- [x] Verifying that dev environment tasks work as expected

### PR DESCRIPTION
**Pull request by joshblack**
Closes #2382

Updates project to monorepo structure in preparation for merge with other codebases.

Reviewer checklist:

- [x] Lint staged works as expected
- [x] Editor plugins work as expected in nested package (like prettier)
- [x] Can still develop locally with fractal
- [x] GitHub files are up-to-date
- [x] CircleCI is running CI checks
- [x] ESLint works as expected
- [x] Tests run as expected, don't fail

### CODE REVIEW

**Comment by joshblack** [comment]
TODO

- [x] Add root-level README.md file

**Comment by asudoh** [comment]
Good checklist @joshblack, just one addition:

- [ ] Build steps around Netlify deploy works

Seems that [`namedExports` settings in our Rollup config](https://github.com/carbon-design-system/carbon-components/blob/v10.2.0/tools/rollup.config.dev.js#L40-L53) need an update (Due to changed `node_modules` directory location)

**Review by alisonjoseph — APPROVED** [review]
Nice work on this Josh! tested developing, tests, linting and all seems to be working 🎉

**Comment by joshblack** [comment]
@asudoh for netlify, I think what we'll need to do is use GitHub actions alongside Netlify to trigger deployments for specific sub-directories.

When looking at this earlier, it seemed like a combination of [`diff-includes`](https://github.com/netlify/actions/tree/master/diff-includes) and [`cli`](https://github.com/netlify/actions/tree/master/cli) would handle our use-cases for publishing netlify builds for sub-packages that have changed

In the interim though, I can definitely set it up so that it hosts the right directory though 👍

**Review by asudoh — COMMENTED** [review]
LGTM 👍 from my perspective, would like feedback from others.

**Review by dakahn — APPROVED** [review]

**Review by mattrosno — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
looks good to me!

**Pull request merged**
