### PR TITLE
fix(TableToolbarSearch): fix rendering issues with TableToolbarSearch

### LINKED ISSUE #8598: [TableToolbarSearch] icon overlay on text
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
The table search has text overlaying the search icon
Screen Shot 2021-05-06 at 12 29 35 PM

This bx-input in search.scss set a padding which broke this.
Screen Shot 2021-05-06 at 12 55 37 PM

> Is this issue related to a specific component?
TableToolbarSearch

> What did you expect to happen? What happened instead? What would you like to
> see changed?
The text not overlay on the icon

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
we used  "carbon-components": "10.33.0", "carbon-components-react": "7.33.0",

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
IBM Cloud

## Steps to reproduce the issue

It's complicated to copy the whole table in sandbox.  you have to import the search.scss

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/main/packages/react/examples/codesandbox

https://codesandbox.io/s/pensive-butterfly-miqbx?file=/src/index.js

## Additional information

- Screenshots or code
- Notes

### LINKED ISSUE #8784: [Data table with toolbar] Search jumped to left and broke onClick
in v10.36

With toolbar
https://react.carbondesignsystem.com/?path=/story/components-datatable--with-toolbar

Also in with Batch actions
https://react.carbondesignsystem.com/?path=/story/components-datatable-batch-actions--usage

Search on the toolbar should not be left aligned, and on click, it looks visibly wrong: 
image

image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/8784 
Closes https://github.com/carbon-design-system/carbon/issues/8598 
Ref https://github.com/carbon-design-system/carbon/pull/8101 & https://github.com/carbon-design-system/carbon/pull/8435

Fixes an issue with `TableToolbarSearch` rendering with an incorrect height and expanding in the wrong direction

#### Changelog

**Changed**

- Increased `TableToolbarSearch` specific selector to prevent newer `Search` styles from overriding the behavior

**Removed**

- Removed hardcoded `sm` size from the internal `Search` used in `TableToolbarSearch`
- No longer add the `xl` class by default to `Search`

#### Testing / Reviewing

Check the `Batch Actions` and `With Toolbar` stories and ensure they are rendering correctly

### CODE REVIEW

**Comment by tw15egan** [comment]
cc @shixiedesign

**Review by emyarod — APPROVED** [review]
looks good to me pending design review

**Comment by aagonzales** [comment]
@tw15egan the preview isn't working for me.

**Comment by tw15egan** [comment]
@aagonzales for some reason Netlify added some new features and it's adding a bunch of stuff to the end of the URL. If you remove it, it should load. Here's the link I got to work: 

https://deploy-preview-8824--carbon-components-react.netlify.app/?path=/story/components-datatable--with-toolbar

**Review by aagonzales — COMMENTED** [review]
The spacing on the search icon is off in the sm and xs sizes. It should be lined up with the text, 16px. 

image

image

**Comment by tw15egan** [comment]
@aagonzales just pushed up a fix, deploy should be available shortly ⌛

**Review by aagonzales — APPROVED** [review]
Yup, looks good now! 👍 ✅

**Review by sstrubberg — APPROVED** [review]
🔥

**Pull request merged**
