### PR TITLE
feat(RadioButton): add `slug` prop

### LINKED ISSUE #15190: Add AI enhancements to React `Checkbox`
> - #15182

Image

### LINKED ISSUE #15191: Add AI enhancements to React `RadioButton`
> - #15183

Image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15191
Closes https://github.com/carbon-design-system/carbon/issues/15190

Adds in `slug` prop to `RadioButton`, `RadioButtonGroup`, `Checkbox`, and `CheckboxGroup`

#### Changelog

**New**

- `slug` prop in `RadioButton`, `RadioButtonGroup`, `Checkbox`, and `CheckboxGroup`
- Styles added to properly positioning the `Slug` inside these components

#### Testing / Reviewing

Added a `Slug test` story to `Checkbox` and `RadioButton`. Ensure they render correctly.

### CODE REVIEW

**Comment by tw15egan** [comment]
@aagonzales can the `Slug` in the group label ever be the inline style, or is that only for the radio/checkbox items themselves?

**Review by tay1orjones — APPROVED** [review]
This looks good to me 👍

**Review by aagonzales — CHANGES_REQUESTED** [review]
For the inline ones, then need to be one size bigger, using the sm/14px size to match the type size of the item labels 

image

**Comment by tw15egan** [comment]
Updated 👍🏻

**Review by aagonzales — APPROVED** [review]
Looks good! ✅ 👍

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Pull request merged**
