### PR TITLE
fix a11y issues on dropdown and combo box

### PR DESCRIPTION
**Pull request by CharlieOrlando**
**Changed**

- Tweaked dropdown and combo box to adhere to A11Y guidelines

### CODE REVIEW

**Comment by dakahn** [comment]
Hey, thanks a lot for the work. For testing purposes could you talk a little about the specific accessibility issues/guidelines you were addressing with these changes?

**Comment by CharlieOrlando** [comment]
Happy to help. Hopefully these tweaks are kosher. They removed the violations from the DAP Chrome extension, but I'm by no means an expert on accessibility so please let me know if there's anything that needs changing.

For added context, I was assigned two accessibility issues for our current sprint. These are the images that were attached to the Github issues... 

1bff2956-0912-11e9-8fe6-96915092ebd6

9d6878bc-0912-11e9-9fea-bfdff8964ab9

**Review by dakahn — CHANGES_REQUESTED** [review]
Testing against the deployed preview with your changes using DAP with the latest ruleset

Dropdown:
- Drop down is removed from the tab order and can no longer be accessed via keyboard
- _"Widget with role of link must have at least one tabbable element."_ error remains. That said this error can be considered a false positive since the widget does in fact contain tabbable elements, but the widget itself is hidden until activated. You can test this yourself by opening the dropdown and re-running DAP.

Combobox:
- I'm not actually able to reproduce this error on my machine using the deployed preview. Could you tell me the specific DAP rulesets you're testing with?

**Comment by joshblack** [comment]
Hi @CharlieOrlando! 👋 are you still interested in finishing up this PR? Seems like @dakahn left some feedback that would need to be addressed before merging in. After that, then we should be good to go!

**Comment by CharlieOrlando** [comment]
Hey, @joshblack. I actually talked to DA via Slack and ended up updating my rulesets. Dropdown, indeed, was a false positive. Combo box still throws a violation for me, but DA mentioned that he wasn't able to reproduce the issue so I'm not sure what to do about that one.

**Comment by joshblack** [comment]
Gotcha, thanks for the update @CharlieOrlando! 🙏 Since we're unable to reproduce, would you want to make an issue with an example in codepen/codesandbox/etc and we can help debug what's going on?

**Comment by joshblack** [comment]
Going to close this for now, thank you so much for taking the time to contribute @CharlieOrlando! 🙏 We really, really appreciate it. Let me know if you want to pick this work back up and we can totally re-open 👍

**Pull request closed without merging**
