### PR TITLE
feat(styles): move grid config to main _config.scss file

### LINKED ISSUE #11036: [Bug]:  SassError: This module was already loaded, so it can't be configured using "with".
When using `@carbon/react` to use modules in the following order:

```scss
@use '@carbon/react/scss/grid/flexbox';
@use '@carbon/react/scss/type';
```

I receive the following error:
```
  ModuleBuildError: Module build failed (from ../../node_modules/sass-loader/dist/cjs.js):
  SassError: This module was already loaded, so it can't be configured using "with".
     ┌──> ../../node_modules/@carbon/grid/index.scss
  8  │   @forward 'scss/modules/config';
     │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ new load
     ╵
     ┌──> ../../node_modules/@carbon/type/scss/modules/_styles.scss
  12 │   @use '@carbon/grid/scss/modules/config' as gridconfig;
     │   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ original load
     ╵
     ┌──> ../../node_modules/@carbon/styles/scss/grid/_config.scss
  9  │ ┌ @forward '@carbon/grid'
  10 │ │   show css-grid,
  11 │ │        flex-grid,
  12 │ │        $grid-gutter,
  13 │ │        $grid-gutter-condensed,
  14 │ │        $grid-breakpoints
  15 │ │   with (
  16 │ │     $prefix: config.$prefix !default,
  17 │ │     $flex-grid-columns: config.$flex-grid-columns !default
  18 │ │   );
     │ └───^ configuration
     ╵
    ../../node_modules/@carbon/grid/index.scss 8:1                 @forward
    ../../node_modules/@carbon/styles/scss/grid/_config.scss 9:1   @forward
    ../../node_modules/@carbon/styles/scss/grid/_flexbox.scss 8:1  @forward
    ../../node_modules/@carbon/react/scss/grid/_flexbox.scss 9:1   @use
    ../gatsby-theme-carbon/src/styles/internal/_global.scss 1:1    @use
    ../gatsby-theme-carbon/src/styles/index.scss 27:1              root stylesheet
```

### PR DESCRIPTION
**Pull request by joshblack**
Closes https://github.com/carbon-design-system/carbon/issues/11036

This PR updates our styles package to be more flexible when it comes to import order. It achieves this by moving our grid configuration to the top-level `scss/_config.scss` module and updating files to import from `_config.scss` first to avoid any errors where a module is redeclared with `with`.

#### Changelog

**New**

- Add CSS grid entrypoint

**Changed**

- Move grid config entrypoint to top-level config
- Update imports to reference config first
- Update tests to rely on public API files
- Update tests to account for out of order imports

**Removed**

#### Testing / Reviewing

- Verify tests pass as expected for the public style entrypoints
- Verify that there is a test for "out of order" imports from the styles package

### CODE REVIEW

**Comment by jnm2377** [comment]
@joshblack seems like some of the tests are still failing. I'm unsure if it's the tests you added or existing tests though.

**Comment by joshblack** [comment]
@jnm2377 ah thanks for the heads up, I'll update the snapshot tests

**Review by dakahn — APPROVED** [review]
other than the broken snappies looks good

**Comment by joshblack** [comment]
@jnm2377 updated!

**Review by tay1orjones — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
