### PR TITLE
fix(grid): Remove min-height that isn't required and causes visual is…

### PR DESCRIPTION
**Pull request by DusanMilko**
…sues with empty cols

When using cols in something like angular or vue where html elements are added and removed there existed a visual bug when adding an empty column vs no column. The ideal result should be no difference but due to the min height the empty column increased parent height.

#### Changelog

**Removed**

- removed min height on columns causing visual issue with empty cols

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
Tagging @IBM/carbon-developers in case anyone who worked on the grid code knows why this min-height was added.

Otherwise seems ok to me. 👍

**Review by lovemecomputer — APPROVED** [review]
approving with same comment as @alisonjoseph

**Comment by asudoh** [comment]
CC @tw15egan Ref: https://github.com/IBM/carbon-components/pull/45

**Comment by tw15egan** [comment]
Seems fine to me 👍

**Pull request merged**
