### PR TITLE
fix(structured-list): add selected background border

### LINKED ISSUE #5232: [structured list] selection variant needs peristent background for selected state
For the selected state, the background needs to stay with the checkmark. The background color of the selected state should be `$layer-selected`.

--------------------------------------------------------------------------------------------------

Spec:
Artboard

### LINKED ISSUE #13383: [structured list] selection variant border is missing a piece
There is a section on the right side of the structured list where the border is wrong, also visible on hover. Border should extend all the way across. 

Screenshot 2023-03-21 at 12 22 53 PM

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #5232
Closes #13383

#### Changelog

Adds selected background state for structured list. Noticed a bug with the border while adding this and created a new [issue](https://github.com/carbon-design-system/carbon/issues/13383).

**New**

- add selected background state

#### Testing / Reviewing

Check that selected state is correct 
https://deploy-preview-13384--carbon-components-react.netlify.app/?path=/story/components-structuredlist--selection

Thanks @francinelucca for the cross-browser fix! 🥳

### CODE REVIEW

**Review by francinelucca — APPROVED** [review]
LGTM!

**Comment by tw15egan** [comment]
Any idea what this little border variance is? It is on `main` as well, so it seems like an existing bug

**Comment by alisonjoseph** [comment]
Yea I opened an issue for that yesterday, I think it has to do with the radio button not being inside a td, but didn't spend too much time on it. https://github.com/carbon-design-system/carbon/issues/13383 @tw15egan

**Review by tw15egan — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
@alisonjoseph 

- The hover and selected state backgrounds should overlap or hide the rule dividers if that is possible. 
- The hover state background color should be `$layer-hover`. I would just double-check because it seems lighter and might currently be $background-layer.

Artboard

**Comment by alisonjoseph** [comment]
Re-requesting reviews @tw15egan @laurenmrice @francinelucca 

This PR now should have correct hover and border colors, it should hide the border when on hover/selected and it should fix the border bug from https://github.com/carbon-design-system/carbon/issues/13383

**Review by francinelucca — APPROVED** [review]
LGTM

**Comment by tw15egan** [comment]
@alisonjoseph the fix looks great! But I'm able to click and change the background on the default `StructuredList` now as well

**Comment by alisonjoseph** [comment]
@tw15egan good catch! Should be fixed now 😅

**Review by laurenmrice — APPROVED** [review]
Looks good to me! ✅

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
