### PR TITLE
feat(Github Actions): add auto-assign github action

### PR DESCRIPTION
**Pull request by dakahn**
This adds a Github action that will auto assigning a dev team maintainer to the issue to see through to close. 

#### Changelog

**New**

- adds ...workflows/auto-assign-issues.yml

#### Testing / Reviewing

I'm not super sure how we can test a Github action adding PR.

### CODE REVIEW

**Comment by aledavila** [comment]
Could we test this on another repo ?

**Review by alisonjoseph — COMMENTED** [review]
This might be better as a team discussion, but was thinking about this more and chatting with a couple people since this morning.  What if we only auto-assigned issues that have the needs-triage label for X amount of days? This would solve the issue of anything falling through the cracks, while also allowing everyone to triage and grab issues normally. @carbon-design-system/developers

**Comment by tw15egan** [comment]
@alisonjoseph I'm down with trying that

**Comment by joshblack** [comment]
Gonna close this one out @dakahn since it's been up for a bit and it _seems_ like our issue count is growing down 👀 

Thanks so much for taking the time to research this / make a PR!! 🙏  Really appreciate it.

**Pull request closed without merging**
