### PR TITLE
fix(Modal): content spacing styles

### LINKED ISSUE #8373: modal bug: inputs should span the full width
This is a regression: the inputs should be spanning the full width of the modal. 

Storybook:
image

Should be:
image

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #8373 

- Adds padding only to paragraph/text within modal. All other elements span full width.
- `xs` modal content always spans full width, even paragraphs/text.

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Looks good! 👍

**Comment by aagonzales** [comment]
Not sure if this is related to this PR or not but the fade at the bottom of the content isn't showing up when there is scrolling content. I'm not seeing it in regular story book so its probably not related, just wanted to check.

**Comment by tw15egan** [comment]
@jnm2377 it seems like this update will make the `hasForm` prop redundant, since all non-`p` elements will now span full width. 

Should we add a deprecate notice to the prop, and leave a coment to remove the `.#{$prefix}--modal-content--with-form` in V11?

**Review by aagonzales — APPROVED** [review]
LGTM!

**Review by emyarod — COMMENTED** [review]
should the xs modal paragraphs have no additional padding or am I misinterpreting this note? https://github.com/carbon-design-system/carbon/issues/8373#issuecomment-818885530

**Comment by jnm2377** [comment]
@tw15egan good call, updated with deprecation warning 👍🏽

**Comment by jnm2377** [comment]
> should the xs modal paragraphs have no additional padding or am I misinterpreting this note? [#8373 (comment)](https://github.com/carbon-design-system/carbon/issues/8373#issuecomment-818885530)

@emyarod I'll defer to @aagonzales on this. I left the xs padding as is.

**Comment by aagonzales** [comment]
Oh good catch. The `xs` small one if good but the `sm` needs a breakpoint change at 1056 to also have the paragraph content span 100%

**Comment by tw15egan** [comment]
It looks like XS still has some padding when the modal is displayed on smaller screens. It looks like the rest of the size variants don't have this padding

XS
Screen Shot 2021-04-29 at 3 49 29 PM

All other variants
Screen Shot 2021-04-29 at 3 49 46 PM

**Pull request closed without merging**
