### PR TITLE
feat(component): add SideNavMenu.tsx component

### LINKED ISSUE #13606: Add TypeScript types to SideNavMenu

### PR DESCRIPTION
**Pull request by Nirajsah**
Closes #13606

I am adding a new file `SideNavMenu.tsx` with its types. However, there is an issue with the `@carbon/icons-react` library. It's important to note that there are no other issues with the `SideNavMenu.tsx` file.

#### Changelog

**New**

- Added `SideNavMenu.tsx` file with its associated types.

**Changed**

- None.

**Removed**

- None.

#### Testing / Reviewing

Reviewers, please follow these steps to verify this PR:

1. Pay special attention to how `@carbon/icons-react` is being used and whether the issue is noticeable.
2. Confirm that there are no other issues introduced by this PR.
3. Please provide feedback on the changes and the issue with `@carbon/icons-react`.

Your help in addressing this issue is much appreciated. Thank you!

### CODE REVIEW

**Comment by Nirajsah** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by guidari — COMMENTED** [review]
Hey @Nirajsah thank you so much for your contribution!! 🚀 

Always nice to see new components being converted to TS! 🔥

I did a commit to fix the error in TS related to propTypes being not supported in render functions when using the `ForwardRefRenderFunction`.
I'm not sure if I understand what is the error with `@carbon/icons-react`  library. Maybe it got it fixed also?

Let me know what you think! 😁

**Comment by Nirajsah** [comment]
> Hey @Nirajsah thank you so much for your contribution!! 🚀
> 
> Always nice to see new components being converted to TS! 🔥
> 
> I did a commit to fix the error in TS related to propTypes being not supported in render functions when using the `ForwardRefRenderFunction`. I'm not sure if I understand what is the error with `@carbon/icons-react` library. Maybe it got it fixed also?
> 
> Let me know what you think! 😀

Thanks for your comment! The issue with the `@carbon/icons-react` library is that it's primarily written in JavaScript, and the components that have been converted to TypeScript (TS) are currently lacking type definitions.

This means that when TypeScript is used in our project, it expects to have type information available for all imported modules. Since the `@carbon/icons-react` library doesn't provide TypeScript type definitions, TypeScript can't properly infer types for these components.

**Comment by guidari** [comment]
> Thanks for your comment! The issue with the `@carbon/icons-react` library is that it's primarily written in JavaScript, and the components that have been converted to TypeScript (TS) are currently lacking type definitions.

Ohh I see what you mean! Currently we are just ignoring that warning using `// @ts-expect-error - PropTypes are unable to cover this case.` 
I did write that in the code also!

**Review by guidari — APPROVED** [review]

**Review by andreancardona — APPROVED** [review]
Looks good! Thank you for the contribution :)

**Comment by tay1orjones** [comment]
@Nirajsah @andreancardona @guidari One thing we missed here was to delete the old SideNavMenu.js file and to ensure the new .tsx file is exported in the index.js

**Comment by Nirajsah** [comment]
> @Nirajsah @andreancardona @guidari One thing we missed here was to delete the old SideNavMenu.js file and to ensure the new .tsx file is exported in the index.js



I apologize for my mistake. Since it was my first pull request, I decided to keep the original file as a precaution in case anything went wrong. However, in my second and third pull requests, I used the `git mv` command to change the file extension from .js to .tsx, thereby updating the file."

**Pull request merged**
