### PR TITLE
fix(codesnippet): Design audit changes

### LINKED ISSUE #1888: QA fixes: code snippet
### Overall: 
- [x] Update all code snippet variants to use type token `$code-01`

### Multiline:

- [x] Need background (same color as interface background) under "Show more" button and code snippet icon so that the code will be hidden when it runs under them; it's not like ghost button where it's just transparent and then you get the background on hover only. We need the same-color background shape to block out code.

<br>

**problem:**
image

<br>

**spec: that background should be there always; it's just that when it's enabled, it is the same color as the code snippet background**

image

<br>

- [x] If type overflows, fade out the copy with a G10 overlay (can we do this?):

image

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #1888 

- example of fadeout/overflow with long text
codesnippet

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @jnm2377!

**Comment by jeanservaas** [comment]
This looks great, one final comment:

can we add the fade to the single line code snippet since terminal code snippet has it?

Otherwise LGTM!

**Comment by shixiedesign** [comment]
Hey @jnm2377 thanks for making the change! Lovely fade for overflow 💯 ❤️ 
A few hopefully small issues: 
- [x] ~~expansion animation is missing when clicking on "show more" (but closing animation goods great)~~
- [x] Copy button also need a background so text and icon don't overlap
image

**Comment by jnm2377** [comment]
@shixiedesign @jeanservaas made those changes! 👍

**Review by jeanservaas — APPROVED** [review]
Looks great!

**Pull request merged**
