### PR TITLE
fix(pagination): fix the select input to support multi-digits numbers

### PR DESCRIPTION
**Pull request by rezak-otmani**
## Overview

*Resolves*
#607
and this issue : 
https://github.com/carbon-design-system/carbon-components-react/issues/732 
in *carbon-components-react*

applying width:auto to the select-input and select--inline to support multi-digits numbers  and render them without any overflow

### CODE REVIEW

**Comment by asudoh** [comment]
@carbon-design-system/ui Would you agree with the style change...? Thanks!

**Comment by joshblack** [comment]
Noticed some style discrepancies when checking out the PR:

screen shot 2018-04-09 at 4 19 38 pm
screen shot 2018-04-09 at 4 19 21 pm

Any chance we can get those fixed?

**Comment by tw15egan** [comment]
Encountering this issue outside of this PR: https://github.com/carbon-design-system/carbon-components/issues/691

**Comment by tw15egan** [comment]
Still seeing some style issues with this PR: 
screen shot 2018-04-11 at 9 30 46 am

**Comment by tw15egan** [comment]
Seeing an issue that when there is a large option (I put in a value of 500 in the `select` menu), it pushes the smaller numbers to the left.

screen shot 2018-04-16 at 11 06 18 am

Seems like adding `text-align-last: center` fixes this issue

screen shot 2018-04-16 at 11 09 00 am

**Comment by rezak-otmani** [comment]
Yes it's possible

**Review by marijohannessen — APPROVED** [review]
Looks good to me! 👍 ✅

**Review by tw15egan — APPROVED** [review]

**Comment by mven** [comment]
@tw15egan just a heads up that `text-align-last` isn't supported in Safari.

**Comment by tw15egan** [comment]
@mven of course 🙄 . If we get any complaints about misalignment in Safari we can reopen this and try and find a more elegant solution.

**Pull request merged**
