### PR TITLE
fix(overflow-menu): use correct icon color for danger items

### LINKED ISSUE #2971: isDelete=true OverflowMenuItem Icon should be white onmouseover
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

When mousing over an isDelete=true OverflowMenuItem, its text is white, but its icon is #171717.

## Steps to reproduce the issue

1. Create an OverflowMenuItem with isDanger=true
2. Mouse over the menu item

https://jv1rn.codesandbox.io/

## Additional information

image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2971

This PR matches SVG icon color with text color in danger/delete variant overflow menu items on hover (similar to icons in buttons)

#### Changelog

**Changed**

- `isDelete` overflow menu item SVG icon hover color

#### Testing / Reviewing

Add an icon to an overflow menu item with `isDelete={true}` to test. as far as I know this isn't a pattern that we expose on our docs so it isn't viewable on Netlify

you can test this by modifying one of the overflow menu items in storybook to

```js
<OverflowMenuItem
  {...overflowMenuItemProps}
  itemText={
    <>
      <Delete16 /> Danger option
    </>
  }
  hasDivider
  isDelete
/>
```

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@emyarod mind checking in the built files? I think it'll just be `yarn docs` in `packages/components`

**Comment by asudoh** [comment]
@joshblack Seems that this is style-only change with a few lines...?

**Comment by joshblack** [comment]
@asudoh since it uses a token, the SassDoc for components needs to be updated since it captures token usage.

**Comment by asudoh** [comment]
@joshblack Sounds that this topic requires update to contributor guide. Would you please do? Thanks!

**Comment by emyarod** [comment]
updated the sassdoc but the error still persists, does the script need to be tweaked?

**Comment by jnm2377** [comment]
Try running `yarn build` at the top-level. That's what I had to do for one of my PR's that was failing with the same error.

**Pull request merged**
