### PR TITLE
[RFC] Add support for vendor folders

### PR DESCRIPTION
**Pull request by joshblack**
RFC for elements-related packages. Adds in support for copying `@carbon/*` packages into a `vendor` folder so that our files in `carbon-components` can import the packages directly. Packages are versioned through `devDependencies`. This allows us to use these packages without requiring downstream consumers to update their `node-sass` config to include `node_modules` so that the module imports work.

#### Changelog

**New**

- `tools/copy-vendor-styles.sh` bash script to copy files

**Changed**

- `global/_colors.scss` now imports from `vendor` folder for colors
- `components/ui-shell` now uses `mini-units` helper

**Removed**

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by asudoh** [comment]
Thanks @joshblack for the proposal! LGTM from my perspective, considering the problem you are trying to solve. Let's see what others think.

**Review by alisonjoseph — APPROVED** [review]
LGTM! 

Would be good to maybe schedule a quick meeting next week to show everyone how we should be using the mini unit stuff in our experimental component work? So we are all on the same page.

**Comment by joshblack** [comment]
Meeting scheduled!

**Comment by joshblack** [comment]
Closing for a PR that officially brings over our tokens! 👍

**Pull request closed without merging**
