### PR TITLE
feat(number-input): add mobile variant

### LINKED ISSUE #1837: Number input fixes
Two fixes needed: 

- [ ] Mobile support https://github.com/carbon-design-system/carbon-contribution/issues/3#issuecomment-464099688 
image

- [ ] Mike found forced italic!

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1837

Related: https://github.com/carbon-design-system/carbon-contribution/issues/3

This PR adds support for a mobile number input variant and updates the documentation to include examples

#### Testing / Reviewing

Ensure the mobile number input looks correct and functions properly

### CODE REVIEW

**Comment by shixiedesign** [comment]
Reviewing on Safari on iPhone:
- [x] There seems to be a small gap between the buttons and number field. Should not have gaps there. This is not visible on Chrome.
- [x] Can we have the numeric keyboard showing up instead of alpha keyboard? Helps to guide users avoid invalid input. 

img_1619

**Comment by emyarod** [comment]
the Safari margins should be taken care of now

I thought it was strange that you reported the numeric keyboard was not appearing, and it turns out this is an iOS ~~bug~~ feature. Just to make sure though: this behavior also occurs with our existing number inputs (on iOS only) right? The workaround for this is to use [invalid (but functional) HTML](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number#Pattern_validation), so I've pushed it up for the mobile variant. I don't have an iOS device so I can't check but for the sake of testing can you confirm that the numeric keyboard now appears for the mobile variant only? I haven't yet modified our existing number input components so they should still be displaying the alphanumeric keyboard on iOS only.

**Review by shixiedesign — APPROVED** [review]
Yep mobile variant now pulls out the numeric keyboard! Standard num input still calls the alpha keyboard, which is fine since you said it's a bug-feature :joy: . All looks good.

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
