### PR TITLE
fix: add shadow token, update overlay token

### LINKED ISSUE #9802: [Feature Request]: Improve contrast on shadows for dark themes (G90 and G100)
### Summary

Based on our conversations about the Side Panels and increasing contrast on dark mode shadows to match the contrast level of Light Themes (White and G10), I want to propose some changes to these components.

**Overflow menu shadows**

- [x] Either changing both to 80% opacity OR G90 to 70% and g100 to 80%

**Page overlay for Modals**

- [x] Overlay color change to #000000 (instead of #161616) and transparency of 65%

image

image

### Justification

_No response_

### Desired UX and success metrics

_No response_

### Required functionality

_No response_

### Specific timeline issues / requests

IBM Cloud is rolling out Dark Mode to clients until next January, product teams are already fixing their code bases to use Carbon Themes correctly. It would be essential this update is ready by the end of the year. 

### Available extra resources

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by janhassel**
Closes #9802

#### Changelog

**New**

- Added new token `shadow`
  - white/g10/v9: `rgba(0, 0, 0, 0.3)`
  - g80/g90/g100: `rgba(0, 0, 0, 0.8)`

**Changed**

- Updated `overlay`/`overlay-01` token
  - white/g10/v9: unchanged (see below)
  - g80/g90/g100: `rgba(0, 0, 0, 0.65)`
- Updated token snapshots

#### Testing / Reviewing

- Verify visual appearance is as expected
- According to @yumeforever, the current `overlay`/`overlay-01` token in light themes should've been `rgba(gray100, 0.7)` though it being `rgba(gray100, 0.5)`. Which one is preferred?
- According to @yumeforever, the current shadow of overflow menus in light themes should've been `rgba(0, 0, 0, 0.3)` though it was `rgba(0, 0, 0, 0.2)`. I changed it to @yumeforever's suggestion to increase the contrast. Let me know if this works for everyone.

### CODE REVIEW

**Comment by yumeforever** [comment]
> #### Testing / Reviewing
> * Verify visual appearance is as expected
> * According to @yumeforever, the current `overlay`/`overlay-01` token in light themes should've been `rgba(gray100, 0.7)` though it being `rgba(gray100, 0.5)`. Which one is preferred?

My bad, I thought it was 0.7, but I just checked the [Color Guidelines](https://www.carbondesignsystem.com/guidelines/color/usage) and it is 0.5—Let's keep this way

> * According to @yumeforever, the current shadow of overflow menus in light themes should've been `rgba(0, 0, 0, 0.3)` though it was `rgba(0, 0, 0, 0.2)`. I changed it to @yumeforever's suggestion to increase the contrast. Let me know if this works for everyone.

Here I was using as reference the [Style infos](https://www.carbondesignsystem.com/components/overflow-menu/style#color) on the Overflow menu that states it is 0.3—if it was not I assume it was a bug.
That being said the [Dropdown shadow](https://www.carbondesignsystem.com/components/dropdown/style#color) is 0.2—I don't see a reason to have one point stop difference, so I would opt for the one with the more contrast, 0.3

**Comment by janhassel** [comment]
@yumeforever

> Here I was using as reference the Style infos on the Overflow menu that states it is 0.3—if it was not I assume it was a bug.
That being said the Dropdown shadow is 0.2—I don't see a reason to have one point stop difference, so I would opt for the one with the more contrast, 0.3

That's probably a mistake on the documentation then as both components use the same code under the hood to display their box shadow. I agree that 0.3 seems better. 👍

**Review by aagonzales — APPROVED** [review]
Yay for making these tokens! And yeah I think @yumeforever has got you the right values. Thank you for making this PR!!! And thanks Morgana for doing the design leg work on this one. We really appreciate y'alls contribution. 

PS Design team talked about this off-line and gave the thumbs up from our perspective.

**Review by sstrubberg — APPROVED** [review]
Looks great @janhassel!

**Review by jnm2377 — APPROVED** [review]
💯 thanks for adding this!!!!

**Pull request merged**
