### PR TITLE
fix: convert menubutton to typescript, and do other menu typescript cleanup.

### PR DESCRIPTION
**Pull request by wkeese**
This builds on #15361 to do a few more menu-related Typescript updates:

* `MenuButton`: Convert to Typescript.
* `MenuContext`: Specify type for context. There’s contradictory evidence though about whether payload is mandatory or optional.
* `Menu`: Minor cleanup including specifying that when `x` and `y` are arrays, the arrays contain exactly two numbers.
* `MenuItem`: Convert some “any” types into actual types, including converting MenuItemRadioGroup to a generic.  Also the same cleanup as above about x and y as arrays.  Ignore spacing diffs.
* `useAttachedMenu()` - Convert to Typescript.

I had to add `@ts-ignore` to some of the `PropTypes` declarations for reasons I don't understand.  I'm not too worried about it since `PropTypes` declarations are essentially deprecated.

Also, I know the doc said not to convert internal files to Typescript but it didn’t seem feasible to do this conversion without useAttachedMenu.js and MenuContext.ts having the right types, and it didn’t seem feasible for them to have the right types without converting them to Typescript.

### CODE REVIEW

**Comment by andreancardona** [comment]
@wkeese Hey Bill, is there a way you can take a look at these merge conflicts? Thank you!

**Comment by wkeese** [comment]
Looks like the conversion was already mainly handled by https://github.com/carbon-design-system/carbon/pull/15361 (cc @mattborghi). The main thing left in my PR is `MenuButton`, but I also tightened up a few Typescript declarations.   I rebased my PR.

**Comment by wkeese** [comment]
@tay1orjones, @andreancardona - I fixed the merge conflicts. This is the second time it's happened, so hopefully this PR can be merged soon. The MenuButton conversion to Typescript changed the indentation, so git diff and git merge are useless. It doesn't even realize that index.tsx is just index.js renamed.  Even though I used `git mv`, as that command is irrelevant to how git detects file renames.

**Review by tw15egan — APPROVED** [review]
We really appreciate all your work on this @wkeese! LGTM 👍🏻 ✅

**Review by guidari — APPROVED** [review]
LGTM! 🚀
Thanks for the contribution!

**Pull request merged**
