### PR TITLE
chore(pictograms): add preview example for elements site

### PR DESCRIPTION
**Pull request by joshblack**
This PR should help out with https://github.com/carbon-design-system/carbon/pull/7094 by providing a way to preview pictograms in the netlify preview link. This example was copied over and modified from the example we currently have for icons.

#### Changelog

**New**

- Add pictograms preview to pictograms package

**Changed**

**Removed**

#### Testing / Reviewing

- Verify that you can see the pictograms page in the elements preview and that pictograms render as expected

### CODE REVIEW

**Comment by joshblack** [comment]
~~Note to reviewers: trying to debug why the build is timing out~~ Resolved!

**Comment by mjabbink** [comment]
@dudley-ibm @joshblack in the elements preview all the ones in the list with “expanded” in the name can be eliminated now that all of them are expanded.
 
For @dudley-ibm I still see a few pictograms that have fills rather than expanded strokes.

**Comment by mjabbink** [comment]
ok, so I’m confused. The preview link above shows the svg files as stroked files. I thought that preview was for the new pictograms. So scratch my above comments since I’m not looking at the latest.

**Comment by joshblack** [comment]
@mjabbink this PR is for visualizing the current set which use strokes. The PR from @emyarod (which should bring this preview in) will help with visualizing the new icons which use fill 👍  This PR is just getting that preview set up like we already have for icons.

**Review by emyarod — APPROVED** [review]
thanks for adding this, looks good to me

**Comment by joshblack** [comment]
bump @andreancardona when you have a sec today 👀

**Review by andreancardona — APPROVED** [review]
@joshblack looks awesome!

**Pull request merged**
