### PR TITLE
chore(dependencies): bring in carbon-elements 10.1

### LINKED ISSUE #2104: Add ms high contrast support for icons
In https://github.com/IBM/carbon-elements/pull/388 we landed support for high contrast mode for icons when being used in a Microsoft browser. This issue is to integrate the mixin available in the latest versions of elements.

### PR DESCRIPTION
**Pull request by asudoh**
For incorporating IBM/carbon-elements#388.

Fixes #2104.

#### Changelog

**New**

- The style for MS high contrast support for `<svg>`, from IBM/carbon-elements#388

**Changed**

- `carbon-elements` dependency to `10.1.x`
- Put `carbon--type-reset` mixin to after other reset styles, to avoid `font: inherit` overriding the `font-family` set in `carbon--type-reset`

#### Testing / Reviewing

- Reviewers - Good to focus on change in `src/globals/scss/_css--reset.scss`, all other changes are of change in dependency (`carbon-elements`).
- Testing should make sure no component is broken.

### CODE REVIEW

**Comment by asudoh** [comment]
Waiting for IBM/carbon-elements#488 to be released to pass the test.

**Comment by mattrosno** [comment]
I preemptively fixed the `font:inherit` issue in https://github.com/IBM/carbon-components/pull/2328. Just sharing as a heads up to potential merge conflict.

**Comment by asudoh** [comment]
Still waiting for carbon-design-system/carbon-elements#488 to be released.

**Comment by joshblack** [comment]
Brought over into #2743 👍 Would you want to add your commits over into there @asudoh for some of the additional changes?

**Comment by asudoh** [comment]
Cool, thanks @joshblack - Netlify preview in #2743 seems to tell that no additional change is necessary, but will see and bring additional changes over otherwise.

**Pull request closed without merging**
