### PR TITLE
test: increase coverage for TimePicker

### LINKED ISSUE #17497: Increase `TimePicker` unit test coverage

### PR DESCRIPTION
**Pull request by somya-05**
Closes #17497 

Increase test coverage for TimePicker component.

#### Changelog

**Changed**

- Increased test coverage to be above 80%

#### Testing / Reviewing

Check code coverage and make sure the test cases make sense

### CODE REVIEW

**Comment by somya-05** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by somya-05** [comment]
@kennylam @alisonjoseph please review the following changes

**Review by alisonjoseph — APPROVED** [review]
Test coverage at 83.78% now for TimePicker 👍
Screenshot 2024-10-07 at 1 30 04 PM

**Comment by somya-05** [comment]
@kennylam please review the changes made

**Review by ariellalgilmore — APPROVED** [review]

**Pull request merged**
