### PR TITLE
fix(breadcrumb): rotate overflow menu icon 90m degress

### LINKED ISSUE #1105: Overflow menu icon should rotate when embedded inside a breadcrumb
## Detailed description
When I add an overflow menu inside a breadcrumb I expect the overflow menu icon to rotate 90 degrees (as it does in a table).

screen shot 2018-09-17 at 10 57 09

> Is this issue related to a specific component? Overflow Menu

> What did you expect to happen? What happened instead? What would you like to see changed? Icon should rotate by 90 degrees

> What browser are you working in? Chrome

> What version of the Carbon Design System are you using? Can reproduce using latest code

> What offering/product do you work on? Any pressing ship or release dates we should be aware of? Assess

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by markewallace**
Fixes #1105

Closes #1105 

Rotate overflow menu item by 90 degrees when nested inside a Breadcrumb

#### Changelog

**Changed**

- Rotate overflow menu item by 90 degrees when nested inside a Breadcrumb

#### Testing / Reviewing

I have added to the existing Breadcrumb sample but need some input on how to include two separate samples

### CODE REVIEW

**Comment by chrisconnors-ibm** [comment]
Thanks for this submission. The as-is behavior is expected and desired - truncated breadcrumb items are collapsed into an _ellipsis_ rather than the overflow menu control.

**Comment by markewallace** [comment]
@chrisconnors-ibm the issue is the orientation of the ellipsis. My understanding is that these should be horizontally aligned rather then vertical.

**Comment by markewallace** [comment]
This is how is currently renders
screen shot 2018-09-17 at 10 57 09

The Carbon documentation shows the ellipsis horizontally aligned, see: http://www.carbondesignsystem.com/components/breadcrumb/usage

**Comment by alisonjoseph** [comment]
Hi @markewallace, this shouldn't be using an icon at all, it should be updated to use an ellipses character. I think that's what the confusion is here.

**Comment by alisonjoseph** [comment]
Closing due to inactivity. Feel free to reopen if needed!

**Comment by chrisconnors-ibm** [comment]
this should be closed bc as above "this shouldn't be using an icon at all, it should be updated to use an ellipses character." not to be fixed as proposed

**Comment by alisonjoseph** [comment]
Yes you're correct @chrisconnors-ibm, was assuming it could be reopened / updated to use the ellipses.

**Pull request closed without merging**
