### PR TITLE
docs(button): expose tertiary button and restrict icon button variants

### LINKED ISSUE #5199: Documentation is missing tertiary button examples
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

while reviewing #5195 we found that tertiary buttons were missing from React storybook and not properly documented in vanilla

> Is this issue related to a specific component?

button

### PR DESCRIPTION
**Pull request by emyarod**
Closes #5199

This PR exposes the tertiary buttons in the React storybook and removes incorrect icon button variants from the React and vanilla docs

#### Testing / Reviewing

Ensure that only the correct button knobs and variants are exposed in the docs

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Review by laurenmrice — CHANGES_REQUESTED** [review]
React
For Default tertiary buttons:
-The active state color should be `active-tertiary` color token

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Vanilla:
- The active state is blocking out the text in the button. the icon only button is correct though.
Jan-29-2020 11-47-48

React:
- The active state does not change the background of the container and it is making the text turn black. It should only be changing the background color to the `active-tertiary` color token. The icon only button is correct though.
Jan-29-2020 11-46-16

- Also I noticed when switching the default buttons from primary to secondary to tertiary, the tertiary buttons jump a bit in size horizontally. the tertiary buttons should remain the same size as they are in primary and secondary.

**Review by joshblack — APPROVED** [review]

**Comment by emyarod** [comment]
vanilla should be correct now

the react issues are mainly because the base elements of the examples you tested are not actually buttons (we're showing some examples of other elements being styled like buttons). mainly we want to check if the element labeled "Button" is correct, since using a different base element can change how active and focus states are applied

the change in width is due to the border width changing from 3px in the other variants to 1px in the tertiary and ghost variants. does that mean the padding needs to change for the 1px border button variants?

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Okay thanks @emyarod that makes sense ! All of the changes you made look good.

- The tertiary icon button is getting a weird double focus outline in react and vanilla.
Screen Shot 2020-01-30 at 10 36 17 AM


- In dark themes, the active state is getting a white border around the active background color, there shouldn't be a visible border.
Jan-30-2020 10-50-50

**Comment by emyarod** [comment]
tertiary button width should be the same as the other button variants now

fixed the double focus outline ref https://github.com/carbon-design-system/carbon/pull/4867

for the dark theme active state border, what should the token be there? it looks like it's just inheriting `$interactive-03`. also it's worth noting that this behavior differs based on browser

**Comment by laurenmrice** [comment]
the token is right for the border, its just that that border should not be showing up on active state, it should be a solid background. Could the active background overlap that border somehow?  Its not happening in the light themes.

**Comment by asudoh** [comment]
@emyarod Is this PR ready for re-review? Thanks!

**Comment by emyarod** [comment]
@asudoh yes it is ready for review

**Review by laurenmrice — APPROVED** [review]
looks great, thank you !👍🏻

**Comment by asudoh** [comment]
Got a green light from @emyarod to move this to "ready to merge" state.

**Pull request merged**
