### PR TITLE
Added divider to `NumberInput`

### LINKED ISSUE #15859: Introduce Divider across multiple states for AI Number Input
image

### PR DESCRIPTION
**Pull request by 2nikhiltom**
Closes #15859

Added dividers to `NumberInput` across all states (warn/invalid)

**New**

Dividers in `NumberInput` 

#### Testing / Reviewing

Go to the storybook and test the dividers across all states (warn/invalid)

### CODE REVIEW

**Comment by tw15egan** [comment]
Looks good! Just had a few comments:

Seems like there might be a slight spacing discrepancy with the divider between the slug variant and the non-slug variant; the non-slug seems to be a few pixels further

Screenshot 2024-03-21 at 5 12 35 PM
Screenshot 2024-03-21 at 5 12 49 PM


Also, there seems to be some flickering when the `NumberInput` is focused, can also kind of see it in the `invalid` variant

**Comment by alina-jacob** [comment]
Hi @2nikhiltom, thanks for working on this! 🚀 
@tw15egan's comment is right, the spacing does look odd a bit  👀 

I did a closer inspection and realised that the spacing that works for the chevron and dismissible icon in the dropdown variants won't work for number input, because in this component the plus and minus items are **buttons**. 

Even though, the icons of these buttons are of 16px, the click area for the button is 48px and that's the same spacing pattern we will have to provide for all subsequent elements coming to the left of the buttons.

Pasting an **updated** screenshot of the spacing just for the number input component, you can also check out the spacing relation for error and invalid states in the default component [here](https://react.carbondesignsystem.com/?path=/story/components-numberinput--playground&args=invalid:!true).

[Figma ref link](https://www.figma.com/file/VIapeeP8TSM77qYIjdMiIY/Dividers-in-Carbon-Components?type=design&node-id=368-12162&mode=design&t=6UQz4ZVsysahCPAj-4)

Specs for Dividers in Number input

**Review by alina-jacob — APPROVED** [review]
Looks good Nikhil! 🚀 

**[RESOLVED]** (in the deploy preview i noticed a vertical divider dissecting the minus button for the default number input component, but the AI one looks good!) ✅

Thanks!

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by tay1orjones — APPROVED** [review]
Be sure to [avoid magic numbers](https://github.com/carbon-design-system/carbon/blob/4bdd6802dd612af764ef76162141333d35bd84f4/docs/style.md?plain=1#L866-L899).

I don't think it's worth holding up merging this but if you want to do another pass here you could open up a new issue to track it for this/next sprint.

**Comment by 2nikhiltom** [comment]
Further enhancements are tracked via #16133

**Pull request closed without merging**
