### PR TITLE
fix(dropdown): issues with activedescendant attribute

### LINKED ISSUE #4031: [Dropdown]: activedescendent not de-selected on blur
## Environment

> Browser
- all
> Automated testing tool and ruleset
- DAP + IBMa/aat

## Detailed description

> What version of the Carbon Design System are you using?
10.6x

> What did you expect to happen?
When clicking away from a dropdown (blur), the `aria-activedescendent` attribute should be removed from the menu (ul.bx--dropdown).

This behavior is there if you `close` the dropdown by clicking it, it just needs to be added on `blur` of the dropdown - which _also_ closes the dropdown, but _does_ remove the attribute. See [this section in the dropdown vanilla js](
https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/dropdown/dropdown.js#L184) where the attribute is removed

> What happened instead?

The attribute is not removed on `blur`, causing the DAP/AAT violation

https://www.w3.org/TR/wai-aria-1.1/#aria-activedescendant

## Acceptance Criteria

- [ ] `aria-activedescendent` is removed on dropdown blur

### PR DESCRIPTION
**Pull request by elizabethsjudd**
Closes https://github.com/carbon-design-system/carbon/issues/4031

clean up focus classes and activedescendant attribute when dropdown is blurred.  Also fixed issued @emyarod found in #4406 where it was possible to have multiple focus indicators at once.  To resolve this issue I carried over the functionality of having the focus move with the mouse hover a behavior that is in the React version.  The styling is different than the react version since it's a much bigger undertaking and would most likely require some HTML changes to not create spaghetti CSS. (much better suited for a major change)

#### Changelog

**Changed**

- update Dropdown JavaScript to clean up focus and active descendant when blurred
- update Dropdown JavaScript and styles so focus also moves with the mouse creating a more similar experience to what's in Carbon React.

#### Testing / Reviewing

Shouldn't be able to reproduce the bug in #4406 and the focus moves with the mouse user (@carbon-design-system/design).  When you `blur` the dropdown the active descendent attribute should no longer be on the list.

### CODE REVIEW

**Comment by asudoh** [comment]
> Also fixed issued @emyarod found in #4406 where it was possible to have multiple focus indicators at once.

@emyarod Can you think of a scenario where we can reproduce this problem? Or in case it comes from a hypothesis, do you have a good explanation of that? Need to get a better handle on what the problem is and how this PR solves the problem. Thanks!

**Review by emyarod — COMMENTED** [review]
nice work so far, we no longer have dual focus outlines. it looks we still have multiple items with the selected or hover background though

dropdown

image

**Comment by emyarod** [comment]
@asudoh this issue first appeared when I went to make a selection from the dropdown but "canceled" my selection by dragging the cursor away from the dropdown before `mouseup`

for additional context: https://github.com/carbon-design-system/carbon/pull/4406#pullrequestreview-305274225

**Comment by elizabethsjudd** [comment]
@emyarod ready for re-review

**Comment by asudoh** [comment]
Thanks @emyarod for clarifying! Seems that we are no longer using actual focus for keyboard navigation. If it's the case, do we still need to keep focus style on dropdown item? Wanted to make sure we have a bit more holistic look at the series of issues here. Thanks!

**Comment by elizabethsjudd** [comment]
@asudoh you still need an indicator so that keyboard users know what item they are on. I considered trying to adopt more of the Carbon React styles but that's a massive overhaul and I'm not positive it could be backwards compatible (without a feature flag) which I figured was out of scope for this specific issue.

**Comment by asudoh** [comment]
You are right that we still need bogus focus style for keyboard navigation. I'm talking about actual focus style.

**Comment by elizabethsjudd** [comment]
By having both pseudo focus and actual focus that is how we were getting the double focus indicators to show up when using keyboard and mouse.  The Carbon React version uses divs (the overhaul i mentioned to make these more aligned stylistically with Carbon React) so the "real" focus isn't applicable which is how there wasn't this problem in Carbon React.  When using active descendent that is an acceptable way to handle focus indicators to users.

**Review by emyarod — APPROVED** [review]
thanks for the update, looks good to me pending design review

**Review by dakahn — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]
Looks good!

**Comment by asudoh** [comment]
Dropped a note to @elizabethsjudd to see if there is a root cause for duplicate focus indicator that we can eliminate.

**Comment by elizabethsjudd** [comment]
@asudoh based on our conversation on Friday, I added the check for using the HTML structure for active descendant and additional comments with explanations. Ready for re-review.

**Comment by asudoh** [comment]
Thanks @elizabethsjudd! Did you mean to push another commit for the check for using the HTML structure for active descendant?

**Comment by elizabethsjudd** [comment]
@asudoh it was part of that commit (sorry should have probably used fix or something): https://github.com/carbon-design-system/carbon/pull/4501/commits/66f3681007bbfca6e5498dab316625948d760eec#diff-3423a6944840e106c1a3af01aae4307eR67

**Comment by asudoh** [comment]
Seems that `this.element.querySelector(this.options.selectorTrigger)` as well as `this.element.querySelector(this.options.selectorMenu)` in older HTML structure. Just in case I wasn't clear enough, I wanted to make sure the "active descendant mode" code won't run in older HTML structure. Does it make sense?

**Comment by elizabethsjudd** [comment]
@asudoh That check is the same check I've used for multiple PRs to test for the `aria-activedescendant` mode because that attribute isn't consistent so I'm having to just look for the new HTML which is what that if statement is doing (I created those 2 selector properties in a previous PR). You can see me using that check for setting/removing the `aria-activedescendant` attribute here:

* https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/dropdown/dropdown.js#L148-L175
* https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/dropdown/dropdown.js#L270-L278
* https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/components/dropdown/dropdown.js#L214-L220

**Comment by asudoh** [comment]
OK thanks for explaining - Seems that you use `.bx--dropdown-text` being `<button>` instead of `<li>` for the detection, is it correct?

**Comment by elizabethsjudd** [comment]
@asudoh that's correct. Prior to all of the work I did in previous PRs the trigger wasn't a button so looking for an actual button element and then the list selector (which is a new selector I added) tells me that I'm using the latest HTML structure.

**Comment by asudoh** [comment]
OK could you add a comment to the `selectorTrigger` definition with that explanation? Maintainers knowing that `selectorTrigger` is only for the new markup of the trigger button is important. Thanks!

**Comment by elizabethsjudd** [comment]
@asudoh the `selectorTrigger` definition already states that it's looking for a button and that it's used for the a11y compliant markup.

**Comment by asudoh** [comment]
As discussed with @elizabethsjudd, added a commit to the comments I requested for. Thanks @elizabethsjudd for your patience!

**Pull request merged**
