### PR TITLE
fix(datepicker): update datepicker, timepicker placeholder colors

### PR DESCRIPTION
**Pull request by tw15egan**
## Overview

Closes https://github.com/carbon-design-system/carbon-components/issues/882

- Adds in proper `placeholder` colors for `DatePicker` and `TimePicker`

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Basically LGTM, thank you for doing this @tw15egan! One question (wrt existing code) - Are we controlling the placeholder color only for WebKit browsers?

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
I think you also need to add the following to get the color to show in IE and FF. 
`::placeholder` & `:-ms-input-placeholder`

**Comment by tw15egan** [comment]
This seems like it might be a larger issue, as doing a search of our components I'm seeing we only reference `::-webkit-input-placeholder`, see `_text-input.scss`, `_text-area.scss` etc..

**Comment by tw15egan** [comment]
I'm going to go through and just refactor all placeholders to reference `::placeholder` directly, as autoprefixer will handle the rest

**Comment by tw15egan** [comment]
Updated

**Review by alisonjoseph — APPROVED** [review]
LGTM! thanks TJ

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks alot @tw15egan for cleaning things up here!

**Pull request merged**
