### PR TITLE
fix(tabs): set tab container height same as tab height

### PR DESCRIPTION
**Pull request by lovemecomputer**
resolves issue from https://github.com/carbon-design-system/carbon/issues/2799

this fix only syncs up `Tabs` height with `Tab` height.

#2799 also contains notes about changing to a non-fixed-height for `Tabs`; after investigating other components, it appears many "toolbar-zone" elements (Toolbar, inputs, etc) also use a fixed height of `2.5rem` or `3rem`, and i'm averse to breaking that consistency for a single component which may need to line up with them.

**Changed**
- `Tabs`'s `min-height` set to same height as `Tab` height (was previously taller)

---

**Testing**

vanilla: https://deploy-preview-3410--the-carbon-components.netlify.com/component/tabs--default.html

react: https://deploy-preview-3410--carbon-components-react.netlify.com/?path=/story/tabs--default

- look at the `Tabs` component, use inspector to verify heights.
- also can chime in about thoughts on fixed vs. fluid heights as discussed in #2799

### CODE REVIEW

**Review by mattrosno — APPROVED** [review]
Any reason why you didn't use the `rem` mixin, `rem(40px)`?

Fix looks good until we can possibly refactor the tabs styling in the future to not use hardcoded heights.

**Comment by lovemecomputer** [comment]
@mattrosno only because i read the value from inspector instead of from source. updated to match, thanks!

**Review by aledavila — APPROVED** [review]
🎊

**Review by joshblack — APPROVED** [review]

**Comment by mattrosno** [comment]
@lovemecomputer I manually closed issue 2799. Just an FYI, `resolves issue from #2799` keywords won't auto-close the issue 😉.

https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by lovemecomputer** [comment]
@mattrosno since this PR didn't fully close all suggested changes in the issue, i didn't use the keyword :) i'm not a fan of issues being auto-closed by PRs that don't actually fully-close all of the points in an issue (tho in this case, after deciding not to implement dynamic heights i suppose it would have been fine). thanks for closing!

**Pull request merged**
