### PR TITLE
fix(Slider): use lighter hue for focused and active slider colors

### LINKED ISSUE #4203: [slider] Gray 90 and Gray 100 bug with interactive color
Interactive state:
When moving the slider, the blue color is too dark. It needs to be using `interactive-04`

### PR DESCRIPTION
**Pull request by AlexanderLyon**
Closes #4203

Changed the colors used for focused / active slider from `$interactive-01` to `$interactive-04` for better visibility on Gray 90 and Gray 100

#### Changelog

**Changed**

- `_slider.scss`

image

### CODE REVIEW

**Comment by AlexanderLyon** [comment]
@laurenmrice 👆

**Review by jnm2377 — APPROVED** [review]
Awesome! Thanks for this! 🎉

**Review by abbeyhrt — APPROVED** [review]
This looks great! Thank you for contributing! 🎉

**Review by laurenmrice — APPROVED** [review]
looks great, thanks ! 🎉

**Pull request merged**
