### PR TITLE
fix(progressindicator): adjust styles for progress step with optional label position

### PR DESCRIPTION
**Pull request by abbeyhrt**
This PR adjusts how the ProgressSteps with an optional label position themselves and resolves a release bug that was caught before the 10.10 release. 

What the bug was:

Screen Shot 2020-02-14 at 10 44 01 AM

#### Changelog

**Changed**

- switches vertical progress bar to display flex 

**Removed**

- `initial` position from optional label

#### Testing / Reviewing

Check to make sure the icons are all in line

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Can someone view the vertical progress indicator  in ie11 or edge? I think that is where this issue was occurring. Positioning looks good in firefox, chrome and safari.

Now that I have access to view themes in react:
- the current and completed icons needs to be calling `interactive-04` they are wrong in the dark themes.
- the fourth and fifth step labels should be calling `text-01`. They are wrong in the dark themes.
- the optional text should be calling `text-02`

**Comment by abbeyhrt** [comment]
@laurenmrice surprisingly, this problem was in all browsers, but someone should definitely still check IE11!

**Review by emyarod — APPROVED** [review]
Edge screenshot for reference

image

looks good to me pending design approval

**Review by laurenmrice — APPROVED** [review]
All looks good to me in firefox, chrome and safari and in diff themes !

**Review by tw15egan — APPROVED** [review]
👍 ✅

**Pull request merged**
