### PR TITLE
feat(progress-bar): add Experimental Progress Indicator

### LINKED ISSUE #1300: Experimental Component - Progress Bar - Development
**Development**
A developer can discover and install the experimental component by following accessible documentation.

- [ ] Add to carbon-components
- [ ] Update website (add to the experimental section and update component status page)

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #1300 

#### Changelog

**New**
- lots of `{{#if}}` blocks because the Experimental progress has a lot of differences from stable mode:
1. optional text 
2. error state
3. disabled state
4. overflow state (with tooltip)
- added js function for overflow class that allows tooltip to display on hover
- added js functionality that adds class to tooltip if it is multiline (diff padding/height/width)

#### Testing / Reviewing
- Ensure that tooltip is only displaying on the truncated text and not other labels.
- Staging link: http://carbon-dev-environment-progress-x3-persistent-crane.mybluemix.net/?nav=progress-indicator

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
You figured it out! Putting performance/complexity concerns aside, the code looks good enough. Thanks alot @jnm2377!

**Comment by alisonjoseph** [comment]
Couple design related questions 

1. sketch file says 8px spacing above the dots but its actually more like 9px because there is 1px padding around the dot. See screenshot. So the spacing looks tighter in code vs. sketch. 
screen shot 2018-11-27 at 9 08 46 am

2. do we want a fixed height on the tooltip @laurenmrice 
screen shot 2018-11-27 at 9 08 19 am

3. Font size looks like it is 14px in the sketch file, but 16px in code

Code looks great btw! 🎉

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Looking good! A couple of things:

-Yes to everything Alison said above :)
-The Step text needs to be 14px and Optional text below it is 12px.
-We should define the height for tooltip. I would like to keep this tooltip consistent with the other tooltip component. I attached a screenshot of the specs of one line in a tooltip vs multiple. 
artboard copy

**Comment by jnm2377** [comment]
Unsure where why the `header submenu` test failed. I didn't touch any of those files.. My branch is up to date with master, too. 😭

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Just reviewed the new staging link:
- The icons are rendering weird in Firefox, but look fine in Chrome.
- The text in the tooltip should be Regular weight and not Semibold. 
- The stepper text is positioned a little higher than the icons in Firefox. They need to come down to be aligned more with the icons and also align within the focus border.

**Review by laurenmrice — APPROVED** [review]
Looks great ! Thank you 🎉

**Comment by asudoh** [comment]
Thank you for the updates @jnm2377!

**Pull request merged**
