### PR TITLE
fix(link): replace box-shadow with text-decoration & outline

### LINKED ISSUE #3059: [Link] cannot have `block` Link due to usage of `box-shadow` for interactive states
## What package(s) are you using?

```
    "@carbon/colors": "^10.1.0",
    "@carbon/grid": "^10.3.0",
    "@carbon/icons-react": "^10.3.0",
    "@carbon/import-once": "^10.1.0",
    "@carbon/layout": "^10.1.0",
    "@carbon/themes": "^10.3.0",
    "@carbon/type": "^10.2.0",
    "carbon-components": "^10.3.1",
    "carbon-components-react": "^7.3.1",
```

## Detailed description

If you ever apply `display: block` to the `Link` component (vanilla, React, or otherwise), the `box-shadow` being used to create the underline on `:hover`/`:active`/`:focus` states will extend to the entire length of the block, way past the text of the link in some cases.

For example, go to the Carbon website (https://www.carbondesignsystem.com/components/link/code), add `display: block` to an example `Link`, and you will see the following:

Screen Shot 2019-06-13 at 10 42 10 AM

Even though this is expected with the box model, this "visual defect" is very noticeable. **And I don't think we should expect `Link` to always remain `inline` in various applications / products.** On the contrary, a block-style `Link` seems like a reasonable customization / deviation to expect, right? 🤔

## 🚨  UPDATE: Other concerns with AVT 🚨  

Please see this comment for additional a11y concerns with using `box-shadow` for interactive link styling: https://github.com/carbon-design-system/carbon/issues/3059#issuecomment-501997246

## Proposed solution 

So `text-decoration: underline` would work great here & passes our AVT cases!

If you used `text-decoration: underline` instead of the `box-shadow` for the `:hover`/`:active`/`:focus` states, then it wouldn't matter if the `Link` was inline or block -- that text decoration would only extend as far as the link's text:

Screen Shot 2019-06-13 at 10 46 31 AM

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3059 

Per https://github.com/carbon-design-system/carbon/issues/3059#issuecomment-506778818

#### Changelog

**Changed**

- replace `box-shadow` with `text-decoration: underline`
- for the focus state, use `outline`

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
looks good to me, but I just want to confirm with design that this is the desired active and focus state

image

**Comment by jendowns** [comment]
@emyarod It looks like you are focusing *and* hovering on a visited link? 🤔 

From the deployed preview, when I only focus on it:
Screen Shot 2019-06-28 at 11 43 44 AM

EDIT: oh ooops, just actually noticed the text in your demo screenshot 😇

**Comment by emyarod** [comment]
@jendowns no the screenshot shows simultaneous focus and active state on Firefox 69

here is what it looks like in Chrome 77

image

**Comment by jendowns** [comment]
Yup! If it’s not clear from my edit, I got that 👍

**Review by shixiedesign — COMMENTED** [review]
I'm double checking the focus + active/hover state of link. Meanwhile, looks like focus border for dark themes is not getting the color change. Could you verify that focus is using `$focus` token? Should be white in dark themes. (https://carbon-elements.netlify.com/themes/examples/preview/#focus)

image

**Review by joshblack — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
🙌

**Comment by jendowns** [comment]
Thanks @shixiedesign! I updated this PR to use the focus mixin, which sets it to `outline: 1px solid $focus` by default. Let me know what you think 👍

**Review by shixiedesign — APPROVED** [review]
Awesome! Thank you for the fix!

**Pull request merged**
