### PR TITLE
fix(ErrorStates): allow form items in error status to receive focus

### LINKED ISSUE #6529: Re-investigate focus states with invalid form items
Based on https://github.com/carbon-design-system/carbon/issues/6513
Related to https://github.com/carbon-design-system/carbon/pull/6522

## What package(s) are you using?

- [x] `carbon-components`

## Detailed description

> Describe in detail the issue you're having.

When an item is invalid, the invalid border takes precedence over the focus state. This causes a11y concerns, as a keyboard user has no visual way to navigate through multiple invalid form items. 

> Is this issue related to a specific component?

Form items (e.g. Text Input, Textarea, DatePicker)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

I would expect the form item to receive a focus border when focused, even when invalid

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

Latest

## Steps to reproduce the issue

1. Go to https://react.carbondesignsystem.com/?path=/story/textinput--default
2. Go to knobs --> set the invalid state to true
3. With an invalid input, click into the text input and notice no focus state is added
4. Tab through and notice no visual change on focus

## Additional information

form

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6529

Enables focus state outlines for components when in error status

#### Changelog

**New**

- Components will now properly receive focus when in error status

**Changed**

- Moved some `data-invalid` specific code to `form.scss`
- Invalid class is now added to `TimePicker` wrapper, not the input

**Removed**

- Removed redundant code and added the selectors to the error blocks in `form.scss`

#### Testing / Reviewing

Go to each form element, enable the error states, then click into the element and ensure it properly receives focus

### CODE REVIEW

**Review by dakahn — APPROVED** [review]
I really like these. These are cool :surfer:

**Review by laurenmrice — COMMENTED** [review]
All of your updates to the focus for invalid state form components looks good.

I did notice weird invalid state behavior happening for `date picker` but this seems like it is possibly unrelated to this pr. I can make an issue separate to this if you want.

Example: In Firefox the border looks fuzzy and in Chrome and Safari the red color of the border is too dark:
Screen Shot 2020-07-24 at 12 36 25 PM

Screen Shot 2020-07-24 at 12 38 43 PM

**Comment by tw15egan** [comment]
@laurenmrice Weird, I can't reproduce either of those 🤔 

Showing up as `$support-01` for me:
Screen Shot 2020-07-24 at 12 47 53 PM


And I'm not seeing a fuzzy border in Firefox 
Screen Shot 2020-07-24 at 12 43 09 PM

**Review by laurenmrice — APPROVED** [review]
🚀

**Review by andreancardona — APPROVED** [review]

**Comment by andreancardona** [comment]
@tw15egan lgtm! 👍

**Pull request merged**
