### PR TITLE
fix(dropdown): use helper mixin for hidden dropdown items

### LINKED ISSUE #3539: Dropdown: please use visibility:hidden when hiding
The Dropdown component uses `opacity: 0` to hide items in the dropdown list.
This is a problem for accessibility because the items are still in the reading order, and screen reader users can see them if they are using virtual cursor navigation.

The DAP catches this - sort of - by complaining about the color contrast when the list items are transparent:

image

To fix this without affecting the animation of the list, please add visibility: hidden (and visibility: visible) to the hide/show code for the dropdown list. (not sure if adding it to the list itself or to the list items is "better").

Here are some blog posts that may be helpful in this area:
- https://css-tricks.com/snippets/css/toggle-visibility-when-hiding-elements/
- https://medium.engineering/five-goofy-things-medium-did-that-break-accessibility-3bc804ae818d

Also: not sure if there are other components that also use opacity: 0 to hide stuff? please search the Carbon codebase for the pattern to ensure that all are using visibility: hidden as well.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #3539 

By using the `@hidden` helper mixin for dropdown items when the menu is not opened, we can make sure that there's `visibility: hidden` etc style rules added for `a11y` purposes.

#### Changelog

**Changed**

- apply `@hidden` helper mixin to un-opened dropdown menu items

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by lovemecomputer** [comment]
oh cool! there's some discussion about syncing/dividing styles btwn listbox and dropdown in my PR at https://github.com/carbon-design-system/carbon/pull/3458 ; i'll make sure to reference this if this also needs to be declared for listbox~

**Review by lovemecomputer — APPROVED** [review]
thanks!!

**Review by tw15egan — APPROVED** [review]
👍

**Comment by elizabethsjudd** [comment]
The mixin used in this PR makes something visually hidden but visible to screen reader users... that's the opposite of what is wanted: https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/scss/_helper-mixins.scss#L121

**Comment by jendowns** [comment]
😱 Oh no you are right @elizabethsjudd! I didn't notice the `visibility: visible` in there & missed the intention of the mixin.

@tw15egan / @lovemecomputer / @josh could we revert this or would you rather I open a different PR that remedies this?

**Comment by tw15egan** [comment]
Just threw up a fix: https://github.com/carbon-design-system/carbon/pull/3547/files

**Pull request merged**
