### PR TITLE
fix(timepickerselect): descender text cut off on chrome & safari

### PR DESCRIPTION
**Pull request by Kman316**
Closes #

Removed `line-height: 1` from `.bx--time-picker .bx--select-input` as this seems to break the descender text on Chrome & Safari. This solves the following bug: https://github.com/carbon-design-system/carbon/issues/9847

#### Changelog

**Removed**

- `line-height: 1`

#### Testing / Reviewing

Check to make sure that descender text isn't cut off in a word such as `Chicago` on Chrome & Safari.

### CODE REVIEW

**Comment by Kman316** [comment]
recheck

**Comment by Kman316** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Kman316** [comment]
recheck

**Comment by Kman316** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by jnm2377 — APPROVED** [review]

**Review by abbeyhrt — APPROVED** [review]

**Pull request merged**
