### PR TITLE
feat(v10): add v10 compat token example app

### LINKED ISSUE #13692: Compat tokens: create a compat token example using all compat token modules
In `./examples`, provide an example that uses compat tokens from every module (grid, layout, color, theme, etc.) so that consumers can more readily understand the compat tokens, how they work, and are configured.

This could be it's own new example, or we could potentially combine this with the existing `examples/custom-theme` example. Maybe it could be renamed to `compat-custom-theme` or something. A new stylesheet called `compat.scss` could be added that shows v10 tokens in use by `@use`ing the proper modules.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/13692

This adds in an example app that shows v10 tokens for the `theme`, `spacing`, `motion` and `type` packages working inside of Carbon V11.

#### Changelog

**New**

- Adds in an example application under `examples/v10-token-compat-in-v11` that is running the latest `@carbon/react` but only using tokens from `v10`. This includes the `theme`, `spacing`, `motion`, and `type` tokens. 

#### Testing / Reviewing

Go to `examples/v10-token-compat-in-v11` locally and run `yarn` and `yarn dev`. Take a look at the source code and ensure this is enough of an example for a user to figure out how to use `v10` tokens in `v11`

### CODE REVIEW

**Review by francinelucca — APPROVED** [review]
looks great! 🚀

**Comment by francinelucca** [comment]
Should this have a `README.md` to kind of explaing what the app is and how to run it? Example: https://github.com/carbon-design-system/carbon/blob/main/examples/id-prefix/README.md

**Comment by tw15egan** [comment]
@francinelucca yeah I can add that

**Review by guidari — APPROVED** [review]

**Comment by guidari** [comment]
LGTM! Everything is running as expected and the informations are clearly

**Pull request merged**
