### PR TITLE
fix: add line height to unsortable columns on sortable datatable (#9311)

### LINKED ISSUE #9311: Vertical alignment of sortable columns vs. non-sortable columns in XL tables
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

With row-size set to XL, the vertical alignment of sortable columns vs. unsortable columns is slightly off.  Notice below how "Protocol" is slightly lower than "Name".

Screen Shot 2021-07-26 at 12 25 55

(It is pretty subtle though, only a few pixels.)

This is on Carbon 10.37, tested on the latest versions of Chrome and Firefox on MacOS.

## Steps to reproduce the issue

See https://codesandbox.io/s/happy-minsky-n5i5s?file=/index.html.

### PR DESCRIPTION
**Pull request by pmweeks98**
Closes #9311

**Changed**

Added lineheight to ensure the correct font size is used in unsortable columns

**Testing / Reviewing**

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Comment by pmweeks98** [comment]
recheck

**Comment by tay1orjones** [comment]
@pmweeks98 could you share a link to the storybook where the original bug can be reproduced to compare with the fix made here? I'm having a hard time determining what/where this fixes the column headers.

**Comment by jnm2377** [comment]
@tay1orjones this is the repro https://codesandbox.io/s/happy-minsky-n5i5s?file=/index.html

**Comment by tay1orjones** [comment]
@jnm2377 Oh thanks! I missed that. Yeah I can't repro in react. If this passes the VRT checks then I think it's alright?

**Comment by pmweeks98** [comment]
@tay1orjones can you advise on how to get a storybook with my changes in it?

**Comment by tay1orjones** [comment]
@pmweeks98 To edit the storybook you can modify the data table `.stories.js` files. When a commit is pushed to this PR the storybook will be deployed to a PR deploy preview via netlify in the comment/links above.

**Comment by pmweeks98** [comment]
@tay1orjones @jnm2377 have updated storybook to have a table with unsortable columns on sortable table, table size is set to xl now, not sure if that is desired, can ye have a look?

**Comment by tay1orjones** [comment]
@pmweeks98 Cool! Yeah I can see the fix when I toggle the line-height off in the dev tools. They don't align correctly and then with the fix turned on it aligns exactly as it should.


https://user-images.githubusercontent.com/3360588/171498494-d070c07e-035e-4bd5-91d4-8de26cfec973.mov

Thanks for adding the story to demo the fix. I think in this case we can probably remove it now since there isn't much of a need for a story demonstrating this beyond to validate this bug. Once removed this looks good to me to merge 👍

**Comment by pmweeks98** [comment]
@tay1orjones removed

**Review by tay1orjones — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
