### PR TITLE
improve Search (and Search in data table toolbar) aria labels

### PR DESCRIPTION
**Pull request by lovemecomputer**
addresses #3000 
usage note added in https://github.com/carbon-design-system/carbon-website/pull/1837

---

**changes**
- removes unnecessary and undesired aria props, avoiding redundant voiceover readout.

thanks for consult @dakahn !

**testing**
- preview Search component and DataTable component in storybook, and test with screen reader.

Note: In VoiceOver on Mac, if the search input's label text and placeholder text differ, both will be read.

### CODE REVIEW

**Review by dakahn — APPROVED** [review]
Looks great! Sounds great on VO for latest macOS. Gave it a quick check on DAP (internal AVT tool) and looks all clear using the June 2019 ruleset 👍

**Comment by lovemecomputer** [comment]
@dakahn rad, thanks! i'm syncing up with josh tomorrow about test updates, so i'll hopefully be resolving these errors tomorrow morning/afternoon and be ready to merge :)

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @lovemecomputer!

**Comment by asudoh** [comment]
@lovemecomputer Would you be able to update the tests? Thanks!

**Comment by lovemecomputer** [comment]
@asudoh will do! @joshblack and i are  going to pair tomorrow and go over this. thanks!

**Pull request merged**
