### PR TITLE
Stylelint16

### LINKED ISSUE #16604: [Feature Request]: Update stylelint-config-carbon for Stylelint 16
### The problem

Stylelint has switched to ESModules as have many maintained packages.

This has a knock on effect of requiring various other packages to be updated including some internal ones to replace module.exports, require etc.

It may even expand to update Carbon to ESM.

### The solution

Update the Carbon packages to use Stylelint 16.

### Examples

_No response_

### Application/PAL

_No response_

### Business priority

None

### Available extra resources

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by lee-chase**
Closes #16604 

Updates to stylelint 16

#### Testing / Reviewing

Running the script `lint:styles`

NOTE: Still work to do, many stylistic rules deprecated in 15 gone in 16.

See - https://stylelint.io/migration-guide/to-15#deprecated-stylistic-rules

### CODE REVIEW

**Comment by lee-chase** [comment]
- stylelint-config-prettier is obsolete in stylelint 16.

https://github.com/prettier/stylelint-config-prettier/issues/139

**Comment by tay1orjones** [comment]
IIRC When Stylelint 15 came out @tw15egan had a hard time detangling it from prettier v3, which caused https://github.com/carbon-design-system/carbon/pull/14744 to not make it through.

**Comment by lee-chase** [comment]
> IIRC When Stylelint 15 came out @tw15egan had a hard time detangling it from prettier v3, which caused #14744 to not make it through.
> 
> If we need to update prettier alongside this we could try to do so, but it'll reach into more packages within `./config`

Prettier V4 is still in alpha, with no releases in the last six months. Not sure we should tie it to Storybook 16.

**Comment by tay1orjones** [comment]
Closing in favor of #17770

**Pull request closed without merging**
