### PR TITLE
feat(dropdown): added inline dropdown, style changes to dropdown, fixed link in data table readme

### LINKED ISSUE #200: Inline Select - add docs about width
The caret for inline select should no be that far away from the text. There should be 10px of padding between the two. I realize that it is adjusting for the lengthier option from the dropdown menu (based on a character count I believe) but is there anyway to reduce the space? With that large amount of space it is difficult for people to see the association between the two elements.
screen shot 2017-06-23 at 10 19 25 am

### LINKED ISSUE #694: Add Inline Dropdown
## Detailed description

Inline Dropdown is missing from the vanilla repo, it needs to be added so we can add it to the website.
It is present in the [React repo](http://react.carbondesignsystem.com/?selectedKind=DropdownV2&selectedStory=inline&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel).

Ref https://github.com/carbon-design-system/design-system-website/issues/177

### PR DESCRIPTION
**Pull request by marijohannessen**
## Overview

Closes #694 
Closes #200 

- Added Inline Dropdown as this was missing from the vanilla repo (only available as the Multi-select component)
- Made some style changes to the Dropdown component to match the Design Kit
- Changed the filename of Inline Select so it shows up in the dev environment
- Added in a link in the Data Tables README

### Added

- `dropdown--inline.html`

### Changed

- `inline-select.html` to `select--inline.html`
- `README.md` for `data-table-v2`

## Testing / Reviewing

Make sure inline Dropdown works as expected.

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Huge thanks @marijohannessen for introducing this variant! I’m excited when I saw the one in our dev env! A couple of questions:

* Is the style changes to non-inline dropdown intentional?
* Should the darkened hover over be shrunk to the length of text?

**Review by alisonjoseph — APPROVED** [review]
Looks good, the only question I have is about the hover/focus state width? Should it be 100% width? Or only as wide as the text/carat? Looks like this might be an existing issue, I checked the react storybook and it looks the same. 
screen shot 2018-05-01 at 10 31 24 am

**Comment by marijohannessen** [comment]
@asudoh yes, the style changes are intentional 🙂
@alisonjoseph I noticed that too, but I'm not sure if I can get it to just hover over the text and keep it accessible. I'll give it a try though!

**Comment by marijohannessen** [comment]
Alright, was able to fix it @asudoh and @alisonjoseph ! 🙂

**Comment by alisonjoseph** [comment]
@marijohannessen If you choose an option now the arrow disappears. 😕 
screen shot 2018-05-02 at 11 49 23 am

**Comment by marijohannessen** [comment]
Oh no! Will fix! 🙂

**Review by alisonjoseph — APPROVED** [review]
🎉 Looks good!

**Review by asudoh — COMMENTED** [review]
It’s great that the trigger button is now shrunk to the size of text, @marijohannessen! 🎉 It’d be great if the JavaScript code doesn’t have to take care of the arrow icon - I put a possible approach to: https://github.com/asudoh/carbon-components/commit/879187f82898d3299800be42247b8211e6ced438

**Pull request closed without merging**
