### PR TITLE
fix(_header.scss): fixed head base nav with mobile first approach

### LINKED ISSUE #5157: Header Base w/navigation not displaying navigation at breakpoint width 1056px
## What package(s) are you using?

- [x] `carbon-components@10.9.1`
- [x] `carbon-components-react@7.9.1`

## Describe the bug
When screen width is at exactly 1056px (breakpoint transition) navigation is not visible.

## To Reproduce

* Open browser and navigate to [Header Base w/navigation demo page](http://react.carbondesignsystem.com/iframe.html?id=ui-shell--header-base-w-navigation)
* Open developer tools
* Set "Responsive" mode and width to 1056px
* No navigation links are displayed
* Expected behavior
* Layout should display desktop navigation links from this breakpoint and greater.

image

### PR DESCRIPTION
**Pull request by fsegu002**
Closes: #5157 

This issue describes how no navigation is shown exactly at 1056px width. This is due to how media queries are applied. 

#### Changelog

**Changed**

- desktop nav was modified to be hidden by default and only displayed at 'lg' or greater width.

@asudoh please review

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, the 1056px viewport width issue appears resolved

**Review by tw15egan — APPROVED** [review]
Looks fixed, thanks for contributing 👍 ✅

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! Thank you for contributing! 🎉

**Review by jeanservaas — APPROVED** [review]
@asudoh looks like react deploy failed but I really don't want to hold this PR up, seems like a clear fix, I will trust that it's just a matter of getting the menu items to appear correctly at the exact 1056 breakpoint.

**Pull request merged**
