### PR TITLE
feat(spacing): change layout variables to spacing

### LINKED ISSUE #5602: Update spacing scale and deprecate our layout scale
When talking to @jeanservaas and @vpicone, it came up that it would be worth consolidating the values of layout into our spacing scale and deprecating the layout scale that we currently have.

This issue is to handle implementing any changes to the spacing scale that need to happen along with deprecating the layout scale.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5602

Deprecates the `layout` tokens in favor of a single `spacing` scale. This change will need to coincide with a website change to update the new/removed tokens

https://www.carbondesignsystem.com/guidelines/spacing/overview#spacing-scale

https://www.carbondesignsystem.com/guidelines/spacing/overview#layout-scale

#### Changelog

**New**

- `$spacing-13` to match the largest `layout` variable

**Changed**

- Changed all internal references of `$layout` to `$spacing` (seemed to only be in Data Table styles)
- Added deprecation notes to old `layout` variables
- Added comment to remove `layout` from `theme` package in v11

#### Testing / Reviewing

- Ensure DataTable renders as expected
- Try using `$spacing-13`

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me

**Comment by kingtraceyj** [comment]
@tw15egan looks good from a visual stand point. should we update the [docs page on the website](https://www.carbondesignsystem.com/guidelines/spacing/overview#spacing-scale) before you merge or do you think we could do that in the next few weeks.

**Comment by tw15egan** [comment]
We can just hold off on merging this until we update the website so we're synced between the website and whats in code 👍🏻

**Review by kingtraceyj — APPROVED** [review]
looks good! 💥

**Review by joshblack — APPROVED** [review]

**Pull request merged**
