### PR TITLE
feat(number-input): change error state for number input x

### PR DESCRIPTION
**Pull request by aledavila**
Partial https://github.com/IBM/carbon-components/issues/1535

#### Changelog

**New**

- icon in error state

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @aledavila!

**Review by emyarod — APPROVED** [review]

**Comment by emyarod** [comment]
just curious, was the lockfile change caused by an update to the icons package?

**Comment by aledavila** [comment]
@emyarod good question. No for some reason that happened before i changed anything. When I ran yarn it changed it changed it. I can remove that file though

**Comment by emyarod** [comment]
@aledavila ok gotcha, it should be alright. thanks for the info!

**Pull request merged**
