### PR TITLE
fix(date-picker): update selected range background colors

### LINKED ISSUE #6214: Date picker using outdated color token for selected days in range
originally reported in Slack

## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

when making a range selection in the date picker, the highlight color for the selection seems incorrect in the dark themes

> Is this issue related to a specific component?

date picker

## Additional information

image

### PR DESCRIPTION
**Pull request by emyarod**
Closes #6214

This PR updates date picker token usage to better accommodate dark themes

#### Testing / Reviewing

Confirm that the date picker colors are correct, particularly on the G90 and G100 themes

### CODE REVIEW

**Comment by tw15egan** [comment]
The date ranges look good, but I noticed some other a11y issues when reviewing this PR. Let me know if you want me to create a separate issue for these. cc @carbon-design-system/design 

## Start / End Date on g90
Screen Shot 2020-06-08 at 3 40 37 PM
Screen Shot 2020-06-08 at 3 41 42 PM

---

## Current date on g90
Screen Shot 2020-06-08 at 3 46 36 PM
Screen Shot 2020-06-08 at 3 43 19 PM

---

## Current date on g100
Screen Shot 2020-06-08 at 3 46 43 PM
Screen Shot 2020-06-08 at 3 44 16 PM

**Comment by laurenmrice** [comment]
Yes. Only the "current day" should be getting the `link-01` token. The "selected days" should have the `interactive-01` token. And the "range days" get the `highlight` token
Artboard

**Comment by emyarod** [comment]
yeah I misunderstood your original comments about `link-01` color for the day (thought you meant the background of the range start/end vs the text color of the current day)

**Review by dakahn — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
-The highlight, selected day and current day look great. 

-I did notice that the year is not the right color. It should be calling the same color token as the month so it works across themes. Can we also update that? Then we will be good to go.
Screen Shot 2020-06-09 at 11 01 44 AM

**Review by tw15egan — APPROVED** [review]
Contrast looks great, good to go once @laurenmrice comment is fixed 👍 ✅

**Comment by emyarod** [comment]
@laurenmrice those controls appear to be disabled, what's the token for disabled text here?

**Comment by laurenmrice** [comment]
The disabled token is disabled-02. If it is disabled then you should not be able to interact with it and you currently can.

**Comment by emyarod** [comment]
it looks like our disabled styles are just from an old file we carried over from v9, but since it's a bit different from the original issue reported I can tackle that separately

**Review by laurenmrice — APPROVED** [review]
Approving! disabled issues we are going to be solving in a separate pr.

**Pull request merged**
