### PR TITLE
fix Tag component

### PR DESCRIPTION
**Pull request by GoldenFishe**
Closes #

Fix diff height Tag and Tag (with icon) https://github.com/carbon-design-system/carbon/issues/6777

#### Changelog

**Changed**

- Changed height from `1.5rem` to `1.8rem.` Because Tag with icon have `1.8rem` height

### CODE REVIEW

**Comment by GoldenFishe** [comment]
https://github.com/carbon-design-system/carbon/issues/6777 fix

**Comment by tw15egan** [comment]
I believe we need to find a way to reduce the height of the `Filter Tag` button, as Tags are supposed to render at `24px / 1.5rem` 

https://www.carbondesignsystem.com/components/tag/style#structure

**Comment by GoldenFishe** [comment]
Ok. So we need to reduce content height. In Tag with filter we got +4px from "close" button. So I reduce "close" button height from 20px to 16px. And now we have 24px for Tag and 24px for Tag with filter

**Review by joshblack — APPROVED** [review]
Looks good with the changes, curious what you think @tw15egan 👀

**Review by tw15egan — APPROVED** [review]
Looks great! Thanks for taking the time to fix this 👍  ✅

**Pull request merged**
