### PR TITLE
fix(tile): update color tokens

### LINKED ISSUE #1912: [Audit] Tile Component
- [x] Selected: on-click border should be gray 100, `$ui-05` or `$interactive-02` token
- [x] Selected: hover icon color should be `$icon-02`

screen shot 2019-02-25 at 4 28 31 pm

fyi @laurenmrice

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #1912

#### Changelog

**Changed**

- Updated color tokens for checkmark and selected border

#### Testing / Reviewing

Make sure tile matches latest spec for v10

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- Can we make the tile larger in the single examples? It is rendering a little small ( in the sketch file it is w 309px x h 165px)
- For expandable tile we do not need a focus box around the chevron, we only need it around the entire tile.
- For selectable tile the border needs to be color #171717 for on-click.

**Comment by alisonjoseph** [comment]
@laurenmrice ~what token should I use for the border on click?  $interactive-02?~ realized I updated it in the wrong place the first time 🤦‍♀️ should be good now

Also, is 309px annd 165px the min height/width the component should be set to? By setting these new width/heights we are effectively suggesting it shouldn't be smaller than these values.

This is the current values.
min-width: 8rem  (128px)
min-height: 4rem (64px)

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Border color looks good now ! And we can keep the size you have for the tile. I see v9 is that way as well.

- One thing, in Chrome i am still getting a focus box around the chevron icon.

**Comment by alisonjoseph** [comment]
updated!

**Review by tw15egan — APPROVED** [review]
🎉 👍

**Review by laurenmrice — APPROVED** [review]
looks great ! 🎉

**Pull request merged**
