### PR TITLE
feat: icons-new-december

### PR DESCRIPTION
**Pull request by conradennis**
Submitting new and updated UI icons from December
all updates and additions approved by BXD

47 net new icons
5 updated icons
4 renamed/removed icons
updated categories.yml with additions and updates
updated ui-icon-master.ai with additions and updates

*note that `lightning` `moon` `sun` are all duplicates of existing icons that have been renamed and added to the `planning > weather` category*

#### Changelog

**New**

- 32/watson-health/scalpel--cursor.svg
- 32/watson-health/scalpel--lasso.svg
- 32/watson-health/scalpel--select.svg
- 32/watson-health/text-annotation-toggle.svg
- 32/cloudy.svg
- 32/deploy.svg
- 32/gift.svg
- 32/hail.svg
- 32/haze.svg
- 32/haze--night.svg
- 32/interactions.svg
- 32/jump-link.svg
- 32/lightning.svg
- 32/mixed-rain-hail.svg
- 32/moon.svg
- 32/mostly-cloudy.svg
- 32/mostly-cloudy--night.svg
- 32/nominal.svg
- 32/not-available.svg
- 32/ordinal.svg
- 32/partly-cloudy--night.svg
- 32/rain.svg
- 32/rain--drizzle.svg
- 32/rain--heavy.svg
- 32/rain--scattered.svg
- 32/rain--scattered--night.svg
- 32/rain-drop.svg
- 32/sleet.svg
- 32/smoke.svg
- 32/snow.svg
- 32/snow--blizzard.svg
- 32/snow--heavy,svg
- 32/snow--scattered.svg
- 32/snow--scattered--night.svg
- 32/snowflake.svg
- 32/sun.svg
- 32/tag--edit.svg
- 32/temperature--frigid.svg
- 32/temperature--hot.svg
- 32/thunderstorm.svg
- 32/thunderstorm--scattered.svg
- 32/thunderstorm--scattered--night.svg
- 32/thunderstorm--severe.svg
- 32/thunderstorm--strong.svg
- 32/tornado.svg
- 32/tropical-storm.svg
- 32/windy.svg
- 32/windy--dust.svg
- 32/windy--snow.svg
- 32/windy--strong.svg
- 32/wintry-mix.svg

**Changed**

- 32/asleep.svg
- 32/asleep--filled.svg
- 32/fog.svg
- 32/hurricane.svg
- 32/partly-cloudy.svg

**Removed**

- 32/cloud--lightning.svg (renamed to 32/thunderstorm.svg)
- 32/cloud--rain.svg (renamed to 32/rain.svg)
- 32/cloud--snow.svg (renamed to 32/snow.svg)
- 32/sunny.svg (renamed to 32/sun.svg)

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
looks good to me ! love the new additions 🎉

**Review by abbeyhrt — APPROVED** [review]

**Comment by joshblack** [comment]
Hey @conradennis! Seems like we have the following issue coming up:

```
Error: The following icons are missing or an error has occurred:
[
  "cloudy",
  "deploy",
  "gift",
  "hail",
  "haze--night",
  "haze",
  "jump-link",
  "lightning",
  "mixed-rain-hail",
  "moon",
  "mostly-cloudy--night",
  "mostly-cloudy",
  "not-available",
  "rain--drizzle",
  "rain--heavy",
  "rain--scattered--night",
  "rain--scattered",
  "rain-drop",
  "rain",
  "sleet",
  "smoke",
  "snow--blizzard",
  "snow--heavy",
  "snow--scattered--night",
  "snow--scattered",
  "snow",
  "snowflake",
  "sun",
  "thunderstorm--scattered--night",
  "thunderstorm--scattered",
  "thunderstorm--severe",
  "thunderstorm--strong",
  "thunderstorm",
  "tornado",
  "tropical-storm",
  "text-annotation-toggle",
  "windy--dust",
  "windy--snow",
  "windy--strong",
  "windy",
  "wintry-mix"
]
```

Were these part of the renames/changes that you were talking about?

**Review by joshblack — CHANGES_REQUESTED** [review]
For icons that are removed/renamed, I think we'll need to keep the originals in codebase as the removal will be a breaking change 😞 For ones that we want to remove, we should flag them as deprecated so folks know not to use them and that they'll be removed.

**Comment by conradennis** [comment]
@joshblack only 4 icons were removed/renamed. not sure why the whole set of icons is causing a problem. 

The renamed icons are the original files, it's just that github recognizes them as removed when they're renamed, so should we add those four back into the repo under their old names?

**Review by joshblack — APPROVED** [review]

**Pull request merged**
