### PR TITLE
fix(DatePicker): change VO cursor order

### PR DESCRIPTION
**Pull request by asudoh**
This change makes VO cursor moves to calendar dropdown as the next element to date picker input.

Also contains the following changes:

* Ensures hitting tab key on date picker input focuses on calendar dropdown, to align to the new VO cursor behavior
* Make the arrow for previous/next month focusable
* Moves an old Flatpickr plugin code to a separate file

Refs #5310.

#### Changelog

**New**

- An ARIA attribute to make VO cursor moves to calendar dropdown as the next element to date picker input.
- A Flatpick plugin to make tab/shift-tab key behaviors align to such new VO cursor behavior.

**Changed**

* Make the arrow for previous/next month focusable.
* Moves an old Flatpickr plugin code to a separate file.

#### Testing / Reviewing

Testing should make sure our date picker is not broken.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
> Ensures hitting tab key on date picker input focuses on calendar dropdown, to align to the new VO cursor behavior

in the range date picker, pressing <kbd>Tab</kbd> while the range start input is focused moves focus to the range end input

Kapture 2020-02-26 at 15 15 40

I'm also unable to focus on the previous/next month arrow buttons with the keyboard only. they are correctly announced when focused with the mouse though

**Comment by asudoh** [comment]
@emyarod Thank you for reviewing!

> in the range date picker, pressing Tab while the range start input is focused moves focus to the range end input

I think it’s the intended behavior, wondering what you expected?

> I’m also unable to focus on the previous/next month arrow buttons with the keyboard only.

Good point, I saw that Flatpickr steals shift-tab key to focus on `<input>`. Made a change to disable that so that shift-tab key from a day in calendar dropdown focused on will focus on an arrow button.

**Comment by emyarod** [comment]
regarding pressing Tab while focused on the range start input, I just wanted to clarify the statement in the PR description ("Ensures hitting tab key on date picker input focuses on calendar dropdown, to align to the new VO cursor behavior"). the current behavior makes sense to me so no change is needed

**Review by emyarod — APPROVED** [review]
looks good to me now that the prev/next month buttons are accessible

**Comment by joshblack** [comment]
Couldn't reproduce in latest netlify so it seems like this PR might be adding in this behavior? Let me know if this is already a known issue 🤔  To reproduce, was using VO + Arrow right to try to navigate to next item but the changes seem to map it back to the end range input

demo

**Comment by asudoh** [comment]
> To reproduce, was using VO + Arrow right to try to navigate to next item but the changes seem to map it back to the end range input

In case it's what's the question is about, it's the biggest thing that this PR addresses:

date-picker-vo

**Comment by joshblack** [comment]
@asudoh I think what I'm observing is a difference in behavior between Safari and Chrome, in Chrome it seems to work but in Safari it does not

demo

**Comment by asudoh** [comment]
Thank you for clarifying it's an issue with a specific browser. Fixed.

**Comment by joshblack** [comment]
Cool!

With respect to the broader changes, what spec are we trying to reference for the intended keyboard behavior? Having a hard time figuring out what the intended keyboard flow is here 👀

**Comment by asudoh** [comment]
If something like [WAI-ARIA Authoring Practices](https://www.w3.org/TR/wai-aria-practices-1.1/examples/dialog-modal/datepicker-dialog.html) is in mind, our date picker or this PR doesn't refer to any of that because none of them matches our UX.

That said, I think it's better to highlight what this PR does:

* Makes sure the sequential focus order as well as screen reader cursor order is start date -> end date -> calendar dropdown. In this way, we can guide screen reader users to use regular way of navigation to read the calendar dropdown contents
* Makes sure calendar dropdown has the following sequential-focusable elements:
  * One of the dates
  * Previous/next months arrows
  * Month/year selectors

**Comment by dakahn** [comment]
To @joshblack's point -- there's not a lot of really solid examples of a truly accessible datepicker with a calendar dropdown, but I tend to reference [this Deque example](https://dequeuniversity.com/library/aria/date-pickers/sf-date-picker) based off of jQuery UI's (since it has similar functionality). 

One thing I noticed on the Deque example is that down arrow focuses the dates and you use arrow keys to move about the grid selecting dates etc, but tab order **is still respected**. Meaning the next tabbable item once the calendar has been expanded is (and in my opinion _should be_) the previous/next month controls. 

On ours (at least on the browsers I'm currently testing on Windows/Chrome in Windows 10) tab closes the calendar and moves to the next focusable element

UPDATE
[This APG 1.2 Calendar Datepicker](https://w3c.github.io/aria-practices/examples/dialog-modal/datepicker-dialog.html) passed to me by @snidersd does _not use_ the above keyboard interaction pattern. 😕

**Comment by snidersd** [comment]
@dakahn  The date picker is failing [WCAG 1.3.2 Meaningful Sequence](https://www.w3.org/TR/UNDERSTANDING-WCAG20/content-structure-separation-sequence.html). There are keyboard only navigation issues as well on macOS w/Chrome such as, the down Arrow takes the user into the calendar but the focus is not on the current date, as well as needing to hit the Enter key twice in the first calendar to return to the date field, but only once in the second calendar.  

The following issues appear when testing with VO on macOS with Chrome:
1. Tab to the date field VO announces the first date picker label and text field w/ format mm/dd/yyyy as expected. Do not select a date. 
2. Tab to the end date field and the date picker label and that its a text field w/ format mm/dd/yyyy as expected. 
3. Tab again and the focus goes to the Arrow keys in the calendar, which are announced as "button". 
**Expected result:** Labels should indicate what the button does "previous month" button and "next month" button. 
4. Tab again and the user is on the current date. If a date is selected it populates the first date field.
**Expected result:** The second date field would be populated. Note: The behavior changes, if the first date had been selected then the end date would have populated.  
5. Tab back to the first date field and then Arrow down. The focus remains on the text field.
**Expected result:** The focus should move down into the calendar.
6. Arrow down a second time and the focus is in the calendar but not on the current date. It is one week later. (3/13)
**Expected result:** The focus should be on the current date when a date has not been selected yet. 
7. Arrow down again to the next week's date and VO does not announce the date. (3/20)
**Expected result:** VO should announce each date in the grid. 
8. Arrow down a fourth time and VO announces the next weeks date as expected. (3/27)
7. Shift-tab and the focus goes to the top of the calendar "next month" button.
**Expected result:**  The focus should go back to the text input date field. Note: The previous and next month buttons are skipped in the navigation sequence when entering the calendar from the first date field.

**Comment by asudoh** [comment]
@dakahn

> I tend to reference this Deque example based off of jQuery UI's (since it has similar functionality).

Created #5573 to track that.

@snidersd Thank you for the test.

* Created a quick fix for 3., 5., 6. and 9. One of those fixes seems to have fixed 7. as well.
* Created #5572 for 4.

date-picker-seqfocus

**Comment by abbeyhrt** [comment]
This looks good to me and reads pretty well in Chrome and Safari in VO! Do we know how it reads for JAWS on Windows? I don't have a Windows machine to test it.

**Comment by dakahn** [comment]
@asudoh Can we put a pin in this PR until we can get consensus on what our target is from an accessibility standpoint for this component from a UX and dev standpoint?

**Comment by dakahn** [comment]
@abbeyhrt Testing with JAWS 2020 on Windows 10 in Firefox and the calendar is not read as having a range input -- when the first input is focused the calendar dropdown is not announced. If the user hits tab the next (ending range) input is focused which sounds identical to the first and so it seems like the first input is just being re-read.

**Comment by dakahn** [comment]
Testing with NVDA on Windows 10 we hear it described identically to JAWS, but when the user enters the calendar dropdown NVDA's arrow controls clash with our day selection controls. So if i'm on the 10th of December using the arrow controls each numbered digit will be read. Strangely as well up and down arrow seems to move days laterally and not vertically like I'd expect.

**Comment by joshblack** [comment]
Hey there! Going through the PR backlog today and am clearing out PRs that have been up for a while 👀

**Pull request closed without merging**
