### PR TITLE
feat(Search): introduce large search back

### PR DESCRIPTION
**Pull request by asudoh**
Refs #3457.

The styling code is covered by: #4237

#### Changelog

**New**

- `lg` search variant (back).
- `size` prop which takes `xl`, `lg`, or `sm`.

**Changed**

- Deprecated `small` prop for the sake of `size`.

#### Testing / Reviewing

Testing should make sure `<Search>` and `<TableToolbarSearch>` are not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me now that #4237 is merged in, pending design approval

**Review by laurenmrice — CHANGES_REQUESTED** [review]
The close icon is 2px to the left when the hover/focus is activated around it. It should be in the complete center when that happens.

Screen Shot 2019-10-09 at 11 44 38 AM

**Review by jnm2377 — APPROVED** [review]

**Comment by asudoh** [comment]
@laurenmrice Good catch - Fixed.

**Review by laurenmrice — COMMENTED** [review]
In Vanilla it still needs to come over one to the left, its slightly off. Then we should be good. I couldn't review React yet because the build failed.

**Comment by asudoh** [comment]
> In Vanilla it still needs to come over one to the left, its slightly off.

@laurenmrice Is it about the position of X icon, or something else...? Thanks!

**Comment by laurenmrice** [comment]
@asudoh Yes sorry, the x icon needs to come over a pixel to the left, its still not in the center.

**Comment by asudoh** [comment]
No worries @laurenmrice, thank you for clarifying - Fixed.

**Review by laurenmrice — APPROVED** [review]
Looks good ! thank you 🙌

**Pull request merged**
