### PR TITLE
fix(structured-list): fixed column header text size

### PR DESCRIPTION
**Pull request by tay-aitken**
Addressing this issue: https://github.com/carbon-design-system/design-system-website/issues/183

Changed the header size from `zeta` (14px) to `omega` 12px

my first PR in carbon-components 😝

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Welcome aboard to `carbon-components` @tay-aitken! 🎉 The change LGTM basically. The only thing is that we don’t put `package-lock.json` in our source control, esp given our Yarn preference. Thanks!

**Comment by tay-aitken** [comment]
@asudoh deleted the file. Thanks!

**Review by asudoh — APPROVED** [review]
LGTM :+1: - Thanks @tay-aitken for making the change!

**Review by tw15egan — APPROVED** [review]
Woo thanks for the fix @tay-aitken! 🎉

**Pull request merged**
