### PR TITLE
chore: introduce Fractal

### PR DESCRIPTION
**Pull request by asudoh**
## Overview

This PR renews the development (demo) environment.

### Added

1. Harvests component metadata using [Fractal](https://fractal.build/) tool. Fractal has more features than just harvesting metadata, that would let us create the entire development environment, but abandoned because:
  a. The default theme is *not* a single-page app
  b. The default theme uses [Nunjunks template library](https://mozilla.github.io/nunjucks/), which is very different from how we have composed our development environment and/or design system website
  c. Fractal lets you create theme from scratch, but does not have enough documentation for that
  d. Lack of flexibility integrating custom build env
  e. Lack of flexibility configuring its Express server
2. Puts more content than just the live demo, especially including documentation - By importing several UI contents from design system website. This demonstrates how we'd be able to (further) automate building our documentation site.

### Removed

@marijohannessen I removed the live demo template for grid because it appears that they can be merged together after cleaning up default live demo template, but please don't hesitate to let me know if you see it's not the case.

### Changed

Names of several live demo HTML files. Fractal requires one of the following naming rules, for components with variants:

* No HTML file has the component name in their names
* One of the HTML file has the exact same name as the component name, and others has `${componentName}--${variantName}` format

## Testing / Reviewing

Testing should make sure no live demo of any component is broken.

### CODE REVIEW

**Comment by joshblack** [comment]
Having a hard time installing the dependencies for this PR @asudoh, seems like something to do with `node-sass` on my machine 🤔

**Comment by joshblack** [comment]
Ah, was the Node.js version. False alarm!

**Comment by asudoh** [comment]
^ @joshblack Thank you for trying it out! For our record - Travis had a similar error, which was resolved when I deleted `node_modules` cache.

**Comment by joshblack** [comment]
Love the changes! It's unfortunately that Fractal doesn't behave the way that we want it to. I think it does bring up some things that we should talk about, though. Namely the handlebars bit that you mentioned.

We've been getting requests from teams to template-ize our work, do you see us being able to support that with the current changes?

On a separate note, is there any way to control the sizes of the previews so that we can view full-screen, or at a specific breakpoint?

**Review by joshblack — APPROVED** [review]
Overall looks great, only question is about controlling the size of the previews 😄

**Comment by asudoh** [comment]
@joshblack You brought up a good question, was wondering why you brought up Fractal and you confirmed one in my guess. Given that, I’ll try creating several NPM packages that would help people scaffold projects like carbon-components. An obvious one in my PR is a set of React components that brought over from design system website.

Wrt size of previews - The quickest way is hitting “view full render” link. Also the width of preview will correspond with the viewport width outside the preview `<iframe>`. But please don’t hesitate to bring up if you have anything else in mind. Thanks!

**Review by marijohannessen — APPROVED** [review]
This is really cool! Makes it much easier to get an overview of each component. And I'm excited to see what we can add-on to it! I'm okay with removing the grid example, it works fine the way it's implemented now.

**Comment by tw15egan** [comment]
Looks awesome! Thanks for adding this, @asudoh! 🙂

**Review by tw15egan — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]
This looks great!

**Pull request merged**
