### PR TITLE
chore(react): update storybook and react

### PR DESCRIPTION
**Pull request by joshblack**
Update storybook and react devDependencies in `carbon-components-react`.

#### Changelog

**New**

**Changed**

- Update storybook dependencies to 5.1.11
- Update React dependencies to 16.9.0

**Removed**

### CODE REVIEW

**Review by vpicone — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Review by emyarod — COMMENTED** [review]
it looks like the React upgrade is causing a few test failures

**Review by emyarod — APPROVED** [review]
looks good to me now

**Review by emyarod — COMMENTED** [review]
test suite is passing but it looks like the react build step is failing now?

**Review by jnm2377 — APPROVED** [review]

**Pull request merged**
