### PR TITLE
feat(progress-indicator): add vertical progress indicator to react

### LINKED ISSUE #5141: [progress indicator] add vertical variant to react
We have vertical progress indicator in vanilla, now we just need it in react.

One change I would like to make from the previous spec for vanilla, is making the vertical height of the sections 58px, to accommodate a 24px padding on the bottom if there is optional text present.

---------------------------------------------------------------------------------------------------

Spec:
Screen Shot 2020-01-22 at 2 12 33 PM

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5141

Adds in the vertical `ProgressIndicator` variation to React. Enabled by passing in `vertical` to the `ProgressIndicator` component. 

#### Changelog

**New**

- Vertical variation of the `ProgressIndicator`

**Changed**

- Modified some styles that account for an extra `div` in the React markup of `ProgressIndicator`

#### Testing / Reviewing

Check the Storybook and ensure the Vertical variation looks the same as the Vanilla version.

### CODE REVIEW

**Comment by tw15egan** [comment]
Question for @laurenmrice, did we want to reduce the padding between Vertical steps?

Current (6rem): 
Screen Shot 2020-01-22 at 3 31 06 PM

Proposed (3.625rem):
Screen Shot 2020-01-22 at 3 30 56 PM

**Review by asudoh — APPROVED** [review]
Thank you for jumping in @tw15egan! I wonder `vertical` thing can be a knob, but I'm open for either way.

**Comment by aagonzales** [comment]
@tw15egan I think it just needs to always have that 24px of padding-bottom and not a set height incase there are more lines in which case the text would wrap.

image

**Comment by tw15egan** [comment]
@asudoh updated and changed it to a knob. Also added in another knob for the Label text so that it is easier to test long text blocks.

**Review by aagonzales — APPROVED** [review]
LGTM

**Review by dakahn — APPROVED** [review]
Looks good to me. Checked it out on Edge, Firefox, and Chrome latest on Windows 10

**Comment by asudoh** [comment]
Thanks @tw15egan for the update!

**Pull request merged**
