### PR TITLE
chore(hbs): add icon helper for handlebars template

### PR DESCRIPTION
**Pull request by joshblack**
Add icon helper for handlebars template during development. Can use in `.hbs` files by calling:

```hbs
{{ carbon-icon 'IconName' aria-label="Label" another-attribute="bar" }}
```

Full README is available here: https://github.com/IBM/carbon-elements/blob/master/packages/icons-handlebars/README.md

#### Changelog

**New**

- `@carbon/icons-handlebars` helper introduced

**Changed**

- `tools/templates.js` now updated to register icon helper

**Removed**

### CODE REVIEW

**Comment by asudoh** [comment]
Thanks @joshblack for proposing this! **Note**: A discussion on avoiding additional Handlebars dependency to templates that we may ship in future is going on offline. Need that to be resolved before this PR is merged.

**Review by dakahn — APPROVED** [review]
👍

**Comment by joshblack** [comment]
TODO

- [x] Add docs for usage
  - [x] How to include
  - [x] Finding a name
  - [x] Feature flags

**Review by aledavila — APPROVED** [review]
🎉

**Review by jnm2377 — APPROVED** [review]
Looks great! Thanks for that awesome documentation! 🔥

**Review by dakahn — APPROVED** [review]
This documentation is freakin' great. Love the FAQ. Way to raise the standard.

**Review by lovemecomputer — APPROVED** [review]

**Comment by lovemecomputer** [comment]
agreed, good stuff!

**Comment by shinytoyrobots** [comment]
I appreciate that there was some debate over this PR. @joshblack has expanded the documentation/context, to positive effect. It fulfils the business requires from design as outlined by @chrisconnors-ibm.

**Pull request merged**
