### PR TITLE
fix(progress-indicator): use circle--filled icon

### LINKED ISSUE #5584: [progress indicator] add circle--filled icon for current state
- Need to add `circle--filled` 16px icon for the current state that Conrad made, so all of the states will be pulling in icons from our repo. https://carbon-elements.netlify.com/icons/examples/preview/#32%2Fcircle--filled%20(Downsized%20to%2016)

- Also I noticed the icons themselves are not aligning to the text, they are a little high:
Artboard

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5584

Uses the new `circle--filled` icon in `ProgressIndicator`. Also bumps the `SVG` icons down 1px to better align to text.

#### Changelog

**New**

- `CircleFilled16` is used for the in-progress step. 

**Changed**

- Added `1px` of top margin on svg icons

**Removed**

- `RadioButtonChecked16` and associated styles that were used to fill the icon

#### Testing / Reviewing

Ensure the `ProgressIndicator` renders as expected

### CODE REVIEW

**Review by laurenmrice — COMMENTED** [review]
- The 1px down for the icons looks good 👍🏻 can you also do this for the vertical variant as well?

- The blue bars for current and completed states need to be `interactive-04`

**Comment by tw15egan** [comment]
@laurenmrice done 👍

**Review by joshblack — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
perfecto! thank you 🎉

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan!

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
