### PR TITLE
fix: extra arrow in tab component on resize

### LINKED ISSUE #16484: [Bug]: Extra Arrow is Visible in Tabs Component on resize
### Package

@carbon/react

### Browser

Chrome, safari, firefox

### Package version

V11.57.0

### React version

_No response_

### Description

An extra arrow is visible in Tabs component on window resize.

https://github.com/carbon-design-system/carbon/assets/146315451/159e88d0-44a7-4762-bf83-8532481e6669

Additionally there is a second related bug [[1](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1715860665973839), [2](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1715863307911929)] where

> There is an unnecessary left arrow (nav button) that is appearing when you click on the last item of the tabs. This appears only in firefox browser.
This is reproducible in the carbon storybook playground. https://react.carbondesignsystem.com/?path=/story/components-tabs--playground

https://github.com/carbon-design-system/carbon/assets/3360588/527bdea2-d500-446f-b988-6c3f7f88259a

### Reproduction/example

Both are reproducible in storybook

### Steps to reproduce

Resize the Tabs window to a small size so that it should display an arrow for the tabs. Now resize the window to original size, Tab will not disappear.

### PR DESCRIPTION
**Pull request by preetibansalui**
Closes #16484 

Fix: Extra arrow is visible in Tab component on resize

#### Testing / Reviewing

1. Resize the screen to small size so that scroll is visible.
2. It should display the arrow in tabs.
3. Now resize it to normal size.
4. It should remove the arrow as well.

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
This looks great in Chrome, however is still broken in Firefox.
Screenshot 2024-06-04 at 7 15 46 AM
Screenshot 2024-06-04 at 7 15 52 AM

**Review by tay1orjones — CHANGES_REQUESTED** [review]
Still seeing some issues in chrome with the left arrow. It's not overlaying the tabs properly and doesn't seem to be clickable in certain situations. Selecting the tabs themselves does cause it to update the scroll position but it doesn't appear the button is actually being clicked

https://github.com/carbon-design-system/carbon/assets/3360588/de50b212-196c-473c-80f4-a08536e793d6

**Comment by preetibansalui** [comment]
> Still seeing some issues in chrome with the left arrow. It's not overlaying the tabs properly and doesn't seem to be clickable in certain situations. Selecting the tabs themselves does cause it to update the scroll position but it doesn't appear the button is actually being clicked
> 
>  CleanShot.2024-06-05.at.13.30.28-converted.mp4

Thanks Taylor, I didn't checked that functionality bcs the issue was related to normal screen and arrow should not be visible. Let me check the functionality part.

**Comment by preetibansalui** [comment]
fixed the left arrow issue although I feel sometimes when we play with arrows, it remove the arrows bcs of some calculations when all tabs are visible (not fully), I will raise a separate issue for this.

**Review by alisonjoseph — APPROVED** [review]
Looks to be working correctly now, I did tag design for a visual review also.

**Review by tay1orjones — APPROVED** [review]

**Comment by tay1orjones** [comment]
Just needs a visual review @alina-jacob

**Review by Kritvi-bhatia17 — COMMENTED** [review]
Hi @preetibansalui, nice work! 🔥
Just wanted to confirm one small thing with you: Is it okay if the arrow still shows up while I'm increasing the screen size (you can see that at 00:05 sec)? It disappears when the mouse is moved out, but I wanted to check if this is acceptable. Everything else looks good to me from a design perspective!


https://github.com/carbon-design-system/carbon/assets/158570656/2a8a444f-d375-440a-861d-65a15b4548a2

**Comment by preetibansalui** [comment]
> Hi @preetibansalui, nice work! 🔥 Just wanted to confirm one small thing with you: Is it okay if the arrow still shows up while I'm increasing the screen size (you can see that at 00:05 sec)? It disappears when the mouse is moved out, but I wanted to check if this is acceptable. Everything else looks good to me from a design perspective!
> 
>  Screen.Recording.2024-06-10.at.4.17.08.PM.mov

Hi Kritvi, It should remove the arrow on a particular width, Here we have a debounce value before we apply changes on window's scroll event, Because of that it remove the arrow after you are done with resizing. I believe it should be acceptable bcs a user should not change window's width like this.

**Comment by preetibansalui** [comment]
> Hi @preetibansalui, this looks neat! 🚀
> 
> Just noticed this one change between the current storybook and the preview that you've shared (please ignore if irrelevant) The arrow button seems to be working fine for the 'default' version, but the **'contained'** version now have a gradient fading from UI colour to **'white'**, earlier it was UI colour to **'transparent'**
> 
> Sharing a screenshot for reference, left is current storybook and right is a screenshot from the preview link shared above: Tab comparison



> Hi @preetibansalui, this looks neat! 🚀
> 
> Just noticed this one change between the current storybook and the preview that you've shared (please ignore if irrelevant) The arrow button seems to be working fine for the 'default' version, but the **'contained'** version now have a gradient fading from UI colour to **'white'**, earlier it was UI colour to **'transparent'**
> 
> Sharing a screenshot for reference, left is current storybook and right is a screenshot from the preview link shared above: Tab comparison

Hi Alina, It looks like an issue, let me look into it. Thanks for pointing this out.

**Review by Kritvi-bhatia17 — APPROVED** [review]
> > ed.mp4
> 
> Thanks Taylor, I didn't checked that functionality bcs the issue was related to normal screen and arrow should not be visible. Let me check the functionality part.

In that case, it looks good to me after addressing the issue Alina mentioned!

**Comment by preetibansalui** [comment]
> > Hi @preetibansalui, this looks neat! 🚀
> > Just noticed this one change between the current storybook and the preview that you've shared (please ignore if irrelevant) The arrow button seems to be working fine for the 'default' version, but the **'contained'** version now have a gradient fading from UI colour to **'white'**, earlier it was UI colour to **'transparent'**
> > Sharing a screenshot for reference, left is current storybook and right is a screenshot from the preview link shared above: Tab comparison
> 
> > Hi @preetibansalui, this looks neat! 🚀
> > Just noticed this one change between the current storybook and the preview that you've shared (please ignore if irrelevant) The arrow button seems to be working fine for the 'default' version, but the **'contained'** version now have a gradient fading from UI colour to **'white'**, earlier it was UI colour to **'transparent'**
> > Sharing a screenshot for reference, left is current storybook and right is a screenshot from the preview link shared above: Tab comparison
> 
> Hi Alina, It looks like an issue, let me look into it. Thanks for pointing this out.

Hi @alina-jacob, I have made the changes, can you please review it again.

**Review by alina-jacob — APPROVED** [review]
Looks good to go @preetibansalui! 🚀 💯

**Pull request merged**
