### PR TITLE
fix(UIShell): Export prop types for components

### PR DESCRIPTION
**Pull request by ibacher**
This is a quick bug-fix that just exports some types for the UIShell sub-components that have been converted to Typescript. Currently, the types end up declared as the argument for the component, but not actually visible to consuming Typescript code.

#### Changelog

**Changed**

- Types for UIShell sub-component props are now exported

#### Testing / Reviewing

In a project using `@carbon/react` and Typescript you should be able to use `SideNavProps` as a type in a consuming component without a TS 4203 error.

### CODE REVIEW

**Comment by ibacher** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tay1orjones — APPROVED** [review]
Thanks for this!

**Comment by denniskigen** [comment]
Good to go, @tay1orjones?

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
