### PR TITLE
feat(Button): add icon-only variant

### LINKED ISSUE #1667: Doc update: Add "Icon only" buttons to the Button examples
If a button contains an icon and does not have any visible text, then the icon needs to have role="img" and a proper aria-label.

For example:
```
<button class="bx--btn bx--btn--primary" type="button">
    <svg class="bx--btn__icon" width="16" height="16" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"
role="img" aria-label="Add">
      <path d="M7 7H4v2h3v3h2V9h3V7H9V4H7v3zm1 9A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" fill-rule="evenodd" />
    </svg>
</button>
```

Would be great to add an example of an icon-only button to _all_ of the [Button examples](https://www.carbondesignsystem.com/components/button/code), i.e. Primary Button, Secondary Button, Tertiary Button, Ghost Button, Danger button, Primary Danger button, Small Primary button, Small secondary button, Small tertiary button, Small ghost button, Small primary danger button, Small danger button.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1667

This PR adds the icon only button variant to the component library

### CODE REVIEW

**Review by shixiedesign — APPROVED** [review]
Looks good to me! 🎉

**Review by asudoh — APPROVED** [review]
🎉 - Thanks a lot @emyarod!

**Comment by elizabethsjudd** [comment]
This did not follow the recommendations that were in issue #1667 regarding accessibility. https://github.com/IBM/carbon-components/issues/1667#issuecomment-460348001 and https://github.com/IBM/carbon-components/issues/1667#issuecomment-461562074

**Comment by emyarod** [comment]
I think we will need designer feedback on the tooltip, so I've opened https://github.com/IBM/carbon-components/issues/2293 to get confirmation on the pattern we want to proceed with

**Comment by shixiedesign** [comment]
@elizabethsjudd sorry I knew there was a reason we didn't include icon buttons in the first pass! We will get a tooltip added asap. Thanks!

**Comment by elizabethsjudd** [comment]
Jane Depgen was the designer that worked on this for Watson Health (I know she's work with the Carbon team on other things as well).

**Pull request merged**
