### PR TITLE
feat(Pictograms): pictogram-master-file-june

### PR DESCRIPTION
**Pull request by dudley-ibm**
new pictogram master

includes the 17 new pictograms from previous PR https://github.com/carbon-design-system/carbon/pull/14067

needs to show up on both Carbon and IDL sites

### CODE REVIEW

**Review by francinelucca — CHANGES_REQUESTED** [review]
LGTM except i'm seeing "app modernization" under "Data Storage" in the master file and in the linked PR it looks like it's under "Design and Development", is this correct @dudley-ibm ?
image
image

**Comment by dudley-ibm** [comment]
`app--modernization` should live in the `Data Storage` category. This might be part of the anomalies that @tw15egan helped me with when my connectivity to github caused a glitch in my local fork.

**Comment by tw15egan** [comment]
Yeah it mistakenly got added to a second category in `categories.yml`, there shouldn't be any issues with the master file

**Comment by tw15egan** [comment]
Fix is here: https://github.com/carbon-design-system/carbon/pull/14113

We don't need to wait before merging this, but @carbon-design-system/design should sign off on the master file

**Review by tw15egan — APPROVED** [review]

**Review by francinelucca — APPROVED** [review]

**Review by kingtraceyj — APPROVED** [review]
master file looks good to go!

**Comment by andreancardona** [comment]
@LMapes testing here

**Pull request merged**
