### PR TITLE
fix(components): overflow menu style bug fix

### PR DESCRIPTION
**Pull request by oyin-k**
Closes #

Style changes to a bug that was identified in issue #5998.

#### Changelog

**New**

- .#{$prefix}--overflow-menu-options[data-floating-menu-direction='bottom']::after {
    **top: rem(-3.2px);**
    left: 0;
    **width: rem(64px);**
    height: rem(3px);
  }

**Changed**

- .#{$prefix}--overflow-menu-options[data-floating-menu-direction='bottom']::after {
    **top: rem(-3px);**
    left: 0;
    **width: rem(32px);**
    height: rem(3px);
  }

**Removed**

- `top: rem(-3px);
    width: rem(32px);
`

#### Testing / Reviewing
Screenshot 2020-07-14 at 03 36 42

Screenshot 2020-07-14 at 03 09 51

### CODE REVIEW

**Comment by tw15egan** [comment]
Seems like this messes up the original implementation

Screen Shot 2020-07-14 at 1 38 06 PM

**Comment by oyin-k** [comment]
@tw15egan while inspecting the code, I realized that the original implementation was designed for the icon menu which is why the text menu button appeared that way as shown in the issue. So I increased the width of the original implementation to be best suited for both cases.

**Comment by tw15egan** [comment]
I think we'll need a way to dynamically set the width on that `::after` element

**Comment by oyin-k** [comment]
Ok I'll work on that.

**Comment by dakahn** [comment]
@oyin-k Did you have a chance to update this PR?

**Comment by joshblack** [comment]
Going to close this out due to inactivity, feel free to comment and I can re-open!

**Pull request closed without merging**
