### PR TITLE
fix(select): match experimental spec

### LINKED ISSUE #1958: [Audit] Select
**variants:**
- Select
- Inline

🖼 design spec (internal link): https://ibm.ent.box.com/file/329981608564

## changes:
**Select:**
- [x]  dev: use type tokens (currently commented-out as TODO items in code)
    - label: `$label-01` ✅ 
    - text in field: `$body-short-01` ✅ 
- [x]  dev: verify that we're using spacing tokens in field & label margin
- [x]  dev: disabled label text should be `$disabled-02` ✅ . verify which token/hex is being used
    - helper text should be same color as label when disabled 
      - helper text type token: `$label-01` ✅ 
      - helper text color tokens: enabled = `$text-02`; disabled = `$disabled-02`  ✅ 
- [x]  dev: space between label & helper text is off—should be `2px`
- [x]  dev: verify error icon is there (it's not there on website)
- [x] ~screenshot: is this overlap in the error state an issue with the component, or its display on the website?~ yes, this is expected (we currently expect devs to apply bottom margin styles to accommodate)
image

**Inline:**
- [x]  ~dev: width should always be the content width plus padding (fluid width) to match design spec. (it will get small with short content)~ de-scoped, see comment below
- [x]  dev: disabled label using wrong color/token
    - helper text should be same color as label when disabled

**React**
- [ ]  do an additional audit pass for react 

FYI @aagonzales

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1958

This PR incorporates feedback from the February 2019 select component audit

depends on https://github.com/IBM/carbon-components/pull/2024

### CODE REVIEW

**Comment by asudoh** [comment]
@emyarod What is the question here...? Thanks!

**Comment by emyarod** [comment]
@asudoh a few questions from the issue for this PR https://github.com/IBM/carbon-components/issues/1958

**Comment by lovemecomputer** [comment]
@emyarod u might have already seen the convo in the issue, but just pasting Anna's comment here to be complete! 

> Inline Select is fluid width, sized based on the currently selected option.
> The select field and the open menu widths should NOT be dependent on each other.

**Review by aagonzales — APPROVED** [review]
LGTM!! Thanks for talking through all that stuff with me.

**Review by asudoh — COMMENTED** [review]
LGTM basically - Could you please do a quick test given I see some markup changes that affect `v9`? Thanks @emyarod!

**Comment by emyarod** [comment]
@asudoh is there a specific line that stood out to you? It looks to me like the `v9` markup changes were formatting changes only

**Review by alisonjoseph — APPROVED** [review]
LGTM after Akira's issue is resolved

**Comment by joshblack** [comment]
image

Should this have truncation styles? e.g. the ellipsis for text overflow

**Comment by emyarod** [comment]
I don't believe truncation styles can be implemented without hacky JavaScript. This is a native `<select>` under the hood (as opposed to our custom dropdown https://github.com/IBM/carbon-components/pull/1994), so we are already quite limited in what we can do to style the element, on top of the custom styles and behaviors imposed by browser vendors and operating system defaults

related: https://github.com/IBM/carbon-components/issues/2063

**Comment by asudoh** [comment]
Let's track the ellipsis topic at: #2091

**Pull request merged**
