### PR TITLE
feat(icons): new icons request

### LINKED ISSUE #12083: [Feature Request]: icons
### Summary

Addition of 3 new icons

Requestor name and email or GitHub ID: James Thompson (james@4dstudio.com)
Business unit: Merative
Name of the UI icon batch: Image Availability Status
Description of each of the UI icons in the batch:
Local - the images of the exam are available locally, i.e. on the local system (as opposed to needing to be retrieved before the exam can be opened locally).

Retrieving - the images of the exam are being retrieved (transferred from a remote system to the local system).

Unavailable - the location (local or remote) of the images of the exam is unknown/unavailable.

Alias(es) for each of the UI icons in the batch (required):
Local: here, internal, location
Retrieving: fetching, transferring to this location
Unavailable: unknown, unknown location
Images: screenshot provided below
Box link: https://app.box.com/folder/172098218505
Due date: Sept 15 - 23

### Justification

A set of icons that will be utilized for a web based application (Merge Workflow Orchestrator) leveraged directly from the Carbon library.

### Screenshots

Screen Shot 2022-09-09 at 12 47 18 PM

### Desired UX and success metrics

Consistency with dozens of other icons leveraged from the library.

### Required functionality

Basic addition to the Carbon icon library.

### Specific timeline issues / requests

Sept 15 - 23, 2022

### Your team

Merative > Imaging > Merge Workflow Orchestrator

### Available extra resources

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by conradennis**
Submitting a few new requested UI icons
all updates and additions approved by BXD

4 net new icons

updated categories.yml with additions

Closes #12083 

#### Changelog

**New**

- watson-health/32/image-availability--local.svg
- watson-health/32/image-availability--retrieving.svg
- watson-health/32/image-availability--unavailable.svg
- 32/plan.svg

### CODE REVIEW

**Review by laurenmrice — APPROVED** [review]
Looks good ! ✅

**Review by tay1orjones — COMMENTED** [review]
@conradennis I'm attempting to generate the metadata for this, but it looks like the file names might be incorrect? Instead of "image-", the file names include "imag-". Is this intentional?

**Comment by conradennis** [comment]
@tay1orjones omg thanks for catching that. I was rushing and missed the "e". Just updated the file names

**Review by tay1orjones — APPROVED** [review]
Metadata has been generated and snaps have been updated 👍

**Review by sstrubberg — APPROVED** [review]

**Pull request merged**
