### PR TITLE
fix(FilterableMultiSelect): extend input outline to trigger button area

### LINKED ISSUE #7535: Filterable Multiselect focus outline on wrong node
When a filterable multiselect has some options selected, clicking on it's `<input>` puts focus outline on wrong node:

Screen Shot 2021-01-12 at 22 05 18

## Environment

> Operating system

MacOS

> Browser

Chrome

## Detailed description

> What version of the Carbon Design System are you using?

10.26

> What did you expect to happen?

Focus outline around whole control.

> What happened instead?

Focus outline around `<input>`

## Test case

See https://react.carbondesignsystem.com/?path=/story/multiselect--filterable or https://react.carbondesignsystem.com/?path=/story/multiselect--filterable

Note that clicking more to the left will put the focus outline around the whole control:

Screen Shot 2021-01-12 at 22 19 22

Presumably a regression from #4721.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #7535

related #7615

This PR resolves a visual issue in the filterable multiselect which expands the input focus outline to the multiselect menu trigger button area

#### Changelog

**New**

- input focus and blur handlers for FilterableMultiSelect

**Changed**

- FilterableMultiSelect focus styles

#### Testing / Reviewing

Confirm the filterable multiselect styles are now correct

### CODE REVIEW

**Comment by tw15egan** [comment]
Slight focus issue in Firefox

Screen Shot 2021-02-02 at 12 17 25 PM

**Comment by emyarod** [comment]
this is what it looks like on Firefox 87 for me

image

**Comment by tw15egan** [comment]
I originally noticed it on the ESR version and I forgot I had 2 versions installed. But after updating Firefox to the latest I'm still seeing it. Is 87 a nightly or something? 

Screen Shot 2021-02-02 at 12 38 03 PM

**Comment by emyarod** [comment]
this looks like an existing issue in Firefox version <87, I can open a separate fix for this. it doesn't appear to be a regression from this PR

**Comment by tw15egan** [comment]
Sounds good to me 👍

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Comment by emyarod** [comment]
#7725 will resolve that issue separately, and this PR will extend the focus outline to the trigger button area

**Review by andreancardona — APPROVED** [review]
looks good! Pending visual review

**Review by laurenmrice — APPROVED** [review]
lgtm! 👍🏻

**Pull request merged**
