### PR TITLE
feat(icons): re-enable SVGO optimizations for icons

### PR DESCRIPTION
**Pull request by joshblack**
We turned off this setting back in #5603 but have since transitioned to using the original SVG assets instead of the generated JS for rendering icons in a Sketch plugin. As a result, this PR re-enables the optimizations that were causing issues in Sketch but still render fine in a browser.

#### Changelog

**New**

**Changed**

- Re-enabled disabled plugins from #5603

**Removed**

### CODE REVIEW

**Comment by tw15egan** [comment]
Would it be possible to also run this on the SVG's in the `@carbon/icons`  package so we can close https://github.com/carbon-design-system/carbon/issues/5568 ?

**Review by emyarod — COMMENTED** [review]
looks like some more snapshots need updating to pass CI. this doesn't affect Sketch symbol generation now right? (all of the Sketch symbols look good to me)

**Review by asudoh — APPROVED** [review]

**Comment by joshblack** [comment]
@emyarod the plugin should be good! And updated 👍 

@tw15egan yeah! That's the plan, I think we'll need to move `svg` to `src/svg` and then output the optimized `svg` directory. The reason being is that SVGO-optimized assets don't really render well when going back into Sketch 😞

**Review by emyarod — APPROVED** [review]
looks good to me

**Pull request merged**
