### PR TITLE
fix(Accordion): update Accordion styles to match spec

### LINKED ISSUE #12141: [Bug]: Accordion various bugs against website spec. lg content not middle aligned, hover color not $background-hover
### Package

@carbon/react

### Browser

Chrome

### Package version

1.13.0

### Description

Two bugs against the specs on [Carbon website](https://carbondesignsystem.com/components/accordion/style#sizes).

1. Size lg, in React storybook shows content top aligned, where as on website, spec shows content should be middle aligned (vertically centered): 
image
2. Headers on hover color changes to `layer-hover`, while website spec states this should be `$background-hover`. Also happening in Figma kit, visible most in gray100 theme.
image
image

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-accordion--playground&args=size:lg

### Steps to reproduce

1. Go to https://react.carbondesignsystem.com/?path=/story/components-accordion--playground&args=size:lg
2. Set accordion size to `lg` 
4. See bug

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### LINKED ISSUE #12223: [Bug]: Accordion missing 1 rem between chevron icon and texts
### Package

@carbon/react

### Browser

Chrome

### Package version

1.14.0

### React version

_No response_

### Description

There seems to be no space between accordion titles and the chevron icon. Expecting there to be 16px/1rem based on website: https://carbondesignsystem.com/components/accordion/style

image

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-accordion--playground

### Steps to reproduce

1. Go to https://react.carbondesignsystem.com/?path=/story/components-accordion--playground
2. Narrow down screen width to see bug

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/12141
Closes https://github.com/carbon-design-system/carbon/issues/12223

Fixes a few style issues with `Accordion`

#### Changelog

**Changed**

- `lg` size `Accordion` is now center aligned
- Background hover color is now `$background-hover`, not `$layer-hover`

#### Testing / Reviewing

- Go to the Playground story and set the size to `lg`, ensure the text and chevron are aligned
- Hover over the `AccordionItem` and ensure the token is `$background-hover` on the `::before` element

cc @shixiedesign

### CODE REVIEW

**Comment by shixiedesign** [comment]
Both issues are fixed! Thank you @tw15egan 🎉 🎉 🎉

**Comment by aagonzales** [comment]
The only thing about using `background-hover` is that its transparency and the border dividers now show up with the hover. 

image

Where as before they were blended in/hidden. 

image

**Comment by tw15egan** [comment]
@aagonzales, do we just need to update the spec on the website re: `background-hover`?  `lg` fix can remain in the PR, but if its just a spec change I can PR the website to update the token value

**Comment by aagonzales** [comment]
Yeah after looking at it a little more I think we should keep it `$layer-hover` in code and just update the website to reflect that. @tw15egan

**Review by aagonzales — APPROVED** [review]

**Review by jnm2377 — APPROVED** [review]

**Review by aledavila — APPROVED** [review]

**Pull request merged**
