### PR TITLE
fix(modal): ensure text input fills it's container

### PR DESCRIPTION
**Pull request by tw15egan**
Arose in Slack:

Screen Shot 2019-07-01 at 10 35 08 AM

`TextInput` is now wrapped inside `.#{$prefix}--text-input__field-wrapper` for error handling. This needs to be set to `width: 100%` to ensure the text input flows to the width of its container.

Previous:
Screen Shot 2019-07-01 at 10 37 11 AM

Updated: 
Screen Shot 2019-07-01 at 10 36 40 AM

**Testing**
- `TextInput` fits the full width of the container
- `TextInput` error handling still looks correct

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
👍

**Review by joshblack — APPROVED** [review]

**Review by emyarod — COMMENTED** [review]
I remember the width is unset because we want to allow dynamic text input width out of the box, but I'm not sure if it's different in this scenario when it's contained inside a modal. if we want full width text inputs then this looks good, otherwise this can be a change specifically targeting text inputs in modals or just a user land change

**Comment by tw15egan** [comment]
@emyarod not sure I follow, wouldn't dynamic text input mean that it fills its container? Right now, if we remove the demo-specific `min-width: 20rem`, we're getting uneven widths of the inputs.

Screen Shot 2019-07-02 at 7 08 42 AM

 If we add `width: 100%`, they fill the size of the container. The website currently has `width: 100%` on all the input wrappers as well. 

Screen Shot 2019-07-02 at 7 10 16 AM


The `width: 100%` was added in [this PR](https://github.com/carbon-design-system/carbon/commit/919ba2e108d1527139dcb012d7827331a091d927#diff-12fe5426691289bd343d44bf1aa97b6cR89) and reverted due to other reasons in [this one](https://github.com/carbon-design-system/carbon/commit/8823fe54f69e89cf9b17ffebfa037430b6d59190#diff-12fe5426691289bd343d44bf1aa97b6cL85).

If this needs to just be added to modal, we can do that, but I'd like to make sure we have Text Inputs behaving as expected. I was under the impression they would always fill the width of their container up until a `max-width`, but it looks like the `max-width` is also missing

**Comment by shixiedesign** [comment]
It's too bad we can't see the issues connected with that commit where `width = 100% ` is taken out. I'm not sure why we'd want text input with auto widths. It makes sense at a glance to have full width (and `max width`, should be breakpoint dependent) defined. 

Is there's history I'm unaware of probably? @aagonzales

**Comment by tw15egan** [comment]
FWIW, [V9 had 100% widths](https://v9.carbondesignsystem.com/components/text-input/code) so I had just assumed we had forgotten to add it to the new text input wrapper. There may be something I'm missing

**Comment by emyarod** [comment]
yeah I think it was related to the helper text having a max width now but I'm unsure. at this point we may as well just reevaluate the component

**Review by shixiedesign — APPROVED** [review]
In that case, I'd say we add this back. Looks good to me 😬

**Review by lovemecomputer — APPROVED** [review]
cool!

**Review by emyarod — APPROVED** [review]
glad the spec issue got cleared up, looks good to me!

**Pull request merged**
