### PR TITLE
fix(pagination): rewrite experimental pagination according to new spec

### LINKED ISSUE #1638: Presentation of experimental pagination <Select> menu content is inconsistent
Based on the spec for the experimental pagination component, we are assuming that the `'items per page'` text should appear *only* on the trigger button rather than within the options of the listbox.

```
|     10 ITEMS PER PAGE      v  |
|-------------------------------|
|              10               |
|              20               |
|              30               |
|              40               |
|              50               |
|-------------------------------|
```

as opposed to the current implementation where text is appended to the selected menu item

image

If this assumption is correct, then a number of technical issues arise, the primary one being that the native `<select>` element does not support this behavior of showing differing content between the trigger button and the list items contained within it.

There are a number of possible workarounds for this issue:

* one would be removing the appended text from the selected menu option
* another would be converting the native `<select>` element to a custom dropdown

This issue could potentially be a ship stopper for the v10 release as it appears to be a regression in functionality for the component consumer

### LINKED ISSUE #1649: v10 Pagination - issue with select dropdown (design change)
From the current way the pagination component is designed, the open select dropdowns are triggering the full name displayed when the dropdown is closed.

Comments by emyarod:

We only want to have the dropdown showing individual numbers inside of it, so we are proposing to reorder the chevrons and numbers to fix this problem.

@IBM/carbon-developers

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1638 
Closes #1649

This PR will refactor the experimental pagination component according to the modified spec provided in the tickets referenced above

### CODE REVIEW

**Comment by emyarod** [comment]
@laurenmrice would be great if you could perform a visual review based on the modified spec you provided!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Looking good but a couple of things:
- The spacing between ‘Items per page:’ and the number needs to be 8 px/.5 rem as well as the spacing between the chevron and ‘of x pages’.
screen shot 2019-01-22 at 2 32 56 pm

- Check to make sure that the left and right carets are sitting within a perfect square, I think the borders are currently making slight rectangles.

- ‘1-10 of 40 items’ should be body-short-01, text-02(#565656). The rest of the text in the pagination can be body-short-01, text-01 (#171717).

- Can we get the focus to have the border wrap closer around the number and icon instead of being tall and vertical?
screen shot 2019-01-22 at 2 30 34 pm

**Comment by asudoh** [comment]
@emyarod Is this ready for re-review? Thanks!

**Comment by emyarod** [comment]
@asudoh yes if @laurenmrice OKs the changes

The focus borders were leftover from the previous experimental implementation so I did not modify them initially but the latest netlify build should include all of the latest requested changes

**Review by laurenmrice — APPROVED** [review]

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Sorry i pushed approve instead of review changes.

Two things:
-We need some more padding around the text and icon within the focus border, I made some specs below. 
screen shot 2019-01-24 at 10 21 36 am
-Also we only need a top border line on the pagination instead of borders on all sides.

**Comment by emyarod** [comment]
@laurenmrice thanks for the feedback! Which browser were you viewing the [latest deploy preview](https://deploy-preview-1679--the-carbon-components.netlify.com/?nav=pagination) on? I've been trying to replicate the "current" view in your screenshot, but the focus borders appear closer to your "proposed" changes than the current version on my end:

latest Firefox:

image

latest Chrome:

image

**Comment by laurenmrice** [comment]
@emyarod The screenshots you show for the foucs on each browser looks fine to me. For some reason when I view it on my firefox on my computer it just still looks really close to the type and my firefox is up to date (60.4.0esr ). Maybe its just my browser?

 Firefox: 
screen shot 2019-01-25 at 10 29 19 am

**Comment by emyarod** [comment]
@laurenmrice that could be why, I looked on Firefox 63 and it looked like your screenshot, but starting from Firefox 64 and higher it looks like my screenshots. Would you be able to confirm that on an updated version of FF?

**Comment by laurenmrice** [comment]
@emyarod yeah okay, I tried it on TJs browser and it was okay.  Also bottom and side borders can be omitted and keep top border only for the component.

**Comment by emyarod** [comment]
@laurenmrice thanks for clarifying! the latest deploy preview should include the border changes as well now

**Comment by laurenmrice** [comment]
Looks good ! 👍

**Review by laurenmrice — APPROVED** [review]

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
