### PR TITLE
fix(Link): unrecognized prop warning for 'isSideNavExpanded'

### LINKED ISSUE #3970: React does not recognize the `isSideNavExpanded` prop on a DOM element
## What package(s) are you using?

- [x] `carbon-components` - 10.6.1 (latest)
- [x] `carbon-components-react` - 7.6.1 (latest)

## Detailed description

> Describe in detail the issue you're having.

It looks like https://github.com/carbon-design-system/carbon/pull/3626 introduced a warning about unrecognized props being applied to DOM elements.

```
Warning: React does not recognize the `isSideNavExpanded` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `issidenavexpanded` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in a (created by Context.Consumer)
    in Link (created by Context.Consumer)
    in NavLink (created by Link)
    in Link (created by ForwardRef(SideNavMenuItem))
```

here, the props (including `isSideNavExpanded`) are being spread onto `element`: https://github.com/carbon-design-system/carbon/blob/99f12f98e226b2ab1872b7379167d827e4fe7bd5/packages/react/src/components/UIShell/Link.js#L19

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

The Carbon components should not be passing through all props like this, instead they should filter out those that are not supported / relevant for the target component / element, or explicitly pass only the expected props to their children.

Having these warnings causes a lot of noise in logs, both in the browser and in tests, making it harder to spot / debug genuine problems.

## Steps to reproduce the issue

This can be reproduced by running the storybook in dev mode
1. from packages/react: `npm run storybook`
2. navigate to http://localhost:9000/?path=/story/ui-shell--fixed-sidenav
3. see the warning in the browser console

image

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by dariusbakunas**
Fixes #3970

Fixes console warning for Link component:
```
 React does not recognize the `isSideNavExpanded` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `issidenavexpanded` instead. If you accidentally passed it from a parent component, remove it from the DOM element
```

#### Changelog

**Changed**

- Link

#### Testing / Reviewing

Launch storybook with `yarn storybook` and go to `http://localhost:9000/?path=/story/ui-shell--sidenav-w-large-side-nav-items` and observe that console warning about unknown prop is no longer visible

### CODE REVIEW

**Comment by dakahn** [comment]
Hey, thanks so much for taking the time to contribute. Could you walk us through your process here a little bit. In particular the filterDomProps.js bit brought in from react-dom.

**Comment by dariusbakunas** [comment]
Yes @dakahn, I was looking at warning source in react codebase (https://github.com/facebook/react/blob/f85aadefc0c059648ee53842ba948a7d7cba468b/packages/react-dom/src/shared/ReactDOMUnknownPropertyHook.js#L169) and traced it back to two hooks that they use to check if property is valid, one for standard dom props and another for aria props, they do have much more code, but I copied what I thought is important for our usecase. So basically it takes the props object, enumerates the keys and checks if lowercased key is part of possibleStandardNames or if it is in fact an aria property. Although it looks like circleci is still failing, so I'm trying to figure out why

**Comment by dariusbakunas** [comment]
I could not find a standard way to do this validation and that code in React is not exposed in their api, thus I had to copy some bits

**Comment by dariusbakunas** [comment]
I could also simplify, for aria I could check if `aria` prefix exists and not check for wrong aria tags.. as for standard props I don't know if we can get around without that list copied from react

**Review by asudoh — COMMENTED** [review]
Hi 👋 thank you for your attempt to fix the problem! Seems that the problem is caused by missing check of target component in [`<SideNavItems>` code](https://github.com/carbon-design-system/carbon/blob/v10.6.0/packages/react/src/components/UIShell/SideNavItems.js#L22) where it propagates its expanded state to children. Great to have a pin-point fix for such problem, to limit the scope of the fix. Thanks!

**Comment by dariusbakunas** [comment]
That makes sense, but isn't the core of the problem still inside the Link component? fixing it in SideNavItems may not prevent this from happening again, no? Anyway, I can close this if you think SideNavItems fix is the way to go, thanks!

**Comment by asudoh** [comment]
Thank you for your thoughts. Here's more background; We have a pattern of propagating misc props to a key DOM element in several components. `<Link>` is one of them. It's the responsibility of the caller not to send redundant props to such components.

**Pull request closed without merging**
