### PR TITLE
feat(dropdown): support new experimental error state

### LINKED ISSUE #1732: Experimental dropdown error state
Related:

https://github.com/IBM/carbon-components/issues/1208

https://github.com/IBM/carbon-components/issues/1215

https://github.com/IBM/carbon-components/issues/1535

### PR DESCRIPTION
**Pull request by emyarod**
Closes #1732

Part of #1535

This PR adds the experimental error state to the dropdown component

### CODE REVIEW

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Just two things:
- The chevron needs to be 16 from the edge of the right side, and there needs to be a 8px space between the alert icon and the chevron.

screen shot 2019-02-07 at 12 57 39 pm

- Also on Firefox, Chrome and Safari the type in the field needs to be in the exact center, right now it is a little too high.

**Comment by emyarod** [comment]
thanks for the feedback, I've repositioned the alert icon to be 8px away from the chevron, and chevron is already 16px away from the edge. The type in the field was left unchanged from https://github.com/IBM/carbon-components/pull/1269 but I've modified it to be centered

**Comment by asudoh** [comment]
Hi @laurenmrice was looking at the original issue (#1535) - Did you mean select UI (https://www.carbondesignsystem.com/components/select/code), dropdown, or both...? Thanks!

**Comment by laurenmrice** [comment]
Hey Akira, yes both types of dropdowns 👍

**Review by laurenmrice — APPROVED** [review]
Dropdown (styled) error state looks good ! 👍

**Comment by emyarod** [comment]
I just made the select error state changes separately in this PR https://github.com/IBM/carbon-components/pull/1756

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @emyarod!

**Pull request merged**
