### PR TITLE
docs(data-table): fix link appearance in datatable stories

### PR DESCRIPTION
**Pull request by janhassel**
Right now, the links in the DataTable stories don't have a `href` attribute. This results in the links not changing cursor on hover and not being in the tab order (at least in Chrome) which can cause confusion.

#### Changelog

**Changed**

- Added `href="#"` to the links

#### Testing / Reviewing

Storybook

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
Thanks for fixing this Jan!

**Comment by andreancardona** [comment]
@janhassel do you mind fixing the ci failures - other than that looks good!

**Comment by janhassel** [comment]
@andreancardona Seems to have been a temporary issue with the VRT runners. I ran them again by pushing an update and everything's green now 👍

**Review by andreancardona — APPROVED** [review]
💯

**Pull request merged**
