### PR TITLE
fix(text-area): modify spacing tokens for invalid icon

### LINKED ISSUE #2157: Invalid textarea icon out of position
I missed this change from IBM/carbon-components-react#2036 🤦‍♂️ 

reported by @laurenmrice 

> The icon should also be placed 12px from the top and 16px from the left of the field.

### PR DESCRIPTION
**Pull request by emyarod**
Closes #2157

This PR repositions the invalid icon for v10 textareas

### CODE REVIEW

**Comment by tw15egan** [comment]
>The icon should also be placed 12px from the top and 16px from the left of the field.

Is the icon supposed to be on the right or left?

**Comment by laurenmrice** [comment]
@tw15egan its supposed to be on the right. it looks good now.

**Comment by tw15egan** [comment]
Great! 👍

**Review by tw15egan — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
Looks good 👍

**Pull request merged**
