### PR TITLE
Update icons.yml

### PR DESCRIPTION
**Pull request by LMapes**
Updated icon aliases and friendly names per #7985

Closes #

{{short description}}

#### Changelog

**New**

- {{new thing}}

**Changed**

- {{change thing}}

**Removed**

- {{removed thing}}

#### Testing / Reviewing

{{ Add descriptions, steps or a checklist for how reviewers can verify this PR works or not }}

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
@LMapes you just need to sign the DCO and you're good to go 👍🏻

**Comment by LMapes** [comment]
recheck

**Comment by LMapes** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by LMapes** [comment]
recheck

**Review by joshblack — APPROVED** [review]

**Pull request merged**
