### PR TITLE
chore(icons): update metadata.yml and meta.json

### PR DESCRIPTION
**Pull request by joshblack**
Resolves some longstanding issues with our `meta.json` file, namely that we need to rename it to `build-info.json` to support a `metadata.json` file that is derived from `metadata.yml`. In addition, `categories.yml` has been folded into `metadata.yml` so we have one place for metadata.

### CODE REVIEW

**Review by lovemecomputer — APPROVED** [review]
yes! great changes to go alongside other icon metadata work in https://github.com/carbon-design-system/carbon/pull/3131

**Review by chrisconnors-ibm — APPROVED** [review]
lgtm

**Comment by chrisconnors-ibm** [comment]
after the fact recriminations/second thoughts (that I already shared with @joshblack) : it's a little weird that the second half of this document generates the first half.

**Comment by joshblack** [comment]
I wouldn't say it generates, but rather it keeps them in sync.

**Pull request merged**
