### PR TITLE
fix(progress-indicator): fix spacing for skeleton progress label

### LINKED ISSUE #11784: [Bug]: Progress indicator vertical, skeleton text miss aligned
### Package

@carbon/react

### Browser

Chrome

### Package version

1.7.0

### React version

_No response_

### Description

Progress indicator, vertical style, when set to skeleton state, the skeleton text is slightly too low next to the dotted circles. Expecting the text to middle align with the circles: 

image

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-progressindicator--skeleton

### Steps to reproduce

Build it locally to check because React storybook currently do not have functional knobs/controls. 
This error is in Angular storybook demo too: https://angular.carbondesignsystem.com/?path=/story/components-progress-indicator--skeleton

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by torresga**
Closes #11784 

This fix updates the `margin-top` on the skeleton state progress label. 

#### Changelog

**Changed**

- updated the `#{$prefix}--progress.#{$prefix}--progress--vertical.#{$prefix}--skeleton
    .#{$prefix}--progress-label` class to have the same margin-top as the svg circle icon

#### Testing / Reviewing

Add the `#{$prefix}--progress--vertical` class to the Skeleton component and look at it in Storybook. It should look like this: 
Screen Shot 2022-10-18 at 3 58 37 PM

### CODE REVIEW

**Comment by torresga** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by tw15egan** [comment]
Thanks for adding this in! I noticed we don't support `vertical` on `ProgressIndicatorSkeleton` out of the box. Would you like to add that to this PR, i.e., adding the `vertical` prop to add the vertical class to `ProgressIndicatorSkeleton` or should we create a separate issue?

**Comment by torresga** [comment]
That's a good point - I will add the `vertical` prop to add the vertical class to `ProgressIndicatorSkeleton` in this PR.

**Comment by sstrubberg** [comment]
@torresga thanks for the PR. Looks like one of the tests fails. Go the root of the carbon folder in your dev environment and run `yarn test packages/react/__tests__/PublicAPI-test.js -u`. That should take care of it.

**Review by tay1orjones — APPROVED** [review]

**Comment by tay1orjones** [comment]
Looks great! Thanks for contributing! I just enabled all status checks to run, they should finish/report shortly.

**Review by tw15egan — APPROVED** [review]
Thanks for adding this fix and new functionality! 🎉

**Pull request merged**
