### PR TITLE
fix(dropdown): set z-index to above the modal

### LINKED ISSUE #1064: Cannot use use a dropdown inside a Modal
## Detailed description

> Describe in detail the issue you're having.

When you try to place a dropdown component onto a modal component the Z-Indexes at https://github.com/IBM/carbon-components/blob/master/src/globals/scss/_layout.scss#L64 mean that when you open the dropdown the dropdown options are hidden *behind* the modal making it effectively impossible to have a dropdown ontop of a modal.

I can't think of a situation when you'd have a dropdown open in the background with a modal ontop taking focus, so it seems like the dropdown should have a higher z-index than the modal.

> Is this issue related to a specific component?

Modal + Dropdown

> What did you expect to happen? What happened instead? What would you like to see changed?

The dropdown menu should render ontop of the modal

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

carbon-components@9.10.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Appconnect

## Steps to reproduce the issue

See description above, or check out my fork of carbon-components-react where I've put a story on the Modal storybook to demonstrate the problem
https://github.com/meganwalker-ibm/carbon-components-react/tree/dropdown-on-modal

## Additional information
screen shot 2018-09-05 at 13 42 21
Here you can see that the dropdown menu appears behind the modal the dropdown is on.

### PR DESCRIPTION
**Pull request by cal-smith**
Closes #1064

z-indexes should be totally reordered at some point (v11?) - to prevent breakages this just bumps the z-index to `9100` for dropdown - Everything else should work as expected, and the dropdown menu should show up in modals!

### CODE REVIEW

**Comment by asudoh** [comment]
Hi @cal-smith thank you for contributing! One question - Has your test involved showing modal on top of dropdown in page content (instead of dropdown on modal)? I have an impression that modal overlay should go on top of dropdown in page content, but I may be wrong.

**Review by jnm2377 — APPROVED** [review]
Hmm, I can definitely understand how this shouldn't be an issue if dropdown closes when other items (i.e. modal) are focused/clicked. Would be good to get some design input, since I know these are layer tokens. cc: @shixiedesign

**Comment by asudoh** [comment]
Good point @jnm2377 - Sounds that it makes sense. So probably `z('dropdown')` should have the same value as `z('floating')`?

**Comment by cal-smith** [comment]
Setting it equivalent to `z('floating')` sounds like it also makes sense ... Is there anything at the level that would fight for layering with the dropdown?

**Comment by shixiedesign** [comment]
Can we potentially use **select** instead of **dropdown** in modals? I’m concerned if dropdown closes but still have a higher z-index, then there will be a 100ms during which dropdown is *closing* and on top of Modal's black overlay, which would look like a glitch. 

Layer tokens is currently removed from v10 so I'm not sure what the game plan is for z-index applications. When we took out "Layers" guidance we didn't know this is still alive on the dev's side (duh!). Making an issue for future to resolve.

**Comment by asudoh** [comment]
Uh great point @shixiedesign! So defining a new `select` token that is equivalent to `floating` (`10000`) makes sense to me. Didn't know that the token is removed in `v10`, is it because IDL should no longer dictate that? If so, we can make it dev-only (`@private`). Reasoning: Hard-coding those values in code make it hard for maintenance in dev team.

**Comment by shixiedesign** [comment]
@asudoh I don't think those tokens are removed. The guidance on them got removed from the website, because DL is moving towards a "flatter" look and feel. But layers still exist to some extend to fix ux issues like this. Meanwhile, I don't think we need to move the tokens to dev-only. We should keep them as tokens, and propose an update + guidance.

**Comment by cal-smith** [comment]
>I’m concerned if dropdown closes but still have a higher z-index, then there will be a 100ms during which dropdown is closing and on top of Modal's black overlay, which would look like a glitch.

Let me do up a demo to test that out, but my guess is that it should close the dropdown _then_ close the modal - even if it happens in the same frame it should be fine?

**Comment by cal-smith** [comment]
Demo: https://stackblitz.com/edit/modal-dropdown-demo

Direct link: https://modal-dropdown-demo.stackblitz.io/

From what I can tell everything closes and disappears in the same frame

**Comment by asudoh** [comment]
Adding `status: visual review` label to make sure the demo is reviewed considering fade-away period.

**Comment by shixiedesign** [comment]
@cal-smith it appears that we lost the animation of the drawer opening completely. But when I checked, it seems like our React Dropdown is missing the animation in the first place (vanilla seems fine). I will fine a bug issue to add animation back to the React dropdown (FYI @emyarod @asudoh). Meanwhile, I think it makes sense to merge since any animation should happen sequentially here. If any error occurs we can proceed to fix as a bug later.

**Review by shixiedesign — APPROVED** [review]
Thanks for contributing fix!

**Pull request merged**
