### PR TITLE
feat(Pictograms): new pictograms and new category

### PR DESCRIPTION
**Pull request by dudley-ibm**
closes issues #107, 130, 186, 190

- New category called Sustainability

- New pictograms and their (categories):
coupon	(Action)
link	(Action)
music	(Action)

shanghai--cityscape	(Cities)
shanghai—oriental-pearl-tower	(Cities)

flag	(Education)
handshake	(Education)
medal--01	(Education)
medal--02	(Education)
scan-code	(Education)
trophy	(Education)

balloon--hot-air	(Lifestyle)
balloon	(Lifestyle)
candy	(Lifestyle)
firecracker	(Lifestyle)
lantern	(Lifestyle)
moon-cake	(Lifestyle)
ornament	(Lifestyle)
snowflake	(Lifestyle)

moon--full	(Weather)

cloud-pak--for-business-automation	(Cloud)

Asset management 	(Data storage)

esg-reporting--01	(Sustainability) – New category
esg-reporting--02	(Sustainability) – New category
sustainability--02	(Sustainability) – New category
sustainability--03	(Sustainability) – New category
sustainability--04	(Sustainability) – New category
green-it--01	(Sustainability) – New category
green-it--02 	(Sustainability) – New category
energy--crisis 	(Sustainability) – New category
sustainability--strategy 	(Sustainability) – New category

supply-chain--01 	(Supply chain)
supply-chain--02 	(Supply chain)

government--01 	(Government)
government--02	(Government)

banking	(Finance)

retail--sustainable	(Retail)

event--automation	(Networking)
event--endpoint-management	(Networking)
event--processing	(Networking)
event--streams	(Networking)

All pictograms should show up on carbon site and on IBM Design Language site pictogram libraries

### CODE REVIEW

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by andreancardona — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
✅

**Comment by dudley-ibm** [comment]
@tw15egan I think there is a slight issue still with this pull request. All the included pictograms show up on Carbon, but only their Friendly name shows up on IBM Design Language, yet no pictogram appears or is downloadable. Could you please investigate? Thanks!

**Comment by tw15egan** [comment]
@dudley-ibm should be fixed once [this PR](https://github.com/carbon-design-system/design-language-website/pull/1240) that was just merged in gets deployed, thanks for catching that 👍

**Comment by dudley-ibm** [comment]
> @dudley-ibm should be fixed once [this PR](https://github.com/carbon-design-system/design-language-website/pull/1240) that was just merged in gets deployed, thanks for catching that 👍

Thanks @tw15egan 
Why was the addition PR necessary? I don't completely understand the language of it.

**Comment by tw15egan** [comment]
No worries, here's a quick summary of what happens when you put up a PR:
- We merge it here into the Core Carbon library, which is how developers would access the `Pictograms` / `Icons`. However, they can't access them immediately, they need to wait for us to "release" it. We release every two weeks, and that includes all code that is committed here in the core repo.
- Once the release is made, we put up two PR's to the Carbon Design System website and the IBM Design Language website to update the dependencies to the latest version of Carbon, i.e. allowing it to pull in these latest and greatest changes. 
- Once those PR's are merged, the build process rebuilds the website and redeploys it with the newest changes/pictograms / icons. Sometimes the reviews get missed and it is sitting there for a review for some time, which seems like it was the case here.

**Pull request merged**
