### PR TITLE
test(Styles): add styles public api tests

### LINKED ISSUE #9168: Write Public API test for `@carbon/styles` for package exports
This issue is for adding the Public API test for `@carbon/styles` in `packages/styles/__tests__/PublicAPI-test.js`. This test should encompass:

- Bringing in styles for the `@carbon/styles` package
- Bringing in individual component styles
- Defining our Public API filepaths
- Snapshotting our public API exports
- Configuration (I can change the prefix or the theme easily)

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/9168

Adds in tests for the `@carbon/styles` package Public API. Some tests already exist in `packages/styles/scss/__tests__`. This will exist in `packages/styles/__tests__`

#### Changelog

**New**

- Snapshot test of all entry points
- `config` tests
- Ensures all entry points can be imported

#### Testing / Reviewing

Ensure all tests pass

### CODE REVIEW

**Comment by tw15egan** [comment]
cc @joshblack

**Comment by joshblack** [comment]
Looking great 🔥

**Review by sstrubberg — APPROVED** [review]
image

🔥

**Review by jnm2377 — APPROVED** [review]

**Comment by jnm2377** [comment]
@tw15egan sorry it took me so long to review, looks like it'll be good to merge once the merge conflict is resolved!

**Pull request merged**
