### PR TITLE
test(project): add support for importing scss files

### PR DESCRIPTION
**Pull request by joshblack**
While working in JSDOM, it may not be obvious that by default our styles are not loaded for components. Most of the time, this shouldn't cause any meaningful impact for test authors. However, when creating/using assertions that depend on visibility status, or if we ever use a browser-based runner like Chrome through puppeteer, we would expect styles to be loaded in the document.

This PR adds support for importing scss files in a similar way to webpack. The idea is that you import the stylesheet you want and under-the-hood the jest matcher will append it to the document before all of your tests run.

#### Changelog

**New**

**Changed**

- Accordion test has been updated to include styles
- Jest css matcher has been updated to process scss and css files

**Removed**

#### Testing / Reviewing

- Pull down the PR and add `console.log(document.styleSheets)` into a test in accordion to verify that the stylesheet has been loaded

### CODE REVIEW

**Comment by vpicone** [comment]
Are we going to require that folks import the styles into each component test? I was hoping to avoid this in the event we might uncover some of our more unsavory style/behavior dependancies. 

For visibility in particular it feels like we’re testing styles not react. Maybe we shouldn’t even be rendering that content, bringing in the styles might be reinforcing a specific implementation. (Using styles vs hidden attribute vs not rendering anything at all)

**Comment by joshblack** [comment]
> Are we going to require that folks import the styles into each component test?

Nah, I don't think we have to do it for all of them ultimately unless we find something that may help out a reporting tool like aXe

> Maybe we shouldn’t even be rendering that content, bringing in the styles might be reinforcing a specific implementation.

Wouldn't this have the opposite effect? Without styles, each component that wants to hide something would have to have `hidden` set (or not render) in order for a visibility check to pass. With styles, we could have either styles or the attribute set (or nothing at all).

**Comment by vpicone** [comment]
@joshblack yeah that's true, not bringing in the style sheet closes to the door to style based behavior, but I think we have an opportunity to see these things as a chance to separate behavior and styles.

If we don't render the content at all or use `hidden`, it solves this without the need for a dependency on a carbon-components class/mixin. That test gets harder to right if we're bringing in the style sheet.

**Comment by joshblack** [comment]
@vpicone just wanted to support multiple ways of solving the same problem versus constraining the solution. Is there a reason we would want to separate out styles? By definition these are coupled, right? And we often use styles to create behavior that we may want, visibility being the largest one not only for things like panels but assistive text that we want announced but not visible.

**Comment by joshblack** [comment]
cc @aledavila let me know if you want to go through this together!

**Review by aledavila — APPROVED** [review]
LG

**Comment by vpicone** [comment]
@joshblack I’d rather we import the styles to every component through the container (maybe same container as SB?) so we don’t have to run into these visibility failures repeatedly or decide on a component by component basis. 

These tests are for the react library, not the react and style library. It seems to me
Like we’re mixing the two and that could make for some confusing precedent. We’ve never needed the style sheet before for tests right?

**Comment by vpicone** [comment]
I’m not sure how all the css transform/cache stuff works could we add some comments here or in the source code? It seems like importing into a single centralized container like the one RTL uses would be the most idiomatic approach.

**Comment by vpicone** [comment]
Could we add some notes on the css transform caching stuff? I’m not sure if everyone would be able to maintain or understand what’s happening there.

**Comment by joshblack** [comment]
@vpicone done!

And I'm definitely torn, it seems like it'd only be useful in a couple of situations which is why it's setup this way. It also wasn't immediately obvious when bringing in all the styles why an error was occurring in JSDOM which made going that route harder.

**Comment by vpicone** [comment]
@joshblack I’m still not able to follow what’s up with the transform stuff, does the error still happen without caching? Does this cause the test to re run if a sass file is changed?

**Comment by vpicone** [comment]
I’m wondering if it’s not possible to take care of all of those scenarios using explicit aria-hidden checks and the hidden attribute. That way we don’t have react component tests failing due to changes in the sass library.

**Comment by joshblack** [comment]
@vpicone what are your questions around the transform? The error comes from compiling the entire style sheet in the test env for some reason (some kind of encoding issue it seems), not necessarily related to the transform. In other words, it's related to a sass source file and not the transform.

The `getCacheKey` would re-run if the contents of the file change due to this line: https://github.com/carbon-design-system/carbon/pull/4467/files#diff-d6a58323528740d8576f90fe84a46782R50

> to take care of all of those scenarios using explicit aria-hidden checks and the hidden attribute

This feels off given that the styles do offer an equally valid way of doing this. The styles and these components are coupled ultimately, feels like separating these out would cause us to do redundant operations like doing hidden in both CSS and in the component when we only need one or the other. Ultimately we might want to prefer the CSS version since that's the bit that is being re-used. If that's the case, we'd want to load them in so that we're not doubling up in the component if we don't have to.

**Comment by vpicone** [comment]
Are we OK with the react component tests failing due to changes in the sass?

**Comment by joshblack** [comment]
@vpicone I feel like we would if it meant something like visibility is no longer done in styles and we would have to update in JS, right?

**Comment by vpicone** [comment]
@joshblack ah yeah that makes sense. I need to research more about the transform stuff I suppose. Does it compile the sass? Is it mean to work like a webpack dev server or something, reloading on change?

I think we should apply the styles to every component to have a consistent testing environment and not need for test authors to decide on a component by component basis whether styles are necessary or not.

**Comment by joshblack** [comment]
@vpicone the way the transforms work is that they'll map a call to `import` or `require` that matches the filename regex to the file itself. The transformer has a `process` function that will take in the source file and emit the module to be executed. This is what compiles the sass into a CSS string and then applies it to the document in `beforeAll` and `afterAll`.

The `getCacheKey` basically is for deciding when Jest should run the `process` function for a given file that is mapped to the transformer.

**Comment by joshblack** [comment]
Gonna close this until the need comes up again 😄

**Pull request closed without merging**
