### PR TITLE
feat(pictograms): replaced watson--avatar with ibm--watson, and added ibm--cloud

### PR DESCRIPTION
**Pull request by dudley-ibm**
Closes #

{{closes enterprise issue #46}}

#### Changelog

**New**

- {{ibm--cloud}}

**Changed**

- {{ibm--watson is new artwork that replaces watson--avatar}}

**Removed**

- {{watson--avatar}}

### CODE REVIEW

**Review by aledavila — APPROVED** [review]

**Review by joshblack — CHANGES_REQUESTED** [review]
Thanks for the contribution @dudley-ibm! One quick note, unfortunate we can't remove things from the package without it being a breaking change. For the Watson Avatar, we'll need to keep the existing asset in place and then add it the `deprecated.yml` so that folks know what to use instead and then we can remove it in the next major version

**Comment by dudley-ibm** [comment]
@joshblack please clarify what steps I need to take. 
There will be many instances where an existing SVG will need to be removed when it is either replaced by updated artwork or replaced by a newly named piece of artwork. Are you guys moving it to this depracated.yml or is that something I'm supposed to be doing?

**Comment by joshblack** [comment]
Hey @dudley-ibm! For a quick overview of deprecation, you can check out: https://github.com/carbon-design-system/carbon/blob/master/packages/pictograms/docs/contributing.md#deprecatedyml

Basically the flow can be summarized as:

- You all decide that an asset should be renamed or removed
- If renamed, add the newly named version but do not remove the existing asset
- Add the name of the icon to `deprecated.yml`

The most important thing is that we don't remove any assets that are already being used in code as it would break teams depending on that icon. Instead, with the deprecation flow, we warn teams that the asset is deprecated and suggest alternatives to be used. The icons are then removed in the next major release of the library.

So on your end, when handling renames it will be following that process above. Similar for removals. The last step will be for you to add the name to `deprecated.yml` and then write out any replacements. As an example, you can check out `deprecated.yml` for icons here: https://github.com/carbon-design-system/carbon/blob/master/packages/icons/deprecated.yml

**Comment by tw15egan** [comment]
Fixed merge conflicts, re-added the deprecated pictogram and added `watson--avatar` to `deprecated.yml`

**Review by tw15egan — APPROVED** [review]

**Review by joshblack — APPROVED** [review]

**Comment by dudley-ibm** [comment]
@joshblack the Cloud logo is still not showing up nor is the updated file for the Watson logo. Please let me know what else I need to do on my end to make that happen.

**Pull request merged**
