### PR TITLE
Update stylelint version and replace deprecated rule names

### LINKED ISSUE #8768: stylelint config uses deprecated rule names
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

NB this should be a feature/enhancement request rather than a bug, but I cannot see how to change that now :-/

Stylelint renamed a number of its rules in August 2020, replacing "whitelist" with "allowed-list" and "blacklist" with "disallowed-list", and has marked the old rule names as deprecated from version 13.7 onward. The stylelint config package still refers to the old rule names. This doesn't affect builds in this package, since package.json and yarn.lock lock in the stylelint version as 13.6 (which is now quite an old version of stylelint), but other packages using more recent versions of stylelint will get deprecation warning messages, and so will carbon builds as soon as a more recent version of stylelint is brought in.

For example, ibm-cloud-cognitive is currently using stylelint 13.12.0, and is seeing deprecation warnings in its builds. It seems undesirable to push stylelint back to a nine-month-old version to temporarily avoid these.

It would be better to pull the stylelint version forward to a more modern version, to benefit from recent changes and fixes, and replace the deprecated rule names as applicable. The current stylelint version is 13.13.1.

This is a routine update chore, and I've included a PR :-)

## Steps to reproduce the issue

1. Update the stylelint version. e.g. use `yarn add stylelint`.
2. Run `yarn lint:styles`
3. Note the following deprecation warnings issued:
image

### PR DESCRIPTION
**Pull request by dcwarwick**
Closes #8768

Update stylelint version to 13.13.1 (current latest). Update rule names which Stylelint has renamed from version 13.7, replacing "whitelist" with "allowed-list" and "blacklist" with "disallowed-list", as these are now marked as deprecated.

#### Changelog

**Changed**

- `package.json` (call for stylelint version 13.13.1).
- `limit-language-features.js` in the stylelint-config-carbon package (rename the deprecated rules).
- yarn cache and lock

#### Testing / Reviewing

Run `yarn lint:styles` and verify that the test still passes satisfactorily.

### CODE REVIEW

**Comment by dcwarwick** [comment]
I have read the DCO document and I hereby sign the DCO.
recheck

**Comment by dcwarwick** [comment]
recheck

**Comment by dcwarwick** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by dcwarwick** [comment]
recheck

**Review by andreancardona — APPROVED** [review]
this looks awesome @dcwarwick thank you for doing this! 🎉

**Review by joshblack — APPROVED** [review]
🎉 Thanks for this!

**Pull request merged**
