### PR TITLE
fix(react): add forward ref to PasswordInput component

### LINKED ISSUE #5893: Support forward ref for TextInput.PasswordInput component
### Summary

I’m able to set focus for a normal `TextInput`  component, but not for a `TextInput.PasswordInput` component.

Test code:

```js
// this works
<TextInput
  ref={input => input && input.focus && input.focus()}
  type="text"
  labelText="Username"
  ...
/>

// this doesn't work
<TextInput.PasswordInput
  ref={input => input && input.focus && input.focus()}
  labelText="Password"
  ...
/>
```

The `ref` for `TextInput.PasswordInput` isn’t working as I see this warning:

```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
```

### Justification

A `PasswordInput` should have the same functionality as a `TextInput`.

### PR DESCRIPTION
**Pull request by code-blooded-developer**
Closes #5893

Add forward ref to PasswordInput component.

#### Changelog
**Changed**
- Changed PasswordInput component to use ref forwarding.

#### Testing / Reviewing
To test you can add ref on the Password component in the story. One way is to test focus on inputs.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
thanks for adding a test. would you mind updating snapshots so it passes CI?

**Comment by code-blooded-developer** [comment]
@emyarod Can you help me here? The test cases are not failing in the local but here they are.

**Comment by emyarod** [comment]
@code-blooded-developer you need to fetch the latest changes from `master` and rebuild the monorepo, then the snapshots should update correctly

**Comment by emyarod** [comment]
it looks like I'm not able to push to your branch because of permissions, but the steps I referenced above should fix the broken tests

**Comment by code-blooded-developer** [comment]
@emyarod thank you for the suggestion. I had a different problem with my OS.

**Review by emyarod — APPROVED** [review]
thanks for the fix, looks good to me

**Review by tw15egan — APPROVED** [review]
Thanks for contributing! Working as expected 👍 ✅

**Pull request merged**
