### PR TITLE
chore(react): updated tile and stories

### PR DESCRIPTION
**Pull request by TannerS**
Closes #

#12315 along with playground stories 

#### Changelog

**Changed**

- Updated index to handle the new files vs the next ones

**Removed**

- Removed args out of default 

#### Testing / Reviewing

Storybook

### CODE REVIEW

**Comment by tw15egan** [comment]
@TannerS can we ensure each `Tile` has a unique `id`? There seem to be some issues when there are multiple `Tile` examples on the same page. To see the issue, go to the `Radio with Layer` story, as well as the docs [tab](https://deploy-preview-12312--carbon-components-react.netlify.app/?path=/docs/components-tile--expandable-with-interactive) and try and interact with `select` and then `radio` examples. I believe they are not updating because there are multiple duplicate `id`'s on the same page. If you can get that working, we can also close this issue that just came in: https://github.com/carbon-design-system/carbon/issues/12315

**Comment by TannerS** [comment]
updated

**Comment by TannerS** [comment]
> @TannerS can we ensure each `Tile` has a unique `id`? There seem to be some issues when there are multiple `Tile` examples on the same page. To see the issue, go to the `Radio with Layer` story, as well as the docs [tab](https://deploy-preview-12312--carbon-components-react.netlify.app/?path=/docs/components-tile--expandable-with-interactive) and try and interact with `select` and then `radio` examples. I believe they are not updating because there are multiple duplicate `id`'s on the same page. If you can get that working, we can also close this issue that just came in: #12315

hey i looked into this, it appears some tiles (like radio) include this 

```
export function useFallbackId(id) {
  const fallback = useId();
  return id ?? fallback;
}
```

so i cant do nothing about that, but let me manually set the ids

**Comment by TannerS** [comment]
@tw15egan fixed the issue #12315, by adding new ids for components i playground

**Comment by tw15egan** [comment]
@TannerS looks good; the issue seems resolved 🎉

**Comment by TannerS** [comment]
> @TannerS looks good; the issue seems resolved 🎉

cool, anything else let me know

**Comment by tw15egan** [comment]
@TannerS any idea why there are snapshot changes in this PR?

**Comment by TannerS** [comment]
> @TannerS any idea why there are snapshot changes in this PR?

not a clue, tbh idk how snapshots work. I know i merged in main into this branch though

**Review by tw15egan — APPROVED** [review]

**Review by sstrubberg — APPROVED** [review]

**Pull request merged**
