### PR TITLE
fix(data-table): update batch action button icon and text color

### LINKED ISSUE #2371: Data Table: batch action button & icon colors are not properly themed
## Detailed description

The batch action icon fill colors are set to `$ui-01`. Whereas that color looks correct in lighter themes, for gray90 and gray100 themes that color is too dark and inaccessible.

Ideally the batch action icon fill colors should be `$icon-03`, which is always white and would therefore look good against the blue60 button background color + work with all themes.

### PR DESCRIPTION
**Pull request by jendowns**
Closes #2371 

#### Changelog

**Changed**

- use `$text-04` (white, all themes) for batch action cancel button `:before` color
- use `$text-04`  (white, all themes) for batch action text color
- use `$text-04`  (white, all themes) for batch action summary text color
- use `$icon-03` (white, all themes) for batch action icon fill color
- use `$icon-01` (gray10 for dark themes, gray100 for light themes) for toolbar icon fill color

### CODE REVIEW

**Comment by jendowns** [comment]
FYI there's also another place for a batch action icon fill color is being set 🤔 But I think it is not used anywhere?  https://github.com/carbon-design-system/carbon-components/blame/a47a4fa259e20acd5a72a8ae0eab0bdaf4c08a4e/src/components/data-table/_data-table-action.scss#L187

```
.#{$prefix}--toolbar-action__icon {
    height: $layout-01;
    width: auto;
    max-width: $layout-01;
    fill: $ui-05;
}
```

Do you want me to update that to `$icon-03` as well? 🤔 Or remove it?

**Review by tw15egan — APPROVED** [review]
Looks good! 👍 It looks like `L187` is modifying the toolbar icon colors.

 If I remove it, I get this:

Screen Shot 2019-05-01 at 10 18 17 AM

If anything, perhaps we should update it to `$icon-01`?

**Comment by jendowns** [comment]
Thanks @tw15egan! I just updated that color to `$icon-01` 👍

**Review by lovemecomputer — APPROVED** [review]
cool, thanks for this catch! we should probably get a designer verification on this too

**Review by designertyler — APPROVED** [review]

**Pull request merged**
