### PR TITLE
Test coverage for TreeView component

### LINKED ISSUE #17502: Increase `TreeView` unit test coverage

### PR DESCRIPTION
**Pull request by soumyaraju**
Closes #17502

Added tests for TreeView component

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by guidari** [comment]
Hey @soumyaraju Thanks for opening that!
I noticed the test it 74.48%, is there any reason why [those lines](https://app.codecov.io/gh/carbon-design-system/carbon/pull/18072/blob/packages/react/src/components/TreeView/TreeView.tsx) weren't tested?

**Comment by soumyaraju** [comment]
Thanks @guidari for looking into this PR, i added few more tests to cover the uncovered lines, thus increased coverage, Please review it. TIA

**Review by guidari — APPROVED** [review]
Thnaks @soumyaraju 
LGTM 🚀

**Comment by soumyaraju** [comment]
Thanks for the approval, @guidari can you help me merging this PR? TIA

**Pull request merged**
