### PR TITLE
fix: 15758 managed state inside the MultiSelect and rendered when change occurs

### LINKED ISSUE #15758: [Bug]: Multiselect drop down throwing browser console error while selecting the value first time
### Package

@carbon/react

### Browser

Chrome, Firefox

### Package version

v1.49.0

### React version

v18.2.0

### Description

Multiselect dropdown throwing browser console error while selecting the value the first time
Error Details:
`App.jsx:13 Warning: Cannot update a component (`App`) while rendering a different component (`MultiSelect`). To locate the bad setState() call inside `MultiSelect`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at https://githubbs1zsv-faiz--5173--a9c8a5a3.local-credentialless.webcontainer.io/node_modules/.vite/deps/@carbon_react.js?v=703ae265:97328:16
    at div
    at App (https://githubbs1zsv-faiz--5173--a9c8a5a3.local-credentialless.webcontainer.io/src/App.jsx:22:49)`

Screenshot: 
image

I have reproduced this issue here
https://stackblitz.com/edit/github-bs1zsv?file=src%2Findex.scss,src%2FApp.jsx&preset=node=

### Reproduction/example

https://stackblitz.com/edit/github-bs1zsv?file=src%2Findex.scss,src%2FApp.jsx&preset=node=

### Steps to reproduce

1. Open URL:https://stackblitz.com/edit/github-bs1zsv?file=src%2Findex.scss,src%2FApp.jsx&preset=node=
2. Open the console tab in the developer tool
3. Select the value from the multi-select dropdown
4. When we select the 1st value, throw console error "Bad setState inside the Multiselect"

### Suggested Severity

Severity 2 = User cannot complete task, and/or no workaround within the user experience of a given component.

### Application/PAL

I am using React carbon component

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [ ] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by huzaifabhutta**
Closes #15758

When using the `controlledItems` in `MultiSelect`, React was throwing this warning below:
```
Warning: Cannot update a component ('Unknown') while rendering a different component ('MultiSelect'). 
To locate the bad setState() call inside 'MultiSelect'
```
`setState` was being called inside the `useSelection` when `onChange` callback was passed
#### Changelog

**Changed**
- Moved the `callOnChangeHandler` inside the useEffect with `isControlled, isMounted, selectedItems` as it's dependencies
- Managed the selectedItems state inside the useSelection 

**Removed**

- Removed `callOnChangeHandler` function from `onItemChange`

#### Testing / Reviewing

- Use the `MultiSelect` component with controlled items
- Pass `selectedItems` and `onChange` props inside the component
- Open Dev console in any browser
- Click the component and select any first item
- The above error will not come now

##### Before Change 
https://github.com/carbon-design-system/carbon/assets/55208374/7f6f7648-6290-4f66-a918-c3755caf207b

##### After Change

https://github.com/carbon-design-system/carbon/assets/55208374/31fe25ae-641b-4d39-b88f-c305a501aa84

### CODE REVIEW

**Comment by mHuzefa** [comment]
Hey @tw15egan @alisonjoseph, can you please let me know why percy/Carbon-Monorepo is failing? Is it something with the code? because visually there will be no change.

Thank you

**Review by tay1orjones — COMMENTED** [review]
Thanks for taking a look at this! I think this looks okay.

This bug might've slipped in because while there are tests covering `onChange` and `initialSelectedItems`, there's not one covering `selectedItems`.

https://github.com/carbon-design-system/carbon/blob/bfea2ed30589f830c7c2f15c9caf0090b8c64454/packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js#L407
https://github.com/carbon-design-system/carbon/blob/bfea2ed30589f830c7c2f15c9caf0090b8c64454/packages/react/src/components/MultiSelect/__tests__/MultiSelect-test.js#L276

Could you write a new test to cover this controlled use case using onChange and selectedItems together as in your example/test code?

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Pull request merged**
