### PR TITLE
fix(DataTable): guard npe when cells being sorted do not exist

### LINKED ISSUE #9713: [Bug]: DataTable throws exception if the sorted column is not rendered
### Package

carbon-components-react

### Browser

Chrome

### Package version

v7.7.0

### Description

DataTable throws an NPE when the cells being sorted do not exist.

### CodeSandbox example

https://ijsul.csb.app/

### Steps to reproduce

In the code sandbox, click "Port" column header to sort by Port, then click the blue button at the bottom to see the exception.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by holmansze**
Closes https://github.com/carbon-design-system/carbon/issues/9713

DataTable throws an NPE when the cells being sorted do not exist.

We have a table settings feature for DataTable where users can show or hide table columns. When the column is hidden, it is removed from `headers` prop to DataTable. If this column happens to be used for sorting, an NPE is thrown.

The fix is simply an NPE check in the sorting code. When the cells being sorted do not exist, the sort compare function returns 0 (equal), and the table renders in the original (unsorted) order.

#### Changelog

**New**

- n/a

**Changed**

- added NPE check in the sorting code

**Removed**

- n/a

#### Testing / Reviewing

New code tested by removing the column being sorted from the `headers` prop. Worked as expected - table renders properly without sorting. When the column is added back, the table becomes sorted.

### CODE REVIEW

**Comment by holmansze** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by hoiwingh** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by hoiwingh** [comment]
recheck

**Review by tay1orjones — APPROVED** [review]
Thanks for taking a look at this! Previously I've recommended the use of a `key` or the `sortBy` function to correct the sort state when a column is removed from the table.
https://github.com/carbon-design-system/carbon/issues/9512#issuecomment-914656452

This PR definitely makes sense - the use of a `key` is no longer necessary, and there is still the option to use the `sortBy` function if reverting to unsorted is not desired.

It would be nice if a new test case was added to the sorting tests to prevent any regression of this functionality, but won't hold up a merge https://github.com/carbon-design-system/carbon/blob/eff767ddfc4bc41b8ebffff72017591ca86bb9e1/packages/react/src/components/DataTable/state/__tests__/sorting-test.js#L8

**Comment by holmansze** [comment]
@tay1orjones - thanks for your review! Unit tests added.

**Review by jnm2377 — APPROVED** [review]

**Comment by jnm2377** [comment]
Thanks for the contribution!

**Comment by holmansze** [comment]
Thanks @tay1orjones and @jnm2377 !

**Pull request merged**
