### PR TITLE
Focus states: Tooltip, notification, modal, file uploader

### PR DESCRIPTION
**Pull request by marijohannessen**
## Overview

Resolves https://github.ibm.com/Bluemix/design-system-website/issues/1064
Resolves https://github.ibm.com/Bluemix/design-system-website/issues/1079
Resolves https://github.ibm.com/Bluemix/design-system-website/issues/1066
Resolves https://github.ibm.com/Bluemix/design-system-website/issues/1058

Updated focus states for tooltip, notification, modal, file uploader.

### CODE REVIEW

**Comment by tw15egan** [comment]
👍 ✅ ❗️  Only thing I noticed was that you can't press enter on the file-uploader to trigger the file selection, but that could be a limitation of the `<input type="file" />` element

**Comment by marijohannessen** [comment]
Yeah, I noticed that as well. Not sure how to fix that, we should probably open a separate issue about it.

**Comment by hellobrian** [comment]
> Only thing I noticed was that you can't press enter on the file-uploader to trigger the file selection, but that could be a limitation of the `<input type="file" />` element

Yeah, this is because we're styling the `<label>` to look like a button. 
In JS, I'm we can add an event listener for using keyboard enter key.

**Comment by hellobrian** [comment]
Can you also add focus state to the close icons that appear in edit state? 
You can make the icons appear when you add files and then invoke this in browser console:
```js
CarbonComponents.FileUploader.components.get(document.querySelector('[data-file]')).setState('edit');
```
And you can add styles to `.bx--file-close`

**Review by hellobrian — CHANGES_REQUESTED** [review]
See comments about file-uploader in conversation

**Comment by marijohannessen** [comment]
Just updated the PR so the close icon gets focus as well, I just needed to add a tabindex to the SVG @hellobrian .

**Review by hellobrian — APPROVED** [review]
👍 ✅

**Pull request merged**
