### PR TITLE
fix(MultiSelect): add missing enter key support to open menu

### LINKED ISSUE #3861: bug(MultiSelect): does not open menu on enter
**Description**
Tab to the Multiselect box
Hit the Enter

The Enter key does not expand or collapse the listbox.

See ARIA Authoring Practices Guide for additional information. 

It states the following:

Enter key:

If the focus is on the button, expands the listbox and places focus on the currently selected option in the list.
If focus is in the listbox , collapses the listbox and keeps the currently selected option as the button label.

-->

## Environment

> Operating system
macOs Mojave Version 10.14.6
> Browser
Chrome

## Detailed description

> What version of the Carbon Design System are you using?
v10

> What WCAG 2.1 checkpoint does the issue violate?
I don't think this technically violates WCAG 2.1. A user can still access the menu with their keyboard, just with the spacebar and not the enter key.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3861.

#### Changelog

**New**

- Enter key support in `<MultiSelect>` and its filterable variant, to open the dropdown.

#### Testing / Reviewing

Testing should make sure `<MultiSelect>` and its filterable variant are not broken.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
previously the user could make several selections with the keyboard before manually closing the list, but currently the only way to select list items is the <kbd>Enter</kbd> key, which will close the list after each selection. should we make <kbd>Space</kbd> select list items now (without closing the list)?

**Comment by abbeyhrt** [comment]
@emyarod  It is a requirement that `space` open menus but it is optional/nice to have that `enter` open menus. Since we use `enter` to select the items, it might be crazy complicated to have `enter` both open/close the menu and select items. I actually meant to close #3861 but I never got around to it, my bad!

**Comment by tw15egan** [comment]
Curious what @dakahn thinks is best for this interaction

**Comment by dakahn** [comment]
I'm with @abbeyhrt less is more here. 👍

**Comment by asudoh** [comment]
OK let's close - Thank you for your thoughts everybody!

**Pull request closed without merging**
