### PR TITLE
fix: fixed hover on multiselect

### LINKED ISSUE #17820: [Bug]: Readonly state in Multiselect and FilterableMultiselect has hover interaction on the close button.
### Package

@carbon/react

### Browser

Chrome

### Package version

v11

### React version

v18

### Description

from the comment in this [PR](https://github.com/carbon-design-system/carbon/pull/17662#pullrequestreview-2367110367), we found out that the hover state is still present on the button when in readonly state. This is from the components `ListBox.Selection` and `ListBoxSelection` (which is in the next folder). 

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-multiselect--playground&args=readOnly:!true

### Steps to reproduce

go to the above link and hover on the 'X' button.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [x] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by guidari**
Closes #17820

Setting background-color to transparent when `Multiselect` is set to `readOnly`

#### Testing / Reviewing

- Go to playground and set `Multiselect` or `FilterableMultiselect` to `readOnly`

### CODE REVIEW

**Review by Gururajj77 — APPROVED** [review]

**Review by preetibansalui — APPROVED** [review]

**Comment by preetibansalui** [comment]
It looks good to me but I think it's better to take a design review on this one.

**Review by laurenmrice — CHANGES_REQUESTED** [review]
@guidari Looking good! Just  two small things:

**MultiSelect and Filterable MultiSelect**
- The border around the tag is not the correct color. The [design spec](https://github.com/carbon-design-system/carbon/issues/17820#issuecomment-2427496780) says it should be color token `$border-subtle`.

**MultiSelect**
- On the "Playground" story of MultiSelect, when the readonly prop is set to true, when hovering over the field and tag, there are still areas where the mouse cursor turns to a pointer instead of the arrow. It should always be the arrow in the readonly state.
Nov-05-2024 15-14-19

**Review by tay1orjones — APPROVED** [review]
LGTM once the cursor is updated 👍

**Comment by guidari** [comment]
> @guidari Looking good! Just two small things:
> 
> **MultiSelect and Filterable MultiSelect**
> 
> * The border around the tag is not the correct color. The [design spec](https://github.com/carbon-design-system/carbon/issues/17820#issuecomment-2427496780) says it should be color token `$border-subtle`.

Thanks @laurenmrice ! My bad, I didn't the design spec down there in the issue 😅

**Review by laurenmrice — APPROVED** [review]
Looks good to me. Thanks Gui!

**Pull request merged**
