### PR TITLE
feat(Tooltip): sass module refactor

### LINKED ISSUE #8969: feat(Tooltip): add Tooltip to @carbon/styles
This issue is for updating the Tooltip component to Sass Modules in the `@carbon/styles` package. In this refactor, we will:
- [x] Copy over styles for for the component to `packages/styles/scss/components/{component}/_{component}.scss`
  - Any additional files will live in the folder `packages/styles/scss/components/{component}/`
- [x] Create an `_index.scss` at `packages/styles/scss/components/search/_index.scss`
- [x] Create a test file at `packages/styles/scss/components/__tests__/{component}-test.js`
- [x] add the storybook stories to @carbon/react
- [x] `@forward` the mixin and any variables from `_{component}.scss` in `_index.scss`
- [x] Include the styles from `_{component}.scss` by calling the mixin in `_index.scss`
- [x] in `{component}-test.js` test the public API/config options of the `/_index.scss` file
- [x] The `_{component}.scss` will then need to be refactored to use the new import paths and conventions. You can find common recipes here: https://github.com/carbon-design-system/carbon/issues/8899#issuecomment-860887959

### PR DESCRIPTION
**Pull request by dakahn**
Closes #8969 

Tooltip sass module refactor 🏄🏽 

#### Testing / Reviewing

Everything should be exactly how you remember it. 🙏🏽

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
not sure how they're being handled in the sass module refactor but `$caret-size` seems like a component token

it looks like CI is failing since the timing function variables are not defined as well

```console
Error: Undefined variable.
    ╷
128 │     transition: opacity $duration--fast-01 motion(standard, productive);
    │                         ^^^^^^^^^^^^^^^^^^
```

**Review by emyarod — COMMENTED** [review]
the "custom icon only" story still has the label, is that difference from the original story intentional?

image

**Comment by andreancardona** [comment]
> not sure how they're being handled in the sass module refactor but `$caret-size` seems like a component token
> 
> it looks like CI is failing since the timing function variables are not defined as well
> 
> ```
> Error: Undefined variable.
>     ╷
> 128 │     transition: opacity $duration--fast-01 motion(standard, productive);
>     │                         ^^^^^^^^^^^^^^^^^^
> ```

@dakahn I think that variable needs to be updated to `$duration-fast-01` (single dash across the whole variable)

**Comment by andreancardona** [comment]
approving for now pending update on the `$duration-fast-01` variable

Looks good 🎉

**Review by andreancardona — APPROVED** [review]
approving for now pending update on the `$duration-fast-01` variable

Looks good 🎉

**Review by emyarod — APPROVED** [review]

**Pull request merged**
