### PR TITLE
fix(Tab): hoist tab role to upper element

### LINKED ISSUE #5083: [Tab]: VoiceOver does not announce number of tabs
## Environment

> Operating system
macOS 10.14.6

> Browser
Chrome 79

> Assistive technology used to verify
VoiceOver

## Detailed description

> What version of the Carbon Design System are you using?
carbon-components-react@7.9.1

> What did you expect to happen?
When tabbing through tabs, VoiceOver should announce the number tabs in this group, e.g. "[label], selected, tab, 4 of 4"

> What happened instead?
VoiceOver always announces the current tab as 1 of 1.

> What WCAG 2.1 checkpoint does the issue violate?

## Steps to reproduce the issue

1. Open http://react.carbondesignsystem.com/?path=/story/tabs--default
2. Click a tab
3. Activate VoiceOver
4. Tab between the tabs

## Additional information

carbon-tab

### PR DESCRIPTION
**Pull request by asudoh**
This change hoists `tab` role and its associated ARIA attributes from
`<a>` to `<li>`, given putting `tab` role to `<a>` makes VoiceOver
think it's a single tab in a container.

No new DAP error is observed by this change.

Fixes #5083.

#### Changelog

**Changed**

- A change to hoist `tab` role and its associated ARIA attributes from
`<a>` to `<li>`, given putting `tab` role to `<a>` makes VoiceOver
think it's a single tab in a container.

#### Testing / Reviewing

Testing should make sure React tabs is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, tabs are now numbered correctly by voiceover

image

**Review by abbeyhrt — APPROVED** [review]
Looking into it, it seems like the ideal way to get tabs to announce the "1 of 5..." way is through putting `aria-owns` with the tab ids on the element with the tablist role, "Elements with the role tab must either be a child of an element with the tablist role, or have their id part of the aria-owns property of a tablist. This combination identifies to assistive technology that the element is part of a group of related elements. Some assistive technology will provide a count of the number of tab role elements inside a tablist, and inform users of which tab they currently have targeted. " Since I think that would be crazy complicated to implement with the way we have tabs set up, this looks good to me 👍

**Comment by abbeyhrt** [comment]
@dakahn would you have time to test this with NVDA or Jaws? It announces well for VO but I just can't verify with the others

**Review by dakahn — APPROVED** [review]
Testing with NVDA the tabs are accessible and announced well. Activating and deactivating is announced properly. Worth noting is that the disabled Tab is still accessible and announced as disabled. The tabs receive focus, but are not automatically activated and require a keypress.

Testing with JAWS 2019 tabs are focusable and read, as well as activated on focus. Disabled tabs are ignored and can't be keyboard accessible.

**Pull request merged**
