### PR TITLE
fix(dropdown): increase max-height for all dropdown variants

### LINKED ISSUE #6195: [dropdown] change cropped option before scroll
When a dropdown is open, we need to change the crop of an option before scroll to the 6th option instead of the 4th option.

Spec:
dropdown-usage-7 copy

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/6195

This PR increases the `max-height` of all  normal dropdown variants to `220px` 
- `40px dropdown item height * 5.5 items shown`

Also changes the `max-height` for `sm` and `xl` variations

#### Changelog

**New**

- Updated all stories to include 6 items to show the new `max-height` working properly

**Changed**

- Increased `max-height` on dropdown / list box menu to `220px`, from `140px` for normal size dropdowns
- Fixed padding issue on `Multiselect` component (text was too close to checkbox)
- Fixed truncation issue on `Multiselect` component (text was not truncating)

#### Testing / Reviewing

Ensure all variants of `ListBox` and `Dropdown` render properly
- [x] `ComboBox`
- [x] `Dropdown`
- [x] `MultiSelect`

### CODE REVIEW

**Review by dakahn — APPROVED** [review]

**Review by asudoh — COMMENTED** [review]
🎉 - You are quick @tw15egan! My naïve question; I think list boxes recently got size variants, and if it's correct, how should dropdown height work for those size variants? Same size for all, or different size for different size variants?

**Review by laurenmrice — APPROVED** [review]
looks good to me ! thank you 🙌🏻

**Comment by tw15egan** [comment]
Ah, good point @asudoh. We would probably want to adjust the maths for different size dropdowns (i.e `32 * 5.5` for `sm` variant, `48 * 5.5` for `xl` variant).

@laurenmrice is that the correct assumption? Right now it is showing all 6 items on the `sm` version, and 4.5 on the `xl` version. I'm thinking we'd want to show 5.5 on all variations

**Comment by laurenmrice** [comment]
@tw15egan ohh, yes. We would want to show 5.5 for all sizes for consistency!

**Comment by tw15egan** [comment]
@laurenmrice @asudoh  updated 👍

**Comment by laurenmrice** [comment]
looks great, thank you guys !

**Review by asudoh — APPROVED** [review]
LGTM :+1: - Thanks @tw15egan for the update!

**Review by aledavila — APPROVED** [review]

**Pull request merged**
