### PR TITLE
fix(fileUploader): add aria label to span for upload button

### LINKED ISSUE #5726: FileUploader component accessibility issues
## Environment
Operating System: Mac OS Catalina 10.15.3 (19D76)
Browser, Version: Google chrome: Version 80.0.3987.87

> Automated testing tool and ruleset
DAP

## Detailed description

> What version of the Carbon Design System are you using?

Cloud Patterns and Assets Library Version: "@console/pal": "1.90.8"

> What did you expect to happen?

A default aria-label or aria-labelledby value or any option to define these values.

> What happened instead?

Dap is reporting issue with latest rule set

> What WCAG 2.1 checkpoint does the issue violate?
IBM Accessibility January 2020

## Steps to reproduce the issue

Create a file uploader component
Run DAP browser extension with IBM Accessibility January 2020 ruleset

Links to code or a live example of the bug:

https://dev.console.test.cloud.ibm.com/security-advisor#/integrations
Step 1: Click on direct connection tile a modal will popup with file uploader component.
Step 2: Execute DAP

### PR DESCRIPTION
**Pull request by abbeyhrt**
Closes #5726 

This PR adds an aria-label of the label text to the span.

#### Changelog

**New**

- adds aria label to span for FileUploader button

#### Testing / Reviewing

Make sure that the FileUploader reads well for screenreaders and that there are no DAP violations

### CODE REVIEW

**Review by joshblack — CHANGES_REQUESTED** [review]

**Review by joshblack — COMMENTED** [review]
Should the contents be considered the label in this position? Would love to learn more about why we need `aria-label` here 👀

**Comment by abbeyhrt** [comment]
@joshblack Really it's just there to resolve the DAP violation but it's possible that DAP is mistaken here

**Review by emyarod — COMMENTED** [review]
voiceover seems to read the label here correctly on `master`. ~~if anything maybe we can just remove the `role` but I don't recall if it's needed.~~ (https://github.com/carbon-design-system/carbon/issues/4208 https://github.com/carbon-design-system/carbon/issues/4221 https://github.com/carbon-design-system/carbon/pull/4209) this might just be a false positive by DAP

**Comment by tw15egan** [comment]
Also wondering if that span itself is even needed? Can't we just render the `labelText` directly?

```jsx
<label>
      {this.state.labelText}
</label>
```

**Comment by emyarod** [comment]
that's what we used to do

https://github.com/carbon-design-system/carbon/issues/4208 https://github.com/carbon-design-system/carbon/issues/4221 https://github.com/carbon-design-system/carbon/pull/4209

**Comment by joshblack** [comment]
Yeah, seems like an issue with DAP misreporting since it should be announced by being content in the `<label>` as noted above 👆

**Comment by abbeyhrt** [comment]
@tw15egan the span is necessary! We need to have `role="button"` somewhere and the button role isn't valid for a `label`.

**Comment by abbeyhrt** [comment]
I'm gonna close this and just make an issue on the repo for DAP since it seems to be a problem on their end!

**Comment by fbarroso24** [comment]
> I'm gonna close this and just make an issue on the repo for DAP since it seems to be a problem on their end!

Hi @abbeyhrt, we recently ran into this issue as part of some `A11Y` testing on our product.  Two questions:

1) Do you have a link to the `DAP` issue you created?
2) Do you know what version of `Carbon` we can upgrade to in order to get this fix?  

Thanks in advance!

**Pull request closed without merging**
