### PR TITLE
test(file-uploader): update tests for FileUploader

### PR DESCRIPTION
**Pull request by joshblack**
Precursor to #3437, this PR updates some of the tests with file uploader before making any updates to the component itself for accessibility.

#### Changelog

**New**

**Changed**

- Update tests for file uploader
- Removed `isRequired` for `uuid` and addressed a bug where multiple buttons could have the same id

**Removed**

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
looks like snapshots need to be updated to pass CI otherwise looks good to me

**Comment by joshblack** [comment]
Updated!

**Comment by joshblack** [comment]
@emyarod @tw15egan let me know if I can help out at all with reviews!

**Review by abbeyhrt — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
thought I approved with my original review, looks good to me

**Pull request merged**
