### PR TITLE
feat(react): upgrade Downshift dependency to v5

### PR DESCRIPTION
**Pull request by dakahn**
We were on v1 Downshift and there are quite very meaningful accessibility fixes/improvements made. This PR upgrades downshift and updates tests/code for any breaking changes. 

### included changes
- Downshift updated from v1 to v5
- combobox/tests updated
- dropdown/tests updated
- filterable multiselect/tests updated
- multiselect/tests updated
- test helpers updated with new downshift props

### to test
Open Multiselect, Dropdown, and Combobox and makes sure all functionality is working as expected 🏄 

_@aledavila @abbeyhrt and anyone on core working on our listy-dropdowny components. We should do a quick check on any bugs in our backlog and see if we don't get free fixes via this update 👍_

### CODE REVIEW

**Comment by vpicone** [comment]
Are we not going to man-in-the-middle the `downShiftProps` or whatever that we allow folks to pass in? It would guard against folks that might have been using the deprecated function names

**Review by vpicone — CHANGES_REQUESTED** [review]
For safety, we should man-in-the-middle the downShiftProps or whatever that we allow folks to pass in.  It would guard against folks that might have been using the deprecated function names

**Comment by vpicone** [comment]
Do we have a list of follow up issues to look into after this? It unlocks some really nice things: https://github.com/carbon-design-system/carbon/pull/4950

**Comment by dakahn** [comment]
@vpicone not that i'm aware of 🤔

**Comment by dakahn** [comment]
closing and reopening as #5373

**Pull request closed without merging**
