### PR TITLE
feat(notification): introduce high contrast style

### LINKED ISSUE #2354: [Notification] Add high contrast style
Designers made a change to notification component styles. The colored styles were not working across the different themes so we switched them to high contrast moments.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #2354.

#### Changelog

**Changed**

- Notification text color to `$inverse-01`
- Notification background color to `$inverse-02`
- Notification icon color to `$inverse-01` (@carbon-design-system/design Does it match your intent?)
- Notification highlight color to `$inverse-support-0x`

#### Testing / Reviewing

Testing should make sure notification looks good.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by joshblack — APPROVED** [review]

**Comment by shixiedesign** [comment]
Thanks for getting this done so quickly! @asudoh Just 1 comment, 

- [ ] we have agreed to remove drop-shadow on the inline, but keep drop-shadow on toast. 
image

Inline notification got drop-shadow in the previous iteration because of the background color is too close to Gray10 ui-background. Now with high contrast colors, we can safely remove the drop shadow. Thanks!

**Review by shixiedesign — COMMENTED** [review]
Thanks for getting this done so quickly! @asudoh Just 1 comment, 

- [x] we have agreed to remove drop-shadow on the inline, but keep drop-shadow on toast. 
image

Inline notification got drop-shadow in the previous iteration because of the background color is too close to Gray10 ui-background. Now with high contrast colors, we can safely remove the drop shadow. Thanks!

**Comment/question:** Can we keep the previous style with colored background as a secondary style? We are seeing potential use cases where users might want the more subtle style, so ideally we can keep both, where High contrast is default/primary. Mentioned this in https://github.com/carbon-design-system/carbon/issues/2354#issuecomment-491400302 Thanks!

**Comment by asudoh** [comment]
@shixiedesign Updated the code to remove drop shadow from inline notification. Also implemented "light" variant with old color scheme - Great to have your thoughts on here, esp. would you think of better naming? Thanks!

**Review by shixiedesign — APPROVED** [review]
Perfect! 🎉 Thank you so much. 

Naming wise, 
- suggestion 1: `low-contrast` variant. Dark background has been referred to as `high-contrast` styling. 
- suggestion 2: `pastel` variant, but on dark themes this wouldn't make sense as much. 
- suggestion 3: say use `tinted background`? 

I proposed these to design team and will return with decision shortly. **Let's wait a minute to merge until this is resolved.**

**Comment by shixiedesign** [comment]
Hi @asudoh `low-contrast` is the name we like! Once naming changes we can merge. Thank you!

**Comment by asudoh** [comment]
Thank you for coming up with a name @shixiedesign! Updated.

**Pull request merged**
