### PR TITLE
fix(notification): title word wrap

### LINKED ISSUE #2294: [Carbon 10: Notification] Inline notification visual issues
## Detailed description

> Describe in detail the issue you're having.

1. The warning notification has a transparent background so if it's applied to any thing other than a white background the color doesn't stay consistent (could use the sass `mix` function to blend it with white to make it opaque if it's not in the IBM DL color palette)
2. Timestamp styling is not supported in inline notifications but is in toast notifications.  I'd like to apply the same styles for both notification types without having to copy and past Carbon's code in to my style sheets.

> Is this issue related to a specific component?

Notification

> What did you expect to happen? What happened instead? What would you like to see changed?

1. The background on the information notification is opaque
2. I don't have to copy and paste Carbon's code to style a timestamp

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library (PAL)

## Steps to reproduce the issue

Issue 1
1. Change the page background color when using a warning notification

Issue 2
1. Add a time stamp to an inline notification

## Additional information

Screen Shot 2019-04-11 at 5 08 53 PM

### PR DESCRIPTION
**Pull request by elizabethsjudd**
Closes #2294 

Notifications with long titles need to wrap so the content is visible

#### Changelog

**Changed**

- the word wrapping for inline notification titles

#### Testing / Reviewing

Test notifications with different title lengths in all Carbon supported browsers

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
Would we want it to wrap, or would we want it to have a `title` attribute or custom tooltip? cc @carbon-design-system/design

**Comment by elizabethsjudd** [comment]
I was going based on the solution accepted here: https://github.com/carbon-design-system/carbon/pull/2746. FYI, the `title` attribute is not a11y compliant for sighted keyboard users so it would need to be a custom tooltip if that's the approach design chooses

**Review by tw15egan — APPROVED** [review]
LGTM 👍

**Review by emyarod — APPROVED** [review]
looks good to me!

**Pull request merged**
