### PR TITLE
fix: interactive tile expand button

### PR DESCRIPTION
**Pull request by lee-chase**
Interactive tile expand button ignores spacebar press.

#### Changelog

InteractiveTile expand/close

#### Testing / Reviewing

Buttons should be operable via the spacebar. In the existing code the expand/collapse of the interactive tile has this disabled to cope with text box usage. 

This PR processes the keypress to check that it is targeting the expand button.

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
This LGTM, should we add a test around this?

**Review by guidari — APPROVED** [review]
LGTM! 🚀

To add some tests you can use this as an example. 
- Add a new `Tab`;
- Change the selector;
- Change from `Enter` to `Space`

https://github.com/carbon-design-system/carbon/blob/6bd58e650e51b2d3e1b3f2f1607c8a99bef10680/e2e/components/Tile/Tile-test.avt.e2e.js#L112-L127

**Comment by tay1orjones** [comment]
@lee-chase would you be up for adding tests to this?

**Review by tay1orjones — APPROVED** [review]
I've added the necessary tests and corrected some that were failing

**Pull request merged**
