### PR TITLE
fix(tag): fix for dark theme

### LINKED ISSUE #4022: Tag (tag) component has insufficient contrast on Gray 100 theme
## Environment

Windows 10
Chrome Version 76.0.3809.132 (Official Build) (64-bit)

## Detailed description

Carbon v10 - React

Component: Tag (filter), http://themes.carbondesignsystem.com/?nav=tag

The component is using,
`background-color: interactive-02, color: inverse-01`

When switching to the Gray 100 theme, the contrast ratio has dropped to 3.57 (WCAG AA: Fail).
I used WebAIM (https://webaim.org/resources/contrastchecker/) to check the colour contrast.

## Additional information

tag

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #4022.

#### Changelog

**Changed**

- Colors of filter version of tag.

#### Testing / Reviewing

Testing should make sure our tag component is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me

image

image

image

**Review by laurenmrice — CHANGES_REQUESTED** [review]
- [ ] The tag focus should get the `inverse-focus-ui` token 

- [ ] The close icon should not be getting a white hover color, it should stay `icon-01`.
tag

**Comment by asudoh** [comment]
Thanks @laurenmrice for reviewing. Made an update. Let me close this PR for now. Will reopen when the work of next release starts.

**Comment by aledavila** [comment]
Reopening as a11y team has started work again

**Comment by asudoh** [comment]
Thanks @aledavila! @laurenmrice Could you re-review? Thanks!

**Review by abbeyhrt — APPROVED** [review]
Looks good to me! Thanks @asudoh!

**Review by laurenmrice — CHANGES_REQUESTED** [review]
The colors look correct per theme and in vanilla and react but when clicking on the close icon, the close icon gets smaller. It should always be the same size

Gif for reference:
tag

**Comment by asudoh** [comment]
Thanks @laurenmrice for pointing this out! It seems an existing issue that seems not related to color contrast stuff this PR addresses. Reported at: #4289

**Review by laurenmrice — APPROVED** [review]
Alright then looks good to me 👍  . thanks for opening that other pr !

**Pull request merged**
