### PR TITLE
Storybook 8

### LINKED ISSUE #16468: Update Storybook to v8
Storybook v8 has been out for a while now - [8.1](https://github.com/storybookjs/storybook/releases/tag/v8.1.0) just dropped today actually. 

We should update to stay current and take advantage of the [new features](https://storybook.js.org/blog/storybook-8/). There's a [migration guide](https://storybook.js.org/docs/8.0/migration-guide) to follow and the [expanded changelog](https://github.com/storybookjs/storybook/blob/4780ae31030197488d66b4fba483867f416bdb0a/MIGRATION.md?ref=storybookblog.ghost.io) will also be helpful.

### PR DESCRIPTION
**Pull request by guidari**
Closes #16468

Storybook 8 is coming 🚀

#### Changelog

**New**

- Upgrade Storybook from `7.1.0` to `8.1.10`
- Added `@storybook/addon-webpack5-compiler-babel`

**Changed**

- `ArgsTable` Doc block replace by `ArgTypes` on `.mdx` files. | [docs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#argstable-doc-block-removed)
- `<Story of={componentStory} />` replace by `<Canvas of={componentStory} />` | [docs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#canvas-block)
- Switch `@storybook/addons` for `@storybook/manager-api` | [docs](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#canvas-block:~:text=%40storybook/addons%20%2D%20this%20package%20has%20been%20split%20into%202%20packages%3A%20%40storybook/preview%2Dapi%20and%20%40storybook/manager%2Dapi%2C%20see%20more%20here%3A%20New%20Addons%20API.)
- Fixed imports in `packages/react/src/index.js`

**Removed**

- Removed the `babelLoader.exclude` since there is no need anymore for that.

References:
- https://github.com/vitejs/vite/issues/5269
- https://github.com/evanw/esbuild/issues/2363#issuecomment-1171992206

#### Testing / Reviewing

Pull down locally

`yarn install`
`yarn build`
`yarn storybook`

- Please test all things in storybook 🙏🏻, docs, playground controls, skeleton, default stories, feature flags, actions... 
- Make sure we still have all the functionalities we used to have on v7.
Should all be running smoothly and let me know of any issues.
- CI should pass

### CODE REVIEW

**Comment by guidari** [comment]
The only missing thing to fix is this "Sourcemap" issue that I'm trying to find a solution. Other than that I think this looks good to review.
Screenshot 2024-07-12 at 16 49 57

**Comment by tay1orjones** [comment]
@guidari someone opened an issue for what seems like the same thing: https://github.com/storybookjs/storybook/issues/28567

**Comment by tay1orjones** [comment]
@guidari also the deploy previews are failing due to what appears to be __DEV__ being undefined in production https://app.netlify.com/sites/v11-carbon-react/deploys/66917f1dc9a2210008441725

**Review by kennylam — APPROVED** [review]
@guidari Nice, LGTM!

I noticed some warnings about sourcemaps:

Screenshot 2024-08-09 at 4 55 24 PM

 These can be removed by deleting Yarn `.cache` and `yarn.lock` and rebuilding both. However, that introduces the nested rule Sass error Guru brought up the other day.

image

Either way, neither one of those issues prevents Storybook from running properly, so it's up to you which way you want to merge it in.

**Comment by guidari** [comment]
> @guidari Nice, LGTM!
> 
> I noticed some warnings about sourcemaps:

Thanks @kennylam , we have to fix that. 

I'm also trying to figure it out why `__DEV__` is being undefined in the the [deploy preview](https://deploy-preview-16910--v11-carbon-react.netlify.app/). I've tried several ways to configure the `main.js`, but I couldn't come to a conclusion yet.

**Review by tay1orjones — COMMENTED** [review]
We shouldn't merge this until the Percy failures are resolved. https://github.com/carbon-design-system/carbon/pull/16582 should fix it though by waiting for the story to be loaded and rendered. I'll try to get eyes on that PR and merge it asap so we can get this in.

**Comment by guidari** [comment]
@kennylam @tay1orjones 
I guess we cann approve this Percy now. After merging the [toContainAStory](https://github.com/carbon-design-system/carbon/pull/16582) the Percy failing that was blocking us is not a problem anymore.

**Comment by kennylam** [comment]
Yep, snapshots all look good. Although I can't tell if the updated snapshots are correct or not. Looks like some spacing changes and gradient removal?

**Comment by guidari** [comment]
@kennylam 
Yeah, there is something wrong with the spacing. I'm gonna check to see what is going on

**Review by tay1orjones — APPROVED** [review]
🎉 Thanks for all your hard work on this!

**Pull request merged**
