### PR TITLE
feat(theme): adding optional utility classes

### PR DESCRIPTION
**Pull request by DusanMilko**
Proposing addition of optional utility classes to specify colors.

This helps with making theme support easier for components and instances of javascript component libraries.

Format: 
PROPERTY--TOKEN

To prevent generation of too many classes, tokens have appropriate properties assigned.

OPEN TO FEEDBACK 👍

### CODE REVIEW

**Comment by joshblack** [comment]
Love this, reminds me of some explorations I did for this and spacing: https://www.sassmeister.com/gist/552291162658f7054aa668d98bc291e4?token=a0ab2532571148490a9f6f5bf22712a17038cdd9&scope=gist,read:user

When thinking about color earlier, it seemed like Tailwind leaned on:

- `background-color` as `bg-{color}`
- `text-color` as `text-{color}`
- `border-color` as `border-{color}
- `fill` seems like they use `fill-current` to set it to the text color 🤔 

Curious what you think of those conventions, along with how they include variants for things like focus/hover or even responsive names 👀

**Comment by DusanMilko** [comment]
> Love this, reminds me of some explorations I did for this and spacing: https://www.sassmeister.com/gist/552291162658f7054aa668d98bc291e4?token=a0ab2532571148490a9f6f5bf22712a17038cdd9&scope=gist,read:user
> 
> When thinking about color earlier, it seemed like Tailwind leaned on:
> 
> * `background-color` as `bg-{color}`
> * `text-color` as `text-{color}`
> * `border-color` as `border-{color}
> * `fill` seems like they use `fill-current` to set it to the text color 🤔
> 
> Curious what you think of those conventions, along with how they include variants for things like focus/hover or even responsive names 👀

I find using the property name as the class makes mapping the easiest and understandable for devs. These classes are used by devs so making it easier for devs to understand in my opinion is ideal. If we shorthand some stuff like background to bg or swap color to text it makes it harder for devs to pick up the utility classes. In css you never do text: HEX or bg: HEX

To change background color use class background--{TOKEN} = in css background: TOKEN
To change text color use class color--{TOKEN} = in css color: TOKEN
To change fill color use class fill--{TOKEN} = in css fill: TOKEN

The mapping is 1-to-1, super easy for devs to pick up and understand.

UPDATED:
updated to allow pseudo

**Comment by joshblack** [comment]
@DusanMilko down for whatever naming makes sense, the structure above came from Tailwind as noted in the comment 👍 

I opened up an RFC as well for this use-case more broadly if you're interested: https://github.com/carbon-design-system/carbon/pull/7295

100% still a WIP but we've gotten a handful of requests for this and was curious what people would think if we just had a package for it and let folks configure what gets emitted/generated similar to Tailwind 👀

**Comment by joshblack** [comment]
Gonna close this out for the broader RFC in #7295 👀

**Pull request closed without merging**
