### PR TITLE
fix(tag) - Make tag more dynamic

### PR DESCRIPTION
**Pull request by DusanMilko**
In certain cases the fixed height can cause visual issues. This code maintains current visuals but allows the tag to scale based on large content or confined spaces

#### Changelog

**Changed**

- adjusted tag styles so they scale better but maintain current visuals

### CODE REVIEW

**Comment by aagonzales** [comment]
How do I test it to see what it's doing? I'm just seeing a normal tag in the storybook? Is there a design spec I can look at to validate it against?
Is this for if the text has to wrap within a tag?

**Comment by DusanMilko** [comment]
@aagonzales Yes this will allow the text to wrap if that case occurs but maintains current styles

You can text by making text longer in tag then the tag has space for

**Review by emyarod — COMMENTED** [review]
it seems in https://github.com/carbon-design-system/carbon/pull/4518 we opted to go with ellipses rather than dynamic height for filter tags

**Comment by DusanMilko** [comment]
@emyarod 4518 only applies to tags with bx--tag__label class which default tags don't use. 

We can make default scale with this pr and keep bx--tag__label for instances when ellipses are preferred

From 4518 I can infer we opted to have a modifier class(bx--tag__label) for ellipse instances

**Comment by emyarod** [comment]
right, I was using the filter tag as a point of reference for default tags. ultimately it comes down to what UX our designers prefer here

**Comment by aagonzales** [comment]
@DusanMilko Do you have a screen shot of a scenario where this would be needed? Just to help with context.

**Comment by aagonzales** [comment]
I'm just thinking beyond translation, if tags that are too long for a space that they need to wrap then maybe a tag isn't the correct format. I understand that user generated tags can cause problems but its also normal in scenarios like that for there to be a character limit on user generated items. Long tags somewhat defeat the scan-ability and usefulness of a using a tag in the first place. 

I'm also wondering if this is a layout problem and not a problem with tag itself. If a tag is over 300px wide then it probably shouldn't be a tag. And if you're having problems accommodating for ~300px wide tags then maybe tags aren't the correct solution for that layout and use-case anyways.

**Comment by aagonzales** [comment]
I guess I'm ok with this as a technical fail safe but we will need a lot of usage guidance on it. We really want to avoid short long tags, is there a way to prevent that from happening on the code side?

image

**Comment by asudoh** [comment]
Thank you for your thoughts @aagonzales! Wrt the code perspective, preventing the right-hand side from happening in code comes with performance cost, which would effectively be monitoring the width of tag and changing the wrapping behavior. So guidance-only approach sounds good.

**Comment by DusanMilko** [comment]
@aagonzales I agree with what you said. This code is just a fail safe incase the situation occurs.

**Comment by aagonzales** [comment]
So is the proposal that this become the default behavior and that the "ellipse" behavior remains as a prop/modifier?

**Comment by DusanMilko** [comment]
@aagonzales Yes, Thats the proposal

**Review by aagonzales — APPROVED** [review]
Ok I'm good with this then and we'll just need to add some good usage docs about all this to the tag page.

**Review by joshblack — APPROVED** [review]

**Pull request merged**
