### PR TITLE
v10.0.1

### PR DESCRIPTION
**Pull request by vpicone**

### CODE REVIEW

**Comment by joshblack** [comment]
@vpicone could you generate a changelog real quick to see what changes got picked up in 10.0.1? Can use the `npx` command in the docs (`npx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0`)

This might be a good step to add to the publishing docs too just so that in the PR we can see what changes are associated with the release branch 👍

**Comment by vpicone** [comment]
~~@joshblack hmmmm that command is merging notes all the way to back to 9.83.1~~

**edit:** RIP I forgot to pull upstream tags before running the command. We should prob add that as well. Here's the generated changelog:

## [10.0.1](https://github.com/IBM/carbon-components/compare/v10.0.0...v10.0.1) (2019-04-08)


### Bug Fixes

* update data table header to fit contents ([#2245](https://github.com/IBM/carbon-components/issues/2245)) ([3e38ceb](https://github.com/IBM/carbon-components/commit/3e38ceb)), closes [#2244](https://github.com/IBM/carbon-components/issues/2244)
* **combo-box:** support v10 input controls ([#2241](https://github.com/IBM/carbon-components/issues/2241)) ([b5584bb](https://github.com/IBM/carbon-components/commit/b5584bb))
* **multi-select:** add styles for filterable multiselect inputs ([#2265](https://github.com/IBM/carbon-components/issues/2265)) ([b457d9a](https://github.com/IBM/carbon-components/commit/b457d9a))
* **project:** update elements to 10.0.0 ([#2243](https://github.com/IBM/carbon-components/issues/2243)) ([e0d6856](https://github.com/IBM/carbon-components/commit/e0d6856))
* **radio-button:** make background color transparent ([#2238](https://github.com/IBM/carbon-components/issues/2238)) ([74d1168](https://github.com/IBM/carbon-components/commit/74d1168))
* **tabs:** use padding instead of margin ([#2250](https://github.com/IBM/carbon-components/issues/2250)) ([6d02294](https://github.com/IBM/carbon-components/commit/6d02294))


### Features

* **data-table:** add v10 toolbar and batch actions ([#2257](https://github.com/IBM/carbon-components/issues/2257)) ([de2243c](https://github.com/IBM/carbon-components/commit/de2243c))

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @vpicone!

**Comment by joshblack** [comment]
Should we separate out the feature if this is a patch release? Or should we bundle all under at a 10.1?

**Comment by vpicone** [comment]
That's a good question, I think that feature is at least part bug-fix too.

**Pull request closed without merging**
