### PR TITLE
feat(feature-flags): allow default feature flag value per feature

### PR DESCRIPTION
**Pull request by asudoh**
This change introduces a mechanism to allow consumer application to define a subset of feature flags and use the default ones for the remainders, instead of using all default ones or defining all feature flags.

#### Changelog

**Changed**

- Default feature flags and user-set feature flags are now merged, instead of overwritten

#### Testing / Reviewing

Testing should make sure our styles are not broken.

### CODE REVIEW

**Comment by joshblack** [comment]
Thanks for doing this @asudoh! Would be helpful in the future if we could have these kinds of discussions in issues before the PR, given that some of the tooling that's been instrumented with the code climate stuff can flag these long-running/high comment PRs.

I think the strategy that we have over in #1045 could be a good start to this strategy, and we can use that to evaluate adding more comprehensive features in the future. What do you think? Anything that should be added into that PR that you feel like is presented here?

**Review by joshblack — COMMENTED** [review]
Left a comment above ^

**Comment by asudoh** [comment]
As discussed privately in the team today, this PR is for a different topic from what we discussed yesterday. This PR is mainly for addressing a Sass limitation with defining default map item, which is discussed in: https://stackoverflow.com/questions/26957753/sass-configuration-map-with-default-values

**Comment by joshblack** [comment]
So for this change, what's the intended use-case? Is this for the situation we were talking about where:

- We turn on a flag by default
- Someone is enabling/disabling a feature flag
- As a result, the flag turned on is inadvertently left undefined

Or are there some other processes/flows where this helps out?

**Comment by asudoh** [comment]
@joshblack While your wording seems to represent your good understanding, let me put a slightly concrete case to ensure we are fully on the same page. If we have below in `src/globals/scss/feature-flags`:

```scss
$feature-flags: (
  foo: true,
  bar: true,
  baz: false,
) !default;
```

And consumer app has:

```scss
$feature-flags: (
  baz: true,
)
```

`foo`/`bar` flags are now lost as the consumer app's code re-sets them to undefined.

https://github.com/IBM/carbon-components/blob/a33a85f125dd96f468c15467ff87afeec866d9db/tests/fixture/test--feature-flags.scss covers the case. Ping me if you have any further questions - Thanks!

**Comment by asudoh** [comment]
Rebased the code and aligned the API better to the code seen in `master`.

**Comment by alisonjoseph** [comment]
Hi Akira, just wanted to be sure this is what this PR is doing.

If the user sets their own feature flags but doesn't set values for all of them then the default will be used from default feature flags?

**Comment by joshblack** [comment]
Thanks for verifying @asudoh! What advantages/disadvantages do you feel like we get from this form over strategies like map-merge? e.g.

```scss
$feature-flags: map-merge($feature-flags, (
  my-custom-flag: true
));
```

**Comment by asudoh** [comment]
@alisonjoseph Exactly!

@joshblack The only thing I’m aware of is the ability to late evaluation (letting consumers re-define feature flags after we define it). That said, we can go either way.

**Comment by asudoh** [comment]
Took @joshblack's suggestion to use `map-merge()`. Thanks @joshblack!

**Review by joshblack — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
