### PR TITLE
fix(date-picke): close range datepicker after clicking elsewhere on page

### LINKED ISSUE #772: Range data picker doesn't disappear after clicking elsewhere on page
## Detailed description

Clicking in to the start or end date pickers works fine - a dropdown showing the current month appears, and clicking outside of that dropdown causes it to disappear.

If I click on the calendar icon to the right of the date pickers, though, the dropdown shows up and then remains. Only by clicking in to the date selector and then on the page background can I make the dropdown go away.

I'm using Chrome 66.0.3359.139 on Mac OS X 10.13.3, viewing the example code here: http://www.carbondesignsystem.com/components/date-picker/code

## Steps to reproduce the issue

1. Click on the calendar icon to the right of the date pickers
2. Click to try and dismiss the dropdown box

## Additional information
* Screenshot:image
* Screen capture in ZIP file: [Carbon Date Picker Bug.zip](https://github.com/carbon-design-system/carbon-components/files/2006155/Carbon.Date.Picker.Bug.zip)

### PR DESCRIPTION
**Pull request by rezak-otmani**
## Overview

Resolves  #772

Close the date picker icon when this component loses focus

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Thanks @rezak-otmani for trying to address the problem. Could you try clicking on start date and then clicking on end date, and ensure that the date picker is still shown? The code you tried to remove has a reason being there as the comment says, and want to ensure that the purpose of the code won't be broken. Thanks!

**Comment by rezak-otmani** [comment]
Hi @asudoh, I don't know exactly if there is a side effect of the code I deleted,, but when we click on the start date, and then on the end date the date picker is always displayed, and it works

**Review by alisonjoseph — APPROVED** [review]
LGTM! 👍 

@asudoh I double checked the config in flatpicker and its related to having it always open, which I don't believe is the intended behavior. So this fix should be ok. https://flatpickr.js.org/examples/#inline-calendar

**Comment by asudoh** [comment]
Thanks @rezak-otmani and @alisonjoseph for diving into this topic! Here’s what I see *with* @rezak-otmani’s change:

without-workaround

And here’s what I expect:

with-workaround

@alisonjoseph is right that the usage of that option is not something Flatpickr intended, but the code was to prevent date picker from being closed in the scenario I brought up. Flatpickr has the code to close the dropdown in that scenario, and cannot be disabled unless we temporarily set `inline` option.

Hope it makes sense to everybody. Please don’t hesitate to bring up if there are any questions. Thanks!

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
I see what @asudoh is saying. So while this solves the issue of being able to click outside the dropdown after clicking on the calendar icon to close it, it creates a new issue where you can't click between input boxes without closing the dropdown prematurely.

**Review by marijohannessen — APPROVED** [review]
It's working for me! 👍 ✅

**Comment by marijohannessen** [comment]
@alisonjoseph can you review again and see if you're still seeing the issue?

**Review by alisonjoseph — APPROVED** [review]

**Comment by alisonjoseph** [comment]
LGTM now! ✅

**Pull request merged**
