### PR TITLE
feat(icons): add icons for covariate and factor

### PR DESCRIPTION
**Pull request by janhassel**
Add data type icons for covariate and factor.

#### Changelog

**New**
- Icon "covariate"
- Icon "factor"

#### Testing / Reviewing

1. Build `packages/icons`
2. Run `yarn develop` in `/packages/icons/examples/preview`
3. Look for the icons "covariate" and "factor"

### CODE REVIEW

**Comment by laurenmrice** [comment]
@janhassel do you know if these were approved/made by conrad?

**Comment by janhassel** [comment]
No, we haven't run those by Conrad yet.

**Comment by conradennis** [comment]
@laurenmrice icons are not approved. Will include the updated icons in a PR with the next batch of icons I add to the repo next week.

**Review by dakahn — APPROVED** [review]

**Comment by tw15egan** [comment]
Closing this PR as it sounds as if @conradennis will add this in a separate PR once approved.

**Comment by conradennis** [comment]
PR including `covariate` and `factor`: https://github.com/carbon-design-system/carbon/pull/5342

**Pull request closed without merging**
