### PR TITLE
chore(auto-update): enable autoupdate on PRs

### PR DESCRIPTION
**Pull request by tw15egan**
A possible solution to keep all of our PR's updated with master whenever a file is merged.

Link: https://github.com/marketplace/actions/auto-update

Repo:
https://github.com/chinthakagodawita/autoupdate

___

Possible alternatives:
https://github.com/marketplace/kodiakhq#pricing-and-setup

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
🔥

**Comment by joshblack** [comment]
🤞 this helps!

**Comment by tw15egan** [comment]
Haven't messed around with Actions so I'm not sure if there is anything else we need to do, but wanted to give it a shot. Would be great if we could keep all our PR's up to date...

**Comment by alisonjoseph** [comment]
oooh this is awesome. we should do on the website too if this works 😄

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
