### PR TITLE
fix(dropdown): use theme token for text color

### LINKED ISSUE #4323: [dropdown] Input text is not calling the right color in vanilla
In Vanilla, the dropdown top input text needs to be calling `text-01`. It may be calling black instead of text-01.

Ex:

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #4323.

#### Changelog

**Changed**

- The color of dropdown trigger text.

#### Testing / Reviewing

Testing should make sure our dropdown component is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me pending design review

image

**Review by laurenmrice — COMMENTED** [review]
For some reason i do not have access to theme tab switcher in react? Is there a way to fix that.

Vanilla looks correct.

**Comment by joshblack** [comment]
@laurenmrice just turned it on 👍 should be available in the next deploy preview

**Comment by joshblack** [comment]
@laurenmrice would you want to pair up with a dev this round since I doubt this PR will get another commit to trigger a rebuild?

**Comment by laurenmrice** [comment]
sure @joshblack

**Comment by abbeyhrt** [comment]
@laurenmrice I can show you the dark theme for react if you want to stop by my desk whenever!

**Comment by laurenmrice** [comment]
ok cool thanks abbey! Will come over once you are out of your meeting @abbeyhrt

**Review by abbeyhrt — APPROVED** [review]

**Review by laurenmrice — APPROVED** [review]
Got with Abbey to review the react link . Looks great thanks !

**Pull request merged**
