### PR TITLE
fix(accordion): resolve accordion header z-index issue

### LINKED ISSUE #5272: Tooltip Icon on an accordion label has z-index 0, which gets behind certain elements
I'm seeing issues with the <TooltipIcon as a label for the accordion, the tooltip shows behind a radio button
see reproducible here:

https://codesandbox.io/s/zen-hofstadter-km7to

The selected Radio button is overlayed over the "F" in that glob of text

image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5272

Refs https://github.com/carbon-design-system/carbon/pull/1674

Changes `z-index` value so that radio buttons are not overlayed on tooltip inside the accordion header.

#### Changelog

**Changed**

- Bumped `z-index` from `0` to `1`

#### Testing / Reviewing

See https://codesandbox.io/s/zen-hofstadter-km7to for example of the issue. Check a radio button, then hover over the filter icon. Inspect `.bx--accordion__title` and set `z-index: 1;`, and see that you can no longer see the filled radio button.

### CODE REVIEW

**Comment by tw15egan** [comment]
cc @asudoh , ref'd the PR that added that `z-index` in case I am missing why it was added in the first place.

**Comment by asudoh** [comment]
Thanks @tw15egan - As I think you saw, [blame history](https://github.com/carbon-design-system/carbon/blame/v10.9.0/packages/components/src/components/accordion/_accordion.scss) points to #1671 - Would you be able to double-check if every bullets in there has no problem?

**Comment by tw15egan** [comment]
@asudoh checked the list and all still seems good 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 ✅ - Thanks @tw15egan!

**Comment by abbeyhrt** [comment]
I noticed that the issue is also resolved if the z-index is removed, would that be another way to go about this?

**Comment by tw15egan** [comment]
@abbeyhrt I think then the accordion header text is covered on hover

**Comment by abbeyhrt** [comment]
@tw15egan ah that makes sense! Thanks!

**Review by abbeyhrt — APPROVED** [review]

**Comment by abbeyhrt** [comment]
@tw15egan ah that makes sense! Thanks!

**Comment by tw15egan** [comment]
@abbeyhrt Yeah I think it has to do with the use of `before` elements to cover up the borders when they are hovered 🤷‍♂

**Pull request merged**
