### PR TITLE
feat: icons-new-march-april

### LINKED ISSUE #4053: [Icons] Checkmark and Indeterminate icon should have editable inner fill in sketch.
There is an override for a fill option for the background but not for the checkmark itself. We need to have this ability to edit the inner fill (specifically when used on a background other than white.)

-------------------------------------------------------------------------------------------------
This is an example of `32/checkmark--filled` that is working correctly and has both a `Fill` and `Inner fill` override option.
Screen Shot 2020-03-19 at 12 42 30 PM

### PR DESCRIPTION
**Pull request by conradennis**
Submitting new and updated UI icons from March and April
all updates and additions approved by BXD

115 net new icons
13 updated icons
updated categories.yml with additions
updated ui-icon-master.ai with additions and updates

Closes https://github.com/carbon-design-system/carbon/issues/4053
@laurenmrice 
[Icons] Checkmark and Indeterminate icon should have editable inner fill in sketch

#### Changelog

**New**

- 32/watson-health/threshold.svg
- 32/watson-health/cut-in-half.svg
- 32/app-connectivity.svg
- 32/bot.svg
- 32/box-plot.svg
- 32/calendar--settings.svg
- 32/campsite.svg
- 32/chart--3D.svg
- 32/chart--area.svg
- 32/chart--candlestick.svg
- 32/chart--cluster-bar.svg
- 32/chart--custom.svg
- 32/chart--error-bar--alt.svg
- 32/chart--error-bar.svg
- 32/chart--evaluation.svg
- 32/chart--high-low.svg
- 32/chart--histogram.svg
- 32/chart--multi-line.svg
- 32/chart--parallel.svg
- 32/chart--population.svg
- 32/chart--radar.svg
- 32/chart--relationship.svg
- 32/chart--ring.svg
- 32/chart--river.svg
- 32/chart--rose.svg
- 32/chart--stacked.svg
- 32/chart--t-sne.svg
- 32/chart--treemap.svg
- 32/circle-packing.svg
- 32/clean.svg
- 32/data--base--alt.svg
- 32/dew-point--filled.svg
- 32/dew-point.svg
- 32/direction--bear-right--01--filled.svg
- 32/direction--bear-right--01.svg
- 32/direction--bear-right--02--filled.svg
- 32/direction--bear-right--02.svg
- 32/direction--curve--filled.svg
- 32/direction--curve.svg
- 32/direction--merge--filled.svg
- 32/direction--merge.svg
- 32/direction--right--01--filled.svg
- 32/direction--right--01.svg
- 32/direction--right--02--filled.svg
- 32/direction--right--02.svg
- 32/direction--rotary--first-right--filled.svg
- 32/direction--rotary--first-right.svg
- 32/direction--rotary--right--filled.svg
- 32/direction--rotary--right.svg
- 32/direction--rotary--straight--filled.svg
- 32/direction--rotary--straight.svg
- 32/direction--sharp-turn--filled.svg
- 32/direction--sharp-turn.svg
- 32/direction--straight--filled.svg
- 32/direction--straight.svg
- 32/direction--straight--right--filled.svg
- 32/direction--straight--right.svg
- 32/direction--u-turn--filled.svg
- 32/direction--u-turn.svg
- 32/fire.svg
- 32/flow--connection.svg
- 32/gas-station.svg
- 32/gradient.svg
- 32/harbor.svg
- 32/heat-map--02.svg
- 32/heat-map--03.svg
- 32/heat-map.svg
- 32/helicopter.svg
- 32/hospital-bed.svg
- 32/hospital.svg
- 32/humidity--alt.svg
- 32/image--search.svg
- 32/insert--page.svg
- 32/join--inner.svg
- 32/join--left.svg
- 32/join--outer.svg
- 32/join--right.svg
- 32/mail--reply.svg
- 32/math-curve.svg
- 32/meter--alt.svg
- 32/milestone.svg
- 32/monument.svg
- 32/mountain.svg
- 32/picnic-area.svg
- 32/plug--filled.svg
- 32/plug.svg
- 32/police.svg
- 32/pressure--filled.svg
- 32/pressure.svg
- 32/qq-plot.svg
- 32/roadmap.svg
- 32/row--collapse.svg
- 32/row--expand.svg
- 32/scatter-matrix.svg
- 32/skill-level--advanced.svg
- 32/skill-level--basic.svg
- 32/skill-level--intermediate.svg
- 32/split.svg
- 32/star--review.svg
- 32/stem-leaf-plot.svg
- 32/stethoscope.svg
- 32/swim.svg
- 32/text--vertical-alignment.svg
- 32/theater.svg
- 32/touch--interaction.svg
- 32/umbrella.svg
- 32/upgrade.svg
- 32/user--multiple.svg
- 32/uv-index--filled.svg
- 32/uv-index.svg
- 32/word-cloud.svg
- 32/worship--christian.svg
- 32/worship--jewish.svg
- 32/worship--muslim.svg
- 32/worship.svg

**Changed**

- 32/arrow-shift-down.svg
- 32/checkmark.svg
- 32/checkbox--checked--filled.svg
- 32/checkbox--indeterminate--filled.svg
- 32/globe.svg
- 32/help--filled.svg
- 32/humidity.svg
- 32/information--filled.svg
- 32/location.svg
- 32/mac--shift.svg
- 32/model--reference.svg
- 32/rain-drop.svg
- 32/warning--alt--filled.svg

### CODE REVIEW

**Comment by joshblack** [comment]
Thanks for this @conradennis! Seems like `app-connectivity` may be missing from the metadata 👀

**Comment by conradennis** [comment]
@joshblack thanks for the heads up. It's included in the categories.yml file under organization > data

**Review by laurenmrice — APPROVED** [review]
looks great ! thank you for adding the inner fills to those icons too 🙌🏻

**Review by joshblack — APPROVED** [review]

**Comment by mjabbink** [comment]
@joshblack When will this release? And @conradennis assuming all these beauties have been updated in the master Ai file for download?

This is a great batch of icons!

**Comment by joshblack** [comment]
Hey @mjabbink! 👋 These should be in our 10.12 release which is targeted for May 5th. [Link to release schedule](https://github.com/carbon-design-system/carbon/wiki/Release-radar)

**Comment by mjabbink** [comment]
@joshblack That is a long period of time. What can we do to get icons and pictograms released on a more fluid release schedule?

**Comment by joshblack** [comment]
@mjabbink, unfortunately, our release schedule is time-based to help teams plan for when to pick up updates so we align to that schedule posted in the previous comment. In the past, we did releases as things got contributed and that ended up creating too much noise for teams to update reliably so we switched to this time-based schedule as a result.

**Comment by mjabbink** [comment]
is this because of the Sketch kit? Is there anything to prevent the release of the icons to the icon library pages in IDL and Carbon sites?

**Comment by joshblack** [comment]
@mjabbink the biggest reason is for the packages themselves, each release comes with a new version and while certain updates get pulled in automatically others are still a manual upgrade for teams.

For the website, I believe it'll reflect our latest version of Carbon so that folks aren't referencing that isn't available yet in code. For the IDL site, we could definitely figure out how it can consume the nightly builds for icons to try and tackle this sooner 👍

**Comment by mjabbink** [comment]
@joshblack It would be great if we can get the new icons released on IDL. Should I get the Aux squad to tackle?

**Comment by mjabbink** [comment]
@joshblack @conradennis Can we get these merged?

**Comment by mjabbink** [comment]
@joshblack I see merged but the icons are not in the libraries in IDL or Carbon sites. Can we get this live in IDL because I think you’re waiting to get these into the Sketch kit?

**Comment by joshblack** [comment]
@mjabbink I believe they're available in the latest deployed site (https://carbondesignsystem.now.sh/guidelines/icons/library) but carbondesignsystem.com hasn't been swapped over yet as we noticed that the pictograms weren't rendering (https://carbondesignsystem.now.sh/guidelines/pictograms/library)

Merged in a fix today, waiting for the slider fix (in PR) and then we're going to do a hotfix with both 👍

**Comment by mjabbink** [comment]
thanks @joshblack Not seeing them in the IDL library?

**Comment by mjabbink** [comment]
also seeing dashes show up in the naming now in any new Icons or Pictograms.
Screen Shot 2020-05-26 at 5 38 24 PM


Screen Shot 2020-05-26 at 5 36 42 PM


————

**Comment by mjabbink** [comment]
Friendly naming now showing up in the new additions.

**Comment by mjabbink** [comment]
These need to show up in the IDL Library.

**Comment by mjabbink** [comment]
These need to be in the IDL l=icon library Monday please. I cannot ask about this again.

**Comment by joshblack** [comment]
@mjabbink there may be some process confusion with this work. Contributors on this PR and this project do not work with the IDL site and do not know how it gets updated or deployed. We ship the icon packages that projects like IDL or carbon can bring in.

This specific PR was included in the v10.12 release of the packages which was released on May 14th and are available for teams to use.

**Comment by mjabbink** [comment]
@vpicone please have someone on the Aux team take care of this. We need to get the workflow sorted for icon and pictogram additions. They need to also get added to the IDL library at the same time they get added to the Carbon library

**Comment by alisonjoseph** [comment]
@vpicone @joshblack lets sync up to figure out how we can make sure icons get updated in sync on IDl/Carbon website.

**Comment by mjabbink** [comment]
@joshblack I was not clear on the process so apologize for any revealed frustration on my part. Looks like Alison and Vince will sort out the flow.

**Pull request merged**
