### PR TITLE
feat: icons-new-september

### PR DESCRIPTION
**Pull request by conradennis**
38 net new icons
4 updated icons
2 deleted logo icons for defunct sites
updated categories.yml with all additions and updates
updated ui-icon-master.ai with all additions and updates

#### Changelog

**New**
- accessibility--alt.svg
- accessibility--color--filled.svg
- accessibility--color.svg
- blockchain.svg
- charging-station.svg
- charging-station--filled.svg
- color-switch.svg
- container-software.svg
- dna.svg
- dot-mark.svg
- drop-photo.svg
- drop-photo--filled.svg
- fit-to-screen.svg
- fog.svg
- hybrid-networking.svg
- logo--instagram.svg
- logo--medium.svg
- logo--openshift.svg
- logo--vmware.svg
- logo--yelp.svg
- managed-solutions.svg
- meter.svg
- microscope.svg
- mobile--audio.svg
- omega.svg
- paragraph.svg
- percentage.svg
- percentage--filled.svg
- product.svg
- schematics.svg
- sigma.svg
- stamp.svg
- text--new-line.svg
- trophy.svg
- trophy--filled.svg
- virtual-machine.svg
- virtual-private-cloud.svg
- zoom--reset.svg

**Changed**
- enterprise.svg
- logo--snapchat.svg
- sunrise.svg
- sunset.svg

**Removed**
- logo--delicious.svg
- logo--stumbleupon.svg

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
just dropping a note about the title, can you update it according to the [commit conventions](https://github.com/carbon-design-system/carbon/blob/master/docs/developer-handbook.md#commit-conventions)?

**Comment by aledavila** [comment]
Sorry what issue is this for ?

**Comment by joshblack** [comment]
@conradennis seems like meta is missing out on some icons:

```
Error: The following icons are missing or an error has occurred:
[
  "blockchain",
  "charging-station--filled",
  "charging-station",
  "color-switch",
  "container-software",
  "dot-mark",
  "drop-photo--filled",
  "drop-photo",
  "fit-to-screen",
  "fog",
  "hybrid-networking",
  "managed-solutions",
  "meter",
  "microscope",
  "omega",
  "paragraph",
  "percentage--filled",
  "percentage",
  "product",
  "schematics",
  "sigma",
  "stamp",
  "trophy--filled",
  "trophy",
  "virtual-machine",
  "virtual-private-cloud",
  "dna"
]
```

**Review by joshblack — CHANGES_REQUESTED** [review]
Left a note above!

**Comment by joshblack** [comment]
@aledavila Conrad is the one who creates icons for IDL 👍

**Comment by aledavila** [comment]
@joshblack thanks! I wasn't sure about the context of this

**Comment by conradennis** [comment]
@joshblack I have a few questions:
1. is there a reason only some of the icons aren't showing up in meta.yml?
2. should i manually add these ones to the file
3. do you have a system for editing/adding items to the metadata file

Once i update the file I'm assuming I should add it to this PR

**Comment by chrisconnors-ibm** [comment]
@joshblack what provokes the autogenerated portions of `metadata.yml` for new icons?

**Comment by joshblack** [comment]
@chrisconnors-ibm manual process for now 😬 hopefully with the icons project we can make a GitHub Action to automate it

**Comment by chrisconnors-ibm** [comment]
> @chrisconnors-ibm manual process for now 😬 hopefully with the icons project we can make a GitHub Action to automate it

can someone run it to address the concerns @conradennis raised above :)

**Comment by joshblack** [comment]
@chrisconnors-ibm should be done in https://github.com/carbon-design-system/carbon/pull/4210/commits/3e48022ab9043640bcfbd037e60e58ede3bab174

**Comment by chrisconnors-ibm** [comment]
> @joshblack I have a few questions:
> 
> 1. is there a reason only some of the icons aren't showing up in meta.yml?
> 2. should i manually add these ones to the file
> 3. do you have a system for editing/adding items to the metadata file
> 
> Once i update the file I'm assuming I should add it to this PR

@conradennis are these still issues? the chore above @ [3e48022](https://github.com/carbon-design-system/carbon/commit/3e48022ab9043640bcfbd037e60e58ede3bab174) should have resolved.

**Comment by conradennis** [comment]
@chrisconnors-ibm nope, Josh took care of it

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
@laurenmrice this link should work for previewing: https://deploy-preview-4210--carbon-elements.netlify.com/icons/examples/preview/

**Comment by laurenmrice** [comment]
@conradennis all looks good except I can't find dna.svg. Did you mean the watson-health/dna?
Screen Shot 2019-10-16 at 10 34 19 AM

**Comment by conradennis** [comment]
@laurenmrice yup, my mistake!

**Review by laurenmrice — APPROVED** [review]
looks good to me 👍

**Review by abbeyhrt — APPROVED** [review]

**Pull request merged**
