### PR TITLE
fix(list): fix markers for nested list items

### LINKED ISSUE #2282: [Carbon 10: List] Nested item issues
## Detailed description
There are multiple issues with the List component specifically with nested items

> Describe in detail the issue you're having.

1. Nesting an unordered list in an ordered list (or vise versa) does not display the correct list type
1. Beyond the 2nd level of nested lists in ordered lists do not reset the counter
1. (not sure if this is intended or not) when the list item wraps to a new line it is not indented to align with the text above it (it's aligned with the item marker)

> Is this issue related to a specific component?

List

> What did you expect to happen? What happened instead? What would you like to see changed?

1. I should be able to mix and match list types when nesting lists and the user would understand what type of list it is
1. The marker for nested lists would reset the counter/be denoted differently
1. The text aligns with the text when it wraps instead of the marker

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10.0.0

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Watson Health Pattern & Asset Library (PAL)

## Steps to reproduce the issue

1. Use the HTML from the screen shot below
1. view the issues

## Additional information

Unordered list test
Screen Shot 2019-04-10 at 11 17 56 AM

Ordered list test
Screen Shot 2019-04-10 at 11 18 06 AM

### PR DESCRIPTION
**Pull request by vincentsnagg**
Fixes #2282 

This PR:
- Fixes the markers on nested lists of different types to be consistent with the semantic tag (`ul`, `ol`)
- Makes wrapped text align to the rest of the text in the list item, rather than the marker.

I didn't want to write anything that would force a user to apply multiple classes to an list element to get the intended effect (e.g., `.bx--list--nested.bx--list--ordered`), and so I used the type selector in combination with the nested class  (e.g., `ol.bx--list--nested`)... but I'm open to feedback on this approach!

Different List Types within Ordered List
Screen Shot 2019-06-06 at 7 26 36 AM

Different List Types within Unordered List
Screen Shot 2019-06-06 at 7 27 02 AM

#### Changelog

**Changed**
- Fixed markers on nested lists
- Fixed alignment of wrapped text

#### Testing / Reviewing

Testing should make sure:
- Default list behavior works as expected
- Nested ordered lists are reset (start from `a`)
- Alignment of wrapping text looks good

### CODE REVIEW

**Comment by asudoh** [comment]
@vincentsnagg Could you add a markup that demonstrates your enhancement? Thanks!

**Comment by vincentsnagg** [comment]
@asudoh It should now be the third demo under List.. let me know if this helps. thanks!

**Review by elizabethsjudd — APPROVED** [review]
@vincentsnagg Everything looks great!  Thanks for helping with this. I tested this in Firefox, Safari, and Chrome and everything looks good.  (I'll test IE11 and Edge tomorrow when I have my windows laptop available).

@carbon-design-system/design I was curious if this was the expected result when we have multiple nested of the same type of list where once you reach the second level all levels use the same marker

Screen Shot 2019-06-06 at 9 46 49 AM

**Comment by aagonzales** [comment]
Shouldn't the `un-order` list not include the letters. Letters imply an ordering structure. I would use a different kind of glyph maybe an open dot?
image

**Comment by aagonzales** [comment]
(if you saw my previous comment I jumped the gun and started review the code instead of reading the specific question, whoops)

An ordered list should always have ordered indicators, like numbers or letters. And oppositely the unordered list should always us abstracted (dots, dashes) indicators. So this one is more correct than what's previewing in code.

image

However, it would be nice if the 3rd and 4th layer could have a unique indicator or at least alternate between numbers/letters and dots/dashes. Do you know what word processors normally do for the 3rd and 4th layers? I think we should probably do whatever is more industry standard. The original designs never went past 2 layers so we had no "expect results" off the cuff.

**Comment by vincentsnagg** [comment]
@aagonzales Thanks for taking a look! I could've been clearer in my intro to this PR. One of the primary goals of this PR to fix issue ( #2282 ) which deals with (the valid behavior of) *mixing ordered and unordered lists (and vice-versa)*. In Liz's screenshots in #2282,  any nested list takes on the parent markers regardless of the tag `ul` or `ol`.  This is not the expected behavior of default HTML and the current Carbon code overrides that. The proposed code shows two lists that have appropriate markers for mixed, nested lists.

What @elizabethsjudd is asking about is a secondary point of alignment that might be fixed in the future, which is that (in Carbon's current code and in the proposed code) when you have nested lists (of the same type) beyond the 2nd level, they all use the same marker (but in the proposed code, they are appropriate to either ordered or unordered lists). Perhaps it makes the most sense right now to align on **what those markers would be for the 3rd level and beyond** and make a new story in Carbon to spec out what exactly the behavior is (alternating between 2 markers, 3 or more different markers, etc.), to be addressed at some point in the future. @elizabethsjudd Let me know if this aligns with your thinking here

@aagonzales please let me know if you'd agree with this direction, and perhaps what that "3rd and beyond markers" should be (for unordered and ordered) for now!

**Comment by aagonzales** [comment]
Your team should be proposing what you think is the desired/ideal solution for behavior. Is this what your team wants it to be? 

image

**Comment by elizabethsjudd** [comment]
@aagonzales What Vincent has in the proposed code is the expected behavior in the fact that the list type (ordered vs unordered) is now visually accurate to what is in the code which was the bug logged in #2282. 

I don't believe either team (Carbon or WH) have specs for the markers when used at the 3rd level and beyond. I feel that it can be tracked in a separate issue (sorry that wasn't clear), I just wanted to point this out so the teams were aware of it.

**Comment by vincentsnagg** [comment]
@asudoh @aagonzales Following Liz's comment above, it seems we are aligned regarding our team's recommendation. Do let me know what the next steps steps are. Thanks!

**Comment by asudoh** [comment]
The code LGTM, will move forward once we get a green light from design.

**Comment by shixiedesign** [comment]
I'm not very familiar with the issue but Anna will be back tomorrow and should be able to review. Sorry for the hold up.

**Comment by shixiedesign** [comment]
Ha my bad - just realized this is actually an issue i created...it makes sense now and Vincent's changes looked good to me!

**Review by shixiedesign — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Comment by lovemecomputer** [comment]
thanks!! merging

**Comment by lovemecomputer** [comment]
oh woops! more changes from master and @jnm2377 beat me to it hehe~

**Review by lovemecomputer — APPROVED** [review]

**Pull request merged**
