### PR TITLE
mv /*/app-switcher.svg to /*/switcher.svg

### PR DESCRIPTION
**Pull request by chrisconnors-ibm**
#### Changelog

**Changed**

- renames /*/app-switcher.svg to /*/switcher.svg, to clarify its purpose and reduce the impression that it's only for a specific case (app switching)

cc @designertyler @aagonzales @joshblack

### CODE REVIEW

**Review by designertyler — APPROVED** [review]

**Review by aagonzales — APPROVED** [review]

**Comment by cal-smith** [comment]
Question: would this result in a breaking change for consumers of the `app-switcher` icon components? Admittedly I'm not deeply familiar with the build process, so it's possible there's already a mechanism to handle renames.

**Comment by joshblack** [comment]
@cal-smith yeah it would be, but given we haven't publicized these icon resources we were going to PR in the updates for teams who may be using it.

**Comment by cal-smith** [comment]
If you have a comprehensive list that would definitely help there. I'd still make the argument that since `10.3.0` is published as a "latest" release (i.e. it's fully out of the `0.x` pre-release mode) the appropriate solution would be to keep both paths and just deprecate `app-switcher`.

Granted, I'd be surprised if this particular icon caused a serious breakage, but who knows.

**Review by joshblack — CHANGES_REQUESTED** [review]
We're going to need to add in an alias to support what @cal-smith was calling out, I can commit this in a bit 👍

**Review by joshblack — APPROVED** [review]

**Pull request merged**
