### PR TITLE
fix(treeview): increase hit area of twistie to 24px

### LINKED ISSUE #12769: [a11y]: Treeview expand/collapse control hit area
### Package

@carbon/react

### Browser

Chrome

### Operating System

_No response_

### Package version

https://carbon-components-react.netlify.app/?path=/story/components-treeview--default

### React version

storybook

### Automated testing tool and ruleset

n/a

### Assistive technology

n/a

### Increase hit area of expand/collapse
The hit area of the expand/collapse control ("twistee") is a small 16x18 pixels area that falls within the larger hit area for selecting the node (which spans the width of the tree).
image
image
The most obvious reason to increase the size of the twistee's hit area is to provide sufficient affordance.
However, a second issue is that since the twistees can be indented (in the different levels of the tree) it means that users wishing to expanda multiple sections are forced to navigate not just vertically, but also horizontally in order to hit the differently oriented targets.
If the whole area to the left of the twistee was included in its hit area, then users would be able to click more accurately and consistently.
Besides increasing the horizontal hit area, consideration should also be given to expanding the hit area to include the height of the span. There is no good reason not to also take the vertical space to ensure it is a full 24 pixels high.

### WCAG 2.1 Violation

_No response_

### Reproduction/example

https://carbon-components-react.netlify.app/?path=/story/components-treeview--default

### Steps to reproduce

Navigate to https://carbon-components-react.netlify.app/?path=/story/components-treeview--default

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

```[tasklist]
### Tasks
- [ ] https://github.com/carbon-design-system/carbon/issues/12800
- [ ] https://github.com/carbon-design-system/carbon/issues/13114
```

### LINKED ISSUE #13114: TreeView: Increase horizontal and vertical hit area of twistee
The TreeView needs to be updated - the twistee hit area/padding needs to be updated to match the new spec delivered in #12800

-----
### 8px padding between icons

Design

Specs

### Final decision
- Going with 8px padding between icons. 
  - *Note: reopen issue if there are changes based on the [a11y touch target](https://github.com/carbon-design-system/carbon/issues/12769) solution.

Frame 2

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #13114, Closes #12769

#### Changelog

**Changed**

- Update styles to increase twistie hit area to 24px x 24px

#### Testing / Reviewing

Visually Treeview should look identical to live storybook, but confirm that hit area for twistie arrow is now 24px 
https://deploy-preview-13354--carbon-components-react.netlify.app/?path=/story/components-treeview--default

Screenshot 2023-03-16 at 9 41 34 AM

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by alisonjoseph** [comment]
@tw15egan keyboard is working for me, for Treeview keyboard controls its left/right arrrows to open/close 
https://www.w3.org/WAI/ARIA/apg/patterns/treeview/

**Comment by tw15egan** [comment]
til today i learned - 87gYYkSC09QetBBHge

**Review by tw15egan — APPROVED** [review]

**Review by tay1orjones — APPROVED** [review]
Looks great!

**Pull request merged**
