### PR TITLE
17028 filterable multi select performance fix

### LINKED ISSUE #17028: [Bug]: Performance Issue with Filterable Multiselect in Carbon React
### Package

@carbon/react

### Browser

_No response_

### Package version

1.60.2

### React version

16.14.0

### Description

After switching from carbon v10 to carbon v11 we noticed a significant performance decrease on a page with multiple filterable multi selects that contain large amounts of items (in the 1000s). We noticed that in carbon v10 you sort and filter only if the dropdown is open but in v11 you are sorting and filtering on every re-render since it is done in the functional component's body. If i have 1000 items in the dropdown you will be sorting all of them every re-render without a filter.

Carbon v11 (sort and filter on every re-render)
[https://github.com/carbon-design-system/carbon/blob/351525d94b31a35760ab7d7e57747c[…]ages/react/src/components/MultiSelect/FilterableMultiSelect.tsx](https://github.com/carbon-design-system/carbon/blob/351525d94b31a35760ab7d7e57747c2888ebb221/packages/react/src/components/MultiSelect/FilterableMultiSelect.tsx#L400)

Carbon v10 (sort and filter only if the dropdown is open)
[https://github.com/carbon-design-system/carbon/blob/25d31a6cc11ee3a252cb6ae2715ada2da5ed5b38/packages/react/src/components/MultiSelect/FilterableMultiSelect.js#L592](https://github.com/carbon-design-system/carbon/blob/25d31a6cc11ee3a252cb6ae2715ada2da5ed5b38/packages/react/src/components/MultiSelect/FilterableMultiSelect.js#L592)

**Note**: This is a separate issue from the performance of searching on filterable multi selects with hundreds of items.

**Temporary Fix**: If you are experiencing this issue you can simply add the following prop to you filterable multi select
```js
<FilterableMultiSelect
sortItems={(items) => items}
/>
```
This will essentially disable the filtering of the multi select items which you could perform yourself separately.

### Reproduction/example

https://stackblitz.com/edit/github-dcqkrj?file=src%2FApp.jsx

### Steps to reproduce

See stack blitz:

If you click the increment counter you will notice it takes a long time to re-render. If you remove sorting by uncommenting out the sort prop you will see it properly re-render.

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by lharrison13**
Closes #17028

fixed performance bug in filterable multi select by memoizing sorted items

#### Changelog

**Changed**

- memoized sorted items in filterable multi select component
- added recommendation to itemToString and compareItems prop docs

#### Testing / Reviewing

- [ ] ensure multi select component only recalculates `sortedItems` when one of the dependencies in useMemo changes

### CODE REVIEW

**Comment by lharrison13** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by Gururajj77** [comment]
Hi @lharrison13 , could you fix the tests so that CI can pass?

**Comment by lharrison13** [comment]
@Gururajj77 Thats strange nothing i touched is imported in the slider component, its also passing on my machine. My fork is also synced with the upstream.


Screenshot 2024-07-29 at 9 58 03 AM
Screenshot 2024-07-29 at 9 58 27 AM
Screenshot 2024-07-29 at 10 05 44 AM

**Comment by lharrison13** [comment]
@riddhybansal thanks for the merge!

**Review by tay1orjones — APPROVED** [review]

**Review by 2nikhiltom — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
