### PR TITLE
fix(pagination): input wrapper alignment closes #4733

### LINKED ISSUE #4733: (pagination) select dropdowns are not aligned
The select dropdowns are not inside the pagination container and are floating.

### PR DESCRIPTION
**Pull request by vpicone**
Regression was likely due to IE fixes, test in all browsers

### CODE REVIEW

**Review by joshblack — APPROVED** [review]
Ugh my VM for IE11 is expired so will need to refresh. Tested though in latest:

- [x] Chrome
- [x] Safari
- [x] Firefox
- [x] Edge for Mac

**Comment by vpicone** [comment]
@joshblack here's ie11:

ie11

**Comment by joshblack** [comment]
@vpicone lol love the browser version info in the screenshot

**Review by abbeyhrt — APPROVED** [review]
I also don't have access to IE11 but checked in the same browsers and the IE11 screenshot and it looks good to me! Would we need design approval on something like this?

**Comment by joshblack** [comment]
Just verified with IE11 👍

**Pull request merged**
