### PR TITLE
fix(checkbox): Checkbox & Radio button position

### LINKED ISSUE #4154: Checkbox & Radio button: incorrect padding
Checkbox and radio button `padding` in **vertical groups** don't match. React and Vanilla both have this problem.

## As-is
image

## To-be
image

### PR DESCRIPTION
**Pull request by AlexanderLyon**
Closes #4154

This fixes some positioning regarding grouped radio buttons and checkboxes. The margin between the `<legend>` and group is now `8px`, as well as the margin between individual group elements.

#### Changelog

**Changed**

- `_radio-button.scss`
- `_checkbox.scss`

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Hi 👋 thank you for jumping in! Seems that the height of checkbox with the margin is 24 pixels with your fix, whereas the spec request for 28 pixels (20 pixels check box, 8 pixels margin). I saw it with the replacing `radio-button.hbs` with:

```html
<div style="display:flex">
  (Original `radio-button.hbs` content)
  (The first `<fieldset>` in `checkbox.hbs`)
</div>
```

**Comment by AlexanderLyon** [comment]
Ahh I see, thanks @asudoh! I can make the fix later today! 👍🏼

**Comment by dakahn** [comment]
@carbon-design-system/design

**Comment by chrisconnors-ibm** [comment]
Please remember to request design reviews from the initial issue author (#4154, @aagonzales ) and one other designer. Tagging @carbon-design-system/design is less directed and too easy to think "someone else will get it".

The related issue author has the context to quickly determine "delivered as designed", and the second design approval makes sure that familiarity doesn't cause anyone to miss anything.

Thanks @carbon-design-system/developers !

**Review by aagonzales — APPROVED** [review]
Awesome! Looks perfect, thanks for fixing!


image
Overlay to show alignment is correct.

**Review by laurenmrice — APPROVED** [review]
🎉

**Comment by AlexanderLyon** [comment]
I'm glad I could help! 😁

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @AlexanderLyon!

**Review by emyarod — COMMENTED** [review]
looks good to me, just want to double check if there are any tokens we might want to use in place of the px values. if none of the [`carbon--spacing`](https://github.com/carbon-design-system/carbon/blob/master/packages/components/src/globals/scss/vendor/@carbon/layout/scss/_spacing.scss) tokens work should we use the `carbon--mini-units` function?

**Review by aledavila — APPROVED** [review]
LGTM after addressing andrew's comment above ^

**Review by dakahn — APPROVED** [review]

**Comment by AlexanderLyon** [comment]
@emyarod I've made the fixes you pointed out - let me know if I should refactor the remaining pixel values in those two stylesheets to use `carbon--spacing` and `carbon--mini-units` in more locations, and maybe I can open a separate PR for that!

**Pull request merged**
