### PR TITLE
fix: friendly name for 3D components

### LINKED ISSUE #3690: [icons]: 3D icons use incorrect casing/format for family name
**current:** `friendly_name: 3 d curve manual`
**expected:** `friendly_name: 3D curve manual` or `friendly_name: 3-D curve manual`

https://www.lexico.com/en/definition/3d

### PR DESCRIPTION
**Pull request by vpicone**
Closes #3690

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Maybe we should use `docs` since it's a metadata change?

```git
docs(icons): update friendly names for 3D components
```

Or could scope as:

```git
fix(icons): update friendly names for 3D components
```

**Comment by vpicone** [comment]
@joshblack i wasn’t sure if there are modules that use friendly name programmatically like I am at the moment to get the component/module name.

**Comment by joshblack** [comment]
I think you're good to go either way 👍

**Comment by vpicone** [comment]
But that seems more appropriate either way

**Review by dakahn — APPROVED** [review]

**Comment by vpicone** [comment]
@joshblack ah I see, gotta remember to scope my initial commit. Wondering if we should force a scope in fix/feat commit messages 🤔

**Pull request merged**
