### PR TITLE
chore(components): rename --experimental mix-ins

### PR DESCRIPTION
**Pull request by asudoh**
When we release next version of Carbon, code in `componentname-experimental` will be the latest, stable code. Which means `componentname-experimental` no longer makes sense given it's no longer "experimental". This change is for renaming those to `componentname-x` so we don't have to go through big rename effort right before releasing next version of Carbon.

#### Changelog

**Changed**

- `componentname-experimental` mix-ins to `componentname-x`.

#### Testing / Reviewing

Testing should make sure no component is broken.

### CODE REVIEW

**Review by joshblack — COMMENTED** [review]
Was thinking that the experimental name would exist up till release, and then we rename them from experimental to the name of the component. Do we need to tie them specifically to `X` after the release? Or is this to prevent breaking changes to the checkbox mixin?

**Comment by asudoh** [comment]
Hi @joshblack thank you for giving this a thought. This change is for avoiding the effort of renaming (that you mentioned) right before we release next Carbon. The goal is making next release of Carbon as simple as flipping the default feature flag values.

**Review by alisonjoseph — APPROVED** [review]
This makes sense to me, thanks Akira! 

@joshblack I think it makes sense to update the name now vs. having to go back in the future and update everything.

**Review by aledavila — APPROVED** [review]
LGTM thanks

**Review by joshblack — CHANGES_REQUESTED** [review]
I think it would be safest if we kept that experimental label up until these components are verified. This is due to the fact that all of the components that are being introduced could be changed/updated.

The experimental label will also be used for them on things like component status pages, iirc. This change seems to create confusion as to what these mixins actually are, as they are not necessarily what will be in Carbon X but instead are experimental components that need to be verified/tested.

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
removing approval until discussion is finalized 😄 
https://github.ibm.com/carbon/issues/issues/1000#issuecomment-7639226

**Comment by asudoh** [comment]
Closing for now as the team wants to defer this discussion for some weeks. Will reopen this after then.

**Pull request closed without merging**
