### PR TITLE
fix: null child crashes RadioButtonGroup (#16655)

### LINKED ISSUE #16655: [Bug]: RadioButtonGroup crashes when passed `null` or `undefined` as child
### Package

@carbon/react

### Browser

Chrome

### Package version

v11.58.1

### React version

v1.58.1

### Description

When I pass a null child to a RadioButtonGroup, it crashes. This is because of [this line](https://github.com/carbon-design-system/carbon/blob/6269fa19f0ce2930b21a2fda05974a597126ec6b/packages/react/src/components/RadioButtonGroup/RadioButtonGroup.tsx#L170): 

```
        const { value } = (radioButton as ReactElement)?.props ?? undefined;
```

which attempts to destructure `undefined`

### Reproduction/example

https://stackblitz.com/edit/github-drap92?file=src%2FApp.jsx

### Steps to reproduce

```
    <div>
      hi
      <RadioButtonGroup name="foo">
        <RadioButton labelText="hey" />
        {null}
      </RadioButtonGroup>
    </div>
```

### Suggested Severity

Severity 3 = User can complete task, and/or has a workaround within the user experience of a given component.

### Application/PAL

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by brandones**
Closes #16655 

Passing `null` as a child of a `RadioButtonGroup` would cause a crash.

#### Changelog

**Changed**

This code will no longer crash:

```
      <RadioButtonGroup name="foo">
        <RadioButton labelText="hey" />
        {null}
      </RadioButtonGroup>
```

#### Testing / Reviewing

Try the above code. I included a test.

### CODE REVIEW

**Comment by brandones** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by 2nikhiltom — COMMENTED** [review]
Hey @brandones .
Thanks for raising this bug and it's fix.

Just trying to understand the use case of below [code](https://stackblitz.com/edit/github-drap92?file=src%2FApp.jsx) 
 ```
<div>
      hi
      <RadioButtonGroup name="foo">
        <RadioButton labelText="hey" />
        {null}
      </RadioButtonGroup>
    </div>

```

**Comment by brandones** [comment]
@2nikhiltom This kind of thing comes up often when options are not hard-coded.

```
const { blackIsAllowed } = useConfig();

<div>
     <RadioButtonGroup name="colors">
       <RadioButton labelText="red" value="red" />
       <RadioButton labelText="blue" value="blue" />
       { blackIsAllowed ? <RadioButton labelText="black" value="black" /> : null }
     </RadioButtonGroup>
</div>
```

Whether you use `null`, `undefined`, or `false` in the `blackIsAllowed` line, you will get a TypeError.

Also your library simply should not crash with a TypeError on what React considers well-structured input :)

**Comment by 2nikhiltom** [comment]
Hey @brandones ! This looks great, could you resolve conflicts in the branch?

**Comment by brandones** [comment]
Got swooped by @cuppajoey , https://github.com/carbon-design-system/carbon/commit/e582548c949a56fba560f19a0c4cad46e63ce3a1 . So here's a test if you want it :)

**Review by guidari — APPROVED** [review]

**Review by 2nikhiltom — APPROVED** [review]

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
