### PR TITLE
feat(components): introduce brand prefix SCSS variable

### LINKED ISSUE #402: Use cx- prefix instead of bx-
Now that the `Bluemix` brand is deprecated, could you consider replacing the `bx` prefix with something like `cx` (Carbon uX) or `cc` (Carbon Components) or `cd` (Carbon Design)?

### PR DESCRIPTION
**Pull request by asudoh**
## Overview

This change introduces `$brand-prefix` SCSS variable (default `bx`) and makes all class names interpolated with such variable.

This change also introduces `brandPrefix` property in `CarbonComponents.settings` JS object, so that our JS code can refer to the brandPrefix for manging DOM, etc.

Fixes #402.

### Added

* `$brand-prefix` SCSS variable
* `brandPrefix` property in `CarbonComponents.settings`

### Changed

* Made all hard-coded CSS selectors/classes component options
* `$bx--standard-easing`, etc. SCSS variables to `$carbon--standard-easing`, etc.

## Testing / Reviewing

Testing should make sure no component is broken.

### CODE REVIEW

**Comment by marijohannessen** [comment]
Are you a mind reader? Bethany and I were planning for V9 yesterday and custom prefixes was a big item on our list! I think we're going to default to something else than `bx` once we release V9 though, but I'm fine with adding this in stepwise. I'll review by EOD, thank you so much!! 👏

**Comment by tw15egan** [comment]
Awesome! 🎉

**Comment by asudoh** [comment]
@marijohannessen @tw15egan Thank you for planning for review! 🙇 As I was thinking of what would enable wider team to use Carbon, the custom prefix got into the one of the top slots as you and Bethany did!

**Comment by marijohannessen** [comment]
The PR overall looks good, I just want to double check with the team about what we want to name some of the variables. I'll bring this up during our sprint retro/planning this week, and leaving this PR open until then!

**Comment by asudoh** [comment]
Sounds good - Thanks @marijohannessen!

**Review by joshblack — APPROVED** [review]
Seems great! Only comment/question I have is if we want to shorten the prefix for development, while still surfacing it as `$brand-prefix` for others.

e.g., when writing a selector as a developer we could shorten it to:

```sass
.#{$bp}--accordion {
  // ...
}
```

**Comment by asudoh** [comment]
@joshblack Tried that - Curious what people think: https://github.com/carbon-design-system/carbon-components/pull/492/commits/b0452e1ca965c5a76cf26b26e5f5775fab698c7c

**Comment by joshblack** [comment]
Thanks for previewing the changes, @asudoh! I'm definitely a fan, but am 100% not tied to it. I'm down for either approach at the end of the day 😄

**Comment by marijohannessen** [comment]
My worry with `bp` is that it's not immediately clear what `bp` stands for. Especially since people are used to seeing `bx` - I feel like the naming might be too similar. Could it be replaced with just `prefix`? Also tagging the rest of the dev team to get their input, @tw15egan and @alisonjoseph 🙂

For the motion naming, I'm fine with using `carbon` as a prefix for now because we want to re-visit this before V9 as it's a bit inconsistent right now (seeing as we have variables like `$transition--expansion` and then variables with the prefix like `$carbon--ease-in`). So until we refactor this, I'm fine with updating it to `carbon`!

I was also wondering - would changing it from `bx--ease-in` to `carbon--ease-in` result in a breaking change? Or does it not matter since it's all the same in the compiled CSS anyway?

**Comment by alisonjoseph** [comment]
I agree with @marijohannessen that `bp` isn't immediately clear what it is, and also very similar to `bx`. I think using `prefix` would work great. 

As far as changing variable names, do we have teams using our variables in their own custom sass files? That's the only way I could see it being a breaking change.

**Comment by asudoh** [comment]
Thank you everyone for giving it a thought! `prefix` sounds OK to me. An alternative idea I have is `brand` - Given it’s less general and thus less risky of naming conflicts/confusions in future.

@marijohannessen Good question on `$carbon--ease-in`! The `_vars.scss` code has [backward-compatiblity layer](https://github.com/carbon-design-system/carbon-components/pull/492/files#diff-92c59311aace9ac066f9bc10144ac4bdR15) which makes this change non-breaking.

**Comment by asudoh** [comment]
Seems that `prefix` is winning - Made a change as such.

**Review by marijohannessen — APPROVED** [review]
This is good to go! Excited about this! 👍

**Pull request merged**
