### PR TITLE
Removed highlight from Dropdown components

### LINKED ISSUE #16512: [Dropdown: Combobox & Multiselect]: Fixing focus state dev implementation
### The problem

1. After sharing at the CAG call, we will not be putting focus on the first option in the open menu in Figma if nothing is selected.
2. Check whether the focus state is overlapping correctly when both the parent and child items have focus states. The overlapping focus stroke should be 2 px.

### The solution

1. Removing the focus state from: 
   - [ ] Combobox
   - [ ] Multi-select
   - [ ] Filterable multi-select

### Examples

Ref: [Figma kit](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=14032-308516&t=2y14z0Ng5R7t6dLh-4)

### Application/PAL

_No response_

### Business priority

None

### Available extra resources

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by guidari**
Closes #16512

Removed the selection from first items after the Dropdown is open.
Changed tests to match the expected behaivour.

#### Testing / Reviewing

- Test if `Combobox`, `MultiSelect` and `FilterableMultiselect` are not focusing on the first element.

### CODE REVIEW

**Review by preetibansalui — CHANGES_REQUESTED** [review]
Hey @guidari, looks like its not working for filterable multiselect, Please check the attached video.


https://github.com/carbon-design-system/carbon/assets/146315451/cadef943-0578-4e66-a7da-5f35afe79e0c

**Comment by guidari** [comment]
@preetibansalui Fixed the arrow click

**Comment by preetibansalui** [comment]
Thanks @guidari for the changes, Its looking perfect. Just want to confirm one minor thing that I notice in multiselect. If we select something in multiselect and reopen this, It won't have any item as highlighted while for filterable, dropdown and combobox on reopen they have highlighted options. @Kritvi-bhatia17 Can you please confirm if this behaviour is correct? 
Attaching video for reference.

https://github.com/carbon-design-system/carbon/assets/146315451/82deeded-e3db-46b6-be4e-ab71b73acbc3

**Review by tay1orjones — APPROVED** [review]
@preetibansalui that's a configurable option through `selectionFeedback`, so I think this is okay

**Review by 2nikhiltom — APPROVED** [review]
Looks good ! 🔥

**Review by Kritvi-bhatia17 — CHANGES_REQUESTED** [review]
Hi @guidari, nice work just a few comments: 

1. I might not have clearly mentioned this in the issue, but when there is no option selected in the combobox, the parent option should have a focus border of 2px. ([figma link](https://www.figma.com/design/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?node-id=14032-291116&t=usoSlpctFqZ6Ux1i-4))
     > image

2. I am unable to verify/crosscheck whether this overlapping focus border is 1px or 2px. Please cross-check. Please verify the same for the multi-select as well.
     > Screenshot 2024-07-01 at 5 12 39 PM

3. The focus border is supposed to be removed from the child option when it is not selected. In this case, as one option is already selected, the focus border should also appear on the child option (the way it is currently now), similar to what you have done for the filterable-multiselect. ([example link](https://react.carbondesignsystem.com/?path=/story/components-multiselect--playground))
     > Screenshot 2024-07-01 at 5 16 16 PM

4. In the filterable-multiselect, I am unsure whether the last selected option interacted with should have the focus state or if it should be the first option that appears when opening the dropdown. For now, let's continue with the current interaction as seen in the [current storybook](https://react.carbondesignsystem.com/?path=/story/components-multiselect--filterable).

Please cross-check these minor points with the fluid states as well.

Let me know if you have any doubts. Thank you, Gui! 🔥

**Comment by Kritvi-bhatia17** [comment]
Hi Gui!!

> 3\. The focus border is supposed to be removed from the child option when it is not selected. In this case, as one option is already selected, the focus border should also appear on the child option (the way it is currently now), similar to what you have done for the filterable-multiselect. ([example link](https://react.carbondesignsystem.com/?path=/story/components-multiselect--playground))
> 
>   Screenshot 2024-07-01 at 5 16 16 PM
1. Can you please reconfirm if this is resolved now? I am unable to see it on my end. The same issue is occurring for fluid multi-select.

     Screenshot 2024-07-13 at 1 38 22 PM

--- 
`Fluids states`

2. 'When no option is selected in the combobox, the parent option should have a 2px focus border.' This same rule should be applied to the fluid combo box as well.

   Screenshot 2024-07-13 at 1 32 35 PM

**Review by Kritvi-bhatia17 — CHANGES_REQUESTED** [review]
Hi Gui!! Thanks for fixing those minor points 🙌🏻.
Can you please look at the following points:

1. Can you please reconfirm if this is resolved now? I am unable to see it on my end. The same issue is occurring for fluid multi-select.

   image

   > 3\. The focus border is supposed to be removed from the child option when it is not selected. In this case, as one option is already selected, the focus border should also appear on the child option (the way it is currently now), similar to what you have done for the filterable-multiselect. ([example link](https://react.carbondesignsystem.com/?path=/story/components-multiselect--playground))
   >  
   >  Screenshot 2024-07-01 at 5 16 16 PM

--- 

2. 'When no option is selected in the combobox, the parent option should have a 2px focus border.' This same rule should be applied to the fluid combo box as well.

   Screenshot 2024-07-13 at 1 32 35 PM

--- 

3. In both multi-select and filterable multi-select, when I select an option, click the cross, and then open the dropdown again, the focus state reappears. I'm not sure why this is happening. Can you please check this?

https://github.com/user-attachments/assets/2064ac2f-f01b-4fc9-8bf6-21b2e49f4cc7

---

**Comment by Kritvi-bhatia17** [comment]
Although this is not related to this issue, when I click on multi-select, the component appears in the middle instead of the top left like all other components. Any idea why this bug is occurring?

Screenshot 2024-07-13 at 2 09 50 PM

**Comment by guidari** [comment]
Fixed the issues @Kritvi-bhatia17 

> Although this is not related to this issue, when I click on multi-select, the component appears in the middle instead of the top left like all other components. Any idea why this bug is occurring?

It is only for testing purpouse. So the user can test the Floating UI when the `autoAlign` is set to true

**Review by Kritvi-bhatia17 — APPROVED** [review]
Amazing, Gui! It is working perfectly fine now. 🔥
Thanks for patiently working on it. 🙌🏻

**Comment by thyhmdo** [comment]
Sorry, I came late to this issue. Just wanted to ask if this is correct for the Invalid and Warning states. 

image

**Review by preetibansalui — APPROVED** [review]
LGTM. Thanks for the changes :rocket:

**Pull request merged**
