### PR TITLE
fix(ListBox): a11y - move filter tag as sibling of menu trigger, esc key improvements

### LINKED ISSUE #12596: [a11y]: Dropdown MultiSelect button should have role="combobox" instead of button
### Package

carbon-components-react

### Browser

Chrome

### Operating System

Windows

### Package version

7.59.3 (from @console/pal)

### React version

17.0.2

### Automated testing tool and ruleset

IBM Equal Access Accessibility Checker - latest version

### Assistive technology

_No response_

### Description

The buttons inside the MultiSelect causes issue because parent is a `button` instead of a `role="combobox"`

### WCAG 2.1 Violation

IBM 4.1.2 Name, Role, Value

### Reproduction/example

https://v10.carbondesignsystem.com/components/dropdown/code

### Steps to reproduce

1. Choose MultiSelect
2. Select an item
3. Close the input
4. Run accessibility checker

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/12596

Refactors `MultiSelect` so that the Filter Tag is an adjacent element to the trigger `button`, rather than a descendant of the `button`. Previously, this was causing issues as an element with `role="button"` cannot be a descendant of a `button` element, causing an a11y violation.

This PR also includes changes to the `esc` behavior for the `MultiSelect` / `ComboBox` variants. The `x` to clear input for `FilterableMultiSelect` and the `x` for the tag selection are not accessed by tabbing. Instead, the actions a user could perform with these have been rolled into the input itself. For example:

**Multiselect**:
Open and select an item with the keyboard. One `esc` press should close the menu. The second `esc` press should clear the selection.

**FilterableMultiselect**:
Open and select an item with the keyboard. One `esc` press should close the menu AND **clear** the input. The second `esc` press should clear the selection.

**ComboBox**:
Open and select an item with the keyboard. One `esc` press should close the menu AND **retain** the input. The second `esc` press should clear the input.

#### Changelog

**New**
- A wrapper (`cds--list-box__field--wrapper`) for the Filter Tag and the trigger Button.
- `onFocus` and `onBlur` handlers attached to the wrapper to apply a focus outline when the inner button is focused/blurred. 
- Styles for the new wrapper component, which mimics the filterable styles. 
- Keyboard handlers to capture `escape` presses inside `MultiSelect`, `FilterableMultiSelect` and `Combobox`

**Changed**

- The trigger button and `ListBox.Selection` (the filter tag) are now adjacent siblings under the new wrapper, rather than the filter tag being a child of the trigger button.
- Adjusted some styles based on the new structure.
- `ListBox.Selection` (the `x` or filter `x`) no longer is in the tab order, and events are captured by the element itself. 

#### Testing / Reviewing

- Open the `MultiSelect` story and select an item. Run the Accessibility Checker and ensure no violations are found.
- Compare with the latest deployed storybook and ensure the component functions the same and there are no regressions.

**Multiselect**:
Open and select an item with the keyboard. One `esc` press should close the menu. The second `esc` press should clear the selection.

**FilterableMultiselect**:
Open and select an item with the keyboard. One `esc` press should close the menu AND **clear** the input. The second `esc` press should clear the selection.

**ComboBox**:
Open and select an item with the keyboard. One `esc` press should close the menu AND **retain** the input. The second `esc` press should clear the input.

### CODE REVIEW

**Review by alisonjoseph — APPROVED** [review]
Tested everything locally, LGTM!

**Review by andreancardona — APPROVED** [review]
tested and looks good!

**Comment by tw15egan** [comment]
Going to wait for #13144 before merging

**Review by tay1orjones — APPROVED** [review]

**Comment by tw15egan** [comment]
@alisonjoseph @andreancardona @tay1orjones I had to make some style changes once the Typescript PR merge conflict was resolved. I had to make some tweaks to Fluid Multiselect and the invalid styles, so if you could take a glance at it, let me know if you see any style issues in the various states.

**Review by alisonjoseph — APPROVED** [review]
LGTM!

**Review by tay1orjones — APPROVED** [review]

**Pull request merged**
