### PR TITLE
style(selectable-tile): use checkbox icon instead of round checkmark

### PR DESCRIPTION
**Pull request by janhassel**
The `RadioTile` and `SelectableTile` components are great to give more details or visual cues to multi- and single-select options. However, since both share the same visual style, it can be hard for users to figure out whether they're dealing with a multiselect or a singleselect until they interact with it and observe if other tiles in the same group change or not.

This PR updates the icon for selectable tiles to (1) always be visible and (2) change to an empty checkbox icon (when unselected) and a filled checkbox (when selected).
The radio tile style stays the same.

image

image

#### Changelog

**Changed**

- Replaced checkmark icon with `CheckboxCheckedFilled16` for `SelectableTile`
- When unselected, the icon in a `SelectableTile` is still shown but changes to `Checkbox16`

### CODE REVIEW

**Comment by tw15egan** [comment]
This makes sense to me, but want @carbon-design-system/design to give the go-ahead since this will require a kit update as well 👍🏻

**Review by joshblack — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]
LGTM pending design signoff 👍 ✅

**Comment by joshblack** [comment]
bump @thyhmdo when you have a sec!

**Comment by thyhmdo** [comment]
@janhassel Hello there, I don't think it would make sense to let users hover to see the checkbox here, I imagine they'd still be confused if it's single or multi-select. The multiselect tile isn't obvious enough but I think just changing the icon shape doesn't really solve the problem here. Can you share some visual examples in this context? 

1. Thinking showing all the checkboxes upfront may help eliminate that confusion
2. Having some support text to let users know what they can single or multi-select here.

**Comment by janhassel** [comment]
@thyhmdo Apologies for the long delay!

Good point, it might still not solve all the confusion.
Due to confidentiality I can't post any example screenshots here but I can send you some via Slack if you're interested (just ping me at jan.hassel).

One key difference between checkboxes and radio buttons I see is that usually a radio button group has one option selected by default (although I think this is not forced). In that case, users could associate a group without any selection with checkboxes and as soon as a group has an option selected, the icon makes it clear.

I'm also open to show a reduced icon on unselected tiles if that's something that you folks woudl support. I just hope it doesn't create too much visual clutter.

**Comment by thyhmdo** [comment]
@janhassel hey Jan, no worries, just Slacked you, let me know

**Comment by janhassel** [comment]
After talking with @thyhmdo, we agreed that showing empty checkbox icons for unselected multi-select tiles will help the user much more to understand whether they're dealing with a multi-select or single-select group. The radio tile style is not affected by this.

I updated the original PR description to reflect this as well.

**Review by thyhmdo — APPROVED** [review]
Good discussion with @janhassel on this!

**Comment by tw15egan** [comment]
Thanks, @thyhmdo for talking this over with @janhassel!

Jan, the PR looks great, just seeing an issue with disabled multi-select tiles

Screen Shot 2021-04-27 at 10 09 09 AM

**Review by tw15egan — CHANGES_REQUESTED** [review]
Just need to address disabled states

**Comment by janhassel** [comment]
@tw15egan Thanks for noticing that! Should be fixed now 👍

**Review by tw15egan — APPROVED** [review]
LGTM 👍 ✅

**Pull request merged**
