### PR TITLE
feat(TooltipIcon): port vanilla WCAG 2.1 fixes

### LINKED ISSUE #3811: [React Icon Tooltip] carry over a11y enhancements from Vanilla
A11y changes where made to the HTML structure in Icon Tooltip in this PR. These changes should be applied to the React version

https://github.com/carbon-design-system/carbon/pull/3115

### PR DESCRIPTION
**Pull request by emyarod**
Closes #3811

This PR ports the changes from #3115 to the React package

#### Testing / Reviewing

Ensure the icon tooltip appears and functions properly

### CODE REVIEW

**Review by joshblack — APPROVED** [review]

**Review by elizabethsjudd — APPROVED** [review]
Thanks for porting over these changes to React @emyarod!

**Review by tw15egan — APPROVED** [review]
🎉👍✅

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thank you for taking this @emyarod!

**Review by laurenmrice — DISMISSED** [review]
The icon tooltip is interacting correctly but just double check its matching these specs below: The vertical spacing right now seems a little tight
Artboard

**Comment by emyarod** [comment]
looks like the top and bottom padding was 2px instead of 3px (carried over from the existing styles https://github.com/carbon-design-system/carbon/pull/2781/files#diff-93734be0784e9530b6d14a7b03b0d352L54), it should be fixed now

**Review by aagonzales — APPROVED** [review]
Looks like the padding has been updated 👍

**Pull request merged**
