### PR TITLE
Revert "fix(dropdown): state disabled background color"

### PR DESCRIPTION
**Pull request by tw15egan**
Reverts carbon-design-system/carbon#7461

### CODE REVIEW

**Comment by tw15egan** [comment]
This is causing bugs with hover states on a `disabled` `light` dropdown: https://deploy-preview-7461--carbon-components-react.netlify.app/?path=/story/dropdown--playground

**Review by emyarod — COMMENTED** [review]
is there any additional context to this change and #7461? before I reviewed the original PR, it was approved and merged but now it's being reverted?

**Comment by tw15egan** [comment]
Hadn't checked that specific variant (`light` + `disabled` ) and it came up when reviewing #7466 . I've recommended that all of these PR's should be tied to specific issues before creating PR's

**Review by emyarod — APPROVED** [review]
oh I see, yeah just wasn't sure what was happening based on PR descriptions and no associated tickets

**Review by joshblack — APPROVED** [review]

**Pull request merged**
