### PR TITLE
fix(HeaderMenu): re-enabled links in submenu

### LINKED ISSUE #4641: <HeaderMenuItem /> href broken when it is a child of <HeaderMenu />
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

As in [React Storybook - UI Shell header base with navigation](http://react.carbondesignsystem.com/?path=/story/ui-shell--header-base-w-navigation) described, i've got a list of multiple `<HeaderMenuItem>` inside a `<HeaderMenu>`. Each of the `<HeaderMenuItem>` got a href, that points to an external URL (e.g. https://www.ibm.com). The linked rendered is also correct. 

Then i left clicked the `<HeaderMenu>` and a drop down opens with all the `<HeaderMenuItem>` defined. 

Now the problem:
**When _left clicking_ one of them the drop down closes and nothing happens.**

Interestingly when _right clicking_ one of the items and opening it in a new window it works. 
Also using only a `<HeaderMenuItem>` that is not wrapped in a `<HeaderMenu>` doesn't lead to this bug. Clicking such an item opens the URL as expected.

> Is this issue related to a specific component?

Related to the UI Shell: `<HeaderContainer>` / `<Header>` / `<HeaderMenuItem />` / `<HeaderMenu />`

> What did you expect to happen? What happened instead? What would you like to
> see changed?

**Problem:** When _left clicking_ one of the children of the `<HeaderMenuItem >`, the drop down closes and nothing happens.
**Expected:** The given URL in the `href` should be opened.

> What browser are you working in?

Chrome
Firefox

> What version of the Carbon Design System are you using?

    "carbon-components": "^10.7.3",
    "carbon-components-react": "^7.7.3",

## Steps to reproduce the issue

1. Step one
Open [CodeSandbox bug example](https://codesandbox.io/s/codesandbox-ghxnn?fontsize=14)
2. Step two
Either click the hamburger icon, open `Link 2` and click its `Sub-link 1` or resize the window so that the items appear in the navigation bar and open `Link 2` and click its `Sub-link 1`.
Nothing will happen.
3. Step three
Click the `Link 1`, see that the URL gets opened as it should.

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #4641.

#### Changelog

**Changed**

- `event.preventDefault()` in the `click` event handler of `<HeaderMenu>` now only runs if the `<HeaderMenu>` itself is clicked on, not on sub-menus.

#### Testing / Reviewing

Testing should make sure `<HeaderMenu>` is not broken.

### CODE REVIEW

**Comment by tw15egan** [comment]
Doesn't look like it is coming from this PR, but getting this console warning now when reviewing

Screen Shot 2020-02-07 at 12 19 13 PM

If it is a larger fix we can move it to a separate PR

**Comment by asudoh** [comment]
@tw15egan You are right that the warning doesn't have to do with this change, but good catch. Fixed.

**Review by emyarod — APPROVED** [review]
looks good to me, submenu links are functioning correctly now

**Review by tw15egan — APPROVED** [review]
LGTM, thanks for taking care of the other issue as well 👍 ✅

**Pull request merged**
