### PR TITLE
fix(dropdown): broken forwardRef binding

### LINKED ISSUE #7269: Broken forwardRef in Dropdown/Multiselect
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.

Binding ref to a Dropdown or Multiselect always returns null/undefined

> Is this issue related to a specific component?

- [x] `Dropdown`
- [x] `Multiselect`
(Could be more)

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Get the actual ref of the component

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

- `carbon-components` 10.23.2
- `carbon-components-react` 7.23.2

## Steps to reproduce the issue

1. Add Dropdown
2. Bind ref
4. useEffect to read ref
3. Get undefined

https://codesandbox.io/s/hidden-glade-mqueu?file=/index.js

## Additional information

image

### PR DESCRIPTION
**Pull request by ConradSchmidt**
Closes #7269

Put ref prop at the end, so that it is not overwritten by other props.

#### Changelog

**New**

**Changed**

- fixed broken forwardRef for dropdown and multiselect

**Removed**

#### Testing / Reviewing

1. Add ref to dropdown/multiselect
e.g. in the story:
```js
  const ref = createRef();
  useEffect(() => {
    console.log(ref);
  }, [ref]);
...
<MultiSelect ref={ref} ...
```
2. Open console and wait for `{current: null}`
3. Apply purposed fix
4. Open console and wait for `current: button#downshift-5-toggle-button.bx--list-box__field}`

### CODE REVIEW

**Comment by ConradSchmidt** [comment]
Is there a reason why the ref is bound to the button? I guess the dropdown (container) itself would be a better candidate.

**Comment by joshblack** [comment]
For the `ref` placement itself it is likely on the button to help with focus management (e.g. a consumer can programmatically focus the button).

Since the `getButtonProps` helper adds in a `ref` from downshift, will we need to merge the two refs potentially? 👀

**Comment by ConradSchmidt** [comment]
How should this approach this? Options I see:
1. leave it like this (I didn't experienced different behaviour)
2. use the wrapper container (different element) as ref
3. try to merge refs (no clue how :D)
4. ?

**Comment by joshblack** [comment]
Great question @ConradSchmidt! I think you can use the `mergeRefs` helper that we have: https://github.com/carbon-design-system/carbon/blob/f1c92af3f40585631d8450a4aa381d121dc2c797/packages/react/src/tools/mergeRefs.js

I was trying to dig into that `getToggleButtonProps` method real quick over on downshift but I couldn't find where it was setting `ref`. Would you happen to have a link handy? 👀

**Comment by ConradSchmidt** [comment]
@joshblack like this: https://github.com/carbon-design-system/carbon/pull/7270/files#diff-9712440dfce10e10be2619b0921a1ba53e775f5d864aecad652354f4e4d198b1R183?
I can not really verify if this actually works, because even when I overwrite the downshift ref it is working fine. The merging works for the passed in ref, which is a good sign.

**Comment by ConradSchmidt** [comment]
I guess I stop the package installation here, maybe @joshblack can take care of this

**Comment by joshblack** [comment]
Hey @ConradSchmidt! So sorry about the delay, I pushed up some changes that I _think_ reflect what you were going for, let me know if that works!

**Comment by andreancardona** [comment]
I still see a failing CI :(

**Comment by joshblack** [comment]
@andreancardona should be updated now!

**Review by joshblack — APPROVED** [review]

**Comment by yuecchen** [comment]
which version this fix will be go into? 

or is there any workaround we can do it overcome this issue?

**Review by andreancardona — APPROVED** [review]
looks good!

**Pull request merged**
