### PR TITLE
feat(text-input): add height variations to text input

### LINKED ISSUE #5071: [text input] add 48px and 32px size options
Since we are already doing these other sizes for dropdown we should make a 48px and 32px size for the text input component. 

-------------------------------------------------------------------------------------------------
Screen Shot 2020-01-16 at 11 29 20 AM

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5071

Adds height variations to `TextInput` component. 
- `small`
- `` (default)
- `large`

#### Changelog

**New**

- New `size` prop on `TextInput`, with a default of ``
-  `.#{$prefix}--text-input--large` and `.#{$prefix}--text-input--small` classes
- Size knob in storybook

#### Testing / Reviewing

Change the size of the `TextInput` via the knob in the storybook

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @tw15egan for your quick change!

**Review by emyarod — APPROVED** [review]
looks good to me, should these variants exist for the password input as well?

**Comment by tw15egan** [comment]
@emyarod added in support for the password fields as well

**Review by jeanservaas — APPROVED** [review]
Hey @asudoh this change looks good and I will approve.

but @laurenmrice and i were wondering what the effort level would be to change the names of these field height sizes... "Extra large" "Large" and "Small" does not really make sense in the scheme of our system. "Large" "Default" and "Small" or something like that would make more sense... 

also  we noticed that other components like Data table are using a different naming convention for field heights: "tall" "short" and "compact." It would be nice to streamline all of this stuff.

**Comment by tw15egan** [comment]
@jeanservaas I can change these to be `small` and `large`, with the default being `default` before we merge this in. The `dropdown` updates can be made in a separate PR

**Pull request merged**
