### PR TITLE
[RFC] add storybook/html example

### PR DESCRIPTION
**Pull request by joshblack**
Noticed that the latest alphas of storybook have support for `storybook/html` 🎉 !

Figured it might be worthwhile to do an initial example to see what it might be like using it and see what other folks on the team thought. Right now, the story writing itself feels a little awkward but I bet we could add in some helpers to help out here. Our handlebars templates could also be used to generate the HTML needed for components.

Something that is nice here is that the storybook stories themselves can receive a string that it will render, in addition to actual DOM nodes. This means that we can use our JavaScript inside of these examples to create live previews while we're developing 👍 

Given the introduction of storybooks for libraries like Angular and Vue, it might be worthwhile to have everything we support be built off of the same component playground.

Can't wait to hear everyone's thoughts! 🎉

### CODE REVIEW

**Comment by asudoh** [comment]
Thank you for thinking about this topic and composing this proposal! I have considered [`@storybook/html`](https://www.npmjs.com/package/@storybook/html) this a couple of months ago, as I see potential merit of using widely-adopted tools like Storybook, which is, quicker for devs to get used to by involving the bigger community. There are a couple of reasons that made me stay with the custom dev-env approach:

1. While HMR behind Storybook is superior in quick "change - result" dev lifecycle for JS, it's not good for HTML/CSS given both of them have better (faster) ways to build than one in Storybook affecting the WebPack bundle. While it's hardly noticable with this PR with only Accordion story being there, we have seen having WebPack build HTML/CSS greatly slowed us down the lifecycle until we introduced the following changes:
    * HTML: https://github.com/IBM/carbon-components/pull/933
    * CSS: https://github.com/IBM/carbon-components/pull/982
2. The Storybook version with plain HTML support is still in alpha

BTW I have seen you have put several thoughts on Carbon vanilla toolstack, and thank you for this! Given you said that the story writing itself feels a little awkward, I'm interested in hearing what's behind your impression. Going further - Don't hesitate to ping me if you stumbled at any gotchas/questions in the current toolstack! 🙂

**Comment by joshblack** [comment]
Definitely can understand the performance concerns, especially with a project of this size. Was the setup similar that experienced these issues similar to the storybook setup? I bet if we hit some performance problems, like css injection, we could use strategies like only including a components css in a story, that could help mitigate this.

For the second point, definitely is unfortunate that it is still in alpha but definitely would feel comfortable including it for a development-time tool, especially if there is a workable version that we could pin to if we ran into any issues.

> Given you said that the story writing itself feels a little awkward, I'm interested in hearing what's behind your impression.

I meant this only with respect to writing the stories in this PR versus anything in the current project 👍

**Comment by asudoh** [comment]
@joshblack Thank you for giving it further thoughts!

> Was the setup similar that experienced these issues similar to the storybook setup?

Yes.

> I bet if we hit some performance problems, like css injection, we could use strategies like only including a components css in a story, that could help mitigate this.

The topic of quicker "change - result" dev lifecycle is more from this (than the simple performance issue of WebPack bundle’s build); We need a way for developers to quickly see the result of change in her HTML code. We need a way for developers to quickly see the result of change in her Sass code. We used a special SSE of HMR (telling client that it needs reload upon change in Handlebars template) for the former. We replaced Express with BrowserSync’s Connect server for the latter.

**Comment by joshblack** [comment]
Just curious, what was the bottleneck for receiving the HMR updates in the last configuration? The performance note is surprising given that teams do use storybook often for their component development and groups can have a component surface area as large as ours.

**Comment by asudoh** [comment]
@joshblack Good question! It’s from putting JS (WebPack) build in play, though some of them may have cache in place, for any Sass/HTML changes. Handlebars rendering is almost instant, meaning much faster than the WebPack build. Pure `node-sass` build is slightly (around 50% in `carbon-components`) faster than the WebPack build.

**Comment by joshblack** [comment]
Totally, just was curious what was the bottleneck in the webpack build time, that's all. The development times we were experiencing earlier this year were very strange given the size of the project, at least when comparing to other products that had more files in their dependency graph.

**Comment by asudoh** [comment]
I see - Thank you for clarifying @joshblack! As you may know `@storybook/html` has a similar issue given those facts, given WebPack is the only tool for the “code change - result” lifecycle, though we may optimize our WebPack build some as you alluded. AFAIK Storybook is optimized for AJAX libraries whose main content of development is JavaScript. For `carbon-components`, the main content of development is Sass/HTML, though there are some JavaScript.

**Comment by asudoh** [comment]
BTW to re-iterate, please don't hesitate to ping me if you have any questions/thoughts on how our dev env (should) work! Though I didn't see Storybook move compelling contemplating different factors (dev lifecycle, dev engagement, dev requirement match, flexibility, publishing, etc.) with current dev env, but understanding where your thoughts in this PR came from will definitely help determine where our toolstack should go in future.

**Pull request closed without merging**
