### PR TITLE
fix(tabs): update tab styles

### LINKED ISSUE #5467: [Tabs]: Design kit tabs do not match live code tabs
## What package(s) are you using?

- [x] `carbon-components`
- [x] `carbon-components-react`

## Detailed description

The tab in sketch design kit does not match the live coded tab--specifically the space from the baseline of the text to the top of the underline and both of the enabled and selected underline heights.

image
_This image is showing: Current (code), align:center, align:bottom, line-height:26px, design kit component_

Originally i thought it was because the text wasn’t aligned center vertically within the text box, but when I tried it out in code where i changed `display: flex`, `align-items: center`, and changed the border bottom from 3 px (live code) to 2 px (design kit), it still doesn’t match. 

> What browser are you working in?
- I am using `Google Chrome Version 80.0.3987.122`. Devs are using `Chrome` & `Firefox`.

> What version of the Carbon Design System are you using?
- I am using Carbon Design System version 10.9.0 design kit.
- Devs are using `carbon-components: 10.9.3` and `carbon-components-react: 7.9.3`

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?
- An important release date to keep in mind for `Watson Studio on CP4D 3.0` is **March 17**.

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/5467

Updates styles for `Tab` component. Tab type styles were already using `productive-heading-01` and `body-short-01`.

@laurenmrice how did we want to go about getting exactly 8px of space between? We have a padding-bottom of `8px`, but since the text is `14px` with an `18px` `line-height`, it's not going to sit on the baseline. Would you rather set the `line-height` to `14px`, or remove some of the bottom padding?

#### Changelog

**Changed**

- Changed tab link `border-bottom` to `2px`, from `3px`
- Changed tab link `padding-bottom` to `4px`, from `8px`

#### Testing / Reviewing

Make sure `Tab` styles match the spec

### CODE REVIEW

**Comment by laurenmrice** [comment]
I would rather remove some of the bottom padding instead of changing line height.

**Review by joshblack — APPROVED** [review]

**Comment by tw15egan** [comment]
@laurenmrice removed some of the padding (dropped it from `$spacing-03` to `$spacing-02`) so let me know if that looks good 👍

**Review by aledavila — APPROVED** [review]

**Review by dakahn — APPROVED** [review]

**Comment by laurenmrice** [comment]
I think we can still have the spacing-03 token. It seems to be aligning with the spec better than having the spacing-02.

**Comment by tw15egan** [comment]
@laurenmrice reverted the padding changes, the preview is rebuilding and should be ready in a few minutes 👍

**Review by laurenmrice — CHANGES_REQUESTED** [review]
Spacing looks great 🙌🏻. Ok last thing, I think we should update the selected blue bar to use `interactive-04` token , it is showing up wrong in the dark themes. Then we should be good to go!

**Comment by tw15egan** [comment]
@laurenmrice done! 🏄

**Review by laurenmrice — APPROVED** [review]
looks good, thanks TJ! 🙌🏻

**Pull request merged**
