### PR TITLE
refactor: Added TypeScript types to SkeletonIcon

### LINKED ISSUE #13574: Add TypeScript types to SkeletonIcon

### PR DESCRIPTION
**Pull request by amanlajpal**
Closes #13574

Added Typescript types to SkeletonIcon Component

Changelog

New

- Renamed file extension to .tsx
- Added types for the component props
- Added non-null assertion on className

Changed

n/a

Removed

- PropTypes and its import statement

Testing / Reviewing

You can check this by confirming that there are no errors when:

building
creating a component that uses the SkeletonIcon and testing which props are valid/invalid

SkeletonIcon

### CODE REVIEW

**Comment by amanlajpal** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by amanlajpal** [comment]
recheck

**Comment by amanlajpal** [comment]
I have read the DCO document and I hereby sign the DCO.

recheck

**Comment by amanlajpal** [comment]
I have read the DCO document and I hereby sign the DCO.

**Comment by amanlajpal** [comment]
recheck

**Comment by amanlajpal** [comment]
recheck

**Comment by amanlajpal** [comment]
> I have read the DCO document and I hereby sign the DCO.

I have read the DCO document and I hereby sign the DCO.

**Comment by tw15egan** [comment]
@amanlajpal it seems like your local git config has a different user associated with it. You should update that to match your username on github

**Comment by amanlajpal** [comment]
I think, I should close this PR here and open a new PR for the same

**Comment by amanlajpal** [comment]
@tw15egan  Please guide me from here, as per your suggestion I have changed my email in the git config and performed a git rebase to correct the author email, but now I can see that this old commit is still present with a new commit.

**Pull request closed without merging**
