### PR TITLE
 feat(eslint): add eslint-config-carbon

### PR DESCRIPTION
**Pull request by joshblack**
Add private package `eslint-config-carbon` with two entrypoints: `index.js` and `vanilla.js` to support the various projects in the monorepo.

#### Changelog

**New**

- top-level `.eslintignore` file

**Changed**

- `components` now uses `eslint-config-carbon` from monorepo
- `react` now uses `eslint-config-carbon` from monorepo
- `yarn lint` is now included in `ci-check`

**Removed**

### CODE REVIEW

**Comment by asudoh** [comment]
Any reasoning for JSDoc format change?

**Review by emyarod — COMMENTED** [review]
just wondering, is there a reason for all of the jsdoc changes? I thought the `Object` param type referred to the actual `Object` constructor

**Comment by joshblack** [comment]
@emyarod they talk about it a bit in: https://github.com/gajus/eslint-plugin-jsdoc/#check-types

> To make things more confusing, there are also object literals and object Objects. But object literals are still static Objects and object Objects are instantiated Objects. So an object primitive is still an object Object.

> However, Object.create(null) objects are not instanceof Object, however, so in the case of this Object we lower-case to indicate possible support for these objects.

> Basically, for primitives, we want to define the type as a primitive, because that's what we use in 99.9% of cases. For everything else, we use the type rather than the primitive. Otherwise it would all just be {object}.

**Review by jnm2377 — APPROVED** [review]

**Comment by asudoh** [comment]
Given `eslint-plugin-jsdoc` is brought up, it seems to prefer `@returns` over `@return`?

**Comment by joshblack** [comment]
@asudoh yeah, ended up adding a rule to alias `@returns` -> `@return` (similar to augments): https://github.com/carbon-design-system/carbon/pull/2986/files#diff-e1c8a6f1d1805010adea9d8ad82d0c45R62

**Comment by asudoh** [comment]
Any reason for such alias? I thought we have been using `@returns` over `@return`.

**Comment by joshblack** [comment]
Ah, when linting it was changing `@return` -> `@returns` and adding more to the diff. Can definitely revert 👍

**Comment by asudoh** [comment]
If we can revert it'd be great, from a couple of reasons; In this way we can reduce a custom rule, and vanilla codebase has always used `@returns` over `@return`.

**Comment by joshblack** [comment]
On it 👍

**Comment by joshblack** [comment]
Done 👍

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Pull request merged**
