### PR TITLE
feat(web-components): migrate web components to the monorepo

### LINKED ISSUE #11877: [carbon web components]: update build process
Update build process for `@carbon/web-components` to more closely align with `@carbon/react`.

```[tasklist]
### Tasks
- [x] remove `gulp` builds - prefer `rollup` instead (https://github.com/carbon-design-system/carbon/issues/17167)
- [x] cleanup unnecessary project files (yarn.lock, .yarnrc.yml, percy.json, etc)
- [x] remove unnecessary package deps and/or ensure shared deps (with Core) are the same version
```

### LINKED ISSUE #17167: [carbon web components]: move `@carbon/web-components` to Carbon monorepo
Migrate the `@carbon/web-components` package to the Carbon monorepo with full history in tact.

```[tasklist]
### Tasks
- [x] add publishing steps to Core workflows
- [ ] https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11877
```

### PR DESCRIPTION
**Pull request by kennylam**
Closes #17167 
Closes [#11877](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/issues/11877)

This PR migrates `@carbon/web-components` into the Carbon monorepo.

#### Changelog

**New**

- `packages/web-components`
- actions to deploy `@carbon/web-components` latest storybook and to publish the CDN artifacts in Cloud 

#### Testing / Reviewing

- go to `web-components` package, build locally, and run storybook

### CODE REVIEW

**Comment by tay1orjones** [comment]
If we're running into issues with yarn hardened mode we could probably turn it off for all CI checks except `dedupe`. The [docs](https://yarnpkg.com/features/security#:~:text=If%20your%20CI%20pipeline%20runs%20multiple%20jobs%2C%20we%20recommend%20disabling%20the%20hardened%20mode%20in%20all%20but%20one%20of%20them%20so%20as%20to%20limit%20the%20performance%20impact.) support the idea:

> If your CI pipeline runs multiple jobs, we recommend disabling the hardened mode in all but one of them so as to limit the performance impact.

**Review by emyarod — COMMENTED** [review]
saw a couple things on the local storybook:

icon only content switcher looks broken

image


it looks like the AISkeleton stories aren't loading

image

**Comment by ariellalgilmore** [comment]
Noticing the cdn style page helper looks a bit odd
Screenshot 2024-09-20 at 9 06 26 AM

**Comment by annawen1** [comment]
> saw a couple things on the local storybook:
> 
> icon only content switcher looks broken
> 
> image
> it looks like the AISkeleton stories aren't loading
> 
> image

Should be fixed now!

**Comment by ariellalgilmore** [comment]
compared to https://web-components.carbondesignsystem.com/?path=/story/experimental-sidepanel--slide-over:
the button should be in the center
Screenshot 2024-09-20 at 9 14 04 AM

the selection stories are all misaligned just for ai with data-table: https://web-components.carbondesignsystem.com/?path=/story/experimental-slug-datatable--column-slug-with-selection-and-expansion
Screenshot 2024-09-20 at 9 14 16 AM

radio button spacing looks off: https://web-components.carbondesignsystem.com/?path=/story/components-radio-button--playground

Screenshot 2024-09-20 at 9 16 35 AM


when clickinig on the batch actions here you can see a toolbar popup:https://web-components.carbondesignsystem.com/iframe.html?args=&id=components-datatable-batch-actions--default&viewMode=story but not in this local one. This was also brought up recently in slack: https://ibm-studios.slack.com/archives/CL83LMKSA/p1726681493924229
Screenshot 2024-09-20 at 9 18 28 AM

**Comment by annawen1** [comment]
All the issues (except for the sidepanel - that one is weird where if I refresh it's centered) should be resolved now!

Also trying to figure out why the storybook title isn't showing up with the package name and version - but we can handle later

**Review by ariellalgilmore — APPROVED** [review]

**Review by emyarod — APPROVED** [review]
thanks for the fix, looks good to me!

**Review by tay1orjones — APPROVED** [review]
LGTM! 🎉

**Pull request merged**
