### PR TITLE
fix(copy-button): replace copy button with one for code snippet

### LINKED ISSUE #3208: [Copy button] Tooltip style wrong, icon wrong
### Two bugs found

- [ ] tooltip styling is wrong. Ref https://github.com/carbon-design-system/carbon/issues/3202 for spec
- [ ] icon in button is v9. should be updated even if we don't expose this component in website
- [ ] it should be using the `copy` icon instead of `add`
- [ ] it should be an icon only style button (no text)

image

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #3208.

#### Changelog

**Changed**

- Replaced the markup of copy button with the one for code snippet.

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
just one thing, should we address the tooltip positioning in this PR or separately?

image

**Comment by asudoh** [comment]
@emyarod Good point, I think we should address that separately.

**Review by emyarod — APPROVED** [review]
looks good to me pending design review, let's address the tooltip alignment issue separately

**Review by aagonzales — CHANGES_REQUESTED** [review]
It looks like the icon is off center vertically by 2px. The tooltip is also showing up a little off centered as well. 

image

**Comment by aagonzales** [comment]
Oh oops I didn't read the other reviews. Would the icon alignment be part of that other issue?  (in addition to the tooltip alignment.

**Comment by asudoh** [comment]
Thank you for reviewing @aagonzales - I think icon alignment will be part of that other issues, too, given I can see the same issue at http://react.carbondesignsystem.com/?path=/story/copybutton--default. This PR focuses on aligning vanilla markup to React given that's all (or at least most) of what #3208 effectively requests for.

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
