### PR TITLE
fix(ProgressIndicator): fix focus style outline (#11773)

### LINKED ISSUE #11773: [Bug]: Progress indicator focus style outline wrong
### Package

@carbon/react

### Browser

Chrome

### Package version

Latest

### React version

Latest

### Description

Progress indicator > Interactive variant is showing wrong focus state styling: 
https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive
Jul-11-2022 19-27-07
Expecting below based on [Style tab spec](https://carbondesignsystem.com/components/progress-indicator/style#interactive-states): 
image

### Reproduction/example

https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive

### Steps to reproduce

Go to link, use keyboard to focus the steps.
https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

### PR DESCRIPTION
**Pull request by hannelevaltanen**
Closes #11773

This fixes the ProgressIndicator focus style to follow the [style guide](https://carbondesignsystem.com/components/progress-indicator/style/#interactive-states). 

**Default**
Screenshot 2022-09-11 at 11 53 59

**Focus when using keyboard**
Screenshot 2022-09-11 at 11 52 52

**Hover**
Screenshot 2022-09-11 at 11 52 22

**Clicked**
Screenshot 2022-09-11 at 11 53 38

#### Changelog

**Changed**

- Changed the progress step button to focus the label only

**Removed**

- Removed unnecessary focus styles

#### Testing / Reviewing

- Ensure this PR's ProgressIndicator Interactive component has states as above (hover, focus when using keyboard, hover, clicked)
- Check the current way for focus style at https://react.carbondesignsystem.com/?path=/story/components-progressindicator--interactive
- Web Components has a focus style as an underline. However, Is the outlined style still the right way to focus these buttons? https://web-components.carbondesignsystem.com/?path=/story/components-progress-indicator--default

### CODE REVIEW

**Comment by hannelevaltanen** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tw15egan — APPROVED** [review]
This looks great. Thanks for contributing! 🎉

**Review by tay1orjones — APPROVED** [review]
Fantastic, thank you!

**Comment by tw15egan** [comment]
cc @thyhmdo does this focus state look correct?

**Comment by thyhmdo** [comment]
Everything looks correct, except the Clicked state.
Text and underline (or text decoration?) change to Black on the active state when the step is a link, meaning that you can go back and forth.
 We already have this in our storybook so just want to confirm this.

**Comment by thyhmdo** [comment]
Here's the spec from Lauren. Active or when selected, the underline should also be 1px instead

image

**Comment by hannelevaltanen** [comment]
Thank you all and thank you @thyhmdo for the spec! I can fix the :active state, so only 1px underline and $text-primary (#161616) token for the colors.

**Pull request merged**
