### PR TITLE
feat(react): update components to use next icons

### LINKED ISSUE #8903: Update codebase to use icons from `@carbon/icons-react/next`
After the issues identified in: https://github.com/carbon-design-system/carbon/issues/8811 are addressed, we should run our codemod across the project to update our icons from `@carbon/icons-react` to `@carbon/icons-react/next`.

This issue will involve:

- Running the codemod on our project
- Verifying icons render as expected
- Figuring out what to do for things like Storybook where we may reference icons and don't want people to use `@carbon/icons-react/next` diretcly

### PR DESCRIPTION
**Pull request by joshblack**
Closes #8903 

This PR updates our components to use the new icons after finishing the (hopefully) last render issue problems that we ran into. This does not update public-facing stories, that work will be done in either our v11 branch or in the `@carbon/react` storybook.

#### Changelog

**New**

**Changed**

- We ran the icons codemod to update the icons in the project from the classic version of the icons to the next version

**Removed**

#### Testing / Reviewing

- First-off, I'm so sorry. This is a long PR 😓 
- Go through the stories in the storybook and make sure that the icons in the stories render as expected

### CODE REVIEW

**Comment by joshblack** [comment]
Just a heads up @laurenmrice, this PR updates our icons under the hood to use our new API so just wanted to bring in a visual review to make sure none of the icons are rendering incorrectly 👀

**Review by dakahn — COMMENTED** [review]
I'm getting an error about having no stories in the preview -- am I doing something wrong?

**Review by tay1orjones — APPROVED** [review]
Icons in stories look good to me 👍

**Comment by tay1orjones** [comment]
@dakahn the deploy preview url sometimes includes `/iframe` at the end. Try removing it to just the base url and it should work.

**Comment by dakahn** [comment]
@tay1orjones whoa wild. noted!

**Review by dakahn — APPROVED** [review]
Seems good 🏄🏽

**Review by laurenmrice — APPROVED** [review]
Looks good to me! ✅

**Comment by tw15egan** [comment]
@joshblack is this good to merge?

**Review by jnm2377 — APPROVED** [review]

**Comment by joshblack** [comment]
@tw15egan I'm definitely torn, visually I think it's good to go but am worried about the types of reports we've seen from us changing component names from under the hood. I'm also worried about what will happen if teams have two separate entry points for icons and what will happen to bundle size 😞  (it's just hard to get good data on t his)

 If people have a strong preference one way or another I could go either way (delay or just merge it in)

**Comment by tw15egan** [comment]
Can always point it to the `next` branch then if we don't want to cause any issues?

**Pull request closed without merging**
