### PR TITLE
Add typescript type definitions to Toggle and ToggleSkeleton

### LINKED ISSUE #12564: Add TypeScript types to Toggle

### LINKED ISSUE #12565: Add TypeScript types to ToggleSkeleton

### PR DESCRIPTION
**Pull request by LuskeyNoah**
Closes #12564 
Closes #12565 

This PR adds typescript type definitions for Toggle and ToggleSkeleton.

#### Changelog

**New**

- `ToggleProps` and `ToggleSkeletonProps` type exports added

**Changed**

- `Toggle` and `ToggleSkeleton` converted to `.tsx`

#### Testing / Reviewing

These changes can be tested and verified by running a fresh `yarn`, `yarn build` and `yarn storybook`. Verify that the behavior in both the Toggle and ToggleSkeleton stories remain unchanged

### CODE REVIEW

**Comment by LuskeyNoah** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by tay1orjones — COMMENTED** [review]
I think this looks alright but it has some conflicts atm

**Review by tay1orjones — APPROVED** [review]
LGTM! Thanks again! 🏆

**Comment by francinelucca** [comment]
Sorry about that @LuskeyNoah looks like this PR got stuck with just one reviewer, can you solve the merge conflicts 🙏🏻 and I'll give second review. thanks!

**Comment by tay1orjones** [comment]
Thanks again for working on this contribution! We’d really like to get this merged but with the current test failures and conflicts it’s not able to. 

If those are resolved in the next few days we can merge, otherwise we’ll close this for inactivity with the option to reopen if work resumes.

**Pull request closed without merging**
