### PR TITLE
chore(styles): update background of bx--body

### PR DESCRIPTION
**Pull request by asudoh**
Refs #2082.

`.bx--body` refers to `$ui-02`, but according to https://github.com/carbon-design-system/carbon/pull/3073#pullrequestreview-250844656 the `<body>` background color seems to be  better with `$ui-background`.

#### Changelog

**Changed**

- `.bx--body` class, using `$ui-background` instead of `$ui-02`.

#### Testing / Reviewing

Testing should make sure the new background color is good.

### CODE REVIEW

**Comment by asudoh** [comment]
Can be tested by the following steps:

1. Open https://deploy-preview-3274--the-carbon-components.netlify.com/component/button--primary.html
2. Open Chrome DevTools
3. Add `class="demo--theme--g100"` attribute to `<html>`
4. Disable `background-color` set by `.demo--container`
5. See if the body has the correct background color

**Review by emyarod — APPROVED** [review]
unable to view the netlify preview but tested locally and it seems to be correct

image

**Review by joshblack — APPROVED** [review]

**Comment by joshblack** [comment]
Would this be a `fix` versus a `chore`?

**Comment by jeanservaas** [comment]
@asudoh 

@shixiedesign may have been more familiar with this issue, but she's out for a bit. 

So @laurenmrice and I have looked at this issue and we're having a hard time understanding where / what this is affecting. What is the class .bx--body affecting? 

So not sure what we'd be approving here. We're still investigating.

**Comment by asudoh** [comment]
Thanks @jeanservaas for asking! `.bx--body` affects body color, body background color and line-height of `<body>` in general, in addition to regular reset styles. This PR changes _only_ the background color.

BTW please don't hesitate to let me know if you need more details on the test script above.

**Review by shixiedesign — APPROVED** [review]
Based on my understanding, this is just updating the variable used in an exiting class. Looks good to me that a class for `<body>` is using `$ui-background`.  

The screenshot @emyarod posted demonstrates that background is using different colors for dark themes, is that right?

**Comment by asudoh** [comment]
Thanks @shixiedesign for reviewing!

> The screenshot @emyarod posted demonstrates that background is using different colors for dark themes, is that right?

You are right!

**Pull request merged**
