### PR TITLE
Increase screen reader a11y for code snippet

### LINKED ISSUE #1531: ♿ AVT3 ♿ Code Snippet - Screen reader accessibility is poor
User tested with latest version of JAWS 2018, Windows 7, Chrome latest version

JAWS screen reader does not announce a code snippet as code and just reads it as text.

_Note: this could be a larger problem with code blocks and screen readers in general and not specific to our implementation, but it's worth noting here for posterity's sake -- and perhaps work can be done to improve this situation_

### PR DESCRIPTION
**Pull request by dakahn**
Closes #1531 

1) Adds a type attribute to the buttons which lets us clean up the labels and in my testing with NVDA cleaned up the screen reader dialogue.

2) Adds a role alert attribute to the "Copied!" notification so it's announced by the screen reader

@snidersd you mentioned in your issue that the `<code>` element wasn't being announced as code in your test. I can add an `aria-label="inline code snippet"` etc -- but that seemed redundant to me? What do you think?

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM :+1: - Thanks @dakahn!

**Review by tw15egan — APPROVED** [review]
LGTM!

**Comment by dakahn** [comment]
We're good to merge this now if we want -- or we can wait and I can add some aria-labelling describing the blocks as code as per @snidersd suggestion. I'm good either way, but I'm tied up right now working on some audit fixes.

**Comment by tw15egan** [comment]
Let's get this fix in, and we can always improve it in the future

**Pull request merged**
