### PR TITLE
Fluid number input skeleton unit test

### LINKED ISSUE #17512: Increase `FluidNumberInput.Skeleton` unit test coverage

### PR DESCRIPTION
**Pull request by irfadkp**
Closes #17512 

This PR adds unit tests for the FluidNumberInputSkeleton component to ensure its proper rendering and functionality. The tests verify that the skeleton displays with the correct classes, supports custom class names, and spreads additional props correctly.

#### Changelog

**Changed**

*  Added Unit tests for FluidNumberInputSkeleton.

#### Testing / Reviewing
* Run the test suite to ensure that all new tests pass.
* Review the tests for clarity and coverage.

#### Additional Notes
* Please let me know if any further modifications are needed or if you have any questions regarding the changes.

### CODE REVIEW

**Review by alisonjoseph — CHANGES_REQUESTED** [review]
Can you fix the spelling of the filename 😄

**Comment by irfadkp** [comment]
> Can you fix the spelling of the filename 😄

Done, Thanks for catching up

**Comment by irfadkp** [comment]
I have read the DCO document and I hereby sign the DCO.

**Review by emyarod — APPROVED** [review]
looks good to me!

**Review by alisonjoseph — APPROVED** [review]

**Pull request merged**
