### PR TITLE
feat(PasswordInput): sync input type prop and state

### PR DESCRIPTION
**Pull request by emyarod**
This PR deprecates `TextInput.ControlledPasswordInput` and adds support for control over the password input field type in the `TextInput.PasswordInput`

this PR includes changes from #8366 so we should review and merge those changes first

#### Testing / Reviewing

Confirm that the controlled password input story which uses `TextInput.PasswordInput` instead of `TextInput.ControlledPasswordInput` functions as expected

### CODE REVIEW

**Comment by joshblack** [comment]
Is this one intended to be fully controlled/uncontrolled or is it more the more hybrid pattern where it has internal state and then if the prop passed in changes it updates?

**Comment by emyarod** [comment]
> the more hybrid pattern where it has internal state and then if the prop passed in changes it updates

the component should now follow this pattern

**Review by jnm2377 — APPROVED** [review]

**Comment by tw15egan** [comment]
Noticed a few issues:

Size variants are causing misalignment with the password icon
Screen Shot 2021-05-12 at 12 55 54 PM


Not seeing any focus styles on the password icon when using keyboard
Screen Shot 2021-05-12 at 12 56 03 PM

**Comment by emyarod** [comment]
these are not regressions and should be addressed separately (the portions of code this PR modifies are unrelated)

**Comment by tw15egan** [comment]
Sounds good!

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
