### PR TITLE
chore(project): update prettier to v2

### PR DESCRIPTION
**Pull request by joshblack**
Update prettier to v2 and format files.

#### Changelog

**New**

**Changed**

- Formatted files with prettier v2
- Updated dependencies for prettier to v2

**Removed**

### CODE REVIEW

**Review by emyarod — COMMENTED** [review]
does this mean we are changing our default rules or should we carry over our existing settings?

**Comment by tw15egan** [comment]
@emyarod IIRC correctly the main change is that parenthesis are always used inside arrow functions. I don't really have a strong preference either way (if anything I think I'd lean towards always having them like this PR adds in).

**Review by tw15egan — APPROVED** [review]

**Comment by joshblack** [comment]
@emyarod yeah, as TJ noted it's that they updated the defaults but our config has stayed the same.

**Comment by emyarod** [comment]
yeah do we want to keep the previous formatting? so this PR would contain the [prettier version upgrade](https://github.com/carbon-design-system/carbon/pull/6196/commits/7a448b706b1399ca17a5801e4f603b5cce0aa5bd) and the necessary config changes to keep formatting the same as before after running `prettier`

**Comment by joshblack** [comment]
@emyarod if you think it'd be helpful, thought it'd be nice to keep them in lock step just so there was one change versus having to add an option for the previous behavior then do a PR to revert that and format.

**Comment by emyarod** [comment]
pretty much my question is are we changing our style rules now?

**Comment by joshblack** [comment]
@emyarod yeah! I think we're just going to use prettier defaults plus our existing config.

**Review by aledavila — APPROVED** [review]

**Pull request merged**
