### PR TITLE
docs(npm): Change TravisCI button to CircleCI button

### LINKED ISSUE #3198: carbon-components NPM page has broken build link
## What package(s) are you using?

- [x] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

On the carbon-components npm page [1], there is a broken link to TravisCI.  
image

My understanding is that the carbon team now uses CircleCI here [2].  I am not sure how to submit a change to the npm page to update the build link.  I would be happy to contribute with some guidance to managing the npm page.

[1] https://www.npmjs.com/package/carbon-components
[2] https://circleci.com/gh/carbon-design-system/carbon

### PR DESCRIPTION
**Pull request by kinueng**
Closes #3198  carbon-components NPM page has broken build link

#### Changelog
**Changed**

Changed the TravisCI `href` to a CircleCI `href`

#### Testing / Reviewing
https://github.com/kinueng/carbon/blob/circleCiLink/packages/components/README.md

### CODE REVIEW

**Comment by kinueng** [comment]
force-pushed to rebase on the `master`

**Review by emyarod — APPROVED** [review]
looks good to me!

**Comment by tw15egan** [comment]
Not sure if this is just GitHubs markdown preview, but I see this when I preview:

Screen Shot 2019-06-27 at 12 24 28 PM

**Comment by kinueng** [comment]
Hi @tw15egan, I think that is GitHub trying to show what was deleted and what was added.  I was confused too.  I ended up just viewing my branch that contains the fix to verify the broken link was removed correctly.
https://github.com/kinueng/carbon/blob/circleCiLink/packages/components/README.md

**Comment by tw15egan** [comment]
Thanks for clarifying!

**Review by tw15egan — APPROVED** [review]
Thanks for updating this 🙂

**Comment by kinueng** [comment]
Verified the fix looks ok on `master`
https://github.com/carbon-design-system/carbon/tree/master/packages/components
image

**Pull request merged**
