### PR TITLE
chore(project): update babel dependencies

### PR DESCRIPTION
**Pull request by joshblack**
Update babel plugins to 7.7.x range where appropriate, also updates related babel plugins.

#### Changelog

**New**

**Changed**

- Update babel plugins to latest
- Update usage of babel cli in React build script as `-q` as an option is no longer supported, it now uses `--quiet` instead

**Removed**

### CODE REVIEW

**Comment by dakahn** [comment]
Looks like the CI is trying to build in offline mode and it can't find a cached version of the newer Babel. How do I get re-run permissions for Circle-CI @alisonjoseph?

**Comment by joshblack** [comment]
@dakahn we only install from offline in CI, just a heads up!

**Comment by dakahn** [comment]
@joshblack So in this case what's the protocol for updating the lockfile?

**Comment by joshblack** [comment]
@dakahn feel free to push to this PR with the updated dependency!

**Comment by joshblack** [comment]
@abbeyhrt @dakahn CI should be green now!

**Review by abbeyhrt — APPROVED** [review]

**Review by tw15egan — APPROVED** [review]

**Pull request merged**
