### PR TITLE
fix(modal): fix modal content padding for regular size

### LINKED ISSUE #4790: [modal] inputs/components should be able to span full width
Currently the modal has a padding-right of 25%. However, this padding-right should only apply to text in a modal and not restrict other components like form inputs and tables. Those should be able to span the full width of the modal container. 

**As-is:**
image

**To-be:**
image

### PR DESCRIPTION
**Pull request by asudoh**
Fixes #4790.

#### Changelog

**Changed**

- A change to ensure "with form" style wins for regular style, for regular size.

#### Testing / Reviewing

Testing should make sure modal is not broken.

### CODE REVIEW

**Review by abbeyhrt — APPROVED** [review]
LGTM! 🎉

**Review by aagonzales — APPROVED** [review]
Thanks for fixing!

**Comment by jz2cao** [comment]
@joshblack 
which version of `carbon-component-react` do we expect to see this change?
thanks

**Comment by joshblack** [comment]
Hi @jz2cao! 👋 I believe it's in `carbon-components@10.9.3`

**Pull request merged**
