### PR TITLE
refactor(pagination): remove unused CSS

### PR DESCRIPTION
**Pull request by emyarod**
This PR will remove a few blocks of unused CSS in the experimental pagination component

Related: https://github.com/IBM/carbon-components-react/issues/1724

### CODE REVIEW

**Review by asudoh — COMMENTED** [review]
Wanted to double-check if `bx--pagination__button-icon` class at https://github.com/IBM/carbon-components/blob/v9.66.3/src/components/pagination/pagination.hbs#L78 is no longer used. Any thoughts @emyarod? Removal of `.bx--pagination__button--no-index` is good to me. Thanks!

**Comment by emyarod** [comment]
@asudoh my guess is those changes were implemented before the icons were updated, because those rules actually break how the icons look or are redundant

**Review by asudoh — APPROVED** [review]
OK thank you @emyarod for explaining this! @lovemecomputer does this change look good to you...? Thanks!

**Review by aledavila — APPROVED** [review]

**Review by lovemecomputer — APPROVED** [review]
@emyarod thanks!! i think when we were updating this, we also had to put in a PR to update an elements/icon package, and i must've missed this detail in while sorting that out

**Pull request merged**
