### PR TITLE
chore(project): remove or update old files

### PR DESCRIPTION
**Pull request by joshblack**
General project clean-up with some files that are either no longer needed, or needed to be updated after our release.

### CODE REVIEW

**Review by asudoh — APPROVED** [review]
LGTM 👍 - Thanks @joshblack!

**Review by vpicone — APPROVED** [review]

**Comment by emyarod** [comment]
can we revert some of the .gitignore changes? the top level gitignore isn't detected if we open an individual package in an editor

**Comment by joshblack** [comment]
@emyarod is this causing files to be mistakenly checked in?

**Comment by emyarod** [comment]
@joshblack no it's interfering with file searching/opening because the files aren't technically included in the local gitignore if you only open the individual packages in the editor (as opposed to the monorepo)

**Comment by joshblack** [comment]
Got it, would the recommendation be to have gitignore files per-package then? This feels like a problem with any sub-folder that one may directly open up (for example, the examples folders in some packages)

**Comment by emyarod** [comment]
we can just add back the ignore rules for auto generated files and directories like `lib`, `es`, `umd`, `css/**`, etc

**Comment by joshblack** [comment]
@emyarod are you talking specifically about the `components` package folder? Wouldn't this also apply to other package folders as well? That's why I brought up the gitignore per-package as that would seem to address this in each sub-folder.

**Comment by emyarod** [comment]
@joshblack yeah this would apply to all package folders

**Comment by joshblack** [comment]
Got it, this feels like something that would happen for any sub-folder then, not just our package folders. Are there editor-level settings that could be set if one is choosing to access a sub-folder and wants to exclude these files?

**Comment by emyarod** [comment]
there are, but is there any reason for not modifying the package gitignores to exclude generated directories? that way the editor can continue to just follow the gitignore by default instead of requiring the user to manually include and exclude patterns based on the project they're working in

**Comment by joshblack** [comment]
@emyarod this is why I brought up other sub-folders, why would we want to stop at just package folders if this problem would occur at any location in the sub-tree?

**Comment by emyarod** [comment]
@joshblack because the packages already contain gitignores so we're just extending them. the search-related issues with ignored files would be more common at the package root level than package subfolders so I'm not suggesting we address this issue for package subfolders

**Comment by joshblack** [comment]
@emyarod right, but then we're solving this for a particular use-case/setup that is tied to how a particular editor behaves, and doing this against how the underlying tool (git) is designed to be used (supporting nested gitignore)

**Comment by emyarod** [comment]
@joshblack I'm not following, what's the reason for leaving the package gitignores but only removing some of the ignored directories?

**Pull request merged**
