### PR TITLE
test(NumberInput): add @avt tests

### LINKED ISSUE #14335: Add AVT coverage for `NumberInput` states: Hover/Active/Visited state

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/14335

Adds in `AVT` tests for `NumberInput` including keyboard navigation + a11y checks

#### Changelog

**New**

- `NumberInput-test.avt.e2e.js`

**Changed**

- Moved a11y tests to `AVT` file

#### Testing / Reviewing

Ensure test coverage is sufficient

### CODE REVIEW

**Review by tay1orjones — APPROVED** [review]
Thanks for adding the keyboard nav tests, too! 👍

**Review by guidari — COMMENTED** [review]
Hey @tw15egan!! The code looks good to me!

Just two comments:

- The first two tests are being skipped, is there a reason for that?

- Can we add a validation for invalid input, if the user types something that exceeds the max attribute? If that makes sense
For example:
```
  // Invalid value for input
    await input.type('101');
    await expect(input).toHaveAttribute(
      'aria-describedby',
      'carbon-number-error-msg'
    );
```

Idk if it would work

**Comment by tw15egan** [comment]
@guidari thanks for catching that, had them skipped just while I was testing the keyboard nav code. I unskipped them, and added a test to make sure `data-invalid` is applied if the number is outside the `min`/`max`

**Review by guidari — APPROVED** [review]
🚀

**Pull request merged**
