### PR TITLE
fix(overflow-menu): update trigger's hover color

### PR DESCRIPTION
**Pull request by asudoh**
Refs #3210.

#### Changelog

**Changed**

- The hover color of overflow menu's trigger button.

#### Testing / Reviewing

Testing should make sure our overflow menu is not broken.

### CODE REVIEW

**Review by emyarod — APPROVED** [review]
looks good to me, pending design review

image

image

**Comment by jnm2377** [comment]
I'll defer to design on this one. I am noticing that now, when you select a row and then hover on the overflow menu, there is no noticeable hover difference bc it's the same color as the row (that's what the `$hover-selected-ui` is for). So I'm not sure if overflow menu hover should be this color. I remember discussing this with @designertyler when I was working on data table but we didn't really discuss other options.

**Comment by designertyler** [comment]
We lose the overflow hover state on selected rows now that they are the same color. Is it possible to have a different overflow hover state for when the row is selected?

It's getting lost on selected rows since they are the same color.
Oct-10-2019 15-10-43

**Comment by asudoh** [comment]
@designertyler Thank you for reviewing - Any ideas (e.g. choice of theme token) wrt what the hover color of overflow menu's trigger button on selected rows? CC @shixiedesign

**Comment by designertyler** [comment]
I'd suggest using the row's original selected color for the overflow menu's hover when it's on a selected row. This means the overflow menu's hover goes lighter for the 4 themes. 

Designers chime in if this isn't what we want.

| | White theme | Gray 10 theme | Gray 90 theme | Gray 100 theme |
| --- | --- | --- | --- | --- |
|Selected row's overflow menu hover | gray-20 `#e0e0e0` | gray-20 `#e0e0e0` | gray-70 `#525252` | gray-80 `#393939` |


image

**Comment by asudoh** [comment]
Thanks @designertyler for the updated spec! Fixed.

**Review by designertyler — APPROVED** [review]

**Pull request merged**
