### PR TITLE
feat(Slug): update slug callout styles 

### LINKED ISSUE #15526: Update Slug Callout styles to new spec
Spec:

Image

Image

Image

Image

### PR DESCRIPTION
**Pull request by tw15egan**
Closes https://github.com/carbon-design-system/carbon/issues/15526

Updates the Slug Callout to the new styles 

Dark theme
Screenshot 2024-01-17 at 12 58 02 PM

Light theme
Screenshot 2024-01-17 at 12 57 54 PM

#### Changelog

**New**

- Added a gradient border to the callout. Due to an issue with `border-image` and `border-radius`, I was able to find a workaround by stacking the callout background and the border`linear-gradients` on top of each other and scoping them to either the `padding-box` or the `border-box`. Hats off to CodyHouse and their [blog post](https://codyhouse.co/nuggets/css-gradient-borders#alternative-approach)!

```scss
    background: linear-gradient(
          0deg,
          theme.$slug-callout-aura-start $start,
          theme.$slug-callout-aura-end 50%
        )
        padding-box,
      linear-gradient(theme.$background, theme.$background) padding-box,
      linear-gradient(
          to bottom,
          theme.$slug-callout-border-01,
          theme.$slug-callout-border-02
        )
        border-box,
      linear-gradient(to bottom, theme.$background, theme.$background)
        border-box;
```

- Added styles to simulate border flow around caret. Created using a combination of `::before` and `::after` pseudo-elements with clip-path on the `cds--popover-caret`. [Relevant code](https://github.com/carbon-design-system/carbon/pull/15522/files#diff-8b218ba577d1f8b7bd5f3c071b501f0b058ba00253aa1d1a82dbbbfc8785e2ccR351-R474)
-  new tokens added for callout and caret styles

**Changed**

- `slugCalloutAuraStart` and `slugCalloutAuraEnd` have updated values. `slugCalloutGradientTop` and `slugCalloutGradientBottom` may be able to be removed. Noted in code.
- Adjusted `Popover`/`Toggletip` offset that was causing issues when the alignment was set to `left-bottom` or `left-top`, can be seen in current [storybook](https://react.carbondesignsystem.com/?path=/story/components-toggletip--playground&args=align:left-bottom) deployment (compare to `right-bottom`). 
- Adjusted `border-radius` on the callout from `16px` to `8px`

**Removed**

- Outdated code

#### Testing / Reviewing

Check out any of the `Slug` stories and ensure the callout matches the [spec](https://www.figma.com/file/7eMfOAyRclD4LuDFwRAa3p/Carbon-for-AI-Sketches?type=design&node-id=1368%3A115940&mode=design&t=XzcxFSEVGYuwDJHU-1).

### CODE REVIEW

**Comment by aagonzales** [comment]
@tw15egan oh no those carets do seem like a nightmare with the gradient borders and background. I forgot about that. How terrible is it to have to set unique values for each of those? The size of the container also effects the color density of the background sometimes ... we might need to re-think the caret or its styling.

**Review by aagonzales — COMMENTED** [review]
The internal padding of callout should be 24px instead of 32px now. 

I was also having a hard time inspecting the open callout with inspector but the color of the gradient borders seem off at the bottom. They look more gray than blue, but it seemed like the written code was correct. Do you know what's causing that?
image

**Comment by tw15egan** [comment]
@aagonzales I can play around with the caret and see what I can do. I can always pull the color values from nearby elements and save them as private tokens or something.

The border issue seems to be due to my workaround to get the linear gradient border image working with rounded corners. I have to set a transparent background on the "border", and then lay a gradient over it. Since the second value in the dark theme is at `.25` opacity, its bleeding all the way through and getting the black background. Can we set this to a non-opacity value?

**Comment by tw15egan** [comment]
@aagonzales just pushed up some explorations on what we could do with the caret in the various alignments. I also added a test story with the popover open by default, but getting it to stay open can be a bit finicky. I've had success opening dev tools, refreshing the page, and using the little selector tool to click back in the callout. 

Screenshot 2024-01-12 at 11 59 06 AM


If I right-click the popover to inspect, it closes 🙃

**Comment by aagonzales** [comment]
@tw15egan Oh yeah, I think that could work, except maybe sample the background without the action bar (I think that's the more common scenario).

**Comment by tw15egan** [comment]
@aagonzales I sampled the action bar / without the action bar, and it should use the correct one based on if the action bar is there or not. Let me know if we just want to always use one color though and I can change it

**Comment by aagonzales** [comment]
@tw15egan I think it looks good now! The only small thing that not really important is if we can change the internal padding from 32 to 24 in the example.

**Comment by tw15egan** [comment]
@aagonzales literally just pushed that, same wavelength 🎸💪🏻

**Comment by alisonjoseph** [comment]
Not sure if this is related to this PR, but the slub position is broken for Modal. (seems fine on live site)

https://deploy-preview-15522--v11-carbon-react.netlify.app/?path=/story/experimental-unstable-slug-examples--modal&globals=theme:g10
Screenshot 2024-01-17 at 12 10 26 PM

**Comment by alisonjoseph** [comment]
So cool how you did the gradient/borders 🔥, this all looks good to me other than my comments above.

**Review by tay1orjones — COMMENTED** [review]
In chrome on low res screens the caret can look a bit funky (taken on my old non-retina thunderbolt monitor). There's a small white gap due to it being misaligned or something with subpixel rendering maybe?

Surfaced on https://deploy-preview-15522--v11-carbon-react.netlify.app/?path=/story/experimental-unstable-slug-datatable--column-slug-sort

image

Zooming in even one click (110%) fixes it

image

No issues if the caret is on the right/bottom/left border

**Comment by tw15egan** [comment]
@alisonjoseph what version of Firefox are you on? I know I had to enable a flag when I first started with some of this to get the benefits of the `:has` and `:is` selector, but it should be released and enabled as of `121.0.1`

**Comment by alisonjoseph** [comment]
I'm on `121.0.1 `

**Comment by tw15egan** [comment]
@alisonjoseph Hmm, I don't see the same thing. Is it a specific component/orientation? Or all alignments?

**Comment by alisonjoseph** [comment]
@tw15egan weird I'm only seeing it on this test story, all the others seem fine. https://deploy-preview-15522--v11-carbon-react.netlify.app/?path=/story/experimental-unstable-slug--test

**Review by aagonzales — COMMENTED** [review]
Style-wise everything is looking good! But checking through the components I noticed in the second line of tags the caret is broken. 

image

**Comment by tw15egan** [comment]
@aagonzales it seems like that is an underlying issue with `Popover` when the available screen space is too small to show the popover contents. I've created an issue [here](https://github.com/carbon-design-system/carbon/issues/15566) that should be addressed by https://github.com/carbon-design-system/carbon/issues/14139. For now, I've hidden the pseudo elements I've added for the new callout styles when the screen size is too small and removed a bunch of the redundant `Tag` examples.

@alisonjoseph I'm still not able to reproduce; it may be something with that one simply because I set the `defaultOpen` prop, and it's not calculating properly in Firefox? I don't think `defaultOpen` will be a normal use case. Do you think this is fine for now, and we can tackle this in a separate issue?

**Review by alisonjoseph — APPROVED** [review]
sounds good @tw15egan I'm not too worried about it 👍

**Review by tay1orjones — APPROVED** [review]
🚀

**Review by aagonzales — APPROVED** [review]

**Pull request merged**
